.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_titlescreen_and_loading_8006D34C

dlabel jtbl_titlescreen_and_loading_8006D34C
    /* 230E8 8006D34C E4090780 */ .word .Ltitlescreen_and_loading_800709E4
    /* 230EC 8006D350 D8040780 */ .word .Ltitlescreen_and_loading_800704D8
    /* 230F0 8006D354 6C060780 */ .word .Ltitlescreen_and_loading_8007066C
    /* 230F4 8006D358 F4060780 */ .word .Ltitlescreen_and_loading_800706F4
    /* 230F8 8006D35C 20090780 */ .word .Ltitlescreen_and_loading_80070920
    /* 230FC 8006D360 74090780 */ .word .Ltitlescreen_and_loading_80070974
enddlabel jtbl_titlescreen_and_loading_8006D34C

.align 3
nonmatching jtbl_titlescreen_and_loading_8006D364

dlabel jtbl_titlescreen_and_loading_8006D364
    /* 23100 8006D364 24070780 */ .word .Ltitlescreen_and_loading_80070724
    /* 23104 8006D368 54070780 */ .word .Ltitlescreen_and_loading_80070754
    /* 23108 8006D36C 8C070780 */ .word .Ltitlescreen_and_loading_8007078C
    /* 2310C 8006D370 E4070780 */ .word .Ltitlescreen_and_loading_800707E4
    /* 23110 8006D374 18080780 */ .word .Ltitlescreen_and_loading_80070818
    /* 23114 8006D378 18080780 */ .word .Ltitlescreen_and_loading_80070818
    /* 23118 8006D37C 18080780 */ .word .Ltitlescreen_and_loading_80070818
    /* 2311C 8006D380 18080780 */ .word .Ltitlescreen_and_loading_80070818
    /* 23120 8006D384 18080780 */ .word .Ltitlescreen_and_loading_80070818
    /* 23124 8006D388 18080780 */ .word .Ltitlescreen_and_loading_80070818
    /* 23128 8006D38C 18080780 */ .word .Ltitlescreen_and_loading_80070818
    /* 2312C 8006D390 18080780 */ .word .Ltitlescreen_and_loading_80070818
    /* 23130 8006D394 98080780 */ .word .Ltitlescreen_and_loading_80070898
    /* 23134 8006D398 00000000 */ .word 0x00000000
enddlabel jtbl_titlescreen_and_loading_8006D364


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_titlescreen_and_loading_80070498, 0x564

glabel func_titlescreen_and_loading_80070498
    /* 26234 80070498 0680023C */  lui        $v0, %hi(D_80066EEC)
    /* 26238 8007049C EC6E428C */  lw         $v0, %lo(D_80066EEC)($v0)
    /* 2623C 800704A0 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 26240 800704A4 2000BFAF */  sw         $ra, 0x20($sp)
    /* 26244 800704A8 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 26248 800704AC FFFF4324 */  addiu      $v1, $v0, -0x1
    /* 2624C 800704B0 0600622C */  sltiu      $v0, $v1, 0x6
    /* 26250 800704B4 4B014010 */  beqz       $v0, .Ltitlescreen_and_loading_800709E4
    /* 26254 800704B8 1800B0AF */   sw        $s0, 0x18($sp)
    /* 26258 800704BC 80100300 */  sll        $v0, $v1, 2
  alabel D_titlescreen_and_loading_800704C0
    /* 2625C 800704C0 0780013C */  lui        $at, %hi(jtbl_titlescreen_and_loading_8006D34C)
    /* 26260 800704C4 21082200 */  addu       $at, $at, $v0
  alabel D_titlescreen_and_loading_800704C8
    /* 26264 800704C8 4CD3228C */  lw         $v0, %lo(jtbl_titlescreen_and_loading_8006D34C)($at)
    /* 26268 800704CC 00000000 */  nop
    /* 2626C 800704D0 08004000 */  jr         $v0
    /* 26270 800704D4 00000000 */   nop
  .Ltitlescreen_and_loading_800704D8:
    /* 26274 800704D8 0780103C */  lui        $s0, %hi(D_8006ABD0)
    /* 26278 800704DC D0AB1026 */  addiu      $s0, $s0, %lo(D_8006ABD0)
    /* 2627C 800704E0 21200002 */  addu       $a0, $s0, $zero
    /* 26280 800704E4 0680053C */  lui        $a1, %hi(D_80067068)
  alabel D_titlescreen_and_loading_800704E8
    /* 26284 800704E8 6870A58C */  lw         $a1, %lo(D_80067068)($a1)
    /* 26288 800704EC 036D000C */  jal        func_8001B40C
    /* 2628C 800704F0 28000624 */   addiu     $a2, $zero, 0x28
    /* 26290 800704F4 0680053C */  lui        $a1, %hi(D_80066F90)
    /* 26294 800704F8 906FA58C */  lw         $a1, %lo(D_80066F90)($a1)
    /* 26298 800704FC 0680013C */  lui        $at, %hi(D_80067068)
    /* 2629C 80070500 687030AC */  sw         $s0, %lo(D_80067068)($at)
    /* 262A0 80070504 0680013C */  lui        $at, %hi(D_80064940)
    /* 262A4 80070508 21082500 */  addu       $at, $at, $a1
    /* 262A8 8007050C 40492290 */  lbu        $v0, %lo(D_80064940)($at)
    /* 262AC 80070510 0680013C */  lui        $at, %hi(D_80066F54)
    /* 262B0 80070514 546F22AC */  sw         $v0, %lo(D_80066F54)($at)
    /* 262B4 80070518 4300A228 */  slti       $v0, $a1, 0x43
    /* 262B8 8007051C 26004010 */  beqz       $v0, .Ltitlescreen_and_loading_800705B8
    /* 262BC 80070520 6666023C */   lui       $v0, (0x66666667 >> 16)
    /* 262C0 80070524 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
    /* 262C4 80070528 1800A200 */  mult       $a1, $v0
    /* 262C8 8007052C C3170500 */  sra        $v0, $a1, 31
    /* 262CC 80070530 0680013C */  lui        $at, %hi(D_80067148)
    /* 262D0 80070534 487120A0 */  sb         $zero, %lo(D_80067148)($at)
    /* 262D4 80070538 0680013C */  lui        $at, %hi(D_80066FF0)
  alabel D_titlescreen_and_loading_8007053C
    /* 262D8 8007053C F06F20A0 */  sb         $zero, %lo(D_80066FF0)($at)
    /* 262DC 80070540 0680013C */  lui        $at, %hi(D_80066F44)
    /* 262E0 80070544 446F20A0 */  sb         $zero, %lo(D_80066F44)($at)
  alabel D_titlescreen_and_loading_80070548
    /* 262E4 80070548 0680013C */  lui        $at, %hi(D_80066FF4)
    /* 262E8 8007054C F46F20A0 */  sb         $zero, %lo(D_80066FF4)($at)
    /* 262EC 80070550 10480000 */  mfhi       $t1
    /* 262F0 80070554 83180900 */  sra        $v1, $t1, 2
    /* 262F4 80070558 23206200 */  subu       $a0, $v1, $v0
    /* 262F8 8007055C 80100400 */  sll        $v0, $a0, 2
    /* 262FC 80070560 21104400 */  addu       $v0, $v0, $a0
    /* 26300 80070564 40100200 */  sll        $v0, $v0, 1
    /* 26304 80070568 2310A200 */  subu       $v0, $a1, $v0
    /* 26308 8007056C 0100432C */  sltiu      $v1, $v0, 0x1
    /* 2630C 80070570 0680013C */  lui        $at, %hi(D_80066EE4)
    /* 26310 80070574 E46E23AC */  sw         $v1, %lo(D_80066EE4)($at)
    /* 26314 80070578 05000324 */  addiu      $v1, $zero, 0x5
    /* 26318 8007057C 05004314 */  bne        $v0, $v1, .Ltitlescreen_and_loading_80070594
    /* 2631C 80070580 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 26320 80070584 41000224 */  addiu      $v0, $zero, 0x41
    /* 26324 80070588 0200A214 */  bne        $a1, $v0, .Ltitlescreen_and_loading_80070594
    /* 26328 8007058C FEFF8224 */   addiu     $v0, $a0, -0x2
    /* 2632C 80070590 FFFF0224 */  addiu      $v0, $zero, -0x1
  .Ltitlescreen_and_loading_80070594:
    /* 26330 80070594 0780013C */  lui        $at, %hi(D_80069894)
  alabel D_titlescreen_and_loading_80070598
    /* 26334 80070598 949822AC */  sw         $v0, %lo(D_80069894)($at)
    /* 26338 8007059C 0680023C */  lui        $v0, %hi(D_80066F54)
  alabel D_titlescreen_and_loading_800705A0
    /* 2633C 800705A0 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* 26340 800705A4 0780013C */  lui        $at, %hi(D_8006B264)
  alabel D_titlescreen_and_loading_800705A8
    /* 26344 800705A8 21082200 */  addu       $at, $at, $v0
    /* 26348 800705AC 64B22290 */  lbu        $v0, %lo(D_8006B264)($at)
    /* 2634C 800705B0 0680013C */  lui        $at, %hi(D_80067090)
    /* 26350 800705B4 907022AC */  sw         $v0, %lo(D_80067090)($at)
  .Ltitlescreen_and_loading_800705B8:
    /* 26354 800705B8 0680033C */  lui        $v1, %hi(D_80066F90)
    /* 26358 800705BC 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
  alabel D_titlescreen_and_loading_800705C0
    /* 2635C 800705C0 2A000224 */  addiu      $v0, $zero, 0x2A
    /* 26360 800705C4 03006210 */  beq        $v1, $v0, .Ltitlescreen_and_loading_800705D4
  alabel D_titlescreen_and_loading_800705C8
    /* 26364 800705C8 33000224 */   addiu     $v0, $zero, 0x33
    /* 26368 800705CC 06006214 */  bne        $v1, $v0, .Ltitlescreen_and_loading_800705E8
    /* 2636C 800705D0 00000000 */   nop
  .Ltitlescreen_and_loading_800705D4:
    /* 26370 800705D4 01000224 */  addiu      $v0, $zero, 0x1
    /* 26374 800705D8 0680013C */  lui        $at, %hi(D_80066FA4)
    /* 26378 800705DC A46F22AC */  sw         $v0, %lo(D_80066FA4)($at)
    /* 2637C 800705E0 7CC10108 */  j          .Ltitlescreen_and_loading_800705F0
    /* 26380 800705E4 00000000 */   nop
  .Ltitlescreen_and_loading_800705E8:
    /* 26384 800705E8 0680013C */  lui        $at, %hi(D_80066FA4)
    /* 26388 800705EC A46F20AC */  sw         $zero, %lo(D_80066FA4)($at)
  .Ltitlescreen_and_loading_800705F0:
    /* 2638C 800705F0 58B6010C */  jal        func_titlescreen_and_loading_8006D960
    /* 26390 800705F4 00000000 */   nop
    /* 26394 800705F8 0780053C */  lui        $a1, %hi(D_8006B288)
    /* 26398 800705FC 88B2A524 */  addiu      $a1, $a1, %lo(D_8006B288)
  alabel D_titlescreen_and_loading_80070600
    /* 2639C 80070600 0680023C */  lui        $v0, %hi(D_80066F54)
    /* 263A0 80070604 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* 263A4 80070608 0180033C */  lui        $v1, %hi(D_80011110)
    /* 263A8 8007060C 1011638C */  lw         $v1, %lo(D_80011110)($v1)
    /* 263AC 80070610 00390200 */  sll        $a3, $v0, 4
    /* 263B0 80070614 0680013C */  lui        $at, %hi(D_8006774C)
    /* 263B4 80070618 21082700 */  addu       $at, $at, $a3
    /* 263B8 8007061C 4C77228C */  lw         $v0, %lo(D_8006774C)($at)
    /* 263BC 80070620 0680043C */  lui        $a0, %hi(D_800670C4)
    /* 263C0 80070624 C470848C */  lw         $a0, %lo(D_800670C4)($a0)
  alabel D_titlescreen_and_loading_80070628
    /* 263C4 80070628 21106200 */  addu       $v0, $v1, $v0
    /* 263C8 8007062C 0000A2AC */  sw         $v0, 0x0($a1)
    /* 263CC 80070630 23104300 */  subu       $v0, $v0, $v1
    /* 263D0 80070634 2A104400 */  slt        $v0, $v0, $a0
    /* 263D4 80070638 02004010 */  beqz       $v0, .Ltitlescreen_and_loading_80070644
    /* 263D8 8007063C 21106400 */   addu      $v0, $v1, $a0
    /* 263DC 80070640 0000A2AC */  sw         $v0, 0x0($a1)
  .Ltitlescreen_and_loading_80070644:
    /* 263E0 80070644 0000A58C */  lw         $a1, 0x0($a1)
    /* 263E4 80070648 0780043C */  lui        $a0, %hi(D_800682D8)
    /* 263E8 8007064C D882848C */  lw         $a0, %lo(D_800682D8)($a0)
    /* 263EC 80070650 0780013C */  lui        $at, %hi(D_8006B28C)
    /* 263F0 80070654 8CB225AC */  sw         $a1, %lo(D_8006B28C)($at)
    /* 263F4 80070658 0680013C */  lui        $at, %hi(D_80067750)
    /* 263F8 8007065C 21082700 */  addu       $at, $at, $a3
    /* 263FC 80070660 5077278C */  lw         $a3, %lo(D_80067750)($at)
    /* 26400 80070664 77C20108 */  j          .Ltitlescreen_and_loading_800709DC
    /* 26404 80070668 00080624 */   addiu     $a2, $zero, 0x800
  .Ltitlescreen_and_loading_8007066C:
    /* 26408 8007066C 0780103C */  lui        $s0, %hi(D_8006B0A4)
    /* 2640C 80070670 A4B01026 */  addiu      $s0, $s0, %lo(D_8006B0A4)
    /* 26410 80070674 21200002 */  addu       $a0, $s0, $zero
    /* 26414 80070678 0780113C */  lui        $s1, %hi(D_8006B28C)
    /* 26418 8007067C 8CB23126 */  addiu      $s1, $s1, %lo(D_8006B28C)
    /* 2641C 80070680 0000258E */  lw         $a1, 0x0($s1)
    /* 26420 80070684 036D000C */  jal        func_8001B40C
    /* 26424 80070688 C0010624 */   addiu     $a2, $zero, 0x1C0
    /* 26428 8007068C 0800063C */  lui        $a2, (0x80000 >> 16)
  alabel D_titlescreen_and_loading_80070690
    /* 2642C 80070690 0680023C */  lui        $v0, %hi(D_80066F54)
    /* 26430 80070694 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* 26434 80070698 0780043C */  lui        $a0, %hi(D_800682D8)
    /* 26438 8007069C D882848C */  lw         $a0, %lo(D_800682D8)($a0)
    /* 2643C 800706A0 0000038E */  lw         $v1, 0x0($s0)
    /* 26440 800706A4 00110200 */  sll        $v0, $v0, 4
    /* 26444 800706A8 0680013C */  lui        $at, %hi(D_80067750)
    /* 26448 800706AC 21082200 */  addu       $at, $at, $v0
    /* 2644C 800706B0 5077278C */  lw         $a3, %lo(D_80067750)($at)
    /* 26450 800706B4 0000258E */  lw         $a1, 0x0($s1)
    /* 26454 800706B8 464E000C */  jal        func_80013918
    /* 26458 800706BC 21386700 */   addu      $a3, $v1, $a3
    /* 2645C 800706C0 0780033C */  lui        $v1, %hi(D_800681C8)
    /* 26460 800706C4 C881638C */  lw         $v1, %lo(D_800681C8)($v1)
    /* 26464 800706C8 09000224 */  addiu      $v0, $zero, 0x9
    /* 26468 800706CC 05006210 */  beq        $v1, $v0, .Ltitlescreen_and_loading_800706E4
    /* 2646C 800706D0 02000224 */   addiu     $v0, $zero, 0x2
    /* 26470 800706D4 0680013C */  lui        $at, %hi(D_80066FAC)
    /* 26474 800706D8 AC6F20AC */  sw         $zero, %lo(D_80066FAC)($at)
    /* 26478 800706DC 79C20108 */  j          .Ltitlescreen_and_loading_800709E4
    /* 2647C 800706E0 00000000 */   nop
  .Ltitlescreen_and_loading_800706E4:
    /* 26480 800706E4 0680013C */  lui        $at, %hi(D_80066FAC)
    /* 26484 800706E8 AC6F22AC */  sw         $v0, %lo(D_80066FAC)($at)
    /* 26488 800706EC 79C20108 */  j          .Ltitlescreen_and_loading_800709E4
    /* 2648C 800706F0 00000000 */   nop
  .Ltitlescreen_and_loading_800706F4:
    /* 26490 800706F4 0680033C */  lui        $v1, %hi(D_80066FAC)
  alabel D_titlescreen_and_loading_800706F8
    /* 26494 800706F8 AC6F638C */  lw         $v1, %lo(D_80066FAC)($v1)
    /* 26498 800706FC 00000000 */  nop
    /* 2649C 80070700 0D00622C */  sltiu      $v0, $v1, 0xD
    /* 264A0 80070704 7A004010 */  beqz       $v0, .Ltitlescreen_and_loading_800708F0
    /* 264A4 80070708 80100300 */   sll       $v0, $v1, 2
    /* 264A8 8007070C 0780013C */  lui        $at, %hi(jtbl_titlescreen_and_loading_8006D364)
    /* 264AC 80070710 21082200 */  addu       $at, $at, $v0
    /* 264B0 80070714 64D3228C */  lw         $v0, %lo(jtbl_titlescreen_and_loading_8006D364)($at)
    /* 264B4 80070718 00000000 */  nop
    /* 264B8 8007071C 08004000 */  jr         $v0
    /* 264BC 80070720 00000000 */   nop
  .Ltitlescreen_and_loading_80070724:
    /* 264C0 80070724 1000A427 */  addiu      $a0, $sp, 0x10
    /* 264C4 80070728 0780053C */  lui        $a1, %hi(D_8006B28C)
    /* 264C8 8007072C 8CB2A58C */  lw         $a1, %lo(D_8006B28C)($a1)
  alabel D_titlescreen_and_loading_80070730
    /* 264CC 80070730 00020224 */  addiu      $v0, $zero, 0x200
    /* 264D0 80070734 1000A2A7 */  sh         $v0, 0x10($sp)
    /* 264D4 80070738 1400A2A7 */  sh         $v0, 0x14($sp)
    /* 264D8 8007073C 00010224 */  addiu      $v0, $zero, 0x100
    /* 264DC 80070740 1200A0A7 */  sh         $zero, 0x12($sp)
    /* 264E0 80070744 7E56010C */  jal        func_800559F8
    /* 264E4 80070748 1600A2A7 */   sh        $v0, 0x16($sp)
    /* 264E8 8007074C 3CC20108 */  j          .Ltitlescreen_and_loading_800708F0
    /* 264EC 80070750 00000000 */   nop
  .Ltitlescreen_and_loading_80070754:
    /* 264F0 80070754 1000A427 */  addiu      $a0, $sp, 0x10
    /* 264F4 80070758 00020324 */  addiu      $v1, $zero, 0x200
    /* 264F8 8007075C 00010224 */  addiu      $v0, $zero, 0x100
    /* 264FC 80070760 1200A2A7 */  sh         $v0, 0x12($sp)
    /* 26500 80070764 1600A2A7 */  sh         $v0, 0x16($sp)
    /* 26504 80070768 0780023C */  lui        $v0, %hi(D_8006B28C)
    /* 26508 8007076C 8CB2428C */  lw         $v0, %lo(D_8006B28C)($v0)
    /* 2650C 80070770 0400053C */  lui        $a1, (0x40000 >> 16)
    /* 26510 80070774 1000A3A7 */  sh         $v1, 0x10($sp)
    /* 26514 80070778 1400A3A7 */  sh         $v1, 0x14($sp)
    /* 26518 8007077C 7E56010C */  jal        func_800559F8
    /* 2651C 80070780 21284500 */   addu      $a1, $v0, $a1
    /* 26520 80070784 3CC20108 */  j          .Ltitlescreen_and_loading_800708F0
    /* 26524 80070788 00000000 */   nop
  .Ltitlescreen_and_loading_8007078C:
    /* 26528 8007078C F8FF073C */  lui        $a3, (0xFFF80000 >> 16)
  alabel D_titlescreen_and_loading_80070790
    /* 2652C 80070790 0780043C */  lui        $a0, %hi(D_800682D8)
    /* 26530 80070794 D882848C */  lw         $a0, %lo(D_800682D8)($a0)
  alabel D_titlescreen_and_loading_80070798
    /* 26534 80070798 0780053C */  lui        $a1, %hi(D_8006B28C)
    /* 26538 8007079C 8CB2A58C */  lw         $a1, %lo(D_8006B28C)($a1)
    /* 2653C 800707A0 0680023C */  lui        $v0, %hi(D_80066F54)
    /* 26540 800707A4 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* 26544 800707A8 0780063C */  lui        $a2, %hi(D_8006B0A8)
    /* 26548 800707AC A8B0C68C */  lw         $a2, %lo(D_8006B0A8)($a2)
    /* 2654C 800707B0 0780033C */  lui        $v1, %hi(D_8006B0A4)
    /* 26550 800707B4 A4B0638C */  lw         $v1, %lo(D_8006B0A4)($v1)
    /* 26554 800707B8 00110200 */  sll        $v0, $v0, 4
    /* 26558 800707BC 2130C700 */  addu       $a2, $a2, $a3
    /* 2655C 800707C0 0680013C */  lui        $at, %hi(D_80067750)
    /* 26560 800707C4 21082200 */  addu       $at, $at, $v0
  alabel D_titlescreen_and_loading_800707C8
    /* 26564 800707C8 5077228C */  lw         $v0, %lo(D_80067750)($at)
    /* 26568 800707CC 0800073C */  lui        $a3, (0x80000 >> 16)
  alabel D_titlescreen_and_loading_800707D0
    /* 2656C 800707D0 21186200 */  addu       $v1, $v1, $v0
    /* 26570 800707D4 464E000C */  jal        func_80013918
    /* 26574 800707D8 21386700 */   addu      $a3, $v1, $a3
    /* 26578 800707DC 3CC20108 */  j          .Ltitlescreen_and_loading_800708F0
    /* 2657C 800707E0 00000000 */   nop
  .Ltitlescreen_and_loading_800707E4:
    /* 26580 800707E4 0700043C */  lui        $a0, (0x7A000 >> 16)
    /* 26584 800707E8 EF67010C */  jal        func_80059FBC
    /* 26588 800707EC 00A08434 */   ori       $a0, $a0, (0x7A000 & 0xFFFF)
    /* 2658C 800707F0 0780043C */  lui        $a0, %hi(D_8006B28C)
    /* 26590 800707F4 8CB2848C */  lw         $a0, %lo(D_8006B28C)($a0)
  alabel D_titlescreen_and_loading_800707F8
    /* 26594 800707F8 AA6A010C */  jal        func_8005AAA8
    /* 26598 800707FC 00600524 */   addiu     $a1, $zero, 0x6000
  .Ltitlescreen_and_loading_80070800:
    /* 2659C 80070800 5768010C */  jal        func_8005A15C
    /* 265A0 80070804 21200000 */   addu      $a0, $zero, $zero
    /* 265A4 80070808 FDFF4010 */  beqz       $v0, .Ltitlescreen_and_loading_80070800
    /* 265A8 8007080C 00000000 */   nop
    /* 265AC 80070810 3CC20108 */  j          .Ltitlescreen_and_loading_800708F0
    /* 265B0 80070814 00000000 */   nop
  .Ltitlescreen_and_loading_80070818:
    /* 265B4 80070818 0800033C */  lui        $v1, (0x86000 >> 16)
    /* 265B8 8007081C 00606334 */  ori        $v1, $v1, (0x86000 & 0xFFFF)
  alabel D_titlescreen_and_loading_80070820
    /* 265BC 80070820 0680023C */  lui        $v0, %hi(D_80066FAC)
    /* 265C0 80070824 AC6F428C */  lw         $v0, %lo(D_80066FAC)($v0)
    /* 265C4 80070828 0780043C */  lui        $a0, %hi(D_8006B0A8)
    /* 265C8 8007082C A8B0848C */  lw         $a0, %lo(D_8006B0A8)($a0)
  alabel D_titlescreen_and_loading_80070830
    /* 265CC 80070830 FCFF4224 */  addiu      $v0, $v0, -0x4
    /* 265D0 80070834 00140200 */  sll        $v0, $v0, 16
  alabel D_titlescreen_and_loading_80070838
    /* 265D4 80070838 21184300 */  addu       $v1, $v0, $v1
    /* 265D8 8007083C 23808300 */  subu       $s0, $a0, $v1
    /* 265DC 80070840 21884000 */  addu       $s1, $v0, $zero
    /* 265E0 80070844 0100023C */  lui        $v0, (0x10000 >> 16)
    /* 265E4 80070848 2A105000 */  slt        $v0, $v0, $s0
    /* 265E8 8007084C 02004010 */  beqz       $v0, .Ltitlescreen_and_loading_80070858
    /* 265EC 80070850 00000000 */   nop
    /* 265F0 80070854 0100103C */  lui        $s0, (0x10000 >> 16)
  .Ltitlescreen_and_loading_80070858:
    /* 265F4 80070858 2500001A */  blez       $s0, .Ltitlescreen_and_loading_800708F0
    /* 265F8 8007085C 00000000 */   nop
    /* 265FC 80070860 EF67010C */  jal        func_80059FBC
    /* 26600 80070864 10102436 */   ori       $a0, $s1, 0x1010
    /* 26604 80070868 21280002 */  addu       $a1, $s0, $zero
    /* 26608 8007086C 0780023C */  lui        $v0, %hi(D_8006B28C)
    /* 2660C 80070870 8CB2428C */  lw         $v0, %lo(D_8006B28C)($v0)
    /* 26610 80070874 00602426 */  addiu      $a0, $s1, 0x6000
    /* 26614 80070878 AA6A010C */  jal        func_8005AAA8
    /* 26618 8007087C 21204400 */   addu      $a0, $v0, $a0
  .Ltitlescreen_and_loading_80070880:
    /* 2661C 80070880 5768010C */  jal        func_8005A15C
    /* 26620 80070884 21200000 */   addu      $a0, $zero, $zero
    /* 26624 80070888 FDFF4010 */  beqz       $v0, .Ltitlescreen_and_loading_80070880
    /* 26628 8007088C 00000000 */   nop
    /* 2662C 80070890 3CC20108 */  j          .Ltitlescreen_and_loading_800708F0
    /* 26630 80070894 00000000 */   nop
  .Ltitlescreen_and_loading_80070898:
    /* 26634 80070898 0780043C */  lui        $a0, %hi(D_800682D8)
    /* 26638 8007089C D882848C */  lw         $a0, %lo(D_800682D8)($a0)
    /* 2663C 800708A0 0680023C */  lui        $v0, %hi(D_80066F54)
    /* 26640 800708A4 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* 26644 800708A8 0780053C */  lui        $a1, %hi(D_8006B28C)
  alabel D_titlescreen_and_loading_800708AC
    /* 26648 800708AC 8CB2A58C */  lw         $a1, %lo(D_8006B28C)($a1)
    /* 2664C 800708B0 0780033C */  lui        $v1, %hi(D_8006B0AC)
    /* 26650 800708B4 ACB0638C */  lw         $v1, %lo(D_8006B0AC)($v1)
    /* 26654 800708B8 00110200 */  sll        $v0, $v0, 4
    /* 26658 800708BC 0680013C */  lui        $at, %hi(D_80067750)
    /* 2665C 800708C0 21082200 */  addu       $at, $at, $v0
    /* 26660 800708C4 5077278C */  lw         $a3, %lo(D_80067750)($at)
    /* 26664 800708C8 0780063C */  lui        $a2, %hi(D_8006B0B0)
    /* 26668 800708CC B0B0C68C */  lw         $a2, %lo(D_8006B0B0)($a2)
    /* 2666C 800708D0 464E000C */  jal        func_80013918
  alabel D_titlescreen_and_loading_800708D4
    /* 26670 800708D4 21386700 */   addu      $a3, $v1, $a3
    /* 26674 800708D8 0680023C */  lui        $v0, %hi(D_80066EEC)
    /* 26678 800708DC EC6E428C */  lw         $v0, %lo(D_80066EEC)($v0)
    /* 2667C 800708E0 00000000 */  nop
    /* 26680 800708E4 01004224 */  addiu      $v0, $v0, 0x1
    /* 26684 800708E8 0680013C */  lui        $at, %hi(D_80066EEC)
    /* 26688 800708EC EC6E22AC */  sw         $v0, %lo(D_80066EEC)($at)
  .Ltitlescreen_and_loading_800708F0:
    /* 2668C 800708F0 0680023C */  lui        $v0, %hi(D_80066FAC)
    /* 26690 800708F4 AC6F428C */  lw         $v0, %lo(D_80066FAC)($v0)
    /* 26694 800708F8 0680033C */  lui        $v1, %hi(D_80066EEC)
    /* 26698 800708FC EC6E638C */  lw         $v1, %lo(D_80066EEC)($v1)
    /* 2669C 80070900 01004224 */  addiu      $v0, $v0, 0x1
    /* 266A0 80070904 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 266A4 80070908 0680013C */  lui        $at, %hi(D_80066FAC)
    /* 266A8 8007090C AC6F22AC */  sw         $v0, %lo(D_80066FAC)($at)
    /* 266AC 80070910 0680013C */  lui        $at, %hi(D_80066EEC)
    /* 266B0 80070914 EC6E23AC */  sw         $v1, %lo(D_80066EEC)($at)
    /* 266B4 80070918 79C20108 */  j          .Ltitlescreen_and_loading_800709E4
    /* 266B8 8007091C 00000000 */   nop
  .Ltitlescreen_and_loading_80070920:
    /* 266BC 80070920 0780043C */  lui        $a0, %hi(D_8006B28C)
    /* 266C0 80070924 8CB2848C */  lw         $a0, %lo(D_8006B28C)($a0)
  alabel D_titlescreen_and_loading_80070928
    /* 266C4 80070928 A6BE010C */  jal        func_titlescreen_and_loading_8006FA98
    /* 266C8 8007092C 00000000 */   nop
    /* 266CC 80070930 21284000 */  addu       $a1, $v0, $zero
    /* 266D0 80070934 0780043C */  lui        $a0, %hi(D_800682D8)
    /* 266D4 80070938 D882848C */  lw         $a0, %lo(D_800682D8)($a0)
    /* 266D8 8007093C 0680033C */  lui        $v1, %hi(D_80066F54)
    /* 266DC 80070940 546F638C */  lw         $v1, %lo(D_80066F54)($v1)
    /* 266E0 80070944 0780023C */  lui        $v0, %hi(D_8006B0B4)
    /* 266E4 80070948 B4B0428C */  lw         $v0, %lo(D_8006B0B4)($v0)
    /* 266E8 8007094C 0780013C */  lui        $at, %hi(D_8006B290)
    /* 266EC 80070950 90B225AC */  sw         $a1, %lo(D_8006B290)($at)
    /* 266F0 80070954 00190300 */  sll        $v1, $v1, 4
    /* 266F4 80070958 0680013C */  lui        $at, %hi(D_80067750)
    /* 266F8 8007095C 21082300 */  addu       $at, $at, $v1
    /* 266FC 80070960 5077278C */  lw         $a3, %lo(D_80067750)($at)
    /* 26700 80070964 0780063C */  lui        $a2, %hi(D_8006B0B8)
    /* 26704 80070968 B8B0C68C */  lw         $a2, %lo(D_8006B0B8)($a2)
    /* 26708 8007096C 77C20108 */  j          .Ltitlescreen_and_loading_800709DC
    /* 2670C 80070970 21384700 */   addu      $a3, $v0, $a3
  .Ltitlescreen_and_loading_80070974:
    /* 26710 80070974 0780043C */  lui        $a0, %hi(D_8006B290)
    /* 26714 80070978 90B2848C */  lw         $a0, %lo(D_8006B290)($a0)
    /* 26718 8007097C E6C0010C */  jal        func_titlescreen_and_loading_80070398
  alabel D_titlescreen_and_loading_80070980
    /* 2671C 80070980 8080053C */   lui       $a1, (0x80800000 >> 16)
    /* 26720 80070984 21284000 */  addu       $a1, $v0, $zero
    /* 26724 80070988 0780043C */  lui        $a0, %hi(D_800682D8)
    /* 26728 8007098C D882848C */  lw         $a0, %lo(D_800682D8)($a0)
    /* 2672C 80070990 0680033C */  lui        $v1, %hi(D_80067118)
  alabel D_titlescreen_and_loading_80070994
    /* 26730 80070994 1871638C */  lw         $v1, %lo(D_80067118)($v1)
    /* 26734 80070998 0680023C */  lui        $v0, %hi(D_80066F54)
    /* 26738 8007099C 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* 2673C 800709A0 0780013C */  lui        $at, %hi(D_8006B294)
    /* 26740 800709A4 94B225AC */  sw         $a1, %lo(D_8006B294)($at)
    /* 26744 800709A8 03006324 */  addiu      $v1, $v1, 0x3
    /* 26748 800709AC C0180300 */  sll        $v1, $v1, 3
    /* 2674C 800709B0 00110200 */  sll        $v0, $v0, 4
    /* 26750 800709B4 0780013C */  lui        $at, %hi(D_8006B0A4)
    /* 26754 800709B8 21082300 */  addu       $at, $at, $v1
    /* 26758 800709BC A4B0288C */  lw         $t0, %lo(D_8006B0A4)($at)
    /* 2675C 800709C0 0680013C */  lui        $at, %hi(D_80067750)
    /* 26760 800709C4 21082200 */  addu       $at, $at, $v0
    /* 26764 800709C8 5077278C */  lw         $a3, %lo(D_80067750)($at)
    /* 26768 800709CC 0780013C */  lui        $at, %hi(D_8006B0A8)
  alabel D_titlescreen_and_loading_800709D0
    /* 2676C 800709D0 21082300 */  addu       $at, $at, $v1
    /* 26770 800709D4 A8B0268C */  lw         $a2, %lo(D_8006B0A8)($at)
    /* 26774 800709D8 21380701 */  addu       $a3, $t0, $a3
  .Ltitlescreen_and_loading_800709DC:
    /* 26778 800709DC 464E000C */  jal        func_80013918
    /* 2677C 800709E0 00000000 */   nop
  .Ltitlescreen_and_loading_800709E4:
    /* 26780 800709E4 2000BF8F */  lw         $ra, 0x20($sp)
    /* 26784 800709E8 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 26788 800709EC 1800B08F */  lw         $s0, 0x18($sp)
    /* 2678C 800709F0 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 26790 800709F4 0800E003 */  jr         $ra
    /* 26794 800709F8 00000000 */   nop
endlabel func_titlescreen_and_loading_80070498
