.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_10_8006D418

dlabel jtbl_level_10_8006D418
    /* D361B4 8006D418 6CF10680 */ .word .Llevel_10_8006F16C
    /* D361B8 8006D41C DCF00680 */ .word .Llevel_10_8006F0DC
    /* D361BC 8006D420 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361C0 8006D424 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361C4 8006D428 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361C8 8006D42C 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361CC 8006D430 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361D0 8006D434 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361D4 8006D438 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361D8 8006D43C 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361DC 8006D440 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361E0 8006D444 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361E4 8006D448 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361E8 8006D44C 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361EC 8006D450 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361F0 8006D454 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361F4 8006D458 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361F8 8006D45C 5CF70680 */ .word .Llevel_10_8006F75C
    /* D361FC 8006D460 5CF70680 */ .word .Llevel_10_8006F75C
    /* D36200 8006D464 5CF70680 */ .word .Llevel_10_8006F75C
    /* D36204 8006D468 DCF00680 */ .word .Llevel_10_8006F0DC
    /* D36208 8006D46C 5CF70680 */ .word .Llevel_10_8006F75C
    /* D3620C 8006D470 4CF20680 */ .word .Llevel_10_8006F24C
    /* D36210 8006D474 4CF20680 */ .word .Llevel_10_8006F24C
    /* D36214 8006D478 18F40680 */ .word .Llevel_10_8006F418
    /* D36218 8006D47C F4F50680 */ .word .Llevel_10_8006F5F4
    /* D3621C 8006D480 F4F50680 */ .word .Llevel_10_8006F5F4
    /* D36220 8006D484 5CF70680 */ .word .Llevel_10_8006F75C
    /* D36224 8006D488 5CF70680 */ .word .Llevel_10_8006F75C
    /* D36228 8006D48C 24F70680 */ .word .Llevel_10_8006F724
    /* D3622C 8006D490 5CF70680 */ .word .Llevel_10_8006F75C
    /* D36230 8006D494 5CF70680 */ .word .Llevel_10_8006F75C
    /* D36234 8006D498 24F70680 */ .word .Llevel_10_8006F724
    /* D36238 8006D49C 24F70680 */ .word .Llevel_10_8006F724
    /* D3623C 8006D4A0 24F70680 */ .word .Llevel_10_8006F724
    /* D36240 8006D4A4 00000000 */ .word 0x00000000
enddlabel jtbl_level_10_8006D418


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_10_8006F0A0, 0x6D4

glabel func_level_10_8006F0A0
    /* D37E3C 8006F0A0 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* D37E40 8006F0A4 4400B1AF */  sw         $s1, 0x44($sp)
    /* D37E44 8006F0A8 21888000 */  addu       $s1, $a0, $zero
    /* D37E48 8006F0AC EEFF2326 */  addiu      $v1, $s1, -0x12
    /* D37E4C 8006F0B0 2300622C */  sltiu      $v0, $v1, 0x23
    /* D37E50 8006F0B4 4800BFAF */  sw         $ra, 0x48($sp)
    /* D37E54 8006F0B8 A8014010 */  beqz       $v0, .Llevel_10_8006F75C
    /* D37E58 8006F0BC 4000B0AF */   sw        $s0, 0x40($sp)
    /* D37E5C 8006F0C0 80100300 */  sll        $v0, $v1, 2
    /* D37E60 8006F0C4 0780013C */  lui        $at, %hi(jtbl_level_10_8006D418)
    /* D37E64 8006F0C8 21082200 */  addu       $at, $at, $v0
    /* D37E68 8006F0CC 18D4228C */  lw         $v0, %lo(jtbl_level_10_8006D418)($at)
    /* D37E6C 8006F0D0 00000000 */  nop
    /* D37E70 8006F0D4 08004000 */  jr         $v0
    /* D37E74 8006F0D8 00000000 */   nop
  .Llevel_10_8006F0DC:
    /* D37E78 8006F0DC 0780013C */  lui        $at, %hi(D_8006A048)
    /* D37E7C 8006F0E0 48A020AC */  sw         $zero, %lo(D_8006A048)($at)
    /* D37E80 8006F0E4 0780013C */  lui        $at, %hi(D_8006A044)
    /* D37E84 8006F0E8 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* D37E88 8006F0EC AFB8000C */  jal        func_8002E2BC
    /* D37E8C 8006F0F0 00000000 */   nop
    /* D37E90 8006F0F4 01000224 */  addiu      $v0, $zero, 0x1
    /* D37E94 8006F0F8 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* D37E98 8006F0FC ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* D37E9C 8006F100 25000224 */  addiu      $v0, $zero, 0x25
    /* D37EA0 8006F104 04002216 */  bne        $s1, $v0, .Llevel_10_8006F118
    /* D37EA4 8006F108 01000424 */   addiu     $a0, $zero, 0x1
    /* D37EA8 8006F10C 05000424 */  addiu      $a0, $zero, 0x5
    /* D37EAC 8006F110 47BC0108 */  j          .Llevel_10_8006F11C
    /* D37EB0 8006F114 08000524 */   addiu     $a1, $zero, 0x8
  .Llevel_10_8006F118:
    /* D37EB4 8006F118 03000524 */  addiu      $a1, $zero, 0x3
  .Llevel_10_8006F11C:
    /* D37EB8 8006F11C 47E2000C */  jal        func_8003891C
    /* D37EBC 8006F120 00000000 */   nop
    /* D37EC0 8006F124 0780013C */  lui        $at, %hi(D_8006A13C)
    /* D37EC4 8006F128 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* D37EC8 8006F12C 0680033C */  lui        $v1, %hi(D_800670B4)
    /* D37ECC 8006F130 B470638C */  lw         $v1, %lo(D_800670B4)($v1)
    /* D37ED0 8006F134 0780013C */  lui        $at, %hi(D_8006A140)
    /* D37ED4 8006F138 40A120AC */  sw         $zero, %lo(D_8006A140)($at)
    /* D37ED8 8006F13C 87016010 */  beqz       $v1, .Llevel_10_8006F75C
    /* D37EDC 8006F140 25000224 */   addiu     $v0, $zero, 0x25
    /* D37EE0 8006F144 03002216 */  bne        $s1, $v0, .Llevel_10_8006F154
    /* D37EE4 8006F148 27000224 */   addiu     $v0, $zero, 0x27
    /* D37EE8 8006F14C 57BC0108 */  j          .Llevel_10_8006F15C
    /* D37EEC 8006F150 F1010424 */   addiu     $a0, $zero, 0x1F1
  .Llevel_10_8006F154:
    /* D37EF0 8006F154 81012216 */  bne        $s1, $v0, .Llevel_10_8006F75C
    /* D37EF4 8006F158 DB010424 */   addiu     $a0, $zero, 0x1DB
  .Llevel_10_8006F15C:
    /* D37EF8 8006F15C 09F86000 */  jalr       $v1
    /* D37EFC 8006F160 21280000 */   addu      $a1, $zero, $zero
    /* D37F00 8006F164 D7BD0108 */  j          .Llevel_10_8006F75C
    /* D37F04 8006F168 00000000 */   nop
  .Llevel_10_8006F16C:
    /* D37F08 8006F16C 0780033C */  lui        $v1, %hi(D_8006A048)
    /* D37F0C 8006F170 48A06324 */  addiu      $v1, $v1, %lo(D_8006A048)
    /* D37F10 8006F174 0780023C */  lui        $v0, %hi(D_8006A208)
    /* D37F14 8006F178 08A2428C */  lw         $v0, %lo(D_8006A208)($v0)
    /* D37F18 8006F17C 00000000 */  nop
    /* D37F1C 8006F180 0000508C */  lw         $s0, 0x0($v0)
    /* D37F20 8006F184 0E000224 */  addiu      $v0, $zero, 0xE
    /* D37F24 8006F188 000062AC */  sw         $v0, 0x0($v1)
    /* D37F28 8006F18C 0780013C */  lui        $at, %hi(D_8006A044)
    /* D37F2C 8006F190 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* D37F30 8006F194 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* D37F34 8006F198 ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* D37F38 8006F19C 686F000C */  jal        func_8001BDA0
    /* D37F3C 8006F1A0 3C006424 */   addiu     $a0, $v1, 0x3C
    /* D37F40 8006F1A4 0780053C */  lui        $a1, %hi(D_8006A208)
    /* D37F44 8006F1A8 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* D37F48 8006F1AC 0780063C */  lui        $a2, %hi(D_8006A05C)
    /* D37F4C 8006F1B0 5CA0C68C */  lw         $a2, %lo(D_8006A05C)($a2)
    /* D37F50 8006F1B4 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* D37F54 8006F1B8 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* D37F58 8006F1BC 1400A38C */  lw         $v1, 0x14($a1)
    /* D37F5C 8006F1C0 0000048E */  lw         $a0, 0x0($s0)
    /* D37F60 8006F1C4 0780013C */  lui        $at, %hi(D_8006A140)
    /* D37F64 8006F1C8 40A126AC */  sw         $a2, %lo(D_8006A140)($at)
    /* D37F68 8006F1CC 0780013C */  lui        $at, %hi(D_8006A13C)
    /* D37F6C 8006F1D0 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* D37F70 8006F1D4 21186400 */  addu       $v1, $v1, $a0
    /* D37F74 8006F1D8 0780013C */  lui        $at, %hi(D_8006A144)
    /* D37F78 8006F1DC 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* D37F7C 8006F1E0 23186200 */  subu       $v1, $v1, $v0
    /* D37F80 8006F1E4 00F86324 */  addiu      $v1, $v1, -0x800
    /* D37F84 8006F1E8 0780013C */  lui        $at, %hi(D_8006A14C)
    /* D37F88 8006F1EC 4CA123AC */  sw         $v1, %lo(D_8006A14C)($at)
    /* D37F8C 8006F1F0 801A0300 */  sll        $v1, $v1, 10
    /* D37F90 8006F1F4 831A0300 */  sra        $v1, $v1, 10
    /* D37F94 8006F1F8 00046324 */  addiu      $v1, $v1, 0x400
    /* D37F98 8006F1FC 0780013C */  lui        $at, %hi(D_8006A148)
    /* D37F9C 8006F200 48A123AC */  sw         $v1, %lo(D_8006A148)($at)
    /* D37FA0 8006F204 4600A290 */  lbu        $v0, 0x46($a1)
    /* D37FA4 8006F208 00000000 */  nop
    /* D37FA8 8006F20C 00110200 */  sll        $v0, $v0, 4
    /* D37FAC 8006F210 23104600 */  subu       $v0, $v0, $a2
    /* D37FB0 8006F214 23104300 */  subu       $v0, $v0, $v1
    /* D37FB4 8006F218 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* D37FB8 8006F21C 01086228 */  slti       $v0, $v1, 0x801
    /* D37FBC 8006F220 0780013C */  lui        $at, %hi(D_8006A148)
    /* D37FC0 8006F224 48A123AC */  sw         $v1, %lo(D_8006A148)($at)
    /* D37FC4 8006F228 03004014 */  bnez       $v0, .Llevel_10_8006F238
    /* D37FC8 8006F22C 00F06224 */   addiu     $v0, $v1, -0x1000
    /* D37FCC 8006F230 0780013C */  lui        $at, %hi(D_8006A148)
    /* D37FD0 8006F234 48A122AC */  sw         $v0, %lo(D_8006A148)($at)
  .Llevel_10_8006F238:
    /* D37FD4 8006F238 0400028E */  lw         $v0, 0x4($s0)
    /* D37FD8 8006F23C 0780013C */  lui        $at, %hi(D_8006A150)
    /* D37FDC 8006F240 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* D37FE0 8006F244 D7BD0108 */  j          .Llevel_10_8006F75C
    /* D37FE4 8006F248 00000000 */   nop
  .Llevel_10_8006F24C:
    /* D37FE8 8006F24C 0780103C */  lui        $s0, %hi(D_8006A048)
    /* D37FEC 8006F250 48A01026 */  addiu      $s0, $s0, %lo(D_8006A048)
    /* D37FF0 8006F254 0000038E */  lw         $v1, 0x0($s0)
    /* D37FF4 8006F258 00000000 */  nop
    /* D37FF8 8006F25C F5FF6224 */  addiu      $v0, $v1, -0xB
    /* D37FFC 8006F260 0200422C */  sltiu      $v0, $v0, 0x2
    /* D38000 8006F264 5D004014 */  bnez       $v0, .Llevel_10_8006F3DC
    /* D38004 8006F268 07000224 */   addiu     $v0, $zero, 0x7
    /* D38008 8006F26C 5B006210 */  beq        $v1, $v0, .Llevel_10_8006F3DC
    /* D3800C 8006F270 00000000 */   nop
    /* D38010 8006F274 0680023C */  lui        $v0, %hi(D_800670FC)
    /* D38014 8006F278 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* D38018 8006F27C 00000000 */  nop
    /* D3801C 8006F280 2F004010 */  beqz       $v0, .Llevel_10_8006F340
    /* D38020 8006F284 1000A427 */   addiu     $a0, $sp, 0x10
    /* D38024 8006F288 6C6F000C */  jal        func_8001BDB0
    /* D38028 8006F28C A8FF0526 */   addiu     $a1, $s0, -0x58
    /* D3802C 8006F290 0000038E */  lw         $v1, 0x0($s0)
    /* D38030 8006F294 0A000224 */  addiu      $v0, $zero, 0xA
    /* D38034 8006F298 11006214 */  bne        $v1, $v0, .Llevel_10_8006F2E0
    /* D38038 8006F29C 00000000 */   nop
    /* D3803C 8006F2A0 0780033C */  lui        $v1, %hi(D_8006A018)
    /* D38040 8006F2A4 18A0638C */  lw         $v1, %lo(D_8006A018)($v1)
    /* D38044 8006F2A8 00000000 */  nop
    /* D38048 8006F2AC 0C006104 */  bgez       $v1, .Llevel_10_8006F2E0
    /* D3804C 8006F2B0 06000424 */   addiu     $a0, $zero, 0x6
    /* D38050 8006F2B4 2E000524 */  addiu      $a1, $zero, 0x2E
    /* D38054 8006F2B8 1000A627 */  addiu      $a2, $sp, 0x10
    /* D38058 8006F2BC 21380000 */  addu       $a3, $zero, $zero
    /* D3805C 8006F2C0 0680023C */  lui        $v0, %hi(D_800670FC)
    /* D38060 8006F2C4 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* D38064 8006F2C8 23180300 */  negu       $v1, $v1
    /* D38068 8006F2CC 09F84000 */  jalr       $v0
    /* D3806C 8006F2D0 1800A3AF */   sw        $v1, 0x18($sp)
    /* D38070 8006F2D4 04000424 */  addiu      $a0, $zero, 0x4
    /* D38074 8006F2D8 CABC0108 */  j          .Llevel_10_8006F328
    /* D38078 8006F2DC 29000524 */   addiu     $a1, $zero, 0x29
  .Llevel_10_8006F2E0:
    /* D3807C 8006F2E0 0780033C */  lui        $v1, %hi(D_8006A048)
    /* D38080 8006F2E4 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* D38084 8006F2E8 04000224 */  addiu      $v0, $zero, 0x4
    /* D38088 8006F2EC 14006214 */  bne        $v1, $v0, .Llevel_10_8006F340
    /* D3808C 8006F2F0 1000A427 */   addiu     $a0, $sp, 0x10
    /* D38090 8006F2F4 1800A28F */  lw         $v0, 0x18($sp)
    /* D38094 8006F2F8 00080524 */  addiu      $a1, $zero, 0x800
    /* D38098 8006F2FC 00044224 */  addiu      $v0, $v0, 0x400
    /* D3809C 8006F300 A1FB000C */  jal        func_8003EE84
    /* D380A0 8006F304 1800A2AF */   sw        $v0, 0x18($sp)
    /* D380A4 8006F308 0D004010 */  beqz       $v0, .Llevel_10_8006F340
    /* D380A8 8006F30C 1800A2AF */   sw        $v0, 0x18($sp)
    /* D380AC 8006F310 0780023C */  lui        $v0, %hi(D_8006ABA4)
    /* D380B0 8006F314 A4AB428C */  lw         $v0, %lo(D_8006ABA4)($v0)
    /* D380B4 8006F318 00000000 */  nop
    /* D380B8 8006F31C 08004010 */  beqz       $v0, .Llevel_10_8006F340
    /* D380BC 8006F320 06000424 */   addiu     $a0, $zero, 0x6
    /* D380C0 8006F324 2E000524 */  addiu      $a1, $zero, 0x2E
  .Llevel_10_8006F328:
    /* D380C4 8006F328 1000A627 */  addiu      $a2, $sp, 0x10
    /* D380C8 8006F32C 0680023C */  lui        $v0, %hi(D_800670FC)
    /* D380CC 8006F330 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* D380D0 8006F334 00000000 */  nop
    /* D380D4 8006F338 09F84000 */  jalr       $v0
    /* D380D8 8006F33C 21380000 */   addu      $a3, $zero, $zero
  .Llevel_10_8006F340:
    /* D380DC 8006F340 0780103C */  lui        $s0, %hi(D_8006A058)
    /* D380E0 8006F344 58A01026 */  addiu      $s0, $s0, %lo(D_8006A058)
    /* D380E4 8006F348 0000028E */  lw         $v0, 0x0($s0)
    /* D380E8 8006F34C 00000000 */  nop
    /* D380EC 8006F350 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* D380F0 8006F354 01086228 */  slti       $v0, $v1, 0x801
    /* D380F4 8006F358 03004014 */  bnez       $v0, .Llevel_10_8006F368
    /* D380F8 8006F35C 000003AE */   sw        $v1, 0x0($s0)
    /* D380FC 8006F360 00F06224 */  addiu      $v0, $v1, -0x1000
    /* D38100 8006F364 000002AE */  sw         $v0, 0x0($s0)
  .Llevel_10_8006F368:
    /* D38104 8006F368 0000028E */  lw         $v0, 0x0($s0)
    /* D38108 8006F36C 00000000 */  nop
    /* D3810C 8006F370 02004018 */  blez       $v0, .Llevel_10_8006F37C
    /* D38110 8006F374 28000224 */   addiu     $v0, $zero, 0x28
    /* D38114 8006F378 000000AE */  sw         $zero, 0x0($s0)
  .Llevel_10_8006F37C:
    /* D38118 8006F37C 03002216 */  bne        $s1, $v0, .Llevel_10_8006F38C
    /* D3811C 8006F380 01000224 */   addiu     $v0, $zero, 0x1
    /* D38120 8006F384 0780013C */  lui        $at, %hi(D_8006A044)
    /* D38124 8006F388 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
  .Llevel_10_8006F38C:
    /* D38128 8006F38C 686F000C */  jal        func_8001BDA0
    /* D3812C 8006F390 EC000426 */   addiu     $a0, $s0, 0xEC
    /* D38130 8006F394 38000426 */  addiu      $a0, $s0, 0x38
    /* D38134 8006F398 0780013C */  lui        $at, %hi(D_8006A13C)
    /* D38138 8006F39C 3CA120AC */  sw         $zero, %lo(D_8006A13C)($at)
    /* D3813C 8006F3A0 886E000C */  jal        func_8001BA20
    /* D38140 8006F3A4 21280000 */   addu      $a1, $zero, $zero
    /* D38144 8006F3A8 0680033C */  lui        $v1, %hi(D_80067020)
    /* D38148 8006F3AC 2070638C */  lw         $v1, %lo(D_80067020)($v1)
    /* D3814C 8006F3B0 21280000 */  addu       $a1, $zero, $zero
    /* D38150 8006F3B4 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* D38154 8006F3B8 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* D38158 8006F3BC 01000224 */  addiu      $v0, $zero, 0x1
    /* D3815C 8006F3C0 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* D38160 8006F3C4 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* D38164 8006F3C8 08006490 */  lbu        $a0, 0x8($v1)
    /* D38168 8006F3CC C841010C */  jal        func_80050720
    /* D3816C 8006F3D0 21300000 */   addu      $a2, $zero, $zero
    /* D38170 8006F3D4 FFBC0108 */  j          .Llevel_10_8006F3FC
    /* D38174 8006F3D8 00000000 */   nop
  .Llevel_10_8006F3DC:
    /* D38178 8006F3DC 0780033C */  lui        $v1, %hi(D_8006A040)
    /* D3817C 8006F3E0 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* D38180 8006F3E4 2A000224 */  addiu      $v0, $zero, 0x2A
    /* D38184 8006F3E8 07006214 */  bne        $v1, $v0, .Llevel_10_8006F408
    /* D38188 8006F3EC 0B000224 */   addiu     $v0, $zero, 0xB
    /* D3818C 8006F3F0 02000224 */  addiu      $v0, $zero, 0x2
    /* D38190 8006F3F4 0780013C */  lui        $at, %hi(D_8006A044)
    /* D38194 8006F3F8 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
  .Llevel_10_8006F3FC:
    /* D38198 8006F3FC 0780013C */  lui        $at, %hi(D_8006A150)
    /* D3819C 8006F400 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* D381A0 8006F404 0B000224 */  addiu      $v0, $zero, 0xB
  .Llevel_10_8006F408:
    /* D381A4 8006F408 0780013C */  lui        $at, %hi(D_8006A048)
    /* D381A8 8006F40C 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* D381AC 8006F410 D7BD0108 */  j          .Llevel_10_8006F75C
    /* D381B0 8006F414 00000000 */   nop
  .Llevel_10_8006F418:
    /* D381B4 8006F418 0780113C */  lui        $s1, %hi(D_8006A048)
    /* D381B8 8006F41C 48A03126 */  addiu      $s1, $s1, %lo(D_8006A048)
    /* D381BC 8006F420 0000228E */  lw         $v0, 0x0($s1)
    /* D381C0 8006F424 00000000 */  nop
    /* D381C4 8006F428 F5FF4224 */  addiu      $v0, $v0, -0xB
    /* D381C8 8006F42C 0200422C */  sltiu      $v0, $v0, 0x2
    /* D381CC 8006F430 69004014 */  bnez       $v0, .Llevel_10_8006F5D8
    /* D381D0 8006F434 0C000224 */   addiu     $v0, $zero, 0xC
    /* D381D4 8006F438 0680023C */  lui        $v0, %hi(D_800670FC)
    /* D381D8 8006F43C FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* D381DC 8006F440 00000000 */  nop
    /* D381E0 8006F444 31004010 */  beqz       $v0, .Llevel_10_8006F50C
    /* D381E4 8006F448 2000B027 */   addiu     $s0, $sp, 0x20
    /* D381E8 8006F44C 21200002 */  addu       $a0, $s0, $zero
    /* D381EC 8006F450 6C6F000C */  jal        func_8001BDB0
    /* D381F0 8006F454 A8FF2526 */   addiu     $a1, $s1, -0x58
    /* D381F4 8006F458 0000238E */  lw         $v1, 0x0($s1)
    /* D381F8 8006F45C 0A000224 */  addiu      $v0, $zero, 0xA
    /* D381FC 8006F460 11006214 */  bne        $v1, $v0, .Llevel_10_8006F4A8
    /* D38200 8006F464 00000000 */   nop
    /* D38204 8006F468 0780033C */  lui        $v1, %hi(D_8006A018)
    /* D38208 8006F46C 18A0638C */  lw         $v1, %lo(D_8006A018)($v1)
    /* D3820C 8006F470 00000000 */  nop
    /* D38210 8006F474 0C006104 */  bgez       $v1, .Llevel_10_8006F4A8
    /* D38214 8006F478 06000424 */   addiu     $a0, $zero, 0x6
    /* D38218 8006F47C 2E000524 */  addiu      $a1, $zero, 0x2E
    /* D3821C 8006F480 21300002 */  addu       $a2, $s0, $zero
    /* D38220 8006F484 21380000 */  addu       $a3, $zero, $zero
    /* D38224 8006F488 0680023C */  lui        $v0, %hi(D_800670FC)
    /* D38228 8006F48C FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* D3822C 8006F490 23180300 */  negu       $v1, $v1
    /* D38230 8006F494 09F84000 */  jalr       $v0
    /* D38234 8006F498 2800A3AF */   sw        $v1, 0x28($sp)
    /* D38238 8006F49C 04000424 */  addiu      $a0, $zero, 0x4
    /* D3823C 8006F4A0 3DBD0108 */  j          .Llevel_10_8006F4F4
    /* D38240 8006F4A4 29000524 */   addiu     $a1, $zero, 0x29
  .Llevel_10_8006F4A8:
    /* D38244 8006F4A8 0780033C */  lui        $v1, %hi(D_8006A048)
    /* D38248 8006F4AC 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* D3824C 8006F4B0 04000224 */  addiu      $v0, $zero, 0x4
    /* D38250 8006F4B4 15006214 */  bne        $v1, $v0, .Llevel_10_8006F50C
    /* D38254 8006F4B8 2000B027 */   addiu     $s0, $sp, 0x20
    /* D38258 8006F4BC 21200002 */  addu       $a0, $s0, $zero
    /* D3825C 8006F4C0 2800A28F */  lw         $v0, 0x28($sp)
    /* D38260 8006F4C4 00080524 */  addiu      $a1, $zero, 0x800
    /* D38264 8006F4C8 00044224 */  addiu      $v0, $v0, 0x400
    /* D38268 8006F4CC A1FB000C */  jal        func_8003EE84
    /* D3826C 8006F4D0 2800A2AF */   sw        $v0, 0x28($sp)
    /* D38270 8006F4D4 0D004010 */  beqz       $v0, .Llevel_10_8006F50C
    /* D38274 8006F4D8 2800A2AF */   sw        $v0, 0x28($sp)
    /* D38278 8006F4DC 0780023C */  lui        $v0, %hi(D_8006ABA4)
    /* D3827C 8006F4E0 A4AB428C */  lw         $v0, %lo(D_8006ABA4)($v0)
    /* D38280 8006F4E4 00000000 */  nop
    /* D38284 8006F4E8 08004010 */  beqz       $v0, .Llevel_10_8006F50C
    /* D38288 8006F4EC 06000424 */   addiu     $a0, $zero, 0x6
    /* D3828C 8006F4F0 2E000524 */  addiu      $a1, $zero, 0x2E
  .Llevel_10_8006F4F4:
    /* D38290 8006F4F4 21300002 */  addu       $a2, $s0, $zero
    /* D38294 8006F4F8 0680023C */  lui        $v0, %hi(D_800670FC)
    /* D38298 8006F4FC FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* D3829C 8006F500 00000000 */  nop
    /* D382A0 8006F504 09F84000 */  jalr       $v0
    /* D382A4 8006F508 21380000 */   addu      $a3, $zero, $zero
  .Llevel_10_8006F50C:
    /* D382A8 8006F50C 0780103C */  lui        $s0, %hi(D_8006A040)
    /* D382AC 8006F510 40A01026 */  addiu      $s0, $s0, %lo(D_8006A040)
    /* D382B0 8006F514 0000038E */  lw         $v1, 0x0($s0)
    /* D382B4 8006F518 2E000224 */  addiu      $v0, $zero, 0x2E
    /* D382B8 8006F51C 07006214 */  bne        $v1, $v0, .Llevel_10_8006F53C
    /* D382BC 8006F520 00000000 */   nop
    /* D382C0 8006F524 0780023C */  lui        $v0, %hi(D_8006A058)
    /* D382C4 8006F528 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* D382C8 8006F52C 00000000 */  nop
    /* D382CC 8006F530 00FC4224 */  addiu      $v0, $v0, -0x400
    /* D382D0 8006F534 0780013C */  lui        $at, %hi(D_8006A058)
    /* D382D4 8006F538 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_10_8006F53C:
    /* D382D8 8006F53C 0780023C */  lui        $v0, %hi(D_8006A058)
    /* D382DC 8006F540 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* D382E0 8006F544 00000000 */  nop
    /* D382E4 8006F548 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* D382E8 8006F54C 01086228 */  slti       $v0, $v1, 0x801
    /* D382EC 8006F550 0780013C */  lui        $at, %hi(D_8006A058)
    /* D382F0 8006F554 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* D382F4 8006F558 03004014 */  bnez       $v0, .Llevel_10_8006F568
    /* D382F8 8006F55C 00F06224 */   addiu     $v0, $v1, -0x1000
    /* D382FC 8006F560 0780013C */  lui        $at, %hi(D_8006A058)
    /* D38300 8006F564 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_10_8006F568:
    /* D38304 8006F568 0780023C */  lui        $v0, %hi(D_8006A058)
    /* D38308 8006F56C 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* D3830C 8006F570 00000000 */  nop
    /* D38310 8006F574 03004018 */  blez       $v0, .Llevel_10_8006F584
    /* D38314 8006F578 01000224 */   addiu     $v0, $zero, 0x1
    /* D38318 8006F57C 0780013C */  lui        $at, %hi(D_8006A058)
    /* D3831C 8006F580 58A020AC */  sw         $zero, %lo(D_8006A058)($at)
  .Llevel_10_8006F584:
    /* D38320 8006F584 0780013C */  lui        $at, %hi(D_8006A044)
    /* D38324 8006F588 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* D38328 8006F58C 686F000C */  jal        func_8001BDA0
    /* D3832C 8006F590 04010426 */   addiu     $a0, $s0, 0x104
    /* D38330 8006F594 50000426 */  addiu      $a0, $s0, 0x50
    /* D38334 8006F598 0780013C */  lui        $at, %hi(D_8006A13C)
    /* D38338 8006F59C 3CA120AC */  sw         $zero, %lo(D_8006A13C)($at)
    /* D3833C 8006F5A0 886E000C */  jal        func_8001BA20
    /* D38340 8006F5A4 21280000 */   addu      $a1, $zero, $zero
    /* D38344 8006F5A8 0680033C */  lui        $v1, %hi(D_80067020)
    /* D38348 8006F5AC 2070638C */  lw         $v1, %lo(D_80067020)($v1)
    /* D3834C 8006F5B0 21280000 */  addu       $a1, $zero, $zero
    /* D38350 8006F5B4 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* D38354 8006F5B8 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* D38358 8006F5BC 01000224 */  addiu      $v0, $zero, 0x1
    /* D3835C 8006F5C0 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* D38360 8006F5C4 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* D38364 8006F5C8 08006490 */  lbu        $a0, 0x8($v1)
    /* D38368 8006F5CC C841010C */  jal        func_80050720
    /* D3836C 8006F5D0 21300000 */   addu      $a2, $zero, $zero
    /* D38370 8006F5D4 0C000224 */  addiu      $v0, $zero, 0xC
  .Llevel_10_8006F5D8:
    /* D38374 8006F5D8 0780013C */  lui        $at, %hi(D_8006A048)
    /* D38378 8006F5DC 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* D3837C 8006F5E0 0200023C */  lui        $v0, (0x20000 >> 16)
    /* D38380 8006F5E4 0780013C */  lui        $at, %hi(D_8006A128)
    /* D38384 8006F5E8 28A122AC */  sw         $v0, %lo(D_8006A128)($at)
    /* D38388 8006F5EC D7BD0108 */  j          .Llevel_10_8006F75C
    /* D3838C 8006F5F0 00000000 */   nop
  .Llevel_10_8006F5F4:
    /* D38390 8006F5F4 0780033C */  lui        $v1, %hi(D_8006A048)
    /* D38394 8006F5F8 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* D38398 8006F5FC 0A000224 */  addiu      $v0, $zero, 0xA
    /* D3839C 8006F600 56006210 */  beq        $v1, $v0, .Llevel_10_8006F75C
    /* D383A0 8006F604 21280000 */   addu      $a1, $zero, $zero
    /* D383A4 8006F608 0680023C */  lui        $v0, %hi(D_80067020)
    /* D383A8 8006F60C 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* D383AC 8006F610 00000000 */  nop
    /* D383B0 8006F614 07004490 */  lbu        $a0, 0x7($v0)
    /* D383B4 8006F618 C841010C */  jal        func_80050720
    /* D383B8 8006F61C 21300000 */   addu      $a2, $zero, $zero
    /* D383BC 8006F620 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* D383C0 8006F624 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* D383C4 8006F628 0780113C */  lui        $s1, %hi(D_8006A13C)
    /* D383C8 8006F62C 3CA13126 */  addiu      $s1, $s1, %lo(D_8006A13C)
    /* D383CC 8006F630 23100200 */  negu       $v0, $v0
    /* D383D0 8006F634 83100200 */  sra        $v0, $v0, 2
    /* D383D4 8006F638 000022AE */  sw         $v0, 0x0($s1)
    /* D383D8 8006F63C 0780033C */  lui        $v1, %hi(D_8006A048)
    /* D383DC 8006F640 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* D383E0 8006F644 08000224 */  addiu      $v0, $zero, 0x8
    /* D383E4 8006F648 06006210 */  beq        $v1, $v0, .Llevel_10_8006F664
    /* D383E8 8006F64C 00590224 */   addiu     $v0, $zero, 0x5900
    /* D383EC 8006F650 0780013C */  lui        $at, %hi(D_8006A140)
    /* D383F0 8006F654 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
    /* D383F4 8006F658 0A000224 */  addiu      $v0, $zero, 0xA
    /* D383F8 8006F65C 0780013C */  lui        $at, %hi(D_8006A048)
    /* D383FC 8006F660 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
  .Llevel_10_8006F664:
    /* D38400 8006F664 54FF2426 */  addiu      $a0, $s1, -0xAC
    /* D38404 8006F668 0780013C */  lui        $at, %hi(D_8006A044)
    /* D38408 8006F66C 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* D3840C 8006F670 886E000C */  jal        func_8001BA20
    /* D38410 8006F674 21280000 */   addu      $a1, $zero, $zero
    /* D38414 8006F678 3000B027 */  addiu      $s0, $sp, 0x30
    /* D38418 8006F67C 21200002 */  addu       $a0, $s0, $zero
    /* D3841C 8006F680 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* D38420 8006F684 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* D38424 8006F688 01000224 */  addiu      $v0, $zero, 0x1
    /* D38428 8006F68C 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* D3842C 8006F690 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* D38430 8006F694 0780013C */  lui        $at, %hi(D_8006A1AD)
    /* D38434 8006F698 ADA122A0 */  sb         $v0, %lo(D_8006A1AD)($at)
    /* D38438 8006F69C 6C6F000C */  jal        func_8001BDB0
    /* D3843C 8006F6A0 B4FE2526 */   addiu     $a1, $s1, -0x14C
    /* D38440 8006F6A4 21200002 */  addu       $a0, $s0, $zero
    /* D38444 8006F6A8 3800A28F */  lw         $v0, 0x38($sp)
    /* D38448 8006F6AC 00080524 */  addiu      $a1, $zero, 0x800
    /* D3844C 8006F6B0 00044224 */  addiu      $v0, $v0, 0x400
    /* D38450 8006F6B4 A1FB000C */  jal        func_8003EE84
    /* D38454 8006F6B8 3800A2AF */   sw        $v0, 0x38($sp)
    /* D38458 8006F6BC 27004010 */  beqz       $v0, .Llevel_10_8006F75C
    /* D3845C 8006F6C0 3800A2AF */   sw        $v0, 0x38($sp)
    /* D38460 8006F6C4 0780023C */  lui        $v0, %hi(D_8006ABA4)
    /* D38464 8006F6C8 A4AB428C */  lw         $v0, %lo(D_8006ABA4)($v0)
    /* D38468 8006F6CC 00000000 */  nop
    /* D3846C 8006F6D0 22004010 */  beqz       $v0, .Llevel_10_8006F75C
    /* D38470 8006F6D4 00000000 */   nop
    /* D38474 8006F6D8 0680023C */  lui        $v0, %hi(D_800670FC)
    /* D38478 8006F6DC FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* D3847C 8006F6E0 00000000 */  nop
    /* D38480 8006F6E4 1D004010 */  beqz       $v0, .Llevel_10_8006F75C
    /* D38484 8006F6E8 0A000424 */   addiu     $a0, $zero, 0xA
    /* D38488 8006F6EC 29000524 */  addiu      $a1, $zero, 0x29
    /* D3848C 8006F6F0 21300002 */  addu       $a2, $s0, $zero
    /* D38490 8006F6F4 09F84000 */  jalr       $v0
    /* D38494 8006F6F8 21380000 */   addu      $a3, $zero, $zero
    /* D38498 8006F6FC 06000424 */  addiu      $a0, $zero, 0x6
    /* D3849C 8006F700 2E000524 */  addiu      $a1, $zero, 0x2E
    /* D384A0 8006F704 21300002 */  addu       $a2, $s0, $zero
    /* D384A4 8006F708 0680023C */  lui        $v0, %hi(D_800670FC)
    /* D384A8 8006F70C FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* D384AC 8006F710 00000000 */  nop
    /* D384B0 8006F714 09F84000 */  jalr       $v0
    /* D384B4 8006F718 21380000 */   addu      $a3, $zero, $zero
    /* D384B8 8006F71C D7BD0108 */  j          .Llevel_10_8006F75C
    /* D384BC 8006F720 00000000 */   nop
  .Llevel_10_8006F724:
    /* D384C0 8006F724 0780033C */  lui        $v1, %hi(D_8006A048)
    /* D384C4 8006F728 48A06324 */  addiu      $v1, $v1, %lo(D_8006A048)
    /* D384C8 8006F72C 0000628C */  lw         $v0, 0x0($v1)
    /* D384CC 8006F730 0D000624 */  addiu      $a2, $zero, 0xD
    /* D384D0 8006F734 09004610 */  beq        $v0, $a2, .Llevel_10_8006F75C
    /* D384D4 8006F738 3C006424 */   addiu     $a0, $v1, 0x3C
    /* D384D8 8006F73C 000066AC */  sw         $a2, 0x0($v1)
    /* D384DC 8006F740 0780013C */  lui        $at, %hi(D_8006A044)
    /* D384E0 8006F744 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* D384E4 8006F748 6C6F000C */  jal        func_8001BDB0
    /* D384E8 8006F74C 48006524 */   addiu     $a1, $v1, 0x48
    /* D384EC 8006F750 01000224 */  addiu      $v0, $zero, 0x1
    /* D384F0 8006F754 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* D384F4 8006F758 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
  .Llevel_10_8006F75C:
    /* D384F8 8006F75C 4800BF8F */  lw         $ra, 0x48($sp)
    /* D384FC 8006F760 4400B18F */  lw         $s1, 0x44($sp)
    /* D38500 8006F764 4000B08F */  lw         $s0, 0x40($sp)
    /* D38504 8006F768 5000BD27 */  addiu      $sp, $sp, 0x50
    /* D38508 8006F76C 0800E003 */  jr         $ra
    /* D3850C 8006F770 00000000 */   nop
endlabel func_level_10_8006F0A0
