.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_10_8006D388

dlabel jtbl_level_10_8006D388
    /* D36124 8006D388 70F00680 */ .word .Llevel_10_8006F070
    /* D36128 8006D38C 58F00680 */ .word .Llevel_10_8006F058
    /* D3612C 8006D390 90F00680 */ .word .Llevel_10_8006F090
    /* D36130 8006D394 90F00680 */ .word .Llevel_10_8006F090
    /* D36134 8006D398 90F00680 */ .word .Llevel_10_8006F090
    /* D36138 8006D39C 90F00680 */ .word .Llevel_10_8006F090
    /* D3613C 8006D3A0 90F00680 */ .word .Llevel_10_8006F090
    /* D36140 8006D3A4 90F00680 */ .word .Llevel_10_8006F090
    /* D36144 8006D3A8 90F00680 */ .word .Llevel_10_8006F090
    /* D36148 8006D3AC 90F00680 */ .word .Llevel_10_8006F090
    /* D3614C 8006D3B0 90F00680 */ .word .Llevel_10_8006F090
    /* D36150 8006D3B4 90F00680 */ .word .Llevel_10_8006F090
    /* D36154 8006D3B8 90F00680 */ .word .Llevel_10_8006F090
    /* D36158 8006D3BC 90F00680 */ .word .Llevel_10_8006F090
    /* D3615C 8006D3C0 90F00680 */ .word .Llevel_10_8006F090
    /* D36160 8006D3C4 90F00680 */ .word .Llevel_10_8006F090
    /* D36164 8006D3C8 90F00680 */ .word .Llevel_10_8006F090
    /* D36168 8006D3CC 90F00680 */ .word .Llevel_10_8006F090
    /* D3616C 8006D3D0 90F00680 */ .word .Llevel_10_8006F090
    /* D36170 8006D3D4 90F00680 */ .word .Llevel_10_8006F090
    /* D36174 8006D3D8 58F00680 */ .word .Llevel_10_8006F058
    /* D36178 8006D3DC 90F00680 */ .word .Llevel_10_8006F090
    /* D3617C 8006D3E0 90F00680 */ .word .Llevel_10_8006F090
    /* D36180 8006D3E4 90F00680 */ .word .Llevel_10_8006F090
    /* D36184 8006D3E8 90F00680 */ .word .Llevel_10_8006F090
    /* D36188 8006D3EC 58F00680 */ .word .Llevel_10_8006F058
    /* D3618C 8006D3F0 58F00680 */ .word .Llevel_10_8006F058
    /* D36190 8006D3F4 90F00680 */ .word .Llevel_10_8006F090
    /* D36194 8006D3F8 90F00680 */ .word .Llevel_10_8006F090
    /* D36198 8006D3FC 80F00680 */ .word .Llevel_10_8006F080
    /* D3619C 8006D400 90F00680 */ .word .Llevel_10_8006F090
    /* D361A0 8006D404 90F00680 */ .word .Llevel_10_8006F090
    /* D361A4 8006D408 80F00680 */ .word .Llevel_10_8006F080
    /* D361A8 8006D40C 80F00680 */ .word .Llevel_10_8006F080
    /* D361AC 8006D410 80F00680 */ .word .Llevel_10_8006F080
    /* D361B0 8006D414 00000000 */ .word 0x00000000
enddlabel jtbl_level_10_8006D388


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_10_8006F008, 0x98

glabel func_level_10_8006F008
    /* D37DA4 8006F008 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* D37DA8 8006F00C 00210400 */  sll        $a0, $a0, 4
    /* D37DAC 8006F010 0780023C */  lui        $v0, %hi(D_800683B0)
    /* D37DB0 8006F014 B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* D37DB4 8006F018 0780033C */  lui        $v1, %hi(D_8006A040)
    /* D37DB8 8006F01C 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* D37DBC 8006F020 21208200 */  addu       $a0, $a0, $v0
    /* D37DC0 8006F024 1000BFAF */  sw         $ra, 0x10($sp)
    /* D37DC4 8006F028 0680013C */  lui        $at, %hi(D_80066F38)
    /* D37DC8 8006F02C 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* D37DCC 8006F030 EEFF6324 */  addiu      $v1, $v1, -0x12
    /* D37DD0 8006F034 2300622C */  sltiu      $v0, $v1, 0x23
    /* D37DD4 8006F038 15004010 */  beqz       $v0, .Llevel_10_8006F090
    /* D37DD8 8006F03C 80100300 */   sll       $v0, $v1, 2
    /* D37DDC 8006F040 0780013C */  lui        $at, %hi(jtbl_level_10_8006D388)
    /* D37DE0 8006F044 21082200 */  addu       $at, $at, $v0
    /* D37DE4 8006F048 88D3228C */  lw         $v0, %lo(jtbl_level_10_8006D388)($at)
    /* D37DE8 8006F04C 00000000 */  nop
    /* D37DEC 8006F050 08004000 */  jr         $v0
    /* D37DF0 8006F054 00000000 */   nop
  .Llevel_10_8006F058:
    /* D37DF4 8006F058 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* D37DF8 8006F05C C4A08424 */  addiu      $a0, $a0, %lo(D_8006A0C4)
    /* D37DFC 8006F060 E3B6000C */  jal        func_8002DB8C
    /* D37E00 8006F064 00000000 */   nop
    /* D37E04 8006F068 24BC0108 */  j          .Llevel_10_8006F090
    /* D37E08 8006F06C 00000000 */   nop
  .Llevel_10_8006F070:
    /* D37E0C 8006F070 E3B6000C */  jal        func_8002DB8C
    /* D37E10 8006F074 21200000 */   addu      $a0, $zero, $zero
    /* D37E14 8006F078 24BC0108 */  j          .Llevel_10_8006F090
    /* D37E18 8006F07C 00000000 */   nop
  .Llevel_10_8006F080:
    /* D37E1C 8006F080 0780043C */  lui        $a0, %hi(D_8006A0D0)
    /* D37E20 8006F084 D0A08424 */  addiu      $a0, $a0, %lo(D_8006A0D0)
    /* D37E24 8006F088 03B8000C */  jal        func_8002E00C
    /* D37E28 8006F08C 00000000 */   nop
  .Llevel_10_8006F090:
    /* D37E2C 8006F090 1000BF8F */  lw         $ra, 0x10($sp)
    /* D37E30 8006F094 1800BD27 */  addiu      $sp, $sp, 0x18
    /* D37E34 8006F098 0800E003 */  jr         $ra
    /* D37E38 8006F09C 00000000 */   nop
endlabel func_level_10_8006F008
