.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
nonmatching jtbl_80010848

dlabel jtbl_80010848
    /* 1048 80010848 90C90180 */ .word .L8001C990
    /* 104C 8001084C 90CA0180 */ .word .L8001CA90
    /* 1050 80010850 90CA0180 */ .word .L8001CA90
    /* 1054 80010854 90CA0180 */ .word .L8001CA90
    /* 1058 80010858 90CA0180 */ .word .L8001CA90
    /* 105C 8001085C 90CA0180 */ .word .L8001CA90
    /* 1060 80010860 90CA0180 */ .word .L8001CA90
    /* 1064 80010864 90CA0180 */ .word .L8001CA90
    /* 1068 80010868 90CA0180 */ .word .L8001CA90
    /* 106C 8001086C 90CA0180 */ .word .L8001CA90
    /* 1070 80010870 90CA0180 */ .word .L8001CA90
    /* 1074 80010874 90CA0180 */ .word .L8001CA90
    /* 1078 80010878 90CA0180 */ .word .L8001CA90
    /* 107C 8001087C 90CA0180 */ .word .L8001CA90
    /* 1080 80010880 90CA0180 */ .word .L8001CA90
    /* 1084 80010884 90CA0180 */ .word .L8001CA90
    /* 1088 80010888 90CA0180 */ .word .L8001CA90
    /* 108C 8001088C 90CA0180 */ .word .L8001CA90
    /* 1090 80010890 C4C90180 */ .word .L8001C9C4
    /* 1094 80010894 90CA0180 */ .word .L8001CA90
    /* 1098 80010898 90CA0180 */ .word .L8001CA90
    /* 109C 8001089C 90CA0180 */ .word .L8001CA90
    /* 10A0 800108A0 90CA0180 */ .word .L8001CA90
    /* 10A4 800108A4 90CA0180 */ .word .L8001CA90
    /* 10A8 800108A8 90CA0180 */ .word .L8001CA90
    /* 10AC 800108AC 90CA0180 */ .word .L8001CA90
    /* 10B0 800108B0 90CA0180 */ .word .L8001CA90
    /* 10B4 800108B4 90CA0180 */ .word .L8001CA90
    /* 10B8 800108B8 F8C90180 */ .word .L8001C9F8
    /* 10BC 800108BC 90CA0180 */ .word .L8001CA90
    /* 10C0 800108C0 90CA0180 */ .word .L8001CA90
    /* 10C4 800108C4 90CA0180 */ .word .L8001CA90
    /* 10C8 800108C8 90CA0180 */ .word .L8001CA90
    /* 10CC 800108CC 90CA0180 */ .word .L8001CA90
    /* 10D0 800108D0 90CA0180 */ .word .L8001CA90
    /* 10D4 800108D4 90CA0180 */ .word .L8001CA90
    /* 10D8 800108D8 90CA0180 */ .word .L8001CA90
    /* 10DC 800108DC 90CA0180 */ .word .L8001CA90
    /* 10E0 800108E0 90CA0180 */ .word .L8001CA90
    /* 10E4 800108E4 2CCA0180 */ .word .L8001CA2C
    /* 10E8 800108E8 90CA0180 */ .word .L8001CA90
    /* 10EC 800108EC 90CA0180 */ .word .L8001CA90
    /* 10F0 800108F0 90CA0180 */ .word .L8001CA90
    /* 10F4 800108F4 90CA0180 */ .word .L8001CA90
    /* 10F8 800108F8 90CA0180 */ .word .L8001CA90
    /* 10FC 800108FC 90CA0180 */ .word .L8001CA90
    /* 1100 80010900 90CA0180 */ .word .L8001CA90
    /* 1104 80010904 90CA0180 */ .word .L8001CA90
    /* 1108 80010908 90CA0180 */ .word .L8001CA90
    /* 110C 8001090C 5CCA0180 */ .word .L8001CA5C
enddlabel jtbl_80010848


.section .text
/* Generated by spimdisasm 1.39.3 */

nonmatching func_8001C734, 0xEC8

glabel func_8001C734
    /* CF34 8001C734 60FFBD27 */  addiu      $sp, $sp, -0xA0
    /* CF38 8001C738 8000B2AF */  sw         $s2, 0x80($sp)
    /* CF3C 8001C73C 21908000 */  addu       $s2, $a0, $zero
    /* CF40 8001C740 9400B7AF */  sw         $s7, 0x94($sp)
    /* CF44 8001C744 21B80000 */  addu       $s7, $zero, $zero
    /* CF48 8001C748 01000324 */  addiu      $v1, $zero, 0x1
    /* CF4C 8001C74C 0680023C */  lui        $v0, %hi(D_80066F54)
    /* CF50 8001C750 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* CF54 8001C754 0680053C */  lui        $a1, %hi(D_800676BC)
    /* CF58 8001C758 BC76A524 */  addiu      $a1, $a1, %lo(D_800676BC)
    /* CF5C 8001C75C 9C00BFAF */  sw         $ra, 0x9C($sp)
    /* CF60 8001C760 9800BEAF */  sw         $fp, 0x98($sp)
    /* CF64 8001C764 9000B6AF */  sw         $s6, 0x90($sp)
    /* CF68 8001C768 8C00B5AF */  sw         $s5, 0x8C($sp)
    /* CF6C 8001C76C 8800B4AF */  sw         $s4, 0x88($sp)
    /* CF70 8001C770 8400B3AF */  sw         $s3, 0x84($sp)
    /* CF74 8001C774 7C00B1AF */  sw         $s1, 0x7C($sp)
    /* CF78 8001C778 7800B0AF */  sw         $s0, 0x78($sp)
    /* CF7C 8001C77C 0780013C */  lui        $at, %hi(D_8006B084)
    /* CF80 8001C780 21082200 */  addu       $at, $at, $v0
    /* CF84 8001C784 84B023A0 */  sb         $v1, %lo(D_8006B084)($at)
    /* CF88 8001C788 0680023C */  lui        $v0, %hi(D_80066EE4)
    /* CF8C 8001C78C E46E428C */  lw         $v0, %lo(D_80066EE4)($v0)
    /* CF90 8001C790 21A04002 */  addu       $s4, $s2, $zero
    /* CF94 8001C794 0680013C */  lui        $at, %hi(D_8006700C)
    /* CF98 8001C798 0C7020AC */  sw         $zero, %lo(D_8006700C)($at)
    /* CF9C 8001C79C 0680013C */  lui        $at, %hi(D_80067008)
    /* CFA0 8001C7A0 087020AC */  sw         $zero, %lo(D_80067008)($at)
    /* CFA4 8001C7A4 0680013C */  lui        $at, %hi(D_80067100)
    /* CFA8 8001C7A8 007120AC */  sw         $zero, %lo(D_80067100)($at)
    /* CFAC 8001C7AC 0680013C */  lui        $at, %hi(D_8006701C)
    /* CFB0 8001C7B0 1C7020AC */  sw         $zero, %lo(D_8006701C)($at)
    /* CFB4 8001C7B4 16004010 */  beqz       $v0, .L8001C810
    /* CFB8 8001C7B8 0000A0AC */   sw        $zero, 0x0($a1)
    /* CFBC 8001C7BC 0680043C */  lui        $a0, %hi(D_80066F54)
    /* CFC0 8001C7C0 546F848C */  lw         $a0, %lo(D_80066F54)($a0)
    /* CFC4 8001C7C4 00000000 */  nop
    /* CFC8 8001C7C8 80100400 */  sll        $v0, $a0, 2
    /* CFCC 8001C7CC 0780013C */  lui        $at, %hi(D_8006AC04)
    /* CFD0 8001C7D0 21082200 */  addu       $at, $at, $v0
    /* CFD4 8001C7D4 04AC238C */  lw         $v1, %lo(D_8006AC04)($at)
    /* CFD8 8001C7D8 90010224 */  addiu      $v0, $zero, 0x190
    /* CFDC 8001C7DC 0D006214 */  bne        $v1, $v0, .L8001C814
    /* CFE0 8001C7E0 09001024 */   addiu     $s0, $zero, 0x9
    /* CFE4 8001C7E4 0780013C */  lui        $at, %hi(D_80069FD0)
    /* CFE8 8001C7E8 21082400 */  addu       $at, $at, $a0
    /* CFEC 8001C7EC D09F2390 */  lbu        $v1, %lo(D_80069FD0)($at)
    /* CFF0 8001C7F0 0680013C */  lui        $at, %hi(D_800648D4)
    /* CFF4 8001C7F4 21082400 */  addu       $at, $at, $a0
    /* CFF8 8001C7F8 D4482290 */  lbu        $v0, %lo(D_800648D4)($at)
    /* CFFC 8001C7FC 00000000 */  nop
    /* D000 8001C800 04006214 */  bne        $v1, $v0, .L8001C814
    /* D004 8001C804 00000000 */   nop
    /* D008 8001C808 96000224 */  addiu      $v0, $zero, 0x96
    /* D00C 8001C80C 0000A2AC */  sw         $v0, 0x0($a1)
  .L8001C810:
    /* D010 8001C810 09001024 */  addiu      $s0, $zero, 0x9
  .L8001C814:
    /* D014 8001C814 0780023C */  lui        $v0, %hi(D_8006AC01)
    /* D018 8001C818 01AC4224 */  addiu      $v0, $v0, %lo(D_8006AC01)
    /* D01C 8001C81C 0680013C */  lui        $at, %hi(D_80066FEC)
    /* D020 8001C820 EC6F20AC */  sw         $zero, %lo(D_80066FEC)($at)
    /* D024 8001C824 0680013C */  lui        $at, %hi(D_80067084)
    /* D028 8001C828 847020AC */  sw         $zero, %lo(D_80067084)($at)
    /* D02C 8001C82C 0680013C */  lui        $at, %hi(D_80067088)
    /* D030 8001C830 887020AC */  sw         $zero, %lo(D_80067088)($at)
    /* D034 8001C834 0680013C */  lui        $at, %hi(D_8006708C)
    /* D038 8001C838 8C7020AC */  sw         $zero, %lo(D_8006708C)($at)
    /* D03C 8001C83C 0680013C */  lui        $at, %hi(D_80066F30)
    /* D040 8001C840 306F20AC */  sw         $zero, %lo(D_80066F30)($at)
    /* D044 8001C844 0680013C */  lui        $at, %hi(D_80066FB0)
    /* D048 8001C848 B06F20AC */  sw         $zero, %lo(D_80066FB0)($at)
    /* D04C 8001C84C 0680013C */  lui        $at, %hi(D_80066EFC)
    /* D050 8001C850 FC6E20AC */  sw         $zero, %lo(D_80066EFC)($at)
    /* D054 8001C854 0680013C */  lui        $at, %hi(D_80066F50)
    /* D058 8001C858 506F20AC */  sw         $zero, %lo(D_80066F50)($at)
    /* D05C 8001C85C 0680013C */  lui        $at, %hi(D_80067038)
    /* D060 8001C860 387020A0 */  sb         $zero, %lo(D_80067038)($at)
    /* D064 8001C864 0680013C */  lui        $at, %hi(D_800670F4)
    /* D068 8001C868 F47020A0 */  sb         $zero, %lo(D_800670F4)($at)
  .L8001C86C:
    /* D06C 8001C86C 000040A0 */  sb         $zero, 0x0($v0)
    /* D070 8001C870 FFFF1026 */  addiu      $s0, $s0, -0x1
    /* D074 8001C874 FDFF0106 */  bgez       $s0, .L8001C86C
    /* D078 8001C878 FFFF4224 */   addiu     $v0, $v0, -0x1
    /* D07C 8001C87C FFFF0224 */  addiu      $v0, $zero, -0x1
    /* D080 8001C880 0680103C */  lui        $s0, %hi(D_80067414)
    /* D084 8001C884 14741026 */  addiu      $s0, $s0, %lo(D_80067414)
    /* D088 8001C888 0680013C */  lui        $at, %hi(D_80066F5C)
    /* D08C 8001C88C 5C6F22AC */  sw         $v0, %lo(D_80066F5C)($at)
    /* D090 8001C890 0000028E */  lw         $v0, 0x0($s0)
    /* D094 8001C894 0780113C */  lui        $s1, %hi(D_8006A054)
    /* D098 8001C898 54A03126 */  addiu      $s1, $s1, %lo(D_8006A054)
    /* D09C 8001C89C 000020AE */  sw         $zero, 0x0($s1)
    /* D0A0 8001C8A0 0780013C */  lui        $at, %hi(D_8006A058)
    /* D0A4 8001C8A4 58A020AC */  sw         $zero, %lo(D_8006A058)($at)
    /* D0A8 8001C8A8 0D004010 */  beqz       $v0, .L8001C8E0
    /* D0AC 8001C8AC 9CFF2426 */   addiu     $a0, $s1, -0x64
    /* D0B0 8001C8B0 24001026 */  addiu      $s0, $s0, 0x24
    /* D0B4 8001C8B4 6C6F000C */  jal        func_8001BDB0
    /* D0B8 8001C8B8 21280002 */   addu      $a1, $s0, $zero
    /* D0BC 8001C8BC C8002426 */  addiu      $a0, $s1, 0xC8
    /* D0C0 8001C8C0 6C6F000C */  jal        func_8001BDB0
    /* D0C4 8001C8C4 21280002 */   addu      $a1, $s0, $zero
    /* D0C8 8001C8C8 0680023C */  lui        $v0, %hi(D_80067444)
    /* D0CC 8001C8CC 4474428C */  lw         $v0, %lo(D_80067444)($v0)
    /* D0D0 8001C8D0 0780013C */  lui        $at, %hi(D_8006A05C)
    /* D0D4 8001C8D4 5CA022AC */  sw         $v0, %lo(D_8006A05C)($at)
    /* D0D8 8001C8D8 F3720008 */  j          .L8001CBCC
    /* D0DC 8001C8DC 10005226 */   addiu     $s2, $s2, 0x10
  .L8001C8E0:
    /* D0E0 8001C8E0 0780043C */  lui        $a0, %hi(D_800698BD)
    /* D0E4 8001C8E4 BD988424 */  addiu      $a0, $a0, %lo(D_800698BD)
    /* D0E8 8001C8E8 00008290 */  lbu        $v0, 0x0($a0)
    /* D0EC 8001C8EC 00000000 */  nop
    /* D0F0 8001C8F0 15004010 */  beqz       $v0, .L8001C948
    /* D0F4 8001C8F4 41000224 */   addiu     $v0, $zero, 0x41
    /* D0F8 8001C8F8 0680033C */  lui        $v1, %hi(D_80066F90)
    /* D0FC 8001C8FC 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* D100 8001C900 00000000 */  nop
    /* D104 8001C904 10006214 */  bne        $v1, $v0, .L8001C948
    /* D108 8001C908 0100033C */   lui       $v1, (0x17466 >> 16)
    /* D10C 8001C90C 66746334 */  ori        $v1, $v1, (0x17466 & 0xFFFF)
    /* D110 8001C910 0100023C */  lui        $v0, (0x15670 >> 16)
    /* D114 8001C914 70564234 */  ori        $v0, $v0, (0x15670 & 0xFFFF)
    /* D118 8001C918 0780013C */  lui        $at, %hi(D_80069FF4)
    /* D11C 8001C91C F49F22AC */  sw         $v0, %lo(D_80069FF4)($at)
    /* D120 8001C920 645C0224 */  addiu      $v0, $zero, 0x5C64
    /* D124 8001C924 0780013C */  lui        $at, %hi(D_80069FF8)
    /* D128 8001C928 F89F22AC */  sw         $v0, %lo(D_80069FF8)($at)
    /* D12C 8001C92C 280F0224 */  addiu      $v0, $zero, 0xF28
    /* D130 8001C930 0780013C */  lui        $at, %hi(D_80069FF0)
    /* D134 8001C934 F09F23AC */  sw         $v1, %lo(D_80069FF0)($at)
    /* D138 8001C938 0780013C */  lui        $at, %hi(D_8006A05C)
    /* D13C 8001C93C 5CA022AC */  sw         $v0, %lo(D_8006A05C)($at)
    /* D140 8001C940 AD720008 */  j          .L8001CAB4
    /* D144 8001C944 000080A0 */   sb        $zero, 0x0($a0)
  .L8001C948:
    /* D148 8001C948 0680023C */  lui        $v0, %hi(D_80067024)
    /* D14C 8001C94C 2470428C */  lw         $v0, %lo(D_80067024)($v0)
    /* D150 8001C950 00000000 */  nop
    /* D154 8001C954 4E004010 */  beqz       $v0, .L8001CA90
    /* D158 8001C958 00000000 */   nop
    /* D15C 8001C95C 0680023C */  lui        $v0, %hi(D_80066F90)
    /* D160 8001C960 906F428C */  lw         $v0, %lo(D_80066F90)($v0)
    /* D164 8001C964 00000000 */  nop
    /* D168 8001C968 F3FF4324 */  addiu      $v1, $v0, -0xD
    /* D16C 8001C96C 3200622C */  sltiu      $v0, $v1, 0x32
    /* D170 8001C970 47004010 */  beqz       $v0, .L8001CA90
    /* D174 8001C974 80100300 */   sll       $v0, $v1, 2
    /* D178 8001C978 0180013C */  lui        $at, %hi(jtbl_80010848)
    /* D17C 8001C97C 21082200 */  addu       $at, $at, $v0
    /* D180 8001C980 4808228C */  lw         $v0, %lo(jtbl_80010848)($at)
    /* D184 8001C984 00000000 */  nop
    /* D188 8001C988 08004000 */  jr         $v0
    /* D18C 8001C98C 00000000 */   nop
  .L8001C990:
    /* D190 8001C990 0100033C */  lui        $v1, (0x1D270 >> 16)
    /* D194 8001C994 70D26334 */  ori        $v1, $v1, (0x1D270 & 0xFFFF)
    /* D198 8001C998 0100023C */  lui        $v0, (0x1D283 >> 16)
    /* D19C 8001C99C 83D24234 */  ori        $v0, $v0, (0x1D283 & 0xFFFF)
    /* D1A0 8001C9A0 0780013C */  lui        $at, %hi(D_80069FF4)
    /* D1A4 8001C9A4 F49F22AC */  sw         $v0, %lo(D_80069FF4)($at)
    /* D1A8 8001C9A8 86440224 */  addiu      $v0, $zero, 0x4486
    /* D1AC 8001C9AC 0780013C */  lui        $at, %hi(D_80069FF8)
    /* D1B0 8001C9B0 F89F22AC */  sw         $v0, %lo(D_80069FF8)($at)
    /* D1B4 8001C9B4 0780013C */  lui        $at, %hi(D_80069FF0)
    /* D1B8 8001C9B8 F09F23AC */  sw         $v1, %lo(D_80069FF0)($at)
    /* D1BC 8001C9BC AB720008 */  j          .L8001CAAC
    /* D1C0 8001C9C0 9F0F0224 */   addiu     $v0, $zero, 0xF9F
  .L8001C9C4:
    /* D1C4 8001C9C4 0100033C */  lui        $v1, (0x12090 >> 16)
    /* D1C8 8001C9C8 90206334 */  ori        $v1, $v1, (0x12090 & 0xFFFF)
    /* D1CC 8001C9CC 0100023C */  lui        $v0, (0x165B5 >> 16)
    /* D1D0 8001C9D0 B5654234 */  ori        $v0, $v0, (0x165B5 & 0xFFFF)
    /* D1D4 8001C9D4 0780013C */  lui        $at, %hi(D_80069FF4)
    /* D1D8 8001C9D8 F49F22AC */  sw         $v0, %lo(D_80069FF4)($at)
    /* D1DC 8001C9DC 67730224 */  addiu      $v0, $zero, 0x7367
    /* D1E0 8001C9E0 0780013C */  lui        $at, %hi(D_80069FF8)
    /* D1E4 8001C9E4 F89F22AC */  sw         $v0, %lo(D_80069FF8)($at)
    /* D1E8 8001C9E8 0780013C */  lui        $at, %hi(D_80069FF0)
    /* D1EC 8001C9EC F09F23AC */  sw         $v1, %lo(D_80069FF0)($at)
    /* D1F0 8001C9F0 AB720008 */  j          .L8001CAAC
    /* D1F4 8001C9F4 60040224 */   addiu     $v0, $zero, 0x460
  .L8001C9F8:
    /* D1F8 8001C9F8 0100033C */  lui        $v1, (0x1784F >> 16)
    /* D1FC 8001C9FC 4F786334 */  ori        $v1, $v1, (0x1784F & 0xFFFF)
    /* D200 8001CA00 0100023C */  lui        $v0, (0x10B58 >> 16)
    /* D204 8001CA04 580B4234 */  ori        $v0, $v0, (0x10B58 & 0xFFFF)
    /* D208 8001CA08 0780013C */  lui        $at, %hi(D_80069FF4)
    /* D20C 8001CA0C F49F22AC */  sw         $v0, %lo(D_80069FF4)($at)
    /* D210 8001CA10 6A2C0224 */  addiu      $v0, $zero, 0x2C6A
    /* D214 8001CA14 0780013C */  lui        $at, %hi(D_80069FF8)
    /* D218 8001CA18 F89F22AC */  sw         $v0, %lo(D_80069FF8)($at)
    /* D21C 8001CA1C 0780013C */  lui        $at, %hi(D_80069FF0)
    /* D220 8001CA20 F09F23AC */  sw         $v1, %lo(D_80069FF0)($at)
    /* D224 8001CA24 AB720008 */  j          .L8001CAAC
    /* D228 8001CA28 25060224 */   addiu     $v0, $zero, 0x625
  .L8001CA2C:
    /* D22C 8001CA2C 0100023C */  lui        $v0, (0x18ACB >> 16)
    /* D230 8001CA30 CB8A4234 */  ori        $v0, $v0, (0x18ACB & 0xFFFF)
    /* D234 8001CA34 0780013C */  lui        $at, %hi(D_80069FF0)
    /* D238 8001CA38 F09F22AC */  sw         $v0, %lo(D_80069FF0)($at)
    /* D23C 8001CA3C 56620224 */  addiu      $v0, $zero, 0x6256
    /* D240 8001CA40 0780013C */  lui        $at, %hi(D_80069FF4)
    /* D244 8001CA44 F49F22AC */  sw         $v0, %lo(D_80069FF4)($at)
    /* D248 8001CA48 66590224 */  addiu      $v0, $zero, 0x5966
    /* D24C 8001CA4C 0780013C */  lui        $at, %hi(D_80069FF8)
    /* D250 8001CA50 F89F22AC */  sw         $v0, %lo(D_80069FF8)($at)
    /* D254 8001CA54 AB720008 */  j          .L8001CAAC
    /* D258 8001CA58 D7030224 */   addiu     $v0, $zero, 0x3D7
  .L8001CA5C:
    /* D25C 8001CA5C 0100033C */  lui        $v1, (0x1D1B5 >> 16)
    /* D260 8001CA60 B5D16334 */  ori        $v1, $v1, (0x1D1B5 & 0xFFFF)
    /* D264 8001CA64 0100023C */  lui        $v0, (0x1C405 >> 16)
    /* D268 8001CA68 05C44234 */  ori        $v0, $v0, (0x1C405 & 0xFFFF)
    /* D26C 8001CA6C 0780013C */  lui        $at, %hi(D_80069FF4)
    /* D270 8001CA70 F49F22AC */  sw         $v0, %lo(D_80069FF4)($at)
    /* D274 8001CA74 6B990234 */  ori        $v0, $zero, 0x996B
    /* D278 8001CA78 0780013C */  lui        $at, %hi(D_80069FF8)
    /* D27C 8001CA7C F89F22AC */  sw         $v0, %lo(D_80069FF8)($at)
    /* D280 8001CA80 0780013C */  lui        $at, %hi(D_80069FF0)
    /* D284 8001CA84 F09F23AC */  sw         $v1, %lo(D_80069FF0)($at)
    /* D288 8001CA88 AB720008 */  j          .L8001CAAC
    /* D28C 8001CA8C A00D0224 */   addiu     $v0, $zero, 0xDA0
  .L8001CA90:
    /* D290 8001CA90 0780043C */  lui        $a0, %hi(D_80069FF0)
    /* D294 8001CA94 F09F8424 */  addiu      $a0, $a0, %lo(D_80069FF0)
    /* D298 8001CA98 6C6F000C */  jal        func_8001BDB0
    /* D29C 8001CA9C 21284002 */   addu      $a1, $s2, $zero
    /* D2A0 8001CAA0 0E004292 */  lbu        $v0, 0xE($s2)
    /* D2A4 8001CAA4 00000000 */  nop
    /* D2A8 8001CAA8 00110200 */  sll        $v0, $v0, 4
  .L8001CAAC:
    /* D2AC 8001CAAC 0780013C */  lui        $at, %hi(D_8006A05C)
    /* D2B0 8001CAB0 5CA022AC */  sw         $v0, %lo(D_8006A05C)($at)
  .L8001CAB4:
    /* D2B4 8001CAB4 0780043C */  lui        $a0, %hi(D_8006A11C)
    /* D2B8 8001CAB8 1CA18424 */  addiu      $a0, $a0, %lo(D_8006A11C)
    /* D2BC 8001CABC 6C6F000C */  jal        func_8001BDB0
    /* D2C0 8001CAC0 D4FE8524 */   addiu     $a1, $a0, -0x12C
    /* D2C4 8001CAC4 0680023C */  lui        $v0, %hi(D_8006712C)
    /* D2C8 8001CAC8 2C71428C */  lw         $v0, %lo(D_8006712C)($v0)
    /* D2CC 8001CACC 00000000 */  nop
    /* D2D0 8001CAD0 0D004004 */  bltz       $v0, .L8001CB08
    /* D2D4 8001CAD4 03000224 */   addiu     $v0, $zero, 0x3
    /* D2D8 8001CAD8 0780033C */  lui        $v1, %hi(D_800681C8)
    /* D2DC 8001CADC C881638C */  lw         $v1, %lo(D_800681C8)($v1)
    /* D2E0 8001CAE0 00000000 */  nop
    /* D2E4 8001CAE4 36006214 */  bne        $v1, $v0, .L8001CBC0
    /* D2E8 8001CAE8 00000000 */   nop
    /* D2EC 8001CAEC 0780023C */  lui        $v0, %hi(D_800698FC)
    /* D2F0 8001CAF0 FC98428C */  lw         $v0, %lo(D_800698FC)($v0)
    /* D2F4 8001CAF4 00000000 */  nop
    /* D2F8 8001CAF8 31004010 */  beqz       $v0, .L8001CBC0
    /* D2FC 8001CAFC 00000000 */   nop
    /* D300 8001CB00 C7720008 */  j          .L8001CB1C
    /* D304 8001CB04 00000000 */   nop
  .L8001CB08:
    /* D308 8001CB08 0680033C */  lui        $v1, %hi(D_80066F90)
    /* D30C 8001CB0C 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* D310 8001CB10 0B000224 */  addiu      $v0, $zero, 0xB
    /* D314 8001CB14 23006210 */  beq        $v1, $v0, .L8001CBA4
    /* D318 8001CB18 00000000 */   nop
  .L8001CB1C:
    /* D31C 8001CB1C 0780113C */  lui        $s1, %hi(D_80069FF0)
    /* D320 8001CB20 F09F3126 */  addiu      $s1, $s1, %lo(D_80069FF0)
    /* D324 8001CB24 0680023C */  lui        $v0, %hi(D_80066FD0)
    /* D328 8001CB28 D06F428C */  lw         $v0, %lo(D_80066FD0)($v0)
    /* D32C 8001CB2C 21202002 */  addu       $a0, $s1, $zero
    /* D330 8001CB30 0680013C */  lui        $at, %hi(D_80064B1C)
    /* D334 8001CB34 21082200 */  addu       $at, $at, $v0
    /* D338 8001CB38 1C4B2590 */  lbu        $a1, %lo(D_80064B1C)($at)
    /* D33C 8001CB3C 0680103C */  lui        $s0, %hi(D_80064B3C)
    /* D340 8001CB40 3C4B1026 */  addiu      $s0, $s0, %lo(D_80064B3C)
    /* D344 8001CB44 C0280500 */  sll        $a1, $a1, 3
    /* D348 8001CB48 5970000C */  jal        func_8001C164
    /* D34C 8001CB4C 2128B000 */   addu      $a1, $a1, $s0
    /* D350 8001CB50 0680023C */  lui        $v0, %hi(D_80066FD0)
    /* D354 8001CB54 D06F428C */  lw         $v0, %lo(D_80066FD0)($v0)
    /* D358 8001CB58 0680013C */  lui        $at, %hi(D_80064B1C)
    /* D35C 8001CB5C 21082200 */  addu       $at, $at, $v0
    /* D360 8001CB60 1C4B2590 */  lbu        $a1, %lo(D_80064B1C)($at)
    /* D364 8001CB64 2C012426 */  addiu      $a0, $s1, 0x12C
    /* D368 8001CB68 C0280500 */  sll        $a1, $a1, 3
    /* D36C 8001CB6C 5970000C */  jal        func_8001C164
    /* D370 8001CB70 2128B000 */   addu      $a1, $a1, $s0
    /* D374 8001CB74 0680023C */  lui        $v0, %hi(D_80066FD0)
    /* D378 8001CB78 D06F428C */  lw         $v0, %lo(D_80066FD0)($v0)
    /* D37C 8001CB7C 0680013C */  lui        $at, %hi(D_80064B1C)
    /* D380 8001CB80 21082200 */  addu       $at, $at, $v0
    /* D384 8001CB84 1C4B2290 */  lbu        $v0, %lo(D_80064B1C)($at)
    /* D388 8001CB88 00000000 */  nop
    /* D38C 8001CB8C C0100200 */  sll        $v0, $v0, 3
    /* D390 8001CB90 0680013C */  lui        $at, %hi(D_80064B42)
    /* D394 8001CB94 21082200 */  addu       $at, $at, $v0
    /* D398 8001CB98 424B2284 */  lh         $v0, %lo(D_80064B42)($at)
    /* D39C 8001CB9C 0780013C */  lui        $at, %hi(D_8006A05C)
    /* D3A0 8001CBA0 5CA022AC */  sw         $v0, %lo(D_8006A05C)($at)
  .L8001CBA4:
    /* D3A4 8001CBA4 0680023C */  lui        $v0, %hi(D_8006712C)
    /* D3A8 8001CBA8 2C71428C */  lw         $v0, %lo(D_8006712C)($v0)
    /* D3AC 8001CBAC 00000000 */  nop
    /* D3B0 8001CBB0 03004104 */  bgez       $v0, .L8001CBC0
    /* D3B4 8001CBB4 04000224 */   addiu     $v0, $zero, 0x4
    /* D3B8 8001CBB8 0680013C */  lui        $at, %hi(D_8006712C)
    /* D3BC 8001CBBC 2C7122AC */  sw         $v0, %lo(D_8006712C)($at)
  .L8001CBC0:
    /* D3C0 8001CBC0 0680013C */  lui        $at, %hi(D_80066FD0)
    /* D3C4 8001CBC4 D06F20AC */  sw         $zero, %lo(D_80066FD0)($at)
    /* D3C8 8001CBC8 10005226 */  addiu      $s2, $s2, 0x10
  .L8001CBCC:
    /* D3CC 8001CBCC 0000428E */  lw         $v0, 0x0($s2)
    /* D3D0 8001CBD0 04005226 */  addiu      $s2, $s2, 0x4
    /* D3D4 8001CBD4 0780043C */  lui        $a0, %hi(D_8006AA1C)
    /* D3D8 8001CBD8 1CAA8424 */  addiu      $a0, $a0, %lo(D_8006AA1C)
    /* D3DC 8001CBDC 21280000 */  addu       $a1, $zero, $zero
    /* D3E0 8001CBE0 0680013C */  lui        $at, %hi(D_80066ED8)
    /* D3E4 8001CBE4 D86E22AC */  sw         $v0, %lo(D_80066ED8)($at)
    /* D3E8 8001CBE8 F26C000C */  jal        func_8001B3C8
    /* D3EC 8001CBEC 30010624 */   addiu     $a2, $zero, 0x130
    /* D3F0 8001CBF0 0000428E */  lw         $v0, 0x0($s2)
    /* D3F4 8001CBF4 0780013C */  lui        $at, %hi(D_8006AA2C)
    /* D3F8 8001CBF8 2CAA22AC */  sw         $v0, %lo(D_8006AA2C)($at)
    /* D3FC 8001CBFC 0400428E */  lw         $v0, 0x4($s2)
    /* D400 8001CC00 08005226 */  addiu      $s2, $s2, 0x8
    /* D404 8001CC04 0780013C */  lui        $at, %hi(D_8006AA30)
    /* D408 8001CC08 30AA22AC */  sw         $v0, %lo(D_8006AA30)($at)
    /* D40C 8001CC0C 0000428E */  lw         $v0, 0x0($s2)
    /* D410 8001CC10 21800000 */  addu       $s0, $zero, $zero
    /* D414 8001CC14 0780013C */  lui        $at, %hi(D_8006820C)
    /* D418 8001CC18 0C8222AC */  sw         $v0, %lo(D_8006820C)($at)
    /* D41C 8001CC1C 0400428E */  lw         $v0, 0x4($s2)
    /* D420 8001CC20 08005226 */  addiu      $s2, $s2, 0x8
    /* D424 8001CC24 08005326 */  addiu      $s3, $s2, 0x8
    /* D428 8001CC28 0780013C */  lui        $at, %hi(D_80068210)
    /* D42C 8001CC2C 108222AC */  sw         $v0, %lo(D_80068210)($at)
    /* D430 8001CC30 0000428E */  lw         $v0, 0x0($s2)
    /* D434 8001CC34 0400438E */  lw         $v1, 0x4($s2)
    /* D438 8001CC38 08007226 */  addiu      $s2, $s3, 0x8
    /* D43C 8001CC3C 0680013C */  lui        $at, %hi(D_80066FDC)
    /* D440 8001CC40 DC6F22AC */  sw         $v0, %lo(D_80066FDC)($at)
    /* D444 8001CC44 0680013C */  lui        $at, %hi(D_80066FE0)
    /* D448 8001CC48 E06F23AC */  sw         $v1, %lo(D_80066FE0)($at)
    /* D44C 8001CC4C 0400628E */  lw         $v0, 0x4($s3)
    /* D450 8001CC50 0780033C */  lui        $v1, %hi(D_800681D4)
    /* D454 8001CC54 D4816324 */  addiu      $v1, $v1, %lo(D_800681D4)
    /* D458 8001CC58 0780013C */  lui        $at, %hi(D_800681D8)
    /* D45C 8001CC5C D88132AC */  sw         $s2, %lo(D_800681D8)($at)
    /* D460 8001CC60 0C004018 */  blez       $v0, .L8001CC94
    /* D464 8001CC64 000062AC */   sw        $v0, 0x0($v1)
  .L8001CC68:
    /* D468 8001CC68 0000428E */  lw         $v0, 0x0($s2)
    /* D46C 8001CC6C 01001026 */  addiu      $s0, $s0, 0x1
    /* D470 8001CC70 04004224 */  addiu      $v0, $v0, 0x4
    /* D474 8001CC74 21106202 */  addu       $v0, $s3, $v0
    /* D478 8001CC78 000042AE */  sw         $v0, 0x0($s2)
    /* D47C 8001CC7C 0000628C */  lw         $v0, 0x0($v1)
    /* D480 8001CC80 00000000 */  nop
    /* D484 8001CC84 2A100202 */  slt        $v0, $s0, $v0
    /* D488 8001CC88 F7FF4014 */  bnez       $v0, .L8001CC68
    /* D48C 8001CC8C 04005226 */   addiu     $s2, $s2, 0x4
    /* D490 8001CC90 21800000 */  addu       $s0, $zero, $zero
  .L8001CC94:
    /* D494 8001CC94 0000628E */  lw         $v0, 0x0($s3)
    /* D498 8001CC98 0780033C */  lui        $v1, %hi(D_800681DC)
    /* D49C 8001CC9C DC816324 */  addiu      $v1, $v1, %lo(D_800681DC)
    /* D4A0 8001CCA0 21986202 */  addu       $s3, $s3, $v0
    /* D4A4 8001CCA4 0400628E */  lw         $v0, 0x4($s3)
    /* D4A8 8001CCA8 08007226 */  addiu      $s2, $s3, 0x8
    /* D4AC 8001CCAC 0780013C */  lui        $at, %hi(D_800681E0)
    /* D4B0 8001CCB0 E08132AC */  sw         $s2, %lo(D_800681E0)($at)
    /* D4B4 8001CCB4 0B004018 */  blez       $v0, .L8001CCE4
    /* D4B8 8001CCB8 000062AC */   sw        $v0, 0x0($v1)
  .L8001CCBC:
    /* D4BC 8001CCBC 0000428E */  lw         $v0, 0x0($s2)
    /* D4C0 8001CCC0 01001026 */  addiu      $s0, $s0, 0x1
    /* D4C4 8001CCC4 04004224 */  addiu      $v0, $v0, 0x4
    /* D4C8 8001CCC8 21106202 */  addu       $v0, $s3, $v0
    /* D4CC 8001CCCC 000042AE */  sw         $v0, 0x0($s2)
    /* D4D0 8001CCD0 0000628C */  lw         $v0, 0x0($v1)
    /* D4D4 8001CCD4 00000000 */  nop
    /* D4D8 8001CCD8 2A100202 */  slt        $v0, $s0, $v0
    /* D4DC 8001CCDC F7FF4014 */  bnez       $v0, .L8001CCBC
    /* D4E0 8001CCE0 04005226 */   addiu     $s2, $s2, 0x4
  .L8001CCE4:
    /* D4E4 8001CCE4 21800000 */  addu       $s0, $zero, $zero
    /* D4E8 8001CCE8 0000628E */  lw         $v0, 0x0($s3)
    /* D4EC 8001CCEC 0780033C */  lui        $v1, %hi(D_800681F4)
    /* D4F0 8001CCF0 F4816324 */  addiu      $v1, $v1, %lo(D_800681F4)
    /* D4F4 8001CCF4 21986202 */  addu       $s3, $s3, $v0
    /* D4F8 8001CCF8 0400628E */  lw         $v0, 0x4($s3)
    /* D4FC 8001CCFC 08007226 */  addiu      $s2, $s3, 0x8
    /* D500 8001CD00 0780013C */  lui        $at, %hi(D_800681F8)
    /* D504 8001CD04 F88132AC */  sw         $s2, %lo(D_800681F8)($at)
    /* D508 8001CD08 0C004018 */  blez       $v0, .L8001CD3C
    /* D50C 8001CD0C 000062AC */   sw        $v0, 0x0($v1)
  .L8001CD10:
    /* D510 8001CD10 0000428E */  lw         $v0, 0x0($s2)
    /* D514 8001CD14 01001026 */  addiu      $s0, $s0, 0x1
    /* D518 8001CD18 04004224 */  addiu      $v0, $v0, 0x4
    /* D51C 8001CD1C 21106202 */  addu       $v0, $s3, $v0
    /* D520 8001CD20 000042AE */  sw         $v0, 0x0($s2)
    /* D524 8001CD24 0000628C */  lw         $v0, 0x0($v1)
    /* D528 8001CD28 00000000 */  nop
    /* D52C 8001CD2C 2A100202 */  slt        $v0, $s0, $v0
    /* D530 8001CD30 F7FF4014 */  bnez       $v0, .L8001CD10
    /* D534 8001CD34 04005226 */   addiu     $s2, $s2, 0x4
    /* D538 8001CD38 21800000 */  addu       $s0, $zero, $zero
  .L8001CD3C:
    /* D53C 8001CD3C 0000628E */  lw         $v0, 0x0($s3)
    /* D540 8001CD40 0780033C */  lui        $v1, %hi(D_800681E4)
    /* D544 8001CD44 E4816324 */  addiu      $v1, $v1, %lo(D_800681E4)
    /* D548 8001CD48 21986202 */  addu       $s3, $s3, $v0
    /* D54C 8001CD4C 0400628E */  lw         $v0, 0x4($s3)
    /* D550 8001CD50 08007226 */  addiu      $s2, $s3, 0x8
    /* D554 8001CD54 0780013C */  lui        $at, %hi(D_800681E8)
    /* D558 8001CD58 E88132AC */  sw         $s2, %lo(D_800681E8)($at)
    /* D55C 8001CD5C 0B004018 */  blez       $v0, .L8001CD8C
    /* D560 8001CD60 000062AC */   sw        $v0, 0x0($v1)
  .L8001CD64:
    /* D564 8001CD64 0000428E */  lw         $v0, 0x0($s2)
    /* D568 8001CD68 01001026 */  addiu      $s0, $s0, 0x1
    /* D56C 8001CD6C 04004224 */  addiu      $v0, $v0, 0x4
    /* D570 8001CD70 21106202 */  addu       $v0, $s3, $v0
    /* D574 8001CD74 000042AE */  sw         $v0, 0x0($s2)
    /* D578 8001CD78 0000628C */  lw         $v0, 0x0($v1)
    /* D57C 8001CD7C 00000000 */  nop
    /* D580 8001CD80 2A100202 */  slt        $v0, $s0, $v0
    /* D584 8001CD84 F7FF4014 */  bnez       $v0, .L8001CD64
    /* D588 8001CD88 04005226 */   addiu     $s2, $s2, 0x4
  .L8001CD8C:
    /* D58C 8001CD8C 21800000 */  addu       $s0, $zero, $zero
    /* D590 8001CD90 0000628E */  lw         $v0, 0x0($s3)
    /* D594 8001CD94 0780033C */  lui        $v1, %hi(D_80068204)
    /* D598 8001CD98 04826324 */  addiu      $v1, $v1, %lo(D_80068204)
    /* D59C 8001CD9C 21986202 */  addu       $s3, $s3, $v0
    /* D5A0 8001CDA0 0400628E */  lw         $v0, 0x4($s3)
    /* D5A4 8001CDA4 08007226 */  addiu      $s2, $s3, 0x8
    /* D5A8 8001CDA8 0780013C */  lui        $at, %hi(D_80068208)
    /* D5AC 8001CDAC 088232AC */  sw         $s2, %lo(D_80068208)($at)
    /* D5B0 8001CDB0 0C004018 */  blez       $v0, .L8001CDE4
    /* D5B4 8001CDB4 000062AC */   sw        $v0, 0x0($v1)
  .L8001CDB8:
    /* D5B8 8001CDB8 0000428E */  lw         $v0, 0x0($s2)
    /* D5BC 8001CDBC 01001026 */  addiu      $s0, $s0, 0x1
    /* D5C0 8001CDC0 04004224 */  addiu      $v0, $v0, 0x4
    /* D5C4 8001CDC4 21106202 */  addu       $v0, $s3, $v0
    /* D5C8 8001CDC8 000042AE */  sw         $v0, 0x0($s2)
    /* D5CC 8001CDCC 0000628C */  lw         $v0, 0x0($v1)
    /* D5D0 8001CDD0 00000000 */  nop
    /* D5D4 8001CDD4 2A100202 */  slt        $v0, $s0, $v0
    /* D5D8 8001CDD8 F7FF4014 */  bnez       $v0, .L8001CDB8
    /* D5DC 8001CDDC 04005226 */   addiu     $s2, $s2, 0x4
    /* D5E0 8001CDE0 21800000 */  addu       $s0, $zero, $zero
  .L8001CDE4:
    /* D5E4 8001CDE4 0000628E */  lw         $v0, 0x0($s3)
    /* D5E8 8001CDE8 0780033C */  lui        $v1, %hi(D_800681FC)
    /* D5EC 8001CDEC FC816324 */  addiu      $v1, $v1, %lo(D_800681FC)
    /* D5F0 8001CDF0 21986202 */  addu       $s3, $s3, $v0
    /* D5F4 8001CDF4 0400628E */  lw         $v0, 0x4($s3)
    /* D5F8 8001CDF8 08007226 */  addiu      $s2, $s3, 0x8
    /* D5FC 8001CDFC 0780013C */  lui        $at, %hi(D_80068200)
    /* D600 8001CE00 008232AC */  sw         $s2, %lo(D_80068200)($at)
    /* D604 8001CE04 0B004018 */  blez       $v0, .L8001CE34
    /* D608 8001CE08 000062AC */   sw        $v0, 0x0($v1)
  .L8001CE0C:
    /* D60C 8001CE0C 0000428E */  lw         $v0, 0x0($s2)
    /* D610 8001CE10 01001026 */  addiu      $s0, $s0, 0x1
    /* D614 8001CE14 04004224 */  addiu      $v0, $v0, 0x4
    /* D618 8001CE18 21106202 */  addu       $v0, $s3, $v0
    /* D61C 8001CE1C 000042AE */  sw         $v0, 0x0($s2)
    /* D620 8001CE20 0000628C */  lw         $v0, 0x0($v1)
    /* D624 8001CE24 00000000 */  nop
    /* D628 8001CE28 2A100202 */  slt        $v0, $s0, $v0
    /* D62C 8001CE2C F7FF4014 */  bnez       $v0, .L8001CE0C
    /* D630 8001CE30 04005226 */   addiu     $s2, $s2, 0x4
  .L8001CE34:
    /* D634 8001CE34 21800000 */  addu       $s0, $zero, $zero
    /* D638 8001CE38 0000628E */  lw         $v0, 0x0($s3)
    /* D63C 8001CE3C 0780033C */  lui        $v1, %hi(D_800681EC)
    /* D640 8001CE40 EC816324 */  addiu      $v1, $v1, %lo(D_800681EC)
    /* D644 8001CE44 21986202 */  addu       $s3, $s3, $v0
    /* D648 8001CE48 0400628E */  lw         $v0, 0x4($s3)
    /* D64C 8001CE4C 08007226 */  addiu      $s2, $s3, 0x8
    /* D650 8001CE50 0780013C */  lui        $at, %hi(D_800681F0)
    /* D654 8001CE54 F08132AC */  sw         $s2, %lo(D_800681F0)($at)
    /* D658 8001CE58 0B004018 */  blez       $v0, .L8001CE88
    /* D65C 8001CE5C 000062AC */   sw        $v0, 0x0($v1)
  .L8001CE60:
    /* D660 8001CE60 0000428E */  lw         $v0, 0x0($s2)
    /* D664 8001CE64 01001026 */  addiu      $s0, $s0, 0x1
    /* D668 8001CE68 04004224 */  addiu      $v0, $v0, 0x4
    /* D66C 8001CE6C 21106202 */  addu       $v0, $s3, $v0
    /* D670 8001CE70 000042AE */  sw         $v0, 0x0($s2)
    /* D674 8001CE74 0000628C */  lw         $v0, 0x0($v1)
    /* D678 8001CE78 00000000 */  nop
    /* D67C 8001CE7C 2A100202 */  slt        $v0, $s0, $v0
    /* D680 8001CE80 F7FF4014 */  bnez       $v0, .L8001CE60
    /* D684 8001CE84 04005226 */   addiu     $s2, $s2, 0x4
  .L8001CE88:
    /* D688 8001CE88 0000628E */  lw         $v0, 0x0($s3)
    /* D68C 8001CE8C 7D8C000C */  jal        func_800231F4
    /* D690 8001CE90 21906202 */   addu      $s2, $s3, $v0
    /* D694 8001CE94 9224053C */  lui        $a1, (0x24924926 >> 16)
    /* D698 8001CE98 04004226 */  addiu      $v0, $s2, 0x4
    /* D69C 8001CE9C 0680013C */  lui        $at, %hi(D_80066F20)
    /* D6A0 8001CEA0 206F22AC */  sw         $v0, %lo(D_80066F20)($at)
    /* D6A4 8001CEA4 0000428E */  lw         $v0, 0x0($s2)
    /* D6A8 8001CEA8 2649A534 */  ori        $a1, $a1, (0x24924926 & 0xFFFF)
    /* D6AC 8001CEAC 21984202 */  addu       $s3, $s2, $v0
    /* D6B0 8001CEB0 08007226 */  addiu      $s2, $s3, 0x8
    /* D6B4 8001CEB4 0400708E */  lw         $s0, 0x4($s3)
    /* D6B8 8001CEB8 08006326 */  addiu      $v1, $s3, 0x8
    /* D6BC 8001CEBC 0680013C */  lui        $at, %hi(D_80066F14)
    /* D6C0 8001CEC0 146F32AC */  sw         $s2, %lo(D_80066F14)($at)
    /* D6C4 8001CEC4 0000648E */  lw         $a0, 0x0($s3)
    /* D6C8 8001CEC8 40101000 */  sll        $v0, $s0, 1
    /* D6CC 8001CECC 21105000 */  addu       $v0, $v0, $s0
    /* D6D0 8001CED0 80100200 */  sll        $v0, $v0, 2
    /* D6D4 8001CED4 23105000 */  subu       $v0, $v0, $s0
    /* D6D8 8001CED8 C0100200 */  sll        $v0, $v0, 3
    /* D6DC 8001CEDC 21186200 */  addu       $v1, $v1, $v0
    /* D6E0 8001CEE0 FF000224 */  addiu      $v0, $zero, 0xFF
    /* D6E4 8001CEE4 0680013C */  lui        $at, %hi(D_800670BC)
    /* D6E8 8001CEE8 BC7023AC */  sw         $v1, %lo(D_800670BC)($at)
    /* D6EC 8001CEEC 0680013C */  lui        $at, %hi(D_80066FD4)
    /* D6F0 8001CEF0 D46F23AC */  sw         $v1, %lo(D_80066FD4)($at)
    /* D6F4 8001CEF4 480062A0 */  sb         $v0, 0x48($v1)
    /* D6F8 8001CEF8 0680033C */  lui        $v1, %hi(D_800670BC)
    /* D6FC 8001CEFC BC70638C */  lw         $v1, %lo(D_800670BC)($v1)
    /* D700 8001CF00 21906402 */  addu       $s2, $s3, $a0
    /* D704 8001CF04 23104302 */  subu       $v0, $s2, $v1
    /* D708 8001CF08 02110200 */  srl        $v0, $v0, 4
    /* D70C 8001CF0C 19004500 */  multu      $v0, $a1
    /* D710 8001CF10 0680013C */  lui        $at, %hi(D_80066F3C)
    /* D714 8001CF14 3C6F20AC */  sw         $zero, %lo(D_80066F3C)($at)
    /* D718 8001CF18 10800000 */  mfhi       $s0
    /* D71C 8001CF1C FFFF0226 */  addiu      $v0, $s0, -0x1
    /* D720 8001CF20 0680013C */  lui        $at, %hi(D_80066F40)
    /* D724 8001CF24 406F22AC */  sw         $v0, %lo(D_80066F40)($at)
    /* D728 8001CF28 40101000 */  sll        $v0, $s0, 1
    /* D72C 8001CF2C 21105000 */  addu       $v0, $v0, $s0
    /* D730 8001CF30 80100200 */  sll        $v0, $v0, 2
    /* D734 8001CF34 23105000 */  subu       $v0, $v0, $s0
    /* D738 8001CF38 C0100200 */  sll        $v0, $v0, 3
    /* D73C 8001CF3C 21186200 */  addu       $v1, $v1, $v0
    /* D740 8001CF40 0680013C */  lui        $at, %hi(D_80066FB4)
    /* D744 8001CF44 B46F23AC */  sw         $v1, %lo(D_80066FB4)($at)
    /* D748 8001CF48 0680013C */  lui        $at, %hi(D_800670D8)
    /* D74C 8001CF4C D87023AC */  sw         $v1, %lo(D_800670D8)($at)
    /* D750 8001CF50 0000428E */  lw         $v0, 0x0($s2)
    /* D754 8001CF54 00000000 */  nop
    /* D758 8001CF58 21984202 */  addu       $s3, $s2, $v0
    /* D75C 8001CF5C 0400628E */  lw         $v0, 0x4($s3)
    /* D760 8001CF60 08007226 */  addiu      $s2, $s3, 0x8
    /* D764 8001CF64 0680013C */  lui        $at, %hi(D_800670E0)
    /* D768 8001CF68 E07032AC */  sw         $s2, %lo(D_800670E0)($at)
    /* D76C 8001CF6C FFFF5024 */  addiu      $s0, $v0, -0x1
    /* D770 8001CF70 0680013C */  lui        $at, %hi(D_80066F4C)
    /* D774 8001CF74 4C6F22AC */  sw         $v0, %lo(D_80066F4C)($at)
    /* D778 8001CF78 08000006 */  bltz       $s0, .L8001CF9C
    /* D77C 8001CF7C 80101000 */   sll       $v0, $s0, 2
    /* D780 8001CF80 21205200 */  addu       $a0, $v0, $s2
  .L8001CF84:
    /* D784 8001CF84 0000828C */  lw         $v0, 0x0($a0)
    /* D788 8001CF88 FFFF1026 */  addiu      $s0, $s0, -0x1
    /* D78C 8001CF8C 21105300 */  addu       $v0, $v0, $s3
    /* D790 8001CF90 000082AC */  sw         $v0, 0x0($a0)
    /* D794 8001CF94 FBFF0106 */  bgez       $s0, .L8001CF84
    /* D798 8001CF98 FCFF8424 */   addiu     $a0, $a0, -0x4
  .L8001CF9C:
    /* D79C 8001CF9C 0000628E */  lw         $v0, 0x0($s3)
    /* D7A0 8001CFA0 21800000 */  addu       $s0, $zero, $zero
    /* D7A4 8001CFA4 21986202 */  addu       $s3, $s3, $v0
    /* D7A8 8001CFA8 0000628E */  lw         $v0, 0x0($s3)
    /* D7AC 8001CFAC 00000000 */  nop
    /* D7B0 8001CFB0 0D004018 */  blez       $v0, .L8001CFE8
    /* D7B4 8001CFB4 04007226 */   addiu     $s2, $s3, 0x4
  .L8001CFB8:
    /* D7B8 8001CFB8 0000428E */  lw         $v0, 0x0($s2)
    /* D7BC 8001CFBC 00000000 */  nop
    /* D7C0 8001CFC0 21108202 */  addu       $v0, $s4, $v0
    /* D7C4 8001CFC4 0000438C */  lw         $v1, 0x0($v0)
    /* D7C8 8001CFC8 01001026 */  addiu      $s0, $s0, 0x1
    /* D7CC 8001CFCC 21187400 */  addu       $v1, $v1, $s4
    /* D7D0 8001CFD0 000043AC */  sw         $v1, 0x0($v0)
    /* D7D4 8001CFD4 0000628E */  lw         $v0, 0x0($s3)
    /* D7D8 8001CFD8 00000000 */  nop
    /* D7DC 8001CFDC 2A100202 */  slt        $v0, $s0, $v0
    /* D7E0 8001CFE0 F5FF4014 */  bnez       $v0, .L8001CFB8
    /* D7E4 8001CFE4 04005226 */   addiu     $s2, $s2, 0x4
  .L8001CFE8:
    /* D7E8 8001CFE8 0680023C */  lui        $v0, %hi(D_80067024)
    /* D7EC 8001CFEC 2470428C */  lw         $v0, %lo(D_80067024)($v0)
    /* D7F0 8001CFF0 00000000 */  nop
    /* D7F4 8001CFF4 06004010 */  beqz       $v0, .L8001D010
    /* D7F8 8001CFF8 04306426 */   addiu     $a0, $s3, 0x3004
    /* D7FC 8001CFFC 0000468E */  lw         $a2, 0x0($s2)
    /* D800 8001D000 21284002 */  addu       $a1, $s2, $zero
    /* D804 8001D004 C0300600 */  sll        $a2, $a2, 3
    /* D808 8001D008 036D000C */  jal        func_8001B40C
    /* D80C 8001D00C 0400C634 */   ori       $a2, $a2, 0x4
  .L8001D010:
    /* D810 8001D010 21206002 */  addu       $a0, $s3, $zero
    /* D814 8001D014 21280000 */  addu       $a1, $zero, $zero
    /* D818 8001D018 0680013C */  lui        $at, %hi(D_80067174)
    /* D81C 8001D01C 747133AC */  sw         $s3, %lo(D_80067174)($at)
    /* D820 8001D020 F26C000C */  jal        func_8001B3C8
    /* D824 8001D024 00100624 */   addiu     $a2, $zero, 0x1000
    /* D828 8001D028 0680043C */  lui        $a0, %hi(D_80066F14)
    /* D82C 8001D02C 146F848C */  lw         $a0, %lo(D_80066F14)($a0)
    /* D830 8001D030 00000000 */  nop
    /* D834 8001D034 48008390 */  lbu        $v1, 0x48($a0)
    /* D838 8001D038 FF000224 */  addiu      $v0, $zero, 0xFF
    /* D83C 8001D03C A4006210 */  beq        $v1, $v0, .L8001D2D0
    /* D840 8001D040 21800000 */   addu      $s0, $zero, $zero
    /* D844 8001D044 06801E3C */  lui        $fp, %hi(D_80067414)
    /* D848 8001D048 1474DE27 */  addiu      $fp, $fp, %lo(D_80067414)
    /* D84C 8001D04C FF001624 */  addiu      $s6, $zero, 0xFF
    /* D850 8001D050 21880000 */  addu       $s1, $zero, $zero
  .L8001D054:
    /* D854 8001D054 01001224 */  addiu      $s2, $zero, 0x1
    /* D858 8001D058 43A11000 */  sra        $s4, $s0, 5
    /* D85C 8001D05C 21202402 */  addu       $a0, $s1, $a0
    /* D860 8001D060 36008384 */  lh         $v1, 0x36($a0)
    /* D864 8001D064 00000000 */  nop
    /* D868 8001D068 00036228 */  slti       $v0, $v1, 0x300
    /* D86C 8001D06C 0C004010 */  beqz       $v0, .L8001D0A0
    /* D870 8001D070 1F001532 */   andi      $s5, $s0, 0x1F
    /* D874 8001D074 80100300 */  sll        $v0, $v1, 2
    /* D878 8001D078 0780013C */  lui        $at, %hi(D_80068C94)
    /* D87C 8001D07C 21082200 */  addu       $at, $at, $v0
    /* D880 8001D080 948C228C */  lw         $v0, %lo(D_80068C94)($at)
    /* D884 8001D084 00000000 */  nop
    /* D888 8001D088 05004010 */  beqz       $v0, .L8001D0A0
    /* D88C 8001D08C 00000000 */   nop
    /* D890 8001D090 0E05010C */  jal        func_80041438
    /* D894 8001D094 00000000 */   nop
    /* D898 8001D098 2C740008 */  j          .L8001D0B0
    /* D89C 8001D09C 00000000 */   nop
  .L8001D0A0:
    /* D8A0 8001D0A0 0680043C */  lui        $a0, %hi(D_80066F14)
    /* D8A4 8001D0A4 146F848C */  lw         $a0, %lo(D_80066F14)($a0)
    /* D8A8 8001D0A8 4905010C */  jal        func_80041524
    /* D8AC 8001D0AC 21209100 */   addu      $a0, $a0, $s1
  .L8001D0B0:
    /* D8B0 8001D0B0 0680023C */  lui        $v0, %hi(D_80066F14)
    /* D8B4 8001D0B4 146F428C */  lw         $v0, %lo(D_80066F14)($v0)
    /* D8B8 8001D0B8 00000000 */  nop
    /* D8BC 8001D0BC 21102202 */  addu       $v0, $s1, $v0
    /* D8C0 8001D0C0 50004490 */  lbu        $a0, 0x50($v0)
    /* D8C4 8001D0C4 00000000 */  nop
    /* D8C8 8001D0C8 FFFF8224 */  addiu      $v0, $a0, -0x1
    /* D8CC 8001D0CC 0200422C */  sltiu      $v0, $v0, 0x2
    /* D8D0 8001D0D0 08004014 */  bnez       $v0, .L8001D0F4
    /* D8D4 8001D0D4 05000224 */   addiu     $v0, $zero, 0x5
    /* D8D8 8001D0D8 06008210 */  beq        $a0, $v0, .L8001D0F4
    /* D8DC 8001D0DC 0A000224 */   addiu     $v0, $zero, 0xA
    /* D8E0 8001D0E0 04008210 */  beq        $a0, $v0, .L8001D0F4
    /* D8E4 8001D0E4 19000224 */   addiu     $v0, $zero, 0x19
    /* D8E8 8001D0E8 02008210 */  beq        $a0, $v0, .L8001D0F4
    /* D8EC 8001D0EC 00000000 */   nop
    /* D8F0 8001D0F0 21200000 */  addu       $a0, $zero, $zero
  .L8001D0F4:
    /* D8F4 8001D0F4 0680023C */  lui        $v0, %hi(D_80066F14)
    /* D8F8 8001D0F8 146F428C */  lw         $v0, %lo(D_80066F14)($v0)
    /* D8FC 8001D0FC 00000000 */  nop
    /* D900 8001D100 21102202 */  addu       $v0, $s1, $v0
    /* D904 8001D104 3A0056A0 */  sb         $s6, 0x3A($v0)
    /* D908 8001D108 0680023C */  lui        $v0, %hi(D_80066F14)
    /* D90C 8001D10C 146F428C */  lw         $v0, %lo(D_80066F14)($v0)
    /* D910 8001D110 00000000 */  nop
    /* D914 8001D114 21102202 */  addu       $v0, $s1, $v0
    /* D918 8001D118 3B004390 */  lbu        $v1, 0x3B($v0)
    /* D91C 8001D11C 7E000224 */  addiu      $v0, $zero, 0x7E
    /* D920 8001D120 03006214 */  bne        $v1, $v0, .L8001D130
    /* D924 8001D124 7D000224 */   addiu     $v0, $zero, 0x7D
    /* D928 8001D128 71740008 */  j          .L8001D1C4
    /* D92C 8001D12C 01001224 */   addiu     $s2, $zero, 0x1
  .L8001D130:
    /* D930 8001D130 14006214 */  bne        $v1, $v0, .L8001D184
    /* D934 8001D134 0001022A */   slti      $v0, $s0, 0x100
    /* D938 8001D138 22004010 */  beqz       $v0, .L8001D1C4
    /* D93C 8001D13C 00000000 */   nop
    /* D940 8001D140 0680033C */  lui        $v1, %hi(D_80066F54)
    /* D944 8001D144 546F638C */  lw         $v1, %lo(D_80066F54)($v1)
    /* D948 8001D148 0780023C */  lui        $v0, %hi(D_8006AC84)
    /* D94C 8001D14C 84AC4224 */  addiu      $v0, $v0, %lo(D_8006AC84)
    /* D950 8001D150 40190300 */  sll        $v1, $v1, 5
    /* D954 8001D154 21186200 */  addu       $v1, $v1, $v0
    /* D958 8001D158 80101400 */  sll        $v0, $s4, 2
    /* D95C 8001D15C 21104300 */  addu       $v0, $v0, $v1
    /* D960 8001D160 0000428C */  lw         $v0, 0x0($v0)
    /* D964 8001D164 00000000 */  nop
    /* D968 8001D168 0710A202 */  srav       $v0, $v0, $s5
    /* D96C 8001D16C 01004230 */  andi       $v0, $v0, 0x1
    /* D970 8001D170 14004010 */  beqz       $v0, .L8001D1C4
    /* D974 8001D174 00000000 */   nop
    /* D978 8001D178 21900000 */  addu       $s2, $zero, $zero
    /* D97C 8001D17C 71740008 */  j          .L8001D1C4
    /* D980 8001D180 21B8E402 */   addu      $s7, $s7, $a0
  .L8001D184:
    /* D984 8001D184 0000C28F */  lw         $v0, 0x0($fp)
    /* D988 8001D188 00000000 */  nop
    /* D98C 8001D18C 0D004010 */  beqz       $v0, .L8001D1C4
    /* D990 8001D190 0001022A */   slti      $v0, $s0, 0x100
    /* D994 8001D194 0B004010 */  beqz       $v0, .L8001D1C4
    /* D998 8001D198 80101400 */   sll       $v0, $s4, 2
    /* D99C 8001D19C 0680083C */  lui        $t0, %hi(D_80067418)
    /* D9A0 8001D1A0 18740825 */  addiu      $t0, $t0, %lo(D_80067418)
    /* D9A4 8001D1A4 21104800 */  addu       $v0, $v0, $t0
    /* D9A8 8001D1A8 0000428C */  lw         $v0, 0x0($v0)
    /* D9AC 8001D1AC 00000000 */  nop
    /* D9B0 8001D1B0 0710A202 */  srav       $v0, $v0, $s5
    /* D9B4 8001D1B4 01004230 */  andi       $v0, $v0, 0x1
    /* D9B8 8001D1B8 02004010 */  beqz       $v0, .L8001D1C4
    /* D9BC 8001D1BC 00000000 */   nop
    /* D9C0 8001D1C0 21900000 */  addu       $s2, $zero, $zero
  .L8001D1C4:
    /* D9C4 8001D1C4 14004016 */  bnez       $s2, .L8001D218
    /* D9C8 8001D1C8 1000A427 */   addiu     $a0, $sp, 0x10
    /* D9CC 8001D1CC 0680043C */  lui        $a0, %hi(D_80066F14)
    /* D9D0 8001D1D0 146F848C */  lw         $a0, %lo(D_80066F14)($a0)
    /* D9D4 8001D1D4 CB04010C */  jal        func_8004132C
    /* D9D8 8001D1D8 21209100 */   addu      $a0, $a0, $s1
    /* D9DC 8001D1DC 0680023C */  lui        $v0, %hi(D_80066F14)
    /* D9E0 8001D1E0 146F428C */  lw         $v0, %lo(D_80066F14)($v0)
    /* D9E4 8001D1E4 00000000 */  nop
    /* D9E8 8001D1E8 21102202 */  addu       $v0, $s1, $v0
    /* D9EC 8001D1EC 53004290 */  lbu        $v0, 0x53($v0)
    /* D9F0 8001D1F0 0680033C */  lui        $v1, %hi(D_80066FB0)
    /* D9F4 8001D1F4 B06F638C */  lw         $v1, %lo(D_80066FB0)($v1)
    /* D9F8 8001D1F8 7F004230 */  andi       $v0, $v0, 0x7F
    /* D9FC 8001D1FC 21186200 */  addu       $v1, $v1, $v0
    /* DA00 8001D200 0680013C */  lui        $at, %hi(D_80066FB0)
    /* DA04 8001D204 B06F23AC */  sw         $v1, %lo(D_80066FB0)($at)
    /* DA08 8001D208 0680013C */  lui        $at, %hi(D_80066EFC)
    /* DA0C 8001D20C FC6E23AC */  sw         $v1, %lo(D_80066EFC)($at)
    /* DA10 8001D210 AC740008 */  j          .L8001D2B0
    /* DA14 8001D214 00000000 */   nop
  .L8001D218:
    /* DA18 8001D218 0680053C */  lui        $a1, %hi(D_80066F14)
    /* DA1C 8001D21C 146FA58C */  lw         $a1, %lo(D_80066F14)($a1)
    /* DA20 8001D220 00000000 */  nop
    /* DA24 8001D224 2128B100 */  addu       $a1, $a1, $s1
    /* DA28 8001D228 6C6F000C */  jal        func_8001BDB0
    /* DA2C 8001D22C 0C00A524 */   addiu     $a1, $a1, 0xC
    /* DA30 8001D230 1000A427 */  addiu      $a0, $sp, 0x10
    /* DA34 8001D234 0100053C */  lui        $a1, (0x10000 >> 16)
    /* DA38 8001D238 21300000 */  addu       $a2, $zero, $zero
    /* DA3C 8001D23C 1800A28F */  lw         $v0, 0x18($sp)
    /* DA40 8001D240 0680073C */  lui        $a3, %hi(D_80066F14)
    /* DA44 8001D244 146FE78C */  lw         $a3, %lo(D_80066F14)($a3)
    /* DA48 8001D248 00044224 */  addiu      $v0, $v0, 0x400
    /* DA4C 8001D24C 2138F100 */  addu       $a3, $a3, $s1
    /* DA50 8001D250 8FFB000C */  jal        func_8003EE3C
    /* DA54 8001D254 1800A2AF */   sw        $v0, 0x18($sp)
    /* DA58 8001D258 0680043C */  lui        $a0, %hi(D_80066F14)
    /* DA5C 8001D25C 146F848C */  lw         $a0, %lo(D_80066F14)($a0)
    /* DA60 8001D260 AE06010C */  jal        func_80041AB8
    /* DA64 8001D264 21209100 */   addu      $a0, $a0, $s1
    /* DA68 8001D268 0680023C */  lui        $v0, %hi(D_80066F14)
    /* DA6C 8001D26C 146F428C */  lw         $v0, %lo(D_80066F14)($v0)
    /* DA70 8001D270 00000000 */  nop
    /* DA74 8001D274 21182202 */  addu       $v1, $s1, $v0
    /* DA78 8001D278 52006290 */  lbu        $v0, 0x52($v1)
    /* DA7C 8001D27C 00000000 */  nop
    /* DA80 8001D280 05004010 */  beqz       $v0, .L8001D298
    /* DA84 8001D284 FF000224 */   addiu     $v0, $zero, 0xFF
    /* DA88 8001D288 0780023C */  lui        $v0, %hi(D_8006AB98)
    /* DA8C 8001D28C 98AB428C */  lw         $v0, %lo(D_8006AB98)($v0)
    /* DA90 8001D290 A7740008 */  j          .L8001D29C
    /* DA94 8001D294 520062A0 */   sb        $v0, 0x52($v1)
  .L8001D298:
    /* DA98 8001D298 520062A0 */  sb         $v0, 0x52($v1)
  .L8001D29C:
    /* DA9C 8001D29C 0680023C */  lui        $v0, %hi(D_80066F14)
    /* DAA0 8001D2A0 146F428C */  lw         $v0, %lo(D_80066F14)($v0)
    /* DAA4 8001D2A4 01000324 */  addiu      $v1, $zero, 0x1
    /* DAA8 8001D2A8 21102202 */  addu       $v0, $s1, $v0
    /* DAAC 8001D2AC 4D0043A0 */  sb         $v1, 0x4D($v0)
  .L8001D2B0:
    /* DAB0 8001D2B0 0680043C */  lui        $a0, %hi(D_80066F14)
    /* DAB4 8001D2B4 146F848C */  lw         $a0, %lo(D_80066F14)($a0)
    /* DAB8 8001D2B8 58003126 */  addiu      $s1, $s1, 0x58
    /* DABC 8001D2BC 21102402 */  addu       $v0, $s1, $a0
    /* DAC0 8001D2C0 48004290 */  lbu        $v0, 0x48($v0)
    /* DAC4 8001D2C4 00000000 */  nop
    /* DAC8 8001D2C8 62FF5614 */  bne        $v0, $s6, .L8001D054
    /* DACC 8001D2CC 01001026 */   addiu     $s0, $s0, 0x1
  .L8001D2D0:
    /* DAD0 8001D2D0 0680023C */  lui        $v0, %hi(D_80066F54)
    /* DAD4 8001D2D4 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* DAD8 8001D2D8 00000000 */  nop
    /* DADC 8001D2DC 80100200 */  sll        $v0, $v0, 2
    /* DAE0 8001D2E0 0780013C */  lui        $at, %hi(D_8006AC04)
    /* DAE4 8001D2E4 21082200 */  addu       $at, $at, $v0
    /* DAE8 8001D2E8 04AC228C */  lw         $v0, %lo(D_8006AC04)($at)
    /* DAEC 8001D2EC 0780103C */  lui        $s0, %hi(D_8006AC04)
    /* DAF0 8001D2F0 04AC1026 */  addiu      $s0, $s0, %lo(D_8006AC04)
    /* DAF4 8001D2F4 2300E212 */  beq        $s7, $v0, .L8001D384
    /* DAF8 8001D2F8 6666023C */   lui       $v0, (0x66666667 >> 16)
    /* DAFC 8001D2FC 0680043C */  lui        $a0, %hi(D_80066F90)
    /* DB00 8001D300 906F848C */  lw         $a0, %lo(D_80066F90)($a0)
    /* DB04 8001D304 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
    /* DB08 8001D308 18008200 */  mult       $a0, $v0
    /* DB0C 8001D30C C3170400 */  sra        $v0, $a0, 31
    /* DB10 8001D310 10400000 */  mfhi       $t0
    /* DB14 8001D314 83180800 */  sra        $v1, $t0, 2
    /* DB18 8001D318 23186200 */  subu       $v1, $v1, $v0
    /* DB1C 8001D31C 80100300 */  sll        $v0, $v1, 2
    /* DB20 8001D320 21104300 */  addu       $v0, $v0, $v1
    /* DB24 8001D324 40100200 */  sll        $v0, $v0, 1
    /* DB28 8001D328 23208200 */  subu       $a0, $a0, $v0
    /* DB2C 8001D32C 05008428 */  slti       $a0, $a0, 0x5
    /* DB30 8001D330 14008010 */  beqz       $a0, .L8001D384
    /* DB34 8001D334 00000000 */   nop
    /* DB38 8001D338 A050010C */  jal        func_80054280
    /* DB3C 8001D33C 00000000 */   nop
    /* DB40 8001D340 0680023C */  lui        $v0, %hi(D_80066F54)
    /* DB44 8001D344 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* DB48 8001D348 00000000 */  nop
    /* DB4C 8001D34C 80100200 */  sll        $v0, $v0, 2
    /* DB50 8001D350 21205000 */  addu       $a0, $v0, $s0
    /* DB54 8001D354 0000828C */  lw         $v0, 0x0($a0)
    /* DB58 8001D358 0680033C */  lui        $v1, %hi(D_800670CC)
    /* DB5C 8001D35C CC70638C */  lw         $v1, %lo(D_800670CC)($v1)
    /* DB60 8001D360 2310E202 */  subu       $v0, $s7, $v0
    /* DB64 8001D364 21186200 */  addu       $v1, $v1, $v0
    /* DB68 8001D368 0680013C */  lui        $at, %hi(D_800670CC)
    /* DB6C 8001D36C CC7023AC */  sw         $v1, %lo(D_800670CC)($at)
    /* DB70 8001D370 03006104 */  bgez       $v1, .L8001D380
    /* DB74 8001D374 00000000 */   nop
    /* DB78 8001D378 0680013C */  lui        $at, %hi(D_800670CC)
    /* DB7C 8001D37C CC7020AC */  sw         $zero, %lo(D_800670CC)($at)
  .L8001D380:
    /* DB80 8001D380 000097AC */  sw         $s7, 0x0($a0)
  .L8001D384:
    /* DB84 8001D384 0680043C */  lui        $a0, %hi(D_80067414)
    /* DB88 8001D388 14748424 */  addiu      $a0, $a0, %lo(D_80067414)
    /* DB8C 8001D38C 0000828C */  lw         $v0, 0x0($a0)
    /* DB90 8001D390 00000000 */  nop
    /* DB94 8001D394 11004010 */  beqz       $v0, .L8001D3DC
    /* DB98 8001D398 00000000 */   nop
    /* DB9C 8001D39C C730010C */  jal        func_8004C31C
    /* DBA0 8001D3A0 00000000 */   nop
    /* DBA4 8001D3A4 0680033C */  lui        $v1, %hi(D_80067658)
    /* DBA8 8001D3A8 5876638C */  lw         $v1, %lo(D_80067658)($v1)
    /* DBAC 8001D3AC 01000224 */  addiu      $v0, $zero, 0x1
    /* DBB0 8001D3B0 05006210 */  beq        $v1, $v0, .L8001D3C8
    /* DBB4 8001D3B4 02000224 */   addiu     $v0, $zero, 0x2
    /* DBB8 8001D3B8 05006210 */  beq        $v1, $v0, .L8001D3D0
    /* DBBC 8001D3BC 00000000 */   nop
    /* DBC0 8001D3C0 F7740008 */  j          .L8001D3DC
    /* DBC4 8001D3C4 00000000 */   nop
  .L8001D3C8:
    /* DBC8 8001D3C8 F5740008 */  j          .L8001D3D4
    /* DBCC 8001D3CC 2C000424 */   addiu     $a0, $zero, 0x2C
  .L8001D3D0:
    /* DBD0 8001D3D0 29000424 */  addiu      $a0, $zero, 0x29
  .L8001D3D4:
    /* DBD4 8001D3D4 76D4000C */  jal        func_800351D8
    /* DBD8 8001D3D8 00000000 */   nop
  .L8001D3DC:
    /* DBDC 8001D3DC 0680043C */  lui        $a0, %hi(D_80067174)
    /* DBE0 8001D3E0 7471848C */  lw         $a0, %lo(D_80067174)($a0)
    /* DBE4 8001D3E4 A371000C */  jal        func_8001C68C
    /* DBE8 8001D3E8 00108424 */   addiu     $a0, $a0, 0x1000
    /* DBEC 8001D3EC 0780103C */  lui        $s0, %hi(D_8006B298)
    /* DBF0 8001D3F0 98B21026 */  addiu      $s0, $s0, %lo(D_8006B298)
    /* DBF4 8001D3F4 0680023C */  lui        $v0, %hi(D_80066F18)
    /* DBF8 8001D3F8 186F428C */  lw         $v0, %lo(D_80066F18)($v0)
    /* DBFC 8001D3FC 0680033C */  lui        $v1, %hi(D_80067024)
    /* DC00 8001D400 2470638C */  lw         $v1, %lo(D_80067024)($v1)
    /* DC04 8001D404 04204224 */  addiu      $v0, $v0, 0x2004
    /* DC08 8001D408 1C006010 */  beqz       $v1, .L8001D47C
    /* DC0C 8001D40C 000002AE */   sw        $v0, 0x0($s0)
    /* DC10 8001D410 5767010C */  jal        func_80059D5C
    /* DC14 8001D414 D2040424 */   addiu     $a0, $zero, 0x4D2
    /* DC18 8001D418 0680033C */  lui        $v1, %hi(D_80067024)
    /* DC1C 8001D41C 2470638C */  lw         $v1, %lo(D_80067024)($v1)
    /* DC20 8001D420 01000224 */  addiu      $v0, $zero, 0x1
    /* DC24 8001D424 0680013C */  lui        $at, %hi(D_80067044)
    /* DC28 8001D428 447022AC */  sw         $v0, %lo(D_80067044)($at)
    /* DC2C 8001D42C 09006214 */  bne        $v1, $v0, .L8001D454
    /* DC30 8001D430 6080033C */   lui       $v1, (0x80600004 >> 16)
    /* DC34 8001D434 0000028E */  lw         $v0, 0x0($s0)
    /* DC38 8001D438 0680013C */  lui        $at, %hi(D_80066F28)
    /* DC3C 8001D43C 286F22AC */  sw         $v0, %lo(D_80066F28)($at)
    /* DC40 8001D440 04004224 */  addiu      $v0, $v0, 0x4
    /* DC44 8001D444 0680013C */  lui        $at, %hi(D_80066F04)
    /* DC48 8001D448 046F22AC */  sw         $v0, %lo(D_80066F04)($at)
    /* DC4C 8001D44C 1F750008 */  j          .L8001D47C
    /* DC50 8001D450 00000000 */   nop
  .L8001D454:
    /* DC54 8001D454 04006334 */  ori        $v1, $v1, (0x80600004 & 0xFFFF)
    /* DC58 8001D458 6080043C */  lui        $a0, (0x80600000 >> 16)
    /* DC5C 8001D45C 21280000 */  addu       $a1, $zero, $zero
    /* DC60 8001D460 6080023C */  lui        $v0, (0x80600000 >> 16)
    /* DC64 8001D464 0680013C */  lui        $at, %hi(D_80066F28)
    /* DC68 8001D468 286F22AC */  sw         $v0, %lo(D_80066F28)($at)
    /* DC6C 8001D46C 0680013C */  lui        $at, %hi(D_80066F04)
    /* DC70 8001D470 046F23AC */  sw         $v1, %lo(D_80066F04)($at)
    /* DC74 8001D474 F26C000C */  jal        func_8001B3C8
    /* DC78 8001D478 00400624 */   addiu     $a2, $zero, 0x4000
  .L8001D47C:
    /* DC7C 8001D47C 0680033C */  lui        $v1, %hi(D_800670B4)
    /* DC80 8001D480 B470638C */  lw         $v1, %lo(D_800670B4)($v1)
    /* DC84 8001D484 00000000 */  nop
    /* DC88 8001D488 0C006010 */  beqz       $v1, .L8001D4BC
    /* DC8C 8001D48C 00000000 */   nop
    /* DC90 8001D490 0780023C */  lui        $v0, %hi(D_80069894)
    /* DC94 8001D494 9498428C */  lw         $v0, %lo(D_80069894)($v0)
    /* DC98 8001D498 00000000 */  nop
    /* DC9C 8001D49C 07004104 */  bgez       $v0, .L8001D4BC
    /* DCA0 8001D4A0 78000424 */   addiu     $a0, $zero, 0x78
    /* DCA4 8001D4A4 09F86000 */  jalr       $v1
    /* DCA8 8001D4A8 21280000 */   addu      $a1, $zero, $zero
    /* DCAC 8001D4AC 0680013C */  lui        $at, %hi(D_80067028)
    /* DCB0 8001D4B0 287022AC */  sw         $v0, %lo(D_80067028)($at)
    /* DCB4 8001D4B4 31750008 */  j          .L8001D4C4
    /* DCB8 8001D4B8 00000000 */   nop
  .L8001D4BC:
    /* DCBC 8001D4BC 0680013C */  lui        $at, %hi(D_80067028)
    /* DCC0 8001D4C0 287020AC */  sw         $zero, %lo(D_80067028)($at)
  .L8001D4C4:
    /* DCC4 8001D4C4 0780023C */  lui        $v0, %hi(D_80069894)
    /* DCC8 8001D4C8 9498428C */  lw         $v0, %lo(D_80069894)($v0)
    /* DCCC 8001D4CC 0680043C */  lui        $a0, %hi(D_80061560)
    /* DCD0 8001D4D0 60158424 */  addiu      $a0, $a0, %lo(D_80061560)
    /* DCD4 8001D4D4 03004004 */  bltz       $v0, .L8001D4E4
    /* DCD8 8001D4D8 00000000 */   nop
    /* DCDC 8001D4DC 0680043C */  lui        $a0, %hi(D_800615C4)
    /* DCE0 8001D4E0 C4158424 */  addiu      $a0, $a0, %lo(D_800615C4)
  .L8001D4E4:
    /* DCE4 8001D4E4 B978000C */  jal        func_8001E2E4
    /* DCE8 8001D4E8 00000000 */   nop
    /* DCEC 8001D4EC 0780043C */  lui        $a0, %hi(D_8006B300)
    /* DCF0 8001D4F0 00B38424 */  addiu      $a0, $a0, %lo(D_8006B300)
    /* DCF4 8001D4F4 0303053C */  lui        $a1, (0x3030303 >> 16)
    /* DCF8 8001D4F8 0303A534 */  ori        $a1, $a1, (0x3030303 & 0xFFFF)
    /* DCFC 8001D4FC 0780023C */  lui        $v0, %hi(D_800681C0)
    /* DD00 8001D500 C0814290 */  lbu        $v0, %lo(D_800681C0)($v0)
    /* DD04 8001D504 0780033C */  lui        $v1, %hi(D_800681C1)
    /* DD08 8001D508 C1816390 */  lbu        $v1, %lo(D_800681C1)($v1)
    /* DD0C 8001D50C 0780073C */  lui        $a3, %hi(D_800681C2)
    /* DD10 8001D510 C281E790 */  lbu        $a3, %lo(D_800681C2)($a3)
    /* DD14 8001D514 0680013C */  lui        $at, %hi(D_80067EC4)
    /* DD18 8001D518 C47E20AC */  sw         $zero, %lo(D_80067EC4)($at)
    /* DD1C 8001D51C 0780013C */  lui        $at, %hi(D_80069941)
    /* DD20 8001D520 419922A0 */  sb         $v0, %lo(D_80069941)($at)
    /* DD24 8001D524 0780013C */  lui        $at, %hi(D_80069942)
    /* DD28 8001D528 429923A0 */  sb         $v1, %lo(D_80069942)($at)
    /* DD2C 8001D52C 0780013C */  lui        $at, %hi(D_80069943)
    /* DD30 8001D530 439927A0 */  sb         $a3, %lo(D_80069943)($at)
    /* DD34 8001D534 0780013C */  lui        $at, %hi(D_800699B5)
    /* DD38 8001D538 B59922A0 */  sb         $v0, %lo(D_800699B5)($at)
    /* DD3C 8001D53C 0780013C */  lui        $at, %hi(D_800699B6)
    /* DD40 8001D540 B69923A0 */  sb         $v1, %lo(D_800699B6)($at)
    /* DD44 8001D544 0780013C */  lui        $at, %hi(D_800699B7)
    /* DD48 8001D548 B79927A0 */  sb         $a3, %lo(D_800699B7)($at)
    /* DD4C 8001D54C F26C000C */  jal        func_8001B3C8
    /* DD50 8001D550 00010624 */   addiu     $a2, $zero, 0x100
    /* DD54 8001D554 0680023C */  lui        $v0, %hi(D_800670F0)
    /* DD58 8001D558 F070428C */  lw         $v0, %lo(D_800670F0)($v0)
    /* DD5C 8001D55C 00000000 */  nop
    /* DD60 8001D560 03004010 */  beqz       $v0, .L8001D570
    /* DD64 8001D564 00000000 */   nop
    /* DD68 8001D568 09F84000 */  jalr       $v0
    /* DD6C 8001D56C 00000000 */   nop
  .L8001D570:
    /* DD70 8001D570 4647010C */  jal        func_80051D18
    /* DD74 8001D574 00000000 */   nop
    /* DD78 8001D578 0680023C */  lui        $v0, %hi(D_80066EE4)
    /* DD7C 8001D57C E46E428C */  lw         $v0, %lo(D_80066EE4)($v0)
    /* DD80 8001D580 00000000 */  nop
    /* DD84 8001D584 10004014 */  bnez       $v0, .L8001D5C8
    /* DD88 8001D588 21106002 */   addu      $v0, $s3, $zero
    /* DD8C 8001D58C 0680033C */  lui        $v1, %hi(D_80066F90)
    /* DD90 8001D590 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* DD94 8001D594 41000224 */  addiu      $v0, $zero, 0x41
    /* DD98 8001D598 0B006210 */  beq        $v1, $v0, .L8001D5C8
    /* DD9C 8001D59C 21106002 */   addu      $v0, $s3, $zero
    /* DDA0 8001D5A0 0680023C */  lui        $v0, %hi(D_80066FA8)
    /* DDA4 8001D5A4 A86F428C */  lw         $v0, %lo(D_80066FA8)($v0)
    /* DDA8 8001D5A8 00000000 */  nop
    /* DDAC 8001D5AC 06004010 */  beqz       $v0, .L8001D5C8
    /* DDB0 8001D5B0 21106002 */   addu      $v0, $s3, $zero
    /* DDB4 8001D5B4 0680023C */  lui        $v0, %hi(D_80066F00)
    /* DDB8 8001D5B8 006F428C */  lw         $v0, %lo(D_80066F00)($v0)
    /* DDBC 8001D5BC 00000000 */  nop
    /* DDC0 8001D5C0 400040A0 */  sb         $zero, 0x40($v0)
    /* DDC4 8001D5C4 21106002 */  addu       $v0, $s3, $zero
  .L8001D5C8:
    /* DDC8 8001D5C8 9C00BF8F */  lw         $ra, 0x9C($sp)
    /* DDCC 8001D5CC 9800BE8F */  lw         $fp, 0x98($sp)
    /* DDD0 8001D5D0 9400B78F */  lw         $s7, 0x94($sp)
    /* DDD4 8001D5D4 9000B68F */  lw         $s6, 0x90($sp)
    /* DDD8 8001D5D8 8C00B58F */  lw         $s5, 0x8C($sp)
    /* DDDC 8001D5DC 8800B48F */  lw         $s4, 0x88($sp)
    /* DDE0 8001D5E0 8400B38F */  lw         $s3, 0x84($sp)
    /* DDE4 8001D5E4 8000B28F */  lw         $s2, 0x80($sp)
    /* DDE8 8001D5E8 7C00B18F */  lw         $s1, 0x7C($sp)
    /* DDEC 8001D5EC 7800B08F */  lw         $s0, 0x78($sp)
    /* DDF0 8001D5F0 A000BD27 */  addiu      $sp, $sp, 0xA0
    /* DDF4 8001D5F4 0800E003 */  jr         $ra
    /* DDF8 8001D5F8 00000000 */   nop
endlabel func_8001C734
