.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
nonmatching jtbl_80010910

dlabel jtbl_80010910
    /* 1110 80010910 A0D60180 */ .word .L8001D6A0
    /* 1114 80010914 E0D60180 */ .word .L8001D6E0
    /* 1118 80010918 E0D60180 */ .word .L8001D6E0
    /* 111C 8001091C E0D60180 */ .word .L8001D6E0
    /* 1120 80010920 E0D60180 */ .word .L8001D6E0
    /* 1124 80010924 E0D60180 */ .word .L8001D6E0
    /* 1128 80010928 E0D60180 */ .word .L8001D6E0
    /* 112C 8001092C B8D70180 */ .word .L8001D7B8
    /* 1130 80010930 F0D60180 */ .word .L8001D6F0
    /* 1134 80010934 6CD70180 */ .word .L8001D76C
enddlabel jtbl_80010910


.section .text
/* Generated by spimdisasm 1.39.3 */

nonmatching func_8001D658, 0x190

glabel func_8001D658
    /* DE58 8001D658 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* DE5C 8001D65C 1400BFAF */  sw         $ra, 0x14($sp)
    /* DE60 8001D660 A44D000C */  jal        func_80013690
    /* DE64 8001D664 1000B0AF */   sw        $s0, 0x10($sp)
    /* DE68 8001D668 5A004014 */  bnez       $v0, .L8001D7D4
    /* DE6C 8001D66C 00000000 */   nop
    /* DE70 8001D670 0680033C */  lui        $v1, %hi(D_80066EEC)
    /* DE74 8001D674 EC6E638C */  lw         $v1, %lo(D_80066EEC)($v1)
    /* DE78 8001D678 00000000 */  nop
    /* DE7C 8001D67C 0A00622C */  sltiu      $v0, $v1, 0xA
    /* DE80 8001D680 4D004010 */  beqz       $v0, .L8001D7B8
    /* DE84 8001D684 80100300 */   sll       $v0, $v1, 2
    /* DE88 8001D688 0180013C */  lui        $at, %hi(jtbl_80010910)
    /* DE8C 8001D68C 21082200 */  addu       $at, $at, $v0
    /* DE90 8001D690 1009228C */  lw         $v0, %lo(jtbl_80010910)($at)
    /* DE94 8001D694 00000000 */  nop
    /* DE98 8001D698 08004000 */  jr         $v0
    /* DE9C 8001D69C 00000000 */   nop
  .L8001D6A0:
    /* DEA0 8001D6A0 0680103C */  lui        $s0, %hi(D_800676E4)
    /* DEA4 8001D6A4 E4761026 */  addiu      $s0, $s0, %lo(D_800676E4)
    /* DEA8 8001D6A8 0780043C */  lui        $a0, %hi(D_800682D8)
    /* DEAC 8001D6AC D882848C */  lw         $a0, %lo(D_800682D8)($a0)
    /* DEB0 8001D6B0 0180053C */  lui        $a1, %hi(D_80011110)
    /* DEB4 8001D6B4 1011A58C */  lw         $a1, %lo(D_80011110)($a1)
    /* DEB8 8001D6B8 0000068E */  lw         $a2, 0x0($s0)
    /* DEBC 8001D6BC 0680073C */  lui        $a3, %hi(D_800676E0)
    /* DEC0 8001D6C0 E076E78C */  lw         $a3, %lo(D_800676E0)($a3)
    /* DEC4 8001D6C4 464E000C */  jal        func_80013918
    /* DEC8 8001D6C8 00000000 */   nop
    /* DECC 8001D6CC 0000028E */  lw         $v0, 0x0($s0)
    /* DED0 8001D6D0 0680013C */  lui        $at, %hi(D_800670C4)
    /* DED4 8001D6D4 C47022AC */  sw         $v0, %lo(D_800670C4)($at)
    /* DED8 8001D6D8 EE750008 */  j          .L8001D7B8
    /* DEDC 8001D6DC 00000000 */   nop
  .L8001D6E0:
    /* DEE0 8001D6E0 26C1010C */  jal        func_titlescreen_and_loading_80070498
    /* DEE4 8001D6E4 00000000 */   nop
    /* DEE8 8001D6E8 EE750008 */  j          .L8001D7B8
    /* DEEC 8001D6EC 00000000 */   nop
  .L8001D6F0:
    /* DEF0 8001D6F0 0780033C */  lui        $v1, %hi(D_800681C8)
    /* DEF4 8001D6F4 C881638C */  lw         $v1, %lo(D_800681C8)($v1)
    /* DEF8 8001D6F8 04000224 */  addiu      $v0, $zero, 0x4
    /* DEFC 8001D6FC 0A006210 */  beq        $v1, $v0, .L8001D728
    /* DF00 8001D700 00000000 */   nop
    /* DF04 8001D704 0680023C */  lui        $v0, %hi(D_80066F54)
    /* DF08 8001D708 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* DF0C 8001D70C 0680013C */  lui        $at, %hi(D_80061BB8)
    /* DF10 8001D710 21082200 */  addu       $at, $at, $v0
    /* DF14 8001D714 B81B2490 */  lbu        $a0, %lo(D_80061BB8)($at)
    /* DF18 8001D718 5634010C */  jal        func_8004D158
    /* DF1C 8001D71C 80220400 */   sll       $a0, $a0, 10
    /* DF20 8001D720 7B71000C */  jal        func_8001C5EC
    /* DF24 8001D724 00000000 */   nop
  .L8001D728:
    /* DF28 8001D728 0780043C */  lui        $a0, %hi(D_800682D8)
    /* DF2C 8001D72C D882848C */  lw         $a0, %lo(D_800682D8)($a0)
    /* DF30 8001D730 0680023C */  lui        $v0, %hi(D_80066F54)
    /* DF34 8001D734 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* DF38 8001D738 0780053C */  lui        $a1, %hi(D_8006B284)
    /* DF3C 8001D73C 84B2A58C */  lw         $a1, %lo(D_8006B284)($a1)
    /* DF40 8001D740 00110200 */  sll        $v0, $v0, 4
    /* DF44 8001D744 0680013C */  lui        $at, %hi(D_8006774C)
    /* DF48 8001D748 21082200 */  addu       $at, $at, $v0
    /* DF4C 8001D74C 4C77268C */  lw         $a2, %lo(D_8006774C)($at)
    /* DF50 8001D750 0680013C */  lui        $at, %hi(D_80067748)
    /* DF54 8001D754 21082200 */  addu       $at, $at, $v0
    /* DF58 8001D758 4877278C */  lw         $a3, %lo(D_80067748)($at)
    /* DF5C 8001D75C 464E000C */  jal        func_80013918
    /* DF60 8001D760 00000000 */   nop
    /* DF64 8001D764 EE750008 */  j          .L8001D7B8
    /* DF68 8001D768 00000000 */   nop
  .L8001D76C:
    /* DF6C 8001D76C 0780033C */  lui        $v1, %hi(D_800681C8)
    /* DF70 8001D770 C881638C */  lw         $v1, %lo(D_800681C8)($v1)
    /* DF74 8001D774 04000224 */  addiu      $v0, $zero, 0x4
    /* DF78 8001D778 0D006210 */  beq        $v1, $v0, .L8001D7B0
    /* DF7C 8001D77C FFFF0224 */   addiu     $v0, $zero, -0x1
    /* DF80 8001D780 0680023C */  lui        $v0, %hi(D_80066F54)
    /* DF84 8001D784 546F428C */  lw         $v0, %lo(D_80066F54)($v0)
    /* DF88 8001D788 00000000 */  nop
    /* DF8C 8001D78C 80100200 */  sll        $v0, $v0, 2
    /* DF90 8001D790 0780013C */  lui        $at, %hi(D_8006AC04)
    /* DF94 8001D794 21082200 */  addu       $at, $at, $v0
    /* DF98 8001D798 04AC228C */  lw         $v0, %lo(D_8006AC04)($at)
    /* DF9C 8001D79C 0680013C */  lui        $at, %hi(D_800670B0)
    /* DFA0 8001D7A0 B07020AC */  sw         $zero, %lo(D_800670B0)($at)
    /* DFA4 8001D7A4 0680013C */  lui        $at, %hi(D_800670D0)
    /* DFA8 8001D7A8 D07022AC */  sw         $v0, %lo(D_800670D0)($at)
    /* DFAC 8001D7AC FFFF0224 */  addiu      $v0, $zero, -0x1
  .L8001D7B0:
    /* DFB0 8001D7B0 0680013C */  lui        $at, %hi(D_80066EEC)
    /* DFB4 8001D7B4 EC6E22AC */  sw         $v0, %lo(D_80066EEC)($at)
  .L8001D7B8:
    /* DFB8 8001D7B8 0680023C */  lui        $v0, %hi(D_80066EEC)
    /* DFBC 8001D7BC EC6E428C */  lw         $v0, %lo(D_80066EEC)($v0)
    /* DFC0 8001D7C0 00000000 */  nop
    /* DFC4 8001D7C4 03004004 */  bltz       $v0, .L8001D7D4
    /* DFC8 8001D7C8 01004224 */   addiu     $v0, $v0, 0x1
    /* DFCC 8001D7CC 0680013C */  lui        $at, %hi(D_80066EEC)
    /* DFD0 8001D7D0 EC6E22AC */  sw         $v0, %lo(D_80066EEC)($at)
  .L8001D7D4:
    /* DFD4 8001D7D4 1400BF8F */  lw         $ra, 0x14($sp)
    /* DFD8 8001D7D8 1000B08F */  lw         $s0, 0x10($sp)
    /* DFDC 8001D7DC 1800BD27 */  addiu      $sp, $sp, 0x18
    /* DFE0 8001D7E0 0800E003 */  jr         $ra
    /* DFE4 8001D7E4 00000000 */   nop
endlabel func_8001D658
