.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_65_8006D4A8

dlabel jtbl_level_65_8006D4A8
    /* 42C0A44 8006D4A8 B8F20680 */ .word .Llevel_65_8006F2B8
    /* 42C0A48 8006D4AC 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A4C 8006D4B0 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A50 8006D4B4 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A54 8006D4B8 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A58 8006D4BC 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A5C 8006D4C0 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A60 8006D4C4 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A64 8006D4C8 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A68 8006D4CC 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A6C 8006D4D0 A4F40680 */ .word .Llevel_65_8006F4A4
    /* 42C0A70 8006D4D4 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A74 8006D4D8 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A78 8006D4DC 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A7C 8006D4E0 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A80 8006D4E4 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A84 8006D4E8 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A88 8006D4EC 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A8C 8006D4F0 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A90 8006D4F4 B8F20680 */ .word .Llevel_65_8006F2B8
    /* 42C0A94 8006D4F8 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0A98 8006D4FC 24F50680 */ .word .Llevel_65_8006F524
    /* 42C0A9C 8006D500 7CF50680 */ .word .Llevel_65_8006F57C
    /* 42C0AA0 8006D504 D0F50680 */ .word .Llevel_65_8006F5D0
    /* 42C0AA4 8006D508 14F60680 */ .word .Llevel_65_8006F614
    /* 42C0AA8 8006D50C F8F60680 */ .word .Llevel_65_8006F6F8
    /* 42C0AAC 8006D510 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0AB0 8006D514 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0AB4 8006D518 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0AB8 8006D51C 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0ABC 8006D520 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0AC0 8006D524 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0AC4 8006D528 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0AC8 8006D52C 70F80680 */ .word .Llevel_65_8006F870
    /* 42C0ACC 8006D530 8CF40680 */ .word .Llevel_65_8006F48C
    /* 42C0AD0 8006D534 8CF40680 */ .word .Llevel_65_8006F48C
enddlabel jtbl_level_65_8006D4A8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_65_8006F27C, 0x608

glabel func_level_65_8006F27C
    /* 42C2818 8006F27C 0780023C */  lui        $v0, %hi(D_8006A040)
    /* 42C281C 8006F280 40A0428C */  lw         $v0, %lo(D_8006A040)($v0)
    /* 42C2820 8006F284 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 42C2824 8006F288 1400BFAF */  sw         $ra, 0x14($sp)
    /* 42C2828 8006F28C EDFF4324 */  addiu      $v1, $v0, -0x13
    /* 42C282C 8006F290 2400622C */  sltiu      $v0, $v1, 0x24
    /* 42C2830 8006F294 76014010 */  beqz       $v0, .Llevel_65_8006F870
    /* 42C2834 8006F298 1000B0AF */   sw        $s0, 0x10($sp)
    /* 42C2838 8006F29C 80100300 */  sll        $v0, $v1, 2
    /* 42C283C 8006F2A0 0780013C */  lui        $at, %hi(jtbl_level_65_8006D4A8)
    /* 42C2840 8006F2A4 21082200 */  addu       $at, $at, $v0
    /* 42C2844 8006F2A8 A8D4228C */  lw         $v0, %lo(jtbl_level_65_8006D4A8)($at)
    /* 42C2848 8006F2AC 00000000 */  nop
    /* 42C284C 8006F2B0 08004000 */  jr         $v0
    /* 42C2850 8006F2B4 00000000 */   nop
  .Llevel_65_8006F2B8:
    /* 42C2854 8006F2B8 2EAC000C */  jal        func_8002B0B8
    /* 42C2858 8006F2BC 00000000 */   nop
    /* 42C285C 8006F2C0 6B014014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2860 8006F2C4 00000000 */   nop
    /* 42C2864 8006F2C8 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 42C2868 8006F2CC A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 42C286C 8006F2D0 00000000 */  nop
    /* 42C2870 8006F2D4 40004230 */  andi       $v0, $v0, 0x40
    /* 42C2874 8006F2D8 63014014 */  bnez       $v0, .Llevel_65_8006F868
    /* 42C2878 8006F2DC 05000424 */   addiu     $a0, $zero, 0x5
    /* 42C287C 8006F2E0 0780043C */  lui        $a0, %hi(D_8006A104)
    /* 42C2880 8006F2E4 04A1848C */  lw         $a0, %lo(D_8006A104)($a0)
    /* 42C2884 8006F2E8 1EAC000C */  jal        func_8002B078
    /* 42C2888 8006F2EC 00000000 */   nop
    /* 42C288C 8006F2F0 04000324 */  addiu      $v1, $zero, 0x4
    /* 42C2890 8006F2F4 08004314 */  bne        $v0, $v1, .Llevel_65_8006F318
    /* 42C2894 8006F2F8 00000000 */   nop
    /* 42C2898 8006F2FC 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 42C289C 8006F300 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 42C28A0 8006F304 00000000 */  nop
    /* 42C28A4 8006F308 59014014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C28A8 8006F30C 09000424 */   addiu     $a0, $zero, 0x9
    /* 42C28AC 8006F310 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C28B0 8006F314 00000000 */   nop
  .Llevel_65_8006F318:
    /* 42C28B4 8006F318 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 42C28B8 8006F31C B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 42C28BC 8006F320 00000000 */  nop
    /* 42C28C0 8006F324 04004228 */  slti       $v0, $v0, 0x4
    /* 42C28C4 8006F328 4F014010 */  beqz       $v0, .Llevel_65_8006F868
    /* 42C28C8 8006F32C 06000424 */   addiu     $a0, $zero, 0x6
    /* 42C28CC 8006F330 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 42C28D0 8006F334 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 42C28D4 8006F338 00000000 */  nop
    /* 42C28D8 8006F33C 17004228 */  slti       $v0, $v0, 0x17
    /* 42C28DC 8006F340 49014010 */  beqz       $v0, .Llevel_65_8006F868
    /* 42C28E0 8006F344 00000000 */   nop
    /* 42C28E4 8006F348 0780033C */  lui        $v1, %hi(D_800683A0)
    /* 42C28E8 8006F34C A083638C */  lw         $v1, %lo(D_800683A0)($v1)
    /* 42C28EC 8006F350 00000000 */  nop
    /* 42C28F0 8006F354 80006230 */  andi       $v0, $v1, 0x80
    /* 42C28F4 8006F358 43014014 */  bnez       $v0, .Llevel_65_8006F868
    /* 42C28F8 8006F35C 0C000424 */   addiu     $a0, $zero, 0xC
    /* 42C28FC 8006F360 0780023C */  lui        $v0, %hi(D_8006A0A0)
    /* 42C2900 8006F364 A0A0428C */  lw         $v0, %lo(D_8006A0A0)($v0)
    /* 42C2904 8006F368 00000000 */  nop
    /* 42C2908 8006F36C 02004104 */  bgez       $v0, .Llevel_65_8006F378
    /* 42C290C 8006F370 00000000 */   nop
    /* 42C2910 8006F374 23100200 */  negu       $v0, $v0
  .Llevel_65_8006F378:
    /* 42C2914 8006F378 11004228 */  slti       $v0, $v0, 0x11
    /* 42C2918 8006F37C 03004014 */  bnez       $v0, .Llevel_65_8006F38C
    /* 42C291C 8006F380 0F006330 */   andi      $v1, $v1, 0xF
    /* 42C2920 8006F384 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2924 8006F388 01000424 */   addiu     $a0, $zero, 0x1
  .Llevel_65_8006F38C:
    /* 42C2928 8006F38C 03000224 */  addiu      $v0, $zero, 0x3
    /* 42C292C 8006F390 06006210 */  beq        $v1, $v0, .Llevel_65_8006F3AC
    /* 42C2930 8006F394 00000000 */   nop
    /* 42C2934 8006F398 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 42C2938 8006F39C A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 42C293C 8006F3A0 00000000 */  nop
    /* 42C2940 8006F3A4 30014014 */  bnez       $v0, .Llevel_65_8006F868
    /* 42C2944 8006F3A8 01000424 */   addiu     $a0, $zero, 0x1
  .Llevel_65_8006F3AC:
    /* 42C2948 8006F3AC 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 42C294C 8006F3B0 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 42C2950 8006F3B4 07000224 */  addiu      $v0, $zero, 0x7
    /* 42C2954 8006F3B8 06006210 */  beq        $v1, $v0, .Llevel_65_8006F3D4
    /* 42C2958 8006F3BC 00000000 */   nop
    /* 42C295C 8006F3C0 0780023C */  lui        $v0, %hi(D_8006A230)
    /* 42C2960 8006F3C4 30A2428C */  lw         $v0, %lo(D_8006A230)($v0)
    /* 42C2964 8006F3C8 00000000 */  nop
    /* 42C2968 8006F3CC 26004010 */  beqz       $v0, .Llevel_65_8006F468
    /* 42C296C 8006F3D0 00000000 */   nop
  .Llevel_65_8006F3D4:
    /* 42C2970 8006F3D4 0780103C */  lui        $s0, %hi(D_8006A040)
    /* 42C2974 8006F3D8 40A01026 */  addiu      $s0, $s0, %lo(D_8006A040)
    /* 42C2978 8006F3DC 0000028E */  lw         $v0, 0x0($s0)
    /* 42C297C 8006F3E0 00000000 */  nop
    /* 42C2980 8006F3E4 22014010 */  beqz       $v0, .Llevel_65_8006F870
    /* 42C2984 8006F3E8 00000000 */   nop
    /* 42C2988 8006F3EC 76D4000C */  jal        func_800351D8
    /* 42C298C 8006F3F0 21200000 */   addu      $a0, $zero, $zero
    /* 42C2990 8006F3F4 CCFF0292 */  lbu        $v0, -0x34($s0)
    /* 42C2994 8006F3F8 0680013C */  lui        $at, %hi(D_80062868)
    /* 42C2998 8006F3FC 21082200 */  addu       $at, $at, $v0
    /* 42C299C 8006F400 68282290 */  lbu        $v0, %lo(D_80062868)($at)
    /* 42C29A0 8006F404 00000000 */  nop
    /* 42C29A4 8006F408 6000422C */  sltiu      $v0, $v0, 0x60
    /* 42C29A8 8006F40C 09004014 */  bnez       $v0, .Llevel_65_8006F434
    /* 42C29AC 8006F410 00000000 */   nop
    /* 42C29B0 8006F414 0780023C */  lui        $v0, %hi(D_8006A005)
    /* 42C29B4 8006F418 05A04290 */  lbu        $v0, %lo(D_8006A005)($v0)
    /* 42C29B8 8006F41C 0780033C */  lui        $v1, %hi(D_8006A007)
    /* 42C29BC 8006F420 07A06390 */  lbu        $v1, %lo(D_8006A007)($v1)
    /* 42C29C0 8006F424 0780013C */  lui        $at, %hi(D_8006A004)
    /* 42C29C4 8006F428 04A022A0 */  sb         $v0, %lo(D_8006A004)($at)
    /* 42C29C8 8006F42C 0780013C */  lui        $at, %hi(D_8006A006)
    /* 42C29CC 8006F430 06A023A0 */  sb         $v1, %lo(D_8006A006)($at)
  .Llevel_65_8006F434:
    /* 42C29D0 8006F434 0780013C */  lui        $at, %hi(D_8006A007)
    /* 42C29D4 8006F438 07A020A0 */  sb         $zero, %lo(D_8006A007)($at)
    /* 42C29D8 8006F43C 0000038E */  lw         $v1, 0x0($s0)
    /* 42C29DC 8006F440 71000224 */  addiu      $v0, $zero, 0x71
    /* 42C29E0 8006F444 CCFF02A2 */  sb         $v0, -0x34($s0)
    /* 42C29E4 8006F448 0780013C */  lui        $at, %hi(D_8006A1E0)
    /* 42C29E8 8006F44C E0A120AC */  sw         $zero, %lo(D_8006A1E0)($at)
    /* 42C29EC 8006F450 0780013C */  lui        $at, %hi(D_8006A005)
    /* 42C29F0 8006F454 05A023A0 */  sb         $v1, %lo(D_8006A005)($at)
    /* 42C29F4 8006F458 0780013C */  lui        $at, %hi(D_8006A1DC)
    /* 42C29F8 8006F45C DCA123AC */  sw         $v1, %lo(D_8006A1DC)($at)
    /* 42C29FC 8006F460 1CBE0108 */  j          .Llevel_65_8006F870
    /* 42C2A00 8006F464 00000000 */   nop
  .Llevel_65_8006F468:
    /* 42C2A04 8006F468 0780023C */  lui        $v0, %hi(D_8006A0F4)
    /* 42C2A08 8006F46C F4A04290 */  lbu        $v0, %lo(D_8006A0F4)($v0)
    /* 42C2A0C 8006F470 00000000 */  nop
    /* 42C2A10 8006F474 FC004014 */  bnez       $v0, .Llevel_65_8006F868
    /* 42C2A14 8006F478 0E000424 */   addiu     $a0, $zero, 0xE
    /* 42C2A18 8006F47C 0DCB000C */  jal        func_80032C34
    /* 42C2A1C 8006F480 00000000 */   nop
    /* 42C2A20 8006F484 1CBE0108 */  j          .Llevel_65_8006F870
    /* 42C2A24 8006F488 00000000 */   nop
  .Llevel_65_8006F48C:
    /* 42C2A28 8006F48C 2EAC000C */  jal        func_8002B0B8
    /* 42C2A2C 8006F490 00000000 */   nop
    /* 42C2A30 8006F494 F6004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2A34 8006F498 21200000 */   addu      $a0, $zero, $zero
    /* 42C2A38 8006F49C 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2A3C 8006F4A0 00000000 */   nop
  .Llevel_65_8006F4A4:
    /* 42C2A40 8006F4A4 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 42C2A44 8006F4A8 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 42C2A48 8006F4AC 00000000 */  nop
    /* 42C2A4C 8006F4B0 19004228 */  slti       $v0, $v0, 0x19
    /* 42C2A50 8006F4B4 EE004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2A54 8006F4B8 00000000 */   nop
    /* 42C2A58 8006F4BC 0780023C */  lui        $v0, %hi(D_8006A248)
    /* 42C2A5C 8006F4C0 48A2428C */  lw         $v0, %lo(D_8006A248)($v0)
    /* 42C2A60 8006F4C4 00000000 */  nop
    /* 42C2A64 8006F4C8 03004104 */  bgez       $v0, .Llevel_65_8006F4D8
    /* 42C2A68 8006F4CC 0A000224 */   addiu     $v0, $zero, 0xA
    /* 42C2A6C 8006F4D0 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2A70 8006F4D4 1F000424 */   addiu     $a0, $zero, 0x1F
  .Llevel_65_8006F4D8:
    /* 42C2A74 8006F4D8 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 42C2A78 8006F4DC 3CA1638C */  lw         $v1, %lo(D_8006A13C)($v1)
    /* 42C2A7C 8006F4E0 00000000 */  nop
    /* 42C2A80 8006F4E4 03006214 */  bne        $v1, $v0, .Llevel_65_8006F4F4
    /* 42C2A84 8006F4E8 F5FF6224 */   addiu     $v0, $v1, -0xB
    /* 42C2A88 8006F4EC 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2A8C 8006F4F0 2C000424 */   addiu     $a0, $zero, 0x2C
  .Llevel_65_8006F4F4:
    /* 42C2A90 8006F4F4 0200422C */  sltiu      $v0, $v0, 0x2
    /* 42C2A94 8006F4F8 03004010 */  beqz       $v0, .Llevel_65_8006F508
    /* 42C2A98 8006F4FC 00000000 */   nop
    /* 42C2A9C 8006F500 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2AA0 8006F504 29000424 */   addiu     $a0, $zero, 0x29
  .Llevel_65_8006F508:
    /* 42C2AA4 8006F508 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 42C2AA8 8006F50C B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 42C2AAC 8006F510 00000000 */  nop
    /* 42C2AB0 8006F514 D4004010 */  beqz       $v0, .Llevel_65_8006F868
    /* 42C2AB4 8006F518 21200000 */   addu      $a0, $zero, $zero
    /* 42C2AB8 8006F51C 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2ABC 8006F520 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_65_8006F524:
    /* 42C2AC0 8006F524 2EAC000C */  jal        func_8002B0B8
    /* 42C2AC4 8006F528 00000000 */   nop
    /* 42C2AC8 8006F52C D0004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2ACC 8006F530 00000000 */   nop
    /* 42C2AD0 8006F534 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 42C2AD4 8006F538 A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 42C2AD8 8006F53C 00000000 */  nop
    /* 42C2ADC 8006F540 80004230 */  andi       $v0, $v0, 0x80
    /* 42C2AE0 8006F544 06004010 */  beqz       $v0, .Llevel_65_8006F560
    /* 42C2AE4 8006F548 01000224 */   addiu     $v0, $zero, 0x1
    /* 42C2AE8 8006F54C 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 42C2AEC 8006F550 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 42C2AF0 8006F554 00000000 */  nop
    /* 42C2AF4 8006F558 C3006214 */  bne        $v1, $v0, .Llevel_65_8006F868
    /* 42C2AF8 8006F55C 2A000424 */   addiu     $a0, $zero, 0x2A
  .Llevel_65_8006F560:
    /* 42C2AFC 8006F560 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 42C2B00 8006F564 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 42C2B04 8006F568 00000000 */  nop
    /* 42C2B08 8006F56C C0004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2B0C 8006F570 29000424 */   addiu     $a0, $zero, 0x29
    /* 42C2B10 8006F574 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2B14 8006F578 00000000 */   nop
  .Llevel_65_8006F57C:
    /* 42C2B18 8006F57C 2EAC000C */  jal        func_8002B0B8
    /* 42C2B1C 8006F580 00000000 */   nop
    /* 42C2B20 8006F584 BA004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2B24 8006F588 00000000 */   nop
    /* 42C2B28 8006F58C 0780043C */  lui        $a0, %hi(D_800683A0)
    /* 42C2B2C 8006F590 A083848C */  lw         $a0, %lo(D_800683A0)($a0)
    /* 42C2B30 8006F594 00000000 */  nop
    /* 42C2B34 8006F598 80008230 */  andi       $v0, $a0, 0x80
    /* 42C2B38 8006F59C 03004010 */  beqz       $v0, .Llevel_65_8006F5AC
    /* 42C2B3C 8006F5A0 07000224 */   addiu     $v0, $zero, 0x7
    /* 42C2B40 8006F5A4 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2B44 8006F5A8 2A000424 */   addiu     $a0, $zero, 0x2A
  .Llevel_65_8006F5AC:
    /* 42C2B48 8006F5AC 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 42C2B4C 8006F5B0 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 42C2B50 8006F5B4 00000000 */  nop
    /* 42C2B54 8006F5B8 AD006210 */  beq        $v1, $v0, .Llevel_65_8006F870
    /* 42C2B58 8006F5BC 40008230 */   andi      $v0, $a0, 0x40
    /* 42C2B5C 8006F5C0 AB004010 */  beqz       $v0, .Llevel_65_8006F870
    /* 42C2B60 8006F5C4 28000424 */   addiu     $a0, $zero, 0x28
    /* 42C2B64 8006F5C8 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2B68 8006F5CC 00000000 */   nop
  .Llevel_65_8006F5D0:
    /* 42C2B6C 8006F5D0 8AAC000C */  jal        func_8002B228
    /* 42C2B70 8006F5D4 00000000 */   nop
    /* 42C2B74 8006F5D8 A5004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2B78 8006F5DC 00000000 */   nop
    /* 42C2B7C 8006F5E0 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 42C2B80 8006F5E4 A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 42C2B84 8006F5E8 00000000 */  nop
    /* 42C2B88 8006F5EC 80004230 */  andi       $v0, $v0, 0x80
    /* 42C2B8C 8006F5F0 9F004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2B90 8006F5F4 01000224 */   addiu     $v0, $zero, 0x1
    /* 42C2B94 8006F5F8 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 42C2B98 8006F5FC 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 42C2B9C 8006F600 00000000 */  nop
    /* 42C2BA0 8006F604 9A006210 */  beq        $v1, $v0, .Llevel_65_8006F870
    /* 42C2BA4 8006F608 28000424 */   addiu     $a0, $zero, 0x28
    /* 42C2BA8 8006F60C 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2BAC 8006F610 00000000 */   nop
  .Llevel_65_8006F614:
    /* 42C2BB0 8006F614 2EAC000C */  jal        func_8002B0B8
    /* 42C2BB4 8006F618 00000000 */   nop
    /* 42C2BB8 8006F61C 94004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2BBC 8006F620 00000000 */   nop
    /* 42C2BC0 8006F624 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 42C2BC4 8006F628 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 42C2BC8 8006F62C 00000000 */  nop
    /* 42C2BCC 8006F630 40004230 */  andi       $v0, $v0, 0x40
    /* 42C2BD0 8006F634 07004010 */  beqz       $v0, .Llevel_65_8006F654
    /* 42C2BD4 8006F638 00000000 */   nop
    /* 42C2BD8 8006F63C 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 42C2BDC 8006F640 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 42C2BE0 8006F644 00000000 */  nop
    /* 42C2BE4 8006F648 09004228 */  slti       $v0, $v0, 0x9
    /* 42C2BE8 8006F64C 21004010 */  beqz       $v0, .Llevel_65_8006F6D4
    /* 42C2BEC 8006F650 05000424 */   addiu     $a0, $zero, 0x5
  .Llevel_65_8006F654:
    /* 42C2BF0 8006F654 0780043C */  lui        $a0, %hi(D_8006A0F8)
    /* 42C2BF4 8006F658 F8A08424 */  addiu      $a0, $a0, %lo(D_8006A0F8)
    /* 42C2BF8 8006F65C 00008290 */  lbu        $v0, 0x0($a0)
    /* 42C2BFC 8006F660 00000000 */  nop
    /* 42C2C00 8006F664 1A004010 */  beqz       $v0, .Llevel_65_8006F6D0
    /* 42C2C04 8006F668 00000000 */   nop
    /* 42C2C08 8006F66C 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 42C2C0C 8006F670 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 42C2C10 8006F674 00000000 */  nop
    /* 42C2C14 8006F678 80004230 */  andi       $v0, $v0, 0x80
    /* 42C2C18 8006F67C 17004010 */  beqz       $v0, .Llevel_65_8006F6DC
    /* 42C2C1C 8006F680 00000000 */   nop
    /* 42C2C20 8006F684 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 42C2C24 8006F688 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 42C2C28 8006F68C 00000000 */  nop
    /* 42C2C2C 8006F690 09004228 */  slti       $v0, $v0, 0x9
    /* 42C2C30 8006F694 11004014 */  bnez       $v0, .Llevel_65_8006F6DC
    /* 42C2C34 8006F698 00000000 */   nop
    /* 42C2C38 8006F69C 0680023C */  lui        $v0, %hi(D_80064682)
    /* 42C2C3C 8006F6A0 82464284 */  lh         $v0, %lo(D_80064682)($v0)
    /* 42C2C40 8006F6A4 00000000 */  nop
    /* 42C2C44 8006F6A8 0C004010 */  beqz       $v0, .Llevel_65_8006F6DC
    /* 42C2C48 8006F6AC F8FE8424 */   addiu     $a0, $a0, -0x108
    /* 42C2C4C 8006F6B0 00040524 */  addiu      $a1, $zero, 0x400
    /* 42C2C50 8006F6B4 01000624 */  addiu      $a2, $zero, 0x1
    /* 42C2C54 8006F6B8 8FFB000C */  jal        func_8003EE3C
    /* 42C2C58 8006F6BC 21380000 */   addu      $a3, $zero, $zero
    /* 42C2C5C 8006F6C0 06004014 */  bnez       $v0, .Llevel_65_8006F6DC
    /* 42C2C60 8006F6C4 28000424 */   addiu     $a0, $zero, 0x28
    /* 42C2C64 8006F6C8 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2C68 8006F6CC 00000000 */   nop
  .Llevel_65_8006F6D0:
    /* 42C2C6C 8006F6D0 06000424 */  addiu      $a0, $zero, 0x6
  .Llevel_65_8006F6D4:
    /* 42C2C70 8006F6D4 76D4000C */  jal        func_800351D8
    /* 42C2C74 8006F6D8 00000000 */   nop
  .Llevel_65_8006F6DC:
    /* 42C2C78 8006F6DC 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 42C2C7C 8006F6E0 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 42C2C80 8006F6E4 00000000 */  nop
    /* 42C2C84 8006F6E8 61004010 */  beqz       $v0, .Llevel_65_8006F870
    /* 42C2C88 8006F6EC 2C000424 */   addiu     $a0, $zero, 0x2C
    /* 42C2C8C 8006F6F0 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2C90 8006F6F4 00000000 */   nop
  .Llevel_65_8006F6F8:
    /* 42C2C94 8006F6F8 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 42C2C98 8006F6FC 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 42C2C9C 8006F700 01000224 */  addiu      $v0, $zero, 0x1
    /* 42C2CA0 8006F704 1F006214 */  bne        $v1, $v0, .Llevel_65_8006F784
    /* 42C2CA4 8006F708 00000000 */   nop
    /* 42C2CA8 8006F70C 0780023C */  lui        $v0, %hi(D_8006ABF8)
    /* 42C2CAC 8006F710 F8AB4290 */  lbu        $v0, %lo(D_8006ABF8)($v0)
    /* 42C2CB0 8006F714 00000000 */  nop
    /* 42C2CB4 8006F718 55004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2CB8 8006F71C 00000000 */   nop
    /* 42C2CBC 8006F720 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 42C2CC0 8006F724 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 42C2CC4 8006F728 00000000 */  nop
    /* 42C2CC8 8006F72C 50084230 */  andi       $v0, $v0, 0x850
    /* 42C2CCC 8006F730 07004014 */  bnez       $v0, .Llevel_65_8006F750
    /* 42C2CD0 8006F734 00000000 */   nop
    /* 42C2CD4 8006F738 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 42C2CD8 8006F73C 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 42C2CDC 8006F740 00000000 */  nop
    /* 42C2CE0 8006F744 3D004228 */  slti       $v0, $v0, 0x3D
    /* 42C2CE4 8006F748 49004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2CE8 8006F74C 00000000 */   nop
  .Llevel_65_8006F750:
    /* 42C2CEC 8006F750 0680023C */  lui        $v0, %hi(D_80066F8C)
    /* 42C2CF0 8006F754 8C6F428C */  lw         $v0, %lo(D_80066F8C)($v0)
    /* 42C2CF4 8006F758 00000000 */  nop
    /* 42C2CF8 8006F75C 05004010 */  beqz       $v0, .Llevel_65_8006F774
    /* 42C2CFC 8006F760 00000000 */   nop
    /* 42C2D00 8006F764 09F84000 */  jalr       $v0
    /* 42C2D04 8006F768 00000000 */   nop
    /* 42C2D08 8006F76C 1CBE0108 */  j          .Llevel_65_8006F870
    /* 42C2D0C 8006F770 00000000 */   nop
  .Llevel_65_8006F774:
    /* 42C2D10 8006F774 9DCB000C */  jal        func_80032E74
    /* 42C2D14 8006F778 00000000 */   nop
    /* 42C2D18 8006F77C 1CBE0108 */  j          .Llevel_65_8006F870
    /* 42C2D1C 8006F780 00000000 */   nop
  .Llevel_65_8006F784:
    /* 42C2D20 8006F784 2EAC000C */  jal        func_8002B0B8
    /* 42C2D24 8006F788 00000000 */   nop
    /* 42C2D28 8006F78C 38004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2D2C 8006F790 00000000 */   nop
    /* 42C2D30 8006F794 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 42C2D34 8006F798 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 42C2D38 8006F79C 00000000 */  nop
    /* 42C2D3C 8006F7A0 40004230 */  andi       $v0, $v0, 0x40
    /* 42C2D40 8006F7A4 07004010 */  beqz       $v0, .Llevel_65_8006F7C4
    /* 42C2D44 8006F7A8 00000000 */   nop
    /* 42C2D48 8006F7AC 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 42C2D4C 8006F7B0 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 42C2D50 8006F7B4 00000000 */  nop
    /* 42C2D54 8006F7B8 09004228 */  slti       $v0, $v0, 0x9
    /* 42C2D58 8006F7BC 2A004010 */  beqz       $v0, .Llevel_65_8006F868
    /* 42C2D5C 8006F7C0 05000424 */   addiu     $a0, $zero, 0x5
  .Llevel_65_8006F7C4:
    /* 42C2D60 8006F7C4 0780043C */  lui        $a0, %hi(D_8006A0F8)
    /* 42C2D64 8006F7C8 F8A08424 */  addiu      $a0, $a0, %lo(D_8006A0F8)
    /* 42C2D68 8006F7CC 00008290 */  lbu        $v0, 0x0($a0)
    /* 42C2D6C 8006F7D0 00000000 */  nop
    /* 42C2D70 8006F7D4 03004014 */  bnez       $v0, .Llevel_65_8006F7E4
    /* 42C2D74 8006F7D8 00000000 */   nop
    /* 42C2D78 8006F7DC 1ABE0108 */  j          .Llevel_65_8006F868
    /* 42C2D7C 8006F7E0 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_65_8006F7E4:
    /* 42C2D80 8006F7E4 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 42C2D84 8006F7E8 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 42C2D88 8006F7EC 00000000 */  nop
    /* 42C2D8C 8006F7F0 80004230 */  andi       $v0, $v0, 0x80
    /* 42C2D90 8006F7F4 12004010 */  beqz       $v0, .Llevel_65_8006F840
    /* 42C2D94 8006F7F8 00000000 */   nop
    /* 42C2D98 8006F7FC 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 42C2D9C 8006F800 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 42C2DA0 8006F804 00000000 */  nop
    /* 42C2DA4 8006F808 09004228 */  slti       $v0, $v0, 0x9
    /* 42C2DA8 8006F80C 0C004014 */  bnez       $v0, .Llevel_65_8006F840
    /* 42C2DAC 8006F810 00000000 */   nop
    /* 42C2DB0 8006F814 0680023C */  lui        $v0, %hi(D_80064682)
    /* 42C2DB4 8006F818 82464284 */  lh         $v0, %lo(D_80064682)($v0)
    /* 42C2DB8 8006F81C 00000000 */  nop
    /* 42C2DBC 8006F820 07004010 */  beqz       $v0, .Llevel_65_8006F840
    /* 42C2DC0 8006F824 F8FE8424 */   addiu     $a0, $a0, -0x108
    /* 42C2DC4 8006F828 00040524 */  addiu      $a1, $zero, 0x400
    /* 42C2DC8 8006F82C 01000624 */  addiu      $a2, $zero, 0x1
    /* 42C2DCC 8006F830 8FFB000C */  jal        func_8003EE3C
    /* 42C2DD0 8006F834 21380000 */   addu      $a3, $zero, $zero
    /* 42C2DD4 8006F838 0B004010 */  beqz       $v0, .Llevel_65_8006F868
    /* 42C2DD8 8006F83C 28000424 */   addiu     $a0, $zero, 0x28
  .Llevel_65_8006F840:
    /* 42C2DDC 8006F840 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 42C2DE0 8006F844 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 42C2DE4 8006F848 07000224 */  addiu      $v0, $zero, 0x7
    /* 42C2DE8 8006F84C 08006210 */  beq        $v1, $v0, .Llevel_65_8006F870
    /* 42C2DEC 8006F850 00000000 */   nop
    /* 42C2DF0 8006F854 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 42C2DF4 8006F858 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 42C2DF8 8006F85C 00000000 */  nop
    /* 42C2DFC 8006F860 03004014 */  bnez       $v0, .Llevel_65_8006F870
    /* 42C2E00 8006F864 2B000424 */   addiu     $a0, $zero, 0x2B
  .Llevel_65_8006F868:
    /* 42C2E04 8006F868 76D4000C */  jal        func_800351D8
    /* 42C2E08 8006F86C 00000000 */   nop
  .Llevel_65_8006F870:
    /* 42C2E0C 8006F870 1400BF8F */  lw         $ra, 0x14($sp)
    /* 42C2E10 8006F874 1000B08F */  lw         $s0, 0x10($sp)
    /* 42C2E14 8006F878 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 42C2E18 8006F87C 0800E003 */  jr         $ra
    /* 42C2E1C 8006F880 00000000 */   nop
endlabel func_level_65_8006F27C
