.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
nonmatching jtbl_80011060

dlabel jtbl_80011060
    /* 1860 80011060 D4A20380 */ .word .L8003A2D4
    /* 1864 80011064 C8A30380 */ .word .L8003A3C8
    /* 1868 80011068 2CA30380 */ .word .L8003A32C
    /* 186C 8001106C 6CA40380 */ .word .L8003A46C
    /* 1870 80011070 90A40380 */ .word .L8003A490
    /* 1874 80011074 F4A40380 */ .word .L8003A4F4
    /* 1878 80011078 0CA30380 */ .word .L8003A30C
    /* 187C 8001107C 84A40380 */ .word .L8003A484
    /* 1880 80011080 84A40380 */ .word .L8003A484
    /* 1884 80011084 D0A40380 */ .word .L8003A4D0
    /* 1888 80011088 E0A20380 */ .word .L8003A2E0
    /* 188C 8001108C 00000000 */ .word 0x00000000
enddlabel jtbl_80011060


.section .text
/* Generated by spimdisasm 1.39.3 */

nonmatching func_8003A0D8, 0x490

glabel func_8003A0D8
    /* 2A8D8 8003A0D8 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 2A8DC 8003A0DC 2C00B5AF */  sw         $s5, 0x2C($sp)
    /* 2A8E0 8003A0E0 21A80000 */  addu       $s5, $zero, $zero
    /* 2A8E4 8003A0E4 2400B3AF */  sw         $s3, 0x24($sp)
    /* 2A8E8 8003A0E8 21100000 */  addu       $v0, $zero, $zero
    /* 2A8EC 8003A0EC 3800BFAF */  sw         $ra, 0x38($sp)
    /* 2A8F0 8003A0F0 3400B7AF */  sw         $s7, 0x34($sp)
    /* 2A8F4 8003A0F4 3000B6AF */  sw         $s6, 0x30($sp)
    /* 2A8F8 8003A0F8 2800B4AF */  sw         $s4, 0x28($sp)
    /* 2A8FC 8003A0FC 2000B2AF */  sw         $s2, 0x20($sp)
    /* 2A900 8003A100 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 2A904 8003A104 1800B0AF */  sw         $s0, 0x18($sp)
    /* 2A908 8003A108 0000928C */  lw         $s2, 0x0($a0)
    /* 2A90C 8003A10C 05014014 */  bnez       $v0, .L8003A524
    /* 2A910 8003A110 21980000 */   addu      $s3, $zero, $zero
    /* 2A914 8003A114 01001424 */  addiu      $s4, $zero, 0x1
    /* 2A918 8003A118 FF001624 */  addiu      $s6, $zero, 0xFF
    /* 2A91C 8003A11C 80101300 */  sll        $v0, $s3, 2
  .L8003A120:
    /* 2A920 8003A120 21105200 */  addu       $v0, $v0, $s2
    /* 2A924 8003A124 1000518C */  lw         $s1, 0x10($v0)
    /* 2A928 8003A128 00000000 */  nop
    /* 2A92C 8003A12C 00002292 */  lbu        $v0, 0x0($s1)
    /* 2A930 8003A130 00000000 */  nop
    /* 2A934 8003A134 21B82202 */  addu       $s7, $s1, $v0
    /* 2A938 8003A138 01003126 */  addiu      $s1, $s1, 0x1
    /* 2A93C 8003A13C 2B103702 */  sltu       $v0, $s1, $s7
    /* 2A940 8003A140 F1004010 */  beqz       $v0, .L8003A508
    /* 2A944 8003A144 00000000 */   nop
    /* 2A948 8003A148 01003026 */  addiu      $s0, $s1, 0x1
  .L8003A14C:
    /* 2A94C 8003A14C 00002392 */  lbu        $v1, 0x0($s1)
    /* 2A950 8003A150 00000000 */  nop
    /* 2A954 8003A154 52006010 */  beqz       $v1, .L8003A2A0
    /* 2A958 8003A158 0A00622C */   sltiu     $v0, $v1, 0xA
    /* 2A95C 8003A15C 50004010 */  beqz       $v0, .L8003A2A0
    /* 2A960 8003A160 FFFF6224 */   addiu     $v0, $v1, -0x1
    /* 2A964 8003A164 1D004014 */  bnez       $v0, .L8003A1DC
    /* 2A968 8003A168 08004228 */   slti      $v0, $v0, 0x8
    /* 2A96C 8003A16C 0680023C */  lui        $v0, %hi(D_80066F44)
    /* 2A970 8003A170 446F4290 */  lbu        $v0, %lo(D_80066F44)($v0)
    /* 2A974 8003A174 00000000 */  nop
    /* 2A978 8003A178 DE004010 */  beqz       $v0, .L8003A4F4
    /* 2A97C 8003A17C 00000000 */   nop
    /* 2A980 8003A180 0680023C */  lui        $v0, %hi(D_80066FF4)
    /* 2A984 8003A184 F46F4290 */  lbu        $v0, %lo(D_80066FF4)($v0)
    /* 2A988 8003A188 00000000 */  nop
    /* 2A98C 8003A18C D9004014 */  bnez       $v0, .L8003A4F4
    /* 2A990 8003A190 00000000 */   nop
    /* 2A994 8003A194 020053A2 */  sb         $s3, 0x2($s2)
    /* 2A998 8003A198 0680013C */  lui        $at, %hi(D_80066FCC)
    /* 2A99C 8003A19C CC6F20AC */  sw         $zero, %lo(D_80066FCC)($at)
    /* 2A9A0 8003A1A0 00000292 */  lbu        $v0, 0x0($s0)
    /* 2A9A4 8003A1A4 0680033C */  lui        $v1, %hi(D_80066F54)
    /* 2A9A8 8003A1A8 546F638C */  lw         $v1, %lo(D_80066F54)($v1)
    /* 2A9AC 8003A1AC 0680013C */  lui        $at, %hi(D_80066F94)
    /* 2A9B0 8003A1B0 946F22AC */  sw         $v0, %lo(D_80066F94)($at)
    /* 2A9B4 8003A1B4 0780013C */  lui        $at, %hi(D_8006B264)
    /* 2A9B8 8003A1B8 21082300 */  addu       $at, $at, $v1
    /* 2A9BC 8003A1BC 64B22290 */  lbu        $v0, %lo(D_8006B264)($at)
    /* 2A9C0 8003A1C0 00000000 */  nop
    /* 2A9C4 8003A1C4 CB004010 */  beqz       $v0, .L8003A4F4
    /* 2A9C8 8003A1C8 00000000 */   nop
    /* 2A9CC 8003A1CC 0680013C */  lui        $at, %hi(D_80067164)
    /* 2A9D0 8003A1D0 647134AC */  sw         $s4, %lo(D_80067164)($at)
    /* 2A9D4 8003A1D4 3EE90008 */  j          .L8003A4F8
    /* 2A9D8 8003A1D8 02001026 */   addiu     $s0, $s0, 0x2
  .L8003A1DC:
    /* 2A9DC 8003A1DC C5004010 */  beqz       $v0, .L8003A4F4
    /* 2A9E0 8003A1E0 FEFF6324 */   addiu     $v1, $v1, -0x2
    /* 2A9E4 8003A1E4 0680023C */  lui        $v0, %hi(D_80067148)
    /* 2A9E8 8003A1E8 48714290 */  lbu        $v0, %lo(D_80067148)($v0)
    /* 2A9EC 8003A1EC 04287400 */  sllv       $a1, $s4, $v1
    /* 2A9F0 8003A1F0 24104500 */  and        $v0, $v0, $a1
    /* 2A9F4 8003A1F4 BF004010 */  beqz       $v0, .L8003A4F4
    /* 2A9F8 8003A1F8 00000000 */   nop
    /* 2A9FC 8003A1FC 0680023C */  lui        $v0, %hi(D_80066FF0)
    /* 2AA00 8003A200 F06F4290 */  lbu        $v0, %lo(D_80066FF0)($v0)
    /* 2AA04 8003A204 00000000 */  nop
    /* 2AA08 8003A208 24104500 */  and        $v0, $v0, $a1
    /* 2AA0C 8003A20C B9004014 */  bnez       $v0, .L8003A4F4
    /* 2AA10 8003A210 00000000 */   nop
    /* 2AA14 8003A214 020053A2 */  sb         $s3, 0x2($s2)
    /* 2AA18 8003A218 0680013C */  lui        $at, %hi(D_80066FCC)
    /* 2AA1C 8003A21C CC6F20AC */  sw         $zero, %lo(D_80066FCC)($at)
    /* 2AA20 8003A220 00000392 */  lbu        $v1, 0x0($s0)
    /* 2AA24 8003A224 0680023C */  lui        $v0, %hi(D_80066FF0)
    /* 2AA28 8003A228 F06F4290 */  lbu        $v0, %lo(D_80066FF0)($v0)
    /* 2AA2C 8003A22C 0680013C */  lui        $at, %hi(D_80066F94)
    /* 2AA30 8003A230 946F23AC */  sw         $v1, %lo(D_80066F94)($at)
    /* 2AA34 8003A234 0680033C */  lui        $v1, %hi(D_80066F54)
    /* 2AA38 8003A238 546F638C */  lw         $v1, %lo(D_80066F54)($v1)
    /* 2AA3C 8003A23C 25104500 */  or         $v0, $v0, $a1
    /* 2AA40 8003A240 0680013C */  lui        $at, %hi(D_80066FF0)
    /* 2AA44 8003A244 F06F22A0 */  sb         $v0, %lo(D_80066FF0)($at)
    /* 2AA48 8003A248 0780023C */  lui        $v0, %hi(D_80069FD0)
    /* 2AA4C 8003A24C D09F4224 */  addiu      $v0, $v0, %lo(D_80069FD0)
    /* 2AA50 8003A250 21186200 */  addu       $v1, $v1, $v0
    /* 2AA54 8003A254 00006490 */  lbu        $a0, 0x0($v1)
    /* 2AA58 8003A258 00000000 */  nop
    /* 2AA5C 8003A25C 24108500 */  and        $v0, $a0, $a1
    /* 2AA60 8003A260 0B004014 */  bnez       $v0, .L8003A290
    /* 2AA64 8003A264 01001524 */   addiu     $s5, $zero, 0x1
    /* 2AA68 8003A268 25108500 */  or         $v0, $a0, $a1
    /* 2AA6C 8003A26C 000062A0 */  sb         $v0, 0x0($v1)
    /* 2AA70 8003A270 0680023C */  lui        $v0, %hi(D_8006702C)
    /* 2AA74 8003A274 2C70428C */  lw         $v0, %lo(D_8006702C)($v0)
    /* 2AA78 8003A278 00000000 */  nop
    /* 2AA7C 8003A27C 01004224 */  addiu      $v0, $v0, 0x1
    /* 2AA80 8003A280 0680013C */  lui        $at, %hi(D_8006702C)
    /* 2AA84 8003A284 2C7022AC */  sw         $v0, %lo(D_8006702C)($at)
    /* 2AA88 8003A288 3EE90008 */  j          .L8003A4F8
    /* 2AA8C 8003A28C 02001026 */   addiu     $s0, $s0, 0x2
  .L8003A290:
    /* 2AA90 8003A290 0680013C */  lui        $at, %hi(D_80067164)
    /* 2AA94 8003A294 647135AC */  sw         $s5, %lo(D_80067164)($at)
    /* 2AA98 8003A298 3EE90008 */  j          .L8003A4F8
    /* 2AA9C 8003A29C 02001026 */   addiu     $s0, $s0, 0x2
  .L8003A2A0:
    /* 2AAA0 8003A2A0 00002292 */  lbu        $v0, 0x0($s1)
    /* 2AAA4 8003A2A4 00000000 */  nop
    /* 2AAA8 8003A2A8 DDFF4324 */  addiu      $v1, $v0, -0x23
    /* 2AAAC 8003A2AC 0B00622C */  sltiu      $v0, $v1, 0xB
    /* 2AAB0 8003A2B0 93004010 */  beqz       $v0, .L8003A500
    /* 2AAB4 8003A2B4 2B103702 */   sltu      $v0, $s1, $s7
    /* 2AAB8 8003A2B8 80100300 */  sll        $v0, $v1, 2
    /* 2AABC 8003A2BC 0180013C */  lui        $at, %hi(jtbl_80011060)
    /* 2AAC0 8003A2C0 21082200 */  addu       $at, $at, $v0
    /* 2AAC4 8003A2C4 6010228C */  lw         $v0, %lo(jtbl_80011060)($at)
    /* 2AAC8 8003A2C8 00000000 */  nop
    /* 2AACC 8003A2CC 08004000 */  jr         $v0
    /* 2AAD0 8003A2D0 00000000 */   nop
  .L8003A2D4:
    /* 2AAD4 8003A2D4 03001026 */  addiu      $s0, $s0, 0x3
    /* 2AAD8 8003A2D8 3FE90008 */  j          .L8003A4FC
    /* 2AADC 8003A2DC 03003126 */   addiu     $s1, $s1, 0x3
  .L8003A2E0:
    /* 2AAE0 8003A2E0 02004292 */  lbu        $v0, 0x2($s2)
    /* 2AAE4 8003A2E4 00000000 */  nop
    /* 2AAE8 8003A2E8 82005314 */  bne        $v0, $s3, .L8003A4F4
    /* 2AAEC 8003A2EC 00000000 */   nop
    /* 2AAF0 8003A2F0 00000292 */  lbu        $v0, 0x0($s0)
    /* 2AAF4 8003A2F4 00000000 */  nop
    /* 2AAF8 8003A2F8 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 2AAFC 8003A2FC 0680013C */  lui        $at, %hi(D_80066FCC)
    /* 2AB00 8003A300 CC6F22AC */  sw         $v0, %lo(D_80066FCC)($at)
    /* 2AB04 8003A304 3EE90008 */  j          .L8003A4F8
    /* 2AB08 8003A308 02001026 */   addiu     $s0, $s0, 0x2
  .L8003A30C:
    /* 2AB0C 8003A30C 02004292 */  lbu        $v0, 0x2($s2)
    /* 2AB10 8003A310 00000000 */  nop
    /* 2AB14 8003A314 77005314 */  bne        $v0, $s3, .L8003A4F4
    /* 2AB18 8003A318 00000000 */   nop
    /* 2AB1C 8003A31C 0680013C */  lui        $at, %hi(D_80066FE8)
    /* 2AB20 8003A320 E86F34AC */  sw         $s4, %lo(D_80066FE8)($at)
    /* 2AB24 8003A324 3EE90008 */  j          .L8003A4F8
    /* 2AB28 8003A328 02001026 */   addiu     $s0, $s0, 0x2
  .L8003A32C:
    /* 2AB2C 8003A32C 02004292 */  lbu        $v0, 0x2($s2)
    /* 2AB30 8003A330 00000000 */  nop
    /* 2AB34 8003A334 21005314 */  bne        $v0, $s3, .L8003A3BC
    /* 2AB38 8003A338 00000000 */   nop
    /* 2AB3C 8003A33C 02000292 */  lbu        $v0, 0x2($s0)
    /* 2AB40 8003A340 00000000 */  nop
    /* 2AB44 8003A344 FFFF4324 */  addiu      $v1, $v0, -0x1
    /* 2AB48 8003A348 FE000224 */  addiu      $v0, $zero, 0xFE
    /* 2AB4C 8003A34C 1B006210 */  beq        $v1, $v0, .L8003A3BC
    /* 2AB50 8003A350 80180300 */   sll       $v1, $v1, 2
    /* 2AB54 8003A354 0680013C */  lui        $at, %hi(D_80064670)
    /* 2AB58 8003A358 21082300 */  addu       $at, $at, $v1
    /* 2AB5C 8003A35C 70462284 */  lh         $v0, %lo(D_80064670)($at)
    /* 2AB60 8003A360 0680013C */  lui        $at, %hi(D_80066F6C)
    /* 2AB64 8003A364 6C6F22AC */  sw         $v0, %lo(D_80066F6C)($at)
    /* 2AB68 8003A368 0680013C */  lui        $at, %hi(D_80064672)
    /* 2AB6C 8003A36C 21082300 */  addu       $at, $at, $v1
    /* 2AB70 8003A370 72462284 */  lh         $v0, %lo(D_80064672)($at)
    /* 2AB74 8003A374 0680013C */  lui        $at, %hi(D_80067104)
    /* 2AB78 8003A378 047134AC */  sw         $s4, %lo(D_80067104)($at)
    /* 2AB7C 8003A37C 0F004014 */  bnez       $v0, .L8003A3BC
    /* 2AB80 8003A380 00000000 */   nop
    /* 2AB84 8003A384 0680013C */  lui        $at, %hi(D_80064670)
    /* 2AB88 8003A388 21082300 */  addu       $at, $at, $v1
    /* 2AB8C 8003A38C 70462384 */  lh         $v1, %lo(D_80064670)($at)
    /* 2AB90 8003A390 0680023C */  lui        $v0, %hi(D_800670CC)
    /* 2AB94 8003A394 CC70428C */  lw         $v0, %lo(D_800670CC)($v0)
    /* 2AB98 8003A398 00000000 */  nop
    /* 2AB9C 8003A39C 2A104300 */  slt        $v0, $v0, $v1
    /* 2ABA0 8003A3A0 06004010 */  beqz       $v0, .L8003A3BC
    /* 2ABA4 8003A3A4 00000000 */   nop
    /* 2ABA8 8003A3A8 03000292 */  lbu        $v0, 0x3($s0)
    /* 2ABAC 8003A3AC 00000000 */  nop
    /* 2ABB0 8003A3B0 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 2ABB4 8003A3B4 4EE90008 */  j          .L8003A538
    /* 2ABB8 8003A3B8 020042A2 */   sb        $v0, 0x2($s2)
  .L8003A3BC:
    /* 2ABBC 8003A3BC 05001026 */  addiu      $s0, $s0, 0x5
    /* 2ABC0 8003A3C0 3FE90008 */  j          .L8003A4FC
    /* 2ABC4 8003A3C4 05003126 */   addiu     $s1, $s1, 0x5
  .L8003A3C8:
    /* 2ABC8 8003A3C8 00000492 */  lbu        $a0, 0x0($s0)
    /* 2ABCC 8003A3CC 00000000 */  nop
    /* 2ABD0 8003A3D0 FFFF8324 */  addiu      $v1, $a0, -0x1
    /* 2ABD4 8003A3D4 05006014 */  bnez       $v1, .L8003A3EC
    /* 2ABD8 8003A3D8 0A006228 */   slti      $v0, $v1, 0xA
    /* 2ABDC 8003A3DC 0680023C */  lui        $v0, %hi(D_80066F44)
    /* 2ABE0 8003A3E0 446F4290 */  lbu        $v0, %lo(D_80066F44)($v0)
    /* 2ABE4 8003A3E4 0BE90008 */  j          .L8003A42C
    /* 2ABE8 8003A3E8 00000000 */   nop
  .L8003A3EC:
    /* 2ABEC 8003A3EC 09004010 */  beqz       $v0, .L8003A414
    /* 2ABF0 8003A3F0 FEFF8224 */   addiu     $v0, $a0, -0x2
    /* 2ABF4 8003A3F4 0680033C */  lui        $v1, %hi(D_80067148)
    /* 2ABF8 8003A3F8 48716390 */  lbu        $v1, %lo(D_80067148)($v1)
    /* 2ABFC 8003A3FC 04105400 */  sllv       $v0, $s4, $v0
    /* 2AC00 8003A400 24186200 */  and        $v1, $v1, $v0
    /* 2AC04 8003A404 3B006010 */  beqz       $v1, .L8003A4F4
    /* 2AC08 8003A408 21200002 */   addu      $a0, $s0, $zero
    /* 2AC0C 8003A40C 0EE90008 */  j          .L8003A438
    /* 2AC10 8003A410 00000000 */   nop
  .L8003A414:
    /* 2AC14 8003A414 14006228 */  slti       $v0, $v1, 0x14
    /* 2AC18 8003A418 36004010 */  beqz       $v0, .L8003A4F4
    /* 2AC1C 8003A41C 00000000 */   nop
    /* 2AC20 8003A420 0780013C */  lui        $at, %hi(D_8006ABEE)
    /* 2AC24 8003A424 21082300 */  addu       $at, $at, $v1
    /* 2AC28 8003A428 EEAB2290 */  lbu        $v0, %lo(D_8006ABEE)($at)
  .L8003A42C:
    /* 2AC2C 8003A42C 00000000 */  nop
    /* 2AC30 8003A430 30004010 */  beqz       $v0, .L8003A4F4
    /* 2AC34 8003A434 21200002 */   addu      $a0, $s0, $zero
  .L8003A438:
    /* 2AC38 8003A438 0680063C */  lui        $a2, %hi(D_8006718C)
    /* 2AC3C 8003A43C 8C71C624 */  addiu      $a2, $a2, %lo(D_8006718C)
    /* 2AC40 8003A440 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 2AC44 8003A444 020053A2 */  sb         $s3, 0x2($s2)
    /* 2AC48 8003A448 000016A2 */  sb         $s6, 0x0($s0)
    /* 2AC4C 8003A44C 0680013C */  lui        $at, %hi(D_80066FE8)
    /* 2AC50 8003A450 E86F22AC */  sw         $v0, %lo(D_80066FE8)($at)
    /* 2AC54 8003A454 0680013C */  lui        $at, %hi(D_80066FCC)
    /* 2AC58 8003A458 CC6F20AC */  sw         $zero, %lo(D_80066FCC)($at)
    /* 2AC5C 8003A45C 8530010C */  jal        func_8004C214
    /* 2AC60 8003A460 01000524 */   addiu     $a1, $zero, 0x1
    /* 2AC64 8003A464 3EE90008 */  j          .L8003A4F8
    /* 2AC68 8003A468 02001026 */   addiu     $s0, $s0, 0x2
  .L8003A46C:
    /* 2AC6C 8003A46C 02004292 */  lbu        $v0, 0x2($s2)
    /* 2AC70 8003A470 00000000 */  nop
    /* 2AC74 8003A474 03006216 */  bne        $s3, $v0, .L8003A484
    /* 2AC78 8003A478 00000000 */   nop
    /* 2AC7C 8003A47C 0680013C */  lui        $at, %hi(D_80066FBC)
    /* 2AC80 8003A480 BC6F34AC */  sw         $s4, %lo(D_80066FBC)($at)
  .L8003A484:
    /* 2AC84 8003A484 01001026 */  addiu      $s0, $s0, 0x1
    /* 2AC88 8003A488 3FE90008 */  j          .L8003A4FC
    /* 2AC8C 8003A48C 01003126 */   addiu     $s1, $s1, 0x1
  .L8003A490:
    /* 2AC90 8003A490 02004292 */  lbu        $v0, 0x2($s2)
    /* 2AC94 8003A494 00000000 */  nop
    /* 2AC98 8003A498 16006216 */  bne        $s3, $v0, .L8003A4F4
    /* 2AC9C 8003A49C 00000000 */   nop
    /* 2ACA0 8003A4A0 0780033C */  lui        $v1, %hi(D_8006A980)
    /* 2ACA4 8003A4A4 80A96324 */  addiu      $v1, $v1, %lo(D_8006A980)
    /* 2ACA8 8003A4A8 0680043C */  lui        $a0, %hi(D_80066F54)
    /* 2ACAC 8003A4AC 546F848C */  lw         $a0, %lo(D_80066F54)($a0)
    /* 2ACB0 8003A4B0 00000292 */  lbu        $v0, 0x0($s0)
    /* 2ACB4 8003A4B4 21208300 */  addu       $a0, $a0, $v1
    /* 2ACB8 8003A4B8 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 2ACBC 8003A4BC 00008390 */  lbu        $v1, 0x0($a0)
    /* 2ACC0 8003A4C0 04105400 */  sllv       $v0, $s4, $v0
    /* 2ACC4 8003A4C4 25186200 */  or         $v1, $v1, $v0
    /* 2ACC8 8003A4C8 3DE90008 */  j          .L8003A4F4
    /* 2ACCC 8003A4CC 000083A0 */   sb        $v1, 0x0($a0)
  .L8003A4D0:
    /* 2ACD0 8003A4D0 02004292 */  lbu        $v0, 0x2($s2)
    /* 2ACD4 8003A4D4 00000000 */  nop
    /* 2ACD8 8003A4D8 06006216 */  bne        $s3, $v0, .L8003A4F4
    /* 2ACDC 8003A4DC 00000000 */   nop
    /* 2ACE0 8003A4E0 00000292 */  lbu        $v0, 0x0($s0)
    /* 2ACE4 8003A4E4 00000000 */  nop
    /* 2ACE8 8003A4E8 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 2ACEC 8003A4EC 0680013C */  lui        $at, %hi(D_80066F5C)
    /* 2ACF0 8003A4F0 5C6F22AC */  sw         $v0, %lo(D_80066F5C)($at)
  .L8003A4F4:
    /* 2ACF4 8003A4F4 02001026 */  addiu      $s0, $s0, 0x2
  .L8003A4F8:
    /* 2ACF8 8003A4F8 02003126 */  addiu      $s1, $s1, 0x2
  .L8003A4FC:
    /* 2ACFC 8003A4FC 2B103702 */  sltu       $v0, $s1, $s7
  .L8003A500:
    /* 2AD00 8003A500 12FF4014 */  bnez       $v0, .L8003A14C
    /* 2AD04 8003A504 00000000 */   nop
  .L8003A508:
    /* 2AD08 8003A508 03004292 */  lbu        $v0, 0x3($s2)
    /* 2AD0C 8003A50C 01007326 */  addiu      $s3, $s3, 0x1
    /* 2AD10 8003A510 2A105300 */  slt        $v0, $v0, $s3
    /* 2AD14 8003A514 04004014 */  bnez       $v0, .L8003A528
    /* 2AD18 8003A518 02004426 */   addiu     $a0, $s2, 0x2
    /* 2AD1C 8003A51C 00FFA012 */  beqz       $s5, .L8003A120
    /* 2AD20 8003A520 80101300 */   sll       $v0, $s3, 2
  .L8003A524:
    /* 2AD24 8003A524 02004426 */  addiu      $a0, $s2, 0x2
  .L8003A528:
    /* 2AD28 8003A528 0680063C */  lui        $a2, %hi(D_8006718C)
    /* 2AD2C 8003A52C 8C71C624 */  addiu      $a2, $a2, %lo(D_8006718C)
    /* 2AD30 8003A530 8530010C */  jal        func_8004C214
    /* 2AD34 8003A534 01000524 */   addiu     $a1, $zero, 0x1
  .L8003A538:
    /* 2AD38 8003A538 3800BF8F */  lw         $ra, 0x38($sp)
    /* 2AD3C 8003A53C 3400B78F */  lw         $s7, 0x34($sp)
    /* 2AD40 8003A540 3000B68F */  lw         $s6, 0x30($sp)
    /* 2AD44 8003A544 2C00B58F */  lw         $s5, 0x2C($sp)
    /* 2AD48 8003A548 2800B48F */  lw         $s4, 0x28($sp)
    /* 2AD4C 8003A54C 2400B38F */  lw         $s3, 0x24($sp)
    /* 2AD50 8003A550 2000B28F */  lw         $s2, 0x20($sp)
    /* 2AD54 8003A554 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 2AD58 8003A558 1800B08F */  lw         $s0, 0x18($sp)
    /* 2AD5C 8003A55C 4000BD27 */  addiu      $sp, $sp, 0x40
    /* 2AD60 8003A560 0800E003 */  jr         $ra
    /* 2AD64 8003A564 00000000 */   nop
endlabel func_8003A0D8
