.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_26_8006D4D8

dlabel jtbl_level_26_8006D4D8
    /* 1DB0274 8006D4D8 40EA0680 */ .word .Llevel_26_8006EA40
    /* 1DB0278 8006D4DC C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB027C 8006D4E0 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0280 8006D4E4 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0284 8006D4E8 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0288 8006D4EC C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB028C 8006D4F0 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0290 8006D4F4 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0294 8006D4F8 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0298 8006D4FC C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB029C 8006D500 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02A0 8006D504 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02A4 8006D508 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02A8 8006D50C C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02AC 8006D510 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02B0 8006D514 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02B4 8006D518 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02B8 8006D51C C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02BC 8006D520 CCEB0680 */ .word .Llevel_26_8006EBCC
    /* 1DB02C0 8006D524 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02C4 8006D528 4CEC0680 */ .word .Llevel_26_8006EC4C
    /* 1DB02C8 8006D52C C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02CC 8006D530 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02D0 8006D534 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02D4 8006D538 E0EC0680 */ .word .Llevel_26_8006ECE0
    /* 1DB02D8 8006D53C 34ED0680 */ .word .Llevel_26_8006ED34
    /* 1DB02DC 8006D540 34ED0680 */ .word .Llevel_26_8006ED34
    /* 1DB02E0 8006D544 34ED0680 */ .word .Llevel_26_8006ED34
    /* 1DB02E4 8006D548 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02E8 8006D54C C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02EC 8006D550 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02F0 8006D554 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02F4 8006D558 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02F8 8006D55C C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB02FC 8006D560 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0300 8006D564 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0304 8006D568 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0308 8006D56C C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB030C 8006D570 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0310 8006D574 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0314 8006D578 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0318 8006D57C C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB031C 8006D580 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0320 8006D584 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0324 8006D588 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0328 8006D58C C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB032C 8006D590 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0330 8006D594 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0334 8006D598 C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB0338 8006D59C C8ED0680 */ .word .Llevel_26_8006EDC8
    /* 1DB033C 8006D5A0 E0EC0680 */ .word .Llevel_26_8006ECE0
    /* 1DB0340 8006D5A4 00000000 */ .word 0x00000000
enddlabel jtbl_level_26_8006D4D8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_26_8006EA04, 0x3DC

glabel func_level_26_8006EA04
    /* 1DB17A0 8006EA04 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 1DB17A4 8006EA08 1000B0AF */  sw         $s0, 0x10($sp)
    /* 1DB17A8 8006EA0C 21808000 */  addu       $s0, $a0, $zero
    /* 1DB17AC 8006EA10 F8FF0326 */  addiu      $v1, $s0, -0x8
    /* 1DB17B0 8006EA14 3300622C */  sltiu      $v0, $v1, 0x33
    /* 1DB17B4 8006EA18 1800BFAF */  sw         $ra, 0x18($sp)
    /* 1DB17B8 8006EA1C EA004010 */  beqz       $v0, .Llevel_26_8006EDC8
    /* 1DB17BC 8006EA20 1400B1AF */   sw        $s1, 0x14($sp)
    /* 1DB17C0 8006EA24 80100300 */  sll        $v0, $v1, 2
    /* 1DB17C4 8006EA28 0780013C */  lui        $at, %hi(jtbl_level_26_8006D4D8)
    /* 1DB17C8 8006EA2C 21082200 */  addu       $at, $at, $v0
    /* 1DB17CC 8006EA30 D8D4228C */  lw         $v0, %lo(jtbl_level_26_8006D4D8)($at)
    /* 1DB17D0 8006EA34 00000000 */  nop
    /* 1DB17D4 8006EA38 08004000 */  jr         $v0
    /* 1DB17D8 8006EA3C 00000000 */   nop
  .Llevel_26_8006EA40:
    /* 1DB17DC 8006EA40 0780113C */  lui        $s1, %hi(D_8006A104)
    /* 1DB17E0 8006EA44 04A13126 */  addiu      $s1, $s1, %lo(D_8006A104)
    /* 1DB17E4 8006EA48 0000248E */  lw         $a0, 0x0($s1)
    /* 1DB17E8 8006EA4C 1EAC000C */  jal        func_8002B078
    /* 1DB17EC 8006EA50 00000000 */   nop
    /* 1DB17F0 8006EA54 07000624 */  addiu      $a2, $zero, 0x7
    /* 1DB17F4 8006EA58 19004614 */  bne        $v0, $a2, .Llevel_26_8006EAC0
    /* 1DB17F8 8006EA5C 80FF2426 */   addiu     $a0, $s1, -0x80
    /* 1DB17FC 8006EA60 8CFF3026 */  addiu      $s0, $s1, -0x74
    /* 1DB1800 8006EA64 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 1DB1804 8006EA68 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* 1DB1808 8006EA6C 01000224 */  addiu      $v0, $zero, 0x1
    /* 1DB180C 8006EA70 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1DB1810 8006EA74 48A026AC */  sw         $a2, %lo(D_8006A048)($at)
    /* 1DB1814 8006EA78 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1DB1818 8006EA7C 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 1DB181C 8006EA80 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 1DB1820 8006EA84 3CA123AC */  sw         $v1, %lo(D_8006A13C)($at)
    /* 1DB1824 8006EA88 6C6F000C */  jal        func_8001BDB0
    /* 1DB1828 8006EA8C 21280002 */   addu      $a1, $s0, $zero
    /* 1DB182C 8006EA90 21200002 */  addu       $a0, $s0, $zero
    /* 1DB1830 8006EA94 886E000C */  jal        func_8001BA20
    /* 1DB1834 8006EA98 21280000 */   addu      $a1, $zero, $zero
    /* 1DB1838 8006EA9C 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1DB183C 8006EAA0 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 1DB1840 8006EAA4 C00D0224 */  addiu      $v0, $zero, 0xDC0
    /* 1DB1844 8006EAA8 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1DB1848 8006EAAC 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1DB184C 8006EAB0 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1DB1850 8006EAB4 ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 1DB1854 8006EAB8 E6BA0108 */  j          .Llevel_26_8006EB98
    /* 1DB1858 8006EABC 00000000 */   nop
  .Llevel_26_8006EAC0:
    /* 1DB185C 8006EAC0 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 1DB1860 8006EAC4 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* 1DB1864 8006EAC8 0780023C */  lui        $v0, %hi(D_8006A1FC)
    /* 1DB1868 8006EACC FCA1428C */  lw         $v0, %lo(D_8006A1FC)($v0)
    /* 1DB186C 8006EAD0 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1DB1870 8006EAD4 48A026AC */  sw         $a2, %lo(D_8006A048)($at)
    /* 1DB1874 8006EAD8 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1DB1878 8006EADC 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1DB187C 8006EAE0 00044230 */  andi       $v0, $v0, 0x400
    /* 1DB1880 8006EAE4 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 1DB1884 8006EAE8 3CA123AC */  sw         $v1, %lo(D_8006A13C)($at)
    /* 1DB1888 8006EAEC 09004010 */  beqz       $v0, .Llevel_26_8006EB14
    /* 1DB188C 8006EAF0 80FF3026 */   addiu     $s0, $s1, -0x80
    /* 1DB1890 8006EAF4 21200002 */  addu       $a0, $s0, $zero
    /* 1DB1894 8006EAF8 6C6F000C */  jal        func_8001BDB0
    /* 1DB1898 8006EAFC 08012526 */   addiu     $a1, $s1, 0x108
    /* 1DB189C 8006EB00 21200002 */  addu       $a0, $s0, $zero
    /* 1DB18A0 8006EB04 486F000C */  jal        func_8001BD20
    /* 1DB18A4 8006EB08 06000524 */   addiu     $a1, $zero, 0x6
    /* 1DB18A8 8006EB0C DDBA0108 */  j          .Llevel_26_8006EB74
    /* 1DB18AC 8006EB10 00000000 */   nop
  .Llevel_26_8006EB14:
    /* 1DB18B0 8006EB14 0780023C */  lui        $v0, %hi(D_8006A264)
    /* 1DB18B4 8006EB18 64A2428C */  lw         $v0, %lo(D_8006A264)($v0)
    /* 1DB18B8 8006EB1C 00000000 */  nop
    /* 1DB18BC 8006EB20 12004004 */  bltz       $v0, .Llevel_26_8006EB6C
    /* 1DB18C0 8006EB24 40100200 */   sll       $v0, $v0, 1
    /* 1DB18C4 8006EB28 0680013C */  lui        $at, %hi(D_80061C58)
    /* 1DB18C8 8006EB2C 21082200 */  addu       $at, $at, $v0
    /* 1DB18CC 8006EB30 581C2384 */  lh         $v1, %lo(D_80061C58)($at)
    /* 1DB18D0 8006EB34 00000000 */  nop
    /* 1DB18D4 8006EB38 43180300 */  sra        $v1, $v1, 1
    /* 1DB18D8 8006EB3C 0780013C */  lui        $at, %hi(D_8006A084)
    /* 1DB18DC 8006EB40 84A023AC */  sw         $v1, %lo(D_8006A084)($at)
    /* 1DB18E0 8006EB44 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 1DB18E4 8006EB48 21082200 */  addu       $at, $at, $v0
    /* 1DB18E8 8006EB4C D81B2284 */  lh         $v0, %lo(D_80061BD8)($at)
    /* 1DB18EC 8006EB50 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1DB18F0 8006EB54 8CA020AC */  sw         $zero, %lo(D_8006A08C)($at)
    /* 1DB18F4 8006EB58 43100200 */  sra        $v0, $v0, 1
    /* 1DB18F8 8006EB5C 0780013C */  lui        $at, %hi(D_8006A088)
    /* 1DB18FC 8006EB60 88A022AC */  sw         $v0, %lo(D_8006A088)($at)
    /* 1DB1900 8006EB64 DDBA0108 */  j          .Llevel_26_8006EB74
    /* 1DB1904 8006EB68 00000000 */   nop
  .Llevel_26_8006EB6C:
    /* 1DB1908 8006EB6C 686F000C */  jal        func_8001BDA0
    /* 1DB190C 8006EB70 80FF2426 */   addiu     $a0, $s1, -0x80
  .Llevel_26_8006EB74:
    /* 1DB1910 8006EB74 0780043C */  lui        $a0, %hi(D_8006A078)
    /* 1DB1914 8006EB78 78A08424 */  addiu      $a0, $a0, %lo(D_8006A078)
    /* 1DB1918 8006EB7C 6C6F000C */  jal        func_8001BDB0
    /* 1DB191C 8006EB80 0C008524 */   addiu     $a1, $a0, 0xC
    /* 1DB1920 8006EB84 C2B6000C */  jal        func_8002DB08
    /* 1DB1924 8006EB88 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 1DB1928 8006EB8C 01000224 */  addiu      $v0, $zero, 0x1
    /* 1DB192C 8006EB90 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1DB1930 8006EB94 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
  .Llevel_26_8006EB98:
    /* 1DB1934 8006EB98 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 1DB1938 8006EB9C FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 1DB193C 8006EBA0 2D000224 */  addiu      $v0, $zero, 0x2D
    /* 1DB1940 8006EBA4 0780013C */  lui        $at, %hi(D_80068390)
    /* 1DB1944 8006EBA8 908322AC */  sw         $v0, %lo(D_80068390)($at)
    /* 1DB1948 8006EBAC 86006010 */  beqz       $v1, .Llevel_26_8006EDC8
    /* 1DB194C 8006EBB0 05000424 */   addiu     $a0, $zero, 0x5
    /* 1DB1950 8006EBB4 0A000524 */  addiu      $a1, $zero, 0xA
    /* 1DB1954 8006EBB8 21300000 */  addu       $a2, $zero, $zero
    /* 1DB1958 8006EBBC 09F86000 */  jalr       $v1
    /* 1DB195C 8006EBC0 21380000 */   addu      $a3, $zero, $zero
    /* 1DB1960 8006EBC4 72BB0108 */  j          .Llevel_26_8006EDC8
    /* 1DB1964 8006EBC8 00000000 */   nop
  .Llevel_26_8006EBCC:
    /* 1DB1968 8006EBCC 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 1DB196C 8006EBD0 3CA16324 */  addiu      $v1, $v1, %lo(D_8006A13C)
    /* 1DB1970 8006EBD4 48FF6424 */  addiu      $a0, $v1, -0xB8
    /* 1DB1974 8006EBD8 0780053C */  lui        $a1, %hi(D_8006A048)
    /* 1DB1978 8006EBDC 48A0A58C */  lw         $a1, %lo(D_8006A048)($a1)
    /* 1DB197C 8006EBE0 07000224 */  addiu      $v0, $zero, 0x7
    /* 1DB1980 8006EBE4 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1DB1984 8006EBE8 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 1DB1988 8006EBEC 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1DB198C 8006EBF0 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1DB1990 8006EBF4 686F000C */  jal        func_8001BDA0
    /* 1DB1994 8006EBF8 000065AC */   sw        $a1, 0x0($v1)
    /* 1DB1998 8006EBFC 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 1DB199C 8006EC00 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 1DB19A0 8006EC04 01000224 */  addiu      $v0, $zero, 0x1
    /* 1DB19A4 8006EC08 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1DB19A8 8006EC0C ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 1DB19AC 8006EC10 0F000224 */  addiu      $v0, $zero, 0xF
    /* 1DB19B0 8006EC14 0780013C */  lui        $at, %hi(D_8006838C)
    /* 1DB19B4 8006EC18 8C8322AC */  sw         $v0, %lo(D_8006838C)($at)
    /* 1DB19B8 8006EC1C 05006010 */  beqz       $v1, .Llevel_26_8006EC34
    /* 1DB19BC 8006EC20 05000424 */   addiu     $a0, $zero, 0x5
    /* 1DB19C0 8006EC24 0A000524 */  addiu      $a1, $zero, 0xA
    /* 1DB19C4 8006EC28 21300000 */  addu       $a2, $zero, $zero
    /* 1DB19C8 8006EC2C 09F86000 */  jalr       $v1
    /* 1DB19CC 8006EC30 21380000 */   addu      $a3, $zero, $zero
  .Llevel_26_8006EC34:
    /* 1DB19D0 8006EC34 0680023C */  lui        $v0, %hi(D_80067020)
    /* 1DB19D4 8006EC38 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 1DB19D8 8006EC3C 00000000 */  nop
    /* 1DB19DC 8006EC40 09004490 */  lbu        $a0, 0x9($v0)
    /* 1DB19E0 8006EC44 49BB0108 */  j          .Llevel_26_8006ED24
    /* 1DB19E4 8006EC48 21280000 */   addu      $a1, $zero, $zero
  .Llevel_26_8006EC4C:
    /* 1DB19E8 8006EC4C 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 1DB19EC 8006EC50 3CA16324 */  addiu      $v1, $v1, %lo(D_8006A13C)
    /* 1DB19F0 8006EC54 48FF6424 */  addiu      $a0, $v1, -0xB8
    /* 1DB19F4 8006EC58 54FF7024 */  addiu      $s0, $v1, -0xAC
    /* 1DB19F8 8006EC5C 21280002 */  addu       $a1, $s0, $zero
    /* 1DB19FC 8006EC60 0780063C */  lui        $a2, %hi(D_8006A048)
    /* 1DB1A00 8006EC64 48A0C68C */  lw         $a2, %lo(D_8006A048)($a2)
    /* 1DB1A04 8006EC68 07000224 */  addiu      $v0, $zero, 0x7
    /* 1DB1A08 8006EC6C 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1DB1A0C 8006EC70 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 1DB1A10 8006EC74 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1DB1A14 8006EC78 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1DB1A18 8006EC7C 6C6F000C */  jal        func_8001BDB0
    /* 1DB1A1C 8006EC80 000066AC */   sw        $a2, 0x0($v1)
    /* 1DB1A20 8006EC84 21200002 */  addu       $a0, $s0, $zero
    /* 1DB1A24 8006EC88 886E000C */  jal        func_8001BA20
    /* 1DB1A28 8006EC8C 21280000 */   addu      $a1, $zero, $zero
    /* 1DB1A2C 8006EC90 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 1DB1A30 8006EC94 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 1DB1A34 8006EC98 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1DB1A38 8006EC9C A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 1DB1A3C 8006ECA0 C00D0224 */  addiu      $v0, $zero, 0xDC0
    /* 1DB1A40 8006ECA4 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1DB1A44 8006ECA8 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1DB1A48 8006ECAC 0F000224 */  addiu      $v0, $zero, 0xF
    /* 1DB1A4C 8006ECB0 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1DB1A50 8006ECB4 ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 1DB1A54 8006ECB8 0780013C */  lui        $at, %hi(D_8006838C)
    /* 1DB1A58 8006ECBC 8C8322AC */  sw         $v0, %lo(D_8006838C)($at)
    /* 1DB1A5C 8006ECC0 14006010 */  beqz       $v1, .Llevel_26_8006ED14
    /* 1DB1A60 8006ECC4 05000424 */   addiu     $a0, $zero, 0x5
    /* 1DB1A64 8006ECC8 0A000524 */  addiu      $a1, $zero, 0xA
    /* 1DB1A68 8006ECCC 21300000 */  addu       $a2, $zero, $zero
    /* 1DB1A6C 8006ECD0 09F86000 */  jalr       $v1
    /* 1DB1A70 8006ECD4 21380000 */   addu      $a3, $zero, $zero
    /* 1DB1A74 8006ECD8 45BB0108 */  j          .Llevel_26_8006ED14
    /* 1DB1A78 8006ECDC 00000000 */   nop
  .Llevel_26_8006ECE0:
    /* 1DB1A7C 8006ECE0 08000224 */  addiu      $v0, $zero, 0x8
    /* 1DB1A80 8006ECE4 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1DB1A84 8006ECE8 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 1DB1A88 8006ECEC 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1DB1A8C 8006ECF0 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1DB1A90 8006ECF4 C2B6000C */  jal        func_8002DB08
    /* 1DB1A94 8006ECF8 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 1DB1A98 8006ECFC 01000224 */  addiu      $v0, $zero, 0x1
    /* 1DB1A9C 8006ED00 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1DB1AA0 8006ED04 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 1DB1AA4 8006ED08 3A000224 */  addiu      $v0, $zero, 0x3A
    /* 1DB1AA8 8006ED0C 2E000216 */  bne        $s0, $v0, .Llevel_26_8006EDC8
    /* 1DB1AAC 8006ED10 00000000 */   nop
  .Llevel_26_8006ED14:
    /* 1DB1AB0 8006ED14 0680023C */  lui        $v0, %hi(D_80067020)
    /* 1DB1AB4 8006ED18 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 1DB1AB8 8006ED1C 21280000 */  addu       $a1, $zero, $zero
    /* 1DB1ABC 8006ED20 0C004490 */  lbu        $a0, 0xC($v0)
  .Llevel_26_8006ED24:
    /* 1DB1AC0 8006ED24 C841010C */  jal        func_80050720
    /* 1DB1AC4 8006ED28 21300000 */   addu      $a2, $zero, $zero
    /* 1DB1AC8 8006ED2C 72BB0108 */  j          .Llevel_26_8006EDC8
    /* 1DB1ACC 8006ED30 00000000 */   nop
  .Llevel_26_8006ED34:
    /* 1DB1AD0 8006ED34 0780103C */  lui        $s0, %hi(D_8006A048)
    /* 1DB1AD4 8006ED38 48A01026 */  addiu      $s0, $s0, %lo(D_8006A048)
    /* 1DB1AD8 8006ED3C 0000028E */  lw         $v0, 0x0($s0)
    /* 1DB1ADC 8006ED40 06000324 */  addiu      $v1, $zero, 0x6
    /* 1DB1AE0 8006ED44 20004310 */  beq        $v0, $v1, .Llevel_26_8006EDC8
    /* 1DB1AE4 8006ED48 00000000 */   nop
    /* 1DB1AE8 8006ED4C 000003AE */  sw         $v1, 0x0($s0)
    /* 1DB1AEC 8006ED50 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1DB1AF0 8006ED54 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1DB1AF4 8006ED58 686F000C */  jal        func_8001BDA0
    /* 1DB1AF8 8006ED5C FC000426 */   addiu     $a0, $s0, 0xFC
    /* 1DB1AFC 8006ED60 48000426 */  addiu      $a0, $s0, 0x48
    /* 1DB1B00 8006ED64 0780013C */  lui        $at, %hi(D_8006A150)
    /* 1DB1B04 8006ED68 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 1DB1B08 8006ED6C 886E000C */  jal        func_8001BA20
    /* 1DB1B0C 8006ED70 21280000 */   addu      $a1, $zero, $zero
    /* 1DB1B10 8006ED74 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1DB1B14 8006ED78 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 1DB1B18 8006ED7C 00084228 */  slti       $v0, $v0, 0x800
    /* 1DB1B1C 8006ED80 03004010 */  beqz       $v0, .Llevel_26_8006ED90
    /* 1DB1B20 8006ED84 00080224 */   addiu     $v0, $zero, 0x800
    /* 1DB1B24 8006ED88 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1DB1B28 8006ED8C A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_26_8006ED90:
    /* 1DB1B2C 8006ED90 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 1DB1B30 8006ED94 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 1DB1B34 8006ED98 00000000 */  nop
    /* 1DB1B38 8006ED9C 014B4228 */  slti       $v0, $v0, 0x4B01
    /* 1DB1B3C 8006EDA0 03004014 */  bnez       $v0, .Llevel_26_8006EDB0
    /* 1DB1B40 8006EDA4 004B0224 */   addiu     $v0, $zero, 0x4B00
    /* 1DB1B44 8006EDA8 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1DB1B48 8006EDAC A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_26_8006EDB0:
    /* 1DB1B4C 8006EDB0 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 1DB1B50 8006EDB4 3CA120AC */  sw         $zero, %lo(D_8006A13C)($at)
    /* 1DB1B54 8006EDB8 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1DB1B58 8006EDBC ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 1DB1B5C 8006EDC0 0780013C */  lui        $at, %hi(D_8006A1AD)
    /* 1DB1B60 8006EDC4 ADA120A0 */  sb         $zero, %lo(D_8006A1AD)($at)
  .Llevel_26_8006EDC8:
    /* 1DB1B64 8006EDC8 1800BF8F */  lw         $ra, 0x18($sp)
    /* 1DB1B68 8006EDCC 1400B18F */  lw         $s1, 0x14($sp)
    /* 1DB1B6C 8006EDD0 1000B08F */  lw         $s0, 0x10($sp)
    /* 1DB1B70 8006EDD4 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 1DB1B74 8006EDD8 0800E003 */  jr         $ra
    /* 1DB1B78 8006EDDC 00000000 */   nop
endlabel func_level_26_8006EA04
