.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_26_8006D268

dlabel jtbl_level_26_8006D268
    /* 1DB0004 8006D268 8CDA0680 */ .word .Llevel_26_8006DA8C
    /* 1DB0008 8006D26C F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB000C 8006D270 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0010 8006D274 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0014 8006D278 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0018 8006D27C F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB001C 8006D280 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0020 8006D284 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0024 8006D288 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0028 8006D28C F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB002C 8006D290 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0030 8006D294 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0034 8006D298 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0038 8006D29C F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB003C 8006D2A0 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0040 8006D2A4 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0044 8006D2A8 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0048 8006D2AC F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB004C 8006D2B0 60DC0680 */ .word .Llevel_26_8006DC60
    /* 1DB0050 8006D2B4 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0054 8006D2B8 D0DC0680 */ .word .Llevel_26_8006DCD0
    /* 1DB0058 8006D2BC F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB005C 8006D2C0 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0060 8006D2C4 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0064 8006D2C8 30DF0680 */ .word .Llevel_26_8006DF30
    /* 1DB0068 8006D2CC C4E00680 */ .word .Llevel_26_8006E0C4
    /* 1DB006C 8006D2D0 C4E00680 */ .word .Llevel_26_8006E0C4
    /* 1DB0070 8006D2D4 C4E00680 */ .word .Llevel_26_8006E0C4
    /* 1DB0074 8006D2D8 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0078 8006D2DC F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB007C 8006D2E0 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0080 8006D2E4 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0084 8006D2E8 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0088 8006D2EC F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB008C 8006D2F0 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0090 8006D2F4 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0094 8006D2F8 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB0098 8006D2FC F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB009C 8006D300 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00A0 8006D304 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00A4 8006D308 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00A8 8006D30C F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00AC 8006D310 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00B0 8006D314 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00B4 8006D318 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00B8 8006D31C F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00BC 8006D320 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00C0 8006D324 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00C4 8006D328 F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00C8 8006D32C F4E60680 */ .word .Llevel_26_8006E6F4
    /* 1DB00CC 8006D330 30DF0680 */ .word .Llevel_26_8006DF30
    /* 1DB00D0 8006D334 00000000 */ .word 0x00000000
enddlabel jtbl_level_26_8006D268


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_26_8006DA20, 0xCF4

glabel func_level_26_8006DA20
    /* 1DB07BC 8006DA20 00110400 */  sll        $v0, $a0, 4
    /* 1DB07C0 8006DA24 0780033C */  lui        $v1, %hi(D_800683B0)
    /* 1DB07C4 8006DA28 B0836324 */  addiu      $v1, $v1, %lo(D_800683B0)
    /* 1DB07C8 8006DA2C 21104300 */  addu       $v0, $v0, $v1
    /* 1DB07CC 8006DA30 0680013C */  lui        $at, %hi(D_80066F38)
    /* 1DB07D0 8006DA34 386F22AC */  sw         $v0, %lo(D_80066F38)($at)
    /* 1DB07D4 8006DA38 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 1DB07D8 8006DA3C 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 1DB07DC 8006DA40 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 1DB07E0 8006DA44 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 1DB07E4 8006DA48 78FFBD27 */  addiu      $sp, $sp, -0x88
    /* 1DB07E8 8006DA4C 8000BFAF */  sw         $ra, 0x80($sp)
    /* 1DB07EC 8006DA50 7C00B3AF */  sw         $s3, 0x7C($sp)
    /* 1DB07F0 8006DA54 7800B2AF */  sw         $s2, 0x78($sp)
    /* 1DB07F4 8006DA58 7400B1AF */  sw         $s1, 0x74($sp)
    /* 1DB07F8 8006DA5C 21904400 */  addu       $s2, $v0, $a0
    /* 1DB07FC 8006DA60 F8FF6324 */  addiu      $v1, $v1, -0x8
    /* 1DB0800 8006DA64 3300622C */  sltiu      $v0, $v1, 0x33
    /* 1DB0804 8006DA68 22034010 */  beqz       $v0, .Llevel_26_8006E6F4
    /* 1DB0808 8006DA6C 7000B0AF */   sw        $s0, 0x70($sp)
    /* 1DB080C 8006DA70 80100300 */  sll        $v0, $v1, 2
    /* 1DB0810 8006DA74 0780013C */  lui        $at, %hi(jtbl_level_26_8006D268)
    /* 1DB0814 8006DA78 21082200 */  addu       $at, $at, $v0
    /* 1DB0818 8006DA7C 68D2228C */  lw         $v0, %lo(jtbl_level_26_8006D268)($at)
    /* 1DB081C 8006DA80 00000000 */  nop
    /* 1DB0820 8006DA84 08004000 */  jr         $v0
    /* 1DB0824 8006DA88 00000000 */   nop
  .Llevel_26_8006DA8C:
    /* 1DB0828 8006DA8C 0780103C */  lui        $s0, %hi(D_8006A044)
    /* 1DB082C 8006DA90 44A01026 */  addiu      $s0, $s0, %lo(D_8006A044)
    /* 1DB0830 8006DA94 0000038E */  lw         $v1, 0x0($s0)
    /* 1DB0834 8006DA98 01000224 */  addiu      $v0, $zero, 0x1
    /* 1DB0838 8006DA9C 46006214 */  bne        $v1, $v0, .Llevel_26_8006DBB8
    /* 1DB083C 8006DAA0 1300422A */   slti      $v0, $s2, 0x13
    /* 1DB0840 8006DAA4 DBAC000C */  jal        func_8002B36C
    /* 1DB0844 8006DAA8 800C0424 */   addiu     $a0, $zero, 0xC80
    /* 1DB0848 8006DAAC 28000424 */  addiu      $a0, $zero, 0x28
    /* 1DB084C 8006DAB0 C9AE000C */  jal        func_8002BB24
    /* 1DB0850 8006DAB4 08000524 */   addiu     $a1, $zero, 0x8
    /* 1DB0854 8006DAB8 40010424 */  addiu      $a0, $zero, 0x140
    /* 1DB0858 8006DABC 5CAF000C */  jal        func_8002BD70
    /* 1DB085C 8006DAC0 C0000524 */   addiu     $a1, $zero, 0xC0
    /* 1DB0860 8006DAC4 0780043C */  lui        $a0, %hi(D_8006A09C)
    /* 1DB0864 8006DAC8 9CA0848C */  lw         $a0, %lo(D_8006A09C)($a0)
    /* 1DB0868 8006DACC 996D000C */  jal        func_8001B664
    /* 1DB086C 8006DAD0 40001126 */   addiu     $s1, $s0, 0x40
    /* 1DB0870 8006DAD4 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 1DB0874 8006DAD8 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 1DB0878 8006DADC 00000000 */  nop
    /* 1DB087C 8006DAE0 18006200 */  mult       $v1, $v0
    /* 1DB0880 8006DAE4 0780043C */  lui        $a0, %hi(D_8006A09C)
    /* 1DB0884 8006DAE8 9CA0848C */  lw         $a0, %lo(D_8006A09C)($a0)
    /* 1DB0888 8006DAEC 12480000 */  mflo       $t1
    /* 1DB088C 8006DAF0 03130900 */  sra        $v0, $t1, 12
    /* 1DB0890 8006DAF4 876D000C */  jal        func_8001B61C
    /* 1DB0894 8006DAF8 1000A2AF */   sw        $v0, 0x10($sp)
    /* 1DB0898 8006DAFC 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 1DB089C 8006DB00 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 1DB08A0 8006DB04 00000000 */  nop
    /* 1DB08A4 8006DB08 18006200 */  mult       $v1, $v0
    /* 1DB08A8 8006DB0C 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1DB08AC 8006DB10 21288000 */  addu       $a1, $a0, $zero
    /* 1DB08B0 8006DB14 21302002 */  addu       $a2, $s1, $zero
    /* 1DB08B4 8006DB18 12480000 */  mflo       $t1
    /* 1DB08B8 8006DB1C 03130900 */  sra        $v0, $t1, 12
    /* 1DB08BC 8006DB20 806F000C */  jal        func_8001BE00
    /* 1DB08C0 8006DB24 1400A2AF */   sw        $v0, 0x14($sp)
    /* 1DB08C4 8006DB28 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1DB08C8 8006DB2C 21280000 */  addu       $a1, $zero, $zero
    /* 1DB08CC 8006DB30 886E000C */  jal        func_8001BA20
    /* 1DB08D0 8006DB34 1800A0AF */   sw        $zero, 0x18($sp)
    /* 1DB08D4 8006DB38 21284000 */  addu       $a1, $v0, $zero
    /* 1DB08D8 8006DB3C 8102A228 */  slti       $v0, $a1, 0x281
    /* 1DB08DC 8006DB40 05004014 */  bnez       $v0, .Llevel_26_8006DB58
    /* 1DB08E0 8006DB44 34000426 */   addiu     $a0, $s0, 0x34
    /* 1DB08E4 8006DB48 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1DB08E8 8006DB4C 316F000C */  jal        func_8001BCC4
    /* 1DB08EC 8006DB50 80020624 */   addiu     $a2, $zero, 0x280
    /* 1DB08F0 8006DB54 34000426 */  addiu      $a0, $s0, 0x34
  .Llevel_26_8006DB58:
    /* 1DB08F4 8006DB58 21282002 */  addu       $a1, $s1, $zero
    /* 1DB08F8 8006DB5C 736F000C */  jal        func_8001BDCC
    /* 1DB08FC 8006DB60 1000A627 */   addiu     $a2, $sp, 0x10
    /* 1DB0900 8006DB64 0EB0000C */  jal        func_8002C038
    /* 1DB0904 8006DB68 00000000 */   nop
    /* 1DB0908 8006DB6C 0D00422A */  slti       $v0, $s2, 0xD
    /* 1DB090C 8006DB70 09004010 */  beqz       $v0, .Llevel_26_8006DB98
    /* 1DB0910 8006DB74 00000000 */   nop
    /* 1DB0914 8006DB78 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 1DB0918 8006DB7C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 1DB091C 8006DB80 00000000 */  nop
    /* 1DB0920 8006DB84 17004224 */  addiu      $v0, $v0, 0x17
    /* 1DB0924 8006DB88 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1DB0928 8006DB8C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1DB092C 8006DB90 BDB90108 */  j          .Llevel_26_8006E6F4
    /* 1DB0930 8006DB94 00000000 */   nop
  .Llevel_26_8006DB98:
    /* 1DB0934 8006DB98 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 1DB0938 8006DB9C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 1DB093C 8006DBA0 00000000 */  nop
    /* 1DB0940 8006DBA4 40FF4224 */  addiu      $v0, $v0, -0xC0
    /* 1DB0944 8006DBA8 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1DB0948 8006DBAC 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1DB094C 8006DBB0 BDB90108 */  j          .Llevel_26_8006E6F4
    /* 1DB0950 8006DBB4 00000000 */   nop
  .Llevel_26_8006DBB8:
    /* 1DB0954 8006DBB8 1A004014 */  bnez       $v0, .Llevel_26_8006DC24
    /* 1DB0958 8006DBBC 40000426 */   addiu     $a0, $s0, 0x40
    /* 1DB095C 8006DBC0 34000426 */  addiu      $a0, $s0, 0x34
    /* 1DB0960 8006DBC4 0780033C */  lui        $v1, %hi(D_8006A084)
    /* 1DB0964 8006DBC8 84A0638C */  lw         $v1, %lo(D_8006A084)($v1)
    /* 1DB0968 8006DBCC 00000000 */  nop
    /* 1DB096C 8006DBD0 C0100300 */  sll        $v0, $v1, 3
    /* 1DB0970 8006DBD4 23104300 */  subu       $v0, $v0, $v1
    /* 1DB0974 8006DBD8 0780033C */  lui        $v1, %hi(D_8006A088)
    /* 1DB0978 8006DBDC 88A0638C */  lw         $v1, %lo(D_8006A088)($v1)
    /* 1DB097C 8006DBE0 40110200 */  sll        $v0, $v0, 5
    /* 1DB0980 8006DBE4 340002AE */  sw         $v0, 0x34($s0)
    /* 1DB0984 8006DBE8 C0100300 */  sll        $v0, $v1, 3
    /* 1DB0988 8006DBEC 23104300 */  subu       $v0, $v0, $v1
    /* 1DB098C 8006DBF0 0780033C */  lui        $v1, %hi(D_8006A08C)
    /* 1DB0990 8006DBF4 8CA0638C */  lw         $v1, %lo(D_8006A08C)($v1)
    /* 1DB0994 8006DBF8 40110200 */  sll        $v0, $v0, 5
    /* 1DB0998 8006DBFC 0780013C */  lui        $at, %hi(D_8006A07C)
    /* 1DB099C 8006DC00 7CA022AC */  sw         $v0, %lo(D_8006A07C)($at)
    /* 1DB09A0 8006DC04 C0100300 */  sll        $v0, $v1, 3
    /* 1DB09A4 8006DC08 23104300 */  subu       $v0, $v0, $v1
    /* 1DB09A8 8006DC0C 40110200 */  sll        $v0, $v0, 5
    /* 1DB09AC 8006DC10 0780013C */  lui        $at, %hi(D_8006A080)
    /* 1DB09B0 8006DC14 80A022AC */  sw         $v0, %lo(D_8006A080)($at)
    /* 1DB09B4 8006DC18 526F000C */  jal        func_8001BD48
    /* 1DB09B8 8006DC1C 08000524 */   addiu     $a1, $zero, 0x8
    /* 1DB09BC 8006DC20 40000426 */  addiu      $a0, $s0, 0x40
  .Llevel_26_8006DC24:
    /* 1DB09C0 8006DC24 6C6F000C */  jal        func_8001BDB0
    /* 1DB09C4 8006DC28 34000526 */   addiu     $a1, $s0, 0x34
    /* 1DB09C8 8006DC2C 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 1DB09CC 8006DC30 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 1DB09D0 8006DC34 00000000 */  nop
    /* 1DB09D4 8006DC38 40FF4224 */  addiu      $v0, $v0, -0xC0
    /* 1DB09D8 8006DC3C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1DB09DC 8006DC40 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1DB09E0 8006DC44 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 1DB09E4 8006DC48 AA024010 */  beqz       $v0, .Llevel_26_8006E6F4
    /* 1DB09E8 8006DC4C 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 1DB09EC 8006DC50 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1DB09F0 8006DC54 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1DB09F4 8006DC58 BDB90108 */  j          .Llevel_26_8006E6F4
    /* 1DB09F8 8006DC5C 00000000 */   nop
  .Llevel_26_8006DC60:
    /* 1DB09FC 8006DC60 0780103C */  lui        $s0, %hi(D_8006A0B0)
    /* 1DB0A00 8006DC64 B0A01026 */  addiu      $s0, $s0, %lo(D_8006A0B0)
    /* 1DB0A04 8006DC68 0000028E */  lw         $v0, 0x0($s0)
    /* 1DB0A08 8006DC6C 00000000 */  nop
    /* 1DB0A0C 8006DC70 11004010 */  beqz       $v0, .Llevel_26_8006DCB8
    /* 1DB0A10 8006DC74 00000000 */   nop
    /* 1DB0A14 8006DC78 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 1DB0A18 8006DC7C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 1DB0A1C 8006DC80 00000000 */  nop
    /* 1DB0A20 8006DC84 00FA4224 */  addiu      $v0, $v0, -0x600
    /* 1DB0A24 8006DC88 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1DB0A28 8006DC8C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1DB0A2C 8006DC90 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 1DB0A30 8006DC94 03004010 */  beqz       $v0, .Llevel_26_8006DCA4
    /* 1DB0A34 8006DC98 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 1DB0A38 8006DC9C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1DB0A3C 8006DCA0 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_26_8006DCA4:
    /* 1DB0A40 8006DCA4 C8FF0426 */  addiu      $a0, $s0, -0x38
    /* 1DB0A44 8006DCA8 6C6F000C */  jal        func_8001BDB0
    /* 1DB0A48 8006DCAC D4FF0526 */   addiu     $a1, $s0, -0x2C
    /* 1DB0A4C 8006DCB0 BDB90108 */  j          .Llevel_26_8006E6F4
    /* 1DB0A50 8006DCB4 00000000 */   nop
  .Llevel_26_8006DCB8:
    /* 1DB0A54 8006DCB8 686F000C */  jal        func_8001BDA0
    /* 1DB0A58 8006DCBC C8FF0426 */   addiu     $a0, $s0, -0x38
    /* 1DB0A5C 8006DCC0 686F000C */  jal        func_8001BDA0
    /* 1DB0A60 8006DCC4 D4FF0426 */   addiu     $a0, $s0, -0x2C
    /* 1DB0A64 8006DCC8 BDB90108 */  j          .Llevel_26_8006E6F4
    /* 1DB0A68 8006DCCC 00000000 */   nop
  .Llevel_26_8006DCD0:
    /* 1DB0A6C 8006DCD0 DBAC000C */  jal        func_8002B36C
    /* 1DB0A70 8006DCD4 800C0424 */   addiu     $a0, $zero, 0xC80
    /* 1DB0A74 8006DCD8 28000424 */  addiu      $a0, $zero, 0x28
    /* 1DB0A78 8006DCDC C9AE000C */  jal        func_8002BB24
    /* 1DB0A7C 8006DCE0 08000524 */   addiu     $a1, $zero, 0x8
    /* 1DB0A80 8006DCE4 40010424 */  addiu      $a0, $zero, 0x140
    /* 1DB0A84 8006DCE8 5CAF000C */  jal        func_8002BD70
    /* 1DB0A88 8006DCEC C0000524 */   addiu     $a1, $zero, 0xC0
    /* 1DB0A8C 8006DCF0 0780113C */  lui        $s1, %hi(D_8006A09C)
    /* 1DB0A90 8006DCF4 9CA03126 */  addiu      $s1, $s1, %lo(D_8006A09C)
    /* 1DB0A94 8006DCF8 0000248E */  lw         $a0, 0x0($s1)
    /* 1DB0A98 8006DCFC 996D000C */  jal        func_8001B664
    /* 1DB0A9C 8006DD00 E8FF3326 */   addiu     $s3, $s1, -0x18
    /* 1DB0AA0 8006DD04 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 1DB0AA4 8006DD08 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 1DB0AA8 8006DD0C 00000000 */  nop
    /* 1DB0AAC 8006DD10 18006200 */  mult       $v1, $v0
    /* 1DB0AB0 8006DD14 0000248E */  lw         $a0, 0x0($s1)
    /* 1DB0AB4 8006DD18 12480000 */  mflo       $t1
    /* 1DB0AB8 8006DD1C 03130900 */  sra        $v0, $t1, 12
    /* 1DB0ABC 8006DD20 876D000C */  jal        func_8001B61C
    /* 1DB0AC0 8006DD24 2000A2AF */   sw        $v0, 0x20($sp)
    /* 1DB0AC4 8006DD28 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 1DB0AC8 8006DD2C A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 1DB0ACC 8006DD30 00000000 */  nop
    /* 1DB0AD0 8006DD34 18006200 */  mult       $v1, $v0
    /* 1DB0AD4 8006DD38 2000B027 */  addiu      $s0, $sp, 0x20
    /* 1DB0AD8 8006DD3C 21200002 */  addu       $a0, $s0, $zero
    /* 1DB0ADC 8006DD40 21280002 */  addu       $a1, $s0, $zero
    /* 1DB0AE0 8006DD44 21306002 */  addu       $a2, $s3, $zero
    /* 1DB0AE4 8006DD48 12480000 */  mflo       $t1
    /* 1DB0AE8 8006DD4C 03130900 */  sra        $v0, $t1, 12
    /* 1DB0AEC 8006DD50 806F000C */  jal        func_8001BE00
    /* 1DB0AF0 8006DD54 2400A2AF */   sw        $v0, 0x24($sp)
    /* 1DB0AF4 8006DD58 21200002 */  addu       $a0, $s0, $zero
    /* 1DB0AF8 8006DD5C 21280000 */  addu       $a1, $zero, $zero
    /* 1DB0AFC 8006DD60 886E000C */  jal        func_8001BA20
    /* 1DB0B00 8006DD64 2800A0AF */   sw        $zero, 0x28($sp)
    /* 1DB0B04 8006DD68 21284000 */  addu       $a1, $v0, $zero
    /* 1DB0B08 8006DD6C 8102A228 */  slti       $v0, $a1, 0x281
    /* 1DB0B0C 8006DD70 05004014 */  bnez       $v0, .Llevel_26_8006DD88
    /* 1DB0B10 8006DD74 DCFF2426 */   addiu     $a0, $s1, -0x24
    /* 1DB0B14 8006DD78 21200002 */  addu       $a0, $s0, $zero
    /* 1DB0B18 8006DD7C 316F000C */  jal        func_8001BCC4
    /* 1DB0B1C 8006DD80 80020624 */   addiu     $a2, $zero, 0x280
    /* 1DB0B20 8006DD84 DCFF2426 */  addiu      $a0, $s1, -0x24
  .Llevel_26_8006DD88:
    /* 1DB0B24 8006DD88 21286002 */  addu       $a1, $s3, $zero
    /* 1DB0B28 8006DD8C 736F000C */  jal        func_8001BDCC
    /* 1DB0B2C 8006DD90 21300002 */   addu      $a2, $s0, $zero
    /* 1DB0B30 8006DD94 0EB0000C */  jal        func_8002C038
    /* 1DB0B34 8006DD98 00000000 */   nop
    /* 1DB0B38 8006DD9C 0D00422A */  slti       $v0, $s2, 0xD
    /* 1DB0B3C 8006DDA0 05004010 */  beqz       $v0, .Llevel_26_8006DDB8
    /* 1DB0B40 8006DDA4 00000000 */   nop
    /* 1DB0B44 8006DDA8 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 1DB0B48 8006DDAC 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 1DB0B4C 8006DDB0 72B70108 */  j          .Llevel_26_8006DDC8
    /* 1DB0B50 8006DDB4 17004224 */   addiu     $v0, $v0, 0x17
  .Llevel_26_8006DDB8:
    /* 1DB0B54 8006DDB8 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 1DB0B58 8006DDBC 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 1DB0B5C 8006DDC0 00000000 */  nop
    /* 1DB0B60 8006DDC4 40FF4224 */  addiu      $v0, $v0, -0xC0
  .Llevel_26_8006DDC8:
    /* 1DB0B64 8006DDC8 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1DB0B68 8006DDCC 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1DB0B6C 8006DDD0 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 1DB0B70 8006DDD4 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 1DB0B74 8006DDD8 00000000 */  nop
    /* 1DB0B78 8006DDDC 45024010 */  beqz       $v0, .Llevel_26_8006E6F4
    /* 1DB0B7C 8006DDE0 21880000 */   addu      $s1, $zero, $zero
    /* 1DB0B80 8006DDE4 80101200 */  sll        $v0, $s2, 2
    /* 1DB0B84 8006DDE8 21985200 */  addu       $s3, $v0, $s2
    /* 1DB0B88 8006DDEC 0780123C */  lui        $s2, %hi(D_80069FFE)
    /* 1DB0B8C 8006DDF0 FE9F5226 */  addiu      $s2, $s2, %lo(D_80069FFE)
    /* 1DB0B90 8006DDF4 4000B027 */  addiu      $s0, $sp, 0x40
  .Llevel_26_8006DDF8:
    /* 1DB0B94 8006DDF8 4B67010C */  jal        func_80059D2C
    /* 1DB0B98 8006DDFC 00000000 */   nop
    /* 1DB0B9C 8006DE00 FF004230 */  andi       $v0, $v0, 0xFF
    /* 1DB0BA0 8006DE04 2A106202 */  slt        $v0, $s3, $v0
    /* 1DB0BA4 8006DE08 43004010 */  beqz       $v0, .Llevel_26_8006DF18
    /* 1DB0BA8 8006DE0C 21200000 */   addu      $a0, $zero, $zero
    /* 1DB0BAC 8006DE10 63E2000C */  jal        func_8003898C
    /* 1DB0BB0 8006DE14 0C000524 */   addiu     $a1, $zero, 0xC
    /* 1DB0BB4 8006DE18 22004426 */  addiu      $a0, $s2, 0x22
    /* 1DB0BB8 8006DE1C 00004392 */  lbu        $v1, 0x0($s2)
    /* 1DB0BBC 8006DE20 21280002 */  addu       $a1, $s0, $zero
    /* 1DB0BC0 8006DE24 80006324 */  addiu      $v1, $v1, 0x80
    /* 1DB0BC4 8006DE28 21186200 */  addu       $v1, $v1, $v0
    /* 1DB0BC8 8006DE2C FF006330 */  andi       $v1, $v1, 0xFF
    /* 1DB0BCC 8006DE30 40180300 */  sll        $v1, $v1, 1
    /* 1DB0BD0 8006DE34 0680013C */  lui        $at, %hi(D_80061C58)
    /* 1DB0BD4 8006DE38 21082300 */  addu       $at, $at, $v1
    /* 1DB0BD8 8006DE3C 581C2784 */  lh         $a3, %lo(D_80061C58)($at)
    /* 1DB0BDC 8006DE40 21300002 */  addu       $a2, $s0, $zero
    /* 1DB0BE0 8006DE44 80100700 */  sll        $v0, $a3, 2
    /* 1DB0BE4 8006DE48 21104700 */  addu       $v0, $v0, $a3
    /* 1DB0BE8 8006DE4C 83120200 */  sra        $v0, $v0, 10
    /* 1DB0BEC 8006DE50 3000A2AF */  sw         $v0, 0x30($sp)
    /* 1DB0BF0 8006DE54 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 1DB0BF4 8006DE58 21082300 */  addu       $at, $at, $v1
    /* 1DB0BF8 8006DE5C D81B2384 */  lh         $v1, %lo(D_80061BD8)($at)
    /* 1DB0BFC 8006DE60 0E000224 */  addiu      $v0, $zero, 0xE
    /* 1DB0C00 8006DE64 3800A2AF */  sw         $v0, 0x38($sp)
    /* 1DB0C04 8006DE68 D4FE0224 */  addiu      $v0, $zero, -0x12C
    /* 1DB0C08 8006DE6C 4000A2AF */  sw         $v0, 0x40($sp)
    /* 1DB0C0C 8006DE70 38FF0224 */  addiu      $v0, $zero, -0xC8
    /* 1DB0C10 8006DE74 4400A0AF */  sw         $zero, 0x44($sp)
    /* 1DB0C14 8006DE78 4800A2AF */  sw         $v0, 0x48($sp)
    /* 1DB0C18 8006DE7C 80100300 */  sll        $v0, $v1, 2
    /* 1DB0C1C 8006DE80 21104300 */  addu       $v0, $v0, $v1
    /* 1DB0C20 8006DE84 83120200 */  sra        $v0, $v0, 10
    /* 1DB0C24 8006DE88 696E000C */  jal        func_8001B9A4
    /* 1DB0C28 8006DE8C 3400A2AF */   sw        $v0, 0x34($sp)
    /* 1DB0C2C 8006DE90 21200000 */  addu       $a0, $zero, $zero
    /* 1DB0C30 8006DE94 63E2000C */  jal        func_8003898C
    /* 1DB0C34 8006DE98 50000524 */   addiu     $a1, $zero, 0x50
    /* 1DB0C38 8006DE9C 21200000 */  addu       $a0, $zero, $zero
    /* 1DB0C3C 8006DEA0 4000A38F */  lw         $v1, 0x40($sp)
    /* 1DB0C40 8006DEA4 50000524 */  addiu      $a1, $zero, 0x50
    /* 1DB0C44 8006DEA8 21186200 */  addu       $v1, $v1, $v0
    /* 1DB0C48 8006DEAC 63E2000C */  jal        func_8003898C
    /* 1DB0C4C 8006DEB0 4000A3AF */   sw        $v1, 0x40($sp)
    /* 1DB0C50 8006DEB4 21200000 */  addu       $a0, $zero, $zero
    /* 1DB0C54 8006DEB8 4400A38F */  lw         $v1, 0x44($sp)
    /* 1DB0C58 8006DEBC 50000524 */  addiu      $a1, $zero, 0x50
    /* 1DB0C5C 8006DEC0 21186200 */  addu       $v1, $v1, $v0
    /* 1DB0C60 8006DEC4 63E2000C */  jal        func_8003898C
    /* 1DB0C64 8006DEC8 4400A3AF */   sw        $v1, 0x44($sp)
    /* 1DB0C68 8006DECC 21200002 */  addu       $a0, $s0, $zero
    /* 1DB0C6C 8006DED0 21280002 */  addu       $a1, $s0, $zero
    /* 1DB0C70 8006DED4 4800A38F */  lw         $v1, 0x48($sp)
    /* 1DB0C74 8006DED8 F2FF4626 */  addiu      $a2, $s2, -0xE
    /* 1DB0C78 8006DEDC 21186200 */  addu       $v1, $v1, $v0
    /* 1DB0C7C 8006DEE0 736F000C */  jal        func_8001BDCC
    /* 1DB0C80 8006DEE4 4800A3AF */   sw        $v1, 0x48($sp)
    /* 1DB0C84 8006DEE8 01000424 */  addiu      $a0, $zero, 0x1
    /* 1DB0C88 8006DEEC 0D000524 */  addiu      $a1, $zero, 0xD
    /* 1DB0C8C 8006DEF0 21300002 */  addu       $a2, $s0, $zero
    /* 1DB0C90 8006DEF4 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 1DB0C94 8006DEF8 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 1DB0C98 8006DEFC 00000000 */  nop
    /* 1DB0C9C 8006DF00 09F84000 */  jalr       $v0
    /* 1DB0CA0 8006DF04 3000A727 */   addiu     $a3, $sp, 0x30
    /* 1DB0CA4 8006DF08 08000324 */  addiu      $v1, $zero, 0x8
    /* 1DB0CA8 8006DF0C 020043A0 */  sb         $v1, 0x2($v0)
    /* 1DB0CAC 8006DF10 20000324 */  addiu      $v1, $zero, 0x20
    /* 1DB0CB0 8006DF14 0A0043A0 */  sb         $v1, 0xA($v0)
  .Llevel_26_8006DF18:
    /* 1DB0CB4 8006DF18 01003126 */  addiu      $s1, $s1, 0x1
    /* 1DB0CB8 8006DF1C 0200222A */  slti       $v0, $s1, 0x2
    /* 1DB0CBC 8006DF20 F4014010 */  beqz       $v0, .Llevel_26_8006E6F4
    /* 1DB0CC0 8006DF24 00000000 */   nop
    /* 1DB0CC4 8006DF28 7EB70108 */  j          .Llevel_26_8006DDF8
    /* 1DB0CC8 8006DF2C 00000000 */   nop
  .Llevel_26_8006DF30:
    /* 1DB0CCC 8006DF30 0780103C */  lui        $s0, %hi(D_8006A0B0)
    /* 1DB0CD0 8006DF34 B0A01026 */  addiu      $s0, $s0, %lo(D_8006A0B0)
    /* 1DB0CD4 8006DF38 0000028E */  lw         $v0, 0x0($s0)
    /* 1DB0CD8 8006DF3C 00000000 */  nop
    /* 1DB0CDC 8006DF40 1F004010 */  beqz       $v0, .Llevel_26_8006DFC0
    /* 1DB0CE0 8006DF44 3000B127 */   addiu     $s1, $sp, 0x30
    /* 1DB0CE4 8006DF48 686F000C */  jal        func_8001BDA0
    /* 1DB0CE8 8006DF4C 21202002 */   addu      $a0, $s1, $zero
    /* 1DB0CEC 8006DF50 21202002 */  addu       $a0, $s1, $zero
    /* 1DB0CF0 8006DF54 21282002 */  addu       $a1, $s1, $zero
    /* 1DB0CF4 8006DF58 D4FF1226 */  addiu      $s2, $s0, -0x2C
    /* 1DB0CF8 8006DF5C 806F000C */  jal        func_8001BE00
    /* 1DB0CFC 8006DF60 21304002 */   addu      $a2, $s2, $zero
    /* 1DB0D00 8006DF64 3800A0AF */  sw         $zero, 0x38($sp)
    /* 1DB0D04 8006DF68 21202002 */  addu       $a0, $s1, $zero
    /* 1DB0D08 8006DF6C 886E000C */  jal        func_8001BA20
    /* 1DB0D0C 8006DF70 21280000 */   addu      $a1, $zero, $zero
    /* 1DB0D10 8006DF74 21284000 */  addu       $a1, $v0, $zero
    /* 1DB0D14 8006DF78 4100A228 */  slti       $v0, $a1, 0x41
    /* 1DB0D18 8006DF7C 05004014 */  bnez       $v0, .Llevel_26_8006DF94
    /* 1DB0D1C 8006DF80 40FF0224 */   addiu     $v0, $zero, -0xC0
    /* 1DB0D20 8006DF84 21202002 */  addu       $a0, $s1, $zero
    /* 1DB0D24 8006DF88 316F000C */  jal        func_8001BCC4
    /* 1DB0D28 8006DF8C 40000624 */   addiu     $a2, $zero, 0x40
    /* 1DB0D2C 8006DF90 40FF0224 */  addiu      $v0, $zero, -0xC0
  .Llevel_26_8006DF94:
    /* 1DB0D30 8006DF94 3800A2AF */  sw         $v0, 0x38($sp)
    /* 1DB0D34 8006DF98 C8FF1026 */  addiu      $s0, $s0, -0x38
    /* 1DB0D38 8006DF9C 21200002 */  addu       $a0, $s0, $zero
    /* 1DB0D3C 8006DFA0 21284002 */  addu       $a1, $s2, $zero
    /* 1DB0D40 8006DFA4 736F000C */  jal        func_8001BDCC
    /* 1DB0D44 8006DFA8 21302002 */   addu      $a2, $s1, $zero
    /* 1DB0D48 8006DFAC 21204002 */  addu       $a0, $s2, $zero
    /* 1DB0D4C 8006DFB0 6C6F000C */  jal        func_8001BDB0
    /* 1DB0D50 8006DFB4 21280002 */   addu      $a1, $s0, $zero
    /* 1DB0D54 8006DFB8 F4B70108 */  j          .Llevel_26_8006DFD0
    /* 1DB0D58 8006DFBC 00000000 */   nop
  .Llevel_26_8006DFC0:
    /* 1DB0D5C 8006DFC0 686F000C */  jal        func_8001BDA0
    /* 1DB0D60 8006DFC4 C8FF0426 */   addiu     $a0, $s0, -0x38
    /* 1DB0D64 8006DFC8 686F000C */  jal        func_8001BDA0
    /* 1DB0D68 8006DFCC D4FF0426 */   addiu     $a0, $s0, -0x2C
  .Llevel_26_8006DFD0:
    /* 1DB0D6C 8006DFD0 0780053C */  lui        $a1, %hi(D_8006A08C)
    /* 1DB0D70 8006DFD4 8CA0A524 */  addiu      $a1, $a1, %lo(D_8006A08C)
    /* 1DB0D74 8006DFD8 0000A28C */  lw         $v0, 0x0($a1)
    /* 1DB0D78 8006DFDC 00000000 */  nop
    /* 1DB0D7C 8006DFE0 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 1DB0D80 8006DFE4 02004010 */  beqz       $v0, .Llevel_26_8006DFF0
    /* 1DB0D84 8006DFE8 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 1DB0D88 8006DFEC 0000A2AC */  sw         $v0, 0x0($a1)
  .Llevel_26_8006DFF0:
    /* 1DB0D8C 8006DFF0 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 1DB0D90 8006DFF4 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 1DB0D94 8006DFF8 3A000224 */  addiu      $v0, $zero, 0x3A
    /* 1DB0D98 8006DFFC BD016214 */  bne        $v1, $v0, .Llevel_26_8006E6F4
    /* 1DB0D9C 8006E000 00000000 */   nop
    /* 1DB0DA0 8006E004 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 1DB0DA4 8006E008 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 1DB0DA8 8006E00C 00000000 */  nop
    /* 1DB0DAC 8006E010 B8014010 */  beqz       $v0, .Llevel_26_8006E6F4
    /* 1DB0DB0 8006E014 00000000 */   nop
    /* 1DB0DB4 8006E018 0680023C */  lui        $v0, %hi(D_80067008)
    /* 1DB0DB8 8006E01C 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 1DB0DBC 8006E020 00000000 */  nop
    /* 1DB0DC0 8006E024 01004230 */  andi       $v0, $v0, 0x1
    /* 1DB0DC4 8006E028 B2014010 */  beqz       $v0, .Llevel_26_8006E6F4
    /* 1DB0DC8 8006E02C 6000B027 */   addiu     $s0, $sp, 0x60
    /* 1DB0DCC 8006E030 21200002 */  addu       $a0, $s0, $zero
    /* 1DB0DD0 8006E034 64FFA524 */  addiu      $a1, $a1, -0x9C
    /* 1DB0DD4 8006E038 0E000224 */  addiu      $v0, $zero, 0xE
    /* 1DB0DD8 8006E03C 5000A0AF */  sw         $zero, 0x50($sp)
    /* 1DB0DDC 8006E040 5400A0AF */  sw         $zero, 0x54($sp)
    /* 1DB0DE0 8006E044 6C6F000C */  jal        func_8001BDB0
    /* 1DB0DE4 8006E048 5800A2AF */   sw        $v0, 0x58($sp)
    /* 1DB0DE8 8006E04C 21200000 */  addu       $a0, $zero, $zero
    /* 1DB0DEC 8006E050 63E2000C */  jal        func_8003898C
    /* 1DB0DF0 8006E054 2C010524 */   addiu     $a1, $zero, 0x12C
    /* 1DB0DF4 8006E058 21200000 */  addu       $a0, $zero, $zero
    /* 1DB0DF8 8006E05C 6000A38F */  lw         $v1, 0x60($sp)
    /* 1DB0DFC 8006E060 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 1DB0E00 8006E064 21186200 */  addu       $v1, $v1, $v0
    /* 1DB0E04 8006E068 63E2000C */  jal        func_8003898C
    /* 1DB0E08 8006E06C 6000A3AF */   sw        $v1, 0x60($sp)
    /* 1DB0E0C 8006E070 21200000 */  addu       $a0, $zero, $zero
    /* 1DB0E10 8006E074 6400A38F */  lw         $v1, 0x64($sp)
    /* 1DB0E14 8006E078 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 1DB0E18 8006E07C 21186200 */  addu       $v1, $v1, $v0
    /* 1DB0E1C 8006E080 63E2000C */  jal        func_8003898C
    /* 1DB0E20 8006E084 6400A3AF */   sw        $v1, 0x64($sp)
    /* 1DB0E24 8006E088 01000424 */  addiu      $a0, $zero, 0x1
    /* 1DB0E28 8006E08C 0D000524 */  addiu      $a1, $zero, 0xD
    /* 1DB0E2C 8006E090 21300002 */  addu       $a2, $s0, $zero
    /* 1DB0E30 8006E094 5000A727 */  addiu      $a3, $sp, 0x50
    /* 1DB0E34 8006E098 6800A38F */  lw         $v1, 0x68($sp)
    /* 1DB0E38 8006E09C 0680083C */  lui        $t0, %hi(D_800670FC)
    /* 1DB0E3C 8006E0A0 FC70088D */  lw         $t0, %lo(D_800670FC)($t0)
    /* 1DB0E40 8006E0A4 21186200 */  addu       $v1, $v1, $v0
    /* 1DB0E44 8006E0A8 09F80001 */  jalr       $t0
    /* 1DB0E48 8006E0AC 6800A3AF */   sw        $v1, 0x68($sp)
    /* 1DB0E4C 8006E0B0 06000324 */  addiu      $v1, $zero, 0x6
    /* 1DB0E50 8006E0B4 020043A0 */  sb         $v1, 0x2($v0)
    /* 1DB0E54 8006E0B8 20000324 */  addiu      $v1, $zero, 0x20
    /* 1DB0E58 8006E0BC BDB90108 */  j          .Llevel_26_8006E6F4
    /* 1DB0E5C 8006E0C0 0A0043A0 */   sb        $v1, 0xA($v0)
  .Llevel_26_8006E0C4:
    /* 1DB0E60 8006E0C4 5000A427 */  addiu      $a0, $sp, 0x50
    /* 1DB0E64 8006E0C8 0780113C */  lui        $s1, %hi(D_8006A144)
    /* 1DB0E68 8006E0CC 44A13126 */  addiu      $s1, $s1, %lo(D_8006A144)
    /* 1DB0E6C 8006E0D0 21282002 */  addu       $a1, $s1, $zero
    /* 1DB0E70 8006E0D4 A5AD000C */  jal        func_8002B694
    /* 1DB0E74 8006E0D8 21300000 */   addu      $a2, $zero, $zero
    /* 1DB0E78 8006E0DC 5400A28F */  lw         $v0, 0x54($sp)
    /* 1DB0E7C 8006E0E0 0780043C */  lui        $a0, %hi(D_8006A08C)
    /* 1DB0E80 8006E0E4 8CA0848C */  lw         $a0, %lo(D_8006A08C)($a0)
    /* 1DB0E84 8006E0E8 23100200 */  negu       $v0, $v0
    /* 1DB0E88 8006E0EC 80180200 */  sll        $v1, $v0, 2
    /* 1DB0E8C 8006E0F0 21186200 */  addu       $v1, $v1, $v0
    /* 1DB0E90 8006E0F4 80180300 */  sll        $v1, $v1, 2
    /* 1DB0E94 8006E0F8 C3910300 */  sra        $s2, $v1, 7
    /* 1DB0E98 8006E0FC C3200400 */  sra        $a0, $a0, 3
    /* 1DB0E9C 8006E100 5000A38F */  lw         $v1, 0x50($sp)
    /* 1DB0EA0 8006E104 00FC8424 */  addiu      $a0, $a0, -0x400
    /* 1DB0EA4 8006E108 6000A4AF */  sw         $a0, 0x60($sp)
    /* 1DB0EA8 8006E10C 80100300 */  sll        $v0, $v1, 2
    /* 1DB0EAC 8006E110 21104300 */  addu       $v0, $v0, $v1
    /* 1DB0EB0 8006E114 80100200 */  sll        $v0, $v0, 2
    /* 1DB0EB4 8006E118 24008104 */  bgez       $a0, .Llevel_26_8006E1AC
    /* 1DB0EB8 8006E11C C3990200 */   sra       $s3, $v0, 7
    /* 1DB0EBC 8006E120 5800B027 */  addiu      $s0, $sp, 0x58
    /* 1DB0EC0 8006E124 21200002 */  addu       $a0, $s0, $zero
    /* 1DB0EC4 8006E128 21280002 */  addu       $a1, $s0, $zero
    /* 1DB0EC8 8006E12C ACFE3126 */  addiu      $s1, $s1, -0x154
    /* 1DB0ECC 8006E130 21302002 */  addu       $a2, $s1, $zero
    /* 1DB0ED0 8006E134 0780023C */  lui        $v0, %hi(D_8006A084)
    /* 1DB0ED4 8006E138 84A0428C */  lw         $v0, %lo(D_8006A084)($v0)
    /* 1DB0ED8 8006E13C 0780033C */  lui        $v1, %hi(D_8006A088)
    /* 1DB0EDC 8006E140 88A0638C */  lw         $v1, %lo(D_8006A088)($v1)
    /* 1DB0EE0 8006E144 C3100200 */  sra        $v0, $v0, 3
    /* 1DB0EE4 8006E148 C3180300 */  sra        $v1, $v1, 3
    /* 1DB0EE8 8006E14C 5800A2AF */  sw         $v0, 0x58($sp)
    /* 1DB0EEC 8006E150 736F000C */  jal        func_8001BDCC
    /* 1DB0EF0 8006E154 5C00A3AF */   sw        $v1, 0x5C($sp)
    /* 1DB0EF4 8006E158 21202002 */  addu       $a0, $s1, $zero
    /* 1DB0EF8 8006E15C 21280002 */  addu       $a1, $s0, $zero
    /* 1DB0EFC 8006E160 867D000C */  jal        func_8001F618
    /* 1DB0F00 8006E164 02000624 */   addiu     $a2, $zero, 0x2
    /* 1DB0F04 8006E168 11004014 */  bnez       $v0, .Llevel_26_8006E1B0
    /* 1DB0F08 8006E16C 19000224 */   addiu     $v0, $zero, 0x19
    /* 1DB0F0C 8006E170 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 1DB0F10 8006E174 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 1DB0F14 8006E178 0780033C */  lui        $v1, %hi(D_8006AB78)
    /* 1DB0F18 8006E17C 78AB638C */  lw         $v1, %lo(D_8006AB78)($v1)
    /* 1DB0F1C 8006E180 00000000 */  nop
    /* 1DB0F20 8006E184 23104300 */  subu       $v0, $v0, $v1
    /* 1DB0F24 8006E188 C3100200 */  sra        $v0, $v0, 3
    /* 1DB0F28 8006E18C 5400A2AF */  sw         $v0, 0x54($sp)
    /* 1DB0F2C 8006E190 0B004228 */  slti       $v0, $v0, 0xB
    /* 1DB0F30 8006E194 02004014 */  bnez       $v0, .Llevel_26_8006E1A0
    /* 1DB0F34 8006E198 0A000224 */   addiu     $v0, $zero, 0xA
    /* 1DB0F38 8006E19C 5400A2AF */  sw         $v0, 0x54($sp)
  .Llevel_26_8006E1A0:
    /* 1DB0F3C 8006E1A0 5400A28F */  lw         $v0, 0x54($sp)
    /* 1DB0F40 8006E1A4 00000000 */  nop
    /* 1DB0F44 8006E1A8 21904202 */  addu       $s2, $s2, $v0
  .Llevel_26_8006E1AC:
    /* 1DB0F48 8006E1AC 19000224 */  addiu      $v0, $zero, 0x19
  .Llevel_26_8006E1B0:
    /* 1DB0F4C 8006E1B0 0680033C */  lui        $v1, %hi(D_80066F90)
    /* 1DB0F50 8006E1B4 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* 1DB0F54 8006E1B8 0780043C */  lui        $a0, %hi(D_8006A0F0)
    /* 1DB0F58 8006E1BC F0A0848C */  lw         $a0, %lo(D_8006A0F0)($a0)
    /* 1DB0F5C 8006E1C0 07006214 */  bne        $v1, $v0, .Llevel_26_8006E1E0
    /* 1DB0F60 8006E1C4 00000000 */   nop
    /* 1DB0F64 8006E1C8 0780023C */  lui        $v0, %hi(D_8006ABF8)
    /* 1DB0F68 8006E1CC F8AB4290 */  lbu        $v0, %lo(D_8006ABF8)($v0)
    /* 1DB0F6C 8006E1D0 00000000 */  nop
    /* 1DB0F70 8006E1D4 02004010 */  beqz       $v0, .Llevel_26_8006E1E0
    /* 1DB0F74 8006E1D8 00000000 */   nop
    /* 1DB0F78 8006E1DC 08CF0434 */  ori        $a0, $zero, 0xCF08
  .Llevel_26_8006E1E0:
    /* 1DB0F7C 8006E1E0 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 1DB0F80 8006E1E4 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 1DB0F84 8006E1E8 00000000 */  nop
    /* 1DB0F88 8006E1EC 23188200 */  subu       $v1, $a0, $v0
    /* 1DB0F8C 8006E1F0 00106228 */  slti       $v0, $v1, 0x1000
    /* 1DB0F90 8006E1F4 12004010 */  beqz       $v0, .Llevel_26_8006E240
    /* 1DB0F94 8006E1F8 40100300 */   sll       $v0, $v1, 1
    /* 1DB0F98 8006E1FC 21104300 */  addu       $v0, $v0, $v1
    /* 1DB0F9C 8006E200 C0100200 */  sll        $v0, $v0, 3
    /* 1DB0FA0 8006E204 21104300 */  addu       $v0, $v0, $v1
    /* 1DB0FA4 8006E208 40110200 */  sll        $v0, $v0, 5
    /* 1DB0FA8 8006E20C 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 1DB0FAC 8006E210 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 1DB0FB0 8006E214 03230200 */  sra        $a0, $v0, 12
    /* 1DB0FB4 8006E218 23188300 */  subu       $v1, $a0, $v1
    /* 1DB0FB8 8006E21C FF0F6430 */  andi       $a0, $v1, 0xFFF
    /* 1DB0FBC 8006E220 01088228 */  slti       $v0, $a0, 0x801
    /* 1DB0FC0 8006E224 03004014 */  bnez       $v0, .Llevel_26_8006E234
    /* 1DB0FC4 8006E228 2A109200 */   slt       $v0, $a0, $s2
    /* 1DB0FC8 8006E22C 00F08424 */  addiu      $a0, $a0, -0x1000
    /* 1DB0FCC 8006E230 2A109200 */  slt        $v0, $a0, $s2
  .Llevel_26_8006E234:
    /* 1DB0FD0 8006E234 02004010 */  beqz       $v0, .Llevel_26_8006E240
    /* 1DB0FD4 8006E238 00000000 */   nop
    /* 1DB0FD8 8006E23C 21908000 */  addu       $s2, $a0, $zero
  .Llevel_26_8006E240:
    /* 1DB0FDC 8006E240 0780043C */  lui        $a0, %hi(D_8006A05C)
    /* 1DB0FE0 8006E244 5CA08424 */  addiu      $a0, $a0, %lo(D_8006A05C)
    /* 1DB0FE4 8006E248 0000828C */  lw         $v0, 0x0($a0)
    /* 1DB0FE8 8006E24C 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 1DB0FEC 8006E250 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 1DB0FF0 8006E254 21105300 */  addu       $v0, $v0, $s3
    /* 1DB0FF4 8006E258 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* 1DB0FF8 8006E25C 21187200 */  addu       $v1, $v1, $s2
    /* 1DB0FFC 8006E260 FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 1DB1000 8006E264 000082AC */  sw         $v0, 0x0($a0)
    /* 1DB1004 8006E268 01086228 */  slti       $v0, $v1, 0x801
    /* 1DB1008 8006E26C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1DB100C 8006E270 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 1DB1010 8006E274 03004014 */  bnez       $v0, .Llevel_26_8006E284
    /* 1DB1014 8006E278 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 1DB1018 8006E27C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1DB101C 8006E280 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_26_8006E284:
    /* 1DB1020 8006E284 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 1DB1024 8006E288 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 1DB1028 8006E28C 00000000 */  nop
    /* 1DB102C 8006E290 E0FC4228 */  slti       $v0, $v0, -0x320
    /* 1DB1030 8006E294 03004010 */  beqz       $v0, .Llevel_26_8006E2A4
    /* 1DB1034 8006E298 E0FC0224 */   addiu     $v0, $zero, -0x320
    /* 1DB1038 8006E29C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1DB103C 8006E2A0 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_26_8006E2A4:
    /* 1DB1040 8006E2A4 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 1DB1044 8006E2A8 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 1DB1048 8006E2AC 00000000 */  nop
    /* 1DB104C 8006E2B0 21034228 */  slti       $v0, $v0, 0x321
    /* 1DB1050 8006E2B4 03004014 */  bnez       $v0, .Llevel_26_8006E2C4
    /* 1DB1054 8006E2B8 20030224 */   addiu     $v0, $zero, 0x320
    /* 1DB1058 8006E2BC 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1DB105C 8006E2C0 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_26_8006E2C4:
    /* 1DB1060 8006E2C4 0780023C */  lui        $v0, %hi(D_80069894)
    /* 1DB1064 8006E2C8 9498428C */  lw         $v0, %lo(D_80069894)($v0)
    /* 1DB1068 8006E2CC 00000000 */  nop
    /* 1DB106C 8006E2D0 46004104 */  bgez       $v0, .Llevel_26_8006E3EC
    /* 1DB1070 8006E2D4 00000000 */   nop
    /* 1DB1074 8006E2D8 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 1DB1078 8006E2DC 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 1DB107C 8006E2E0 00000000 */  nop
    /* 1DB1080 8006E2E4 07006104 */  bgez       $v1, .Llevel_26_8006E304
    /* 1DB1084 8006E2E8 00000000 */   nop
    /* 1DB1088 8006E2EC 0680043C */  lui        $a0, %hi(D_80060184)
    /* 1DB108C 8006E2F0 8401848C */  lw         $a0, %lo(D_80060184)($a0)
    /* 1DB1090 8006E2F4 0680023C */  lui        $v0, %hi(D_80060180)
    /* 1DB1094 8006E2F8 8001428C */  lw         $v0, %lo(D_80060180)($v0)
    /* 1DB1098 8006E2FC C9B80108 */  j          .Llevel_26_8006E324
    /* 1DB109C 8006E300 23108200 */   subu      $v0, $a0, $v0
  .Llevel_26_8006E304:
    /* 1DB10A0 8006E304 15006018 */  blez       $v1, .Llevel_26_8006E35C
    /* 1DB10A4 8006E308 00000000 */   nop
    /* 1DB10A8 8006E30C 0680023C */  lui        $v0, %hi(D_80060188)
    /* 1DB10AC 8006E310 8801428C */  lw         $v0, %lo(D_80060188)($v0)
    /* 1DB10B0 8006E314 0680043C */  lui        $a0, %hi(D_80060184)
    /* 1DB10B4 8006E318 8401848C */  lw         $a0, %lo(D_80060184)($a0)
    /* 1DB10B8 8006E31C 00000000 */  nop
    /* 1DB10BC 8006E320 23104400 */  subu       $v0, $v0, $a0
  .Llevel_26_8006E324:
    /* 1DB10C0 8006E324 18006200 */  mult       $v1, $v0
    /* 1DB10C4 8006E328 12100000 */  mflo       $v0
    /* 1DB10C8 8006E32C EB51033C */  lui        $v1, (0x51EB851F >> 16)
    /* 1DB10CC 8006E330 1F856334 */  ori        $v1, $v1, (0x51EB851F & 0xFFFF)
    /* 1DB10D0 8006E334 18004300 */  mult       $v0, $v1
    /* 1DB10D4 8006E338 C3170200 */  sra        $v0, $v0, 31
    /* 1DB10D8 8006E33C 10480000 */  mfhi       $t1
    /* 1DB10DC 8006E340 031A0900 */  sra        $v1, $t1, 8
    /* 1DB10E0 8006E344 23186200 */  subu       $v1, $v1, $v0
    /* 1DB10E4 8006E348 21208300 */  addu       $a0, $a0, $v1
    /* 1DB10E8 8006E34C 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 1DB10EC 8006E350 A4A024AC */  sw         $a0, %lo(D_8006A0A4)($at)
    /* 1DB10F0 8006E354 DBB80108 */  j          .Llevel_26_8006E36C
    /* 1DB10F4 8006E358 00000000 */   nop
  .Llevel_26_8006E35C:
    /* 1DB10F8 8006E35C 0680023C */  lui        $v0, %hi(D_80060184)
    /* 1DB10FC 8006E360 8401428C */  lw         $v0, %lo(D_80060184)($v0)
    /* 1DB1100 8006E364 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 1DB1104 8006E368 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
  .Llevel_26_8006E36C:
    /* 1DB1108 8006E36C 0780053C */  lui        $a1, %hi(D_8006A13C)
    /* 1DB110C 8006E370 3CA1A524 */  addiu      $a1, $a1, %lo(D_8006A13C)
    /* 1DB1110 8006E374 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 1DB1114 8006E378 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 1DB1118 8006E37C 0780043C */  lui        $a0, %hi(D_8006A0A8)
    /* 1DB111C 8006E380 A8A0848C */  lw         $a0, %lo(D_8006A0A8)($a0)
    /* 1DB1120 8006E384 0000A38C */  lw         $v1, 0x0($a1)
    /* 1DB1124 8006E388 23104400 */  subu       $v0, $v0, $a0
    /* 1DB1128 8006E38C 23104300 */  subu       $v0, $v0, $v1
    /* 1DB112C 8006E390 80110200 */  sll        $v0, $v0, 6
    /* 1DB1130 8006E394 83110200 */  sra        $v0, $v0, 6
    /* 1DB1134 8006E398 21186200 */  addu       $v1, $v1, $v0
    /* 1DB1138 8006E39C 0000A3AC */  sw         $v1, 0x0($a1)
    /* 1DB113C 8006E3A0 83190300 */  sra        $v1, $v1, 6
    /* 1DB1140 8006E3A4 21208300 */  addu       $a0, $a0, $v1
    /* 1DB1144 8006E3A8 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1DB1148 8006E3AC A8A024AC */  sw         $a0, %lo(D_8006A0A8)($at)
    /* 1DB114C 8006E3B0 00088428 */  slti       $a0, $a0, 0x800
    /* 1DB1150 8006E3B4 03008010 */  beqz       $a0, .Llevel_26_8006E3C4
    /* 1DB1154 8006E3B8 00080224 */   addiu     $v0, $zero, 0x800
    /* 1DB1158 8006E3BC 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1DB115C 8006E3C0 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_26_8006E3C4:
    /* 1DB1160 8006E3C4 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 1DB1164 8006E3C8 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 1DB1168 8006E3CC 00000000 */  nop
    /* 1DB116C 8006E3D0 014B4228 */  slti       $v0, $v0, 0x4B01
    /* 1DB1170 8006E3D4 41004014 */  bnez       $v0, .Llevel_26_8006E4DC
    /* 1DB1174 8006E3D8 004B0224 */   addiu     $v0, $zero, 0x4B00
    /* 1DB1178 8006E3DC 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1DB117C 8006E3E0 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 1DB1180 8006E3E4 37B90108 */  j          .Llevel_26_8006E4DC
    /* 1DB1184 8006E3E8 00000000 */   nop
  .Llevel_26_8006E3EC:
    /* 1DB1188 8006E3EC 0680033C */  lui        $v1, %hi(D_80066F90)
    /* 1DB118C 8006E3F0 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* 1DB1190 8006E3F4 19000224 */  addiu      $v0, $zero, 0x19
    /* 1DB1194 8006E3F8 13006214 */  bne        $v1, $v0, .Llevel_26_8006E448
    /* 1DB1198 8006E3FC 00000000 */   nop
    /* 1DB119C 8006E400 0780023C */  lui        $v0, %hi(D_8006ABF8)
    /* 1DB11A0 8006E404 F8AB4290 */  lbu        $v0, %lo(D_8006ABF8)($v0)
    /* 1DB11A4 8006E408 00000000 */  nop
    /* 1DB11A8 8006E40C 0E004010 */  beqz       $v0, .Llevel_26_8006E448
    /* 1DB11AC 8006E410 08CF0234 */   ori       $v0, $zero, 0xCF08
    /* 1DB11B0 8006E414 0780033C */  lui        $v1, %hi(D_80069FF8)
    /* 1DB11B4 8006E418 F89F638C */  lw         $v1, %lo(D_80069FF8)($v1)
    /* 1DB11B8 8006E41C 00000000 */  nop
    /* 1DB11BC 8006E420 23204300 */  subu       $a0, $v0, $v1
    /* 1DB11C0 8006E424 03008104 */  bgez       $a0, .Llevel_26_8006E434
    /* 1DB11C4 8006E428 00000000 */   nop
    /* 1DB11C8 8006E42C 27B90108 */  j          .Llevel_26_8006E49C
    /* 1DB11CC 8006E430 00080224 */   addiu     $v0, $zero, 0x800
  .Llevel_26_8006E434:
    /* 1DB11D0 8006E434 F06F000C */  jal        func_8001BFC0
    /* 1DB11D4 8006E438 00000000 */   nop
    /* 1DB11D8 8006E43C 80110200 */  sll        $v0, $v0, 6
    /* 1DB11DC 8006E440 27B90108 */  j          .Llevel_26_8006E49C
    /* 1DB11E0 8006E444 00084224 */   addiu     $v0, $v0, 0x800
  .Llevel_26_8006E448:
    /* 1DB11E4 8006E448 0780033C */  lui        $v1, %hi(D_8006A0F0)
    /* 1DB11E8 8006E44C F0A0638C */  lw         $v1, %lo(D_8006A0F0)($v1)
    /* 1DB11EC 8006E450 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 1DB11F0 8006E454 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 1DB11F4 8006E458 00000000 */  nop
    /* 1DB11F8 8006E45C 23206200 */  subu       $a0, $v1, $v0
    /* 1DB11FC 8006E460 0A008104 */  bgez       $a0, .Llevel_26_8006E48C
    /* 1DB1200 8006E464 00000000 */   nop
    /* 1DB1204 8006E468 F06F000C */  jal        func_8001BFC0
    /* 1DB1208 8006E46C 23200400 */   negu      $a0, $a0
    /* 1DB120C 8006E470 C0110200 */  sll        $v0, $v0, 7
    /* 1DB1210 8006E474 40100324 */  addiu      $v1, $zero, 0x1040
    /* 1DB1214 8006E478 23186200 */  subu       $v1, $v1, $v0
    /* 1DB1218 8006E47C 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1DB121C 8006E480 A8A023AC */  sw         $v1, %lo(D_8006A0A8)($at)
    /* 1DB1220 8006E484 29B90108 */  j          .Llevel_26_8006E4A4
    /* 1DB1224 8006E488 00000000 */   nop
  .Llevel_26_8006E48C:
    /* 1DB1228 8006E48C F06F000C */  jal        func_8001BFC0
    /* 1DB122C 8006E490 00000000 */   nop
    /* 1DB1230 8006E494 80110200 */  sll        $v0, $v0, 6
    /* 1DB1234 8006E498 40104224 */  addiu      $v0, $v0, 0x1040
  .Llevel_26_8006E49C:
    /* 1DB1238 8006E49C 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1DB123C 8006E4A0 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_26_8006E4A4:
    /* 1DB1240 8006E4A4 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 1DB1244 8006E4A8 A8A06324 */  addiu      $v1, $v1, %lo(D_8006A0A8)
    /* 1DB1248 8006E4AC 0000628C */  lw         $v0, 0x0($v1)
    /* 1DB124C 8006E4B0 00000000 */  nop
    /* 1DB1250 8006E4B4 01594228 */  slti       $v0, $v0, 0x5901
    /* 1DB1254 8006E4B8 02004014 */  bnez       $v0, .Llevel_26_8006E4C4
    /* 1DB1258 8006E4BC 00590224 */   addiu     $v0, $zero, 0x5900
    /* 1DB125C 8006E4C0 000062AC */  sw         $v0, 0x0($v1)
  .Llevel_26_8006E4C4:
    /* 1DB1260 8006E4C4 0000628C */  lw         $v0, 0x0($v1)
    /* 1DB1264 8006E4C8 00000000 */  nop
    /* 1DB1268 8006E4CC 00084228 */  slti       $v0, $v0, 0x800
    /* 1DB126C 8006E4D0 02004010 */  beqz       $v0, .Llevel_26_8006E4DC
    /* 1DB1270 8006E4D4 00080224 */   addiu     $v0, $zero, 0x800
    /* 1DB1274 8006E4D8 000062AC */  sw         $v0, 0x0($v1)
  .Llevel_26_8006E4DC:
    /* 1DB1278 8006E4DC 0780043C */  lui        $a0, %hi(D_8006A058)
    /* 1DB127C 8006E4E0 58A0848C */  lw         $a0, %lo(D_8006A058)($a0)
    /* 1DB1280 8006E4E4 996D000C */  jal        func_8001B664
    /* 1DB1284 8006E4E8 00000000 */   nop
    /* 1DB1288 8006E4EC 40110200 */  sll        $v0, $v0, 5
    /* 1DB128C 8006E4F0 23100200 */  negu       $v0, $v0
    /* 1DB1290 8006E4F4 18006202 */  mult       $s3, $v0
    /* 1DB1294 8006E4F8 0780033C */  lui        $v1, %hi(D_8006A144)
    /* 1DB1298 8006E4FC 44A1638C */  lw         $v1, %lo(D_8006A144)($v1)
    /* 1DB129C 8006E500 0780053C */  lui        $a1, %hi(D_8006A054)
    /* 1DB12A0 8006E504 54A0A58C */  lw         $a1, %lo(D_8006A054)($a1)
    /* 1DB12A4 8006E508 00110300 */  sll        $v0, $v1, 4
    /* 1DB12A8 8006E50C 83110200 */  sra        $v0, $v0, 6
    /* 1DB12AC 8006E510 12480000 */  mflo       $t1
    /* 1DB12B0 8006E514 03230900 */  sra        $a0, $t1, 12
    /* 1DB12B4 8006E518 23208200 */  subu       $a0, $a0, $v0
    /* 1DB12B8 8006E51C 80110500 */  sll        $v0, $a1, 6
    /* 1DB12BC 8006E520 83110200 */  sra        $v0, $v0, 6
    /* 1DB12C0 8006E524 23208200 */  subu       $a0, $a0, $v0
    /* 1DB12C4 8006E528 21186400 */  addu       $v1, $v1, $a0
    /* 1DB12C8 8006E52C 0780013C */  lui        $at, %hi(D_8006A144)
    /* 1DB12CC 8006E530 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 1DB12D0 8006E534 83190300 */  sra        $v1, $v1, 6
    /* 1DB12D4 8006E538 2128A300 */  addu       $a1, $a1, $v1
    /* 1DB12D8 8006E53C FF0FA530 */  andi       $a1, $a1, 0xFFF
    /* 1DB12DC 8006E540 0108A228 */  slti       $v0, $a1, 0x801
    /* 1DB12E0 8006E544 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1DB12E4 8006E548 54A025AC */  sw         $a1, %lo(D_8006A054)($at)
    /* 1DB12E8 8006E54C 03004014 */  bnez       $v0, .Llevel_26_8006E55C
    /* 1DB12EC 8006E550 00F0A224 */   addiu     $v0, $a1, -0x1000
    /* 1DB12F0 8006E554 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1DB12F4 8006E558 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_26_8006E55C:
    /* 1DB12F8 8006E55C 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 1DB12FC 8006E560 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 1DB1300 8006E564 00000000 */  nop
    /* 1DB1304 8006E568 00FD4228 */  slti       $v0, $v0, -0x300
    /* 1DB1308 8006E56C 03004010 */  beqz       $v0, .Llevel_26_8006E57C
    /* 1DB130C 8006E570 00FD0224 */   addiu     $v0, $zero, -0x300
    /* 1DB1310 8006E574 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1DB1314 8006E578 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_26_8006E57C:
    /* 1DB1318 8006E57C 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 1DB131C 8006E580 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 1DB1320 8006E584 00000000 */  nop
    /* 1DB1324 8006E588 01034228 */  slti       $v0, $v0, 0x301
    /* 1DB1328 8006E58C 03004014 */  bnez       $v0, .Llevel_26_8006E59C
    /* 1DB132C 8006E590 00030224 */   addiu     $v0, $zero, 0x300
    /* 1DB1330 8006E594 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1DB1334 8006E598 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_26_8006E59C:
    /* 1DB1338 8006E59C 6FAF000C */  jal        func_8002BDBC
    /* 1DB133C 8006E5A0 00000000 */   nop
    /* 1DB1340 8006E5A4 0780043C */  lui        $a0, %hi(D_8006A044)
    /* 1DB1344 8006E5A8 44A0848C */  lw         $a0, %lo(D_8006A044)($a0)
    /* 1DB1348 8006E5AC 00000000 */  nop
    /* 1DB134C 8006E5B0 1C008014 */  bnez       $a0, .Llevel_26_8006E624
    /* 1DB1350 8006E5B4 00000000 */   nop
    /* 1DB1354 8006E5B8 0680023C */  lui        $v0, %hi(D_80066F38)
    /* 1DB1358 8006E5BC 386F428C */  lw         $v0, %lo(D_80066F38)($v0)
    /* 1DB135C 8006E5C0 00000000 */  nop
    /* 1DB1360 8006E5C4 0400428C */  lw         $v0, 0x4($v0)
    /* 1DB1364 8006E5C8 00000000 */  nop
    /* 1DB1368 8006E5CC 40004230 */  andi       $v0, $v0, 0x40
    /* 1DB136C 8006E5D0 46004010 */  beqz       $v0, .Llevel_26_8006E6EC
    /* 1DB1370 8006E5D4 00000000 */   nop
    /* 1DB1374 8006E5D8 0780023C */  lui        $v0, %hi(D_8006A0F0)
    /* 1DB1378 8006E5DC F0A0428C */  lw         $v0, %lo(D_8006A0F0)($v0)
    /* 1DB137C 8006E5E0 0780033C */  lui        $v1, %hi(D_80069FF8)
    /* 1DB1380 8006E5E4 F89F638C */  lw         $v1, %lo(D_80069FF8)($v1)
    /* 1DB1384 8006E5E8 00FE4224 */  addiu      $v0, $v0, -0x200
    /* 1DB1388 8006E5EC 2A186200 */  slt        $v1, $v1, $v0
    /* 1DB138C 8006E5F0 3E006010 */  beqz       $v1, .Llevel_26_8006E6EC
    /* 1DB1390 8006E5F4 21000224 */   addiu     $v0, $zero, 0x21
    /* 1DB1394 8006E5F8 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 1DB1398 8006E5FC 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 1DB139C 8006E600 00000000 */  nop
    /* 1DB13A0 8006E604 39006214 */  bne        $v1, $v0, .Llevel_26_8006E6EC
    /* 1DB13A4 8006E608 01000224 */   addiu     $v0, $zero, 0x1
    /* 1DB13A8 8006E60C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1DB13AC 8006E610 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 1DB13B0 8006E614 0780013C */  lui        $at, %hi(D_8006A150)
    /* 1DB13B4 8006E618 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 1DB13B8 8006E61C BBB90108 */  j          .Llevel_26_8006E6EC
    /* 1DB13BC 8006E620 00000000 */   nop
  .Llevel_26_8006E624:
    /* 1DB13C0 8006E624 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 1DB13C4 8006E628 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 1DB13C8 8006E62C 0780033C */  lui        $v1, %hi(D_8006A0F0)
    /* 1DB13CC 8006E630 F0A0638C */  lw         $v1, %lo(D_8006A0F0)($v1)
    /* 1DB13D0 8006E634 00000000 */  nop
    /* 1DB13D4 8006E638 2A104300 */  slt        $v0, $v0, $v1
    /* 1DB13D8 8006E63C 05004014 */  bnez       $v0, .Llevel_26_8006E654
    /* 1DB13DC 8006E640 01000224 */   addiu     $v0, $zero, 0x1
    /* 1DB13E0 8006E644 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1DB13E4 8006E648 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1DB13E8 8006E64C BBB90108 */  j          .Llevel_26_8006E6EC
    /* 1DB13EC 8006E650 00000000 */   nop
  .Llevel_26_8006E654:
    /* 1DB13F0 8006E654 11008214 */  bne        $a0, $v0, .Llevel_26_8006E69C
    /* 1DB13F4 8006E658 00000000 */   nop
    /* 1DB13F8 8006E65C 0780023C */  lui        $v0, %hi(D_8006A150)
    /* 1DB13FC 8006E660 50A1428C */  lw         $v0, %lo(D_8006A150)($v0)
    /* 1DB1400 8006E664 00000000 */  nop
    /* 1DB1404 8006E668 00024224 */  addiu      $v0, $v0, 0x200
    /* 1DB1408 8006E66C 0780013C */  lui        $at, %hi(D_8006A150)
    /* 1DB140C 8006E670 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 1DB1410 8006E674 00184228 */  slti       $v0, $v0, 0x1800
    /* 1DB1414 8006E678 14004014 */  bnez       $v0, .Llevel_26_8006E6CC
    /* 1DB1418 8006E67C 00180224 */   addiu     $v0, $zero, 0x1800
    /* 1DB141C 8006E680 0780013C */  lui        $at, %hi(D_8006A150)
    /* 1DB1420 8006E684 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 1DB1424 8006E688 02000224 */  addiu      $v0, $zero, 0x2
    /* 1DB1428 8006E68C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1DB142C 8006E690 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 1DB1430 8006E694 B3B90108 */  j          .Llevel_26_8006E6CC
    /* 1DB1434 8006E698 00000000 */   nop
  .Llevel_26_8006E69C:
    /* 1DB1438 8006E69C 0780023C */  lui        $v0, %hi(D_8006A150)
    /* 1DB143C 8006E6A0 50A1428C */  lw         $v0, %lo(D_8006A150)($v0)
    /* 1DB1440 8006E6A4 00000000 */  nop
    /* 1DB1444 8006E6A8 00FF4224 */  addiu      $v0, $v0, -0x100
    /* 1DB1448 8006E6AC 0780013C */  lui        $at, %hi(D_8006A150)
    /* 1DB144C 8006E6B0 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 1DB1450 8006E6B4 0500401C */  bgtz       $v0, .Llevel_26_8006E6CC
    /* 1DB1454 8006E6B8 00000000 */   nop
    /* 1DB1458 8006E6BC 0780013C */  lui        $at, %hi(D_8006A150)
    /* 1DB145C 8006E6C0 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 1DB1460 8006E6C4 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1DB1464 8006E6C8 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
  .Llevel_26_8006E6CC:
    /* 1DB1468 8006E6CC 0780023C */  lui        $v0, %hi(D_8006A080)
    /* 1DB146C 8006E6D0 80A04224 */  addiu      $v0, $v0, %lo(D_8006A080)
    /* 1DB1470 8006E6D4 0000438C */  lw         $v1, 0x0($v0)
    /* 1DB1474 8006E6D8 0780043C */  lui        $a0, %hi(D_8006A150)
    /* 1DB1478 8006E6DC 50A1848C */  lw         $a0, %lo(D_8006A150)($a0)
    /* 1DB147C 8006E6E0 00000000 */  nop
    /* 1DB1480 8006E6E4 21186400 */  addu       $v1, $v1, $a0
    /* 1DB1484 8006E6E8 000043AC */  sw         $v1, 0x0($v0)
  .Llevel_26_8006E6EC:
    /* 1DB1488 8006E6EC 0EB0000C */  jal        func_8002C038
    /* 1DB148C 8006E6F0 00000000 */   nop
  .Llevel_26_8006E6F4:
    /* 1DB1490 8006E6F4 8000BF8F */  lw         $ra, 0x80($sp)
    /* 1DB1494 8006E6F8 7C00B38F */  lw         $s3, 0x7C($sp)
    /* 1DB1498 8006E6FC 7800B28F */  lw         $s2, 0x78($sp)
    /* 1DB149C 8006E700 7400B18F */  lw         $s1, 0x74($sp)
    /* 1DB14A0 8006E704 7000B08F */  lw         $s0, 0x70($sp)
    /* 1DB14A4 8006E708 8800BD27 */  addiu      $sp, $sp, 0x88
    /* 1DB14A8 8006E70C 0800E003 */  jr         $ra
    /* 1DB14AC 8006E710 00000000 */   nop
endlabel func_level_26_8006DA20
