.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_62_8006D408

dlabel jtbl_level_62_8006D408
    /* 40B11A4 8006D408 34F60680 */ .word .Llevel_62_8006F634
    /* 40B11A8 8006D40C ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11AC 8006D410 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11B0 8006D414 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11B4 8006D418 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11B8 8006D41C ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11BC 8006D420 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11C0 8006D424 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11C4 8006D428 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11C8 8006D42C ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11CC 8006D430 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11D0 8006D434 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11D4 8006D438 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11D8 8006D43C ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11DC 8006D440 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11E0 8006D444 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11E4 8006D448 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11E8 8006D44C ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11EC 8006D450 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11F0 8006D454 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11F4 8006D458 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11F8 8006D45C ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B11FC 8006D460 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1200 8006D464 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1204 8006D468 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1208 8006D46C ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B120C 8006D470 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1210 8006D474 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1214 8006D478 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1218 8006D47C ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B121C 8006D480 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1220 8006D484 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1224 8006D488 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1228 8006D48C ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B122C 8006D490 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1230 8006D494 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1234 8006D498 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1238 8006D49C ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B123C 8006D4A0 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1240 8006D4A4 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1244 8006D4A8 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1248 8006D4AC 9CF60680 */ .word .Llevel_62_8006F69C
    /* 40B124C 8006D4B0 FCF60680 */ .word .Llevel_62_8006F6FC
    /* 40B1250 8006D4B4 FCF60680 */ .word .Llevel_62_8006F6FC
    /* 40B1254 8006D4B8 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1258 8006D4BC ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B125C 8006D4C0 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1260 8006D4C4 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1264 8006D4C8 ACF70680 */ .word .Llevel_62_8006F7AC
    /* 40B1268 8006D4CC 70F70680 */ .word .Llevel_62_8006F770
enddlabel jtbl_level_62_8006D408


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_62_8006F5F4, 0x1D0

glabel func_level_62_8006F5F4
    /* 40B3390 8006F5F4 0780023C */  lui        $v0, %hi(D_8006A004)
    /* 40B3394 8006F5F8 04A04290 */  lbu        $v0, %lo(D_8006A004)($v0)
    /* 40B3398 8006F5FC E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 40B339C 8006F600 1800BFAF */  sw         $ra, 0x18($sp)
    /* 40B33A0 8006F604 1400B1AF */  sw         $s1, 0x14($sp)
    /* 40B33A4 8006F608 F7FF4324 */  addiu      $v1, $v0, -0x9
    /* 40B33A8 8006F60C 3200622C */  sltiu      $v0, $v1, 0x32
    /* 40B33AC 8006F610 66004010 */  beqz       $v0, .Llevel_62_8006F7AC
    /* 40B33B0 8006F614 1000B0AF */   sw        $s0, 0x10($sp)
    /* 40B33B4 8006F618 80100300 */  sll        $v0, $v1, 2
    /* 40B33B8 8006F61C 0780013C */  lui        $at, %hi(jtbl_level_62_8006D408)
    /* 40B33BC 8006F620 21082200 */  addu       $at, $at, $v0
    /* 40B33C0 8006F624 08D4228C */  lw         $v0, %lo(jtbl_level_62_8006D408)($at)
    /* 40B33C4 8006F628 00000000 */  nop
    /* 40B33C8 8006F62C 08004000 */  jr         $v0
    /* 40B33CC 8006F630 00000000 */   nop
  .Llevel_62_8006F634:
    /* 40B33D0 8006F634 0780103C */  lui        $s0, %hi(D_8006A006)
    /* 40B33D4 8006F638 06A01026 */  addiu      $s0, $s0, %lo(D_8006A006)
    /* 40B33D8 8006F63C 00000392 */  lbu        $v1, 0x0($s0)
    /* 40B33DC 8006F640 01000224 */  addiu      $v0, $zero, 0x1
    /* 40B33E0 8006F644 03006210 */  beq        $v1, $v0, .Llevel_62_8006F654
    /* 40B33E4 8006F648 06000224 */   addiu     $v0, $zero, 0x6
    /* 40B33E8 8006F64C 57006214 */  bne        $v1, $v0, .Llevel_62_8006F7AC
    /* 40B33EC 8006F650 00000000 */   nop
  .Llevel_62_8006F654:
    /* 40B33F0 8006F654 0680023C */  lui        $v0, %hi(D_80067020)
    /* 40B33F4 8006F658 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 40B33F8 8006F65C 21280000 */  addu       $a1, $zero, $zero
    /* 40B33FC 8006F660 0B004490 */  lbu        $a0, 0xB($v0)
    /* 40B3400 8006F664 C841010C */  jal        func_80050720
    /* 40B3404 8006F668 21300000 */   addu      $a2, $zero, $zero
    /* 40B3408 8006F66C 00000392 */  lbu        $v1, 0x0($s0)
    /* 40B340C 8006F670 21204000 */  addu       $a0, $v0, $zero
    /* 40B3410 8006F674 0780013C */  lui        $at, %hi(D_8006A268)
    /* 40B3414 8006F678 68A223AC */  sw         $v1, %lo(D_8006A268)($at)
    /* 40B3418 8006F67C 4B008004 */  bltz       $a0, .Llevel_62_8006F7AC
    /* 40B341C 8006F680 06000224 */   addiu     $v0, $zero, 0x6
    /* 40B3420 8006F684 49006214 */  bne        $v1, $v0, .Llevel_62_8006F7AC
    /* 40B3424 8006F688 00000000 */   nop
    /* 40B3428 8006F68C 1943010C */  jal        func_80050C64
    /* 40B342C 8006F690 90110524 */   addiu     $a1, $zero, 0x1190
    /* 40B3430 8006F694 EBBD0108 */  j          .Llevel_62_8006F7AC
    /* 40B3434 8006F698 00000000 */   nop
  .Llevel_62_8006F69C:
    /* 40B3438 8006F69C 0780103C */  lui        $s0, %hi(D_8006A006)
    /* 40B343C 8006F6A0 06A01026 */  addiu      $s0, $s0, %lo(D_8006A006)
    /* 40B3440 8006F6A4 00000392 */  lbu        $v1, 0x0($s0)
    /* 40B3444 8006F6A8 03000224 */  addiu      $v0, $zero, 0x3
    /* 40B3448 8006F6AC 03006210 */  beq        $v1, $v0, .Llevel_62_8006F6BC
    /* 40B344C 8006F6B0 0A000224 */   addiu     $v0, $zero, 0xA
    /* 40B3450 8006F6B4 3D006214 */  bne        $v1, $v0, .Llevel_62_8006F7AC
    /* 40B3454 8006F6B8 00000000 */   nop
  .Llevel_62_8006F6BC:
    /* 40B3458 8006F6BC 0680023C */  lui        $v0, %hi(D_80067020)
    /* 40B345C 8006F6C0 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 40B3460 8006F6C4 21280000 */  addu       $a1, $zero, $zero
    /* 40B3464 8006F6C8 11004490 */  lbu        $a0, 0x11($v0)
    /* 40B3468 8006F6CC C841010C */  jal        func_80050720
    /* 40B346C 8006F6D0 21300000 */   addu      $a2, $zero, $zero
    /* 40B3470 8006F6D4 00000392 */  lbu        $v1, 0x0($s0)
    /* 40B3474 8006F6D8 21204000 */  addu       $a0, $v0, $zero
    /* 40B3478 8006F6DC 0780013C */  lui        $at, %hi(D_8006A268)
    /* 40B347C 8006F6E0 68A223AC */  sw         $v1, %lo(D_8006A268)($at)
    /* 40B3480 8006F6E4 31008004 */  bltz       $a0, .Llevel_62_8006F7AC
    /* 40B3484 8006F6E8 0A000224 */   addiu     $v0, $zero, 0xA
    /* 40B3488 8006F6EC 1C006210 */  beq        $v1, $v0, .Llevel_62_8006F760
    /* 40B348C 8006F6F0 00000000 */   nop
    /* 40B3490 8006F6F4 EBBD0108 */  j          .Llevel_62_8006F7AC
    /* 40B3494 8006F6F8 00000000 */   nop
  .Llevel_62_8006F6FC:
    /* 40B3498 8006F6FC 0780103C */  lui        $s0, %hi(D_8006A006)
    /* 40B349C 8006F700 06A01026 */  addiu      $s0, $s0, %lo(D_8006A006)
    /* 40B34A0 8006F704 00000392 */  lbu        $v1, 0x0($s0)
    /* 40B34A4 8006F708 01001124 */  addiu      $s1, $zero, 0x1
    /* 40B34A8 8006F70C 03007110 */  beq        $v1, $s1, .Llevel_62_8006F71C
    /* 40B34AC 8006F710 03000224 */   addiu     $v0, $zero, 0x3
    /* 40B34B0 8006F714 25006214 */  bne        $v1, $v0, .Llevel_62_8006F7AC
    /* 40B34B4 8006F718 00000000 */   nop
  .Llevel_62_8006F71C:
    /* 40B34B8 8006F71C 0680023C */  lui        $v0, %hi(D_80067020)
    /* 40B34BC 8006F720 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 40B34C0 8006F724 21280000 */  addu       $a1, $zero, $zero
    /* 40B34C4 8006F728 11004490 */  lbu        $a0, 0x11($v0)
    /* 40B34C8 8006F72C C841010C */  jal        func_80050720
    /* 40B34CC 8006F730 21300000 */   addu      $a2, $zero, $zero
    /* 40B34D0 8006F734 00000392 */  lbu        $v1, 0x0($s0)
    /* 40B34D4 8006F738 21804000 */  addu       $s0, $v0, $zero
    /* 40B34D8 8006F73C 0780013C */  lui        $at, %hi(D_8006A268)
    /* 40B34DC 8006F740 68A223AC */  sw         $v1, %lo(D_8006A268)($at)
    /* 40B34E0 8006F744 19000006 */  bltz       $s0, .Llevel_62_8006F7AC
    /* 40B34E4 8006F748 00000000 */   nop
    /* 40B34E8 8006F74C 17007114 */  bne        $v1, $s1, .Llevel_62_8006F7AC
    /* 40B34EC 8006F750 21200002 */   addu      $a0, $s0, $zero
    /* 40B34F0 8006F754 3D43010C */  jal        func_80050CF4
    /* 40B34F4 8006F758 000C0524 */   addiu     $a1, $zero, 0xC00
    /* 40B34F8 8006F75C 21200002 */  addu       $a0, $s0, $zero
  .Llevel_62_8006F760:
    /* 40B34FC 8006F760 1943010C */  jal        func_80050C64
    /* 40B3500 8006F764 00120524 */   addiu     $a1, $zero, 0x1200
    /* 40B3504 8006F768 EBBD0108 */  j          .Llevel_62_8006F7AC
    /* 40B3508 8006F76C 00000000 */   nop
  .Llevel_62_8006F770:
    /* 40B350C 8006F770 0780103C */  lui        $s0, %hi(D_8006A006)
    /* 40B3510 8006F774 06A01026 */  addiu      $s0, $s0, %lo(D_8006A006)
    /* 40B3514 8006F778 00000392 */  lbu        $v1, 0x0($s0)
    /* 40B3518 8006F77C 0D000224 */  addiu      $v0, $zero, 0xD
    /* 40B351C 8006F780 0A006214 */  bne        $v1, $v0, .Llevel_62_8006F7AC
    /* 40B3520 8006F784 21280000 */   addu      $a1, $zero, $zero
    /* 40B3524 8006F788 0680023C */  lui        $v0, %hi(D_80067020)
    /* 40B3528 8006F78C 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 40B352C 8006F790 00000000 */  nop
    /* 40B3530 8006F794 0D004490 */  lbu        $a0, 0xD($v0)
    /* 40B3534 8006F798 C841010C */  jal        func_80050720
    /* 40B3538 8006F79C 21300000 */   addu      $a2, $zero, $zero
    /* 40B353C 8006F7A0 00000292 */  lbu        $v0, 0x0($s0)
    /* 40B3540 8006F7A4 0780013C */  lui        $at, %hi(D_8006A268)
    /* 40B3544 8006F7A8 68A222AC */  sw         $v0, %lo(D_8006A268)($at)
  .Llevel_62_8006F7AC:
    /* 40B3548 8006F7AC 1800BF8F */  lw         $ra, 0x18($sp)
    /* 40B354C 8006F7B0 1400B18F */  lw         $s1, 0x14($sp)
    /* 40B3550 8006F7B4 1000B08F */  lw         $s0, 0x10($sp)
    /* 40B3554 8006F7B8 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 40B3558 8006F7BC 0800E003 */  jr         $ra
    /* 40B355C 8006F7C0 00000000 */   nop
endlabel func_level_62_8006F5F4
