.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_62_8006D268

dlabel jtbl_level_62_8006D268
    /* 40B1004 8006D268 8CE00680 */ .word .Llevel_62_8006E08C
    /* 40B1008 8006D26C 3CE20680 */ .word .Llevel_62_8006E23C
    /* 40B100C 8006D270 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1010 8006D274 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1014 8006D278 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1018 8006D27C 68F20680 */ .word .Llevel_62_8006F268
    /* 40B101C 8006D280 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1020 8006D284 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1024 8006D288 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1028 8006D28C 68F20680 */ .word .Llevel_62_8006F268
    /* 40B102C 8006D290 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1030 8006D294 3CE00680 */ .word .Llevel_62_8006E03C
    /* 40B1034 8006D298 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1038 8006D29C 68F20680 */ .word .Llevel_62_8006F268
    /* 40B103C 8006D2A0 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1040 8006D2A4 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1044 8006D2A8 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1048 8006D2AC 68F20680 */ .word .Llevel_62_8006F268
    /* 40B104C 8006D2B0 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1050 8006D2B4 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1054 8006D2B8 90E50680 */ .word .Llevel_62_8006E590
    /* 40B1058 8006D2BC 98E40680 */ .word .Llevel_62_8006E498
    /* 40B105C 8006D2C0 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1060 8006D2C4 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1064 8006D2C8 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1068 8006D2CC 84E90680 */ .word .Llevel_62_8006E984
    /* 40B106C 8006D2D0 84E90680 */ .word .Llevel_62_8006E984
    /* 40B1070 8006D2D4 84E90680 */ .word .Llevel_62_8006E984
    /* 40B1074 8006D2D8 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1078 8006D2DC 68F20680 */ .word .Llevel_62_8006F268
    /* 40B107C 8006D2E0 3CE00680 */ .word .Llevel_62_8006E03C
    /* 40B1080 8006D2E4 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1084 8006D2E8 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1088 8006D2EC 68F20680 */ .word .Llevel_62_8006F268
    /* 40B108C 8006D2F0 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1090 8006D2F4 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1094 8006D2F8 68F20680 */ .word .Llevel_62_8006F268
    /* 40B1098 8006D2FC 68F20680 */ .word .Llevel_62_8006F268
    /* 40B109C 8006D300 68F20680 */ .word .Llevel_62_8006F268
    /* 40B10A0 8006D304 BCEF0680 */ .word .Llevel_62_8006EFBC
    /* 40B10A4 8006D308 68F20680 */ .word .Llevel_62_8006F268
    /* 40B10A8 8006D30C 68F20680 */ .word .Llevel_62_8006F268
    /* 40B10AC 8006D310 DCF00680 */ .word .Llevel_62_8006F0DC
    /* 40B10B0 8006D314 DCF00680 */ .word .Llevel_62_8006F0DC
    /* 40B10B4 8006D318 DCF00680 */ .word .Llevel_62_8006F0DC
    /* 40B10B8 8006D31C 68F20680 */ .word .Llevel_62_8006F268
    /* 40B10BC 8006D320 3CE00680 */ .word .Llevel_62_8006E03C
    /* 40B10C0 8006D324 68F20680 */ .word .Llevel_62_8006F268
    /* 40B10C4 8006D328 68F20680 */ .word .Llevel_62_8006F268
    /* 40B10C8 8006D32C 68F20680 */ .word .Llevel_62_8006F268
    /* 40B10CC 8006D330 F0E70680 */ .word .Llevel_62_8006E7F0
    /* 40B10D0 8006D334 00000000 */ .word 0x00000000
enddlabel jtbl_level_62_8006D268


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_62_8006DFD0, 0x12B8

glabel func_level_62_8006DFD0
    /* 40B1D6C 8006DFD0 00110400 */  sll        $v0, $a0, 4
    /* 40B1D70 8006DFD4 0780033C */  lui        $v1, %hi(D_800683B0)
    /* 40B1D74 8006DFD8 B0836324 */  addiu      $v1, $v1, %lo(D_800683B0)
    /* 40B1D78 8006DFDC 21104300 */  addu       $v0, $v0, $v1
    /* 40B1D7C 8006DFE0 0680013C */  lui        $at, %hi(D_80066F38)
    /* 40B1D80 8006DFE4 386F22AC */  sw         $v0, %lo(D_80066F38)($at)
    /* 40B1D84 8006DFE8 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 40B1D88 8006DFEC 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 40B1D8C 8006DFF0 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 40B1D90 8006DFF4 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 40B1D94 8006DFF8 38FFBD27 */  addiu      $sp, $sp, -0xC8
    /* 40B1D98 8006DFFC C000BFAF */  sw         $ra, 0xC0($sp)
    /* 40B1D9C 8006E000 BC00B3AF */  sw         $s3, 0xBC($sp)
    /* 40B1DA0 8006E004 B800B2AF */  sw         $s2, 0xB8($sp)
    /* 40B1DA4 8006E008 B400B1AF */  sw         $s1, 0xB4($sp)
    /* 40B1DA8 8006E00C 21904400 */  addu       $s2, $v0, $a0
    /* 40B1DAC 8006E010 F8FF6324 */  addiu      $v1, $v1, -0x8
    /* 40B1DB0 8006E014 3300622C */  sltiu      $v0, $v1, 0x33
    /* 40B1DB4 8006E018 93044010 */  beqz       $v0, .Llevel_62_8006F268
    /* 40B1DB8 8006E01C B000B0AF */   sw        $s0, 0xB0($sp)
    /* 40B1DBC 8006E020 80100300 */  sll        $v0, $v1, 2
    /* 40B1DC0 8006E024 0780013C */  lui        $at, %hi(jtbl_level_62_8006D268)
    /* 40B1DC4 8006E028 21082200 */  addu       $at, $at, $v0
    /* 40B1DC8 8006E02C 68D2228C */  lw         $v0, %lo(jtbl_level_62_8006D268)($at)
    /* 40B1DCC 8006E030 00000000 */  nop
    /* 40B1DD0 8006E034 08004000 */  jr         $v0
    /* 40B1DD4 8006E038 00000000 */   nop
  .Llevel_62_8006E03C:
    /* 40B1DD8 8006E03C 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 40B1DDC 8006E040 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 40B1DE0 8006E044 686F000C */  jal        func_8001BDA0
    /* 40B1DE4 8006E048 21200002 */   addu      $a0, $s0, $zero
    /* 40B1DE8 8006E04C 686F000C */  jal        func_8001BDA0
    /* 40B1DEC 8006E050 0C000426 */   addiu     $a0, $s0, 0xC
    /* 40B1DF0 8006E054 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 40B1DF4 8006E058 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 40B1DF8 8006E05C 07000224 */  addiu      $v0, $zero, 0x7
    /* 40B1DFC 8006E060 81046210 */  beq        $v1, $v0, .Llevel_62_8006F268
    /* 40B1E00 8006E064 00000000 */   nop
    /* 40B1E04 8006E068 DBAC000C */  jal        func_8002B36C
    /* 40B1E08 8006E06C 00120424 */   addiu     $a0, $zero, 0x1200
    /* 40B1E0C 8006E070 1AAF000C */  jal        func_8002BC68
    /* 40B1E10 8006E074 00000000 */   nop
    /* 40B1E14 8006E078 5A000424 */  addiu      $a0, $zero, 0x5A
    /* 40B1E18 8006E07C C9AE000C */  jal        func_8002BB24
    /* 40B1E1C 8006E080 10000524 */   addiu     $a1, $zero, 0x10
    /* 40B1E20 8006E084 9ABC0108 */  j          .Llevel_62_8006F268
    /* 40B1E24 8006E088 00000000 */   nop
  .Llevel_62_8006E08C:
    /* 40B1E28 8006E08C 0780103C */  lui        $s0, %hi(D_8006A044)
    /* 40B1E2C 8006E090 44A01026 */  addiu      $s0, $s0, %lo(D_8006A044)
    /* 40B1E30 8006E094 0000038E */  lw         $v1, 0x0($s0)
    /* 40B1E34 8006E098 01000224 */  addiu      $v0, $zero, 0x1
    /* 40B1E38 8006E09C 42006214 */  bne        $v1, $v0, .Llevel_62_8006E1A8
    /* 40B1E3C 8006E0A0 1300422A */   slti      $v0, $s2, 0x13
    /* 40B1E40 8006E0A4 DBAC000C */  jal        func_8002B36C
    /* 40B1E44 8006E0A8 800C0424 */   addiu     $a0, $zero, 0xC80
    /* 40B1E48 8006E0AC 28000424 */  addiu      $a0, $zero, 0x28
    /* 40B1E4C 8006E0B0 C9AE000C */  jal        func_8002BB24
    /* 40B1E50 8006E0B4 08000524 */   addiu     $a1, $zero, 0x8
    /* 40B1E54 8006E0B8 40010424 */  addiu      $a0, $zero, 0x140
    /* 40B1E58 8006E0BC 5CAF000C */  jal        func_8002BD70
    /* 40B1E5C 8006E0C0 C0000524 */   addiu     $a1, $zero, 0xC0
    /* 40B1E60 8006E0C4 0780043C */  lui        $a0, %hi(D_8006A09C)
    /* 40B1E64 8006E0C8 9CA0848C */  lw         $a0, %lo(D_8006A09C)($a0)
    /* 40B1E68 8006E0CC 996D000C */  jal        func_8001B664
    /* 40B1E6C 8006E0D0 40001126 */   addiu     $s1, $s0, 0x40
    /* 40B1E70 8006E0D4 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 40B1E74 8006E0D8 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 40B1E78 8006E0DC 00000000 */  nop
    /* 40B1E7C 8006E0E0 18006200 */  mult       $v1, $v0
    /* 40B1E80 8006E0E4 0780043C */  lui        $a0, %hi(D_8006A09C)
    /* 40B1E84 8006E0E8 9CA0848C */  lw         $a0, %lo(D_8006A09C)($a0)
    /* 40B1E88 8006E0EC 12480000 */  mflo       $t1
    /* 40B1E8C 8006E0F0 03130900 */  sra        $v0, $t1, 12
    /* 40B1E90 8006E0F4 876D000C */  jal        func_8001B61C
    /* 40B1E94 8006E0F8 1000A2AF */   sw        $v0, 0x10($sp)
    /* 40B1E98 8006E0FC 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 40B1E9C 8006E100 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 40B1EA0 8006E104 00000000 */  nop
    /* 40B1EA4 8006E108 18006200 */  mult       $v1, $v0
    /* 40B1EA8 8006E10C 1000A427 */  addiu      $a0, $sp, 0x10
    /* 40B1EAC 8006E110 21288000 */  addu       $a1, $a0, $zero
    /* 40B1EB0 8006E114 21302002 */  addu       $a2, $s1, $zero
    /* 40B1EB4 8006E118 12480000 */  mflo       $t1
    /* 40B1EB8 8006E11C 03130900 */  sra        $v0, $t1, 12
    /* 40B1EBC 8006E120 806F000C */  jal        func_8001BE00
    /* 40B1EC0 8006E124 1400A2AF */   sw        $v0, 0x14($sp)
    /* 40B1EC4 8006E128 1000A427 */  addiu      $a0, $sp, 0x10
    /* 40B1EC8 8006E12C 21280000 */  addu       $a1, $zero, $zero
    /* 40B1ECC 8006E130 886E000C */  jal        func_8001BA20
    /* 40B1ED0 8006E134 1800A0AF */   sw        $zero, 0x18($sp)
    /* 40B1ED4 8006E138 21284000 */  addu       $a1, $v0, $zero
    /* 40B1ED8 8006E13C 8102A228 */  slti       $v0, $a1, 0x281
    /* 40B1EDC 8006E140 05004014 */  bnez       $v0, .Llevel_62_8006E158
    /* 40B1EE0 8006E144 34000426 */   addiu     $a0, $s0, 0x34
    /* 40B1EE4 8006E148 1000A427 */  addiu      $a0, $sp, 0x10
    /* 40B1EE8 8006E14C 316F000C */  jal        func_8001BCC4
    /* 40B1EEC 8006E150 80020624 */   addiu     $a2, $zero, 0x280
    /* 40B1EF0 8006E154 34000426 */  addiu      $a0, $s0, 0x34
  .Llevel_62_8006E158:
    /* 40B1EF4 8006E158 21282002 */  addu       $a1, $s1, $zero
    /* 40B1EF8 8006E15C 736F000C */  jal        func_8001BDCC
    /* 40B1EFC 8006E160 1000A627 */   addiu     $a2, $sp, 0x10
    /* 40B1F00 8006E164 0EB0000C */  jal        func_8002C038
    /* 40B1F04 8006E168 00000000 */   nop
    /* 40B1F08 8006E16C 0D00422A */  slti       $v0, $s2, 0xD
    /* 40B1F0C 8006E170 09004010 */  beqz       $v0, .Llevel_62_8006E198
    /* 40B1F10 8006E174 00000000 */   nop
    /* 40B1F14 8006E178 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 40B1F18 8006E17C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 40B1F1C 8006E180 00000000 */  nop
    /* 40B1F20 8006E184 17004224 */  addiu      $v0, $v0, 0x17
    /* 40B1F24 8006E188 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 40B1F28 8006E18C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 40B1F2C 8006E190 9ABC0108 */  j          .Llevel_62_8006F268
    /* 40B1F30 8006E194 00000000 */   nop
  .Llevel_62_8006E198:
    /* 40B1F34 8006E198 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 40B1F38 8006E19C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 40B1F3C 8006E1A0 1DB90108 */  j          .Llevel_62_8006E474
    /* 40B1F40 8006E1A4 40FF4224 */   addiu     $v0, $v0, -0xC0
  .Llevel_62_8006E1A8:
    /* 40B1F44 8006E1A8 1A004014 */  bnez       $v0, .Llevel_62_8006E214
    /* 40B1F48 8006E1AC 40000426 */   addiu     $a0, $s0, 0x40
    /* 40B1F4C 8006E1B0 34000426 */  addiu      $a0, $s0, 0x34
    /* 40B1F50 8006E1B4 0780033C */  lui        $v1, %hi(D_8006A084)
    /* 40B1F54 8006E1B8 84A0638C */  lw         $v1, %lo(D_8006A084)($v1)
    /* 40B1F58 8006E1BC 00000000 */  nop
    /* 40B1F5C 8006E1C0 C0100300 */  sll        $v0, $v1, 3
    /* 40B1F60 8006E1C4 23104300 */  subu       $v0, $v0, $v1
    /* 40B1F64 8006E1C8 0780033C */  lui        $v1, %hi(D_8006A088)
    /* 40B1F68 8006E1CC 88A0638C */  lw         $v1, %lo(D_8006A088)($v1)
    /* 40B1F6C 8006E1D0 40110200 */  sll        $v0, $v0, 5
    /* 40B1F70 8006E1D4 340002AE */  sw         $v0, 0x34($s0)
    /* 40B1F74 8006E1D8 C0100300 */  sll        $v0, $v1, 3
    /* 40B1F78 8006E1DC 23104300 */  subu       $v0, $v0, $v1
    /* 40B1F7C 8006E1E0 0780033C */  lui        $v1, %hi(D_8006A08C)
    /* 40B1F80 8006E1E4 8CA0638C */  lw         $v1, %lo(D_8006A08C)($v1)
    /* 40B1F84 8006E1E8 40110200 */  sll        $v0, $v0, 5
    /* 40B1F88 8006E1EC 0780013C */  lui        $at, %hi(D_8006A07C)
    /* 40B1F8C 8006E1F0 7CA022AC */  sw         $v0, %lo(D_8006A07C)($at)
    /* 40B1F90 8006E1F4 C0100300 */  sll        $v0, $v1, 3
    /* 40B1F94 8006E1F8 23104300 */  subu       $v0, $v0, $v1
    /* 40B1F98 8006E1FC 40110200 */  sll        $v0, $v0, 5
    /* 40B1F9C 8006E200 0780013C */  lui        $at, %hi(D_8006A080)
    /* 40B1FA0 8006E204 80A022AC */  sw         $v0, %lo(D_8006A080)($at)
    /* 40B1FA4 8006E208 526F000C */  jal        func_8001BD48
    /* 40B1FA8 8006E20C 08000524 */   addiu     $a1, $zero, 0x8
    /* 40B1FAC 8006E210 40000426 */  addiu      $a0, $s0, 0x40
  .Llevel_62_8006E214:
    /* 40B1FB0 8006E214 6C6F000C */  jal        func_8001BDB0
    /* 40B1FB4 8006E218 34000526 */   addiu     $a1, $s0, 0x34
    /* 40B1FB8 8006E21C 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 40B1FBC 8006E220 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 40B1FC0 8006E224 00000000 */  nop
    /* 40B1FC4 8006E228 40FF4224 */  addiu      $v0, $v0, -0xC0
    /* 40B1FC8 8006E22C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 40B1FCC 8006E230 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 40B1FD0 8006E234 5EB90108 */  j          .Llevel_62_8006E578
    /* 40B1FD4 8006E238 00DD4228 */   slti      $v0, $v0, -0x2300
  .Llevel_62_8006E23C:
    /* 40B1FD8 8006E23C 0680033C */  lui        $v1, %hi(D_80066F90)
    /* 40B1FDC 8006E240 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* 40B1FE0 8006E244 3E000224 */  addiu      $v0, $zero, 0x3E
    /* 40B1FE4 8006E248 0B006214 */  bne        $v1, $v0, .Llevel_62_8006E278
    /* 40B1FE8 8006E24C 00000000 */   nop
    /* 40B1FEC 8006E250 DBAC000C */  jal        func_8002B36C
    /* 40B1FF0 8006E254 000F0424 */   addiu     $a0, $zero, 0xF00
    /* 40B1FF4 8006E258 000F0224 */  addiu      $v0, $zero, 0xF00
    /* 40B1FF8 8006E25C 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 40B1FFC 8006E260 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 40B2000 8006E264 19000424 */  addiu      $a0, $zero, 0x19
    /* 40B2004 8006E268 C9AE000C */  jal        func_8002BB24
    /* 40B2008 8006E26C 05000524 */   addiu     $a1, $zero, 0x5
    /* 40B200C 8006E270 FAB80108 */  j          .Llevel_62_8006E3E8
    /* 40B2010 8006E274 40010424 */   addiu     $a0, $zero, 0x140
  .Llevel_62_8006E278:
    /* 40B2014 8006E278 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 40B2018 8006E27C 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 40B201C 8006E280 00000000 */  nop
    /* 40B2020 8006E284 16004010 */  beqz       $v0, .Llevel_62_8006E2E0
    /* 40B2024 8006E288 2000A427 */   addiu     $a0, $sp, 0x20
    /* 40B2028 8006E28C 0780023C */  lui        $v0, %hi(D_8006A0F6)
    /* 40B202C 8006E290 F6A04290 */  lbu        $v0, %lo(D_8006A0F6)($v0)
    /* 40B2030 8006E294 00000000 */  nop
    /* 40B2034 8006E298 11004010 */  beqz       $v0, .Llevel_62_8006E2E0
    /* 40B2038 8006E29C 00000000 */   nop
    /* 40B203C 8006E2A0 0780043C */  lui        $a0, %hi(D_8006A0D0)
    /* 40B2040 8006E2A4 D0A0848C */  lw         $a0, %lo(D_8006A0D0)($a0)
    /* 40B2044 8006E2A8 0780053C */  lui        $a1, %hi(D_8006A0D4)
    /* 40B2048 8006E2AC D4A0A58C */  lw         $a1, %lo(D_8006A0D4)($a1)
    /* 40B204C 8006E2B0 2E6D000C */  jal        func_8001B4B8
    /* 40B2050 8006E2B4 21300000 */   addu      $a2, $zero, $zero
    /* 40B2054 8006E2B8 0780033C */  lui        $v1, %hi(D_8006A05C)
    /* 40B2058 8006E2BC 5CA0638C */  lw         $v1, %lo(D_8006A05C)($v1)
    /* 40B205C 8006E2C0 00000000 */  nop
    /* 40B2060 8006E2C4 23104300 */  subu       $v0, $v0, $v1
    /* 40B2064 8006E2C8 FF0F4430 */  andi       $a0, $v0, 0xFFF
    /* 40B2068 8006E2CC 01088228 */  slti       $v0, $a0, 0x801
    /* 40B206C 8006E2D0 0C004014 */  bnez       $v0, .Llevel_62_8006E304
    /* 40B2070 8006E2D4 00000000 */   nop
    /* 40B2074 8006E2D8 C1B80108 */  j          .Llevel_62_8006E304
    /* 40B2078 8006E2DC 00F08424 */   addiu     $a0, $a0, -0x1000
  .Llevel_62_8006E2E0:
    /* 40B207C 8006E2E0 39AD000C */  jal        func_8002B4E4
    /* 40B2080 8006E2E4 01000524 */   addiu     $a1, $zero, 0x1
    /* 40B2084 8006E2E8 2000A38F */  lw         $v1, 0x20($sp)
    /* 40B2088 8006E2EC 00000000 */  nop
    /* 40B208C 8006E2F0 40100300 */  sll        $v0, $v1, 1
    /* 40B2090 8006E2F4 21104300 */  addu       $v0, $v0, $v1
    /* 40B2094 8006E2F8 C0100200 */  sll        $v0, $v0, 3
    /* 40B2098 8006E2FC 21104300 */  addu       $v0, $v0, $v1
    /* 40B209C 8006E300 C3210200 */  sra        $a0, $v0, 7
  .Llevel_62_8006E304:
    /* 40B20A0 8006E304 05008014 */  bnez       $a0, .Llevel_62_8006E31C
    /* 40B20A4 8006E308 00000000 */   nop
    /* 40B20A8 8006E30C 0780013C */  lui        $at, %hi(D_8006A0A0)
    /* 40B20AC 8006E310 A0A020AC */  sw         $zero, %lo(D_8006A0A0)($at)
    /* 40B20B0 8006E314 D8B80108 */  j          .Llevel_62_8006E360
    /* 40B20B4 8006E318 00000000 */   nop
  .Llevel_62_8006E31C:
    /* 40B20B8 8006E31C 09008104 */  bgez       $a0, .Llevel_62_8006E344
    /* 40B20BC 8006E320 00000000 */   nop
    /* 40B20C0 8006E324 0780033C */  lui        $v1, %hi(D_8006A0A0)
    /* 40B20C4 8006E328 A0A06324 */  addiu      $v1, $v1, %lo(D_8006A0A0)
    /* 40B20C8 8006E32C 0000628C */  lw         $v0, 0x0($v1)
    /* 40B20CC 8006E330 00000000 */  nop
    /* 40B20D0 8006E334 0A004018 */  blez       $v0, .Llevel_62_8006E360
    /* 40B20D4 8006E338 00000000 */   nop
    /* 40B20D8 8006E33C D8B80108 */  j          .Llevel_62_8006E360
    /* 40B20DC 8006E340 000060AC */   sw        $zero, 0x0($v1)
  .Llevel_62_8006E344:
    /* 40B20E0 8006E344 0780033C */  lui        $v1, %hi(D_8006A0A0)
    /* 40B20E4 8006E348 A0A06324 */  addiu      $v1, $v1, %lo(D_8006A0A0)
    /* 40B20E8 8006E34C 0000628C */  lw         $v0, 0x0($v1)
    /* 40B20EC 8006E350 00000000 */  nop
    /* 40B20F0 8006E354 02004104 */  bgez       $v0, .Llevel_62_8006E360
    /* 40B20F4 8006E358 00000000 */   nop
    /* 40B20F8 8006E35C 000060AC */  sw         $zero, 0x0($v1)
  .Llevel_62_8006E360:
    /* 40B20FC 8006E360 0780053C */  lui        $a1, %hi(D_8006A0A0)
    /* 40B2100 8006E364 A0A0A524 */  addiu      $a1, $a1, %lo(D_8006A0A0)
    /* 40B2104 8006E368 0000A38C */  lw         $v1, 0x0($a1)
    /* 40B2108 8006E36C 00000000 */  nop
    /* 40B210C 8006E370 2A106400 */  slt        $v0, $v1, $a0
    /* 40B2110 8006E374 04004010 */  beqz       $v0, .Llevel_62_8006E388
    /* 40B2114 8006E378 05006224 */   addiu     $v0, $v1, 0x5
    /* 40B2118 8006E37C 0000A2AC */  sw         $v0, 0x0($a1)
    /* 40B211C 8006E380 E5B80108 */  j          .Llevel_62_8006E394
    /* 40B2120 8006E384 2A108200 */   slt       $v0, $a0, $v0
  .Llevel_62_8006E388:
    /* 40B2124 8006E388 FBFF6224 */  addiu      $v0, $v1, -0x5
    /* 40B2128 8006E38C 0000A2AC */  sw         $v0, 0x0($a1)
    /* 40B212C 8006E390 2A104400 */  slt        $v0, $v0, $a0
  .Llevel_62_8006E394:
    /* 40B2130 8006E394 02004010 */  beqz       $v0, .Llevel_62_8006E3A0
    /* 40B2134 8006E398 00000000 */   nop
    /* 40B2138 8006E39C 0000A4AC */  sw         $a0, 0x0($a1)
  .Llevel_62_8006E3A0:
    /* 40B213C 8006E3A0 0780043C */  lui        $a0, %hi(D_8006A0A0)
    /* 40B2140 8006E3A4 A0A0848C */  lw         $a0, %lo(D_8006A0A0)($a0)
    /* 40B2144 8006E3A8 68AE000C */  jal        func_8002B9A0
    /* 40B2148 8006E3AC 00000000 */   nop
    /* 40B214C 8006E3B0 2400A38F */  lw         $v1, 0x24($sp)
    /* 40B2150 8006E3B4 00000000 */  nop
    /* 40B2154 8006E3B8 04006104 */  bgez       $v1, .Llevel_62_8006E3CC
    /* 40B2158 8006E3BC 00110300 */   sll       $v0, $v1, 4
    /* 40B215C 8006E3C0 23104300 */  subu       $v0, $v0, $v1
    /* 40B2160 8006E3C4 F5B80108 */  j          .Llevel_62_8006E3D4
    /* 40B2164 8006E3C8 C0110200 */   sll       $v0, $v0, 7
  .Llevel_62_8006E3CC:
    /* 40B2168 8006E3CC 23104300 */  subu       $v0, $v0, $v1
    /* 40B216C 8006E3D0 80110200 */  sll        $v0, $v0, 6
  .Llevel_62_8006E3D4:
    /* 40B2170 8006E3D4 C3110200 */  sra        $v0, $v0, 7
    /* 40B2174 8006E3D8 000F4224 */  addiu      $v0, $v0, 0xF00
    /* 40B2178 8006E3DC 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 40B217C 8006E3E0 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 40B2180 8006E3E4 40010424 */  addiu      $a0, $zero, 0x140
  .Llevel_62_8006E3E8:
    /* 40B2184 8006E3E8 5CAF000C */  jal        func_8002BD70
    /* 40B2188 8006E3EC C0000524 */   addiu     $a1, $zero, 0xC0
    /* 40B218C 8006E3F0 0780043C */  lui        $a0, %hi(D_8006A0F9)
    /* 40B2190 8006E3F4 F9A08424 */  addiu      $a0, $a0, %lo(D_8006A0F9)
    /* 40B2194 8006E3F8 00008290 */  lbu        $v0, 0x0($a0)
    /* 40B2198 8006E3FC 00000000 */  nop
    /* 40B219C 8006E400 05004010 */  beqz       $v0, .Llevel_62_8006E418
    /* 40B21A0 8006E404 00000000 */   nop
    /* 40B21A4 8006E408 686F000C */  jal        func_8001BDA0
    /* 40B21A8 8006E40C 8BFF8424 */   addiu     $a0, $a0, -0x75
    /* 40B21AC 8006E410 0AB90108 */  j          .Llevel_62_8006E428
    /* 40B21B0 8006E414 00000000 */   nop
  .Llevel_62_8006E418:
    /* 40B21B4 8006E418 6FAF000C */  jal        func_8002BDBC
    /* 40B21B8 8006E41C 00000000 */   nop
    /* 40B21BC 8006E420 0EB0000C */  jal        func_8002C038
    /* 40B21C0 8006E424 00000000 */   nop
  .Llevel_62_8006E428:
    /* 40B21C4 8006E428 0780103C */  lui        $s0, %hi(D_8006A084)
    /* 40B21C8 8006E42C 84A01026 */  addiu      $s0, $s0, %lo(D_8006A084)
    /* 40B21CC 8006E430 21200002 */  addu       $a0, $s0, $zero
    /* 40B21D0 8006E434 6C6F000C */  jal        func_8001BDB0
    /* 40B21D4 8006E438 F4FF0526 */   addiu     $a1, $s0, -0xC
    /* 40B21D8 8006E43C 0780023C */  lui        $v0, %hi(D_8006A0F4)
    /* 40B21DC 8006E440 F4A04290 */  lbu        $v0, %lo(D_8006A0F4)($v0)
    /* 40B21E0 8006E444 00000000 */  nop
    /* 40B21E4 8006E448 06004014 */  bnez       $v0, .Llevel_62_8006E464
    /* 40B21E8 8006E44C 00000000 */   nop
    /* 40B21EC 8006E450 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 40B21F0 8006E454 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 40B21F4 8006E458 00000000 */  nop
    /* 40B21F8 8006E45C 09004010 */  beqz       $v0, .Llevel_62_8006E484
    /* 40B21FC 8006E460 21200002 */   addu      $a0, $s0, $zero
  .Llevel_62_8006E464:
    /* 40B2200 8006E464 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 40B2204 8006E468 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 40B2208 8006E46C 00000000 */  nop
    /* 40B220C 8006E470 40FF4224 */  addiu      $v0, $v0, -0xC0
  .Llevel_62_8006E474:
    /* 40B2210 8006E474 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 40B2214 8006E478 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 40B2218 8006E47C 9ABC0108 */  j          .Llevel_62_8006F268
    /* 40B221C 8006E480 00000000 */   nop
  .Llevel_62_8006E484:
    /* 40B2220 8006E484 21288000 */  addu       $a1, $a0, $zero
    /* 40B2224 8006E488 736F000C */  jal        func_8001BDCC
    /* 40B2228 8006E48C 5C008624 */   addiu     $a2, $a0, 0x5C
    /* 40B222C 8006E490 9ABC0108 */  j          .Llevel_62_8006F268
    /* 40B2230 8006E494 00000000 */   nop
  .Llevel_62_8006E498:
    /* 40B2234 8006E498 2800B027 */  addiu      $s0, $sp, 0x28
    /* 40B2238 8006E49C 686F000C */  jal        func_8001BDA0
    /* 40B223C 8006E4A0 21200002 */   addu      $a0, $s0, $zero
    /* 40B2240 8006E4A4 21200002 */  addu       $a0, $s0, $zero
    /* 40B2244 8006E4A8 21280002 */  addu       $a1, $s0, $zero
    /* 40B2248 8006E4AC 0780113C */  lui        $s1, %hi(D_8006A084)
    /* 40B224C 8006E4B0 84A03126 */  addiu      $s1, $s1, %lo(D_8006A084)
    /* 40B2250 8006E4B4 806F000C */  jal        func_8001BE00
    /* 40B2254 8006E4B8 21302002 */   addu      $a2, $s1, $zero
    /* 40B2258 8006E4BC 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 40B225C 8006E4C0 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 40B2260 8006E4C4 00000000 */  nop
    /* 40B2264 8006E4C8 11004010 */  beqz       $v0, .Llevel_62_8006E510
    /* 40B2268 8006E4CC 21200002 */   addu      $a0, $s0, $zero
    /* 40B226C 8006E4D0 3000A0AF */  sw         $zero, 0x30($sp)
    /* 40B2270 8006E4D4 886E000C */  jal        func_8001BA20
    /* 40B2274 8006E4D8 21280000 */   addu      $a1, $zero, $zero
    /* 40B2278 8006E4DC 21284000 */  addu       $a1, $v0, $zero
    /* 40B227C 8006E4E0 4100A228 */  slti       $v0, $a1, 0x41
    /* 40B2280 8006E4E4 05004014 */  bnez       $v0, .Llevel_62_8006E4FC
    /* 40B2284 8006E4E8 40FF0224 */   addiu     $v0, $zero, -0xC0
    /* 40B2288 8006E4EC 21200002 */  addu       $a0, $s0, $zero
    /* 40B228C 8006E4F0 316F000C */  jal        func_8001BCC4
    /* 40B2290 8006E4F4 40000624 */   addiu     $a2, $zero, 0x40
    /* 40B2294 8006E4F8 40FF0224 */  addiu      $v0, $zero, -0xC0
  .Llevel_62_8006E4FC:
    /* 40B2298 8006E4FC 3000A2AF */  sw         $v0, 0x30($sp)
    /* 40B229C 8006E500 F4FF2426 */  addiu      $a0, $s1, -0xC
    /* 40B22A0 8006E504 21282002 */  addu       $a1, $s1, $zero
    /* 40B22A4 8006E508 54B90108 */  j          .Llevel_62_8006E550
    /* 40B22A8 8006E50C 21300002 */   addu      $a2, $s0, $zero
  .Llevel_62_8006E510:
    /* 40B22AC 8006E510 886E000C */  jal        func_8001BA20
    /* 40B22B0 8006E514 01000524 */   addiu     $a1, $zero, 0x1
    /* 40B22B4 8006E518 21284000 */  addu       $a1, $v0, $zero
    /* 40B22B8 8006E51C 0101A228 */  slti       $v0, $a1, 0x101
    /* 40B22BC 8006E520 05004014 */  bnez       $v0, .Llevel_62_8006E538
    /* 40B22C0 8006E524 21202002 */   addu      $a0, $s1, $zero
    /* 40B22C4 8006E528 21200002 */  addu       $a0, $s0, $zero
    /* 40B22C8 8006E52C 316F000C */  jal        func_8001BCC4
    /* 40B22CC 8006E530 00010624 */   addiu     $a2, $zero, 0x100
    /* 40B22D0 8006E534 21202002 */  addu       $a0, $s1, $zero
  .Llevel_62_8006E538:
    /* 40B22D4 8006E538 21282002 */  addu       $a1, $s1, $zero
    /* 40B22D8 8006E53C 736F000C */  jal        func_8001BDCC
    /* 40B22DC 8006E540 21300002 */   addu      $a2, $s0, $zero
    /* 40B22E0 8006E544 F4FF2426 */  addiu      $a0, $s1, -0xC
    /* 40B22E4 8006E548 21282002 */  addu       $a1, $s1, $zero
    /* 40B22E8 8006E54C 5C00A624 */  addiu      $a2, $a1, 0x5C
  .Llevel_62_8006E550:
    /* 40B22EC 8006E550 736F000C */  jal        func_8001BDCC
    /* 40B22F0 8006E554 00000000 */   nop
    /* 40B22F4 8006E558 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 40B22F8 8006E55C 84A08424 */  addiu      $a0, $a0, %lo(D_8006A084)
    /* 40B22FC 8006E560 6C6F000C */  jal        func_8001BDB0
    /* 40B2300 8006E564 21288000 */   addu      $a1, $a0, $zero
    /* 40B2304 8006E568 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 40B2308 8006E56C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 40B230C 8006E570 00000000 */  nop
    /* 40B2310 8006E574 00DD4228 */  slti       $v0, $v0, -0x2300
  .Llevel_62_8006E578:
    /* 40B2314 8006E578 3B034010 */  beqz       $v0, .Llevel_62_8006F268
    /* 40B2318 8006E57C 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 40B231C 8006E580 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 40B2320 8006E584 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 40B2324 8006E588 9ABC0108 */  j          .Llevel_62_8006F268
    /* 40B2328 8006E58C 00000000 */   nop
  .Llevel_62_8006E590:
    /* 40B232C 8006E590 DBAC000C */  jal        func_8002B36C
    /* 40B2330 8006E594 800C0424 */   addiu     $a0, $zero, 0xC80
    /* 40B2334 8006E598 28000424 */  addiu      $a0, $zero, 0x28
    /* 40B2338 8006E59C C9AE000C */  jal        func_8002BB24
    /* 40B233C 8006E5A0 08000524 */   addiu     $a1, $zero, 0x8
    /* 40B2340 8006E5A4 40010424 */  addiu      $a0, $zero, 0x140
    /* 40B2344 8006E5A8 5CAF000C */  jal        func_8002BD70
    /* 40B2348 8006E5AC C0000524 */   addiu     $a1, $zero, 0xC0
    /* 40B234C 8006E5B0 0780113C */  lui        $s1, %hi(D_8006A09C)
    /* 40B2350 8006E5B4 9CA03126 */  addiu      $s1, $s1, %lo(D_8006A09C)
    /* 40B2354 8006E5B8 0000248E */  lw         $a0, 0x0($s1)
    /* 40B2358 8006E5BC 996D000C */  jal        func_8001B664
    /* 40B235C 8006E5C0 E8FF3326 */   addiu     $s3, $s1, -0x18
    /* 40B2360 8006E5C4 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 40B2364 8006E5C8 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 40B2368 8006E5CC 00000000 */  nop
    /* 40B236C 8006E5D0 18006200 */  mult       $v1, $v0
    /* 40B2370 8006E5D4 0000248E */  lw         $a0, 0x0($s1)
    /* 40B2374 8006E5D8 12480000 */  mflo       $t1
    /* 40B2378 8006E5DC 03130900 */  sra        $v0, $t1, 12
    /* 40B237C 8006E5E0 876D000C */  jal        func_8001B61C
    /* 40B2380 8006E5E4 3800A2AF */   sw        $v0, 0x38($sp)
    /* 40B2384 8006E5E8 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 40B2388 8006E5EC A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 40B238C 8006E5F0 00000000 */  nop
    /* 40B2390 8006E5F4 18006200 */  mult       $v1, $v0
    /* 40B2394 8006E5F8 3800B027 */  addiu      $s0, $sp, 0x38
    /* 40B2398 8006E5FC 21200002 */  addu       $a0, $s0, $zero
    /* 40B239C 8006E600 21280002 */  addu       $a1, $s0, $zero
    /* 40B23A0 8006E604 21306002 */  addu       $a2, $s3, $zero
    /* 40B23A4 8006E608 12480000 */  mflo       $t1
    /* 40B23A8 8006E60C 03130900 */  sra        $v0, $t1, 12
    /* 40B23AC 8006E610 806F000C */  jal        func_8001BE00
    /* 40B23B0 8006E614 3C00A2AF */   sw        $v0, 0x3C($sp)
    /* 40B23B4 8006E618 21200002 */  addu       $a0, $s0, $zero
    /* 40B23B8 8006E61C 21280000 */  addu       $a1, $zero, $zero
    /* 40B23BC 8006E620 886E000C */  jal        func_8001BA20
    /* 40B23C0 8006E624 4000A0AF */   sw        $zero, 0x40($sp)
    /* 40B23C4 8006E628 21284000 */  addu       $a1, $v0, $zero
    /* 40B23C8 8006E62C 8102A228 */  slti       $v0, $a1, 0x281
    /* 40B23CC 8006E630 05004014 */  bnez       $v0, .Llevel_62_8006E648
    /* 40B23D0 8006E634 DCFF2426 */   addiu     $a0, $s1, -0x24
    /* 40B23D4 8006E638 21200002 */  addu       $a0, $s0, $zero
    /* 40B23D8 8006E63C 316F000C */  jal        func_8001BCC4
    /* 40B23DC 8006E640 80020624 */   addiu     $a2, $zero, 0x280
    /* 40B23E0 8006E644 DCFF2426 */  addiu      $a0, $s1, -0x24
  .Llevel_62_8006E648:
    /* 40B23E4 8006E648 21286002 */  addu       $a1, $s3, $zero
    /* 40B23E8 8006E64C 736F000C */  jal        func_8001BDCC
    /* 40B23EC 8006E650 21300002 */   addu      $a2, $s0, $zero
    /* 40B23F0 8006E654 0EB0000C */  jal        func_8002C038
    /* 40B23F4 8006E658 00000000 */   nop
    /* 40B23F8 8006E65C 0D00422A */  slti       $v0, $s2, 0xD
    /* 40B23FC 8006E660 05004010 */  beqz       $v0, .Llevel_62_8006E678
    /* 40B2400 8006E664 00000000 */   nop
    /* 40B2404 8006E668 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 40B2408 8006E66C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 40B240C 8006E670 A2B90108 */  j          .Llevel_62_8006E688
    /* 40B2410 8006E674 17004224 */   addiu     $v0, $v0, 0x17
  .Llevel_62_8006E678:
    /* 40B2414 8006E678 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 40B2418 8006E67C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 40B241C 8006E680 00000000 */  nop
    /* 40B2420 8006E684 40FF4224 */  addiu      $v0, $v0, -0xC0
  .Llevel_62_8006E688:
    /* 40B2424 8006E688 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 40B2428 8006E68C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 40B242C 8006E690 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 40B2430 8006E694 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 40B2434 8006E698 00000000 */  nop
    /* 40B2438 8006E69C F2024010 */  beqz       $v0, .Llevel_62_8006F268
    /* 40B243C 8006E6A0 21880000 */   addu      $s1, $zero, $zero
    /* 40B2440 8006E6A4 80101200 */  sll        $v0, $s2, 2
    /* 40B2444 8006E6A8 21985200 */  addu       $s3, $v0, $s2
    /* 40B2448 8006E6AC 0780123C */  lui        $s2, %hi(D_80069FFE)
    /* 40B244C 8006E6B0 FE9F5226 */  addiu      $s2, $s2, %lo(D_80069FFE)
    /* 40B2450 8006E6B4 5800B027 */  addiu      $s0, $sp, 0x58
  .Llevel_62_8006E6B8:
    /* 40B2454 8006E6B8 4B67010C */  jal        func_80059D2C
    /* 40B2458 8006E6BC 00000000 */   nop
    /* 40B245C 8006E6C0 FF004230 */  andi       $v0, $v0, 0xFF
    /* 40B2460 8006E6C4 2A106202 */  slt        $v0, $s3, $v0
    /* 40B2464 8006E6C8 43004010 */  beqz       $v0, .Llevel_62_8006E7D8
    /* 40B2468 8006E6CC 21200000 */   addu      $a0, $zero, $zero
    /* 40B246C 8006E6D0 63E2000C */  jal        func_8003898C
    /* 40B2470 8006E6D4 0C000524 */   addiu     $a1, $zero, 0xC
    /* 40B2474 8006E6D8 22004426 */  addiu      $a0, $s2, 0x22
    /* 40B2478 8006E6DC 00004392 */  lbu        $v1, 0x0($s2)
    /* 40B247C 8006E6E0 21280002 */  addu       $a1, $s0, $zero
    /* 40B2480 8006E6E4 80006324 */  addiu      $v1, $v1, 0x80
    /* 40B2484 8006E6E8 21186200 */  addu       $v1, $v1, $v0
    /* 40B2488 8006E6EC FF006330 */  andi       $v1, $v1, 0xFF
    /* 40B248C 8006E6F0 40180300 */  sll        $v1, $v1, 1
    /* 40B2490 8006E6F4 0680013C */  lui        $at, %hi(D_80061C58)
    /* 40B2494 8006E6F8 21082300 */  addu       $at, $at, $v1
    /* 40B2498 8006E6FC 581C2784 */  lh         $a3, %lo(D_80061C58)($at)
    /* 40B249C 8006E700 21300002 */  addu       $a2, $s0, $zero
    /* 40B24A0 8006E704 80100700 */  sll        $v0, $a3, 2
    /* 40B24A4 8006E708 21104700 */  addu       $v0, $v0, $a3
    /* 40B24A8 8006E70C 83120200 */  sra        $v0, $v0, 10
    /* 40B24AC 8006E710 4800A2AF */  sw         $v0, 0x48($sp)
    /* 40B24B0 8006E714 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 40B24B4 8006E718 21082300 */  addu       $at, $at, $v1
    /* 40B24B8 8006E71C D81B2384 */  lh         $v1, %lo(D_80061BD8)($at)
    /* 40B24BC 8006E720 0E000224 */  addiu      $v0, $zero, 0xE
    /* 40B24C0 8006E724 5000A2AF */  sw         $v0, 0x50($sp)
    /* 40B24C4 8006E728 D4FE0224 */  addiu      $v0, $zero, -0x12C
    /* 40B24C8 8006E72C 5800A2AF */  sw         $v0, 0x58($sp)
    /* 40B24CC 8006E730 38FF0224 */  addiu      $v0, $zero, -0xC8
    /* 40B24D0 8006E734 5C00A0AF */  sw         $zero, 0x5C($sp)
    /* 40B24D4 8006E738 6000A2AF */  sw         $v0, 0x60($sp)
    /* 40B24D8 8006E73C 80100300 */  sll        $v0, $v1, 2
    /* 40B24DC 8006E740 21104300 */  addu       $v0, $v0, $v1
    /* 40B24E0 8006E744 83120200 */  sra        $v0, $v0, 10
    /* 40B24E4 8006E748 696E000C */  jal        func_8001B9A4
    /* 40B24E8 8006E74C 4C00A2AF */   sw        $v0, 0x4C($sp)
    /* 40B24EC 8006E750 21200000 */  addu       $a0, $zero, $zero
    /* 40B24F0 8006E754 63E2000C */  jal        func_8003898C
    /* 40B24F4 8006E758 50000524 */   addiu     $a1, $zero, 0x50
    /* 40B24F8 8006E75C 21200000 */  addu       $a0, $zero, $zero
    /* 40B24FC 8006E760 5800A38F */  lw         $v1, 0x58($sp)
    /* 40B2500 8006E764 50000524 */  addiu      $a1, $zero, 0x50
    /* 40B2504 8006E768 21186200 */  addu       $v1, $v1, $v0
    /* 40B2508 8006E76C 63E2000C */  jal        func_8003898C
    /* 40B250C 8006E770 5800A3AF */   sw        $v1, 0x58($sp)
    /* 40B2510 8006E774 21200000 */  addu       $a0, $zero, $zero
    /* 40B2514 8006E778 5C00A38F */  lw         $v1, 0x5C($sp)
    /* 40B2518 8006E77C 50000524 */  addiu      $a1, $zero, 0x50
    /* 40B251C 8006E780 21186200 */  addu       $v1, $v1, $v0
    /* 40B2520 8006E784 63E2000C */  jal        func_8003898C
    /* 40B2524 8006E788 5C00A3AF */   sw        $v1, 0x5C($sp)
    /* 40B2528 8006E78C 21200002 */  addu       $a0, $s0, $zero
    /* 40B252C 8006E790 21280002 */  addu       $a1, $s0, $zero
    /* 40B2530 8006E794 6000A38F */  lw         $v1, 0x60($sp)
    /* 40B2534 8006E798 F2FF4626 */  addiu      $a2, $s2, -0xE
    /* 40B2538 8006E79C 21186200 */  addu       $v1, $v1, $v0
    /* 40B253C 8006E7A0 736F000C */  jal        func_8001BDCC
    /* 40B2540 8006E7A4 6000A3AF */   sw        $v1, 0x60($sp)
    /* 40B2544 8006E7A8 01000424 */  addiu      $a0, $zero, 0x1
    /* 40B2548 8006E7AC 0D000524 */  addiu      $a1, $zero, 0xD
    /* 40B254C 8006E7B0 21300002 */  addu       $a2, $s0, $zero
    /* 40B2550 8006E7B4 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 40B2554 8006E7B8 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 40B2558 8006E7BC 00000000 */  nop
    /* 40B255C 8006E7C0 09F84000 */  jalr       $v0
    /* 40B2560 8006E7C4 4800A727 */   addiu     $a3, $sp, 0x48
    /* 40B2564 8006E7C8 08000324 */  addiu      $v1, $zero, 0x8
    /* 40B2568 8006E7CC 020043A0 */  sb         $v1, 0x2($v0)
    /* 40B256C 8006E7D0 20000324 */  addiu      $v1, $zero, 0x20
    /* 40B2570 8006E7D4 0A0043A0 */  sb         $v1, 0xA($v0)
  .Llevel_62_8006E7D8:
    /* 40B2574 8006E7D8 01003126 */  addiu      $s1, $s1, 0x1
    /* 40B2578 8006E7DC 0200222A */  slti       $v0, $s1, 0x2
    /* 40B257C 8006E7E0 A1024010 */  beqz       $v0, .Llevel_62_8006F268
    /* 40B2580 8006E7E4 00000000 */   nop
    /* 40B2584 8006E7E8 AEB90108 */  j          .Llevel_62_8006E6B8
    /* 40B2588 8006E7EC 00000000 */   nop
  .Llevel_62_8006E7F0:
    /* 40B258C 8006E7F0 0780103C */  lui        $s0, %hi(D_8006A0B0)
    /* 40B2590 8006E7F4 B0A01026 */  addiu      $s0, $s0, %lo(D_8006A0B0)
    /* 40B2594 8006E7F8 0000028E */  lw         $v0, 0x0($s0)
    /* 40B2598 8006E7FC 00000000 */  nop
    /* 40B259C 8006E800 1F004010 */  beqz       $v0, .Llevel_62_8006E880
    /* 40B25A0 8006E804 4800B127 */   addiu     $s1, $sp, 0x48
    /* 40B25A4 8006E808 686F000C */  jal        func_8001BDA0
    /* 40B25A8 8006E80C 21202002 */   addu      $a0, $s1, $zero
    /* 40B25AC 8006E810 21202002 */  addu       $a0, $s1, $zero
    /* 40B25B0 8006E814 21282002 */  addu       $a1, $s1, $zero
    /* 40B25B4 8006E818 D4FF1226 */  addiu      $s2, $s0, -0x2C
    /* 40B25B8 8006E81C 806F000C */  jal        func_8001BE00
    /* 40B25BC 8006E820 21304002 */   addu      $a2, $s2, $zero
    /* 40B25C0 8006E824 5000A0AF */  sw         $zero, 0x50($sp)
    /* 40B25C4 8006E828 21202002 */  addu       $a0, $s1, $zero
    /* 40B25C8 8006E82C 886E000C */  jal        func_8001BA20
    /* 40B25CC 8006E830 21280000 */   addu      $a1, $zero, $zero
    /* 40B25D0 8006E834 21284000 */  addu       $a1, $v0, $zero
    /* 40B25D4 8006E838 4100A228 */  slti       $v0, $a1, 0x41
    /* 40B25D8 8006E83C 05004014 */  bnez       $v0, .Llevel_62_8006E854
    /* 40B25DC 8006E840 40FF0224 */   addiu     $v0, $zero, -0xC0
    /* 40B25E0 8006E844 21202002 */  addu       $a0, $s1, $zero
    /* 40B25E4 8006E848 316F000C */  jal        func_8001BCC4
    /* 40B25E8 8006E84C 40000624 */   addiu     $a2, $zero, 0x40
    /* 40B25EC 8006E850 40FF0224 */  addiu      $v0, $zero, -0xC0
  .Llevel_62_8006E854:
    /* 40B25F0 8006E854 5000A2AF */  sw         $v0, 0x50($sp)
    /* 40B25F4 8006E858 C8FF1026 */  addiu      $s0, $s0, -0x38
    /* 40B25F8 8006E85C 21200002 */  addu       $a0, $s0, $zero
    /* 40B25FC 8006E860 21284002 */  addu       $a1, $s2, $zero
    /* 40B2600 8006E864 736F000C */  jal        func_8001BDCC
    /* 40B2604 8006E868 21302002 */   addu      $a2, $s1, $zero
    /* 40B2608 8006E86C 21204002 */  addu       $a0, $s2, $zero
    /* 40B260C 8006E870 6C6F000C */  jal        func_8001BDB0
    /* 40B2610 8006E874 21280002 */   addu      $a1, $s0, $zero
    /* 40B2614 8006E878 24BA0108 */  j          .Llevel_62_8006E890
    /* 40B2618 8006E87C 00000000 */   nop
  .Llevel_62_8006E880:
    /* 40B261C 8006E880 686F000C */  jal        func_8001BDA0
    /* 40B2620 8006E884 C8FF0426 */   addiu     $a0, $s0, -0x38
    /* 40B2624 8006E888 686F000C */  jal        func_8001BDA0
    /* 40B2628 8006E88C D4FF0426 */   addiu     $a0, $s0, -0x2C
  .Llevel_62_8006E890:
    /* 40B262C 8006E890 0780053C */  lui        $a1, %hi(D_8006A08C)
    /* 40B2630 8006E894 8CA0A524 */  addiu      $a1, $a1, %lo(D_8006A08C)
    /* 40B2634 8006E898 0000A28C */  lw         $v0, 0x0($a1)
    /* 40B2638 8006E89C 00000000 */  nop
    /* 40B263C 8006E8A0 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 40B2640 8006E8A4 02004010 */  beqz       $v0, .Llevel_62_8006E8B0
    /* 40B2644 8006E8A8 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 40B2648 8006E8AC 0000A2AC */  sw         $v0, 0x0($a1)
  .Llevel_62_8006E8B0:
    /* 40B264C 8006E8B0 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 40B2650 8006E8B4 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 40B2654 8006E8B8 3A000224 */  addiu      $v0, $zero, 0x3A
    /* 40B2658 8006E8BC 6A026214 */  bne        $v1, $v0, .Llevel_62_8006F268
    /* 40B265C 8006E8C0 00000000 */   nop
    /* 40B2660 8006E8C4 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 40B2664 8006E8C8 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 40B2668 8006E8CC 00000000 */  nop
    /* 40B266C 8006E8D0 65024010 */  beqz       $v0, .Llevel_62_8006F268
    /* 40B2670 8006E8D4 00000000 */   nop
    /* 40B2674 8006E8D8 0680023C */  lui        $v0, %hi(D_80067008)
    /* 40B2678 8006E8DC 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 40B267C 8006E8E0 00000000 */  nop
    /* 40B2680 8006E8E4 01004230 */  andi       $v0, $v0, 0x1
    /* 40B2684 8006E8E8 5F024010 */  beqz       $v0, .Llevel_62_8006F268
    /* 40B2688 8006E8EC 7800B027 */   addiu     $s0, $sp, 0x78
    /* 40B268C 8006E8F0 21200002 */  addu       $a0, $s0, $zero
    /* 40B2690 8006E8F4 64FFA524 */  addiu      $a1, $a1, -0x9C
    /* 40B2694 8006E8F8 0E000224 */  addiu      $v0, $zero, 0xE
    /* 40B2698 8006E8FC 6800A0AF */  sw         $zero, 0x68($sp)
    /* 40B269C 8006E900 6C00A0AF */  sw         $zero, 0x6C($sp)
    /* 40B26A0 8006E904 6C6F000C */  jal        func_8001BDB0
    /* 40B26A4 8006E908 7000A2AF */   sw        $v0, 0x70($sp)
    /* 40B26A8 8006E90C 21200000 */  addu       $a0, $zero, $zero
    /* 40B26AC 8006E910 63E2000C */  jal        func_8003898C
    /* 40B26B0 8006E914 2C010524 */   addiu     $a1, $zero, 0x12C
    /* 40B26B4 8006E918 21200000 */  addu       $a0, $zero, $zero
    /* 40B26B8 8006E91C 7800A38F */  lw         $v1, 0x78($sp)
    /* 40B26BC 8006E920 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 40B26C0 8006E924 21186200 */  addu       $v1, $v1, $v0
    /* 40B26C4 8006E928 63E2000C */  jal        func_8003898C
    /* 40B26C8 8006E92C 7800A3AF */   sw        $v1, 0x78($sp)
    /* 40B26CC 8006E930 21200000 */  addu       $a0, $zero, $zero
    /* 40B26D0 8006E934 7C00A38F */  lw         $v1, 0x7C($sp)
    /* 40B26D4 8006E938 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 40B26D8 8006E93C 21186200 */  addu       $v1, $v1, $v0
    /* 40B26DC 8006E940 63E2000C */  jal        func_8003898C
    /* 40B26E0 8006E944 7C00A3AF */   sw        $v1, 0x7C($sp)
    /* 40B26E4 8006E948 01000424 */  addiu      $a0, $zero, 0x1
    /* 40B26E8 8006E94C 0D000524 */  addiu      $a1, $zero, 0xD
    /* 40B26EC 8006E950 21300002 */  addu       $a2, $s0, $zero
    /* 40B26F0 8006E954 6800A727 */  addiu      $a3, $sp, 0x68
    /* 40B26F4 8006E958 8000A38F */  lw         $v1, 0x80($sp)
    /* 40B26F8 8006E95C 0680083C */  lui        $t0, %hi(D_800670FC)
    /* 40B26FC 8006E960 FC70088D */  lw         $t0, %lo(D_800670FC)($t0)
    /* 40B2700 8006E964 21186200 */  addu       $v1, $v1, $v0
    /* 40B2704 8006E968 09F80001 */  jalr       $t0
    /* 40B2708 8006E96C 8000A3AF */   sw        $v1, 0x80($sp)
    /* 40B270C 8006E970 06000324 */  addiu      $v1, $zero, 0x6
    /* 40B2710 8006E974 020043A0 */  sb         $v1, 0x2($v0)
    /* 40B2714 8006E978 20000324 */  addiu      $v1, $zero, 0x20
    /* 40B2718 8006E97C 9ABC0108 */  j          .Llevel_62_8006F268
    /* 40B271C 8006E980 0A0043A0 */   sb        $v1, 0xA($v0)
  .Llevel_62_8006E984:
    /* 40B2720 8006E984 2000A427 */  addiu      $a0, $sp, 0x20
    /* 40B2724 8006E988 0780113C */  lui        $s1, %hi(D_8006A144)
    /* 40B2728 8006E98C 44A13126 */  addiu      $s1, $s1, %lo(D_8006A144)
    /* 40B272C 8006E990 21282002 */  addu       $a1, $s1, $zero
    /* 40B2730 8006E994 A5AD000C */  jal        func_8002B694
    /* 40B2734 8006E998 21300000 */   addu      $a2, $zero, $zero
    /* 40B2738 8006E99C 2400A28F */  lw         $v0, 0x24($sp)
    /* 40B273C 8006E9A0 0780043C */  lui        $a0, %hi(D_8006A08C)
    /* 40B2740 8006E9A4 8CA0848C */  lw         $a0, %lo(D_8006A08C)($a0)
    /* 40B2744 8006E9A8 23100200 */  negu       $v0, $v0
    /* 40B2748 8006E9AC 80180200 */  sll        $v1, $v0, 2
    /* 40B274C 8006E9B0 21186200 */  addu       $v1, $v1, $v0
    /* 40B2750 8006E9B4 80180300 */  sll        $v1, $v1, 2
    /* 40B2754 8006E9B8 C3910300 */  sra        $s2, $v1, 7
    /* 40B2758 8006E9BC C3200400 */  sra        $a0, $a0, 3
    /* 40B275C 8006E9C0 2000A38F */  lw         $v1, 0x20($sp)
    /* 40B2760 8006E9C4 00FC8424 */  addiu      $a0, $a0, -0x400
    /* 40B2764 8006E9C8 7000A4AF */  sw         $a0, 0x70($sp)
    /* 40B2768 8006E9CC 80100300 */  sll        $v0, $v1, 2
    /* 40B276C 8006E9D0 21104300 */  addu       $v0, $v0, $v1
    /* 40B2770 8006E9D4 80100200 */  sll        $v0, $v0, 2
    /* 40B2774 8006E9D8 24008104 */  bgez       $a0, .Llevel_62_8006EA6C
    /* 40B2778 8006E9DC C3990200 */   sra       $s3, $v0, 7
    /* 40B277C 8006E9E0 6800B027 */  addiu      $s0, $sp, 0x68
    /* 40B2780 8006E9E4 21200002 */  addu       $a0, $s0, $zero
    /* 40B2784 8006E9E8 21280002 */  addu       $a1, $s0, $zero
    /* 40B2788 8006E9EC ACFE3126 */  addiu      $s1, $s1, -0x154
    /* 40B278C 8006E9F0 21302002 */  addu       $a2, $s1, $zero
    /* 40B2790 8006E9F4 0780023C */  lui        $v0, %hi(D_8006A084)
    /* 40B2794 8006E9F8 84A0428C */  lw         $v0, %lo(D_8006A084)($v0)
    /* 40B2798 8006E9FC 0780033C */  lui        $v1, %hi(D_8006A088)
    /* 40B279C 8006EA00 88A0638C */  lw         $v1, %lo(D_8006A088)($v1)
    /* 40B27A0 8006EA04 C3100200 */  sra        $v0, $v0, 3
    /* 40B27A4 8006EA08 C3180300 */  sra        $v1, $v1, 3
    /* 40B27A8 8006EA0C 6800A2AF */  sw         $v0, 0x68($sp)
    /* 40B27AC 8006EA10 736F000C */  jal        func_8001BDCC
    /* 40B27B0 8006EA14 6C00A3AF */   sw        $v1, 0x6C($sp)
    /* 40B27B4 8006EA18 21202002 */  addu       $a0, $s1, $zero
    /* 40B27B8 8006EA1C 21280002 */  addu       $a1, $s0, $zero
    /* 40B27BC 8006EA20 867D000C */  jal        func_8001F618
    /* 40B27C0 8006EA24 02000624 */   addiu     $a2, $zero, 0x2
    /* 40B27C4 8006EA28 11004014 */  bnez       $v0, .Llevel_62_8006EA70
    /* 40B27C8 8006EA2C 19000224 */   addiu     $v0, $zero, 0x19
    /* 40B27CC 8006EA30 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 40B27D0 8006EA34 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 40B27D4 8006EA38 0780033C */  lui        $v1, %hi(D_8006AB78)
    /* 40B27D8 8006EA3C 78AB638C */  lw         $v1, %lo(D_8006AB78)($v1)
    /* 40B27DC 8006EA40 00000000 */  nop
    /* 40B27E0 8006EA44 23104300 */  subu       $v0, $v0, $v1
    /* 40B27E4 8006EA48 C3100200 */  sra        $v0, $v0, 3
    /* 40B27E8 8006EA4C 2400A2AF */  sw         $v0, 0x24($sp)
    /* 40B27EC 8006EA50 0B004228 */  slti       $v0, $v0, 0xB
    /* 40B27F0 8006EA54 02004014 */  bnez       $v0, .Llevel_62_8006EA60
    /* 40B27F4 8006EA58 0A000224 */   addiu     $v0, $zero, 0xA
    /* 40B27F8 8006EA5C 2400A2AF */  sw         $v0, 0x24($sp)
  .Llevel_62_8006EA60:
    /* 40B27FC 8006EA60 2400A28F */  lw         $v0, 0x24($sp)
    /* 40B2800 8006EA64 00000000 */  nop
    /* 40B2804 8006EA68 21904202 */  addu       $s2, $s2, $v0
  .Llevel_62_8006EA6C:
    /* 40B2808 8006EA6C 19000224 */  addiu      $v0, $zero, 0x19
  .Llevel_62_8006EA70:
    /* 40B280C 8006EA70 0680033C */  lui        $v1, %hi(D_80066F90)
    /* 40B2810 8006EA74 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* 40B2814 8006EA78 0780043C */  lui        $a0, %hi(D_8006A0F0)
    /* 40B2818 8006EA7C F0A0848C */  lw         $a0, %lo(D_8006A0F0)($a0)
    /* 40B281C 8006EA80 07006214 */  bne        $v1, $v0, .Llevel_62_8006EAA0
    /* 40B2820 8006EA84 00000000 */   nop
    /* 40B2824 8006EA88 0780023C */  lui        $v0, %hi(D_8006ABF8)
    /* 40B2828 8006EA8C F8AB4290 */  lbu        $v0, %lo(D_8006ABF8)($v0)
    /* 40B282C 8006EA90 00000000 */  nop
    /* 40B2830 8006EA94 02004010 */  beqz       $v0, .Llevel_62_8006EAA0
    /* 40B2834 8006EA98 00000000 */   nop
    /* 40B2838 8006EA9C 08CF0434 */  ori        $a0, $zero, 0xCF08
  .Llevel_62_8006EAA0:
    /* 40B283C 8006EAA0 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 40B2840 8006EAA4 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 40B2844 8006EAA8 00000000 */  nop
    /* 40B2848 8006EAAC 23188200 */  subu       $v1, $a0, $v0
    /* 40B284C 8006EAB0 00106228 */  slti       $v0, $v1, 0x1000
    /* 40B2850 8006EAB4 12004010 */  beqz       $v0, .Llevel_62_8006EB00
    /* 40B2854 8006EAB8 40100300 */   sll       $v0, $v1, 1
    /* 40B2858 8006EABC 21104300 */  addu       $v0, $v0, $v1
    /* 40B285C 8006EAC0 C0100200 */  sll        $v0, $v0, 3
    /* 40B2860 8006EAC4 21104300 */  addu       $v0, $v0, $v1
    /* 40B2864 8006EAC8 40110200 */  sll        $v0, $v0, 5
    /* 40B2868 8006EACC 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 40B286C 8006EAD0 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 40B2870 8006EAD4 03230200 */  sra        $a0, $v0, 12
    /* 40B2874 8006EAD8 23188300 */  subu       $v1, $a0, $v1
    /* 40B2878 8006EADC FF0F6430 */  andi       $a0, $v1, 0xFFF
    /* 40B287C 8006EAE0 01088228 */  slti       $v0, $a0, 0x801
    /* 40B2880 8006EAE4 03004014 */  bnez       $v0, .Llevel_62_8006EAF4
    /* 40B2884 8006EAE8 2A109200 */   slt       $v0, $a0, $s2
    /* 40B2888 8006EAEC 00F08424 */  addiu      $a0, $a0, -0x1000
    /* 40B288C 8006EAF0 2A109200 */  slt        $v0, $a0, $s2
  .Llevel_62_8006EAF4:
    /* 40B2890 8006EAF4 02004010 */  beqz       $v0, .Llevel_62_8006EB00
    /* 40B2894 8006EAF8 00000000 */   nop
    /* 40B2898 8006EAFC 21908000 */  addu       $s2, $a0, $zero
  .Llevel_62_8006EB00:
    /* 40B289C 8006EB00 0780043C */  lui        $a0, %hi(D_8006A05C)
    /* 40B28A0 8006EB04 5CA08424 */  addiu      $a0, $a0, %lo(D_8006A05C)
    /* 40B28A4 8006EB08 0000828C */  lw         $v0, 0x0($a0)
    /* 40B28A8 8006EB0C 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 40B28AC 8006EB10 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 40B28B0 8006EB14 21105300 */  addu       $v0, $v0, $s3
    /* 40B28B4 8006EB18 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* 40B28B8 8006EB1C 21187200 */  addu       $v1, $v1, $s2
    /* 40B28BC 8006EB20 FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 40B28C0 8006EB24 000082AC */  sw         $v0, 0x0($a0)
    /* 40B28C4 8006EB28 01086228 */  slti       $v0, $v1, 0x801
    /* 40B28C8 8006EB2C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 40B28CC 8006EB30 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 40B28D0 8006EB34 03004014 */  bnez       $v0, .Llevel_62_8006EB44
    /* 40B28D4 8006EB38 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 40B28D8 8006EB3C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 40B28DC 8006EB40 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_62_8006EB44:
    /* 40B28E0 8006EB44 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 40B28E4 8006EB48 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 40B28E8 8006EB4C 00000000 */  nop
    /* 40B28EC 8006EB50 E0FC4228 */  slti       $v0, $v0, -0x320
    /* 40B28F0 8006EB54 03004010 */  beqz       $v0, .Llevel_62_8006EB64
    /* 40B28F4 8006EB58 E0FC0224 */   addiu     $v0, $zero, -0x320
    /* 40B28F8 8006EB5C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 40B28FC 8006EB60 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_62_8006EB64:
    /* 40B2900 8006EB64 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 40B2904 8006EB68 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 40B2908 8006EB6C 00000000 */  nop
    /* 40B290C 8006EB70 21034228 */  slti       $v0, $v0, 0x321
    /* 40B2910 8006EB74 03004014 */  bnez       $v0, .Llevel_62_8006EB84
    /* 40B2914 8006EB78 20030224 */   addiu     $v0, $zero, 0x320
    /* 40B2918 8006EB7C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 40B291C 8006EB80 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_62_8006EB84:
    /* 40B2920 8006EB84 0780023C */  lui        $v0, %hi(D_80069894)
    /* 40B2924 8006EB88 9498428C */  lw         $v0, %lo(D_80069894)($v0)
    /* 40B2928 8006EB8C 00000000 */  nop
    /* 40B292C 8006EB90 46004104 */  bgez       $v0, .Llevel_62_8006ECAC
    /* 40B2930 8006EB94 00000000 */   nop
    /* 40B2934 8006EB98 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 40B2938 8006EB9C 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 40B293C 8006EBA0 00000000 */  nop
    /* 40B2940 8006EBA4 07006104 */  bgez       $v1, .Llevel_62_8006EBC4
    /* 40B2944 8006EBA8 00000000 */   nop
    /* 40B2948 8006EBAC 0680043C */  lui        $a0, %hi(D_80060184)
    /* 40B294C 8006EBB0 8401848C */  lw         $a0, %lo(D_80060184)($a0)
    /* 40B2950 8006EBB4 0680023C */  lui        $v0, %hi(D_80060180)
    /* 40B2954 8006EBB8 8001428C */  lw         $v0, %lo(D_80060180)($v0)
    /* 40B2958 8006EBBC F9BA0108 */  j          .Llevel_62_8006EBE4
    /* 40B295C 8006EBC0 23108200 */   subu      $v0, $a0, $v0
  .Llevel_62_8006EBC4:
    /* 40B2960 8006EBC4 15006018 */  blez       $v1, .Llevel_62_8006EC1C
    /* 40B2964 8006EBC8 00000000 */   nop
    /* 40B2968 8006EBCC 0680023C */  lui        $v0, %hi(D_80060188)
    /* 40B296C 8006EBD0 8801428C */  lw         $v0, %lo(D_80060188)($v0)
    /* 40B2970 8006EBD4 0680043C */  lui        $a0, %hi(D_80060184)
    /* 40B2974 8006EBD8 8401848C */  lw         $a0, %lo(D_80060184)($a0)
    /* 40B2978 8006EBDC 00000000 */  nop
    /* 40B297C 8006EBE0 23104400 */  subu       $v0, $v0, $a0
  .Llevel_62_8006EBE4:
    /* 40B2980 8006EBE4 18006200 */  mult       $v1, $v0
    /* 40B2984 8006EBE8 12100000 */  mflo       $v0
    /* 40B2988 8006EBEC EB51033C */  lui        $v1, (0x51EB851F >> 16)
    /* 40B298C 8006EBF0 1F856334 */  ori        $v1, $v1, (0x51EB851F & 0xFFFF)
    /* 40B2990 8006EBF4 18004300 */  mult       $v0, $v1
    /* 40B2994 8006EBF8 C3170200 */  sra        $v0, $v0, 31
    /* 40B2998 8006EBFC 10480000 */  mfhi       $t1
    /* 40B299C 8006EC00 031A0900 */  sra        $v1, $t1, 8
    /* 40B29A0 8006EC04 23186200 */  subu       $v1, $v1, $v0
    /* 40B29A4 8006EC08 21208300 */  addu       $a0, $a0, $v1
    /* 40B29A8 8006EC0C 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 40B29AC 8006EC10 A4A024AC */  sw         $a0, %lo(D_8006A0A4)($at)
    /* 40B29B0 8006EC14 0BBB0108 */  j          .Llevel_62_8006EC2C
    /* 40B29B4 8006EC18 00000000 */   nop
  .Llevel_62_8006EC1C:
    /* 40B29B8 8006EC1C 0680023C */  lui        $v0, %hi(D_80060184)
    /* 40B29BC 8006EC20 8401428C */  lw         $v0, %lo(D_80060184)($v0)
    /* 40B29C0 8006EC24 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 40B29C4 8006EC28 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
  .Llevel_62_8006EC2C:
    /* 40B29C8 8006EC2C 0780053C */  lui        $a1, %hi(D_8006A13C)
    /* 40B29CC 8006EC30 3CA1A524 */  addiu      $a1, $a1, %lo(D_8006A13C)
    /* 40B29D0 8006EC34 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 40B29D4 8006EC38 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 40B29D8 8006EC3C 0780043C */  lui        $a0, %hi(D_8006A0A8)
    /* 40B29DC 8006EC40 A8A0848C */  lw         $a0, %lo(D_8006A0A8)($a0)
    /* 40B29E0 8006EC44 0000A38C */  lw         $v1, 0x0($a1)
    /* 40B29E4 8006EC48 23104400 */  subu       $v0, $v0, $a0
    /* 40B29E8 8006EC4C 23104300 */  subu       $v0, $v0, $v1
    /* 40B29EC 8006EC50 80110200 */  sll        $v0, $v0, 6
    /* 40B29F0 8006EC54 83110200 */  sra        $v0, $v0, 6
    /* 40B29F4 8006EC58 21186200 */  addu       $v1, $v1, $v0
    /* 40B29F8 8006EC5C 0000A3AC */  sw         $v1, 0x0($a1)
    /* 40B29FC 8006EC60 83190300 */  sra        $v1, $v1, 6
    /* 40B2A00 8006EC64 21208300 */  addu       $a0, $a0, $v1
    /* 40B2A04 8006EC68 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 40B2A08 8006EC6C A8A024AC */  sw         $a0, %lo(D_8006A0A8)($at)
    /* 40B2A0C 8006EC70 00088428 */  slti       $a0, $a0, 0x800
    /* 40B2A10 8006EC74 03008010 */  beqz       $a0, .Llevel_62_8006EC84
    /* 40B2A14 8006EC78 00080224 */   addiu     $v0, $zero, 0x800
    /* 40B2A18 8006EC7C 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 40B2A1C 8006EC80 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_62_8006EC84:
    /* 40B2A20 8006EC84 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 40B2A24 8006EC88 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 40B2A28 8006EC8C 00000000 */  nop
    /* 40B2A2C 8006EC90 014B4228 */  slti       $v0, $v0, 0x4B01
    /* 40B2A30 8006EC94 41004014 */  bnez       $v0, .Llevel_62_8006ED9C
    /* 40B2A34 8006EC98 004B0224 */   addiu     $v0, $zero, 0x4B00
    /* 40B2A38 8006EC9C 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 40B2A3C 8006ECA0 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 40B2A40 8006ECA4 67BB0108 */  j          .Llevel_62_8006ED9C
    /* 40B2A44 8006ECA8 00000000 */   nop
  .Llevel_62_8006ECAC:
    /* 40B2A48 8006ECAC 0680033C */  lui        $v1, %hi(D_80066F90)
    /* 40B2A4C 8006ECB0 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* 40B2A50 8006ECB4 19000224 */  addiu      $v0, $zero, 0x19
    /* 40B2A54 8006ECB8 13006214 */  bne        $v1, $v0, .Llevel_62_8006ED08
    /* 40B2A58 8006ECBC 00000000 */   nop
    /* 40B2A5C 8006ECC0 0780023C */  lui        $v0, %hi(D_8006ABF8)
    /* 40B2A60 8006ECC4 F8AB4290 */  lbu        $v0, %lo(D_8006ABF8)($v0)
    /* 40B2A64 8006ECC8 00000000 */  nop
    /* 40B2A68 8006ECCC 0E004010 */  beqz       $v0, .Llevel_62_8006ED08
    /* 40B2A6C 8006ECD0 08CF0234 */   ori       $v0, $zero, 0xCF08
    /* 40B2A70 8006ECD4 0780033C */  lui        $v1, %hi(D_80069FF8)
    /* 40B2A74 8006ECD8 F89F638C */  lw         $v1, %lo(D_80069FF8)($v1)
    /* 40B2A78 8006ECDC 00000000 */  nop
    /* 40B2A7C 8006ECE0 23204300 */  subu       $a0, $v0, $v1
    /* 40B2A80 8006ECE4 03008104 */  bgez       $a0, .Llevel_62_8006ECF4
    /* 40B2A84 8006ECE8 00000000 */   nop
    /* 40B2A88 8006ECEC 57BB0108 */  j          .Llevel_62_8006ED5C
    /* 40B2A8C 8006ECF0 00080224 */   addiu     $v0, $zero, 0x800
  .Llevel_62_8006ECF4:
    /* 40B2A90 8006ECF4 F06F000C */  jal        func_8001BFC0
    /* 40B2A94 8006ECF8 00000000 */   nop
    /* 40B2A98 8006ECFC 80110200 */  sll        $v0, $v0, 6
    /* 40B2A9C 8006ED00 57BB0108 */  j          .Llevel_62_8006ED5C
    /* 40B2AA0 8006ED04 00084224 */   addiu     $v0, $v0, 0x800
  .Llevel_62_8006ED08:
    /* 40B2AA4 8006ED08 0780033C */  lui        $v1, %hi(D_8006A0F0)
    /* 40B2AA8 8006ED0C F0A0638C */  lw         $v1, %lo(D_8006A0F0)($v1)
    /* 40B2AAC 8006ED10 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 40B2AB0 8006ED14 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 40B2AB4 8006ED18 00000000 */  nop
    /* 40B2AB8 8006ED1C 23206200 */  subu       $a0, $v1, $v0
    /* 40B2ABC 8006ED20 0A008104 */  bgez       $a0, .Llevel_62_8006ED4C
    /* 40B2AC0 8006ED24 00000000 */   nop
    /* 40B2AC4 8006ED28 F06F000C */  jal        func_8001BFC0
    /* 40B2AC8 8006ED2C 23200400 */   negu      $a0, $a0
    /* 40B2ACC 8006ED30 C0110200 */  sll        $v0, $v0, 7
    /* 40B2AD0 8006ED34 40100324 */  addiu      $v1, $zero, 0x1040
    /* 40B2AD4 8006ED38 23186200 */  subu       $v1, $v1, $v0
    /* 40B2AD8 8006ED3C 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 40B2ADC 8006ED40 A8A023AC */  sw         $v1, %lo(D_8006A0A8)($at)
    /* 40B2AE0 8006ED44 59BB0108 */  j          .Llevel_62_8006ED64
    /* 40B2AE4 8006ED48 00000000 */   nop
  .Llevel_62_8006ED4C:
    /* 40B2AE8 8006ED4C F06F000C */  jal        func_8001BFC0
    /* 40B2AEC 8006ED50 00000000 */   nop
    /* 40B2AF0 8006ED54 80110200 */  sll        $v0, $v0, 6
    /* 40B2AF4 8006ED58 40104224 */  addiu      $v0, $v0, 0x1040
  .Llevel_62_8006ED5C:
    /* 40B2AF8 8006ED5C 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 40B2AFC 8006ED60 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_62_8006ED64:
    /* 40B2B00 8006ED64 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 40B2B04 8006ED68 A8A06324 */  addiu      $v1, $v1, %lo(D_8006A0A8)
    /* 40B2B08 8006ED6C 0000628C */  lw         $v0, 0x0($v1)
    /* 40B2B0C 8006ED70 00000000 */  nop
    /* 40B2B10 8006ED74 01594228 */  slti       $v0, $v0, 0x5901
    /* 40B2B14 8006ED78 02004014 */  bnez       $v0, .Llevel_62_8006ED84
    /* 40B2B18 8006ED7C 00590224 */   addiu     $v0, $zero, 0x5900
    /* 40B2B1C 8006ED80 000062AC */  sw         $v0, 0x0($v1)
  .Llevel_62_8006ED84:
    /* 40B2B20 8006ED84 0000628C */  lw         $v0, 0x0($v1)
    /* 40B2B24 8006ED88 00000000 */  nop
    /* 40B2B28 8006ED8C 00084228 */  slti       $v0, $v0, 0x800
    /* 40B2B2C 8006ED90 02004010 */  beqz       $v0, .Llevel_62_8006ED9C
    /* 40B2B30 8006ED94 00080224 */   addiu     $v0, $zero, 0x800
    /* 40B2B34 8006ED98 000062AC */  sw         $v0, 0x0($v1)
  .Llevel_62_8006ED9C:
    /* 40B2B38 8006ED9C 0780043C */  lui        $a0, %hi(D_8006A058)
    /* 40B2B3C 8006EDA0 58A0848C */  lw         $a0, %lo(D_8006A058)($a0)
    /* 40B2B40 8006EDA4 996D000C */  jal        func_8001B664
    /* 40B2B44 8006EDA8 00000000 */   nop
    /* 40B2B48 8006EDAC 40110200 */  sll        $v0, $v0, 5
    /* 40B2B4C 8006EDB0 23100200 */  negu       $v0, $v0
    /* 40B2B50 8006EDB4 18006202 */  mult       $s3, $v0
    /* 40B2B54 8006EDB8 0780033C */  lui        $v1, %hi(D_8006A144)
    /* 40B2B58 8006EDBC 44A1638C */  lw         $v1, %lo(D_8006A144)($v1)
    /* 40B2B5C 8006EDC0 0780053C */  lui        $a1, %hi(D_8006A054)
    /* 40B2B60 8006EDC4 54A0A58C */  lw         $a1, %lo(D_8006A054)($a1)
    /* 40B2B64 8006EDC8 00110300 */  sll        $v0, $v1, 4
    /* 40B2B68 8006EDCC 83110200 */  sra        $v0, $v0, 6
    /* 40B2B6C 8006EDD0 12480000 */  mflo       $t1
    /* 40B2B70 8006EDD4 03230900 */  sra        $a0, $t1, 12
    /* 40B2B74 8006EDD8 23208200 */  subu       $a0, $a0, $v0
    /* 40B2B78 8006EDDC 80110500 */  sll        $v0, $a1, 6
    /* 40B2B7C 8006EDE0 83110200 */  sra        $v0, $v0, 6
    /* 40B2B80 8006EDE4 23208200 */  subu       $a0, $a0, $v0
    /* 40B2B84 8006EDE8 21186400 */  addu       $v1, $v1, $a0
    /* 40B2B88 8006EDEC 0780013C */  lui        $at, %hi(D_8006A144)
    /* 40B2B8C 8006EDF0 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 40B2B90 8006EDF4 83190300 */  sra        $v1, $v1, 6
    /* 40B2B94 8006EDF8 2128A300 */  addu       $a1, $a1, $v1
    /* 40B2B98 8006EDFC FF0FA530 */  andi       $a1, $a1, 0xFFF
    /* 40B2B9C 8006EE00 0108A228 */  slti       $v0, $a1, 0x801
    /* 40B2BA0 8006EE04 0780013C */  lui        $at, %hi(D_8006A054)
    /* 40B2BA4 8006EE08 54A025AC */  sw         $a1, %lo(D_8006A054)($at)
    /* 40B2BA8 8006EE0C 03004014 */  bnez       $v0, .Llevel_62_8006EE1C
    /* 40B2BAC 8006EE10 00F0A224 */   addiu     $v0, $a1, -0x1000
    /* 40B2BB0 8006EE14 0780013C */  lui        $at, %hi(D_8006A054)
    /* 40B2BB4 8006EE18 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_62_8006EE1C:
    /* 40B2BB8 8006EE1C 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 40B2BBC 8006EE20 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 40B2BC0 8006EE24 00000000 */  nop
    /* 40B2BC4 8006EE28 00FD4228 */  slti       $v0, $v0, -0x300
    /* 40B2BC8 8006EE2C 03004010 */  beqz       $v0, .Llevel_62_8006EE3C
    /* 40B2BCC 8006EE30 00FD0224 */   addiu     $v0, $zero, -0x300
    /* 40B2BD0 8006EE34 0780013C */  lui        $at, %hi(D_8006A054)
    /* 40B2BD4 8006EE38 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_62_8006EE3C:
    /* 40B2BD8 8006EE3C 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 40B2BDC 8006EE40 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 40B2BE0 8006EE44 00000000 */  nop
    /* 40B2BE4 8006EE48 01034228 */  slti       $v0, $v0, 0x301
    /* 40B2BE8 8006EE4C 03004014 */  bnez       $v0, .Llevel_62_8006EE5C
    /* 40B2BEC 8006EE50 00030224 */   addiu     $v0, $zero, 0x300
    /* 40B2BF0 8006EE54 0780013C */  lui        $at, %hi(D_8006A054)
    /* 40B2BF4 8006EE58 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_62_8006EE5C:
    /* 40B2BF8 8006EE5C 6FAF000C */  jal        func_8002BDBC
    /* 40B2BFC 8006EE60 00000000 */   nop
    /* 40B2C00 8006EE64 0780043C */  lui        $a0, %hi(D_8006A044)
    /* 40B2C04 8006EE68 44A0848C */  lw         $a0, %lo(D_8006A044)($a0)
    /* 40B2C08 8006EE6C 00000000 */  nop
    /* 40B2C0C 8006EE70 1C008014 */  bnez       $a0, .Llevel_62_8006EEE4
    /* 40B2C10 8006EE74 00000000 */   nop
    /* 40B2C14 8006EE78 0680023C */  lui        $v0, %hi(D_80066F38)
    /* 40B2C18 8006EE7C 386F428C */  lw         $v0, %lo(D_80066F38)($v0)
    /* 40B2C1C 8006EE80 00000000 */  nop
    /* 40B2C20 8006EE84 0400428C */  lw         $v0, 0x4($v0)
    /* 40B2C24 8006EE88 00000000 */  nop
    /* 40B2C28 8006EE8C 40004230 */  andi       $v0, $v0, 0x40
    /* 40B2C2C 8006EE90 46004010 */  beqz       $v0, .Llevel_62_8006EFAC
    /* 40B2C30 8006EE94 00000000 */   nop
    /* 40B2C34 8006EE98 0780023C */  lui        $v0, %hi(D_8006A0F0)
    /* 40B2C38 8006EE9C F0A0428C */  lw         $v0, %lo(D_8006A0F0)($v0)
    /* 40B2C3C 8006EEA0 0780033C */  lui        $v1, %hi(D_80069FF8)
    /* 40B2C40 8006EEA4 F89F638C */  lw         $v1, %lo(D_80069FF8)($v1)
    /* 40B2C44 8006EEA8 00FE4224 */  addiu      $v0, $v0, -0x200
    /* 40B2C48 8006EEAC 2A186200 */  slt        $v1, $v1, $v0
    /* 40B2C4C 8006EEB0 3E006010 */  beqz       $v1, .Llevel_62_8006EFAC
    /* 40B2C50 8006EEB4 21000224 */   addiu     $v0, $zero, 0x21
    /* 40B2C54 8006EEB8 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 40B2C58 8006EEBC 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 40B2C5C 8006EEC0 00000000 */  nop
    /* 40B2C60 8006EEC4 39006214 */  bne        $v1, $v0, .Llevel_62_8006EFAC
    /* 40B2C64 8006EEC8 01000224 */   addiu     $v0, $zero, 0x1
    /* 40B2C68 8006EECC 0780013C */  lui        $at, %hi(D_8006A044)
    /* 40B2C6C 8006EED0 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 40B2C70 8006EED4 0780013C */  lui        $at, %hi(D_8006A150)
    /* 40B2C74 8006EED8 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 40B2C78 8006EEDC EBBB0108 */  j          .Llevel_62_8006EFAC
    /* 40B2C7C 8006EEE0 00000000 */   nop
  .Llevel_62_8006EEE4:
    /* 40B2C80 8006EEE4 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 40B2C84 8006EEE8 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 40B2C88 8006EEEC 0780033C */  lui        $v1, %hi(D_8006A0F0)
    /* 40B2C8C 8006EEF0 F0A0638C */  lw         $v1, %lo(D_8006A0F0)($v1)
    /* 40B2C90 8006EEF4 00000000 */  nop
    /* 40B2C94 8006EEF8 2A104300 */  slt        $v0, $v0, $v1
    /* 40B2C98 8006EEFC 05004014 */  bnez       $v0, .Llevel_62_8006EF14
    /* 40B2C9C 8006EF00 01000224 */   addiu     $v0, $zero, 0x1
    /* 40B2CA0 8006EF04 0780013C */  lui        $at, %hi(D_8006A044)
    /* 40B2CA4 8006EF08 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 40B2CA8 8006EF0C EBBB0108 */  j          .Llevel_62_8006EFAC
    /* 40B2CAC 8006EF10 00000000 */   nop
  .Llevel_62_8006EF14:
    /* 40B2CB0 8006EF14 11008214 */  bne        $a0, $v0, .Llevel_62_8006EF5C
    /* 40B2CB4 8006EF18 00000000 */   nop
    /* 40B2CB8 8006EF1C 0780023C */  lui        $v0, %hi(D_8006A150)
    /* 40B2CBC 8006EF20 50A1428C */  lw         $v0, %lo(D_8006A150)($v0)
    /* 40B2CC0 8006EF24 00000000 */  nop
    /* 40B2CC4 8006EF28 00024224 */  addiu      $v0, $v0, 0x200
    /* 40B2CC8 8006EF2C 0780013C */  lui        $at, %hi(D_8006A150)
    /* 40B2CCC 8006EF30 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 40B2CD0 8006EF34 00184228 */  slti       $v0, $v0, 0x1800
    /* 40B2CD4 8006EF38 14004014 */  bnez       $v0, .Llevel_62_8006EF8C
    /* 40B2CD8 8006EF3C 00180224 */   addiu     $v0, $zero, 0x1800
    /* 40B2CDC 8006EF40 0780013C */  lui        $at, %hi(D_8006A150)
    /* 40B2CE0 8006EF44 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 40B2CE4 8006EF48 02000224 */  addiu      $v0, $zero, 0x2
    /* 40B2CE8 8006EF4C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 40B2CEC 8006EF50 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 40B2CF0 8006EF54 E3BB0108 */  j          .Llevel_62_8006EF8C
    /* 40B2CF4 8006EF58 00000000 */   nop
  .Llevel_62_8006EF5C:
    /* 40B2CF8 8006EF5C 0780023C */  lui        $v0, %hi(D_8006A150)
    /* 40B2CFC 8006EF60 50A1428C */  lw         $v0, %lo(D_8006A150)($v0)
    /* 40B2D00 8006EF64 00000000 */  nop
    /* 40B2D04 8006EF68 00FF4224 */  addiu      $v0, $v0, -0x100
    /* 40B2D08 8006EF6C 0780013C */  lui        $at, %hi(D_8006A150)
    /* 40B2D0C 8006EF70 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 40B2D10 8006EF74 0500401C */  bgtz       $v0, .Llevel_62_8006EF8C
    /* 40B2D14 8006EF78 00000000 */   nop
    /* 40B2D18 8006EF7C 0780013C */  lui        $at, %hi(D_8006A150)
    /* 40B2D1C 8006EF80 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 40B2D20 8006EF84 0780013C */  lui        $at, %hi(D_8006A044)
    /* 40B2D24 8006EF88 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
  .Llevel_62_8006EF8C:
    /* 40B2D28 8006EF8C 0780023C */  lui        $v0, %hi(D_8006A080)
    /* 40B2D2C 8006EF90 80A04224 */  addiu      $v0, $v0, %lo(D_8006A080)
    /* 40B2D30 8006EF94 0000438C */  lw         $v1, 0x0($v0)
    /* 40B2D34 8006EF98 0780043C */  lui        $a0, %hi(D_8006A150)
    /* 40B2D38 8006EF9C 50A1848C */  lw         $a0, %lo(D_8006A150)($a0)
    /* 40B2D3C 8006EFA0 00000000 */  nop
    /* 40B2D40 8006EFA4 21186400 */  addu       $v1, $v1, $a0
    /* 40B2D44 8006EFA8 000043AC */  sw         $v1, 0x0($v0)
  .Llevel_62_8006EFAC:
    /* 40B2D48 8006EFAC 0EB0000C */  jal        func_8002C038
    /* 40B2D4C 8006EFB0 00000000 */   nop
    /* 40B2D50 8006EFB4 9ABC0108 */  j          .Llevel_62_8006F268
    /* 40B2D54 8006EFB8 00000000 */   nop
  .Llevel_62_8006EFBC:
    /* 40B2D58 8006EFBC 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 40B2D5C 8006EFC0 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 40B2D60 8006EFC4 07000224 */  addiu      $v0, $zero, 0x7
    /* 40B2D64 8006EFC8 3A006210 */  beq        $v1, $v0, .Llevel_62_8006F0B4
    /* 40B2D68 8006EFCC 7800A427 */   addiu     $a0, $sp, 0x78
    /* 40B2D6C 8006EFD0 39AD000C */  jal        func_8002B4E4
    /* 40B2D70 8006EFD4 21280000 */   addu      $a1, $zero, $zero
    /* 40B2D74 8006EFD8 8800A427 */  addiu      $a0, $sp, 0x88
    /* 40B2D78 8006EFDC 7800A28F */  lw         $v0, 0x78($sp)
    /* 40B2D7C 8006EFE0 7C00A68F */  lw         $a2, 0x7C($sp)
    /* 40B2D80 8006EFE4 21280000 */  addu       $a1, $zero, $zero
    /* 40B2D84 8006EFE8 8800A0AF */  sw         $zero, 0x88($sp)
    /* 40B2D88 8006EFEC C0180200 */  sll        $v1, $v0, 3
    /* 40B2D8C 8006EFF0 21186200 */  addu       $v1, $v1, $v0
    /* 40B2D90 8006EFF4 C0190300 */  sll        $v1, $v1, 7
    /* 40B2D94 8006EFF8 C3190300 */  sra        $v1, $v1, 7
    /* 40B2D98 8006EFFC 40100600 */  sll        $v0, $a2, 1
    /* 40B2D9C 8006F000 21104600 */  addu       $v0, $v0, $a2
    /* 40B2DA0 8006F004 40120200 */  sll        $v0, $v0, 9
    /* 40B2DA4 8006F008 C3110200 */  sra        $v0, $v0, 7
    /* 40B2DA8 8006F00C 7800A3AF */  sw         $v1, 0x78($sp)
    /* 40B2DAC 8006F010 23180300 */  negu       $v1, $v1
    /* 40B2DB0 8006F014 7C00A2AF */  sw         $v0, 0x7C($sp)
    /* 40B2DB4 8006F018 8C00A3AF */  sw         $v1, 0x8C($sp)
    /* 40B2DB8 8006F01C 886E000C */  jal        func_8001BA20
    /* 40B2DBC 8006F020 9000A2AF */   sw        $v0, 0x90($sp)
    /* 40B2DC0 8006F024 9000A48F */  lw         $a0, 0x90($sp)
    /* 40B2DC4 8006F028 00000000 */  nop
    /* 40B2DC8 8006F02C 02008104 */  bgez       $a0, .Llevel_62_8006F038
    /* 40B2DCC 8006F030 21188000 */   addu      $v1, $a0, $zero
    /* 40B2DD0 8006F034 23180300 */  negu       $v1, $v1
  .Llevel_62_8006F038:
    /* 40B2DD4 8006F038 2A186200 */  slt        $v1, $v1, $v0
    /* 40B2DD8 8006F03C 0C006010 */  beqz       $v1, .Llevel_62_8006F070
    /* 40B2DDC 8006F040 00000000 */   nop
    /* 40B2DE0 8006F044 8C00A28F */  lw         $v0, 0x8C($sp)
    /* 40B2DE4 8006F048 9000A0AF */  sw         $zero, 0x90($sp)
    /* 40B2DE8 8006F04C 02004018 */  blez       $v0, .Llevel_62_8006F058
    /* 40B2DEC 8006F050 21200000 */   addu      $a0, $zero, $zero
    /* 40B2DF0 8006F054 01000424 */  addiu      $a0, $zero, 0x1
  .Llevel_62_8006F058:
    /* 40B2DF4 8006F058 CAB4000C */  jal        func_8002D328
    /* 40B2DF8 8006F05C 00000000 */   nop
    /* 40B2DFC 8006F060 0E004014 */  bnez       $v0, .Llevel_62_8006F09C
    /* 40B2E00 8006F064 8800A427 */   addiu     $a0, $sp, 0x88
    /* 40B2E04 8006F068 27BC0108 */  j          .Llevel_62_8006F09C
    /* 40B2E08 8006F06C 8C00A0AF */   sw        $zero, 0x8C($sp)
  .Llevel_62_8006F070:
    /* 40B2E0C 8006F070 8C00A0AF */  sw         $zero, 0x8C($sp)
    /* 40B2E10 8006F074 03008018 */  blez       $a0, .Llevel_62_8006F084
    /* 40B2E14 8006F078 8800A0AF */   sw        $zero, 0x88($sp)
    /* 40B2E18 8006F07C 22BC0108 */  j          .Llevel_62_8006F088
    /* 40B2E1C 8006F080 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_62_8006F084:
    /* 40B2E20 8006F084 03000424 */  addiu      $a0, $zero, 0x3
  .Llevel_62_8006F088:
    /* 40B2E24 8006F088 CAB4000C */  jal        func_8002D328
    /* 40B2E28 8006F08C 00000000 */   nop
    /* 40B2E2C 8006F090 02004014 */  bnez       $v0, .Llevel_62_8006F09C
    /* 40B2E30 8006F094 8800A427 */   addiu     $a0, $sp, 0x88
    /* 40B2E34 8006F098 9000A0AF */  sw         $zero, 0x90($sp)
  .Llevel_62_8006F09C:
    /* 40B2E38 8006F09C 886E000C */  jal        func_8001BA20
    /* 40B2E3C 8006F0A0 01000524 */   addiu     $a1, $zero, 0x1
    /* 40B2E40 8006F0A4 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 40B2E44 8006F0A8 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 40B2E48 8006F0AC 2FBC0108 */  j          .Llevel_62_8006F0BC
    /* 40B2E4C 8006F0B0 00000000 */   nop
  .Llevel_62_8006F0B4:
    /* 40B2E50 8006F0B4 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 40B2E54 8006F0B8 A4A020AC */  sw         $zero, %lo(D_8006A0A4)($at)
  .Llevel_62_8006F0BC:
    /* 40B2E58 8006F0BC 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 40B2E5C 8006F0C0 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 40B2E60 8006F0C4 686F000C */  jal        func_8001BDA0
    /* 40B2E64 8006F0C8 21200002 */   addu      $a0, $s0, $zero
    /* 40B2E68 8006F0CC 686F000C */  jal        func_8001BDA0
    /* 40B2E6C 8006F0D0 0C000426 */   addiu     $a0, $s0, 0xC
    /* 40B2E70 8006F0D4 9ABC0108 */  j          .Llevel_62_8006F268
    /* 40B2E74 8006F0D8 00000000 */   nop
  .Llevel_62_8006F0DC:
    /* 40B2E78 8006F0DC 9800A427 */  addiu      $a0, $sp, 0x98
    /* 40B2E7C 8006F0E0 39AD000C */  jal        func_8002B4E4
    /* 40B2E80 8006F0E4 21280000 */   addu      $a1, $zero, $zero
    /* 40B2E84 8006F0E8 A000A427 */  addiu      $a0, $sp, 0xA0
    /* 40B2E88 8006F0EC 9800A28F */  lw         $v0, 0x98($sp)
    /* 40B2E8C 8006F0F0 9C00A68F */  lw         $a2, 0x9C($sp)
    /* 40B2E90 8006F0F4 21280000 */  addu       $a1, $zero, $zero
    /* 40B2E94 8006F0F8 A000A0AF */  sw         $zero, 0xA0($sp)
    /* 40B2E98 8006F0FC C0180200 */  sll        $v1, $v0, 3
    /* 40B2E9C 8006F100 21186200 */  addu       $v1, $v1, $v0
    /* 40B2EA0 8006F104 C0190300 */  sll        $v1, $v1, 7
    /* 40B2EA4 8006F108 C3190300 */  sra        $v1, $v1, 7
    /* 40B2EA8 8006F10C 40100600 */  sll        $v0, $a2, 1
    /* 40B2EAC 8006F110 21104600 */  addu       $v0, $v0, $a2
    /* 40B2EB0 8006F114 40120200 */  sll        $v0, $v0, 9
    /* 40B2EB4 8006F118 C3110200 */  sra        $v0, $v0, 7
    /* 40B2EB8 8006F11C 9800A3AF */  sw         $v1, 0x98($sp)
    /* 40B2EBC 8006F120 23180300 */  negu       $v1, $v1
    /* 40B2EC0 8006F124 9C00A2AF */  sw         $v0, 0x9C($sp)
    /* 40B2EC4 8006F128 A400A3AF */  sw         $v1, 0xA4($sp)
    /* 40B2EC8 8006F12C 886E000C */  jal        func_8001BA20
    /* 40B2ECC 8006F130 A800A2AF */   sw        $v0, 0xA8($sp)
    /* 40B2ED0 8006F134 A800A48F */  lw         $a0, 0xA8($sp)
    /* 40B2ED4 8006F138 00000000 */  nop
    /* 40B2ED8 8006F13C 02008104 */  bgez       $a0, .Llevel_62_8006F148
    /* 40B2EDC 8006F140 21188000 */   addu      $v1, $a0, $zero
    /* 40B2EE0 8006F144 23180300 */  negu       $v1, $v1
  .Llevel_62_8006F148:
    /* 40B2EE4 8006F148 2A186200 */  slt        $v1, $v1, $v0
    /* 40B2EE8 8006F14C 0C006010 */  beqz       $v1, .Llevel_62_8006F180
    /* 40B2EEC 8006F150 00000000 */   nop
    /* 40B2EF0 8006F154 A400A28F */  lw         $v0, 0xA4($sp)
    /* 40B2EF4 8006F158 A800A0AF */  sw         $zero, 0xA8($sp)
    /* 40B2EF8 8006F15C 02004018 */  blez       $v0, .Llevel_62_8006F168
    /* 40B2EFC 8006F160 21200000 */   addu      $a0, $zero, $zero
    /* 40B2F00 8006F164 01000424 */  addiu      $a0, $zero, 0x1
  .Llevel_62_8006F168:
    /* 40B2F04 8006F168 CAB4000C */  jal        func_8002D328
    /* 40B2F08 8006F16C 00000000 */   nop
    /* 40B2F0C 8006F170 0E004014 */  bnez       $v0, .Llevel_62_8006F1AC
    /* 40B2F10 8006F174 A000B127 */   addiu     $s1, $sp, 0xA0
    /* 40B2F14 8006F178 6BBC0108 */  j          .Llevel_62_8006F1AC
    /* 40B2F18 8006F17C A400A0AF */   sw        $zero, 0xA4($sp)
  .Llevel_62_8006F180:
    /* 40B2F1C 8006F180 A400A0AF */  sw         $zero, 0xA4($sp)
    /* 40B2F20 8006F184 03008018 */  blez       $a0, .Llevel_62_8006F194
    /* 40B2F24 8006F188 A000A0AF */   sw        $zero, 0xA0($sp)
    /* 40B2F28 8006F18C 66BC0108 */  j          .Llevel_62_8006F198
    /* 40B2F2C 8006F190 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_62_8006F194:
    /* 40B2F30 8006F194 03000424 */  addiu      $a0, $zero, 0x3
  .Llevel_62_8006F198:
    /* 40B2F34 8006F198 CAB4000C */  jal        func_8002D328
    /* 40B2F38 8006F19C 00000000 */   nop
    /* 40B2F3C 8006F1A0 02004014 */  bnez       $v0, .Llevel_62_8006F1AC
    /* 40B2F40 8006F1A4 A000B127 */   addiu     $s1, $sp, 0xA0
    /* 40B2F44 8006F1A8 A800A0AF */  sw         $zero, 0xA8($sp)
  .Llevel_62_8006F1AC:
    /* 40B2F48 8006F1AC 21202002 */  addu       $a0, $s1, $zero
    /* 40B2F4C 8006F1B0 886E000C */  jal        func_8001BA20
    /* 40B2F50 8006F1B4 01000524 */   addiu     $a1, $zero, 0x1
    /* 40B2F54 8006F1B8 01000624 */  addiu      $a2, $zero, 0x1
    /* 40B2F58 8006F1BC 9800A48F */  lw         $a0, 0x98($sp)
    /* 40B2F5C 8006F1C0 9C00A58F */  lw         $a1, 0x9C($sp)
    /* 40B2F60 8006F1C4 0780103C */  lui        $s0, %hi(D_8006A0A4)
    /* 40B2F64 8006F1C8 A4A01026 */  addiu      $s0, $s0, %lo(D_8006A0A4)
    /* 40B2F68 8006F1CC 2E6D000C */  jal        func_8001B4B8
    /* 40B2F6C 8006F1D0 000002AE */   sw        $v0, 0x0($s0)
    /* 40B2F70 8006F1D4 21184000 */  addu       $v1, $v0, $zero
    /* 40B2F74 8006F1D8 01086228 */  slti       $v0, $v1, 0x801
    /* 40B2F78 8006F1DC 0780013C */  lui        $at, %hi(D_8006A09C)
    /* 40B2F7C 8006F1E0 9CA023AC */  sw         $v1, %lo(D_8006A09C)($at)
    /* 40B2F80 8006F1E4 04004014 */  bnez       $v0, .Llevel_62_8006F1F8
    /* 40B2F84 8006F1E8 7CFF0426 */   addiu     $a0, $s0, -0x84
    /* 40B2F88 8006F1EC 00F06224 */  addiu      $v0, $v1, -0x1000
    /* 40B2F8C 8006F1F0 0780013C */  lui        $at, %hi(D_8006A09C)
    /* 40B2F90 8006F1F4 9CA022AC */  sw         $v0, %lo(D_8006A09C)($at)
  .Llevel_62_8006F1F8:
    /* 40B2F94 8006F1F8 21282002 */  addu       $a1, $s1, $zero
    /* 40B2F98 8006F1FC A000A28F */  lw         $v0, 0xA0($sp)
    /* 40B2F9C 8006F200 21302002 */  addu       $a2, $s1, $zero
    /* 40B2FA0 8006F204 00044224 */  addiu      $v0, $v0, 0x400
    /* 40B2FA4 8006F208 696E000C */  jal        func_8001B9A4
    /* 40B2FA8 8006F20C A000A2AF */   sw        $v0, 0xA0($sp)
    /* 40B2FAC 8006F210 21202002 */  addu       $a0, $s1, $zero
    /* 40B2FB0 8006F214 21282002 */  addu       $a1, $s1, $zero
    /* 40B2FB4 8006F218 E0FF1226 */  addiu      $s2, $s0, -0x20
    /* 40B2FB8 8006F21C 806F000C */  jal        func_8001BE00
    /* 40B2FBC 8006F220 21304002 */   addu      $a2, $s2, $zero
    /* 40B2FC0 8006F224 21202002 */  addu       $a0, $s1, $zero
    /* 40B2FC4 8006F228 886E000C */  jal        func_8001BA20
    /* 40B2FC8 8006F22C 21280000 */   addu      $a1, $zero, $zero
    /* 40B2FCC 8006F230 21284000 */  addu       $a1, $v0, $zero
    /* 40B2FD0 8006F234 8101A228 */  slti       $v0, $a1, 0x181
    /* 40B2FD4 8006F238 03004014 */  bnez       $v0, .Llevel_62_8006F248
    /* 40B2FD8 8006F23C 21202002 */   addu      $a0, $s1, $zero
    /* 40B2FDC 8006F240 316F000C */  jal        func_8001BCC4
    /* 40B2FE0 8006F244 80010624 */   addiu     $a2, $zero, 0x180
  .Llevel_62_8006F248:
    /* 40B2FE4 8006F248 D4FF1026 */  addiu      $s0, $s0, -0x2C
    /* 40B2FE8 8006F24C 21200002 */  addu       $a0, $s0, $zero
    /* 40B2FEC 8006F250 21284002 */  addu       $a1, $s2, $zero
    /* 40B2FF0 8006F254 736F000C */  jal        func_8001BDCC
    /* 40B2FF4 8006F258 21302002 */   addu      $a2, $s1, $zero
    /* 40B2FF8 8006F25C 21204002 */  addu       $a0, $s2, $zero
    /* 40B2FFC 8006F260 6C6F000C */  jal        func_8001BDB0
    /* 40B3000 8006F264 21280002 */   addu      $a1, $s0, $zero
  .Llevel_62_8006F268:
    /* 40B3004 8006F268 C000BF8F */  lw         $ra, 0xC0($sp)
    /* 40B3008 8006F26C BC00B38F */  lw         $s3, 0xBC($sp)
    /* 40B300C 8006F270 B800B28F */  lw         $s2, 0xB8($sp)
    /* 40B3010 8006F274 B400B18F */  lw         $s1, 0xB4($sp)
    /* 40B3014 8006F278 B000B08F */  lw         $s0, 0xB0($sp)
    /* 40B3018 8006F27C C800BD27 */  addiu      $sp, $sp, 0xC8
    /* 40B301C 8006F280 0800E003 */  jr         $ra
    /* 40B3020 8006F284 00000000 */   nop
endlabel func_level_62_8006DFD0
