.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_23_8006D3F8

dlabel jtbl_level_23_8006D3F8
    /* 19AB194 8006D3F8 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB198 8006D3FC F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB19C 8006D400 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1A0 8006D404 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1A4 8006D408 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1A8 8006D40C F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1AC 8006D410 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1B0 8006D414 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1B4 8006D418 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1B8 8006D41C F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1BC 8006D420 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1C0 8006D424 E0F40680 */ .word .Llevel_23_8006F4E0
    /* 19AB1C4 8006D428 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1C8 8006D42C F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1CC 8006D430 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1D0 8006D434 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1D4 8006D438 F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1D8 8006D43C F0F50680 */ .word .Llevel_23_8006F5F0
    /* 19AB1DC 8006D440 24F50680 */ .word .Llevel_23_8006F524
    /* 19AB1E0 8006D444 84F50680 */ .word .Llevel_23_8006F584
    /* 19AB1E4 8006D448 84F50680 */ .word .Llevel_23_8006F584
    /* 19AB1E8 8006D44C 00000000 */ .word 0x00000000
enddlabel jtbl_level_23_8006D3F8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_23_8006F4A0, 0x168

glabel func_level_23_8006F4A0
    /* 19AD23C 8006F4A0 0780023C */  lui        $v0, %hi(D_8006A004)
    /* 19AD240 8006F4A4 04A04290 */  lbu        $v0, %lo(D_8006A004)($v0)
    /* 19AD244 8006F4A8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 19AD248 8006F4AC 1800BFAF */  sw         $ra, 0x18($sp)
    /* 19AD24C 8006F4B0 1400B1AF */  sw         $s1, 0x14($sp)
    /* 19AD250 8006F4B4 E0FF4324 */  addiu      $v1, $v0, -0x20
    /* 19AD254 8006F4B8 1500622C */  sltiu      $v0, $v1, 0x15
    /* 19AD258 8006F4BC 4C004010 */  beqz       $v0, .Llevel_23_8006F5F0
    /* 19AD25C 8006F4C0 1000B0AF */   sw        $s0, 0x10($sp)
    /* 19AD260 8006F4C4 80100300 */  sll        $v0, $v1, 2
    /* 19AD264 8006F4C8 0780013C */  lui        $at, %hi(jtbl_level_23_8006D3F8)
    /* 19AD268 8006F4CC 21082200 */  addu       $at, $at, $v0
    /* 19AD26C 8006F4D0 F8D3228C */  lw         $v0, %lo(jtbl_level_23_8006D3F8)($at)
    /* 19AD270 8006F4D4 00000000 */  nop
    /* 19AD274 8006F4D8 08004000 */  jr         $v0
    /* 19AD278 8006F4DC 00000000 */   nop
  .Llevel_23_8006F4E0:
    /* 19AD27C 8006F4E0 0780103C */  lui        $s0, %hi(D_8006A006)
    /* 19AD280 8006F4E4 06A01026 */  addiu      $s0, $s0, %lo(D_8006A006)
    /* 19AD284 8006F4E8 00000392 */  lbu        $v1, 0x0($s0)
    /* 19AD288 8006F4EC 01000224 */  addiu      $v0, $zero, 0x1
    /* 19AD28C 8006F4F0 3F006214 */  bne        $v1, $v0, .Llevel_23_8006F5F0
    /* 19AD290 8006F4F4 21280000 */   addu      $a1, $zero, $zero
    /* 19AD294 8006F4F8 0680023C */  lui        $v0, %hi(D_80067020)
    /* 19AD298 8006F4FC 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 19AD29C 8006F500 00000000 */  nop
    /* 19AD2A0 8006F504 0A004490 */  lbu        $a0, 0xA($v0)
    /* 19AD2A4 8006F508 C841010C */  jal        func_80050720
    /* 19AD2A8 8006F50C 21300000 */   addu      $a2, $zero, $zero
    /* 19AD2AC 8006F510 00000292 */  lbu        $v0, 0x0($s0)
    /* 19AD2B0 8006F514 0780013C */  lui        $at, %hi(D_8006A268)
    /* 19AD2B4 8006F518 68A222AC */  sw         $v0, %lo(D_8006A268)($at)
    /* 19AD2B8 8006F51C 7CBD0108 */  j          .Llevel_23_8006F5F0
    /* 19AD2BC 8006F520 00000000 */   nop
  .Llevel_23_8006F524:
    /* 19AD2C0 8006F524 0780103C */  lui        $s0, %hi(D_8006A006)
    /* 19AD2C4 8006F528 06A01026 */  addiu      $s0, $s0, %lo(D_8006A006)
    /* 19AD2C8 8006F52C 00000392 */  lbu        $v1, 0x0($s0)
    /* 19AD2CC 8006F530 03000224 */  addiu      $v0, $zero, 0x3
    /* 19AD2D0 8006F534 03006210 */  beq        $v1, $v0, .Llevel_23_8006F544
    /* 19AD2D4 8006F538 0A000224 */   addiu     $v0, $zero, 0xA
    /* 19AD2D8 8006F53C 2C006214 */  bne        $v1, $v0, .Llevel_23_8006F5F0
    /* 19AD2DC 8006F540 00000000 */   nop
  .Llevel_23_8006F544:
    /* 19AD2E0 8006F544 0680023C */  lui        $v0, %hi(D_80067020)
    /* 19AD2E4 8006F548 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 19AD2E8 8006F54C 21280000 */  addu       $a1, $zero, $zero
    /* 19AD2EC 8006F550 11004490 */  lbu        $a0, 0x11($v0)
    /* 19AD2F0 8006F554 C841010C */  jal        func_80050720
    /* 19AD2F4 8006F558 21300000 */   addu      $a2, $zero, $zero
    /* 19AD2F8 8006F55C 00000392 */  lbu        $v1, 0x0($s0)
    /* 19AD2FC 8006F560 21204000 */  addu       $a0, $v0, $zero
    /* 19AD300 8006F564 0780013C */  lui        $at, %hi(D_8006A268)
    /* 19AD304 8006F568 68A223AC */  sw         $v1, %lo(D_8006A268)($at)
    /* 19AD308 8006F56C 20008004 */  bltz       $a0, .Llevel_23_8006F5F0
    /* 19AD30C 8006F570 0A000224 */   addiu     $v0, $zero, 0xA
    /* 19AD310 8006F574 1C006210 */  beq        $v1, $v0, .Llevel_23_8006F5E8
    /* 19AD314 8006F578 00000000 */   nop
    /* 19AD318 8006F57C 7CBD0108 */  j          .Llevel_23_8006F5F0
    /* 19AD31C 8006F580 00000000 */   nop
  .Llevel_23_8006F584:
    /* 19AD320 8006F584 0780103C */  lui        $s0, %hi(D_8006A006)
    /* 19AD324 8006F588 06A01026 */  addiu      $s0, $s0, %lo(D_8006A006)
    /* 19AD328 8006F58C 00000392 */  lbu        $v1, 0x0($s0)
    /* 19AD32C 8006F590 01001124 */  addiu      $s1, $zero, 0x1
    /* 19AD330 8006F594 03007110 */  beq        $v1, $s1, .Llevel_23_8006F5A4
    /* 19AD334 8006F598 03000224 */   addiu     $v0, $zero, 0x3
    /* 19AD338 8006F59C 14006214 */  bne        $v1, $v0, .Llevel_23_8006F5F0
    /* 19AD33C 8006F5A0 00000000 */   nop
  .Llevel_23_8006F5A4:
    /* 19AD340 8006F5A4 0680023C */  lui        $v0, %hi(D_80067020)
    /* 19AD344 8006F5A8 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 19AD348 8006F5AC 21280000 */  addu       $a1, $zero, $zero
    /* 19AD34C 8006F5B0 11004490 */  lbu        $a0, 0x11($v0)
    /* 19AD350 8006F5B4 C841010C */  jal        func_80050720
    /* 19AD354 8006F5B8 21300000 */   addu      $a2, $zero, $zero
    /* 19AD358 8006F5BC 00000392 */  lbu        $v1, 0x0($s0)
    /* 19AD35C 8006F5C0 21804000 */  addu       $s0, $v0, $zero
    /* 19AD360 8006F5C4 0780013C */  lui        $at, %hi(D_8006A268)
    /* 19AD364 8006F5C8 68A223AC */  sw         $v1, %lo(D_8006A268)($at)
    /* 19AD368 8006F5CC 08000006 */  bltz       $s0, .Llevel_23_8006F5F0
    /* 19AD36C 8006F5D0 00000000 */   nop
    /* 19AD370 8006F5D4 06007114 */  bne        $v1, $s1, .Llevel_23_8006F5F0
    /* 19AD374 8006F5D8 21200002 */   addu      $a0, $s0, $zero
    /* 19AD378 8006F5DC 3D43010C */  jal        func_80050CF4
    /* 19AD37C 8006F5E0 000C0524 */   addiu     $a1, $zero, 0xC00
    /* 19AD380 8006F5E4 21200002 */  addu       $a0, $s0, $zero
  .Llevel_23_8006F5E8:
    /* 19AD384 8006F5E8 1943010C */  jal        func_80050C64
    /* 19AD388 8006F5EC 00120524 */   addiu     $a1, $zero, 0x1200
  .Llevel_23_8006F5F0:
    /* 19AD38C 8006F5F0 1800BF8F */  lw         $ra, 0x18($sp)
    /* 19AD390 8006F5F4 1400B18F */  lw         $s1, 0x14($sp)
    /* 19AD394 8006F5F8 1000B08F */  lw         $s0, 0x10($sp)
    /* 19AD398 8006F5FC 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 19AD39C 8006F600 0800E003 */  jr         $ra
    /* 19AD3A0 8006F604 00000000 */   nop
endlabel func_level_23_8006F4A0
