.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_32_8006D2C0

dlabel jtbl_level_32_8006D2C0
    /* 235F05C 8006D2C0 0CE80680 */ .word .Llevel_32_8006E80C
    /* 235F060 8006D2C4 A4E70680 */ .word .Llevel_32_8006E7A4
    /* 235F064 8006D2C8 0CE80680 */ .word .Llevel_32_8006E80C
    /* 235F068 8006D2CC 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F06C 8006D2D0 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F070 8006D2D4 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F074 8006D2D8 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F078 8006D2DC 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F07C 8006D2E0 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F080 8006D2E4 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F084 8006D2E8 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F088 8006D2EC E4E70680 */ .word .Llevel_32_8006E7E4
    /* 235F08C 8006D2F0 34E80680 */ .word .Llevel_32_8006E834
    /* 235F090 8006D2F4 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F094 8006D2F8 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F098 8006D2FC 0CE80680 */ .word .Llevel_32_8006E80C
    /* 235F09C 8006D300 0CE80680 */ .word .Llevel_32_8006E80C
    /* 235F0A0 8006D304 0CE80680 */ .word .Llevel_32_8006E80C
    /* 235F0A4 8006D308 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F0A8 8006D30C 0CE90680 */ .word .Llevel_32_8006E90C
    /* 235F0AC 8006D310 A4E70680 */ .word .Llevel_32_8006E7A4
    /* 235F0B0 8006D314 00000000 */ .word 0x00000000
enddlabel jtbl_level_32_8006D2C0


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_32_8006E76C, 0x1B0

glabel func_level_32_8006E76C
    /* 2360508 8006E76C 0780023C */  lui        $v0, %hi(D_8006A040)
    /* 236050C 8006E770 40A0428C */  lw         $v0, %lo(D_8006A040)($v0)
    /* 2360510 8006E774 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 2360514 8006E778 EEFF4324 */  addiu      $v1, $v0, -0x12
    /* 2360518 8006E77C 1500622C */  sltiu      $v0, $v1, 0x15
    /* 236051C 8006E780 62004010 */  beqz       $v0, .Llevel_32_8006E90C
    /* 2360520 8006E784 2000BFAF */   sw        $ra, 0x20($sp)
    /* 2360524 8006E788 80100300 */  sll        $v0, $v1, 2
    /* 2360528 8006E78C 0780013C */  lui        $at, %hi(jtbl_level_32_8006D2C0)
    /* 236052C 8006E790 21082200 */  addu       $at, $at, $v0
    /* 2360530 8006E794 C0D2228C */  lw         $v0, %lo(jtbl_level_32_8006D2C0)($at)
    /* 2360534 8006E798 00000000 */  nop
    /* 2360538 8006E79C 08004000 */  jr         $v0
    /* 236053C 8006E7A0 00000000 */   nop
  .Llevel_32_8006E7A4:
    /* 2360540 8006E7A4 71B6000C */  jal        func_8002D9C4
    /* 2360544 8006E7A8 00000000 */   nop
    /* 2360548 8006E7AC 03004014 */  bnez       $v0, .Llevel_32_8006E7BC
    /* 236054C 8006E7B0 00000000 */   nop
    /* 2360550 8006E7B4 FEB5000C */  jal        func_8002D7F8
    /* 2360554 8006E7B8 00000000 */   nop
  .Llevel_32_8006E7BC:
    /* 2360558 8006E7BC 3DB0000C */  jal        func_8002C0F4
    /* 236055C 8006E7C0 00000000 */   nop
    /* 2360560 8006E7C4 0780013C */  lui        $at, %hi(D_8006A0B4)
    /* 2360564 8006E7C8 B4A020AC */  sw         $zero, %lo(D_8006A0B4)($at)
    /* 2360568 8006E7CC 22B3000C */  jal        func_8002CC88
    /* 236056C 8006E7D0 00000000 */   nop
    /* 2360570 8006E7D4 0780013C */  lui        $at, %hi(D_8006A018)
    /* 2360574 8006E7D8 18A020AC */  sw         $zero, %lo(D_8006A018)($at)
    /* 2360578 8006E7DC 43BA0108 */  j          .Llevel_32_8006E90C
    /* 236057C 8006E7E0 00000000 */   nop
  .Llevel_32_8006E7E4:
    /* 2360580 8006E7E4 3DB0000C */  jal        func_8002C0F4
    /* 2360584 8006E7E8 00000000 */   nop
    /* 2360588 8006E7EC 22B3000C */  jal        func_8002CC88
    /* 236058C 8006E7F0 00000000 */   nop
    /* 2360590 8006E7F4 C2B6000C */  jal        func_8002DB08
    /* 2360594 8006E7F8 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 2360598 8006E7FC 0780013C */  lui        $at, %hi(D_8006A018)
    /* 236059C 8006E800 18A020AC */  sw         $zero, %lo(D_8006A018)($at)
    /* 23605A0 8006E804 43BA0108 */  j          .Llevel_32_8006E90C
    /* 23605A4 8006E808 00000000 */   nop
  .Llevel_32_8006E80C:
    /* 23605A8 8006E80C 3DB0000C */  jal        func_8002C0F4
    /* 23605AC 8006E810 00000000 */   nop
    /* 23605B0 8006E814 22B3000C */  jal        func_8002CC88
    /* 23605B4 8006E818 00000000 */   nop
    /* 23605B8 8006E81C 81AF000C */  jal        func_8002BE04
    /* 23605BC 8006E820 00000000 */   nop
    /* 23605C0 8006E824 0780013C */  lui        $at, %hi(D_8006A018)
    /* 23605C4 8006E828 18A020AC */  sw         $zero, %lo(D_8006A018)($at)
    /* 23605C8 8006E82C 43BA0108 */  j          .Llevel_32_8006E90C
    /* 23605CC 8006E830 00000000 */   nop
  .Llevel_32_8006E834:
    /* 23605D0 8006E834 0780053C */  lui        $a1, %hi(D_80069FF8)
    /* 23605D4 8006E838 F89FA524 */  addiu      $a1, $a1, %lo(D_80069FF8)
    /* 23605D8 8006E83C 0780063C */  lui        $a2, %hi(D_8006A13C)
    /* 23605DC 8006E840 3CA1C68C */  lw         $a2, %lo(D_8006A13C)($a2)
    /* 23605E0 8006E844 0000A28C */  lw         $v0, 0x0($a1)
    /* 23605E4 8006E848 0680033C */  lui        $v1, %hi(D_80067018)
    /* 23605E8 8006E84C 1870638C */  lw         $v1, %lo(D_80067018)($v1)
    /* 23605EC 8006E850 83210600 */  sra        $a0, $a2, 6
    /* 23605F0 8006E854 21104400 */  addu       $v0, $v0, $a0
    /* 23605F4 8006E858 401A0300 */  sll        $v1, $v1, 9
    /* 23605F8 8006E85C 0000A2AC */  sw         $v0, 0x0($a1)
    /* 23605FC 8006E860 0780023C */  lui        $v0, %hi(D_8006A248)
    /* 2360600 8006E864 48A2428C */  lw         $v0, %lo(D_8006A248)($v0)
    /* 2360604 8006E868 2130C300 */  addu       $a2, $a2, $v1
    /* 2360608 8006E86C 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 236060C 8006E870 3CA126AC */  sw         $a2, %lo(D_8006A13C)($at)
    /* 2360610 8006E874 09004104 */  bgez       $v0, .Llevel_32_8006E89C
    /* 2360614 8006E878 8125C228 */   slti      $v0, $a2, 0x2581
    /* 2360618 8006E87C 00900334 */  ori        $v1, $zero, 0x9000
    /* 236061C 8006E880 2A106600 */  slt        $v0, $v1, $a2
    /* 2360620 8006E884 09004010 */  beqz       $v0, .Llevel_32_8006E8AC
    /* 2360624 8006E888 00000000 */   nop
    /* 2360628 8006E88C 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 236062C 8006E890 3CA123AC */  sw         $v1, %lo(D_8006A13C)($at)
    /* 2360630 8006E894 2BBA0108 */  j          .Llevel_32_8006E8AC
    /* 2360634 8006E898 00000000 */   nop
  .Llevel_32_8006E89C:
    /* 2360638 8006E89C 03004014 */  bnez       $v0, .Llevel_32_8006E8AC
    /* 236063C 8006E8A0 80250224 */   addiu     $v0, $zero, 0x2580
    /* 2360640 8006E8A4 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 2360644 8006E8A8 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
  .Llevel_32_8006E8AC:
    /* 2360648 8006E8AC 3DB0000C */  jal        func_8002C0F4
    /* 236064C 8006E8B0 00000000 */   nop
    /* 2360650 8006E8B4 22B3000C */  jal        func_8002CC88
    /* 2360654 8006E8B8 00000000 */   nop
    /* 2360658 8006E8BC 0780053C */  lui        $a1, %hi(D_80069FF0)
    /* 236065C 8006E8C0 F09FA524 */  addiu      $a1, $a1, %lo(D_80069FF0)
    /* 2360660 8006E8C4 6C6F000C */  jal        func_8001BDB0
    /* 2360664 8006E8C8 1000A427 */   addiu     $a0, $sp, 0x10
    /* 2360668 8006E8CC 1000A427 */  addiu      $a0, $sp, 0x10
    /* 236066C 8006E8D0 1800A28F */  lw         $v0, 0x18($sp)
    /* 2360670 8006E8D4 000C0524 */  addiu      $a1, $zero, 0xC00
    /* 2360674 8006E8D8 00044224 */  addiu      $v0, $v0, 0x400
    /* 2360678 8006E8DC A1FB000C */  jal        func_8003EE84
    /* 236067C 8006E8E0 1800A2AF */   sw        $v0, 0x18($sp)
    /* 2360680 8006E8E4 0780013C */  lui        $at, %hi(D_8006A018)
    /* 2360684 8006E8E8 18A022AC */  sw         $v0, %lo(D_8006A018)($at)
    /* 2360688 8006E8EC 0780023C */  lui        $v0, %hi(D_8006A13C)
    /* 236068C 8006E8F0 3CA1428C */  lw         $v0, %lo(D_8006A13C)($v0)
    /* 2360690 8006E8F4 0780033C */  lui        $v1, %hi(D_80069FF8)
    /* 2360694 8006E8F8 F89F638C */  lw         $v1, %lo(D_80069FF8)($v1)
    /* 2360698 8006E8FC 83110200 */  sra        $v0, $v0, 6
    /* 236069C 8006E900 23186200 */  subu       $v1, $v1, $v0
    /* 23606A0 8006E904 0780013C */  lui        $at, %hi(D_80069FF8)
    /* 23606A4 8006E908 F89F23AC */  sw         $v1, %lo(D_80069FF8)($at)
  .Llevel_32_8006E90C:
    /* 23606A8 8006E90C 2000BF8F */  lw         $ra, 0x20($sp)
    /* 23606AC 8006E910 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 23606B0 8006E914 0800E003 */  jr         $ra
    /* 23606B4 8006E918 00000000 */   nop
endlabel func_level_32_8006E76C
