.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_32_8006D268

dlabel jtbl_level_32_8006D268
    /* 235F004 8006D268 58DC0680 */ .word .Llevel_32_8006DC58
    /* 235F008 8006D26C 08DC0680 */ .word .Llevel_32_8006DC08
    /* 235F00C 8006D270 6CDF0680 */ .word .Llevel_32_8006DF6C
    /* 235F010 8006D274 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F014 8006D278 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F018 8006D27C 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F01C 8006D280 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F020 8006D284 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F024 8006D288 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F028 8006D28C 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F02C 8006D290 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F030 8006D294 04E00680 */ .word .Llevel_32_8006E004
    /* 235F034 8006D298 FCE00680 */ .word .Llevel_32_8006E0FC
    /* 235F038 8006D29C 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F03C 8006D2A0 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F040 8006D2A4 1CE10680 */ .word .Llevel_32_8006E11C
    /* 235F044 8006D2A8 1CE10680 */ .word .Llevel_32_8006E11C
    /* 235F048 8006D2AC 1CE10680 */ .word .Llevel_32_8006E11C
    /* 235F04C 8006D2B0 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F050 8006D2B4 4CE70680 */ .word .Llevel_32_8006E74C
    /* 235F054 8006D2B8 08DC0680 */ .word .Llevel_32_8006DC08
    /* 235F058 8006D2BC 00000000 */ .word 0x00000000
enddlabel jtbl_level_32_8006D268


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_32_8006DBA8, 0xBC4

glabel func_level_32_8006DBA8
    /* 235F944 8006DBA8 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 235F948 8006DBAC 00210400 */  sll        $a0, $a0, 4
    /* 235F94C 8006DBB0 0780023C */  lui        $v0, %hi(D_800683B0)
    /* 235F950 8006DBB4 B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* 235F954 8006DBB8 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 235F958 8006DBBC 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 235F95C 8006DBC0 21208200 */  addu       $a0, $a0, $v0
    /* 235F960 8006DBC4 5800BFAF */  sw         $ra, 0x58($sp)
    /* 235F964 8006DBC8 5400B3AF */  sw         $s3, 0x54($sp)
    /* 235F968 8006DBCC 5000B2AF */  sw         $s2, 0x50($sp)
    /* 235F96C 8006DBD0 4C00B1AF */  sw         $s1, 0x4C($sp)
    /* 235F970 8006DBD4 4800B0AF */  sw         $s0, 0x48($sp)
    /* 235F974 8006DBD8 0680013C */  lui        $at, %hi(D_80066F38)
    /* 235F978 8006DBDC 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* 235F97C 8006DBE0 EEFF6324 */  addiu      $v1, $v1, -0x12
    /* 235F980 8006DBE4 1500622C */  sltiu      $v0, $v1, 0x15
    /* 235F984 8006DBE8 D8024010 */  beqz       $v0, .Llevel_32_8006E74C
    /* 235F988 8006DBEC 80100300 */   sll       $v0, $v1, 2
    /* 235F98C 8006DBF0 0780013C */  lui        $at, %hi(jtbl_level_32_8006D268)
    /* 235F990 8006DBF4 21082200 */  addu       $at, $at, $v0
    /* 235F994 8006DBF8 68D2228C */  lw         $v0, %lo(jtbl_level_32_8006D268)($at)
    /* 235F998 8006DBFC 00000000 */  nop
    /* 235F99C 8006DC00 08004000 */  jr         $v0
    /* 235F9A0 8006DC04 00000000 */   nop
  .Llevel_32_8006DC08:
    /* 235F9A4 8006DC08 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 235F9A8 8006DC0C 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 235F9AC 8006DC10 686F000C */  jal        func_8001BDA0
    /* 235F9B0 8006DC14 21200002 */   addu      $a0, $s0, $zero
    /* 235F9B4 8006DC18 686F000C */  jal        func_8001BDA0
    /* 235F9B8 8006DC1C 0C000426 */   addiu     $a0, $s0, 0xC
    /* 235F9BC 8006DC20 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 235F9C0 8006DC24 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 235F9C4 8006DC28 07000224 */  addiu      $v0, $zero, 0x7
    /* 235F9C8 8006DC2C C7026210 */  beq        $v1, $v0, .Llevel_32_8006E74C
    /* 235F9CC 8006DC30 00000000 */   nop
    /* 235F9D0 8006DC34 DBAC000C */  jal        func_8002B36C
    /* 235F9D4 8006DC38 00120424 */   addiu     $a0, $zero, 0x1200
    /* 235F9D8 8006DC3C 1AAF000C */  jal        func_8002BC68
    /* 235F9DC 8006DC40 00000000 */   nop
    /* 235F9E0 8006DC44 5A000424 */  addiu      $a0, $zero, 0x5A
    /* 235F9E4 8006DC48 C9AE000C */  jal        func_8002BB24
    /* 235F9E8 8006DC4C 10000524 */   addiu     $a1, $zero, 0x10
    /* 235F9EC 8006DC50 D3B90108 */  j          .Llevel_32_8006E74C
    /* 235F9F0 8006DC54 00000000 */   nop
  .Llevel_32_8006DC58:
    /* 235F9F4 8006DC58 0780113C */  lui        $s1, %hi(D_80069FF8)
    /* 235F9F8 8006DC5C F89F3126 */  addiu      $s1, $s1, %lo(D_80069FF8)
    /* 235F9FC 8006DC60 0000238E */  lw         $v1, 0x0($s1)
    /* 235FA00 8006DC64 4401228E */  lw         $v0, 0x144($s1)
    /* 235FA04 8006DC68 00000000 */  nop
    /* 235FA08 8006DC6C 23206200 */  subu       $a0, $v1, $v0
    /* 235FA0C 8006DC70 00048228 */  slti       $v0, $a0, 0x400
    /* 235FA10 8006DC74 28004010 */  beqz       $v0, .Llevel_32_8006DD18
    /* 235FA14 8006DC78 00000000 */   nop
    /* 235FA18 8006DC7C 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 235FA1C 8006DC80 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 235FA20 8006DC84 00000000 */  nop
    /* 235FA24 8006DC88 80004224 */  addiu      $v0, $v0, 0x80
    /* 235FA28 8006DC8C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 235FA2C 8006DC90 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 235FA30 8006DC94 C1124228 */  slti       $v0, $v0, 0x12C1
    /* 235FA34 8006DC98 04004014 */  bnez       $v0, .Llevel_32_8006DCAC
    /* 235FA38 8006DC9C 18008400 */   mult      $a0, $a0
    /* 235FA3C 8006DCA0 C0120224 */  addiu      $v0, $zero, 0x12C0
    /* 235FA40 8006DCA4 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 235FA44 8006DCA8 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_32_8006DCAC:
    /* 235FA48 8006DCAC 1000A427 */  addiu      $a0, $sp, 0x10
    /* 235FA4C 8006DCB0 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 235FA50 8006DCB4 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 235FA54 8006DCB8 0780033C */  lui        $v1, %hi(D_8006A140)
    /* 235FA58 8006DCBC 40A1638C */  lw         $v1, %lo(D_8006A140)($v1)
    /* 235FA5C 8006DCC0 12480000 */  mflo       $t1
    /* 235FA60 8006DCC4 C3120900 */  sra        $v0, $t1, 11
    /* 235FA64 8006DCC8 21804300 */  addu       $s0, $v0, $v1
    /* 235FA68 8006DCCC 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 235FA6C 8006DCD0 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 235FA70 8006DCD4 6C6F000C */  jal        func_8001BDB0
    /* 235FA74 8006DCD8 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 235FA78 8006DCDC 1000A427 */  addiu      $a0, $sp, 0x10
    /* 235FA7C 8006DCE0 21288000 */  addu       $a1, $a0, $zero
    /* 235FA80 8006DCE4 806F000C */  jal        func_8001BE00
    /* 235FA84 8006DCE8 F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 235FA88 8006DCEC 1000A427 */  addiu      $a0, $sp, 0x10
    /* 235FA8C 8006DCF0 21280000 */  addu       $a1, $zero, $zero
    /* 235FA90 8006DCF4 886E000C */  jal        func_8001BA20
    /* 235FA94 8006DCF8 1800A0AF */   sw        $zero, 0x18($sp)
    /* 235FA98 8006DCFC 21404000 */  addu       $t0, $v0, $zero
    /* 235FA9C 8006DD00 01040229 */  slti       $v0, $t0, 0x401
    /* 235FAA0 8006DD04 91004014 */  bnez       $v0, .Llevel_32_8006DF4C
    /* 235FAA4 8006DD08 1000A427 */   addiu     $a0, $sp, 0x10
    /* 235FAA8 8006DD0C 21280001 */  addu       $a1, $t0, $zero
    /* 235FAAC 8006DD10 D1B70108 */  j          .Llevel_32_8006DF44
    /* 235FAB0 8006DD14 00040624 */   addiu     $a2, $zero, 0x400
  .Llevel_32_8006DD18:
    /* 235FAB4 8006DD18 0780053C */  lui        $a1, %hi(D_8006A144)
    /* 235FAB8 8006DD1C 44A1A58C */  lw         $a1, %lo(D_8006A144)($a1)
    /* 235FABC 8006DD20 00000000 */  nop
    /* 235FAC0 8006DD24 23106500 */  subu       $v0, $v1, $a1
    /* 235FAC4 8006DD28 00FC4228 */  slti       $v0, $v0, -0x400
    /* 235FAC8 8006DD2C 49004010 */  beqz       $v0, .Llevel_32_8006DE54
    /* 235FACC 8006DD30 2340A300 */   subu      $t0, $a1, $v1
    /* 235FAD0 8006DD34 0780023C */  lui        $v0, %hi(D_8006A044)
    /* 235FAD4 8006DD38 44A0428C */  lw         $v0, %lo(D_8006A044)($v0)
    /* 235FAD8 8006DD3C 00000000 */  nop
    /* 235FADC 8006DD40 08004014 */  bnez       $v0, .Llevel_32_8006DD64
    /* 235FAE0 8006DD44 01000324 */   addiu     $v1, $zero, 0x1
    /* 235FAE4 8006DD48 0780023C */  lui        $v0, %hi(D_8006A140)
    /* 235FAE8 8006DD4C 40A1428C */  lw         $v0, %lo(D_8006A140)($v0)
    /* 235FAEC 8006DD50 0780013C */  lui        $at, %hi(D_8006A044)
    /* 235FAF0 8006DD54 44A023AC */  sw         $v1, %lo(D_8006A044)($at)
    /* 235FAF4 8006DD58 00024224 */  addiu      $v0, $v0, 0x200
    /* 235FAF8 8006DD5C 0780013C */  lui        $at, %hi(D_8006A140)
    /* 235FAFC 8006DD60 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
  .Llevel_32_8006DD64:
    /* 235FB00 8006DD64 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 235FB04 8006DD68 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 235FB08 8006DD6C 00000000 */  nop
    /* 235FB0C 8006DD70 80004224 */  addiu      $v0, $v0, 0x80
    /* 235FB10 8006DD74 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 235FB14 8006DD78 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 235FB18 8006DD7C C1124228 */  slti       $v0, $v0, 0x12C1
    /* 235FB1C 8006DD80 03004014 */  bnez       $v0, .Llevel_32_8006DD90
    /* 235FB20 8006DD84 C0120224 */   addiu     $v0, $zero, 0x12C0
    /* 235FB24 8006DD88 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 235FB28 8006DD8C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_32_8006DD90:
    /* 235FB2C 8006DD90 0780023C */  lui        $v0, %hi(D_8006A148)
    /* 235FB30 8006DD94 48A1428C */  lw         $v0, %lo(D_8006A148)($v0)
    /* 235FB34 8006DD98 00FC8824 */  addiu      $t0, $a0, -0x400
    /* 235FB38 8006DD9C 18004800 */  mult       $v0, $t0
    /* 235FB3C 8006DDA0 12180000 */  mflo       $v1
    /* 235FB40 8006DDA4 0780023C */  lui        $v0, %hi(D_8006A14C)
    /* 235FB44 8006DDA8 4CA1428C */  lw         $v0, %lo(D_8006A14C)($v0)
    /* 235FB48 8006DDAC 00000000 */  nop
    /* 235FB4C 8006DDB0 1A006200 */  div        $zero, $v1, $v0
    /* 235FB50 8006DDB4 02004014 */  bnez       $v0, .Llevel_32_8006DDC0
    /* 235FB54 8006DDB8 00000000 */   nop
    /* 235FB58 8006DDBC 0D000700 */  break      7
  .Llevel_32_8006DDC0:
    /* 235FB5C 8006DDC0 FFFF0124 */  addiu      $at, $zero, -0x1
    /* 235FB60 8006DDC4 04004114 */  bne        $v0, $at, .Llevel_32_8006DDD8
    /* 235FB64 8006DDC8 0080013C */   lui       $at, (0x80000000 >> 16)
    /* 235FB68 8006DDCC 02006114 */  bne        $v1, $at, .Llevel_32_8006DDD8
    /* 235FB6C 8006DDD0 00000000 */   nop
    /* 235FB70 8006DDD4 0D000600 */  break      6
  .Llevel_32_8006DDD8:
    /* 235FB74 8006DDD8 12100000 */  mflo       $v0
    /* 235FB78 8006DDDC 1000A427 */  addiu      $a0, $sp, 0x10
    /* 235FB7C 8006DDE0 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 235FB80 8006DDE4 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 235FB84 8006DDE8 0780033C */  lui        $v1, %hi(D_8006A140)
    /* 235FB88 8006DDEC 40A1638C */  lw         $v1, %lo(D_8006A140)($v1)
    /* 235FB8C 8006DDF0 00000000 */  nop
    /* 235FB90 8006DDF4 21806200 */  addu       $s0, $v1, $v0
    /* 235FB94 8006DDF8 80120800 */  sll        $v0, $t0, 10
    /* 235FB98 8006DDFC 83120200 */  sra        $v0, $v0, 10
    /* 235FB9C 8006DE00 21100202 */  addu       $v0, $s0, $v0
    /* 235FBA0 8006DE04 FF0F5030 */  andi       $s0, $v0, 0xFFF
    /* 235FBA4 8006DE08 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 235FBA8 8006DE0C 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 235FBAC 8006DE10 6C6F000C */  jal        func_8001BDB0
    /* 235FBB0 8006DE14 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 235FBB4 8006DE18 1000A427 */  addiu      $a0, $sp, 0x10
    /* 235FBB8 8006DE1C 21288000 */  addu       $a1, $a0, $zero
    /* 235FBBC 8006DE20 806F000C */  jal        func_8001BE00
    /* 235FBC0 8006DE24 F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 235FBC4 8006DE28 1000A427 */  addiu      $a0, $sp, 0x10
    /* 235FBC8 8006DE2C 21280000 */  addu       $a1, $zero, $zero
    /* 235FBCC 8006DE30 886E000C */  jal        func_8001BA20
    /* 235FBD0 8006DE34 1800A0AF */   sw        $zero, 0x18($sp)
    /* 235FBD4 8006DE38 21404000 */  addu       $t0, $v0, $zero
    /* 235FBD8 8006DE3C 01040229 */  slti       $v0, $t0, 0x401
    /* 235FBDC 8006DE40 42004014 */  bnez       $v0, .Llevel_32_8006DF4C
    /* 235FBE0 8006DE44 1000A427 */   addiu     $a0, $sp, 0x10
    /* 235FBE4 8006DE48 21280001 */  addu       $a1, $t0, $zero
    /* 235FBE8 8006DE4C D1B70108 */  j          .Llevel_32_8006DF44
    /* 235FBEC 8006DE50 00040624 */   addiu     $a2, $zero, 0x400
  .Llevel_32_8006DE54:
    /* 235FBF0 8006DE54 80180800 */  sll        $v1, $t0, 2
    /* 235FBF4 8006DE58 21186800 */  addu       $v1, $v1, $t0
    /* 235FBF8 8006DE5C 00110300 */  sll        $v0, $v1, 4
    /* 235FBFC 8006DE60 23104300 */  subu       $v0, $v0, $v1
    /* 235FC00 8006DE64 80110200 */  sll        $v0, $v0, 6
    /* 235FC04 8006DE68 0780063C */  lui        $a2, %hi(D_8006A208)
    /* 235FC08 8006DE6C 08A2C68C */  lw         $a2, %lo(D_8006A208)($a2)
    /* 235FC0C 8006DE70 83120200 */  sra        $v0, $v0, 10
    /* 235FC10 8006DE74 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 235FC14 8006DE78 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 235FC18 8006DE7C 4600C790 */  lbu        $a3, 0x46($a2)
    /* 235FC1C 8006DE80 0780033C */  lui        $v1, %hi(D_8006A150)
    /* 235FC20 8006DE84 50A1638C */  lw         $v1, %lo(D_8006A150)($v1)
    /* 235FC24 8006DE88 40100700 */  sll        $v0, $a3, 1
    /* 235FC28 8006DE8C 0680013C */  lui        $at, %hi(D_80061C58)
    /* 235FC2C 8006DE90 21082200 */  addu       $at, $at, $v0
    /* 235FC30 8006DE94 581C2284 */  lh         $v0, %lo(D_80061C58)($at)
    /* 235FC34 8006DE98 00046324 */  addiu      $v1, $v1, 0x400
    /* 235FC38 8006DE9C 18006200 */  mult       $v1, $v0
    /* 235FC3C 8006DEA0 12500000 */  mflo       $t2
    /* 235FC40 8006DEA4 00000000 */  nop
    /* 235FC44 8006DEA8 00000000 */  nop
    /* 235FC48 8006DEAC 18000801 */  mult       $t0, $t0
    /* 235FC4C 8006DEB0 03130A00 */  sra        $v0, $t2, 12
    /* 235FC50 8006DEB4 1000A2AF */  sw         $v0, 0x10($sp)
    /* 235FC54 8006DEB8 4600C290 */  lbu        $v0, 0x46($a2)
    /* 235FC58 8006DEBC 00000000 */  nop
    /* 235FC5C 8006DEC0 40100200 */  sll        $v0, $v0, 1
    /* 235FC60 8006DEC4 12400000 */  mflo       $t0
    /* 235FC64 8006DEC8 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 235FC68 8006DECC 21082200 */  addu       $at, $at, $v0
    /* 235FC6C 8006DED0 D81B2284 */  lh         $v0, %lo(D_80061BD8)($at)
    /* 235FC70 8006DED4 00000000 */  nop
    /* 235FC74 8006DED8 18006200 */  mult       $v1, $v0
    /* 235FC78 8006DEDC 1000A427 */  addiu      $a0, $sp, 0x10
    /* 235FC7C 8006DEE0 21288000 */  addu       $a1, $a0, $zero
    /* 235FC80 8006DEE4 00390700 */  sll        $a3, $a3, 4
    /* 235FC84 8006DEE8 0C00C624 */  addiu      $a2, $a2, 0xC
    /* 235FC88 8006DEEC C3120800 */  sra        $v0, $t0, 11
    /* 235FC8C 8006DEF0 2380E200 */  subu       $s0, $a3, $v0
    /* 235FC90 8006DEF4 12180000 */  mflo       $v1
    /* 235FC94 8006DEF8 03130300 */  sra        $v0, $v1, 12
    /* 235FC98 8006DEFC 736F000C */  jal        func_8001BDCC
    /* 235FC9C 8006DF00 1400A2AF */   sw        $v0, 0x14($sp)
    /* 235FCA0 8006DF04 1000A427 */  addiu      $a0, $sp, 0x10
    /* 235FCA4 8006DF08 21288000 */  addu       $a1, $a0, $zero
    /* 235FCA8 8006DF0C 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 235FCAC 8006DF10 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 235FCB0 8006DF14 806F000C */  jal        func_8001BE00
    /* 235FCB4 8006DF18 F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 235FCB8 8006DF1C 1000A427 */  addiu      $a0, $sp, 0x10
    /* 235FCBC 8006DF20 21280000 */  addu       $a1, $zero, $zero
    /* 235FCC0 8006DF24 886E000C */  jal        func_8001BA20
    /* 235FCC4 8006DF28 1800A0AF */   sw        $zero, 0x18($sp)
    /* 235FCC8 8006DF2C 21404000 */  addu       $t0, $v0, $zero
    /* 235FCCC 8006DF30 01080229 */  slti       $v0, $t0, 0x801
    /* 235FCD0 8006DF34 05004014 */  bnez       $v0, .Llevel_32_8006DF4C
    /* 235FCD4 8006DF38 1000A427 */   addiu     $a0, $sp, 0x10
    /* 235FCD8 8006DF3C 21280001 */  addu       $a1, $t0, $zero
    /* 235FCDC 8006DF40 00080624 */  addiu      $a2, $zero, 0x800
  .Llevel_32_8006DF44:
    /* 235FCE0 8006DF44 316F000C */  jal        func_8001BCC4
    /* 235FCE4 8006DF48 00000000 */   nop
  .Llevel_32_8006DF4C:
    /* 235FCE8 8006DF4C 1000A28F */  lw         $v0, 0x10($sp)
    /* 235FCEC 8006DF50 1400A38F */  lw         $v1, 0x14($sp)
    /* 235FCF0 8006DF54 0780013C */  lui        $at, %hi(D_8006A084)
    /* 235FCF4 8006DF58 84A022AC */  sw         $v0, %lo(D_8006A084)($at)
    /* 235FCF8 8006DF5C 0780013C */  lui        $at, %hi(D_8006A088)
    /* 235FCFC 8006DF60 88A023AC */  sw         $v1, %lo(D_8006A088)($at)
    /* 235FD00 8006DF64 D3B90108 */  j          .Llevel_32_8006E74C
    /* 235FD04 8006DF68 00000000 */   nop
  .Llevel_32_8006DF6C:
    /* 235FD08 8006DF6C 0780033C */  lui        $v1, %hi(D_8006A08C)
    /* 235FD0C 8006DF70 8CA06324 */  addiu      $v1, $v1, %lo(D_8006A08C)
    /* 235FD10 8006DF74 0000628C */  lw         $v0, 0x0($v1)
    /* 235FD14 8006DF78 00000000 */  nop
    /* 235FD18 8006DF7C C0FE4224 */  addiu      $v0, $v0, -0x140
    /* 235FD1C 8006DF80 000062AC */  sw         $v0, 0x0($v1)
    /* 235FD20 8006DF84 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 235FD24 8006DF88 02004010 */  beqz       $v0, .Llevel_32_8006DF94
    /* 235FD28 8006DF8C 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 235FD2C 8006DF90 000062AC */  sw         $v0, 0x0($v1)
  .Llevel_32_8006DF94:
    /* 235FD30 8006DF94 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 235FD34 8006DF98 84A0848C */  lw         $a0, %lo(D_8006A084)($a0)
    /* 235FD38 8006DF9C 0780053C */  lui        $a1, %hi(D_8006A088)
    /* 235FD3C 8006DFA0 88A0A58C */  lw         $a1, %lo(D_8006A088)($a1)
    /* 235FD40 8006DFA4 2E6D000C */  jal        func_8001B4B8
    /* 235FD44 8006DFA8 01000624 */   addiu     $a2, $zero, 0x1
    /* 235FD48 8006DFAC 0780043C */  lui        $a0, %hi(D_8006A05C)
    /* 235FD4C 8006DFB0 5CA0848C */  lw         $a0, %lo(D_8006A05C)($a0)
    /* 235FD50 8006DFB4 00000000 */  nop
    /* 235FD54 8006DFB8 23104400 */  subu       $v0, $v0, $a0
    /* 235FD58 8006DFBC FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 235FD5C 8006DFC0 01086228 */  slti       $v0, $v1, 0x801
    /* 235FD60 8006DFC4 03004014 */  bnez       $v0, .Llevel_32_8006DFD4
    /* 235FD64 8006DFC8 F0FF6228 */   slti      $v0, $v1, -0x10
    /* 235FD68 8006DFCC 00F06324 */  addiu      $v1, $v1, -0x1000
    /* 235FD6C 8006DFD0 F0FF6228 */  slti       $v0, $v1, -0x10
  .Llevel_32_8006DFD4:
    /* 235FD70 8006DFD4 03004010 */  beqz       $v0, .Llevel_32_8006DFE4
    /* 235FD74 8006DFD8 11006228 */   slti      $v0, $v1, 0x11
    /* 235FD78 8006DFDC F0FF0324 */  addiu      $v1, $zero, -0x10
    /* 235FD7C 8006DFE0 11006228 */  slti       $v0, $v1, 0x11
  .Llevel_32_8006DFE4:
    /* 235FD80 8006DFE4 03004014 */  bnez       $v0, .Llevel_32_8006DFF4
    /* 235FD84 8006DFE8 21108300 */   addu      $v0, $a0, $v1
    /* 235FD88 8006DFEC 10000324 */  addiu      $v1, $zero, 0x10
    /* 235FD8C 8006DFF0 21108300 */  addu       $v0, $a0, $v1
  .Llevel_32_8006DFF4:
    /* 235FD90 8006DFF4 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 235FD94 8006DFF8 5CA022AC */  sw         $v0, %lo(D_8006A05C)($at)
    /* 235FD98 8006DFFC D3B90108 */  j          .Llevel_32_8006E74C
    /* 235FD9C 8006E000 00000000 */   nop
  .Llevel_32_8006E004:
    /* 235FDA0 8006E004 2000B027 */  addiu      $s0, $sp, 0x20
    /* 235FDA4 8006E008 686F000C */  jal        func_8001BDA0
    /* 235FDA8 8006E00C 21200002 */   addu      $a0, $s0, $zero
    /* 235FDAC 8006E010 21200002 */  addu       $a0, $s0, $zero
    /* 235FDB0 8006E014 21280002 */  addu       $a1, $s0, $zero
    /* 235FDB4 8006E018 0780113C */  lui        $s1, %hi(D_8006A084)
    /* 235FDB8 8006E01C 84A03126 */  addiu      $s1, $s1, %lo(D_8006A084)
    /* 235FDBC 8006E020 806F000C */  jal        func_8001BE00
    /* 235FDC0 8006E024 21302002 */   addu      $a2, $s1, $zero
    /* 235FDC4 8006E028 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 235FDC8 8006E02C B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 235FDCC 8006E030 00000000 */  nop
    /* 235FDD0 8006E034 11004010 */  beqz       $v0, .Llevel_32_8006E07C
    /* 235FDD4 8006E038 21200002 */   addu      $a0, $s0, $zero
    /* 235FDD8 8006E03C 2800A0AF */  sw         $zero, 0x28($sp)
    /* 235FDDC 8006E040 886E000C */  jal        func_8001BA20
    /* 235FDE0 8006E044 21280000 */   addu      $a1, $zero, $zero
    /* 235FDE4 8006E048 21284000 */  addu       $a1, $v0, $zero
    /* 235FDE8 8006E04C 4100A228 */  slti       $v0, $a1, 0x41
    /* 235FDEC 8006E050 05004014 */  bnez       $v0, .Llevel_32_8006E068
    /* 235FDF0 8006E054 40FF0224 */   addiu     $v0, $zero, -0xC0
    /* 235FDF4 8006E058 21200002 */  addu       $a0, $s0, $zero
    /* 235FDF8 8006E05C 316F000C */  jal        func_8001BCC4
    /* 235FDFC 8006E060 40000624 */   addiu     $a2, $zero, 0x40
    /* 235FE00 8006E064 40FF0224 */  addiu      $v0, $zero, -0xC0
  .Llevel_32_8006E068:
    /* 235FE04 8006E068 2800A2AF */  sw         $v0, 0x28($sp)
    /* 235FE08 8006E06C F4FF2426 */  addiu      $a0, $s1, -0xC
    /* 235FE0C 8006E070 21282002 */  addu       $a1, $s1, $zero
    /* 235FE10 8006E074 2FB80108 */  j          .Llevel_32_8006E0BC
    /* 235FE14 8006E078 21300002 */   addu      $a2, $s0, $zero
  .Llevel_32_8006E07C:
    /* 235FE18 8006E07C 886E000C */  jal        func_8001BA20
    /* 235FE1C 8006E080 01000524 */   addiu     $a1, $zero, 0x1
    /* 235FE20 8006E084 21284000 */  addu       $a1, $v0, $zero
    /* 235FE24 8006E088 0101A228 */  slti       $v0, $a1, 0x101
    /* 235FE28 8006E08C 05004014 */  bnez       $v0, .Llevel_32_8006E0A4
    /* 235FE2C 8006E090 21202002 */   addu      $a0, $s1, $zero
    /* 235FE30 8006E094 21200002 */  addu       $a0, $s0, $zero
    /* 235FE34 8006E098 316F000C */  jal        func_8001BCC4
    /* 235FE38 8006E09C 00010624 */   addiu     $a2, $zero, 0x100
    /* 235FE3C 8006E0A0 21202002 */  addu       $a0, $s1, $zero
  .Llevel_32_8006E0A4:
    /* 235FE40 8006E0A4 21282002 */  addu       $a1, $s1, $zero
    /* 235FE44 8006E0A8 736F000C */  jal        func_8001BDCC
    /* 235FE48 8006E0AC 21300002 */   addu      $a2, $s0, $zero
    /* 235FE4C 8006E0B0 F4FF2426 */  addiu      $a0, $s1, -0xC
    /* 235FE50 8006E0B4 21282002 */  addu       $a1, $s1, $zero
    /* 235FE54 8006E0B8 5C00A624 */  addiu      $a2, $a1, 0x5C
  .Llevel_32_8006E0BC:
    /* 235FE58 8006E0BC 736F000C */  jal        func_8001BDCC
    /* 235FE5C 8006E0C0 00000000 */   nop
    /* 235FE60 8006E0C4 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 235FE64 8006E0C8 84A08424 */  addiu      $a0, $a0, %lo(D_8006A084)
    /* 235FE68 8006E0CC 6C6F000C */  jal        func_8001BDB0
    /* 235FE6C 8006E0D0 21288000 */   addu      $a1, $a0, $zero
    /* 235FE70 8006E0D4 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 235FE74 8006E0D8 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 235FE78 8006E0DC 00000000 */  nop
    /* 235FE7C 8006E0E0 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 235FE80 8006E0E4 99014010 */  beqz       $v0, .Llevel_32_8006E74C
    /* 235FE84 8006E0E8 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 235FE88 8006E0EC 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 235FE8C 8006E0F0 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 235FE90 8006E0F4 D3B90108 */  j          .Llevel_32_8006E74C
    /* 235FE94 8006E0F8 00000000 */   nop
  .Llevel_32_8006E0FC:
    /* 235FE98 8006E0FC 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 235FE9C 8006E100 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 235FEA0 8006E104 686F000C */  jal        func_8001BDA0
    /* 235FEA4 8006E108 21200002 */   addu      $a0, $s0, $zero
    /* 235FEA8 8006E10C 686F000C */  jal        func_8001BDA0
    /* 235FEAC 8006E110 0C000426 */   addiu     $a0, $s0, 0xC
    /* 235FEB0 8006E114 D3B90108 */  j          .Llevel_32_8006E74C
    /* 235FEB4 8006E118 00000000 */   nop
  .Llevel_32_8006E11C:
    /* 235FEB8 8006E11C 3000A427 */  addiu      $a0, $sp, 0x30
    /* 235FEBC 8006E120 0780113C */  lui        $s1, %hi(D_8006A144)
    /* 235FEC0 8006E124 44A13126 */  addiu      $s1, $s1, %lo(D_8006A144)
    /* 235FEC4 8006E128 21282002 */  addu       $a1, $s1, $zero
    /* 235FEC8 8006E12C A5AD000C */  jal        func_8002B694
    /* 235FECC 8006E130 21300000 */   addu      $a2, $zero, $zero
    /* 235FED0 8006E134 3400A28F */  lw         $v0, 0x34($sp)
    /* 235FED4 8006E138 0780043C */  lui        $a0, %hi(D_8006A08C)
    /* 235FED8 8006E13C 8CA0848C */  lw         $a0, %lo(D_8006A08C)($a0)
    /* 235FEDC 8006E140 23100200 */  negu       $v0, $v0
    /* 235FEE0 8006E144 80180200 */  sll        $v1, $v0, 2
    /* 235FEE4 8006E148 21186200 */  addu       $v1, $v1, $v0
    /* 235FEE8 8006E14C 80180300 */  sll        $v1, $v1, 2
    /* 235FEEC 8006E150 C3910300 */  sra        $s2, $v1, 7
    /* 235FEF0 8006E154 C3200400 */  sra        $a0, $a0, 3
    /* 235FEF4 8006E158 3000A38F */  lw         $v1, 0x30($sp)
    /* 235FEF8 8006E15C 00FC8424 */  addiu      $a0, $a0, -0x400
    /* 235FEFC 8006E160 4000A4AF */  sw         $a0, 0x40($sp)
    /* 235FF00 8006E164 80100300 */  sll        $v0, $v1, 2
    /* 235FF04 8006E168 21104300 */  addu       $v0, $v0, $v1
    /* 235FF08 8006E16C 80100200 */  sll        $v0, $v0, 2
    /* 235FF0C 8006E170 24008104 */  bgez       $a0, .Llevel_32_8006E204
    /* 235FF10 8006E174 C3990200 */   sra       $s3, $v0, 7
    /* 235FF14 8006E178 3800B027 */  addiu      $s0, $sp, 0x38
    /* 235FF18 8006E17C 21200002 */  addu       $a0, $s0, $zero
    /* 235FF1C 8006E180 21280002 */  addu       $a1, $s0, $zero
    /* 235FF20 8006E184 ACFE3126 */  addiu      $s1, $s1, -0x154
    /* 235FF24 8006E188 21302002 */  addu       $a2, $s1, $zero
    /* 235FF28 8006E18C 0780023C */  lui        $v0, %hi(D_8006A084)
    /* 235FF2C 8006E190 84A0428C */  lw         $v0, %lo(D_8006A084)($v0)
    /* 235FF30 8006E194 0780033C */  lui        $v1, %hi(D_8006A088)
    /* 235FF34 8006E198 88A0638C */  lw         $v1, %lo(D_8006A088)($v1)
    /* 235FF38 8006E19C C3100200 */  sra        $v0, $v0, 3
    /* 235FF3C 8006E1A0 C3180300 */  sra        $v1, $v1, 3
    /* 235FF40 8006E1A4 3800A2AF */  sw         $v0, 0x38($sp)
    /* 235FF44 8006E1A8 736F000C */  jal        func_8001BDCC
    /* 235FF48 8006E1AC 3C00A3AF */   sw        $v1, 0x3C($sp)
    /* 235FF4C 8006E1B0 21202002 */  addu       $a0, $s1, $zero
    /* 235FF50 8006E1B4 21280002 */  addu       $a1, $s0, $zero
    /* 235FF54 8006E1B8 867D000C */  jal        func_8001F618
    /* 235FF58 8006E1BC 02000624 */   addiu     $a2, $zero, 0x2
    /* 235FF5C 8006E1C0 11004014 */  bnez       $v0, .Llevel_32_8006E208
    /* 235FF60 8006E1C4 19000224 */   addiu     $v0, $zero, 0x19
    /* 235FF64 8006E1C8 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 235FF68 8006E1CC F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 235FF6C 8006E1D0 0780033C */  lui        $v1, %hi(D_8006AB78)
    /* 235FF70 8006E1D4 78AB638C */  lw         $v1, %lo(D_8006AB78)($v1)
    /* 235FF74 8006E1D8 00000000 */  nop
    /* 235FF78 8006E1DC 23104300 */  subu       $v0, $v0, $v1
    /* 235FF7C 8006E1E0 C3100200 */  sra        $v0, $v0, 3
    /* 235FF80 8006E1E4 3400A2AF */  sw         $v0, 0x34($sp)
    /* 235FF84 8006E1E8 0B004228 */  slti       $v0, $v0, 0xB
    /* 235FF88 8006E1EC 02004014 */  bnez       $v0, .Llevel_32_8006E1F8
    /* 235FF8C 8006E1F0 0A000224 */   addiu     $v0, $zero, 0xA
    /* 235FF90 8006E1F4 3400A2AF */  sw         $v0, 0x34($sp)
  .Llevel_32_8006E1F8:
    /* 235FF94 8006E1F8 3400A28F */  lw         $v0, 0x34($sp)
    /* 235FF98 8006E1FC 00000000 */  nop
    /* 235FF9C 8006E200 21904202 */  addu       $s2, $s2, $v0
  .Llevel_32_8006E204:
    /* 235FFA0 8006E204 19000224 */  addiu      $v0, $zero, 0x19
  .Llevel_32_8006E208:
    /* 235FFA4 8006E208 0680033C */  lui        $v1, %hi(D_80066F90)
    /* 235FFA8 8006E20C 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* 235FFAC 8006E210 0780043C */  lui        $a0, %hi(D_8006A0F0)
    /* 235FFB0 8006E214 F0A0848C */  lw         $a0, %lo(D_8006A0F0)($a0)
    /* 235FFB4 8006E218 07006214 */  bne        $v1, $v0, .Llevel_32_8006E238
    /* 235FFB8 8006E21C 00000000 */   nop
    /* 235FFBC 8006E220 0780023C */  lui        $v0, %hi(D_8006ABF8)
    /* 235FFC0 8006E224 F8AB4290 */  lbu        $v0, %lo(D_8006ABF8)($v0)
    /* 235FFC4 8006E228 00000000 */  nop
    /* 235FFC8 8006E22C 02004010 */  beqz       $v0, .Llevel_32_8006E238
    /* 235FFCC 8006E230 00000000 */   nop
    /* 235FFD0 8006E234 08CF0434 */  ori        $a0, $zero, 0xCF08
  .Llevel_32_8006E238:
    /* 235FFD4 8006E238 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 235FFD8 8006E23C F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 235FFDC 8006E240 00000000 */  nop
    /* 235FFE0 8006E244 23188200 */  subu       $v1, $a0, $v0
    /* 235FFE4 8006E248 00106228 */  slti       $v0, $v1, 0x1000
    /* 235FFE8 8006E24C 12004010 */  beqz       $v0, .Llevel_32_8006E298
    /* 235FFEC 8006E250 40100300 */   sll       $v0, $v1, 1
    /* 235FFF0 8006E254 21104300 */  addu       $v0, $v0, $v1
    /* 235FFF4 8006E258 C0100200 */  sll        $v0, $v0, 3
    /* 235FFF8 8006E25C 21104300 */  addu       $v0, $v0, $v1
    /* 235FFFC 8006E260 40110200 */  sll        $v0, $v0, 5
    /* 2360000 8006E264 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 2360004 8006E268 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 2360008 8006E26C 03230200 */  sra        $a0, $v0, 12
    /* 236000C 8006E270 23188300 */  subu       $v1, $a0, $v1
    /* 2360010 8006E274 FF0F6430 */  andi       $a0, $v1, 0xFFF
    /* 2360014 8006E278 01088228 */  slti       $v0, $a0, 0x801
    /* 2360018 8006E27C 03004014 */  bnez       $v0, .Llevel_32_8006E28C
    /* 236001C 8006E280 2A109200 */   slt       $v0, $a0, $s2
    /* 2360020 8006E284 00F08424 */  addiu      $a0, $a0, -0x1000
    /* 2360024 8006E288 2A109200 */  slt        $v0, $a0, $s2
  .Llevel_32_8006E28C:
    /* 2360028 8006E28C 02004010 */  beqz       $v0, .Llevel_32_8006E298
    /* 236002C 8006E290 00000000 */   nop
    /* 2360030 8006E294 21908000 */  addu       $s2, $a0, $zero
  .Llevel_32_8006E298:
    /* 2360034 8006E298 0780043C */  lui        $a0, %hi(D_8006A05C)
    /* 2360038 8006E29C 5CA08424 */  addiu      $a0, $a0, %lo(D_8006A05C)
    /* 236003C 8006E2A0 0000828C */  lw         $v0, 0x0($a0)
    /* 2360040 8006E2A4 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 2360044 8006E2A8 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 2360048 8006E2AC 21105300 */  addu       $v0, $v0, $s3
    /* 236004C 8006E2B0 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* 2360050 8006E2B4 21187200 */  addu       $v1, $v1, $s2
    /* 2360054 8006E2B8 FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 2360058 8006E2BC 000082AC */  sw         $v0, 0x0($a0)
    /* 236005C 8006E2C0 01086228 */  slti       $v0, $v1, 0x801
    /* 2360060 8006E2C4 0780013C */  lui        $at, %hi(D_8006A058)
    /* 2360064 8006E2C8 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 2360068 8006E2CC 03004014 */  bnez       $v0, .Llevel_32_8006E2DC
    /* 236006C 8006E2D0 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 2360070 8006E2D4 0780013C */  lui        $at, %hi(D_8006A058)
    /* 2360074 8006E2D8 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_32_8006E2DC:
    /* 2360078 8006E2DC 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 236007C 8006E2E0 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 2360080 8006E2E4 00000000 */  nop
    /* 2360084 8006E2E8 E0FC4228 */  slti       $v0, $v0, -0x320
    /* 2360088 8006E2EC 03004010 */  beqz       $v0, .Llevel_32_8006E2FC
    /* 236008C 8006E2F0 E0FC0224 */   addiu     $v0, $zero, -0x320
    /* 2360090 8006E2F4 0780013C */  lui        $at, %hi(D_8006A058)
    /* 2360094 8006E2F8 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_32_8006E2FC:
    /* 2360098 8006E2FC 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 236009C 8006E300 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 23600A0 8006E304 00000000 */  nop
    /* 23600A4 8006E308 21034228 */  slti       $v0, $v0, 0x321
    /* 23600A8 8006E30C 03004014 */  bnez       $v0, .Llevel_32_8006E31C
    /* 23600AC 8006E310 20030224 */   addiu     $v0, $zero, 0x320
    /* 23600B0 8006E314 0780013C */  lui        $at, %hi(D_8006A058)
    /* 23600B4 8006E318 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_32_8006E31C:
    /* 23600B8 8006E31C 0780023C */  lui        $v0, %hi(D_80069894)
    /* 23600BC 8006E320 9498428C */  lw         $v0, %lo(D_80069894)($v0)
    /* 23600C0 8006E324 00000000 */  nop
    /* 23600C4 8006E328 46004104 */  bgez       $v0, .Llevel_32_8006E444
    /* 23600C8 8006E32C 00000000 */   nop
    /* 23600CC 8006E330 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 23600D0 8006E334 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 23600D4 8006E338 00000000 */  nop
    /* 23600D8 8006E33C 07006104 */  bgez       $v1, .Llevel_32_8006E35C
    /* 23600DC 8006E340 00000000 */   nop
    /* 23600E0 8006E344 0680043C */  lui        $a0, %hi(D_80060184)
    /* 23600E4 8006E348 8401848C */  lw         $a0, %lo(D_80060184)($a0)
    /* 23600E8 8006E34C 0680023C */  lui        $v0, %hi(D_80060180)
    /* 23600EC 8006E350 8001428C */  lw         $v0, %lo(D_80060180)($v0)
    /* 23600F0 8006E354 DFB80108 */  j          .Llevel_32_8006E37C
    /* 23600F4 8006E358 23108200 */   subu      $v0, $a0, $v0
  .Llevel_32_8006E35C:
    /* 23600F8 8006E35C 15006018 */  blez       $v1, .Llevel_32_8006E3B4
    /* 23600FC 8006E360 00000000 */   nop
    /* 2360100 8006E364 0680023C */  lui        $v0, %hi(D_80060188)
    /* 2360104 8006E368 8801428C */  lw         $v0, %lo(D_80060188)($v0)
    /* 2360108 8006E36C 0680043C */  lui        $a0, %hi(D_80060184)
    /* 236010C 8006E370 8401848C */  lw         $a0, %lo(D_80060184)($a0)
    /* 2360110 8006E374 00000000 */  nop
    /* 2360114 8006E378 23104400 */  subu       $v0, $v0, $a0
  .Llevel_32_8006E37C:
    /* 2360118 8006E37C 18006200 */  mult       $v1, $v0
    /* 236011C 8006E380 12100000 */  mflo       $v0
    /* 2360120 8006E384 EB51033C */  lui        $v1, (0x51EB851F >> 16)
    /* 2360124 8006E388 1F856334 */  ori        $v1, $v1, (0x51EB851F & 0xFFFF)
    /* 2360128 8006E38C 18004300 */  mult       $v0, $v1
    /* 236012C 8006E390 C3170200 */  sra        $v0, $v0, 31
    /* 2360130 8006E394 10480000 */  mfhi       $t1
    /* 2360134 8006E398 031A0900 */  sra        $v1, $t1, 8
    /* 2360138 8006E39C 23186200 */  subu       $v1, $v1, $v0
    /* 236013C 8006E3A0 21208300 */  addu       $a0, $a0, $v1
    /* 2360140 8006E3A4 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 2360144 8006E3A8 A4A024AC */  sw         $a0, %lo(D_8006A0A4)($at)
    /* 2360148 8006E3AC F1B80108 */  j          .Llevel_32_8006E3C4
    /* 236014C 8006E3B0 00000000 */   nop
  .Llevel_32_8006E3B4:
    /* 2360150 8006E3B4 0680023C */  lui        $v0, %hi(D_80060184)
    /* 2360154 8006E3B8 8401428C */  lw         $v0, %lo(D_80060184)($v0)
    /* 2360158 8006E3BC 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 236015C 8006E3C0 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
  .Llevel_32_8006E3C4:
    /* 2360160 8006E3C4 0780053C */  lui        $a1, %hi(D_8006A13C)
    /* 2360164 8006E3C8 3CA1A524 */  addiu      $a1, $a1, %lo(D_8006A13C)
    /* 2360168 8006E3CC 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 236016C 8006E3D0 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 2360170 8006E3D4 0780043C */  lui        $a0, %hi(D_8006A0A8)
    /* 2360174 8006E3D8 A8A0848C */  lw         $a0, %lo(D_8006A0A8)($a0)
    /* 2360178 8006E3DC 0000A38C */  lw         $v1, 0x0($a1)
    /* 236017C 8006E3E0 23104400 */  subu       $v0, $v0, $a0
    /* 2360180 8006E3E4 23104300 */  subu       $v0, $v0, $v1
    /* 2360184 8006E3E8 80110200 */  sll        $v0, $v0, 6
    /* 2360188 8006E3EC 83110200 */  sra        $v0, $v0, 6
    /* 236018C 8006E3F0 21186200 */  addu       $v1, $v1, $v0
    /* 2360190 8006E3F4 0000A3AC */  sw         $v1, 0x0($a1)
    /* 2360194 8006E3F8 83190300 */  sra        $v1, $v1, 6
    /* 2360198 8006E3FC 21208300 */  addu       $a0, $a0, $v1
    /* 236019C 8006E400 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 23601A0 8006E404 A8A024AC */  sw         $a0, %lo(D_8006A0A8)($at)
    /* 23601A4 8006E408 00088428 */  slti       $a0, $a0, 0x800
    /* 23601A8 8006E40C 03008010 */  beqz       $a0, .Llevel_32_8006E41C
    /* 23601AC 8006E410 00080224 */   addiu     $v0, $zero, 0x800
    /* 23601B0 8006E414 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 23601B4 8006E418 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_32_8006E41C:
    /* 23601B8 8006E41C 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 23601BC 8006E420 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 23601C0 8006E424 00000000 */  nop
    /* 23601C4 8006E428 014B4228 */  slti       $v0, $v0, 0x4B01
    /* 23601C8 8006E42C 41004014 */  bnez       $v0, .Llevel_32_8006E534
    /* 23601CC 8006E430 004B0224 */   addiu     $v0, $zero, 0x4B00
    /* 23601D0 8006E434 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 23601D4 8006E438 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 23601D8 8006E43C 4DB90108 */  j          .Llevel_32_8006E534
    /* 23601DC 8006E440 00000000 */   nop
  .Llevel_32_8006E444:
    /* 23601E0 8006E444 0680033C */  lui        $v1, %hi(D_80066F90)
    /* 23601E4 8006E448 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* 23601E8 8006E44C 19000224 */  addiu      $v0, $zero, 0x19
    /* 23601EC 8006E450 13006214 */  bne        $v1, $v0, .Llevel_32_8006E4A0
    /* 23601F0 8006E454 00000000 */   nop
    /* 23601F4 8006E458 0780023C */  lui        $v0, %hi(D_8006ABF8)
    /* 23601F8 8006E45C F8AB4290 */  lbu        $v0, %lo(D_8006ABF8)($v0)
    /* 23601FC 8006E460 00000000 */  nop
    /* 2360200 8006E464 0E004010 */  beqz       $v0, .Llevel_32_8006E4A0
    /* 2360204 8006E468 08CF0234 */   ori       $v0, $zero, 0xCF08
    /* 2360208 8006E46C 0780033C */  lui        $v1, %hi(D_80069FF8)
    /* 236020C 8006E470 F89F638C */  lw         $v1, %lo(D_80069FF8)($v1)
    /* 2360210 8006E474 00000000 */  nop
    /* 2360214 8006E478 23204300 */  subu       $a0, $v0, $v1
    /* 2360218 8006E47C 03008104 */  bgez       $a0, .Llevel_32_8006E48C
    /* 236021C 8006E480 00000000 */   nop
    /* 2360220 8006E484 3DB90108 */  j          .Llevel_32_8006E4F4
    /* 2360224 8006E488 00080224 */   addiu     $v0, $zero, 0x800
  .Llevel_32_8006E48C:
    /* 2360228 8006E48C F06F000C */  jal        func_8001BFC0
    /* 236022C 8006E490 00000000 */   nop
    /* 2360230 8006E494 80110200 */  sll        $v0, $v0, 6
    /* 2360234 8006E498 3DB90108 */  j          .Llevel_32_8006E4F4
    /* 2360238 8006E49C 00084224 */   addiu     $v0, $v0, 0x800
  .Llevel_32_8006E4A0:
    /* 236023C 8006E4A0 0780033C */  lui        $v1, %hi(D_8006A0F0)
    /* 2360240 8006E4A4 F0A0638C */  lw         $v1, %lo(D_8006A0F0)($v1)
    /* 2360244 8006E4A8 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 2360248 8006E4AC F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 236024C 8006E4B0 00000000 */  nop
    /* 2360250 8006E4B4 23206200 */  subu       $a0, $v1, $v0
    /* 2360254 8006E4B8 0A008104 */  bgez       $a0, .Llevel_32_8006E4E4
    /* 2360258 8006E4BC 00000000 */   nop
    /* 236025C 8006E4C0 F06F000C */  jal        func_8001BFC0
    /* 2360260 8006E4C4 23200400 */   negu      $a0, $a0
    /* 2360264 8006E4C8 C0110200 */  sll        $v0, $v0, 7
    /* 2360268 8006E4CC 40100324 */  addiu      $v1, $zero, 0x1040
    /* 236026C 8006E4D0 23186200 */  subu       $v1, $v1, $v0
    /* 2360270 8006E4D4 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 2360274 8006E4D8 A8A023AC */  sw         $v1, %lo(D_8006A0A8)($at)
    /* 2360278 8006E4DC 3FB90108 */  j          .Llevel_32_8006E4FC
    /* 236027C 8006E4E0 00000000 */   nop
  .Llevel_32_8006E4E4:
    /* 2360280 8006E4E4 F06F000C */  jal        func_8001BFC0
    /* 2360284 8006E4E8 00000000 */   nop
    /* 2360288 8006E4EC 80110200 */  sll        $v0, $v0, 6
    /* 236028C 8006E4F0 40104224 */  addiu      $v0, $v0, 0x1040
  .Llevel_32_8006E4F4:
    /* 2360290 8006E4F4 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 2360294 8006E4F8 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_32_8006E4FC:
    /* 2360298 8006E4FC 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 236029C 8006E500 A8A06324 */  addiu      $v1, $v1, %lo(D_8006A0A8)
    /* 23602A0 8006E504 0000628C */  lw         $v0, 0x0($v1)
    /* 23602A4 8006E508 00000000 */  nop
    /* 23602A8 8006E50C 01594228 */  slti       $v0, $v0, 0x5901
    /* 23602AC 8006E510 02004014 */  bnez       $v0, .Llevel_32_8006E51C
    /* 23602B0 8006E514 00590224 */   addiu     $v0, $zero, 0x5900
    /* 23602B4 8006E518 000062AC */  sw         $v0, 0x0($v1)
  .Llevel_32_8006E51C:
    /* 23602B8 8006E51C 0000628C */  lw         $v0, 0x0($v1)
    /* 23602BC 8006E520 00000000 */  nop
    /* 23602C0 8006E524 00084228 */  slti       $v0, $v0, 0x800
    /* 23602C4 8006E528 02004010 */  beqz       $v0, .Llevel_32_8006E534
    /* 23602C8 8006E52C 00080224 */   addiu     $v0, $zero, 0x800
    /* 23602CC 8006E530 000062AC */  sw         $v0, 0x0($v1)
  .Llevel_32_8006E534:
    /* 23602D0 8006E534 0780043C */  lui        $a0, %hi(D_8006A058)
    /* 23602D4 8006E538 58A0848C */  lw         $a0, %lo(D_8006A058)($a0)
    /* 23602D8 8006E53C 996D000C */  jal        func_8001B664
    /* 23602DC 8006E540 00000000 */   nop
    /* 23602E0 8006E544 40110200 */  sll        $v0, $v0, 5
    /* 23602E4 8006E548 23100200 */  negu       $v0, $v0
    /* 23602E8 8006E54C 18006202 */  mult       $s3, $v0
    /* 23602EC 8006E550 0780033C */  lui        $v1, %hi(D_8006A144)
    /* 23602F0 8006E554 44A1638C */  lw         $v1, %lo(D_8006A144)($v1)
    /* 23602F4 8006E558 0780053C */  lui        $a1, %hi(D_8006A054)
    /* 23602F8 8006E55C 54A0A58C */  lw         $a1, %lo(D_8006A054)($a1)
    /* 23602FC 8006E560 00110300 */  sll        $v0, $v1, 4
    /* 2360300 8006E564 83110200 */  sra        $v0, $v0, 6
    /* 2360304 8006E568 12480000 */  mflo       $t1
    /* 2360308 8006E56C 03230900 */  sra        $a0, $t1, 12
    /* 236030C 8006E570 23208200 */  subu       $a0, $a0, $v0
    /* 2360310 8006E574 80110500 */  sll        $v0, $a1, 6
    /* 2360314 8006E578 83110200 */  sra        $v0, $v0, 6
    /* 2360318 8006E57C 23208200 */  subu       $a0, $a0, $v0
    /* 236031C 8006E580 21186400 */  addu       $v1, $v1, $a0
    /* 2360320 8006E584 0780013C */  lui        $at, %hi(D_8006A144)
    /* 2360324 8006E588 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 2360328 8006E58C 83190300 */  sra        $v1, $v1, 6
    /* 236032C 8006E590 2128A300 */  addu       $a1, $a1, $v1
    /* 2360330 8006E594 FF0FA530 */  andi       $a1, $a1, 0xFFF
    /* 2360334 8006E598 0108A228 */  slti       $v0, $a1, 0x801
    /* 2360338 8006E59C 0780013C */  lui        $at, %hi(D_8006A054)
    /* 236033C 8006E5A0 54A025AC */  sw         $a1, %lo(D_8006A054)($at)
    /* 2360340 8006E5A4 03004014 */  bnez       $v0, .Llevel_32_8006E5B4
    /* 2360344 8006E5A8 00F0A224 */   addiu     $v0, $a1, -0x1000
    /* 2360348 8006E5AC 0780013C */  lui        $at, %hi(D_8006A054)
    /* 236034C 8006E5B0 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_32_8006E5B4:
    /* 2360350 8006E5B4 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 2360354 8006E5B8 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 2360358 8006E5BC 00000000 */  nop
    /* 236035C 8006E5C0 00FD4228 */  slti       $v0, $v0, -0x300
    /* 2360360 8006E5C4 03004010 */  beqz       $v0, .Llevel_32_8006E5D4
    /* 2360364 8006E5C8 00FD0224 */   addiu     $v0, $zero, -0x300
    /* 2360368 8006E5CC 0780013C */  lui        $at, %hi(D_8006A054)
    /* 236036C 8006E5D0 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_32_8006E5D4:
    /* 2360370 8006E5D4 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 2360374 8006E5D8 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 2360378 8006E5DC 00000000 */  nop
    /* 236037C 8006E5E0 01034228 */  slti       $v0, $v0, 0x301
    /* 2360380 8006E5E4 03004014 */  bnez       $v0, .Llevel_32_8006E5F4
    /* 2360384 8006E5E8 00030224 */   addiu     $v0, $zero, 0x300
    /* 2360388 8006E5EC 0780013C */  lui        $at, %hi(D_8006A054)
    /* 236038C 8006E5F0 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_32_8006E5F4:
    /* 2360390 8006E5F4 6FAF000C */  jal        func_8002BDBC
    /* 2360394 8006E5F8 00000000 */   nop
    /* 2360398 8006E5FC 0780043C */  lui        $a0, %hi(D_8006A044)
    /* 236039C 8006E600 44A0848C */  lw         $a0, %lo(D_8006A044)($a0)
    /* 23603A0 8006E604 00000000 */  nop
    /* 23603A4 8006E608 1C008014 */  bnez       $a0, .Llevel_32_8006E67C
    /* 23603A8 8006E60C 00000000 */   nop
    /* 23603AC 8006E610 0680023C */  lui        $v0, %hi(D_80066F38)
    /* 23603B0 8006E614 386F428C */  lw         $v0, %lo(D_80066F38)($v0)
    /* 23603B4 8006E618 00000000 */  nop
    /* 23603B8 8006E61C 0400428C */  lw         $v0, 0x4($v0)
    /* 23603BC 8006E620 00000000 */  nop
    /* 23603C0 8006E624 40004230 */  andi       $v0, $v0, 0x40
    /* 23603C4 8006E628 46004010 */  beqz       $v0, .Llevel_32_8006E744
    /* 23603C8 8006E62C 00000000 */   nop
    /* 23603CC 8006E630 0780023C */  lui        $v0, %hi(D_8006A0F0)
    /* 23603D0 8006E634 F0A0428C */  lw         $v0, %lo(D_8006A0F0)($v0)
    /* 23603D4 8006E638 0780033C */  lui        $v1, %hi(D_80069FF8)
    /* 23603D8 8006E63C F89F638C */  lw         $v1, %lo(D_80069FF8)($v1)
    /* 23603DC 8006E640 00FE4224 */  addiu      $v0, $v0, -0x200
    /* 23603E0 8006E644 2A186200 */  slt        $v1, $v1, $v0
    /* 23603E4 8006E648 3E006010 */  beqz       $v1, .Llevel_32_8006E744
    /* 23603E8 8006E64C 21000224 */   addiu     $v0, $zero, 0x21
    /* 23603EC 8006E650 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 23603F0 8006E654 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 23603F4 8006E658 00000000 */  nop
    /* 23603F8 8006E65C 39006214 */  bne        $v1, $v0, .Llevel_32_8006E744
    /* 23603FC 8006E660 01000224 */   addiu     $v0, $zero, 0x1
    /* 2360400 8006E664 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2360404 8006E668 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 2360408 8006E66C 0780013C */  lui        $at, %hi(D_8006A150)
    /* 236040C 8006E670 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 2360410 8006E674 D1B90108 */  j          .Llevel_32_8006E744
    /* 2360414 8006E678 00000000 */   nop
  .Llevel_32_8006E67C:
    /* 2360418 8006E67C 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 236041C 8006E680 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 2360420 8006E684 0780033C */  lui        $v1, %hi(D_8006A0F0)
    /* 2360424 8006E688 F0A0638C */  lw         $v1, %lo(D_8006A0F0)($v1)
    /* 2360428 8006E68C 00000000 */  nop
    /* 236042C 8006E690 2A104300 */  slt        $v0, $v0, $v1
    /* 2360430 8006E694 05004014 */  bnez       $v0, .Llevel_32_8006E6AC
    /* 2360434 8006E698 01000224 */   addiu     $v0, $zero, 0x1
    /* 2360438 8006E69C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 236043C 8006E6A0 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 2360440 8006E6A4 D1B90108 */  j          .Llevel_32_8006E744
    /* 2360444 8006E6A8 00000000 */   nop
  .Llevel_32_8006E6AC:
    /* 2360448 8006E6AC 11008214 */  bne        $a0, $v0, .Llevel_32_8006E6F4
    /* 236044C 8006E6B0 00000000 */   nop
    /* 2360450 8006E6B4 0780023C */  lui        $v0, %hi(D_8006A150)
    /* 2360454 8006E6B8 50A1428C */  lw         $v0, %lo(D_8006A150)($v0)
    /* 2360458 8006E6BC 00000000 */  nop
    /* 236045C 8006E6C0 00024224 */  addiu      $v0, $v0, 0x200
    /* 2360460 8006E6C4 0780013C */  lui        $at, %hi(D_8006A150)
    /* 2360464 8006E6C8 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 2360468 8006E6CC 00184228 */  slti       $v0, $v0, 0x1800
    /* 236046C 8006E6D0 14004014 */  bnez       $v0, .Llevel_32_8006E724
    /* 2360470 8006E6D4 00180224 */   addiu     $v0, $zero, 0x1800
    /* 2360474 8006E6D8 0780013C */  lui        $at, %hi(D_8006A150)
    /* 2360478 8006E6DC 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 236047C 8006E6E0 02000224 */  addiu      $v0, $zero, 0x2
    /* 2360480 8006E6E4 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2360484 8006E6E8 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 2360488 8006E6EC C9B90108 */  j          .Llevel_32_8006E724
    /* 236048C 8006E6F0 00000000 */   nop
  .Llevel_32_8006E6F4:
    /* 2360490 8006E6F4 0780023C */  lui        $v0, %hi(D_8006A150)
    /* 2360494 8006E6F8 50A1428C */  lw         $v0, %lo(D_8006A150)($v0)
    /* 2360498 8006E6FC 00000000 */  nop
    /* 236049C 8006E700 00FF4224 */  addiu      $v0, $v0, -0x100
    /* 23604A0 8006E704 0780013C */  lui        $at, %hi(D_8006A150)
    /* 23604A4 8006E708 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 23604A8 8006E70C 0500401C */  bgtz       $v0, .Llevel_32_8006E724
    /* 23604AC 8006E710 00000000 */   nop
    /* 23604B0 8006E714 0780013C */  lui        $at, %hi(D_8006A150)
    /* 23604B4 8006E718 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 23604B8 8006E71C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 23604BC 8006E720 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
  .Llevel_32_8006E724:
    /* 23604C0 8006E724 0780023C */  lui        $v0, %hi(D_8006A080)
    /* 23604C4 8006E728 80A04224 */  addiu      $v0, $v0, %lo(D_8006A080)
    /* 23604C8 8006E72C 0000438C */  lw         $v1, 0x0($v0)
    /* 23604CC 8006E730 0780043C */  lui        $a0, %hi(D_8006A150)
    /* 23604D0 8006E734 50A1848C */  lw         $a0, %lo(D_8006A150)($a0)
    /* 23604D4 8006E738 00000000 */  nop
    /* 23604D8 8006E73C 21186400 */  addu       $v1, $v1, $a0
    /* 23604DC 8006E740 000043AC */  sw         $v1, 0x0($v0)
  .Llevel_32_8006E744:
    /* 23604E0 8006E744 0EB0000C */  jal        func_8002C038
    /* 23604E4 8006E748 00000000 */   nop
  .Llevel_32_8006E74C:
    /* 23604E8 8006E74C 5800BF8F */  lw         $ra, 0x58($sp)
    /* 23604EC 8006E750 5400B38F */  lw         $s3, 0x54($sp)
    /* 23604F0 8006E754 5000B28F */  lw         $s2, 0x50($sp)
    /* 23604F4 8006E758 4C00B18F */  lw         $s1, 0x4C($sp)
    /* 23604F8 8006E75C 4800B08F */  lw         $s0, 0x48($sp)
    /* 23604FC 8006E760 6000BD27 */  addiu      $sp, $sp, 0x60
    /* 2360500 8006E764 0800E003 */  jr         $ra
    /* 2360504 8006E768 00000000 */   nop
endlabel func_level_32_8006DBA8
