.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_22_8006D268

dlabel jtbl_level_22_8006D268
    /* 178B004 8006D268 94DC0680 */ .word .Llevel_22_8006DC94
    /* 178B008 8006D26C F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B00C 8006D270 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B010 8006D274 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B014 8006D278 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B018 8006D27C F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B01C 8006D280 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B020 8006D284 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B024 8006D288 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B028 8006D28C F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B02C 8006D290 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B030 8006D294 44DC0680 */ .word .Llevel_22_8006DC44
    /* 178B034 8006D298 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B038 8006D29C F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B03C 8006D2A0 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B040 8006D2A4 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B044 8006D2A8 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B048 8006D2AC F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B04C 8006D2B0 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B050 8006D2B4 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B054 8006D2B8 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B058 8006D2BC F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B05C 8006D2C0 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B060 8006D2C4 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B064 8006D2C8 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B068 8006D2CC F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B06C 8006D2D0 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B070 8006D2D4 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B074 8006D2D8 68DE0680 */ .word .Llevel_22_8006DE68
    /* 178B078 8006D2DC F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B07C 8006D2E0 44DC0680 */ .word .Llevel_22_8006DC44
    /* 178B080 8006D2E4 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B084 8006D2E8 78E00680 */ .word .Llevel_22_8006E078
    /* 178B088 8006D2EC 60E30680 */ .word .Llevel_22_8006E360
    /* 178B08C 8006D2F0 6CE50680 */ .word .Llevel_22_8006E56C
    /* 178B090 8006D2F4 00E80680 */ .word .Llevel_22_8006E800
    /* 178B094 8006D2F8 00E80680 */ .word .Llevel_22_8006E800
    /* 178B098 8006D2FC F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B09C 8006D300 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B0A0 8006D304 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B0A4 8006D308 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B0A8 8006D30C F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B0AC 8006D310 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B0B0 8006D314 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B0B4 8006D318 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B0B8 8006D31C F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B0BC 8006D320 44DC0680 */ .word .Llevel_22_8006DC44
    /* 178B0C0 8006D324 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B0C4 8006D328 F8EB0680 */ .word .Llevel_22_8006EBF8
    /* 178B0C8 8006D32C 70EB0680 */ .word .Llevel_22_8006EB70
enddlabel jtbl_level_22_8006D268


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_22_8006DBD0, 0x104C

glabel func_level_22_8006DBD0
    /* 178B96C 8006DBD0 58FFBD27 */  addiu      $sp, $sp, -0xA8
    /* 178B970 8006DBD4 9800B2AF */  sw         $s2, 0x98($sp)
    /* 178B974 8006DBD8 21908000 */  addu       $s2, $a0, $zero
    /* 178B978 8006DBDC 00111200 */  sll        $v0, $s2, 4
    /* 178B97C 8006DBE0 0780033C */  lui        $v1, %hi(D_800683B0)
    /* 178B980 8006DBE4 B0836324 */  addiu      $v1, $v1, %lo(D_800683B0)
    /* 178B984 8006DBE8 21104300 */  addu       $v0, $v0, $v1
    /* 178B988 8006DBEC 0680013C */  lui        $at, %hi(D_80066F38)
    /* 178B98C 8006DBF0 386F22AC */  sw         $v0, %lo(D_80066F38)($at)
    /* 178B990 8006DBF4 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 178B994 8006DBF8 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 178B998 8006DBFC 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 178B99C 8006DC00 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 178B9A0 8006DC04 A400BFAF */  sw         $ra, 0xA4($sp)
    /* 178B9A4 8006DC08 A000B4AF */  sw         $s4, 0xA0($sp)
    /* 178B9A8 8006DC0C 9C00B3AF */  sw         $s3, 0x9C($sp)
    /* 178B9AC 8006DC10 9400B1AF */  sw         $s1, 0x94($sp)
    /* 178B9B0 8006DC14 21885200 */  addu       $s1, $v0, $s2
    /* 178B9B4 8006DC18 F8FF6324 */  addiu      $v1, $v1, -0x8
    /* 178B9B8 8006DC1C 3200622C */  sltiu      $v0, $v1, 0x32
    /* 178B9BC 8006DC20 F5034010 */  beqz       $v0, .Llevel_22_8006EBF8
    /* 178B9C0 8006DC24 9000B0AF */   sw        $s0, 0x90($sp)
    /* 178B9C4 8006DC28 80100300 */  sll        $v0, $v1, 2
    /* 178B9C8 8006DC2C 0780013C */  lui        $at, %hi(jtbl_level_22_8006D268)
    /* 178B9CC 8006DC30 21082200 */  addu       $at, $at, $v0
    /* 178B9D0 8006DC34 68D2228C */  lw         $v0, %lo(jtbl_level_22_8006D268)($at)
    /* 178B9D4 8006DC38 00000000 */  nop
    /* 178B9D8 8006DC3C 08004000 */  jr         $v0
    /* 178B9DC 8006DC40 00000000 */   nop
  .Llevel_22_8006DC44:
    /* 178B9E0 8006DC44 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 178B9E4 8006DC48 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 178B9E8 8006DC4C 686F000C */  jal        func_8001BDA0
    /* 178B9EC 8006DC50 21200002 */   addu      $a0, $s0, $zero
    /* 178B9F0 8006DC54 686F000C */  jal        func_8001BDA0
    /* 178B9F4 8006DC58 0C000426 */   addiu     $a0, $s0, 0xC
    /* 178B9F8 8006DC5C 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 178B9FC 8006DC60 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 178BA00 8006DC64 07000224 */  addiu      $v0, $zero, 0x7
    /* 178BA04 8006DC68 E3036210 */  beq        $v1, $v0, .Llevel_22_8006EBF8
    /* 178BA08 8006DC6C 00000000 */   nop
    /* 178BA0C 8006DC70 DBAC000C */  jal        func_8002B36C
    /* 178BA10 8006DC74 00120424 */   addiu     $a0, $zero, 0x1200
    /* 178BA14 8006DC78 1AAF000C */  jal        func_8002BC68
    /* 178BA18 8006DC7C 00000000 */   nop
    /* 178BA1C 8006DC80 5A000424 */  addiu      $a0, $zero, 0x5A
    /* 178BA20 8006DC84 C9AE000C */  jal        func_8002BB24
    /* 178BA24 8006DC88 10000524 */   addiu     $a1, $zero, 0x10
    /* 178BA28 8006DC8C FEBA0108 */  j          .Llevel_22_8006EBF8
    /* 178BA2C 8006DC90 00000000 */   nop
  .Llevel_22_8006DC94:
    /* 178BA30 8006DC94 0780103C */  lui        $s0, %hi(D_8006A044)
    /* 178BA34 8006DC98 44A01026 */  addiu      $s0, $s0, %lo(D_8006A044)
    /* 178BA38 8006DC9C 0000038E */  lw         $v1, 0x0($s0)
    /* 178BA3C 8006DCA0 01000224 */  addiu      $v0, $zero, 0x1
    /* 178BA40 8006DCA4 46006214 */  bne        $v1, $v0, .Llevel_22_8006DDC0
    /* 178BA44 8006DCA8 1300222A */   slti      $v0, $s1, 0x13
    /* 178BA48 8006DCAC DBAC000C */  jal        func_8002B36C
    /* 178BA4C 8006DCB0 800C0424 */   addiu     $a0, $zero, 0xC80
    /* 178BA50 8006DCB4 28000424 */  addiu      $a0, $zero, 0x28
    /* 178BA54 8006DCB8 C9AE000C */  jal        func_8002BB24
    /* 178BA58 8006DCBC 08000524 */   addiu     $a1, $zero, 0x8
    /* 178BA5C 8006DCC0 40010424 */  addiu      $a0, $zero, 0x140
    /* 178BA60 8006DCC4 5CAF000C */  jal        func_8002BD70
    /* 178BA64 8006DCC8 C0000524 */   addiu     $a1, $zero, 0xC0
    /* 178BA68 8006DCCC 0780043C */  lui        $a0, %hi(D_8006A09C)
    /* 178BA6C 8006DCD0 9CA0848C */  lw         $a0, %lo(D_8006A09C)($a0)
    /* 178BA70 8006DCD4 996D000C */  jal        func_8001B664
    /* 178BA74 8006DCD8 40001226 */   addiu     $s2, $s0, 0x40
    /* 178BA78 8006DCDC 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 178BA7C 8006DCE0 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 178BA80 8006DCE4 00000000 */  nop
    /* 178BA84 8006DCE8 18006200 */  mult       $v1, $v0
    /* 178BA88 8006DCEC 0780043C */  lui        $a0, %hi(D_8006A09C)
    /* 178BA8C 8006DCF0 9CA0848C */  lw         $a0, %lo(D_8006A09C)($a0)
    /* 178BA90 8006DCF4 12400000 */  mflo       $t0
    /* 178BA94 8006DCF8 03130800 */  sra        $v0, $t0, 12
    /* 178BA98 8006DCFC 876D000C */  jal        func_8001B61C
    /* 178BA9C 8006DD00 1000A2AF */   sw        $v0, 0x10($sp)
    /* 178BAA0 8006DD04 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 178BAA4 8006DD08 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 178BAA8 8006DD0C 00000000 */  nop
    /* 178BAAC 8006DD10 18006200 */  mult       $v1, $v0
    /* 178BAB0 8006DD14 1000A427 */  addiu      $a0, $sp, 0x10
    /* 178BAB4 8006DD18 21288000 */  addu       $a1, $a0, $zero
    /* 178BAB8 8006DD1C 21304002 */  addu       $a2, $s2, $zero
    /* 178BABC 8006DD20 12400000 */  mflo       $t0
    /* 178BAC0 8006DD24 03130800 */  sra        $v0, $t0, 12
    /* 178BAC4 8006DD28 806F000C */  jal        func_8001BE00
    /* 178BAC8 8006DD2C 1400A2AF */   sw        $v0, 0x14($sp)
    /* 178BACC 8006DD30 1000A427 */  addiu      $a0, $sp, 0x10
    /* 178BAD0 8006DD34 21280000 */  addu       $a1, $zero, $zero
    /* 178BAD4 8006DD38 886E000C */  jal        func_8001BA20
    /* 178BAD8 8006DD3C 1800A0AF */   sw        $zero, 0x18($sp)
    /* 178BADC 8006DD40 21284000 */  addu       $a1, $v0, $zero
    /* 178BAE0 8006DD44 8102A228 */  slti       $v0, $a1, 0x281
    /* 178BAE4 8006DD48 05004014 */  bnez       $v0, .Llevel_22_8006DD60
    /* 178BAE8 8006DD4C 34000426 */   addiu     $a0, $s0, 0x34
    /* 178BAEC 8006DD50 1000A427 */  addiu      $a0, $sp, 0x10
    /* 178BAF0 8006DD54 316F000C */  jal        func_8001BCC4
    /* 178BAF4 8006DD58 80020624 */   addiu     $a2, $zero, 0x280
    /* 178BAF8 8006DD5C 34000426 */  addiu      $a0, $s0, 0x34
  .Llevel_22_8006DD60:
    /* 178BAFC 8006DD60 21284002 */  addu       $a1, $s2, $zero
    /* 178BB00 8006DD64 736F000C */  jal        func_8001BDCC
    /* 178BB04 8006DD68 1000A627 */   addiu     $a2, $sp, 0x10
    /* 178BB08 8006DD6C 0EB0000C */  jal        func_8002C038
    /* 178BB0C 8006DD70 00000000 */   nop
    /* 178BB10 8006DD74 0D00222A */  slti       $v0, $s1, 0xD
    /* 178BB14 8006DD78 09004010 */  beqz       $v0, .Llevel_22_8006DDA0
    /* 178BB18 8006DD7C 00000000 */   nop
    /* 178BB1C 8006DD80 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 178BB20 8006DD84 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 178BB24 8006DD88 00000000 */  nop
    /* 178BB28 8006DD8C 17004224 */  addiu      $v0, $v0, 0x17
    /* 178BB2C 8006DD90 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 178BB30 8006DD94 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 178BB34 8006DD98 FEBA0108 */  j          .Llevel_22_8006EBF8
    /* 178BB38 8006DD9C 00000000 */   nop
  .Llevel_22_8006DDA0:
    /* 178BB3C 8006DDA0 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 178BB40 8006DDA4 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 178BB44 8006DDA8 00000000 */  nop
    /* 178BB48 8006DDAC 40FF4224 */  addiu      $v0, $v0, -0xC0
    /* 178BB4C 8006DDB0 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 178BB50 8006DDB4 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 178BB54 8006DDB8 FEBA0108 */  j          .Llevel_22_8006EBF8
    /* 178BB58 8006DDBC 00000000 */   nop
  .Llevel_22_8006DDC0:
    /* 178BB5C 8006DDC0 1A004014 */  bnez       $v0, .Llevel_22_8006DE2C
    /* 178BB60 8006DDC4 40000426 */   addiu     $a0, $s0, 0x40
    /* 178BB64 8006DDC8 34000426 */  addiu      $a0, $s0, 0x34
    /* 178BB68 8006DDCC 0780033C */  lui        $v1, %hi(D_8006A084)
    /* 178BB6C 8006DDD0 84A0638C */  lw         $v1, %lo(D_8006A084)($v1)
    /* 178BB70 8006DDD4 00000000 */  nop
    /* 178BB74 8006DDD8 C0100300 */  sll        $v0, $v1, 3
    /* 178BB78 8006DDDC 23104300 */  subu       $v0, $v0, $v1
    /* 178BB7C 8006DDE0 0780033C */  lui        $v1, %hi(D_8006A088)
    /* 178BB80 8006DDE4 88A0638C */  lw         $v1, %lo(D_8006A088)($v1)
    /* 178BB84 8006DDE8 40110200 */  sll        $v0, $v0, 5
    /* 178BB88 8006DDEC 340002AE */  sw         $v0, 0x34($s0)
    /* 178BB8C 8006DDF0 C0100300 */  sll        $v0, $v1, 3
    /* 178BB90 8006DDF4 23104300 */  subu       $v0, $v0, $v1
    /* 178BB94 8006DDF8 0780033C */  lui        $v1, %hi(D_8006A08C)
    /* 178BB98 8006DDFC 8CA0638C */  lw         $v1, %lo(D_8006A08C)($v1)
    /* 178BB9C 8006DE00 40110200 */  sll        $v0, $v0, 5
    /* 178BBA0 8006DE04 0780013C */  lui        $at, %hi(D_8006A07C)
    /* 178BBA4 8006DE08 7CA022AC */  sw         $v0, %lo(D_8006A07C)($at)
    /* 178BBA8 8006DE0C C0100300 */  sll        $v0, $v1, 3
    /* 178BBAC 8006DE10 23104300 */  subu       $v0, $v0, $v1
    /* 178BBB0 8006DE14 40110200 */  sll        $v0, $v0, 5
    /* 178BBB4 8006DE18 0780013C */  lui        $at, %hi(D_8006A080)
    /* 178BBB8 8006DE1C 80A022AC */  sw         $v0, %lo(D_8006A080)($at)
    /* 178BBBC 8006DE20 526F000C */  jal        func_8001BD48
    /* 178BBC0 8006DE24 08000524 */   addiu     $a1, $zero, 0x8
    /* 178BBC4 8006DE28 40000426 */  addiu      $a0, $s0, 0x40
  .Llevel_22_8006DE2C:
    /* 178BBC8 8006DE2C 6C6F000C */  jal        func_8001BDB0
    /* 178BBCC 8006DE30 34000526 */   addiu     $a1, $s0, 0x34
    /* 178BBD0 8006DE34 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 178BBD4 8006DE38 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 178BBD8 8006DE3C 00000000 */  nop
    /* 178BBDC 8006DE40 40FF4224 */  addiu      $v0, $v0, -0xC0
    /* 178BBE0 8006DE44 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 178BBE4 8006DE48 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 178BBE8 8006DE4C 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 178BBEC 8006DE50 69034010 */  beqz       $v0, .Llevel_22_8006EBF8
    /* 178BBF0 8006DE54 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 178BBF4 8006DE58 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 178BBF8 8006DE5C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 178BBFC 8006DE60 FEBA0108 */  j          .Llevel_22_8006EBF8
    /* 178BC00 8006DE64 00000000 */   nop
  .Llevel_22_8006DE68:
    /* 178BC04 8006DE68 2000A427 */  addiu      $a0, $sp, 0x20
    /* 178BC08 8006DE6C 0780053C */  lui        $a1, %hi(D_8006A144)
    /* 178BC0C 8006DE70 44A1A524 */  addiu      $a1, $a1, %lo(D_8006A144)
    /* 178BC10 8006DE74 A5AD000C */  jal        func_8002B694
    /* 178BC14 8006DE78 21300000 */   addu      $a2, $zero, $zero
    /* 178BC18 8006DE7C 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 178BC1C 8006DE80 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 178BC20 8006DE84 00000000 */  nop
    /* 178BC24 8006DE88 20036224 */  addiu      $v0, $v1, 0x320
    /* 178BC28 8006DE8C 2107422C */  sltiu      $v0, $v0, 0x721
    /* 178BC2C 8006DE90 04004014 */  bnez       $v0, .Llevel_22_8006DEA4
    /* 178BC30 8006DE94 21036228 */   slti      $v0, $v1, 0x321
    /* 178BC34 8006DE98 21800000 */  addu       $s0, $zero, $zero
    /* 178BC38 8006DE9C C2B70108 */  j          .Llevel_22_8006DF08
    /* 178BC3C 8006DEA0 17000524 */   addiu     $a1, $zero, 0x17
  .Llevel_22_8006DEA4:
    /* 178BC40 8006DEA4 0B004014 */  bnez       $v0, .Llevel_22_8006DED4
    /* 178BC44 8006DEA8 00000000 */   nop
    /* 178BC48 8006DEAC 2400A38F */  lw         $v1, 0x24($sp)
    /* 178BC4C 8006DEB0 00000000 */  nop
    /* 178BC50 8006DEB4 23180300 */  negu       $v1, $v1
    /* 178BC54 8006DEB8 40100300 */  sll        $v0, $v1, 1
    /* 178BC58 8006DEBC 21104300 */  addu       $v0, $v0, $v1
    /* 178BC5C 8006DEC0 C0100200 */  sll        $v0, $v0, 3
    /* 178BC60 8006DEC4 23104300 */  subu       $v0, $v0, $v1
    /* 178BC64 8006DEC8 2000A38F */  lw         $v1, 0x20($sp)
    /* 178BC68 8006DECC BEB70108 */  j          .Llevel_22_8006DEF8
    /* 178BC6C 8006DED0 032A0200 */   sra       $a1, $v0, 8
  .Llevel_22_8006DED4:
    /* 178BC70 8006DED4 2400A38F */  lw         $v1, 0x24($sp)
    /* 178BC74 8006DED8 00000000 */  nop
    /* 178BC78 8006DEDC 23180300 */  negu       $v1, $v1
    /* 178BC7C 8006DEE0 40100300 */  sll        $v0, $v1, 1
    /* 178BC80 8006DEE4 21104300 */  addu       $v0, $v0, $v1
    /* 178BC84 8006DEE8 C0100200 */  sll        $v0, $v0, 3
    /* 178BC88 8006DEEC 23104300 */  subu       $v0, $v0, $v1
    /* 178BC8C 8006DEF0 2000A38F */  lw         $v1, 0x20($sp)
    /* 178BC90 8006DEF4 C3290200 */  sra        $a1, $v0, 7
  .Llevel_22_8006DEF8:
    /* 178BC94 8006DEF8 00110300 */  sll        $v0, $v1, 4
    /* 178BC98 8006DEFC 23104300 */  subu       $v0, $v0, $v1
    /* 178BC9C 8006DF00 40100200 */  sll        $v0, $v0, 1
    /* 178BCA0 8006DF04 C3810200 */  sra        $s0, $v0, 7
  .Llevel_22_8006DF08:
    /* 178BCA4 8006DF08 0780043C */  lui        $a0, %hi(D_8006A05C)
    /* 178BCA8 8006DF0C 5CA08424 */  addiu      $a0, $a0, %lo(D_8006A05C)
    /* 178BCAC 8006DF10 0000828C */  lw         $v0, 0x0($a0)
    /* 178BCB0 8006DF14 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 178BCB4 8006DF18 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 178BCB8 8006DF1C 21105000 */  addu       $v0, $v0, $s0
    /* 178BCBC 8006DF20 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* 178BCC0 8006DF24 21186500 */  addu       $v1, $v1, $a1
    /* 178BCC4 8006DF28 FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 178BCC8 8006DF2C 000082AC */  sw         $v0, 0x0($a0)
    /* 178BCCC 8006DF30 01086228 */  slti       $v0, $v1, 0x801
    /* 178BCD0 8006DF34 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178BCD4 8006DF38 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 178BCD8 8006DF3C 03004014 */  bnez       $v0, .Llevel_22_8006DF4C
    /* 178BCDC 8006DF40 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 178BCE0 8006DF44 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178BCE4 8006DF48 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006DF4C:
    /* 178BCE8 8006DF4C 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 178BCEC 8006DF50 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 178BCF0 8006DF54 00180224 */  addiu      $v0, $zero, 0x1800
    /* 178BCF4 8006DF58 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 178BCF8 8006DF5C A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 178BCFC 8006DF60 02000224 */  addiu      $v0, $zero, 0x2
    /* 178BD00 8006DF64 0D006214 */  bne        $v1, $v0, .Llevel_22_8006DF9C
    /* 178BD04 8006DF68 40010424 */   addiu     $a0, $zero, 0x140
    /* 178BD08 8006DF6C 5CAF000C */  jal        func_8002BD70
    /* 178BD0C 8006DF70 C0000524 */   addiu     $a1, $zero, 0xC0
    /* 178BD10 8006DF74 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 178BD14 8006DF78 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 178BD18 8006DF7C 00000000 */  nop
    /* 178BD1C 8006DF80 01184228 */  slti       $v0, $v0, 0x1801
    /* 178BD20 8006DF84 07004010 */  beqz       $v0, .Llevel_22_8006DFA4
    /* 178BD24 8006DF88 00000000 */   nop
    /* 178BD28 8006DF8C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178BD2C 8006DF90 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 178BD30 8006DF94 E9B70108 */  j          .Llevel_22_8006DFA4
    /* 178BD34 8006DF98 00000000 */   nop
  .Llevel_22_8006DF9C:
    /* 178BD38 8006DF9C 5CAF000C */  jal        func_8002BD70
    /* 178BD3C 8006DFA0 50000524 */   addiu     $a1, $zero, 0x50
  .Llevel_22_8006DFA4:
    /* 178BD40 8006DFA4 0780113C */  lui        $s1, %hi(D_8006A058)
    /* 178BD44 8006DFA8 58A03126 */  addiu      $s1, $s1, %lo(D_8006A058)
    /* 178BD48 8006DFAC 0000248E */  lw         $a0, 0x0($s1)
    /* 178BD4C 8006DFB0 996D000C */  jal        func_8001B664
    /* 178BD50 8006DFB4 00000000 */   nop
    /* 178BD54 8006DFB8 40110200 */  sll        $v0, $v0, 5
    /* 178BD58 8006DFBC 23100200 */  negu       $v0, $v0
    /* 178BD5C 8006DFC0 18000202 */  mult       $s0, $v0
    /* 178BD60 8006DFC4 0780033C */  lui        $v1, %hi(D_8006A144)
    /* 178BD64 8006DFC8 44A1638C */  lw         $v1, %lo(D_8006A144)($v1)
    /* 178BD68 8006DFCC 0780053C */  lui        $a1, %hi(D_8006A054)
    /* 178BD6C 8006DFD0 54A0A58C */  lw         $a1, %lo(D_8006A054)($a1)
    /* 178BD70 8006DFD4 00110300 */  sll        $v0, $v1, 4
    /* 178BD74 8006DFD8 83110200 */  sra        $v0, $v0, 6
    /* 178BD78 8006DFDC 12400000 */  mflo       $t0
    /* 178BD7C 8006DFE0 03230800 */  sra        $a0, $t0, 12
    /* 178BD80 8006DFE4 23208200 */  subu       $a0, $a0, $v0
    /* 178BD84 8006DFE8 80110500 */  sll        $v0, $a1, 6
    /* 178BD88 8006DFEC 83110200 */  sra        $v0, $v0, 6
    /* 178BD8C 8006DFF0 23208200 */  subu       $a0, $a0, $v0
    /* 178BD90 8006DFF4 21186400 */  addu       $v1, $v1, $a0
    /* 178BD94 8006DFF8 0780013C */  lui        $at, %hi(D_8006A144)
    /* 178BD98 8006DFFC 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 178BD9C 8006E000 83190300 */  sra        $v1, $v1, 6
    /* 178BDA0 8006E004 2128A300 */  addu       $a1, $a1, $v1
    /* 178BDA4 8006E008 FF0FA530 */  andi       $a1, $a1, 0xFFF
    /* 178BDA8 8006E00C 0108A228 */  slti       $v0, $a1, 0x801
    /* 178BDAC 8006E010 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178BDB0 8006E014 54A025AC */  sw         $a1, %lo(D_8006A054)($at)
    /* 178BDB4 8006E018 03004014 */  bnez       $v0, .Llevel_22_8006E028
    /* 178BDB8 8006E01C 00F0A224 */   addiu     $v0, $a1, -0x1000
    /* 178BDBC 8006E020 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178BDC0 8006E024 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E028:
    /* 178BDC4 8006E028 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 178BDC8 8006E02C 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 178BDCC 8006E030 00000000 */  nop
    /* 178BDD0 8006E034 00FD4228 */  slti       $v0, $v0, -0x300
    /* 178BDD4 8006E038 03004010 */  beqz       $v0, .Llevel_22_8006E048
    /* 178BDD8 8006E03C 00FD0224 */   addiu     $v0, $zero, -0x300
    /* 178BDDC 8006E040 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178BDE0 8006E044 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E048:
    /* 178BDE4 8006E048 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 178BDE8 8006E04C 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 178BDEC 8006E050 00000000 */  nop
    /* 178BDF0 8006E054 01034228 */  slti       $v0, $v0, 0x301
    /* 178BDF4 8006E058 03004014 */  bnez       $v0, .Llevel_22_8006E068
    /* 178BDF8 8006E05C 00030224 */   addiu     $v0, $zero, 0x300
    /* 178BDFC 8006E060 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178BE00 8006E064 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E068:
    /* 178BE04 8006E068 6FAF000C */  jal        func_8002BDBC
    /* 178BE08 8006E06C 00000000 */   nop
    /* 178BE0C 8006E070 F8BA0108 */  j          .Llevel_22_8006EBE0
    /* 178BE10 8006E074 00000000 */   nop
  .Llevel_22_8006E078:
    /* 178BE14 8006E078 2800A427 */  addiu      $a0, $sp, 0x28
    /* 178BE18 8006E07C 0780053C */  lui        $a1, %hi(D_8006A144)
    /* 178BE1C 8006E080 44A1A524 */  addiu      $a1, $a1, %lo(D_8006A144)
    /* 178BE20 8006E084 A5AD000C */  jal        func_8002B694
    /* 178BE24 8006E088 21300000 */   addu      $a2, $zero, $zero
    /* 178BE28 8006E08C 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 178BE2C 8006E090 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 178BE30 8006E094 01000224 */  addiu      $v0, $zero, 0x1
    /* 178BE34 8006E098 19006214 */  bne        $v1, $v0, .Llevel_22_8006E100
    /* 178BE38 8006E09C 00020224 */   addiu     $v0, $zero, 0x200
    /* 178BE3C 8006E0A0 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 178BE40 8006E0A4 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 178BE44 8006E0A8 0780043C */  lui        $a0, %hi(D_8006A13C)
    /* 178BE48 8006E0AC 3CA1848C */  lw         $a0, %lo(D_8006A13C)($a0)
    /* 178BE4C 8006E0B0 23104300 */  subu       $v0, $v0, $v1
    /* 178BE50 8006E0B4 00190400 */  sll        $v1, $a0, 4
    /* 178BE54 8006E0B8 23104300 */  subu       $v0, $v0, $v1
    /* 178BE58 8006E0BC FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 178BE5C 8006E0C0 01086228 */  slti       $v0, $v1, 0x801
    /* 178BE60 8006E0C4 03004014 */  bnez       $v0, .Llevel_22_8006E0D4
    /* 178BE64 8006E0C8 2C00A3AF */   sw        $v1, 0x2C($sp)
    /* 178BE68 8006E0CC 00F06224 */  addiu      $v0, $v1, -0x1000
    /* 178BE6C 8006E0D0 2C00A2AF */  sw         $v0, 0x2C($sp)
  .Llevel_22_8006E0D4:
    /* 178BE70 8006E0D4 2C00A28F */  lw         $v0, 0x2C($sp)
    /* 178BE74 8006E0D8 01008324 */  addiu      $v1, $a0, 0x1
    /* 178BE78 8006E0DC 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 178BE7C 8006E0E0 3CA123AC */  sw         $v1, %lo(D_8006A13C)($at)
    /* 178BE80 8006E0E4 15006328 */  slti       $v1, $v1, 0x15
    /* 178BE84 8006E0E8 C0110200 */  sll        $v0, $v0, 7
    /* 178BE88 8006E0EC 03120200 */  sra        $v0, $v0, 8
    /* 178BE8C 8006E0F0 03006014 */  bnez       $v1, .Llevel_22_8006E100
    /* 178BE90 8006E0F4 2C00A2AF */   sw        $v0, 0x2C($sp)
    /* 178BE94 8006E0F8 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178BE98 8006E0FC 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
  .Llevel_22_8006E100:
    /* 178BE9C 8006E100 0780053C */  lui        $a1, %hi(D_8006A05C)
    /* 178BEA0 8006E104 5CA0A524 */  addiu      $a1, $a1, %lo(D_8006A05C)
    /* 178BEA4 8006E108 2800A38F */  lw         $v1, 0x28($sp)
    /* 178BEA8 8006E10C 2C00A48F */  lw         $a0, 0x2C($sp)
    /* 178BEAC 8006E110 80100300 */  sll        $v0, $v1, 2
    /* 178BEB0 8006E114 21104300 */  addu       $v0, $v0, $v1
    /* 178BEB4 8006E118 80100200 */  sll        $v0, $v0, 2
    /* 178BEB8 8006E11C C3890200 */  sra        $s1, $v0, 7
    /* 178BEBC 8006E120 00110400 */  sll        $v0, $a0, 4
    /* 178BEC0 8006E124 0000A38C */  lw         $v1, 0x0($a1)
    /* 178BEC4 8006E128 23208200 */  subu       $a0, $a0, $v0
    /* 178BEC8 8006E12C 21187100 */  addu       $v1, $v1, $s1
    /* 178BECC 8006E130 FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 178BED0 8006E134 0000A3AC */  sw         $v1, 0x0($a1)
    /* 178BED4 8006E138 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178BED8 8006E13C 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178BEDC 8006E140 C3210400 */  sra        $a0, $a0, 7
    /* 178BEE0 8006E144 21104400 */  addu       $v0, $v0, $a0
    /* 178BEE4 8006E148 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 178BEE8 8006E14C 01086228 */  slti       $v0, $v1, 0x801
    /* 178BEEC 8006E150 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178BEF0 8006E154 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 178BEF4 8006E158 03004014 */  bnez       $v0, .Llevel_22_8006E168
    /* 178BEF8 8006E15C 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 178BEFC 8006E160 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178BF00 8006E164 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006E168:
    /* 178BF04 8006E168 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178BF08 8006E16C 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178BF0C 8006E170 00000000 */  nop
    /* 178BF10 8006E174 E0FC4228 */  slti       $v0, $v0, -0x320
    /* 178BF14 8006E178 03004010 */  beqz       $v0, .Llevel_22_8006E188
    /* 178BF18 8006E17C E0FC0224 */   addiu     $v0, $zero, -0x320
    /* 178BF1C 8006E180 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178BF20 8006E184 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006E188:
    /* 178BF24 8006E188 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178BF28 8006E18C 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178BF2C 8006E190 00000000 */  nop
    /* 178BF30 8006E194 21034228 */  slti       $v0, $v0, 0x321
    /* 178BF34 8006E198 03004014 */  bnez       $v0, .Llevel_22_8006E1A8
    /* 178BF38 8006E19C 20030224 */   addiu     $v0, $zero, 0x320
    /* 178BF3C 8006E1A0 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178BF40 8006E1A4 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006E1A8:
    /* 178BF44 8006E1A8 0680023C */  lui        $v0, %hi(D_80066F38)
    /* 178BF48 8006E1AC 386F428C */  lw         $v0, %lo(D_80066F38)($v0)
    /* 178BF4C 8006E1B0 00000000 */  nop
    /* 178BF50 8006E1B4 0000428C */  lw         $v0, 0x0($v0)
    /* 178BF54 8006E1B8 00000000 */  nop
    /* 178BF58 8006E1BC 40004230 */  andi       $v0, $v0, 0x40
    /* 178BF5C 8006E1C0 06004014 */  bnez       $v0, .Llevel_22_8006E1DC
    /* 178BF60 8006E1C4 000E0224 */   addiu     $v0, $zero, 0xE00
    /* 178BF64 8006E1C8 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 178BF68 8006E1CC 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 178BF6C 8006E1D0 01000224 */  addiu      $v0, $zero, 0x1
    /* 178BF70 8006E1D4 05006214 */  bne        $v1, $v0, .Llevel_22_8006E1EC
    /* 178BF74 8006E1D8 000E0224 */   addiu     $v0, $zero, 0xE00
  .Llevel_22_8006E1DC:
    /* 178BF78 8006E1DC 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 178BF7C 8006E1E0 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 178BF80 8006E1E4 7DB80108 */  j          .Llevel_22_8006E1F4
    /* 178BF84 8006E1E8 00000000 */   nop
  .Llevel_22_8006E1EC:
    /* 178BF88 8006E1EC 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 178BF8C 8006E1F0 A4A020AC */  sw         $zero, %lo(D_8006A0A4)($at)
  .Llevel_22_8006E1F4:
    /* 178BF90 8006E1F4 0780103C */  lui        $s0, %hi(D_8006A044)
    /* 178BF94 8006E1F8 44A01026 */  addiu      $s0, $s0, %lo(D_8006A044)
    /* 178BF98 8006E1FC 0000038E */  lw         $v1, 0x0($s0)
    /* 178BF9C 8006E200 02000224 */  addiu      $v0, $zero, 0x2
    /* 178BFA0 8006E204 0B006214 */  bne        $v1, $v0, .Llevel_22_8006E234
    /* 178BFA4 8006E208 C0000424 */   addiu     $a0, $zero, 0xC0
    /* 178BFA8 8006E20C 5CAF000C */  jal        func_8002BD70
    /* 178BFAC 8006E210 C0000524 */   addiu     $a1, $zero, 0xC0
    /* 178BFB0 8006E214 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 178BFB4 8006E218 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 178BFB8 8006E21C 00000000 */  nop
    /* 178BFBC 8006E220 010E4228 */  slti       $v0, $v0, 0xE01
    /* 178BFC0 8006E224 05004010 */  beqz       $v0, .Llevel_22_8006E23C
    /* 178BFC4 8006E228 00000000 */   nop
    /* 178BFC8 8006E22C 8FB80108 */  j          .Llevel_22_8006E23C
    /* 178BFCC 8006E230 000000AE */   sw        $zero, 0x0($s0)
  .Llevel_22_8006E234:
    /* 178BFD0 8006E234 5CAF000C */  jal        func_8002BD70
    /* 178BFD4 8006E238 30000524 */   addiu     $a1, $zero, 0x30
  .Llevel_22_8006E23C:
    /* 178BFD8 8006E23C 0780103C */  lui        $s0, %hi(D_8006A058)
    /* 178BFDC 8006E240 58A01026 */  addiu      $s0, $s0, %lo(D_8006A058)
    /* 178BFE0 8006E244 0000048E */  lw         $a0, 0x0($s0)
    /* 178BFE4 8006E248 996D000C */  jal        func_8001B664
    /* 178BFE8 8006E24C 00000000 */   nop
    /* 178BFEC 8006E250 40110200 */  sll        $v0, $v0, 5
    /* 178BFF0 8006E254 23100200 */  negu       $v0, $v0
    /* 178BFF4 8006E258 18002202 */  mult       $s1, $v0
    /* 178BFF8 8006E25C 0780033C */  lui        $v1, %hi(D_8006A144)
    /* 178BFFC 8006E260 44A1638C */  lw         $v1, %lo(D_8006A144)($v1)
    /* 178C000 8006E264 0780053C */  lui        $a1, %hi(D_8006A054)
    /* 178C004 8006E268 54A0A58C */  lw         $a1, %lo(D_8006A054)($a1)
    /* 178C008 8006E26C 00110300 */  sll        $v0, $v1, 4
    /* 178C00C 8006E270 83110200 */  sra        $v0, $v0, 6
    /* 178C010 8006E274 12400000 */  mflo       $t0
    /* 178C014 8006E278 03230800 */  sra        $a0, $t0, 12
    /* 178C018 8006E27C 23208200 */  subu       $a0, $a0, $v0
    /* 178C01C 8006E280 80110500 */  sll        $v0, $a1, 6
    /* 178C020 8006E284 83110200 */  sra        $v0, $v0, 6
    /* 178C024 8006E288 23208200 */  subu       $a0, $a0, $v0
    /* 178C028 8006E28C 21186400 */  addu       $v1, $v1, $a0
    /* 178C02C 8006E290 0780013C */  lui        $at, %hi(D_8006A144)
    /* 178C030 8006E294 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 178C034 8006E298 83190300 */  sra        $v1, $v1, 6
    /* 178C038 8006E29C 2128A300 */  addu       $a1, $a1, $v1
    /* 178C03C 8006E2A0 FF0FA530 */  andi       $a1, $a1, 0xFFF
    /* 178C040 8006E2A4 0108A228 */  slti       $v0, $a1, 0x801
    /* 178C044 8006E2A8 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C048 8006E2AC 54A025AC */  sw         $a1, %lo(D_8006A054)($at)
    /* 178C04C 8006E2B0 03004014 */  bnez       $v0, .Llevel_22_8006E2C0
    /* 178C050 8006E2B4 00F0A224 */   addiu     $v0, $a1, -0x1000
    /* 178C054 8006E2B8 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C058 8006E2BC 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E2C0:
    /* 178C05C 8006E2C0 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 178C060 8006E2C4 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 178C064 8006E2C8 00000000 */  nop
    /* 178C068 8006E2CC 00FD4228 */  slti       $v0, $v0, -0x300
    /* 178C06C 8006E2D0 03004010 */  beqz       $v0, .Llevel_22_8006E2E0
    /* 178C070 8006E2D4 00FD0224 */   addiu     $v0, $zero, -0x300
    /* 178C074 8006E2D8 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C078 8006E2DC 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E2E0:
    /* 178C07C 8006E2E0 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 178C080 8006E2E4 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 178C084 8006E2E8 00000000 */  nop
    /* 178C088 8006E2EC 01034228 */  slti       $v0, $v0, 0x301
    /* 178C08C 8006E2F0 03004014 */  bnez       $v0, .Llevel_22_8006E300
    /* 178C090 8006E2F4 00030224 */   addiu     $v0, $zero, 0x300
    /* 178C094 8006E2F8 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C098 8006E2FC 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E300:
    /* 178C09C 8006E300 6FAF000C */  jal        func_8002BDBC
    /* 178C0A0 8006E304 00000000 */   nop
    /* 178C0A4 8006E308 2C000426 */  addiu      $a0, $s0, 0x2C
    /* 178C0A8 8006E30C 6C6F000C */  jal        func_8001BDB0
    /* 178C0AC 8006E310 20000526 */   addiu     $a1, $s0, 0x20
    /* 178C0B0 8006E314 4B67010C */  jal        func_80059D2C
    /* 178C0B4 8006E318 00000000 */   nop
    /* 178C0B8 8006E31C 1F004230 */  andi       $v0, $v0, 0x1F
    /* 178C0BC 8006E320 8B004014 */  bnez       $v0, .Llevel_22_8006E550
    /* 178C0C0 8006E324 00000000 */   nop
    /* 178C0C4 8006E328 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 178C0C8 8006E32C FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 178C0CC 8006E330 00000000 */  nop
    /* 178C0D0 8006E334 86006010 */  beqz       $v1, .Llevel_22_8006E550
    /* 178C0D4 8006E338 01000424 */   addiu     $a0, $zero, 0x1
    /* 178C0D8 8006E33C 2C000524 */  addiu      $a1, $zero, 0x2C
    /* 178C0DC 8006E340 3000A627 */  addiu      $a2, $sp, 0x30
    /* 178C0E0 8006E344 21380000 */  addu       $a3, $zero, $zero
    /* 178C0E4 8006E348 20020224 */  addiu      $v0, $zero, 0x220
    /* 178C0E8 8006E34C 3000A2AF */  sw         $v0, 0x30($sp)
    /* 178C0EC 8006E350 40000224 */  addiu      $v0, $zero, 0x40
    /* 178C0F0 8006E354 3400A0AF */  sw         $zero, 0x34($sp)
    /* 178C0F4 8006E358 52B90108 */  j          .Llevel_22_8006E548
    /* 178C0F8 8006E35C 3800A2AF */   sw        $v0, 0x38($sp)
  .Llevel_22_8006E360:
    /* 178C0FC 8006E360 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 178C100 8006E364 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 178C104 8006E368 07000224 */  addiu      $v0, $zero, 0x7
    /* 178C108 8006E36C 5E006210 */  beq        $v1, $v0, .Llevel_22_8006E4E8
    /* 178C10C 8006E370 3000A427 */   addiu     $a0, $sp, 0x30
    /* 178C110 8006E374 0780113C */  lui        $s1, %hi(D_8006A144)
    /* 178C114 8006E378 44A13126 */  addiu      $s1, $s1, %lo(D_8006A144)
    /* 178C118 8006E37C 21282002 */  addu       $a1, $s1, $zero
    /* 178C11C 8006E380 A5AD000C */  jal        func_8002B694
    /* 178C120 8006E384 21300000 */   addu      $a2, $zero, $zero
    /* 178C124 8006E388 3000A38F */  lw         $v1, 0x30($sp)
    /* 178C128 8006E38C 3400A48F */  lw         $a0, 0x34($sp)
    /* 178C12C 8006E390 80100300 */  sll        $v0, $v1, 2
    /* 178C130 8006E394 21104300 */  addu       $v0, $v0, $v1
    /* 178C134 8006E398 80100200 */  sll        $v0, $v0, 2
    /* 178C138 8006E39C C3810200 */  sra        $s0, $v0, 7
    /* 178C13C 8006E3A0 00110400 */  sll        $v0, $a0, 4
    /* 178C140 8006E3A4 23208200 */  subu       $a0, $a0, $v0
    /* 178C144 8006E3A8 C3210400 */  sra        $a0, $a0, 7
    /* 178C148 8006E3AC 0780033C */  lui        $v1, %hi(D_8006A05C)
    /* 178C14C 8006E3B0 5CA0638C */  lw         $v1, %lo(D_8006A05C)($v1)
    /* 178C150 8006E3B4 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178C154 8006E3B8 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178C158 8006E3BC 21187000 */  addu       $v1, $v1, $s0
    /* 178C15C 8006E3C0 FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 178C160 8006E3C4 21104400 */  addu       $v0, $v0, $a0
    /* 178C164 8006E3C8 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 178C168 8006E3CC 5CA023AC */  sw         $v1, %lo(D_8006A05C)($at)
    /* 178C16C 8006E3D0 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 178C170 8006E3D4 01086228 */  slti       $v0, $v1, 0x801
    /* 178C174 8006E3D8 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178C178 8006E3DC 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 178C17C 8006E3E0 03004014 */  bnez       $v0, .Llevel_22_8006E3F0
    /* 178C180 8006E3E4 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 178C184 8006E3E8 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178C188 8006E3EC 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006E3F0:
    /* 178C18C 8006E3F0 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178C190 8006E3F4 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178C194 8006E3F8 00000000 */  nop
    /* 178C198 8006E3FC E0FC4228 */  slti       $v0, $v0, -0x320
    /* 178C19C 8006E400 03004010 */  beqz       $v0, .Llevel_22_8006E410
    /* 178C1A0 8006E404 E0FC0224 */   addiu     $v0, $zero, -0x320
    /* 178C1A4 8006E408 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178C1A8 8006E40C 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006E410:
    /* 178C1AC 8006E410 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178C1B0 8006E414 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178C1B4 8006E418 00000000 */  nop
    /* 178C1B8 8006E41C 21034228 */  slti       $v0, $v0, 0x321
    /* 178C1BC 8006E420 03004014 */  bnez       $v0, .Llevel_22_8006E430
    /* 178C1C0 8006E424 20030224 */   addiu     $v0, $zero, 0x320
    /* 178C1C4 8006E428 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178C1C8 8006E42C 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006E430:
    /* 178C1CC 8006E430 0780043C */  lui        $a0, %hi(D_8006A058)
    /* 178C1D0 8006E434 58A0848C */  lw         $a0, %lo(D_8006A058)($a0)
    /* 178C1D4 8006E438 996D000C */  jal        func_8001B664
    /* 178C1D8 8006E43C 00000000 */   nop
    /* 178C1DC 8006E440 40110200 */  sll        $v0, $v0, 5
    /* 178C1E0 8006E444 23100200 */  negu       $v0, $v0
    /* 178C1E4 8006E448 18000202 */  mult       $s0, $v0
    /* 178C1E8 8006E44C 0000238E */  lw         $v1, 0x0($s1)
    /* 178C1EC 8006E450 0780053C */  lui        $a1, %hi(D_8006A054)
    /* 178C1F0 8006E454 54A0A58C */  lw         $a1, %lo(D_8006A054)($a1)
    /* 178C1F4 8006E458 00110300 */  sll        $v0, $v1, 4
    /* 178C1F8 8006E45C 83110200 */  sra        $v0, $v0, 6
    /* 178C1FC 8006E460 12400000 */  mflo       $t0
    /* 178C200 8006E464 03230800 */  sra        $a0, $t0, 12
    /* 178C204 8006E468 23208200 */  subu       $a0, $a0, $v0
    /* 178C208 8006E46C 80110500 */  sll        $v0, $a1, 6
    /* 178C20C 8006E470 83110200 */  sra        $v0, $v0, 6
    /* 178C210 8006E474 23208200 */  subu       $a0, $a0, $v0
    /* 178C214 8006E478 21186400 */  addu       $v1, $v1, $a0
    /* 178C218 8006E47C 000023AE */  sw         $v1, 0x0($s1)
    /* 178C21C 8006E480 83190300 */  sra        $v1, $v1, 6
    /* 178C220 8006E484 2128A300 */  addu       $a1, $a1, $v1
    /* 178C224 8006E488 FF0FA530 */  andi       $a1, $a1, 0xFFF
    /* 178C228 8006E48C 0108A228 */  slti       $v0, $a1, 0x801
    /* 178C22C 8006E490 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C230 8006E494 54A025AC */  sw         $a1, %lo(D_8006A054)($at)
    /* 178C234 8006E498 03004014 */  bnez       $v0, .Llevel_22_8006E4A8
    /* 178C238 8006E49C 00F0A224 */   addiu     $v0, $a1, -0x1000
    /* 178C23C 8006E4A0 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C240 8006E4A4 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E4A8:
    /* 178C244 8006E4A8 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 178C248 8006E4AC 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 178C24C 8006E4B0 00000000 */  nop
    /* 178C250 8006E4B4 00FD4228 */  slti       $v0, $v0, -0x300
    /* 178C254 8006E4B8 03004010 */  beqz       $v0, .Llevel_22_8006E4C8
    /* 178C258 8006E4BC 00FD0224 */   addiu     $v0, $zero, -0x300
    /* 178C25C 8006E4C0 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C260 8006E4C4 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E4C8:
    /* 178C264 8006E4C8 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 178C268 8006E4CC 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 178C26C 8006E4D0 00000000 */  nop
    /* 178C270 8006E4D4 01034228 */  slti       $v0, $v0, 0x301
    /* 178C274 8006E4D8 03004014 */  bnez       $v0, .Llevel_22_8006E4E8
    /* 178C278 8006E4DC 00030224 */   addiu     $v0, $zero, 0x300
    /* 178C27C 8006E4E0 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C280 8006E4E4 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E4E8:
    /* 178C284 8006E4E8 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 178C288 8006E4EC 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 178C28C 8006E4F0 686F000C */  jal        func_8001BDA0
    /* 178C290 8006E4F4 21200002 */   addu      $a0, $s0, $zero
    /* 178C294 8006E4F8 686F000C */  jal        func_8001BDA0
    /* 178C298 8006E4FC 0C000426 */   addiu     $a0, $s0, 0xC
    /* 178C29C 8006E500 4B67010C */  jal        func_80059D2C
    /* 178C2A0 8006E504 00000000 */   nop
    /* 178C2A4 8006E508 1F004230 */  andi       $v0, $v0, 0x1F
    /* 178C2A8 8006E50C 10004014 */  bnez       $v0, .Llevel_22_8006E550
    /* 178C2AC 8006E510 00000000 */   nop
    /* 178C2B0 8006E514 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 178C2B4 8006E518 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 178C2B8 8006E51C 00000000 */  nop
    /* 178C2BC 8006E520 0B006010 */  beqz       $v1, .Llevel_22_8006E550
    /* 178C2C0 8006E524 01000424 */   addiu     $a0, $zero, 0x1
    /* 178C2C4 8006E528 2C000524 */  addiu      $a1, $zero, 0x2C
    /* 178C2C8 8006E52C 4000A627 */  addiu      $a2, $sp, 0x40
    /* 178C2CC 8006E530 21380000 */  addu       $a3, $zero, $zero
    /* 178C2D0 8006E534 20020224 */  addiu      $v0, $zero, 0x220
    /* 178C2D4 8006E538 4000A2AF */  sw         $v0, 0x40($sp)
    /* 178C2D8 8006E53C 40000224 */  addiu      $v0, $zero, 0x40
    /* 178C2DC 8006E540 4400A0AF */  sw         $zero, 0x44($sp)
    /* 178C2E0 8006E544 4800A2AF */  sw         $v0, 0x48($sp)
  .Llevel_22_8006E548:
    /* 178C2E4 8006E548 09F86000 */  jalr       $v1
    /* 178C2E8 8006E54C 00000000 */   nop
  .Llevel_22_8006E550:
    /* 178C2EC 8006E550 0780033C */  lui        $v1, %hi(D_8006A150)
    /* 178C2F0 8006E554 50A16324 */  addiu      $v1, $v1, %lo(D_8006A150)
    /* 178C2F4 8006E558 0000628C */  lw         $v0, 0x0($v1)
    /* 178C2F8 8006E55C 00000000 */  nop
    /* 178C2FC 8006E560 01004224 */  addiu      $v0, $v0, 0x1
    /* 178C300 8006E564 FEBA0108 */  j          .Llevel_22_8006EBF8
    /* 178C304 8006E568 000062AC */   sw        $v0, 0x0($v1)
  .Llevel_22_8006E56C:
    /* 178C308 8006E56C 4000A427 */  addiu      $a0, $sp, 0x40
    /* 178C30C 8006E570 0780053C */  lui        $a1, %hi(D_8006A144)
    /* 178C310 8006E574 44A1A524 */  addiu      $a1, $a1, %lo(D_8006A144)
    /* 178C314 8006E578 A5AD000C */  jal        func_8002B694
    /* 178C318 8006E57C 21300000 */   addu      $a2, $zero, $zero
    /* 178C31C 8006E580 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 178C320 8006E584 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 178C324 8006E588 01000224 */  addiu      $v0, $zero, 0x1
    /* 178C328 8006E58C 1B006214 */  bne        $v1, $v0, .Llevel_22_8006E5FC
    /* 178C32C 8006E590 00020224 */   addiu     $v0, $zero, 0x200
    /* 178C330 8006E594 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 178C334 8006E598 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 178C338 8006E59C 0780053C */  lui        $a1, %hi(D_8006A13C)
    /* 178C33C 8006E5A0 3CA1A58C */  lw         $a1, %lo(D_8006A13C)($a1)
    /* 178C340 8006E5A4 23104300 */  subu       $v0, $v0, $v1
    /* 178C344 8006E5A8 00190500 */  sll        $v1, $a1, 4
    /* 178C348 8006E5AC 23104300 */  subu       $v0, $v0, $v1
    /* 178C34C 8006E5B0 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 178C350 8006E5B4 01086228 */  slti       $v0, $v1, 0x801
    /* 178C354 8006E5B8 03004014 */  bnez       $v0, .Llevel_22_8006E5C8
    /* 178C358 8006E5BC 4400A3AF */   sw        $v1, 0x44($sp)
    /* 178C35C 8006E5C0 00F06224 */  addiu      $v0, $v1, -0x1000
    /* 178C360 8006E5C4 4400A2AF */  sw         $v0, 0x44($sp)
  .Llevel_22_8006E5C8:
    /* 178C364 8006E5C8 4400A48F */  lw         $a0, 0x44($sp)
    /* 178C368 8006E5CC 0100A324 */  addiu      $v1, $a1, 0x1
    /* 178C36C 8006E5D0 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 178C370 8006E5D4 3CA123AC */  sw         $v1, %lo(D_8006A13C)($at)
    /* 178C374 8006E5D8 0D006328 */  slti       $v1, $v1, 0xD
    /* 178C378 8006E5DC 40100400 */  sll        $v0, $a0, 1
    /* 178C37C 8006E5E0 21104400 */  addu       $v0, $v0, $a0
    /* 178C380 8006E5E4 40110200 */  sll        $v0, $v0, 5
    /* 178C384 8006E5E8 03120200 */  sra        $v0, $v0, 8
    /* 178C388 8006E5EC 03006014 */  bnez       $v1, .Llevel_22_8006E5FC
    /* 178C38C 8006E5F0 4400A2AF */   sw        $v0, 0x44($sp)
    /* 178C390 8006E5F4 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178C394 8006E5F8 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
  .Llevel_22_8006E5FC:
    /* 178C398 8006E5FC 0780113C */  lui        $s1, %hi(D_8006A05C)
    /* 178C39C 8006E600 5CA03126 */  addiu      $s1, $s1, %lo(D_8006A05C)
    /* 178C3A0 8006E604 4000A38F */  lw         $v1, 0x40($sp)
    /* 178C3A4 8006E608 4400A48F */  lw         $a0, 0x44($sp)
    /* 178C3A8 8006E60C 80100300 */  sll        $v0, $v1, 2
    /* 178C3AC 8006E610 21104300 */  addu       $v0, $v0, $v1
    /* 178C3B0 8006E614 80100200 */  sll        $v0, $v0, 2
    /* 178C3B4 8006E618 C3810200 */  sra        $s0, $v0, 7
    /* 178C3B8 8006E61C 00110400 */  sll        $v0, $a0, 4
    /* 178C3BC 8006E620 0000238E */  lw         $v1, 0x0($s1)
    /* 178C3C0 8006E624 23208200 */  subu       $a0, $a0, $v0
    /* 178C3C4 8006E628 21187000 */  addu       $v1, $v1, $s0
    /* 178C3C8 8006E62C FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 178C3CC 8006E630 000023AE */  sw         $v1, 0x0($s1)
    /* 178C3D0 8006E634 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178C3D4 8006E638 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178C3D8 8006E63C C3210400 */  sra        $a0, $a0, 7
    /* 178C3DC 8006E640 21104400 */  addu       $v0, $v0, $a0
    /* 178C3E0 8006E644 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 178C3E4 8006E648 01086228 */  slti       $v0, $v1, 0x801
    /* 178C3E8 8006E64C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178C3EC 8006E650 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 178C3F0 8006E654 03004014 */  bnez       $v0, .Llevel_22_8006E664
    /* 178C3F4 8006E658 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 178C3F8 8006E65C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178C3FC 8006E660 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006E664:
    /* 178C400 8006E664 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178C404 8006E668 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178C408 8006E66C 00000000 */  nop
    /* 178C40C 8006E670 E0FC4228 */  slti       $v0, $v0, -0x320
    /* 178C410 8006E674 03004010 */  beqz       $v0, .Llevel_22_8006E684
    /* 178C414 8006E678 E0FC0224 */   addiu     $v0, $zero, -0x320
    /* 178C418 8006E67C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178C41C 8006E680 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006E684:
    /* 178C420 8006E684 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178C424 8006E688 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178C428 8006E68C 00000000 */  nop
    /* 178C42C 8006E690 21034228 */  slti       $v0, $v0, 0x321
    /* 178C430 8006E694 04004014 */  bnez       $v0, .Llevel_22_8006E6A8
    /* 178C434 8006E698 40020424 */   addiu     $a0, $zero, 0x240
    /* 178C438 8006E69C 20030224 */  addiu      $v0, $zero, 0x320
    /* 178C43C 8006E6A0 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178C440 8006E6A4 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006E6A8:
    /* 178C444 8006E6A8 001C0224 */  addiu      $v0, $zero, 0x1C00
    /* 178C448 8006E6AC 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 178C44C 8006E6B0 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 178C450 8006E6B4 5CAF000C */  jal        func_8002BD70
    /* 178C454 8006E6B8 30000524 */   addiu     $a1, $zero, 0x30
    /* 178C458 8006E6BC 0780043C */  lui        $a0, %hi(D_8006A058)
    /* 178C45C 8006E6C0 58A0848C */  lw         $a0, %lo(D_8006A058)($a0)
    /* 178C460 8006E6C4 996D000C */  jal        func_8001B664
    /* 178C464 8006E6C8 00000000 */   nop
    /* 178C468 8006E6CC 40110200 */  sll        $v0, $v0, 5
    /* 178C46C 8006E6D0 23100200 */  negu       $v0, $v0
    /* 178C470 8006E6D4 18000202 */  mult       $s0, $v0
    /* 178C474 8006E6D8 0780033C */  lui        $v1, %hi(D_8006A144)
    /* 178C478 8006E6DC 44A1638C */  lw         $v1, %lo(D_8006A144)($v1)
    /* 178C47C 8006E6E0 0780053C */  lui        $a1, %hi(D_8006A054)
    /* 178C480 8006E6E4 54A0A58C */  lw         $a1, %lo(D_8006A054)($a1)
    /* 178C484 8006E6E8 00110300 */  sll        $v0, $v1, 4
    /* 178C488 8006E6EC 83110200 */  sra        $v0, $v0, 6
    /* 178C48C 8006E6F0 12400000 */  mflo       $t0
    /* 178C490 8006E6F4 03230800 */  sra        $a0, $t0, 12
    /* 178C494 8006E6F8 23208200 */  subu       $a0, $a0, $v0
    /* 178C498 8006E6FC 80110500 */  sll        $v0, $a1, 6
    /* 178C49C 8006E700 83110200 */  sra        $v0, $v0, 6
    /* 178C4A0 8006E704 23208200 */  subu       $a0, $a0, $v0
    /* 178C4A4 8006E708 21186400 */  addu       $v1, $v1, $a0
    /* 178C4A8 8006E70C 0780013C */  lui        $at, %hi(D_8006A144)
    /* 178C4AC 8006E710 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 178C4B0 8006E714 83190300 */  sra        $v1, $v1, 6
    /* 178C4B4 8006E718 2128A300 */  addu       $a1, $a1, $v1
    /* 178C4B8 8006E71C FF0FA530 */  andi       $a1, $a1, 0xFFF
    /* 178C4BC 8006E720 0108A228 */  slti       $v0, $a1, 0x801
    /* 178C4C0 8006E724 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C4C4 8006E728 54A025AC */  sw         $a1, %lo(D_8006A054)($at)
    /* 178C4C8 8006E72C 03004014 */  bnez       $v0, .Llevel_22_8006E73C
    /* 178C4CC 8006E730 00F0A224 */   addiu     $v0, $a1, -0x1000
    /* 178C4D0 8006E734 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C4D4 8006E738 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E73C:
    /* 178C4D8 8006E73C 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 178C4DC 8006E740 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 178C4E0 8006E744 00000000 */  nop
    /* 178C4E4 8006E748 00FD4228 */  slti       $v0, $v0, -0x300
    /* 178C4E8 8006E74C 03004010 */  beqz       $v0, .Llevel_22_8006E75C
    /* 178C4EC 8006E750 00FD0224 */   addiu     $v0, $zero, -0x300
    /* 178C4F0 8006E754 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C4F4 8006E758 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E75C:
    /* 178C4F8 8006E75C 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 178C4FC 8006E760 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 178C500 8006E764 00000000 */  nop
    /* 178C504 8006E768 01034228 */  slti       $v0, $v0, 0x301
    /* 178C508 8006E76C 03004014 */  bnez       $v0, .Llevel_22_8006E77C
    /* 178C50C 8006E770 00030224 */   addiu     $v0, $zero, 0x300
    /* 178C510 8006E774 0780013C */  lui        $at, %hi(D_8006A054)
    /* 178C514 8006E778 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_22_8006E77C:
    /* 178C518 8006E77C 6FAF000C */  jal        func_8002BDBC
    /* 178C51C 8006E780 00000000 */   nop
    /* 178C520 8006E784 28002426 */  addiu      $a0, $s1, 0x28
    /* 178C524 8006E788 6C6F000C */  jal        func_8001BDB0
    /* 178C528 8006E78C 1C002526 */   addiu     $a1, $s1, 0x1C
    /* 178C52C 8006E790 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178C530 8006E794 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178C534 8006E798 00000000 */  nop
    /* 178C538 8006E79C 16014010 */  beqz       $v0, .Llevel_22_8006EBF8
    /* 178C53C 8006E7A0 00000000 */   nop
    /* 178C540 8006E7A4 0780023C */  lui        $v0, %hi(D_8006A0AC)
    /* 178C544 8006E7A8 ACA0428C */  lw         $v0, %lo(D_8006A0AC)($v0)
    /* 178C548 8006E7AC 00000000 */  nop
    /* 178C54C 8006E7B0 D1074228 */  slti       $v0, $v0, 0x7D1
    /* 178C550 8006E7B4 10014014 */  bnez       $v0, .Llevel_22_8006EBF8
    /* 178C554 8006E7B8 70FE0224 */   addiu     $v0, $zero, -0x190
    /* 178C558 8006E7BC 4B67010C */  jal        func_80059D2C
    /* 178C55C 8006E7C0 5000A2AF */   sw        $v0, 0x50($sp)
    /* 178C560 8006E7C4 01000424 */  addiu      $a0, $zero, 0x1
    /* 178C564 8006E7C8 2C000524 */  addiu      $a1, $zero, 0x2C
    /* 178C568 8006E7CC 5000A627 */  addiu      $a2, $sp, 0x50
    /* 178C56C 8006E7D0 21380000 */  addu       $a3, $zero, $zero
    /* 178C570 8006E7D4 7F004230 */  andi       $v0, $v0, 0x7F
    /* 178C574 8006E7D8 40000324 */  addiu      $v1, $zero, 0x40
    /* 178C578 8006E7DC 23186200 */  subu       $v1, $v1, $v0
    /* 178C57C 8006E7E0 5400A3AF */  sw         $v1, 0x54($sp)
    /* 178C580 8006E7E4 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 178C584 8006E7E8 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 178C588 8006E7EC D4FE0224 */  addiu      $v0, $zero, -0x12C
    /* 178C58C 8006E7F0 09F86000 */  jalr       $v1
    /* 178C590 8006E7F4 5800A2AF */   sw        $v0, 0x58($sp)
    /* 178C594 8006E7F8 FEBA0108 */  j          .Llevel_22_8006EBF8
    /* 178C598 8006E7FC 00000000 */   nop
  .Llevel_22_8006E800:
    /* 178C59C 8006E800 0780103C */  lui        $s0, %hi(D_8006A044)
    /* 178C5A0 8006E804 44A01026 */  addiu      $s0, $s0, %lo(D_8006A044)
    /* 178C5A4 8006E808 0000038E */  lw         $v1, 0x0($s0)
    /* 178C5A8 8006E80C 01000224 */  addiu      $v0, $zero, 0x1
    /* 178C5AC 8006E810 07006214 */  bne        $v1, $v0, .Llevel_22_8006E830
    /* 178C5B0 8006E814 07000224 */   addiu     $v0, $zero, 0x7
    /* 178C5B4 8006E818 686F000C */  jal        func_8001BDA0
    /* 178C5B8 8006E81C 34000426 */   addiu     $a0, $s0, 0x34
    /* 178C5BC 8006E820 686F000C */  jal        func_8001BDA0
    /* 178C5C0 8006E824 40000426 */   addiu     $a0, $s0, 0x40
    /* 178C5C4 8006E828 FEBA0108 */  j          .Llevel_22_8006EBF8
    /* 178C5C8 8006E82C 00000000 */   nop
  .Llevel_22_8006E830:
    /* 178C5CC 8006E830 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 178C5D0 8006E834 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 178C5D4 8006E838 00000000 */  nop
    /* 178C5D8 8006E83C 05006214 */  bne        $v1, $v0, .Llevel_22_8006E854
    /* 178C5DC 8006E840 00000000 */   nop
    /* 178C5E0 8006E844 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 178C5E4 8006E848 A8A020AC */  sw         $zero, %lo(D_8006A0A8)($at)
    /* 178C5E8 8006E84C 2EBA0108 */  j          .Llevel_22_8006E8B8
    /* 178C5EC 8006E850 00000000 */   nop
  .Llevel_22_8006E854:
    /* 178C5F0 8006E854 DBAC000C */  jal        func_8002B36C
    /* 178C5F4 8006E858 80090424 */   addiu     $a0, $zero, 0x980
    /* 178C5F8 8006E85C 5A000424 */  addiu      $a0, $zero, 0x5A
    /* 178C5FC 8006E860 C9AE000C */  jal        func_8002BB24
    /* 178C600 8006E864 10000524 */   addiu     $a1, $zero, 0x10
    /* 178C604 8006E868 02004104 */  bgez       $v0, .Llevel_22_8006E874
    /* 178C608 8006E86C 00000000 */   nop
    /* 178C60C 8006E870 23100200 */  negu       $v0, $v0
  .Llevel_22_8006E874:
    /* 178C610 8006E874 01024228 */  slti       $v0, $v0, 0x201
    /* 178C614 8006E878 03004014 */  bnez       $v0, .Llevel_22_8006E888
    /* 178C618 8006E87C 00000000 */   nop
    /* 178C61C 8006E880 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 178C620 8006E884 A4A020AC */  sw         $zero, %lo(D_8006A0A4)($at)
  .Llevel_22_8006E888:
    /* 178C624 8006E888 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 178C628 8006E88C A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 178C62C 8006E890 00000000 */  nop
    /* 178C630 8006E894 810C4228 */  slti       $v0, $v0, 0xC81
    /* 178C634 8006E898 04004014 */  bnez       $v0, .Llevel_22_8006E8AC
    /* 178C638 8006E89C C0000424 */   addiu     $a0, $zero, 0xC0
    /* 178C63C 8006E8A0 21200000 */  addu       $a0, $zero, $zero
    /* 178C640 8006E8A4 2CBA0108 */  j          .Llevel_22_8006E8B0
    /* 178C644 8006E8A8 C0000524 */   addiu     $a1, $zero, 0xC0
  .Llevel_22_8006E8AC:
    /* 178C648 8006E8AC 40000524 */  addiu      $a1, $zero, 0x40
  .Llevel_22_8006E8B0:
    /* 178C64C 8006E8B0 5CAF000C */  jal        func_8002BD70
    /* 178C650 8006E8B4 00000000 */   nop
  .Llevel_22_8006E8B8:
    /* 178C654 8006E8B8 0780103C */  lui        $s0, %hi(D_8006A0A8)
    /* 178C658 8006E8BC A8A01026 */  addiu      $s0, $s0, %lo(D_8006A0A8)
    /* 178C65C 8006E8C0 0000028E */  lw         $v0, 0x0($s0)
    /* 178C660 8006E8C4 00000000 */  nop
    /* 178C664 8006E8C8 09004010 */  beqz       $v0, .Llevel_22_8006E8F0
    /* 178C668 8006E8CC 00000000 */   nop
    /* 178C66C 8006E8D0 6FAF000C */  jal        func_8002BDBC
    /* 178C670 8006E8D4 00000000 */   nop
    /* 178C674 8006E8D8 0EB0000C */  jal        func_8002C038
    /* 178C678 8006E8DC 00000000 */   nop
    /* 178C67C 8006E8E0 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 178C680 8006E8E4 8CA020AC */  sw         $zero, %lo(D_8006A08C)($at)
    /* 178C684 8006E8E8 40BA0108 */  j          .Llevel_22_8006E900
    /* 178C688 8006E8EC 00000000 */   nop
  .Llevel_22_8006E8F0:
    /* 178C68C 8006E8F0 686F000C */  jal        func_8001BDA0
    /* 178C690 8006E8F4 D0FF0426 */   addiu     $a0, $s0, -0x30
    /* 178C694 8006E8F8 686F000C */  jal        func_8001BDA0
    /* 178C698 8006E8FC DCFF0426 */   addiu     $a0, $s0, -0x24
  .Llevel_22_8006E900:
    /* 178C69C 8006E900 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178C6A0 8006E904 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178C6A4 8006E908 00000000 */  nop
    /* 178C6A8 8006E90C 79004010 */  beqz       $v0, .Llevel_22_8006EAF4
    /* 178C6AC 8006E910 00000000 */   nop
    /* 178C6B0 8006E914 0780143C */  lui        $s4, %hi(D_8006A018)
    /* 178C6B4 8006E918 18A09426 */  addiu      $s4, $s4, %lo(D_8006A018)
    /* 178C6B8 8006E91C 0000828E */  lw         $v0, 0x0($s4)
    /* 178C6BC 8006E920 00000000 */  nop
    /* 178C6C0 8006E924 73004104 */  bgez       $v0, .Llevel_22_8006EAF4
    /* 178C6C4 8006E928 00000000 */   nop
    /* 178C6C8 8006E92C 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 178C6CC 8006E930 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 178C6D0 8006E934 00000000 */  nop
    /* 178C6D4 8006E938 01044228 */  slti       $v0, $v0, 0x401
    /* 178C6D8 8006E93C 42004014 */  bnez       $v0, .Llevel_22_8006EA48
    /* 178C6DC 8006E940 0200422A */   slti      $v0, $s2, 0x2
    /* 178C6E0 8006E944 40004010 */  beqz       $v0, .Llevel_22_8006EA48
    /* 178C6E4 8006E948 00000000 */   nop
    /* 178C6E8 8006E94C 0680023C */  lui        $v0, %hi(D_80067008)
    /* 178C6EC 8006E950 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 178C6F0 8006E954 00000000 */  nop
    /* 178C6F4 8006E958 01004230 */  andi       $v0, $v0, 0x1
    /* 178C6F8 8006E95C 3A004010 */  beqz       $v0, .Llevel_22_8006EA48
    /* 178C6FC 8006E960 5000B327 */   addiu     $s3, $sp, 0x50
    /* 178C700 8006E964 21206002 */  addu       $a0, $s3, $zero
    /* 178C704 8006E968 6C6F000C */  jal        func_8001BDB0
    /* 178C708 8006E96C D8FF8526 */   addiu     $a1, $s4, -0x28
    /* 178C70C 8006E970 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 178C710 8006E974 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 178C714 8006E978 40000224 */  addiu      $v0, $zero, 0x40
    /* 178C718 8006E97C 6400A2AF */  sw         $v0, 0x64($sp)
    /* 178C71C 8006E980 6800A0AF */  sw         $zero, 0x68($sp)
    /* 178C720 8006E984 43190300 */  sra        $v1, $v1, 5
    /* 178C724 8006E988 03004012 */  beqz       $s2, .Llevel_22_8006E998
    /* 178C728 8006E98C 6000A3AF */   sw        $v1, 0x60($sp)
    /* 178C72C 8006E990 C0FF0224 */  addiu      $v0, $zero, -0x40
    /* 178C730 8006E994 6400A2AF */  sw         $v0, 0x64($sp)
  .Llevel_22_8006E998:
    /* 178C734 8006E998 08009226 */  addiu      $s2, $s4, 0x8
    /* 178C738 8006E99C 21204002 */  addu       $a0, $s2, $zero
    /* 178C73C 8006E9A0 6000B127 */  addiu      $s1, $sp, 0x60
    /* 178C740 8006E9A4 21282002 */  addu       $a1, $s1, $zero
    /* 178C744 8006E9A8 7000B027 */  addiu      $s0, $sp, 0x70
    /* 178C748 8006E9AC 696E000C */  jal        func_8001B9A4
    /* 178C74C 8006E9B0 21300002 */   addu      $a2, $s0, $zero
    /* 178C750 8006E9B4 21206002 */  addu       $a0, $s3, $zero
    /* 178C754 8006E9B8 21286002 */  addu       $a1, $s3, $zero
    /* 178C758 8006E9BC 736F000C */  jal        func_8001BDCC
    /* 178C75C 8006E9C0 21300002 */   addu      $a2, $s0, $zero
    /* 178C760 8006E9C4 21204002 */  addu       $a0, $s2, $zero
    /* 178C764 8006E9C8 21282002 */  addu       $a1, $s1, $zero
    /* 178C768 8006E9CC 0000828E */  lw         $v0, 0x0($s4)
    /* 178C76C 8006E9D0 21302002 */  addu       $a2, $s1, $zero
    /* 178C770 8006E9D4 6000A0AF */  sw         $zero, 0x60($sp)
    /* 178C774 8006E9D8 23100200 */  negu       $v0, $v0
    /* 178C778 8006E9DC 696E000C */  jal        func_8001B9A4
    /* 178C77C 8006E9E0 5800A2AF */   sw        $v0, 0x58($sp)
    /* 178C780 8006E9E4 21202002 */  addu       $a0, $s1, $zero
    /* 178C784 8006E9E8 526F000C */  jal        func_8001BD48
    /* 178C788 8006E9EC 03000524 */   addiu     $a1, $zero, 0x3
    /* 178C78C 8006E9F0 01000424 */  addiu      $a0, $zero, 0x1
    /* 178C790 8006E9F4 2A000524 */  addiu      $a1, $zero, 0x2A
    /* 178C794 8006E9F8 21306002 */  addu       $a2, $s3, $zero
    /* 178C798 8006E9FC 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178C79C 8006EA00 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178C7A0 8006EA04 00000000 */  nop
    /* 178C7A4 8006EA08 09F84000 */  jalr       $v0
    /* 178C7A8 8006EA0C 21382002 */   addu      $a3, $s1, $zero
    /* 178C7AC 8006EA10 4B67010C */  jal        func_80059D2C
    /* 178C7B0 8006EA14 00000000 */   nop
    /* 178C7B4 8006EA18 1F004230 */  andi       $v0, $v0, 0x1F
    /* 178C7B8 8006EA1C 35004014 */  bnez       $v0, .Llevel_22_8006EAF4
    /* 178C7BC 8006EA20 01000424 */   addiu     $a0, $zero, 0x1
    /* 178C7C0 8006EA24 29000524 */  addiu      $a1, $zero, 0x29
    /* 178C7C4 8006EA28 21306002 */  addu       $a2, $s3, $zero
    /* 178C7C8 8006EA2C 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178C7CC 8006EA30 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178C7D0 8006EA34 00000000 */  nop
    /* 178C7D4 8006EA38 09F84000 */  jalr       $v0
    /* 178C7D8 8006EA3C 21380000 */   addu      $a3, $zero, $zero
    /* 178C7DC 8006EA40 BDBA0108 */  j          .Llevel_22_8006EAF4
    /* 178C7E0 8006EA44 00000000 */   nop
  .Llevel_22_8006EA48:
    /* 178C7E4 8006EA48 0780113C */  lui        $s1, %hi(D_8006A0A8)
    /* 178C7E8 8006EA4C A8A03126 */  addiu      $s1, $s1, %lo(D_8006A0A8)
    /* 178C7EC 8006EA50 0000228E */  lw         $v0, 0x0($s1)
    /* 178C7F0 8006EA54 00000000 */  nop
    /* 178C7F4 8006EA58 01024228 */  slti       $v0, $v0, 0x201
    /* 178C7F8 8006EA5C 25004010 */  beqz       $v0, .Llevel_22_8006EAF4
    /* 178C7FC 8006EA60 00000000 */   nop
    /* 178C800 8006EA64 23004016 */  bnez       $s2, .Llevel_22_8006EAF4
    /* 178C804 8006EA68 00000000 */   nop
    /* 178C808 8006EA6C 0680023C */  lui        $v0, %hi(D_80067008)
    /* 178C80C 8006EA70 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 178C810 8006EA74 00000000 */  nop
    /* 178C814 8006EA78 07004230 */  andi       $v0, $v0, 0x7
    /* 178C818 8006EA7C 1D004014 */  bnez       $v0, .Llevel_22_8006EAF4
    /* 178C81C 8006EA80 00000000 */   nop
    /* 178C820 8006EA84 4B67010C */  jal        func_80059D2C
    /* 178C824 8006EA88 00000000 */   nop
    /* 178C828 8006EA8C 03004230 */  andi       $v0, $v0, 0x3
    /* 178C82C 8006EA90 18004014 */  bnez       $v0, .Llevel_22_8006EAF4
    /* 178C830 8006EA94 78FF2426 */   addiu     $a0, $s1, -0x88
    /* 178C834 8006EA98 8000B027 */  addiu      $s0, $sp, 0x80
    /* 178C838 8006EA9C 21280002 */  addu       $a1, $s0, $zero
    /* 178C83C 8006EAA0 21300002 */  addu       $a2, $s0, $zero
    /* 178C840 8006EAA4 80000224 */  addiu      $v0, $zero, 0x80
    /* 178C844 8006EAA8 8000A2AF */  sw         $v0, 0x80($sp)
    /* 178C848 8006EAAC 8400A0AF */  sw         $zero, 0x84($sp)
    /* 178C84C 8006EAB0 696E000C */  jal        func_8001B9A4
    /* 178C850 8006EAB4 8800A0AF */   sw        $zero, 0x88($sp)
    /* 178C854 8006EAB8 21200002 */  addu       $a0, $s0, $zero
    /* 178C858 8006EABC 21280002 */  addu       $a1, $s0, $zero
    /* 178C85C 8006EAC0 736F000C */  jal        func_8001BDCC
    /* 178C860 8006EAC4 48FF2626 */   addiu     $a2, $s1, -0xB8
    /* 178C864 8006EAC8 01000424 */  addiu      $a0, $zero, 0x1
    /* 178C868 8006EACC 2B000524 */  addiu      $a1, $zero, 0x2B
    /* 178C86C 8006EAD0 21300002 */  addu       $a2, $s0, $zero
    /* 178C870 8006EAD4 01000724 */  addiu      $a3, $zero, 0x1
    /* 178C874 8006EAD8 0780023C */  lui        $v0, %hi(D_8006A018)
    /* 178C878 8006EADC 18A0428C */  lw         $v0, %lo(D_8006A018)($v0)
    /* 178C87C 8006EAE0 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 178C880 8006EAE4 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 178C884 8006EAE8 23100200 */  negu       $v0, $v0
    /* 178C888 8006EAEC 09F86000 */  jalr       $v1
    /* 178C88C 8006EAF0 8800A2AF */   sw        $v0, 0x88($sp)
  .Llevel_22_8006EAF4:
    /* 178C890 8006EAF4 0780063C */  lui        $a2, %hi(D_8006A13C)
    /* 178C894 8006EAF8 3CA1C624 */  addiu      $a2, $a2, %lo(D_8006A13C)
    /* 178C898 8006EAFC 0780043C */  lui        $a0, %hi(D_8006A140)
    /* 178C89C 8006EB00 40A1848C */  lw         $a0, %lo(D_8006A140)($a0)
    /* 178C8A0 8006EB04 0000C58C */  lw         $a1, 0x0($a2)
    /* 178C8A4 8006EB08 40180400 */  sll        $v1, $a0, 1
    /* 178C8A8 8006EB0C 80100500 */  sll        $v0, $a1, 2
    /* 178C8AC 8006EB10 21104500 */  addu       $v0, $v0, $a1
    /* 178C8B0 8006EB14 80100200 */  sll        $v0, $v0, 2
    /* 178C8B4 8006EB18 21186200 */  addu       $v1, $v1, $v0
    /* 178C8B8 8006EB1C 031A0300 */  sra        $v1, $v1, 8
    /* 178C8BC 8006EB20 2328A300 */  subu       $a1, $a1, $v1
    /* 178C8C0 8006EB24 21208500 */  addu       $a0, $a0, $a1
    /* 178C8C4 8006EB28 0000C5AC */  sw         $a1, 0x0($a2)
    /* 178C8C8 8006EB2C 0780013C */  lui        $at, %hi(D_8006A140)
    /* 178C8CC 8006EB30 40A124AC */  sw         $a0, %lo(D_8006A140)($at)
    /* 178C8D0 8006EB34 01598428 */  slti       $a0, $a0, 0x5901
    /* 178C8D4 8006EB38 03008014 */  bnez       $a0, .Llevel_22_8006EB48
    /* 178C8D8 8006EB3C 00590224 */   addiu     $v0, $zero, 0x5900
    /* 178C8DC 8006EB40 0780013C */  lui        $at, %hi(D_8006A140)
    /* 178C8E0 8006EB44 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
  .Llevel_22_8006EB48:
    /* 178C8E4 8006EB48 0780023C */  lui        $v0, %hi(D_8006A140)
    /* 178C8E8 8006EB4C 40A1428C */  lw         $v0, %lo(D_8006A140)($v0)
    /* 178C8EC 8006EB50 00000000 */  nop
    /* 178C8F0 8006EB54 00A74228 */  slti       $v0, $v0, -0x5900
    /* 178C8F4 8006EB58 27004010 */  beqz       $v0, .Llevel_22_8006EBF8
    /* 178C8F8 8006EB5C 00A70224 */   addiu     $v0, $zero, -0x5900
    /* 178C8FC 8006EB60 0780013C */  lui        $at, %hi(D_8006A140)
    /* 178C900 8006EB64 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
    /* 178C904 8006EB68 FEBA0108 */  j          .Llevel_22_8006EBF8
    /* 178C908 8006EB6C 00000000 */   nop
  .Llevel_22_8006EB70:
    /* 178C90C 8006EB70 0900222A */  slti       $v0, $s1, 0x9
    /* 178C910 8006EB74 1A004014 */  bnez       $v0, .Llevel_22_8006EBE0
    /* 178C914 8006EB78 00000000 */   nop
    /* 178C918 8006EB7C 0780043C */  lui        $a0, %hi(D_8006A078)
    /* 178C91C 8006EB80 78A08424 */  addiu      $a0, $a0, %lo(D_8006A078)
    /* 178C920 8006EB84 0780033C */  lui        $v1, %hi(D_8006A084)
    /* 178C924 8006EB88 84A0638C */  lw         $v1, %lo(D_8006A084)($v1)
    /* 178C928 8006EB8C 00000000 */  nop
    /* 178C92C 8006EB90 40110300 */  sll        $v0, $v1, 5
    /* 178C930 8006EB94 23104300 */  subu       $v0, $v0, $v1
    /* 178C934 8006EB98 0780033C */  lui        $v1, %hi(D_8006A088)
    /* 178C938 8006EB9C 88A0638C */  lw         $v1, %lo(D_8006A088)($v1)
    /* 178C93C 8006EBA0 C0100200 */  sll        $v0, $v0, 3
    /* 178C940 8006EBA4 000082AC */  sw         $v0, 0x0($a0)
    /* 178C944 8006EBA8 40110300 */  sll        $v0, $v1, 5
    /* 178C948 8006EBAC 23104300 */  subu       $v0, $v0, $v1
    /* 178C94C 8006EBB0 0780033C */  lui        $v1, %hi(D_8006A08C)
    /* 178C950 8006EBB4 8CA0638C */  lw         $v1, %lo(D_8006A08C)($v1)
    /* 178C954 8006EBB8 C0100200 */  sll        $v0, $v0, 3
    /* 178C958 8006EBBC 0780013C */  lui        $at, %hi(D_8006A07C)
    /* 178C95C 8006EBC0 7CA022AC */  sw         $v0, %lo(D_8006A07C)($at)
    /* 178C960 8006EBC4 40110300 */  sll        $v0, $v1, 5
    /* 178C964 8006EBC8 23104300 */  subu       $v0, $v0, $v1
    /* 178C968 8006EBCC C0100200 */  sll        $v0, $v0, 3
    /* 178C96C 8006EBD0 0780013C */  lui        $at, %hi(D_8006A080)
    /* 178C970 8006EBD4 80A022AC */  sw         $v0, %lo(D_8006A080)($at)
    /* 178C974 8006EBD8 526F000C */  jal        func_8001BD48
    /* 178C978 8006EBDC 08000524 */   addiu     $a1, $zero, 0x8
  .Llevel_22_8006EBE0:
    /* 178C97C 8006EBE0 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 178C980 8006EBE4 84A08424 */  addiu      $a0, $a0, %lo(D_8006A084)
    /* 178C984 8006EBE8 0780053C */  lui        $a1, %hi(D_8006A078)
    /* 178C988 8006EBEC 78A0A524 */  addiu      $a1, $a1, %lo(D_8006A078)
    /* 178C98C 8006EBF0 6C6F000C */  jal        func_8001BDB0
    /* 178C990 8006EBF4 00000000 */   nop
  .Llevel_22_8006EBF8:
    /* 178C994 8006EBF8 A400BF8F */  lw         $ra, 0xA4($sp)
    /* 178C998 8006EBFC A000B48F */  lw         $s4, 0xA0($sp)
    /* 178C99C 8006EC00 9C00B38F */  lw         $s3, 0x9C($sp)
    /* 178C9A0 8006EC04 9800B28F */  lw         $s2, 0x98($sp)
    /* 178C9A4 8006EC08 9400B18F */  lw         $s1, 0x94($sp)
    /* 178C9A8 8006EC0C 9000B08F */  lw         $s0, 0x90($sp)
    /* 178C9AC 8006EC10 A800BD27 */  addiu      $sp, $sp, 0xA8
    /* 178C9B0 8006EC14 0800E003 */  jr         $ra
    /* 178C9B4 8006EC18 00000000 */   nop
endlabel func_level_22_8006DBD0
