.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_22_8006D3F8

dlabel jtbl_level_22_8006D3F8
    /* 178B194 8006D3F8 98F00680 */ .word .Llevel_22_8006F098
    /* 178B198 8006D3FC C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B19C 8006D400 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1A0 8006D404 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1A4 8006D408 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1A8 8006D40C C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1AC 8006D410 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1B0 8006D414 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1B4 8006D418 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1B8 8006D41C C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1BC 8006D420 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1C0 8006D424 B0F00680 */ .word .Llevel_22_8006F0B0
    /* 178B1C4 8006D428 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1C8 8006D42C C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1CC 8006D430 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1D0 8006D434 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1D4 8006D438 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1D8 8006D43C C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1DC 8006D440 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1E0 8006D444 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1E4 8006D448 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1E8 8006D44C C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1EC 8006D450 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1F0 8006D454 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1F4 8006D458 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1F8 8006D45C C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B1FC 8006D460 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B200 8006D464 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B204 8006D468 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B208 8006D46C C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B20C 8006D470 B0F00680 */ .word .Llevel_22_8006F0B0
    /* 178B210 8006D474 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B214 8006D478 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B218 8006D47C C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B21C 8006D480 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B220 8006D484 B0F00680 */ .word .Llevel_22_8006F0B0
    /* 178B224 8006D488 B0F00680 */ .word .Llevel_22_8006F0B0
    /* 178B228 8006D48C C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B22C 8006D490 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B230 8006D494 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B234 8006D498 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B238 8006D49C C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B23C 8006D4A0 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B240 8006D4A4 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B244 8006D4A8 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B248 8006D4AC C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B24C 8006D4B0 B0F00680 */ .word .Llevel_22_8006F0B0
    /* 178B250 8006D4B4 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B254 8006D4B8 C0F00680 */ .word .Llevel_22_8006F0C0
    /* 178B258 8006D4BC C0F00680 */ .word .Llevel_22_8006F0C0
enddlabel jtbl_level_22_8006D3F8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_22_8006F048, 0x88

glabel func_level_22_8006F048
    /* 178CDE4 8006F048 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 178CDE8 8006F04C 00210400 */  sll        $a0, $a0, 4
    /* 178CDEC 8006F050 0780023C */  lui        $v0, %hi(D_800683B0)
    /* 178CDF0 8006F054 B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* 178CDF4 8006F058 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 178CDF8 8006F05C 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 178CDFC 8006F060 21208200 */  addu       $a0, $a0, $v0
    /* 178CE00 8006F064 1000BFAF */  sw         $ra, 0x10($sp)
    /* 178CE04 8006F068 0680013C */  lui        $at, %hi(D_80066F38)
    /* 178CE08 8006F06C 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* 178CE0C 8006F070 F8FF6324 */  addiu      $v1, $v1, -0x8
    /* 178CE10 8006F074 3200622C */  sltiu      $v0, $v1, 0x32
    /* 178CE14 8006F078 11004010 */  beqz       $v0, .Llevel_22_8006F0C0
    /* 178CE18 8006F07C 80100300 */   sll       $v0, $v1, 2
    /* 178CE1C 8006F080 0780013C */  lui        $at, %hi(jtbl_level_22_8006D3F8)
    /* 178CE20 8006F084 21082200 */  addu       $at, $at, $v0
    /* 178CE24 8006F088 F8D3228C */  lw         $v0, %lo(jtbl_level_22_8006D3F8)($at)
    /* 178CE28 8006F08C 00000000 */  nop
    /* 178CE2C 8006F090 08004000 */  jr         $v0
    /* 178CE30 8006F094 00000000 */   nop
  .Llevel_22_8006F098:
    /* 178CE34 8006F098 0780043C */  lui        $a0, %hi(D_8006A044)
    /* 178CE38 8006F09C 44A08424 */  addiu      $a0, $a0, %lo(D_8006A044)
    /* 178CE3C 8006F0A0 0000838C */  lw         $v1, 0x0($a0)
    /* 178CE40 8006F0A4 01000224 */  addiu      $v0, $zero, 0x1
    /* 178CE44 8006F0A8 03006210 */  beq        $v1, $v0, .Llevel_22_8006F0B8
    /* 178CE48 8006F0AC 21200000 */   addu      $a0, $zero, $zero
  .Llevel_22_8006F0B0:
    /* 178CE4C 8006F0B0 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* 178CE50 8006F0B4 C4A08424 */  addiu      $a0, $a0, %lo(D_8006A0C4)
  .Llevel_22_8006F0B8:
    /* 178CE54 8006F0B8 E3B6000C */  jal        func_8002DB8C
    /* 178CE58 8006F0BC 00000000 */   nop
  .Llevel_22_8006F0C0:
    /* 178CE5C 8006F0C0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 178CE60 8006F0C4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 178CE64 8006F0C8 0800E003 */  jr         $ra
    /* 178CE68 8006F0CC 00000000 */   nop
endlabel func_level_22_8006F048
