.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_22_8006D4C0

dlabel jtbl_level_22_8006D4C0
    /* 178B25C 8006D4C0 9CF10680 */ .word .Llevel_22_8006F19C
    /* 178B260 8006D4C4 88F90680 */ .word .Llevel_22_8006F988
    /* 178B264 8006D4C8 88F90680 */ .word .Llevel_22_8006F988
    /* 178B268 8006D4CC 88F90680 */ .word .Llevel_22_8006F988
    /* 178B26C 8006D4D0 88F90680 */ .word .Llevel_22_8006F988
    /* 178B270 8006D4D4 88F90680 */ .word .Llevel_22_8006F988
    /* 178B274 8006D4D8 88F90680 */ .word .Llevel_22_8006F988
    /* 178B278 8006D4DC 88F90680 */ .word .Llevel_22_8006F988
    /* 178B27C 8006D4E0 88F90680 */ .word .Llevel_22_8006F988
    /* 178B280 8006D4E4 88F90680 */ .word .Llevel_22_8006F988
    /* 178B284 8006D4E8 88F90680 */ .word .Llevel_22_8006F988
    /* 178B288 8006D4EC 0CF10680 */ .word .Llevel_22_8006F10C
    /* 178B28C 8006D4F0 88F90680 */ .word .Llevel_22_8006F988
    /* 178B290 8006D4F4 88F90680 */ .word .Llevel_22_8006F988
    /* 178B294 8006D4F8 88F90680 */ .word .Llevel_22_8006F988
    /* 178B298 8006D4FC 88F90680 */ .word .Llevel_22_8006F988
    /* 178B29C 8006D500 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2A0 8006D504 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2A4 8006D508 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2A8 8006D50C 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2AC 8006D510 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2B0 8006D514 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2B4 8006D518 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2B8 8006D51C 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2BC 8006D520 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2C0 8006D524 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2C4 8006D528 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2C8 8006D52C 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2CC 8006D530 28F30680 */ .word .Llevel_22_8006F328
    /* 178B2D0 8006D534 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2D4 8006D538 0CF10680 */ .word .Llevel_22_8006F10C
    /* 178B2D8 8006D53C 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2DC 8006D540 98F30680 */ .word .Llevel_22_8006F398
    /* 178B2E0 8006D544 98F30680 */ .word .Llevel_22_8006F398
    /* 178B2E4 8006D548 64F50680 */ .word .Llevel_22_8006F564
    /* 178B2E8 8006D54C 40F70680 */ .word .Llevel_22_8006F740
    /* 178B2EC 8006D550 40F70680 */ .word .Llevel_22_8006F740
    /* 178B2F0 8006D554 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2F4 8006D558 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2F8 8006D55C 88F90680 */ .word .Llevel_22_8006F988
    /* 178B2FC 8006D560 88F90680 */ .word .Llevel_22_8006F988
    /* 178B300 8006D564 88F90680 */ .word .Llevel_22_8006F988
    /* 178B304 8006D568 88F90680 */ .word .Llevel_22_8006F988
    /* 178B308 8006D56C 88F90680 */ .word .Llevel_22_8006F988
    /* 178B30C 8006D570 88F90680 */ .word .Llevel_22_8006F988
    /* 178B310 8006D574 88F90680 */ .word .Llevel_22_8006F988
    /* 178B314 8006D578 70F80680 */ .word .Llevel_22_8006F870
    /* 178B318 8006D57C 88F90680 */ .word .Llevel_22_8006F988
    /* 178B31C 8006D580 88F90680 */ .word .Llevel_22_8006F988
    /* 178B320 8006D584 9CF80680 */ .word .Llevel_22_8006F89C
enddlabel jtbl_level_22_8006D4C0


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_22_8006F0D0, 0x8D0

glabel func_level_22_8006F0D0
    /* 178CE6C 8006F0D0 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 178CE70 8006F0D4 4400B1AF */  sw         $s1, 0x44($sp)
    /* 178CE74 8006F0D8 21888000 */  addu       $s1, $a0, $zero
    /* 178CE78 8006F0DC F8FF2326 */  addiu      $v1, $s1, -0x8
    /* 178CE7C 8006F0E0 3200622C */  sltiu      $v0, $v1, 0x32
    /* 178CE80 8006F0E4 4800BFAF */  sw         $ra, 0x48($sp)
    /* 178CE84 8006F0E8 27024010 */  beqz       $v0, .Llevel_22_8006F988
    /* 178CE88 8006F0EC 4000B0AF */   sw        $s0, 0x40($sp)
    /* 178CE8C 8006F0F0 80100300 */  sll        $v0, $v1, 2
    /* 178CE90 8006F0F4 0780013C */  lui        $at, %hi(jtbl_level_22_8006D4C0)
    /* 178CE94 8006F0F8 21082200 */  addu       $at, $at, $v0
    /* 178CE98 8006F0FC C0D4228C */  lw         $v0, %lo(jtbl_level_22_8006D4C0)($at)
    /* 178CE9C 8006F100 00000000 */  nop
    /* 178CEA0 8006F104 08004000 */  jr         $v0
    /* 178CEA4 8006F108 00000000 */   nop
  .Llevel_22_8006F10C:
    /* 178CEA8 8006F10C 0780013C */  lui        $at, %hi(D_8006A048)
    /* 178CEAC 8006F110 48A020AC */  sw         $zero, %lo(D_8006A048)($at)
    /* 178CEB0 8006F114 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178CEB4 8006F118 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 178CEB8 8006F11C AFB8000C */  jal        func_8002E2BC
    /* 178CEBC 8006F120 00000000 */   nop
    /* 178CEC0 8006F124 01000224 */  addiu      $v0, $zero, 0x1
    /* 178CEC4 8006F128 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 178CEC8 8006F12C ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 178CECC 8006F130 25000224 */  addiu      $v0, $zero, 0x25
    /* 178CED0 8006F134 04002216 */  bne        $s1, $v0, .Llevel_22_8006F148
    /* 178CED4 8006F138 01000424 */   addiu     $a0, $zero, 0x1
    /* 178CED8 8006F13C 05000424 */  addiu      $a0, $zero, 0x5
    /* 178CEDC 8006F140 53BC0108 */  j          .Llevel_22_8006F14C
    /* 178CEE0 8006F144 08000524 */   addiu     $a1, $zero, 0x8
  .Llevel_22_8006F148:
    /* 178CEE4 8006F148 03000524 */  addiu      $a1, $zero, 0x3
  .Llevel_22_8006F14C:
    /* 178CEE8 8006F14C 47E2000C */  jal        func_8003891C
    /* 178CEEC 8006F150 00000000 */   nop
    /* 178CEF0 8006F154 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 178CEF4 8006F158 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* 178CEF8 8006F15C 0680033C */  lui        $v1, %hi(D_800670B4)
    /* 178CEFC 8006F160 B470638C */  lw         $v1, %lo(D_800670B4)($v1)
    /* 178CF00 8006F164 0780013C */  lui        $at, %hi(D_8006A140)
    /* 178CF04 8006F168 40A120AC */  sw         $zero, %lo(D_8006A140)($at)
    /* 178CF08 8006F16C 06026010 */  beqz       $v1, .Llevel_22_8006F988
    /* 178CF0C 8006F170 25000224 */   addiu     $v0, $zero, 0x25
    /* 178CF10 8006F174 03002216 */  bne        $s1, $v0, .Llevel_22_8006F184
    /* 178CF14 8006F178 27000224 */   addiu     $v0, $zero, 0x27
    /* 178CF18 8006F17C 63BC0108 */  j          .Llevel_22_8006F18C
    /* 178CF1C 8006F180 F1010424 */   addiu     $a0, $zero, 0x1F1
  .Llevel_22_8006F184:
    /* 178CF20 8006F184 00022216 */  bne        $s1, $v0, .Llevel_22_8006F988
    /* 178CF24 8006F188 DB010424 */   addiu     $a0, $zero, 0x1DB
  .Llevel_22_8006F18C:
    /* 178CF28 8006F18C 09F86000 */  jalr       $v1
    /* 178CF2C 8006F190 21280000 */   addu      $a1, $zero, $zero
    /* 178CF30 8006F194 62BE0108 */  j          .Llevel_22_8006F988
    /* 178CF34 8006F198 00000000 */   nop
  .Llevel_22_8006F19C:
    /* 178CF38 8006F19C 0780113C */  lui        $s1, %hi(D_8006A104)
    /* 178CF3C 8006F1A0 04A13126 */  addiu      $s1, $s1, %lo(D_8006A104)
    /* 178CF40 8006F1A4 0000248E */  lw         $a0, 0x0($s1)
    /* 178CF44 8006F1A8 1EAC000C */  jal        func_8002B078
    /* 178CF48 8006F1AC 00000000 */   nop
    /* 178CF4C 8006F1B0 07000624 */  addiu      $a2, $zero, 0x7
    /* 178CF50 8006F1B4 19004614 */  bne        $v0, $a2, .Llevel_22_8006F21C
    /* 178CF54 8006F1B8 80FF2426 */   addiu     $a0, $s1, -0x80
    /* 178CF58 8006F1BC 8CFF3026 */  addiu      $s0, $s1, -0x74
    /* 178CF5C 8006F1C0 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 178CF60 8006F1C4 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* 178CF64 8006F1C8 01000224 */  addiu      $v0, $zero, 0x1
    /* 178CF68 8006F1CC 0780013C */  lui        $at, %hi(D_8006A048)
    /* 178CF6C 8006F1D0 48A026AC */  sw         $a2, %lo(D_8006A048)($at)
    /* 178CF70 8006F1D4 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178CF74 8006F1D8 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 178CF78 8006F1DC 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 178CF7C 8006F1E0 3CA123AC */  sw         $v1, %lo(D_8006A13C)($at)
    /* 178CF80 8006F1E4 6C6F000C */  jal        func_8001BDB0
    /* 178CF84 8006F1E8 21280002 */   addu      $a1, $s0, $zero
    /* 178CF88 8006F1EC 21200002 */  addu       $a0, $s0, $zero
    /* 178CF8C 8006F1F0 886E000C */  jal        func_8001BA20
    /* 178CF90 8006F1F4 21280000 */   addu      $a1, $zero, $zero
    /* 178CF94 8006F1F8 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 178CF98 8006F1FC A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 178CF9C 8006F200 C00D0224 */  addiu      $v0, $zero, 0xDC0
    /* 178CFA0 8006F204 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 178CFA4 8006F208 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 178CFA8 8006F20C 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 178CFAC 8006F210 ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 178CFB0 8006F214 BDBC0108 */  j          .Llevel_22_8006F2F4
    /* 178CFB4 8006F218 00000000 */   nop
  .Llevel_22_8006F21C:
    /* 178CFB8 8006F21C 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 178CFBC 8006F220 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* 178CFC0 8006F224 0780023C */  lui        $v0, %hi(D_8006A1FC)
    /* 178CFC4 8006F228 FCA1428C */  lw         $v0, %lo(D_8006A1FC)($v0)
    /* 178CFC8 8006F22C 0780013C */  lui        $at, %hi(D_8006A048)
    /* 178CFCC 8006F230 48A026AC */  sw         $a2, %lo(D_8006A048)($at)
    /* 178CFD0 8006F234 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178CFD4 8006F238 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 178CFD8 8006F23C 00044230 */  andi       $v0, $v0, 0x400
    /* 178CFDC 8006F240 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 178CFE0 8006F244 3CA123AC */  sw         $v1, %lo(D_8006A13C)($at)
    /* 178CFE4 8006F248 09004010 */  beqz       $v0, .Llevel_22_8006F270
    /* 178CFE8 8006F24C 80FF3026 */   addiu     $s0, $s1, -0x80
    /* 178CFEC 8006F250 21200002 */  addu       $a0, $s0, $zero
    /* 178CFF0 8006F254 6C6F000C */  jal        func_8001BDB0
    /* 178CFF4 8006F258 08012526 */   addiu     $a1, $s1, 0x108
    /* 178CFF8 8006F25C 21200002 */  addu       $a0, $s0, $zero
    /* 178CFFC 8006F260 486F000C */  jal        func_8001BD20
    /* 178D000 8006F264 06000524 */   addiu     $a1, $zero, 0x6
    /* 178D004 8006F268 B4BC0108 */  j          .Llevel_22_8006F2D0
    /* 178D008 8006F26C 00000000 */   nop
  .Llevel_22_8006F270:
    /* 178D00C 8006F270 0780023C */  lui        $v0, %hi(D_8006A264)
    /* 178D010 8006F274 64A2428C */  lw         $v0, %lo(D_8006A264)($v0)
    /* 178D014 8006F278 00000000 */  nop
    /* 178D018 8006F27C 12004004 */  bltz       $v0, .Llevel_22_8006F2C8
    /* 178D01C 8006F280 40100200 */   sll       $v0, $v0, 1
    /* 178D020 8006F284 0680013C */  lui        $at, %hi(D_80061C58)
    /* 178D024 8006F288 21082200 */  addu       $at, $at, $v0
    /* 178D028 8006F28C 581C2384 */  lh         $v1, %lo(D_80061C58)($at)
    /* 178D02C 8006F290 00000000 */  nop
    /* 178D030 8006F294 43180300 */  sra        $v1, $v1, 1
    /* 178D034 8006F298 0780013C */  lui        $at, %hi(D_8006A084)
    /* 178D038 8006F29C 84A023AC */  sw         $v1, %lo(D_8006A084)($at)
    /* 178D03C 8006F2A0 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 178D040 8006F2A4 21082200 */  addu       $at, $at, $v0
    /* 178D044 8006F2A8 D81B2284 */  lh         $v0, %lo(D_80061BD8)($at)
    /* 178D048 8006F2AC 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 178D04C 8006F2B0 8CA020AC */  sw         $zero, %lo(D_8006A08C)($at)
    /* 178D050 8006F2B4 43100200 */  sra        $v0, $v0, 1
    /* 178D054 8006F2B8 0780013C */  lui        $at, %hi(D_8006A088)
    /* 178D058 8006F2BC 88A022AC */  sw         $v0, %lo(D_8006A088)($at)
    /* 178D05C 8006F2C0 B4BC0108 */  j          .Llevel_22_8006F2D0
    /* 178D060 8006F2C4 00000000 */   nop
  .Llevel_22_8006F2C8:
    /* 178D064 8006F2C8 686F000C */  jal        func_8001BDA0
    /* 178D068 8006F2CC 80FF2426 */   addiu     $a0, $s1, -0x80
  .Llevel_22_8006F2D0:
    /* 178D06C 8006F2D0 0780043C */  lui        $a0, %hi(D_8006A078)
    /* 178D070 8006F2D4 78A08424 */  addiu      $a0, $a0, %lo(D_8006A078)
    /* 178D074 8006F2D8 6C6F000C */  jal        func_8001BDB0
    /* 178D078 8006F2DC 0C008524 */   addiu     $a1, $a0, 0xC
    /* 178D07C 8006F2E0 C2B6000C */  jal        func_8002DB08
    /* 178D080 8006F2E4 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 178D084 8006F2E8 01000224 */  addiu      $v0, $zero, 0x1
    /* 178D088 8006F2EC 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 178D08C 8006F2F0 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
  .Llevel_22_8006F2F4:
    /* 178D090 8006F2F4 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 178D094 8006F2F8 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 178D098 8006F2FC 2D000224 */  addiu      $v0, $zero, 0x2D
    /* 178D09C 8006F300 0780013C */  lui        $at, %hi(D_80068390)
    /* 178D0A0 8006F304 908322AC */  sw         $v0, %lo(D_80068390)($at)
    /* 178D0A4 8006F308 9F016010 */  beqz       $v1, .Llevel_22_8006F988
    /* 178D0A8 8006F30C 05000424 */   addiu     $a0, $zero, 0x5
    /* 178D0AC 8006F310 0A000524 */  addiu      $a1, $zero, 0xA
    /* 178D0B0 8006F314 21300000 */  addu       $a2, $zero, $zero
    /* 178D0B4 8006F318 09F86000 */  jalr       $v1
    /* 178D0B8 8006F31C 21380000 */   addu      $a3, $zero, $zero
    /* 178D0BC 8006F320 62BE0108 */  j          .Llevel_22_8006F988
    /* 178D0C0 8006F324 00000000 */   nop
  .Llevel_22_8006F328:
    /* 178D0C4 8006F328 0780103C */  lui        $s0, %hi(D_8006A048)
    /* 178D0C8 8006F32C 48A01026 */  addiu      $s0, $s0, %lo(D_8006A048)
    /* 178D0CC 8006F330 0B000224 */  addiu      $v0, $zero, 0xB
    /* 178D0D0 8006F334 000002AE */  sw         $v0, 0x0($s0)
    /* 178D0D4 8006F338 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 178D0D8 8006F33C 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 178D0DC 8006F340 2A000224 */  addiu      $v0, $zero, 0x2A
    /* 178D0E0 8006F344 03006214 */  bne        $v1, $v0, .Llevel_22_8006F354
    /* 178D0E4 8006F348 02000224 */   addiu     $v0, $zero, 0x2
    /* 178D0E8 8006F34C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178D0EC 8006F350 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
  .Llevel_22_8006F354:
    /* 178D0F0 8006F354 686F000C */  jal        func_8001BDA0
    /* 178D0F4 8006F358 FC000426 */   addiu     $a0, $s0, 0xFC
    /* 178D0F8 8006F35C 48000426 */  addiu      $a0, $s0, 0x48
    /* 178D0FC 8006F360 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 178D100 8006F364 3CA120AC */  sw         $zero, %lo(D_8006A13C)($at)
    /* 178D104 8006F368 886E000C */  jal        func_8001BA20
    /* 178D108 8006F36C 21280000 */   addu      $a1, $zero, $zero
    /* 178D10C 8006F370 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 178D110 8006F374 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 178D114 8006F378 01000224 */  addiu      $v0, $zero, 0x1
    /* 178D118 8006F37C 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 178D11C 8006F380 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 178D120 8006F384 80020224 */  addiu      $v0, $zero, 0x280
    /* 178D124 8006F388 0780013C */  lui        $at, %hi(D_8006A260)
    /* 178D128 8006F38C 60A222AC */  sw         $v0, %lo(D_8006A260)($at)
    /* 178D12C 8006F390 62BE0108 */  j          .Llevel_22_8006F988
    /* 178D130 8006F394 00000000 */   nop
  .Llevel_22_8006F398:
    /* 178D134 8006F398 0780103C */  lui        $s0, %hi(D_8006A048)
    /* 178D138 8006F39C 48A01026 */  addiu      $s0, $s0, %lo(D_8006A048)
    /* 178D13C 8006F3A0 0000038E */  lw         $v1, 0x0($s0)
    /* 178D140 8006F3A4 00000000 */  nop
    /* 178D144 8006F3A8 F5FF6224 */  addiu      $v0, $v1, -0xB
    /* 178D148 8006F3AC 0200422C */  sltiu      $v0, $v0, 0x2
    /* 178D14C 8006F3B0 5D004014 */  bnez       $v0, .Llevel_22_8006F528
    /* 178D150 8006F3B4 07000224 */   addiu     $v0, $zero, 0x7
    /* 178D154 8006F3B8 5B006210 */  beq        $v1, $v0, .Llevel_22_8006F528
    /* 178D158 8006F3BC 00000000 */   nop
    /* 178D15C 8006F3C0 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178D160 8006F3C4 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178D164 8006F3C8 00000000 */  nop
    /* 178D168 8006F3CC 2F004010 */  beqz       $v0, .Llevel_22_8006F48C
    /* 178D16C 8006F3D0 1000A427 */   addiu     $a0, $sp, 0x10
    /* 178D170 8006F3D4 6C6F000C */  jal        func_8001BDB0
    /* 178D174 8006F3D8 A8FF0526 */   addiu     $a1, $s0, -0x58
    /* 178D178 8006F3DC 0000038E */  lw         $v1, 0x0($s0)
    /* 178D17C 8006F3E0 0A000224 */  addiu      $v0, $zero, 0xA
    /* 178D180 8006F3E4 11006214 */  bne        $v1, $v0, .Llevel_22_8006F42C
    /* 178D184 8006F3E8 00000000 */   nop
    /* 178D188 8006F3EC 0780033C */  lui        $v1, %hi(D_8006A018)
    /* 178D18C 8006F3F0 18A0638C */  lw         $v1, %lo(D_8006A018)($v1)
    /* 178D190 8006F3F4 00000000 */  nop
    /* 178D194 8006F3F8 0C006104 */  bgez       $v1, .Llevel_22_8006F42C
    /* 178D198 8006F3FC 06000424 */   addiu     $a0, $zero, 0x6
    /* 178D19C 8006F400 2E000524 */  addiu      $a1, $zero, 0x2E
    /* 178D1A0 8006F404 1000A627 */  addiu      $a2, $sp, 0x10
    /* 178D1A4 8006F408 21380000 */  addu       $a3, $zero, $zero
    /* 178D1A8 8006F40C 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178D1AC 8006F410 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178D1B0 8006F414 23180300 */  negu       $v1, $v1
    /* 178D1B4 8006F418 09F84000 */  jalr       $v0
    /* 178D1B8 8006F41C 1800A3AF */   sw        $v1, 0x18($sp)
    /* 178D1BC 8006F420 04000424 */  addiu      $a0, $zero, 0x4
    /* 178D1C0 8006F424 1DBD0108 */  j          .Llevel_22_8006F474
    /* 178D1C4 8006F428 29000524 */   addiu     $a1, $zero, 0x29
  .Llevel_22_8006F42C:
    /* 178D1C8 8006F42C 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 178D1CC 8006F430 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* 178D1D0 8006F434 04000224 */  addiu      $v0, $zero, 0x4
    /* 178D1D4 8006F438 14006214 */  bne        $v1, $v0, .Llevel_22_8006F48C
    /* 178D1D8 8006F43C 1000A427 */   addiu     $a0, $sp, 0x10
    /* 178D1DC 8006F440 1800A28F */  lw         $v0, 0x18($sp)
    /* 178D1E0 8006F444 00080524 */  addiu      $a1, $zero, 0x800
    /* 178D1E4 8006F448 00044224 */  addiu      $v0, $v0, 0x400
    /* 178D1E8 8006F44C A1FB000C */  jal        func_8003EE84
    /* 178D1EC 8006F450 1800A2AF */   sw        $v0, 0x18($sp)
    /* 178D1F0 8006F454 0D004010 */  beqz       $v0, .Llevel_22_8006F48C
    /* 178D1F4 8006F458 1800A2AF */   sw        $v0, 0x18($sp)
    /* 178D1F8 8006F45C 0780023C */  lui        $v0, %hi(D_8006ABA4)
    /* 178D1FC 8006F460 A4AB428C */  lw         $v0, %lo(D_8006ABA4)($v0)
    /* 178D200 8006F464 00000000 */  nop
    /* 178D204 8006F468 08004010 */  beqz       $v0, .Llevel_22_8006F48C
    /* 178D208 8006F46C 06000424 */   addiu     $a0, $zero, 0x6
    /* 178D20C 8006F470 2E000524 */  addiu      $a1, $zero, 0x2E
  .Llevel_22_8006F474:
    /* 178D210 8006F474 1000A627 */  addiu      $a2, $sp, 0x10
    /* 178D214 8006F478 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178D218 8006F47C FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178D21C 8006F480 00000000 */  nop
    /* 178D220 8006F484 09F84000 */  jalr       $v0
    /* 178D224 8006F488 21380000 */   addu      $a3, $zero, $zero
  .Llevel_22_8006F48C:
    /* 178D228 8006F48C 0780103C */  lui        $s0, %hi(D_8006A058)
    /* 178D22C 8006F490 58A01026 */  addiu      $s0, $s0, %lo(D_8006A058)
    /* 178D230 8006F494 0000028E */  lw         $v0, 0x0($s0)
    /* 178D234 8006F498 00000000 */  nop
    /* 178D238 8006F49C FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 178D23C 8006F4A0 01086228 */  slti       $v0, $v1, 0x801
    /* 178D240 8006F4A4 03004014 */  bnez       $v0, .Llevel_22_8006F4B4
    /* 178D244 8006F4A8 000003AE */   sw        $v1, 0x0($s0)
    /* 178D248 8006F4AC 00F06224 */  addiu      $v0, $v1, -0x1000
    /* 178D24C 8006F4B0 000002AE */  sw         $v0, 0x0($s0)
  .Llevel_22_8006F4B4:
    /* 178D250 8006F4B4 0000028E */  lw         $v0, 0x0($s0)
    /* 178D254 8006F4B8 00000000 */  nop
    /* 178D258 8006F4BC 02004018 */  blez       $v0, .Llevel_22_8006F4C8
    /* 178D25C 8006F4C0 28000224 */   addiu     $v0, $zero, 0x28
    /* 178D260 8006F4C4 000000AE */  sw         $zero, 0x0($s0)
  .Llevel_22_8006F4C8:
    /* 178D264 8006F4C8 03002216 */  bne        $s1, $v0, .Llevel_22_8006F4D8
    /* 178D268 8006F4CC 01000224 */   addiu     $v0, $zero, 0x1
    /* 178D26C 8006F4D0 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178D270 8006F4D4 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
  .Llevel_22_8006F4D8:
    /* 178D274 8006F4D8 686F000C */  jal        func_8001BDA0
    /* 178D278 8006F4DC EC000426 */   addiu     $a0, $s0, 0xEC
    /* 178D27C 8006F4E0 38000426 */  addiu      $a0, $s0, 0x38
    /* 178D280 8006F4E4 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 178D284 8006F4E8 3CA120AC */  sw         $zero, %lo(D_8006A13C)($at)
    /* 178D288 8006F4EC 886E000C */  jal        func_8001BA20
    /* 178D28C 8006F4F0 21280000 */   addu      $a1, $zero, $zero
    /* 178D290 8006F4F4 0680033C */  lui        $v1, %hi(D_80067020)
    /* 178D294 8006F4F8 2070638C */  lw         $v1, %lo(D_80067020)($v1)
    /* 178D298 8006F4FC 21280000 */  addu       $a1, $zero, $zero
    /* 178D29C 8006F500 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 178D2A0 8006F504 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 178D2A4 8006F508 01000224 */  addiu      $v0, $zero, 0x1
    /* 178D2A8 8006F50C 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 178D2AC 8006F510 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 178D2B0 8006F514 08006490 */  lbu        $a0, 0x8($v1)
    /* 178D2B4 8006F518 C841010C */  jal        func_80050720
    /* 178D2B8 8006F51C 21300000 */   addu      $a2, $zero, $zero
    /* 178D2BC 8006F520 52BD0108 */  j          .Llevel_22_8006F548
    /* 178D2C0 8006F524 00000000 */   nop
  .Llevel_22_8006F528:
    /* 178D2C4 8006F528 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 178D2C8 8006F52C 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 178D2CC 8006F530 2A000224 */  addiu      $v0, $zero, 0x2A
    /* 178D2D0 8006F534 07006214 */  bne        $v1, $v0, .Llevel_22_8006F554
    /* 178D2D4 8006F538 0B000224 */   addiu     $v0, $zero, 0xB
    /* 178D2D8 8006F53C 02000224 */  addiu      $v0, $zero, 0x2
    /* 178D2DC 8006F540 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178D2E0 8006F544 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
  .Llevel_22_8006F548:
    /* 178D2E4 8006F548 0780013C */  lui        $at, %hi(D_8006A150)
    /* 178D2E8 8006F54C 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 178D2EC 8006F550 0B000224 */  addiu      $v0, $zero, 0xB
  .Llevel_22_8006F554:
    /* 178D2F0 8006F554 0780013C */  lui        $at, %hi(D_8006A048)
    /* 178D2F4 8006F558 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 178D2F8 8006F55C 62BE0108 */  j          .Llevel_22_8006F988
    /* 178D2FC 8006F560 00000000 */   nop
  .Llevel_22_8006F564:
    /* 178D300 8006F564 0780113C */  lui        $s1, %hi(D_8006A048)
    /* 178D304 8006F568 48A03126 */  addiu      $s1, $s1, %lo(D_8006A048)
    /* 178D308 8006F56C 0000228E */  lw         $v0, 0x0($s1)
    /* 178D30C 8006F570 00000000 */  nop
    /* 178D310 8006F574 F5FF4224 */  addiu      $v0, $v0, -0xB
    /* 178D314 8006F578 0200422C */  sltiu      $v0, $v0, 0x2
    /* 178D318 8006F57C 69004014 */  bnez       $v0, .Llevel_22_8006F724
    /* 178D31C 8006F580 0C000224 */   addiu     $v0, $zero, 0xC
    /* 178D320 8006F584 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178D324 8006F588 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178D328 8006F58C 00000000 */  nop
    /* 178D32C 8006F590 31004010 */  beqz       $v0, .Llevel_22_8006F658
    /* 178D330 8006F594 2000B027 */   addiu     $s0, $sp, 0x20
    /* 178D334 8006F598 21200002 */  addu       $a0, $s0, $zero
    /* 178D338 8006F59C 6C6F000C */  jal        func_8001BDB0
    /* 178D33C 8006F5A0 A8FF2526 */   addiu     $a1, $s1, -0x58
    /* 178D340 8006F5A4 0000238E */  lw         $v1, 0x0($s1)
    /* 178D344 8006F5A8 0A000224 */  addiu      $v0, $zero, 0xA
    /* 178D348 8006F5AC 11006214 */  bne        $v1, $v0, .Llevel_22_8006F5F4
    /* 178D34C 8006F5B0 00000000 */   nop
    /* 178D350 8006F5B4 0780033C */  lui        $v1, %hi(D_8006A018)
    /* 178D354 8006F5B8 18A0638C */  lw         $v1, %lo(D_8006A018)($v1)
    /* 178D358 8006F5BC 00000000 */  nop
    /* 178D35C 8006F5C0 0C006104 */  bgez       $v1, .Llevel_22_8006F5F4
    /* 178D360 8006F5C4 06000424 */   addiu     $a0, $zero, 0x6
    /* 178D364 8006F5C8 2E000524 */  addiu      $a1, $zero, 0x2E
    /* 178D368 8006F5CC 21300002 */  addu       $a2, $s0, $zero
    /* 178D36C 8006F5D0 21380000 */  addu       $a3, $zero, $zero
    /* 178D370 8006F5D4 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178D374 8006F5D8 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178D378 8006F5DC 23180300 */  negu       $v1, $v1
    /* 178D37C 8006F5E0 09F84000 */  jalr       $v0
    /* 178D380 8006F5E4 2800A3AF */   sw        $v1, 0x28($sp)
    /* 178D384 8006F5E8 04000424 */  addiu      $a0, $zero, 0x4
    /* 178D388 8006F5EC 90BD0108 */  j          .Llevel_22_8006F640
    /* 178D38C 8006F5F0 29000524 */   addiu     $a1, $zero, 0x29
  .Llevel_22_8006F5F4:
    /* 178D390 8006F5F4 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 178D394 8006F5F8 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* 178D398 8006F5FC 04000224 */  addiu      $v0, $zero, 0x4
    /* 178D39C 8006F600 15006214 */  bne        $v1, $v0, .Llevel_22_8006F658
    /* 178D3A0 8006F604 2000B027 */   addiu     $s0, $sp, 0x20
    /* 178D3A4 8006F608 21200002 */  addu       $a0, $s0, $zero
    /* 178D3A8 8006F60C 2800A28F */  lw         $v0, 0x28($sp)
    /* 178D3AC 8006F610 00080524 */  addiu      $a1, $zero, 0x800
    /* 178D3B0 8006F614 00044224 */  addiu      $v0, $v0, 0x400
    /* 178D3B4 8006F618 A1FB000C */  jal        func_8003EE84
    /* 178D3B8 8006F61C 2800A2AF */   sw        $v0, 0x28($sp)
    /* 178D3BC 8006F620 0D004010 */  beqz       $v0, .Llevel_22_8006F658
    /* 178D3C0 8006F624 2800A2AF */   sw        $v0, 0x28($sp)
    /* 178D3C4 8006F628 0780023C */  lui        $v0, %hi(D_8006ABA4)
    /* 178D3C8 8006F62C A4AB428C */  lw         $v0, %lo(D_8006ABA4)($v0)
    /* 178D3CC 8006F630 00000000 */  nop
    /* 178D3D0 8006F634 08004010 */  beqz       $v0, .Llevel_22_8006F658
    /* 178D3D4 8006F638 06000424 */   addiu     $a0, $zero, 0x6
    /* 178D3D8 8006F63C 2E000524 */  addiu      $a1, $zero, 0x2E
  .Llevel_22_8006F640:
    /* 178D3DC 8006F640 21300002 */  addu       $a2, $s0, $zero
    /* 178D3E0 8006F644 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178D3E4 8006F648 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178D3E8 8006F64C 00000000 */  nop
    /* 178D3EC 8006F650 09F84000 */  jalr       $v0
    /* 178D3F0 8006F654 21380000 */   addu      $a3, $zero, $zero
  .Llevel_22_8006F658:
    /* 178D3F4 8006F658 0780103C */  lui        $s0, %hi(D_8006A040)
    /* 178D3F8 8006F65C 40A01026 */  addiu      $s0, $s0, %lo(D_8006A040)
    /* 178D3FC 8006F660 0000038E */  lw         $v1, 0x0($s0)
    /* 178D400 8006F664 2E000224 */  addiu      $v0, $zero, 0x2E
    /* 178D404 8006F668 07006214 */  bne        $v1, $v0, .Llevel_22_8006F688
    /* 178D408 8006F66C 00000000 */   nop
    /* 178D40C 8006F670 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178D410 8006F674 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178D414 8006F678 00000000 */  nop
    /* 178D418 8006F67C 00FC4224 */  addiu      $v0, $v0, -0x400
    /* 178D41C 8006F680 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178D420 8006F684 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006F688:
    /* 178D424 8006F688 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178D428 8006F68C 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178D42C 8006F690 00000000 */  nop
    /* 178D430 8006F694 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 178D434 8006F698 01086228 */  slti       $v0, $v1, 0x801
    /* 178D438 8006F69C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178D43C 8006F6A0 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 178D440 8006F6A4 03004014 */  bnez       $v0, .Llevel_22_8006F6B4
    /* 178D444 8006F6A8 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 178D448 8006F6AC 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178D44C 8006F6B0 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_22_8006F6B4:
    /* 178D450 8006F6B4 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 178D454 8006F6B8 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 178D458 8006F6BC 00000000 */  nop
    /* 178D45C 8006F6C0 03004018 */  blez       $v0, .Llevel_22_8006F6D0
    /* 178D460 8006F6C4 01000224 */   addiu     $v0, $zero, 0x1
    /* 178D464 8006F6C8 0780013C */  lui        $at, %hi(D_8006A058)
    /* 178D468 8006F6CC 58A020AC */  sw         $zero, %lo(D_8006A058)($at)
  .Llevel_22_8006F6D0:
    /* 178D46C 8006F6D0 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178D470 8006F6D4 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 178D474 8006F6D8 686F000C */  jal        func_8001BDA0
    /* 178D478 8006F6DC 04010426 */   addiu     $a0, $s0, 0x104
    /* 178D47C 8006F6E0 50000426 */  addiu      $a0, $s0, 0x50
    /* 178D480 8006F6E4 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 178D484 8006F6E8 3CA120AC */  sw         $zero, %lo(D_8006A13C)($at)
    /* 178D488 8006F6EC 886E000C */  jal        func_8001BA20
    /* 178D48C 8006F6F0 21280000 */   addu      $a1, $zero, $zero
    /* 178D490 8006F6F4 0680033C */  lui        $v1, %hi(D_80067020)
    /* 178D494 8006F6F8 2070638C */  lw         $v1, %lo(D_80067020)($v1)
    /* 178D498 8006F6FC 21280000 */  addu       $a1, $zero, $zero
    /* 178D49C 8006F700 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 178D4A0 8006F704 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 178D4A4 8006F708 01000224 */  addiu      $v0, $zero, 0x1
    /* 178D4A8 8006F70C 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 178D4AC 8006F710 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 178D4B0 8006F714 08006490 */  lbu        $a0, 0x8($v1)
    /* 178D4B4 8006F718 C841010C */  jal        func_80050720
    /* 178D4B8 8006F71C 21300000 */   addu      $a2, $zero, $zero
    /* 178D4BC 8006F720 0C000224 */  addiu      $v0, $zero, 0xC
  .Llevel_22_8006F724:
    /* 178D4C0 8006F724 0780013C */  lui        $at, %hi(D_8006A048)
    /* 178D4C4 8006F728 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 178D4C8 8006F72C 0200023C */  lui        $v0, (0x20000 >> 16)
    /* 178D4CC 8006F730 0780013C */  lui        $at, %hi(D_8006A128)
    /* 178D4D0 8006F734 28A122AC */  sw         $v0, %lo(D_8006A128)($at)
    /* 178D4D4 8006F738 62BE0108 */  j          .Llevel_22_8006F988
    /* 178D4D8 8006F73C 00000000 */   nop
  .Llevel_22_8006F740:
    /* 178D4DC 8006F740 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 178D4E0 8006F744 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* 178D4E4 8006F748 0A000224 */  addiu      $v0, $zero, 0xA
    /* 178D4E8 8006F74C 8E006210 */  beq        $v1, $v0, .Llevel_22_8006F988
    /* 178D4EC 8006F750 21280000 */   addu      $a1, $zero, $zero
    /* 178D4F0 8006F754 0680023C */  lui        $v0, %hi(D_80067020)
    /* 178D4F4 8006F758 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 178D4F8 8006F75C 00000000 */  nop
    /* 178D4FC 8006F760 07004490 */  lbu        $a0, 0x7($v0)
    /* 178D500 8006F764 C841010C */  jal        func_80050720
    /* 178D504 8006F768 21300000 */   addu      $a2, $zero, $zero
    /* 178D508 8006F76C 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 178D50C 8006F770 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 178D510 8006F774 0780113C */  lui        $s1, %hi(D_8006A13C)
    /* 178D514 8006F778 3CA13126 */  addiu      $s1, $s1, %lo(D_8006A13C)
    /* 178D518 8006F77C 23100200 */  negu       $v0, $v0
    /* 178D51C 8006F780 83100200 */  sra        $v0, $v0, 2
    /* 178D520 8006F784 000022AE */  sw         $v0, 0x0($s1)
    /* 178D524 8006F788 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 178D528 8006F78C 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* 178D52C 8006F790 08000224 */  addiu      $v0, $zero, 0x8
    /* 178D530 8006F794 06006210 */  beq        $v1, $v0, .Llevel_22_8006F7B0
    /* 178D534 8006F798 00590224 */   addiu     $v0, $zero, 0x5900
    /* 178D538 8006F79C 0780013C */  lui        $at, %hi(D_8006A140)
    /* 178D53C 8006F7A0 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
    /* 178D540 8006F7A4 0A000224 */  addiu      $v0, $zero, 0xA
    /* 178D544 8006F7A8 0780013C */  lui        $at, %hi(D_8006A048)
    /* 178D548 8006F7AC 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
  .Llevel_22_8006F7B0:
    /* 178D54C 8006F7B0 54FF2426 */  addiu      $a0, $s1, -0xAC
    /* 178D550 8006F7B4 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178D554 8006F7B8 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 178D558 8006F7BC 886E000C */  jal        func_8001BA20
    /* 178D55C 8006F7C0 21280000 */   addu      $a1, $zero, $zero
    /* 178D560 8006F7C4 3000B027 */  addiu      $s0, $sp, 0x30
    /* 178D564 8006F7C8 21200002 */  addu       $a0, $s0, $zero
    /* 178D568 8006F7CC 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 178D56C 8006F7D0 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 178D570 8006F7D4 01000224 */  addiu      $v0, $zero, 0x1
    /* 178D574 8006F7D8 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 178D578 8006F7DC ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 178D57C 8006F7E0 0780013C */  lui        $at, %hi(D_8006A1AD)
    /* 178D580 8006F7E4 ADA122A0 */  sb         $v0, %lo(D_8006A1AD)($at)
    /* 178D584 8006F7E8 6C6F000C */  jal        func_8001BDB0
    /* 178D588 8006F7EC B4FE2526 */   addiu     $a1, $s1, -0x14C
    /* 178D58C 8006F7F0 21200002 */  addu       $a0, $s0, $zero
    /* 178D590 8006F7F4 3800A28F */  lw         $v0, 0x38($sp)
    /* 178D594 8006F7F8 00080524 */  addiu      $a1, $zero, 0x800
    /* 178D598 8006F7FC 00044224 */  addiu      $v0, $v0, 0x400
    /* 178D59C 8006F800 A1FB000C */  jal        func_8003EE84
    /* 178D5A0 8006F804 3800A2AF */   sw        $v0, 0x38($sp)
    /* 178D5A4 8006F808 5F004010 */  beqz       $v0, .Llevel_22_8006F988
    /* 178D5A8 8006F80C 3800A2AF */   sw        $v0, 0x38($sp)
    /* 178D5AC 8006F810 0780023C */  lui        $v0, %hi(D_8006ABA4)
    /* 178D5B0 8006F814 A4AB428C */  lw         $v0, %lo(D_8006ABA4)($v0)
    /* 178D5B4 8006F818 00000000 */  nop
    /* 178D5B8 8006F81C 5A004010 */  beqz       $v0, .Llevel_22_8006F988
    /* 178D5BC 8006F820 00000000 */   nop
    /* 178D5C0 8006F824 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178D5C4 8006F828 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178D5C8 8006F82C 00000000 */  nop
    /* 178D5CC 8006F830 55004010 */  beqz       $v0, .Llevel_22_8006F988
    /* 178D5D0 8006F834 0A000424 */   addiu     $a0, $zero, 0xA
    /* 178D5D4 8006F838 29000524 */  addiu      $a1, $zero, 0x29
    /* 178D5D8 8006F83C 21300002 */  addu       $a2, $s0, $zero
    /* 178D5DC 8006F840 09F84000 */  jalr       $v0
    /* 178D5E0 8006F844 21380000 */   addu      $a3, $zero, $zero
    /* 178D5E4 8006F848 06000424 */  addiu      $a0, $zero, 0x6
    /* 178D5E8 8006F84C 2E000524 */  addiu      $a1, $zero, 0x2E
    /* 178D5EC 8006F850 21300002 */  addu       $a2, $s0, $zero
    /* 178D5F0 8006F854 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 178D5F4 8006F858 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 178D5F8 8006F85C 00000000 */  nop
    /* 178D5FC 8006F860 09F84000 */  jalr       $v0
    /* 178D600 8006F864 21380000 */   addu      $a3, $zero, $zero
    /* 178D604 8006F868 62BE0108 */  j          .Llevel_22_8006F988
    /* 178D608 8006F86C 00000000 */   nop
  .Llevel_22_8006F870:
    /* 178D60C 8006F870 0780013C */  lui        $at, %hi(D_8006A048)
    /* 178D610 8006F874 48A020AC */  sw         $zero, %lo(D_8006A048)($at)
    /* 178D614 8006F878 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178D618 8006F87C 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 178D61C 8006F880 AFB8000C */  jal        func_8002E2BC
    /* 178D620 8006F884 00000000 */   nop
    /* 178D624 8006F888 01000224 */  addiu      $v0, $zero, 0x1
    /* 178D628 8006F88C 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 178D62C 8006F890 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 178D630 8006F894 62BE0108 */  j          .Llevel_22_8006F988
    /* 178D634 8006F898 00000000 */   nop
  .Llevel_22_8006F89C:
    /* 178D638 8006F89C 0780023C */  lui        $v0, %hi(D_8006A048)
    /* 178D63C 8006F8A0 48A0428C */  lw         $v0, %lo(D_8006A048)($v0)
    /* 178D640 8006F8A4 07000324 */  addiu      $v1, $zero, 0x7
    /* 178D644 8006F8A8 0780013C */  lui        $at, %hi(D_8006A048)
    /* 178D648 8006F8AC 48A023AC */  sw         $v1, %lo(D_8006A048)($at)
    /* 178D64C 8006F8B0 0780033C */  lui        $v1, %hi(D_8006A264)
    /* 178D650 8006F8B4 64A2638C */  lw         $v1, %lo(D_8006A264)($v1)
    /* 178D654 8006F8B8 0780053C */  lui        $a1, %hi(D_8006A13C)
    /* 178D658 8006F8BC 3CA1A524 */  addiu      $a1, $a1, %lo(D_8006A13C)
    /* 178D65C 8006F8C0 0780013C */  lui        $at, %hi(D_8006A044)
    /* 178D660 8006F8C4 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 178D664 8006F8C8 09006104 */  bgez       $v1, .Llevel_22_8006F8F0
    /* 178D668 8006F8CC 0000A2AC */   sw        $v0, 0x0($a1)
    /* 178D66C 8006F8D0 0780023C */  lui        $v0, %hi(D_8006A05C)
    /* 178D670 8006F8D4 5CA0428C */  lw         $v0, %lo(D_8006A05C)($v0)
    /* 178D674 8006F8D8 00000000 */  nop
    /* 178D678 8006F8DC 00084224 */  addiu      $v0, $v0, 0x800
    /* 178D67C 8006F8E0 03110200 */  sra        $v0, $v0, 4
    /* 178D680 8006F8E4 FF004230 */  andi       $v0, $v0, 0xFF
    /* 178D684 8006F8E8 0780013C */  lui        $at, %hi(D_8006A264)
    /* 178D688 8006F8EC 64A222AC */  sw         $v0, %lo(D_8006A264)($at)
  .Llevel_22_8006F8F0:
    /* 178D68C 8006F8F0 0780023C */  lui        $v0, %hi(D_8006A264)
    /* 178D690 8006F8F4 64A2428C */  lw         $v0, %lo(D_8006A264)($v0)
    /* 178D694 8006F8F8 00000000 */  nop
    /* 178D698 8006F8FC 40100200 */  sll        $v0, $v0, 1
    /* 178D69C 8006F900 0680013C */  lui        $at, %hi(D_80061C58)
    /* 178D6A0 8006F904 21082200 */  addu       $at, $at, $v0
    /* 178D6A4 8006F908 581C2384 */  lh         $v1, %lo(D_80061C58)($at)
    /* 178D6A8 8006F90C 3CFFA424 */  addiu      $a0, $a1, -0xC4
    /* 178D6AC 8006F910 48FFA3AC */  sw         $v1, -0xB8($a1)
    /* 178D6B0 8006F914 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 178D6B4 8006F918 21082200 */  addu       $at, $at, $v0
    /* 178D6B8 8006F91C D81B2284 */  lh         $v0, %lo(D_80061BD8)($at)
    /* 178D6BC 8006F920 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 178D6C0 8006F924 8CA020AC */  sw         $zero, %lo(D_8006A08C)($at)
    /* 178D6C4 8006F928 0780013C */  lui        $at, %hi(D_8006A088)
    /* 178D6C8 8006F92C 88A022AC */  sw         $v0, %lo(D_8006A088)($at)
    /* 178D6CC 8006F930 6C6F000C */  jal        func_8001BDB0
    /* 178D6D0 8006F934 48FFA524 */   addiu     $a1, $a1, -0xB8
    /* 178D6D4 8006F938 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 178D6D8 8006F93C FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 178D6DC 8006F940 01000224 */  addiu      $v0, $zero, 0x1
    /* 178D6E0 8006F944 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 178D6E4 8006F948 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 178D6E8 8006F94C 0F000224 */  addiu      $v0, $zero, 0xF
    /* 178D6EC 8006F950 0780013C */  lui        $at, %hi(D_8006838C)
    /* 178D6F0 8006F954 8C8322AC */  sw         $v0, %lo(D_8006838C)($at)
    /* 178D6F4 8006F958 05006010 */  beqz       $v1, .Llevel_22_8006F970
    /* 178D6F8 8006F95C 05000424 */   addiu     $a0, $zero, 0x5
    /* 178D6FC 8006F960 0A000524 */  addiu      $a1, $zero, 0xA
    /* 178D700 8006F964 21300000 */  addu       $a2, $zero, $zero
    /* 178D704 8006F968 09F86000 */  jalr       $v1
    /* 178D708 8006F96C 21380000 */   addu      $a3, $zero, $zero
  .Llevel_22_8006F970:
    /* 178D70C 8006F970 0680023C */  lui        $v0, %hi(D_80067020)
    /* 178D710 8006F974 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 178D714 8006F978 21280000 */  addu       $a1, $zero, $zero
    /* 178D718 8006F97C 18004490 */  lbu        $a0, 0x18($v0)
    /* 178D71C 8006F980 C841010C */  jal        func_80050720
    /* 178D720 8006F984 21300000 */   addu      $a2, $zero, $zero
  .Llevel_22_8006F988:
    /* 178D724 8006F988 4800BF8F */  lw         $ra, 0x48($sp)
    /* 178D728 8006F98C 4400B18F */  lw         $s1, 0x44($sp)
    /* 178D72C 8006F990 4000B08F */  lw         $s0, 0x40($sp)
    /* 178D730 8006F994 5000BD27 */  addiu      $sp, $sp, 0x50
    /* 178D734 8006F998 0800E003 */  jr         $ra
    /* 178D738 8006F99C 00000000 */   nop
endlabel func_level_22_8006F0D0
