.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_25_8006D478

dlabel jtbl_level_25_8006D478
    /* 1BC5A14 8006D478 90EB0680 */ .word .Llevel_25_8006EB90
    /* 1BC5A18 8006D47C 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A1C 8006D480 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A20 8006D484 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A24 8006D488 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A28 8006D48C 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A2C 8006D490 20EC0680 */ .word .Llevel_25_8006EC20
    /* 1BC5A30 8006D494 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A34 8006D498 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A38 8006D49C 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A3C 8006D4A0 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A40 8006D4A4 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A44 8006D4A8 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A48 8006D4AC 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A4C 8006D4B0 70EC0680 */ .word .Llevel_25_8006EC70
    /* 1BC5A50 8006D4B4 70EC0680 */ .word .Llevel_25_8006EC70
    /* 1BC5A54 8006D4B8 70EC0680 */ .word .Llevel_25_8006EC70
    /* 1BC5A58 8006D4BC 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A5C 8006D4C0 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A60 8006D4C4 90EB0680 */ .word .Llevel_25_8006EB90
    /* 1BC5A64 8006D4C8 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A68 8006D4CC 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A6C 8006D4D0 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A70 8006D4D4 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A74 8006D4D8 0CED0680 */ .word .Llevel_25_8006ED0C
    /* 1BC5A78 8006D4DC 0CED0680 */ .word .Llevel_25_8006ED0C
    /* 1BC5A7C 8006D4E0 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A80 8006D4E4 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A84 8006D4E8 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A88 8006D4EC 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A8C 8006D4F0 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A90 8006D4F4 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A94 8006D4F8 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A98 8006D4FC 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5A9C 8006D500 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5AA0 8006D504 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5AA4 8006D508 38EE0680 */ .word .Llevel_25_8006EE38
    /* 1BC5AA8 8006D50C 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5AAC 8006D510 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5AB0 8006D514 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5AB4 8006D518 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5AB8 8006D51C 50EF0680 */ .word .Llevel_25_8006EF50
    /* 1BC5ABC 8006D520 A0EE0680 */ .word .Llevel_25_8006EEA0
    /* 1BC5AC0 8006D524 00000000 */ .word 0x00000000
enddlabel jtbl_level_25_8006D478


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_25_8006EB58, 0x40C

glabel func_level_25_8006EB58
    /* 1BC70F4 8006EB58 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 1BC70F8 8006EB5C 2000B0AF */  sw         $s0, 0x20($sp)
    /* 1BC70FC 8006EB60 21808000 */  addu       $s0, $a0, $zero
    /* 1BC7100 8006EB64 EDFF0326 */  addiu      $v1, $s0, -0x13
    /* 1BC7104 8006EB68 2B00622C */  sltiu      $v0, $v1, 0x2B
    /* 1BC7108 8006EB6C F8004010 */  beqz       $v0, .Llevel_25_8006EF50
    /* 1BC710C 8006EB70 2400BFAF */   sw        $ra, 0x24($sp)
    /* 1BC7110 8006EB74 80100300 */  sll        $v0, $v1, 2
    /* 1BC7114 8006EB78 0780013C */  lui        $at, %hi(jtbl_level_25_8006D478)
    /* 1BC7118 8006EB7C 21082200 */  addu       $at, $at, $v0
    /* 1BC711C 8006EB80 78D4228C */  lw         $v0, %lo(jtbl_level_25_8006D478)($at)
    /* 1BC7120 8006EB84 00000000 */  nop
    /* 1BC7124 8006EB88 08004000 */  jr         $v0
    /* 1BC7128 8006EB8C 00000000 */   nop
  .Llevel_25_8006EB90:
    /* 1BC712C 8006EB90 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1BC7130 8006EB94 48A020AC */  sw         $zero, %lo(D_8006A048)($at)
    /* 1BC7134 8006EB98 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1BC7138 8006EB9C 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1BC713C 8006EBA0 AFB8000C */  jal        func_8002E2BC
    /* 1BC7140 8006EBA4 00000000 */   nop
    /* 1BC7144 8006EBA8 01000224 */  addiu      $v0, $zero, 0x1
    /* 1BC7148 8006EBAC 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1BC714C 8006EBB0 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 1BC7150 8006EBB4 25000224 */  addiu      $v0, $zero, 0x25
    /* 1BC7154 8006EBB8 04000216 */  bne        $s0, $v0, .Llevel_25_8006EBCC
    /* 1BC7158 8006EBBC 01000424 */   addiu     $a0, $zero, 0x1
    /* 1BC715C 8006EBC0 05000424 */  addiu      $a0, $zero, 0x5
    /* 1BC7160 8006EBC4 F4BA0108 */  j          .Llevel_25_8006EBD0
    /* 1BC7164 8006EBC8 08000524 */   addiu     $a1, $zero, 0x8
  .Llevel_25_8006EBCC:
    /* 1BC7168 8006EBCC 03000524 */  addiu      $a1, $zero, 0x3
  .Llevel_25_8006EBD0:
    /* 1BC716C 8006EBD0 47E2000C */  jal        func_8003891C
    /* 1BC7170 8006EBD4 00000000 */   nop
    /* 1BC7174 8006EBD8 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 1BC7178 8006EBDC 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* 1BC717C 8006EBE0 0680033C */  lui        $v1, %hi(D_800670B4)
    /* 1BC7180 8006EBE4 B470638C */  lw         $v1, %lo(D_800670B4)($v1)
    /* 1BC7184 8006EBE8 0780013C */  lui        $at, %hi(D_8006A140)
    /* 1BC7188 8006EBEC 40A120AC */  sw         $zero, %lo(D_8006A140)($at)
    /* 1BC718C 8006EBF0 D7006010 */  beqz       $v1, .Llevel_25_8006EF50
    /* 1BC7190 8006EBF4 25000224 */   addiu     $v0, $zero, 0x25
    /* 1BC7194 8006EBF8 03000216 */  bne        $s0, $v0, .Llevel_25_8006EC08
    /* 1BC7198 8006EBFC 27000224 */   addiu     $v0, $zero, 0x27
    /* 1BC719C 8006EC00 04BB0108 */  j          .Llevel_25_8006EC10
    /* 1BC71A0 8006EC04 F1010424 */   addiu     $a0, $zero, 0x1F1
  .Llevel_25_8006EC08:
    /* 1BC71A4 8006EC08 D1000216 */  bne        $s0, $v0, .Llevel_25_8006EF50
    /* 1BC71A8 8006EC0C DB010424 */   addiu     $a0, $zero, 0x1DB
  .Llevel_25_8006EC10:
    /* 1BC71AC 8006EC10 09F86000 */  jalr       $v1
    /* 1BC71B0 8006EC14 21280000 */   addu      $a1, $zero, $zero
    /* 1BC71B4 8006EC18 D4BB0108 */  j          .Llevel_25_8006EF50
    /* 1BC71B8 8006EC1C 00000000 */   nop
  .Llevel_25_8006EC20:
    /* 1BC71BC 8006EC20 0680033C */  lui        $v1, %hi(D_80067020)
    /* 1BC71C0 8006EC24 2070638C */  lw         $v1, %lo(D_80067020)($v1)
    /* 1BC71C4 8006EC28 09000224 */  addiu      $v0, $zero, 0x9
    /* 1BC71C8 8006EC2C 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1BC71CC 8006EC30 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 1BC71D0 8006EC34 0600023C */  lui        $v0, (0x60000 >> 16)
    /* 1BC71D4 8006EC38 0780013C */  lui        $at, %hi(D_8006A128)
    /* 1BC71D8 8006EC3C 28A122AC */  sw         $v0, %lo(D_8006A128)($at)
    /* 1BC71DC 8006EC40 01000224 */  addiu      $v0, $zero, 0x1
    /* 1BC71E0 8006EC44 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1BC71E4 8006EC48 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1BC71E8 8006EC4C 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 1BC71EC 8006EC50 3CA120AC */  sw         $zero, %lo(D_8006A13C)($at)
    /* 1BC71F0 8006EC54 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1BC71F4 8006EC58 ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 1BC71F8 8006EC5C 0780013C */  lui        $at, %hi(D_8006A1AD)
    /* 1BC71FC 8006EC60 ADA122A0 */  sb         $v0, %lo(D_8006A1AD)($at)
    /* 1BC7200 8006EC64 22006490 */  lbu        $a0, 0x22($v1)
    /* 1BC7204 8006EC68 A4BB0108 */  j          .Llevel_25_8006EE90
    /* 1BC7208 8006EC6C 21280000 */   addu      $a1, $zero, $zero
  .Llevel_25_8006EC70:
    /* 1BC720C 8006EC70 0780103C */  lui        $s0, %hi(D_8006A048)
    /* 1BC7210 8006EC74 48A01026 */  addiu      $s0, $s0, %lo(D_8006A048)
    /* 1BC7214 8006EC78 0000028E */  lw         $v0, 0x0($s0)
    /* 1BC7218 8006EC7C 06000324 */  addiu      $v1, $zero, 0x6
    /* 1BC721C 8006EC80 B3004310 */  beq        $v0, $v1, .Llevel_25_8006EF50
    /* 1BC7220 8006EC84 00000000 */   nop
    /* 1BC7224 8006EC88 000003AE */  sw         $v1, 0x0($s0)
    /* 1BC7228 8006EC8C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1BC722C 8006EC90 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1BC7230 8006EC94 686F000C */  jal        func_8001BDA0
    /* 1BC7234 8006EC98 FC000426 */   addiu     $a0, $s0, 0xFC
    /* 1BC7238 8006EC9C 48000426 */  addiu      $a0, $s0, 0x48
    /* 1BC723C 8006ECA0 0780013C */  lui        $at, %hi(D_8006A150)
    /* 1BC7240 8006ECA4 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 1BC7244 8006ECA8 886E000C */  jal        func_8001BA20
    /* 1BC7248 8006ECAC 21280000 */   addu      $a1, $zero, $zero
    /* 1BC724C 8006ECB0 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1BC7250 8006ECB4 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 1BC7254 8006ECB8 00084228 */  slti       $v0, $v0, 0x800
    /* 1BC7258 8006ECBC 03004010 */  beqz       $v0, .Llevel_25_8006ECCC
    /* 1BC725C 8006ECC0 00080224 */   addiu     $v0, $zero, 0x800
    /* 1BC7260 8006ECC4 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1BC7264 8006ECC8 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_25_8006ECCC:
    /* 1BC7268 8006ECCC 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 1BC726C 8006ECD0 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 1BC7270 8006ECD4 00000000 */  nop
    /* 1BC7274 8006ECD8 014B4228 */  slti       $v0, $v0, 0x4B01
    /* 1BC7278 8006ECDC 03004014 */  bnez       $v0, .Llevel_25_8006ECEC
    /* 1BC727C 8006ECE0 004B0224 */   addiu     $v0, $zero, 0x4B00
    /* 1BC7280 8006ECE4 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1BC7284 8006ECE8 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_25_8006ECEC:
    /* 1BC7288 8006ECEC 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 1BC728C 8006ECF0 3CA120AC */  sw         $zero, %lo(D_8006A13C)($at)
    /* 1BC7290 8006ECF4 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1BC7294 8006ECF8 ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 1BC7298 8006ECFC 0780013C */  lui        $at, %hi(D_8006A1AD)
    /* 1BC729C 8006ED00 ADA120A0 */  sb         $zero, %lo(D_8006A1AD)($at)
    /* 1BC72A0 8006ED04 D4BB0108 */  j          .Llevel_25_8006EF50
    /* 1BC72A4 8006ED08 00000000 */   nop
  .Llevel_25_8006ED0C:
    /* 1BC72A8 8006ED0C 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 1BC72AC 8006ED10 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* 1BC72B0 8006ED14 0A000224 */  addiu      $v0, $zero, 0xA
    /* 1BC72B4 8006ED18 8D006210 */  beq        $v1, $v0, .Llevel_25_8006EF50
    /* 1BC72B8 8006ED1C 21280000 */   addu      $a1, $zero, $zero
    /* 1BC72BC 8006ED20 0680023C */  lui        $v0, %hi(D_80067020)
    /* 1BC72C0 8006ED24 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 1BC72C4 8006ED28 00000000 */  nop
    /* 1BC72C8 8006ED2C 07004490 */  lbu        $a0, 0x7($v0)
    /* 1BC72CC 8006ED30 C841010C */  jal        func_80050720
    /* 1BC72D0 8006ED34 21300000 */   addu      $a2, $zero, $zero
    /* 1BC72D4 8006ED38 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 1BC72D8 8006ED3C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 1BC72DC 8006ED40 0780103C */  lui        $s0, %hi(D_8006A13C)
    /* 1BC72E0 8006ED44 3CA11026 */  addiu      $s0, $s0, %lo(D_8006A13C)
    /* 1BC72E4 8006ED48 23100200 */  negu       $v0, $v0
    /* 1BC72E8 8006ED4C 83100200 */  sra        $v0, $v0, 2
    /* 1BC72EC 8006ED50 000002AE */  sw         $v0, 0x0($s0)
    /* 1BC72F0 8006ED54 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 1BC72F4 8006ED58 48A0638C */  lw         $v1, %lo(D_8006A048)($v1)
    /* 1BC72F8 8006ED5C 08000224 */  addiu      $v0, $zero, 0x8
    /* 1BC72FC 8006ED60 06006210 */  beq        $v1, $v0, .Llevel_25_8006ED7C
    /* 1BC7300 8006ED64 00590224 */   addiu     $v0, $zero, 0x5900
    /* 1BC7304 8006ED68 0780013C */  lui        $at, %hi(D_8006A140)
    /* 1BC7308 8006ED6C 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
    /* 1BC730C 8006ED70 0A000224 */  addiu      $v0, $zero, 0xA
    /* 1BC7310 8006ED74 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1BC7314 8006ED78 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
  .Llevel_25_8006ED7C:
    /* 1BC7318 8006ED7C 54FF0426 */  addiu      $a0, $s0, -0xAC
    /* 1BC731C 8006ED80 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1BC7320 8006ED84 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1BC7324 8006ED88 886E000C */  jal        func_8001BA20
    /* 1BC7328 8006ED8C 21280000 */   addu      $a1, $zero, $zero
    /* 1BC732C 8006ED90 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1BC7330 8006ED94 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1BC7334 8006ED98 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 1BC7338 8006ED9C 01000224 */  addiu      $v0, $zero, 0x1
    /* 1BC733C 8006EDA0 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1BC7340 8006EDA4 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 1BC7344 8006EDA8 0780013C */  lui        $at, %hi(D_8006A1AD)
    /* 1BC7348 8006EDAC ADA122A0 */  sb         $v0, %lo(D_8006A1AD)($at)
    /* 1BC734C 8006EDB0 6C6F000C */  jal        func_8001BDB0
    /* 1BC7350 8006EDB4 B4FE0526 */   addiu     $a1, $s0, -0x14C
    /* 1BC7354 8006EDB8 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1BC7358 8006EDBC 1800A28F */  lw         $v0, 0x18($sp)
    /* 1BC735C 8006EDC0 00080524 */  addiu      $a1, $zero, 0x800
    /* 1BC7360 8006EDC4 00044224 */  addiu      $v0, $v0, 0x400
    /* 1BC7364 8006EDC8 A1FB000C */  jal        func_8003EE84
    /* 1BC7368 8006EDCC 1800A2AF */   sw        $v0, 0x18($sp)
    /* 1BC736C 8006EDD0 5F004010 */  beqz       $v0, .Llevel_25_8006EF50
    /* 1BC7370 8006EDD4 1800A2AF */   sw        $v0, 0x18($sp)
    /* 1BC7374 8006EDD8 0780023C */  lui        $v0, %hi(D_8006ABA4)
    /* 1BC7378 8006EDDC A4AB428C */  lw         $v0, %lo(D_8006ABA4)($v0)
    /* 1BC737C 8006EDE0 00000000 */  nop
    /* 1BC7380 8006EDE4 5A004010 */  beqz       $v0, .Llevel_25_8006EF50
    /* 1BC7384 8006EDE8 00000000 */   nop
    /* 1BC7388 8006EDEC 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 1BC738C 8006EDF0 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 1BC7390 8006EDF4 00000000 */  nop
    /* 1BC7394 8006EDF8 55004010 */  beqz       $v0, .Llevel_25_8006EF50
    /* 1BC7398 8006EDFC 0A000424 */   addiu     $a0, $zero, 0xA
    /* 1BC739C 8006EE00 29000524 */  addiu      $a1, $zero, 0x29
    /* 1BC73A0 8006EE04 1000A627 */  addiu      $a2, $sp, 0x10
    /* 1BC73A4 8006EE08 09F84000 */  jalr       $v0
    /* 1BC73A8 8006EE0C 21380000 */   addu      $a3, $zero, $zero
    /* 1BC73AC 8006EE10 06000424 */  addiu      $a0, $zero, 0x6
    /* 1BC73B0 8006EE14 2E000524 */  addiu      $a1, $zero, 0x2E
    /* 1BC73B4 8006EE18 1000A627 */  addiu      $a2, $sp, 0x10
    /* 1BC73B8 8006EE1C 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 1BC73BC 8006EE20 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 1BC73C0 8006EE24 00000000 */  nop
    /* 1BC73C4 8006EE28 09F84000 */  jalr       $v0
    /* 1BC73C8 8006EE2C 21380000 */   addu      $a3, $zero, $zero
    /* 1BC73CC 8006EE30 D4BB0108 */  j          .Llevel_25_8006EF50
    /* 1BC73D0 8006EE34 00000000 */   nop
  .Llevel_25_8006EE38:
    /* 1BC73D4 8006EE38 08000224 */  addiu      $v0, $zero, 0x8
    /* 1BC73D8 8006EE3C 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1BC73DC 8006EE40 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 1BC73E0 8006EE44 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 1BC73E4 8006EE48 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 1BC73E8 8006EE4C 01000324 */  addiu      $v1, $zero, 0x1
    /* 1BC73EC 8006EE50 0780013C */  lui        $at, %hi(D_8006A1AD)
    /* 1BC73F0 8006EE54 ADA123A0 */  sb         $v1, %lo(D_8006A1AD)($at)
    /* 1BC73F4 8006EE58 0680033C */  lui        $v1, %hi(D_80067020)
    /* 1BC73F8 8006EE5C 2070638C */  lw         $v1, %lo(D_80067020)($v1)
    /* 1BC73FC 8006EE60 21280000 */  addu       $a1, $zero, $zero
    /* 1BC7400 8006EE64 0780013C */  lui        $at, %hi(D_8006A140)
    /* 1BC7404 8006EE68 40A120AC */  sw         $zero, %lo(D_8006A140)($at)
    /* 1BC7408 8006EE6C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1BC740C 8006EE70 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1BC7410 8006EE74 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1BC7414 8006EE78 ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 1BC7418 8006EE7C 23100200 */  negu       $v0, $v0
    /* 1BC741C 8006EE80 83100200 */  sra        $v0, $v0, 2
    /* 1BC7420 8006EE84 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 1BC7424 8006EE88 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* 1BC7428 8006EE8C 07006490 */  lbu        $a0, 0x7($v1)
  .Llevel_25_8006EE90:
    /* 1BC742C 8006EE90 C841010C */  jal        func_80050720
    /* 1BC7430 8006EE94 21300000 */   addu      $a2, $zero, $zero
    /* 1BC7434 8006EE98 D4BB0108 */  j          .Llevel_25_8006EF50
    /* 1BC7438 8006EE9C 00000000 */   nop
  .Llevel_25_8006EEA0:
    /* 1BC743C 8006EEA0 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 1BC7440 8006EEA4 48A06324 */  addiu      $v1, $v1, %lo(D_8006A048)
    /* 1BC7444 8006EEA8 48006424 */  addiu      $a0, $v1, 0x48
    /* 1BC7448 8006EEAC 09000224 */  addiu      $v0, $zero, 0x9
    /* 1BC744C 8006EEB0 000062AC */  sw         $v0, 0x0($v1)
    /* 1BC7450 8006EEB4 0600023C */  lui        $v0, (0x60000 >> 16)
    /* 1BC7454 8006EEB8 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1BC7458 8006EEBC 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1BC745C 8006EEC0 0780013C */  lui        $at, %hi(D_8006A128)
    /* 1BC7460 8006EEC4 28A122AC */  sw         $v0, %lo(D_8006A128)($at)
    /* 1BC7464 8006EEC8 886E000C */  jal        func_8001BA20
    /* 1BC7468 8006EECC 21280000 */   addu      $a1, $zero, $zero
    /* 1BC746C 8006EED0 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1BC7470 8006EED4 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 1BC7474 8006EED8 801E0224 */  addiu      $v0, $zero, 0x1E80
    /* 1BC7478 8006EEDC 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 1BC747C 8006EEE0 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 1BC7480 8006EEE4 C2B6000C */  jal        func_8002DB08
    /* 1BC7484 8006EEE8 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 1BC7488 8006EEEC 0780033C */  lui        $v1, %hi(D_8006A15C)
    /* 1BC748C 8006EEF0 5CA1638C */  lw         $v1, %lo(D_8006A15C)($v1)
    /* 1BC7490 8006EEF4 01000224 */  addiu      $v0, $zero, 0x1
    /* 1BC7494 8006EEF8 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1BC7498 8006EEFC ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 1BC749C 8006EF00 0B006014 */  bnez       $v1, .Llevel_25_8006EF30
    /* 1BC74A0 8006EF04 06000224 */   addiu     $v0, $zero, 0x6
    /* 1BC74A4 8006EF08 0780023C */  lui        $v0, %hi(D_8006A1EC)
    /* 1BC74A8 8006EF0C ECA1428C */  lw         $v0, %lo(D_8006A1EC)($v0)
    /* 1BC74AC 8006EF10 00000000 */  nop
    /* 1BC74B0 8006EF14 06004014 */  bnez       $v0, .Llevel_25_8006EF30
    /* 1BC74B4 8006EF18 06000224 */   addiu     $v0, $zero, 0x6
    /* 1BC74B8 8006EF1C 0780033C */  lui        $v1, %hi(D_8006A1F0)
    /* 1BC74BC 8006EF20 F0A1638C */  lw         $v1, %lo(D_8006A1F0)($v1)
    /* 1BC74C0 8006EF24 00000000 */  nop
    /* 1BC74C4 8006EF28 09006210 */  beq        $v1, $v0, .Llevel_25_8006EF50
    /* 1BC74C8 8006EF2C 00000000 */   nop
  .Llevel_25_8006EF30:
    /* 1BC74CC 8006EF30 0780013C */  lui        $at, %hi(D_8006A15C)
    /* 1BC74D0 8006EF34 5CA120AC */  sw         $zero, %lo(D_8006A15C)($at)
    /* 1BC74D4 8006EF38 0780013C */  lui        $at, %hi(D_8006A1EC)
    /* 1BC74D8 8006EF3C ECA120AC */  sw         $zero, %lo(D_8006A1EC)($at)
    /* 1BC74DC 8006EF40 0780013C */  lui        $at, %hi(D_8006A1F0)
    /* 1BC74E0 8006EF44 F0A122AC */  sw         $v0, %lo(D_8006A1F0)($at)
    /* 1BC74E4 8006EF48 85C2000C */  jal        func_80030A14
    /* 1BC74E8 8006EF4C 00000000 */   nop
  .Llevel_25_8006EF50:
    /* 1BC74EC 8006EF50 2400BF8F */  lw         $ra, 0x24($sp)
    /* 1BC74F0 8006EF54 2000B08F */  lw         $s0, 0x20($sp)
    /* 1BC74F4 8006EF58 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 1BC74F8 8006EF5C 0800E003 */  jr         $ra
    /* 1BC74FC 8006EF60 00000000 */   nop
endlabel func_level_25_8006EB58
