.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_11_8006D398

dlabel jtbl_level_11_8006D398
    /* F28934 8006D398 E8ED0680 */ .word .Llevel_11_8006EDE8
    /* F28938 8006D39C D0ED0680 */ .word .Llevel_11_8006EDD0
    /* F2893C 8006D3A0 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28940 8006D3A4 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28944 8006D3A8 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28948 8006D3AC 08EE0680 */ .word .Llevel_11_8006EE08
    /* F2894C 8006D3B0 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28950 8006D3B4 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28954 8006D3B8 D0ED0680 */ .word .Llevel_11_8006EDD0
    /* F28958 8006D3BC 08EE0680 */ .word .Llevel_11_8006EE08
    /* F2895C 8006D3C0 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28960 8006D3C4 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28964 8006D3C8 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28968 8006D3CC 08EE0680 */ .word .Llevel_11_8006EE08
    /* F2896C 8006D3D0 D0ED0680 */ .word .Llevel_11_8006EDD0
    /* F28970 8006D3D4 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28974 8006D3D8 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28978 8006D3DC 08EE0680 */ .word .Llevel_11_8006EE08
    /* F2897C 8006D3E0 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28980 8006D3E4 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28984 8006D3E8 D0ED0680 */ .word .Llevel_11_8006EDD0
    /* F28988 8006D3EC 08EE0680 */ .word .Llevel_11_8006EE08
    /* F2898C 8006D3F0 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28990 8006D3F4 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28994 8006D3F8 08EE0680 */ .word .Llevel_11_8006EE08
    /* F28998 8006D3FC 08EE0680 */ .word .Llevel_11_8006EE08
    /* F2899C 8006D400 08EE0680 */ .word .Llevel_11_8006EE08
    /* F289A0 8006D404 08EE0680 */ .word .Llevel_11_8006EE08
    /* F289A4 8006D408 08EE0680 */ .word .Llevel_11_8006EE08
    /* F289A8 8006D40C F8ED0680 */ .word .Llevel_11_8006EDF8
    /* F289AC 8006D410 08EE0680 */ .word .Llevel_11_8006EE08
    /* F289B0 8006D414 08EE0680 */ .word .Llevel_11_8006EE08
    /* F289B4 8006D418 F8ED0680 */ .word .Llevel_11_8006EDF8
    /* F289B8 8006D41C F8ED0680 */ .word .Llevel_11_8006EDF8
    /* F289BC 8006D420 F8ED0680 */ .word .Llevel_11_8006EDF8
    /* F289C0 8006D424 D0ED0680 */ .word .Llevel_11_8006EDD0
    /* F289C4 8006D428 D0ED0680 */ .word .Llevel_11_8006EDD0
    /* F289C8 8006D42C 00000000 */ .word 0x00000000
enddlabel jtbl_level_11_8006D398


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_11_8006ED80, 0x98

glabel func_level_11_8006ED80
    /* F2A31C 8006ED80 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* F2A320 8006ED84 00210400 */  sll        $a0, $a0, 4
    /* F2A324 8006ED88 0780023C */  lui        $v0, %hi(D_800683B0)
    /* F2A328 8006ED8C B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* F2A32C 8006ED90 0780033C */  lui        $v1, %hi(D_8006A040)
    /* F2A330 8006ED94 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* F2A334 8006ED98 21208200 */  addu       $a0, $a0, $v0
    /* F2A338 8006ED9C 1000BFAF */  sw         $ra, 0x10($sp)
    /* F2A33C 8006EDA0 0680013C */  lui        $at, %hi(D_80066F38)
    /* F2A340 8006EDA4 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* F2A344 8006EDA8 EEFF6324 */  addiu      $v1, $v1, -0x12
    /* F2A348 8006EDAC 2500622C */  sltiu      $v0, $v1, 0x25
    /* F2A34C 8006EDB0 15004010 */  beqz       $v0, .Llevel_11_8006EE08
    /* F2A350 8006EDB4 80100300 */   sll       $v0, $v1, 2
    /* F2A354 8006EDB8 0780013C */  lui        $at, %hi(jtbl_level_11_8006D398)
    /* F2A358 8006EDBC 21082200 */  addu       $at, $at, $v0
    /* F2A35C 8006EDC0 98D3228C */  lw         $v0, %lo(jtbl_level_11_8006D398)($at)
    /* F2A360 8006EDC4 00000000 */  nop
    /* F2A364 8006EDC8 08004000 */  jr         $v0
    /* F2A368 8006EDCC 00000000 */   nop
  .Llevel_11_8006EDD0:
    /* F2A36C 8006EDD0 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* F2A370 8006EDD4 C4A08424 */  addiu      $a0, $a0, %lo(D_8006A0C4)
    /* F2A374 8006EDD8 E3B6000C */  jal        func_8002DB8C
    /* F2A378 8006EDDC 00000000 */   nop
    /* F2A37C 8006EDE0 82BB0108 */  j          .Llevel_11_8006EE08
    /* F2A380 8006EDE4 00000000 */   nop
  .Llevel_11_8006EDE8:
    /* F2A384 8006EDE8 E3B6000C */  jal        func_8002DB8C
    /* F2A388 8006EDEC 21200000 */   addu      $a0, $zero, $zero
    /* F2A38C 8006EDF0 82BB0108 */  j          .Llevel_11_8006EE08
    /* F2A390 8006EDF4 00000000 */   nop
  .Llevel_11_8006EDF8:
    /* F2A394 8006EDF8 0780043C */  lui        $a0, %hi(D_8006A0D0)
    /* F2A398 8006EDFC D0A08424 */  addiu      $a0, $a0, %lo(D_8006A0D0)
    /* F2A39C 8006EE00 03B8000C */  jal        func_8002E00C
    /* F2A3A0 8006EE04 00000000 */   nop
  .Llevel_11_8006EE08:
    /* F2A3A4 8006EE08 1000BF8F */  lw         $ra, 0x10($sp)
    /* F2A3A8 8006EE0C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* F2A3AC 8006EE10 0800E003 */  jr         $ra
    /* F2A3B0 8006EE14 00000000 */   nop
endlabel func_level_11_8006ED80
