.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_41_8006D4C8

dlabel jtbl_level_41_8006D4C8
    /* 2BB8A64 8006D4C8 94EC0680 */ .word .Llevel_41_8006EC94
    /* 2BB8A68 8006D4CC 30EA0680 */ .word .Llevel_41_8006EA30
    /* 2BB8A6C 8006D4D0 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8A70 8006D4D4 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8A74 8006D4D8 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8A78 8006D4DC 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8A7C 8006D4E0 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8A80 8006D4E4 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8A84 8006D4E8 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8A88 8006D4EC 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8A8C 8006D4F0 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8A90 8006D4F4 1CEC0680 */ .word .Llevel_41_8006EC1C
    /* 2BB8A94 8006D4F8 DCEC0680 */ .word .Llevel_41_8006ECDC
    /* 2BB8A98 8006D4FC 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8A9C 8006D500 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AA0 8006D504 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AA4 8006D508 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AA8 8006D50C 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AAC 8006D510 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AB0 8006D514 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AB4 8006D518 30EA0680 */ .word .Llevel_41_8006EA30
    /* 2BB8AB8 8006D51C 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8ABC 8006D520 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AC0 8006D524 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AC4 8006D528 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AC8 8006D52C 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8ACC 8006D530 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AD0 8006D534 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AD4 8006D538 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AD8 8006D53C 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8ADC 8006D540 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AE0 8006D544 D4ED0680 */ .word .Llevel_41_8006EDD4
    /* 2BB8AE4 8006D548 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AE8 8006D54C 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AEC 8006D550 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AF0 8006D554 20EE0680 */ .word .Llevel_41_8006EE20
    /* 2BB8AF4 8006D558 04EC0680 */ .word .Llevel_41_8006EC04
    /* 2BB8AF8 8006D55C 00000000 */ .word 0x00000000
enddlabel jtbl_level_41_8006D4C8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_41_8006E9F4, 0x440

glabel func_level_41_8006E9F4
    /* 2BB9F90 8006E9F4 0780023C */  lui        $v0, %hi(D_8006A040)
    /* 2BB9F94 8006E9F8 40A0428C */  lw         $v0, %lo(D_8006A040)($v0)
    /* 2BB9F98 8006E9FC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2BB9F9C 8006EA00 1400BFAF */  sw         $ra, 0x14($sp)
    /* 2BB9FA0 8006EA04 EEFF4324 */  addiu      $v1, $v0, -0x12
    /* 2BB9FA4 8006EA08 2500622C */  sltiu      $v0, $v1, 0x25
    /* 2BB9FA8 8006EA0C 04014010 */  beqz       $v0, .Llevel_41_8006EE20
    /* 2BB9FAC 8006EA10 1000B0AF */   sw        $s0, 0x10($sp)
    /* 2BB9FB0 8006EA14 80100300 */  sll        $v0, $v1, 2
    /* 2BB9FB4 8006EA18 0780013C */  lui        $at, %hi(jtbl_level_41_8006D4C8)
    /* 2BB9FB8 8006EA1C 21082200 */  addu       $at, $at, $v0
    /* 2BB9FBC 8006EA20 C8D4228C */  lw         $v0, %lo(jtbl_level_41_8006D4C8)($at)
    /* 2BB9FC0 8006EA24 00000000 */  nop
    /* 2BB9FC4 8006EA28 08004000 */  jr         $v0
    /* 2BB9FC8 8006EA2C 00000000 */   nop
  .Llevel_41_8006EA30:
    /* 2BB9FCC 8006EA30 2EAC000C */  jal        func_8002B0B8
    /* 2BB9FD0 8006EA34 00000000 */   nop
    /* 2BB9FD4 8006EA38 F9004014 */  bnez       $v0, .Llevel_41_8006EE20
    /* 2BB9FD8 8006EA3C 00000000 */   nop
    /* 2BB9FDC 8006EA40 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 2BB9FE0 8006EA44 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 2BB9FE4 8006EA48 00000000 */  nop
    /* 2BB9FE8 8006EA4C 40004230 */  andi       $v0, $v0, 0x40
    /* 2BB9FEC 8006EA50 F1004014 */  bnez       $v0, .Llevel_41_8006EE18
    /* 2BB9FF0 8006EA54 05000424 */   addiu     $a0, $zero, 0x5
    /* 2BB9FF4 8006EA58 0780043C */  lui        $a0, %hi(D_8006A104)
    /* 2BB9FF8 8006EA5C 04A1848C */  lw         $a0, %lo(D_8006A104)($a0)
    /* 2BB9FFC 8006EA60 1EAC000C */  jal        func_8002B078
    /* 2BBA000 8006EA64 00000000 */   nop
    /* 2BBA004 8006EA68 04000324 */  addiu      $v1, $zero, 0x4
    /* 2BBA008 8006EA6C 08004314 */  bne        $v0, $v1, .Llevel_41_8006EA90
    /* 2BBA00C 8006EA70 00000000 */   nop
    /* 2BBA010 8006EA74 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 2BBA014 8006EA78 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 2BBA018 8006EA7C 00000000 */  nop
    /* 2BBA01C 8006EA80 E7004014 */  bnez       $v0, .Llevel_41_8006EE20
    /* 2BBA020 8006EA84 09000424 */   addiu     $a0, $zero, 0x9
    /* 2BBA024 8006EA88 86BB0108 */  j          .Llevel_41_8006EE18
    /* 2BBA028 8006EA8C 00000000 */   nop
  .Llevel_41_8006EA90:
    /* 2BBA02C 8006EA90 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 2BBA030 8006EA94 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 2BBA034 8006EA98 00000000 */  nop
    /* 2BBA038 8006EA9C 04004228 */  slti       $v0, $v0, 0x4
    /* 2BBA03C 8006EAA0 DD004010 */  beqz       $v0, .Llevel_41_8006EE18
    /* 2BBA040 8006EAA4 06000424 */   addiu     $a0, $zero, 0x6
    /* 2BBA044 8006EAA8 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 2BBA048 8006EAAC DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 2BBA04C 8006EAB0 00000000 */  nop
    /* 2BBA050 8006EAB4 17004228 */  slti       $v0, $v0, 0x17
    /* 2BBA054 8006EAB8 D7004010 */  beqz       $v0, .Llevel_41_8006EE18
    /* 2BBA058 8006EABC 00000000 */   nop
    /* 2BBA05C 8006EAC0 0780033C */  lui        $v1, %hi(D_800683A0)
    /* 2BBA060 8006EAC4 A083638C */  lw         $v1, %lo(D_800683A0)($v1)
    /* 2BBA064 8006EAC8 00000000 */  nop
    /* 2BBA068 8006EACC 80006230 */  andi       $v0, $v1, 0x80
    /* 2BBA06C 8006EAD0 D1004014 */  bnez       $v0, .Llevel_41_8006EE18
    /* 2BBA070 8006EAD4 0C000424 */   addiu     $a0, $zero, 0xC
    /* 2BBA074 8006EAD8 0780023C */  lui        $v0, %hi(D_8006A0A0)
    /* 2BBA078 8006EADC A0A0428C */  lw         $v0, %lo(D_8006A0A0)($v0)
    /* 2BBA07C 8006EAE0 00000000 */  nop
    /* 2BBA080 8006EAE4 02004104 */  bgez       $v0, .Llevel_41_8006EAF0
    /* 2BBA084 8006EAE8 00000000 */   nop
    /* 2BBA088 8006EAEC 23100200 */  negu       $v0, $v0
  .Llevel_41_8006EAF0:
    /* 2BBA08C 8006EAF0 11004228 */  slti       $v0, $v0, 0x11
    /* 2BBA090 8006EAF4 03004014 */  bnez       $v0, .Llevel_41_8006EB04
    /* 2BBA094 8006EAF8 0F006330 */   andi      $v1, $v1, 0xF
    /* 2BBA098 8006EAFC 86BB0108 */  j          .Llevel_41_8006EE18
    /* 2BBA09C 8006EB00 01000424 */   addiu     $a0, $zero, 0x1
  .Llevel_41_8006EB04:
    /* 2BBA0A0 8006EB04 03000224 */  addiu      $v0, $zero, 0x3
    /* 2BBA0A4 8006EB08 06006210 */  beq        $v1, $v0, .Llevel_41_8006EB24
    /* 2BBA0A8 8006EB0C 00000000 */   nop
    /* 2BBA0AC 8006EB10 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 2BBA0B0 8006EB14 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 2BBA0B4 8006EB18 00000000 */  nop
    /* 2BBA0B8 8006EB1C BE004014 */  bnez       $v0, .Llevel_41_8006EE18
    /* 2BBA0BC 8006EB20 01000424 */   addiu     $a0, $zero, 0x1
  .Llevel_41_8006EB24:
    /* 2BBA0C0 8006EB24 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 2BBA0C4 8006EB28 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 2BBA0C8 8006EB2C 07000224 */  addiu      $v0, $zero, 0x7
    /* 2BBA0CC 8006EB30 06006210 */  beq        $v1, $v0, .Llevel_41_8006EB4C
    /* 2BBA0D0 8006EB34 00000000 */   nop
    /* 2BBA0D4 8006EB38 0780023C */  lui        $v0, %hi(D_8006A230)
    /* 2BBA0D8 8006EB3C 30A2428C */  lw         $v0, %lo(D_8006A230)($v0)
    /* 2BBA0DC 8006EB40 00000000 */  nop
    /* 2BBA0E0 8006EB44 26004010 */  beqz       $v0, .Llevel_41_8006EBE0
    /* 2BBA0E4 8006EB48 00000000 */   nop
  .Llevel_41_8006EB4C:
    /* 2BBA0E8 8006EB4C 0780103C */  lui        $s0, %hi(D_8006A040)
    /* 2BBA0EC 8006EB50 40A01026 */  addiu      $s0, $s0, %lo(D_8006A040)
    /* 2BBA0F0 8006EB54 0000028E */  lw         $v0, 0x0($s0)
    /* 2BBA0F4 8006EB58 00000000 */  nop
    /* 2BBA0F8 8006EB5C B0004010 */  beqz       $v0, .Llevel_41_8006EE20
    /* 2BBA0FC 8006EB60 00000000 */   nop
    /* 2BBA100 8006EB64 76D4000C */  jal        func_800351D8
    /* 2BBA104 8006EB68 21200000 */   addu      $a0, $zero, $zero
    /* 2BBA108 8006EB6C CCFF0292 */  lbu        $v0, -0x34($s0)
    /* 2BBA10C 8006EB70 0680013C */  lui        $at, %hi(D_80062868)
    /* 2BBA110 8006EB74 21082200 */  addu       $at, $at, $v0
    /* 2BBA114 8006EB78 68282290 */  lbu        $v0, %lo(D_80062868)($at)
    /* 2BBA118 8006EB7C 00000000 */  nop
    /* 2BBA11C 8006EB80 6000422C */  sltiu      $v0, $v0, 0x60
    /* 2BBA120 8006EB84 09004014 */  bnez       $v0, .Llevel_41_8006EBAC
    /* 2BBA124 8006EB88 00000000 */   nop
    /* 2BBA128 8006EB8C 0780023C */  lui        $v0, %hi(D_8006A005)
    /* 2BBA12C 8006EB90 05A04290 */  lbu        $v0, %lo(D_8006A005)($v0)
    /* 2BBA130 8006EB94 0780033C */  lui        $v1, %hi(D_8006A007)
    /* 2BBA134 8006EB98 07A06390 */  lbu        $v1, %lo(D_8006A007)($v1)
    /* 2BBA138 8006EB9C 0780013C */  lui        $at, %hi(D_8006A004)
    /* 2BBA13C 8006EBA0 04A022A0 */  sb         $v0, %lo(D_8006A004)($at)
    /* 2BBA140 8006EBA4 0780013C */  lui        $at, %hi(D_8006A006)
    /* 2BBA144 8006EBA8 06A023A0 */  sb         $v1, %lo(D_8006A006)($at)
  .Llevel_41_8006EBAC:
    /* 2BBA148 8006EBAC 0780013C */  lui        $at, %hi(D_8006A007)
    /* 2BBA14C 8006EBB0 07A020A0 */  sb         $zero, %lo(D_8006A007)($at)
    /* 2BBA150 8006EBB4 0000038E */  lw         $v1, 0x0($s0)
    /* 2BBA154 8006EBB8 71000224 */  addiu      $v0, $zero, 0x71
    /* 2BBA158 8006EBBC CCFF02A2 */  sb         $v0, -0x34($s0)
    /* 2BBA15C 8006EBC0 0780013C */  lui        $at, %hi(D_8006A1E0)
    /* 2BBA160 8006EBC4 E0A120AC */  sw         $zero, %lo(D_8006A1E0)($at)
    /* 2BBA164 8006EBC8 0780013C */  lui        $at, %hi(D_8006A005)
    /* 2BBA168 8006EBCC 05A023A0 */  sb         $v1, %lo(D_8006A005)($at)
    /* 2BBA16C 8006EBD0 0780013C */  lui        $at, %hi(D_8006A1DC)
    /* 2BBA170 8006EBD4 DCA123AC */  sw         $v1, %lo(D_8006A1DC)($at)
    /* 2BBA174 8006EBD8 88BB0108 */  j          .Llevel_41_8006EE20
    /* 2BBA178 8006EBDC 00000000 */   nop
  .Llevel_41_8006EBE0:
    /* 2BBA17C 8006EBE0 0780023C */  lui        $v0, %hi(D_8006A0F4)
    /* 2BBA180 8006EBE4 F4A04290 */  lbu        $v0, %lo(D_8006A0F4)($v0)
    /* 2BBA184 8006EBE8 00000000 */  nop
    /* 2BBA188 8006EBEC 8A004014 */  bnez       $v0, .Llevel_41_8006EE18
    /* 2BBA18C 8006EBF0 0E000424 */   addiu     $a0, $zero, 0xE
    /* 2BBA190 8006EBF4 0DCB000C */  jal        func_80032C34
    /* 2BBA194 8006EBF8 00000000 */   nop
    /* 2BBA198 8006EBFC 88BB0108 */  j          .Llevel_41_8006EE20
    /* 2BBA19C 8006EC00 00000000 */   nop
  .Llevel_41_8006EC04:
    /* 2BBA1A0 8006EC04 2EAC000C */  jal        func_8002B0B8
    /* 2BBA1A4 8006EC08 00000000 */   nop
    /* 2BBA1A8 8006EC0C 84004014 */  bnez       $v0, .Llevel_41_8006EE20
    /* 2BBA1AC 8006EC10 21200000 */   addu      $a0, $zero, $zero
    /* 2BBA1B0 8006EC14 86BB0108 */  j          .Llevel_41_8006EE18
    /* 2BBA1B4 8006EC18 00000000 */   nop
  .Llevel_41_8006EC1C:
    /* 2BBA1B8 8006EC1C 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 2BBA1BC 8006EC20 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 2BBA1C0 8006EC24 00000000 */  nop
    /* 2BBA1C4 8006EC28 19004228 */  slti       $v0, $v0, 0x19
    /* 2BBA1C8 8006EC2C 7C004014 */  bnez       $v0, .Llevel_41_8006EE20
    /* 2BBA1CC 8006EC30 00000000 */   nop
    /* 2BBA1D0 8006EC34 0780023C */  lui        $v0, %hi(D_8006A248)
    /* 2BBA1D4 8006EC38 48A2428C */  lw         $v0, %lo(D_8006A248)($v0)
    /* 2BBA1D8 8006EC3C 00000000 */  nop
    /* 2BBA1DC 8006EC40 03004104 */  bgez       $v0, .Llevel_41_8006EC50
    /* 2BBA1E0 8006EC44 0A000224 */   addiu     $v0, $zero, 0xA
    /* 2BBA1E4 8006EC48 86BB0108 */  j          .Llevel_41_8006EE18
    /* 2BBA1E8 8006EC4C 1F000424 */   addiu     $a0, $zero, 0x1F
  .Llevel_41_8006EC50:
    /* 2BBA1EC 8006EC50 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 2BBA1F0 8006EC54 3CA1638C */  lw         $v1, %lo(D_8006A13C)($v1)
    /* 2BBA1F4 8006EC58 00000000 */  nop
    /* 2BBA1F8 8006EC5C 03006214 */  bne        $v1, $v0, .Llevel_41_8006EC6C
    /* 2BBA1FC 8006EC60 F5FF6224 */   addiu     $v0, $v1, -0xB
    /* 2BBA200 8006EC64 86BB0108 */  j          .Llevel_41_8006EE18
    /* 2BBA204 8006EC68 2C000424 */   addiu     $a0, $zero, 0x2C
  .Llevel_41_8006EC6C:
    /* 2BBA208 8006EC6C 0200422C */  sltiu      $v0, $v0, 0x2
    /* 2BBA20C 8006EC70 69004014 */  bnez       $v0, .Llevel_41_8006EE18
    /* 2BBA210 8006EC74 29000424 */   addiu     $a0, $zero, 0x29
    /* 2BBA214 8006EC78 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 2BBA218 8006EC7C B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 2BBA21C 8006EC80 00000000 */  nop
    /* 2BBA220 8006EC84 63004010 */  beqz       $v0, .Llevel_41_8006EE14
    /* 2BBA224 8006EC88 06000424 */   addiu     $a0, $zero, 0x6
    /* 2BBA228 8006EC8C 86BB0108 */  j          .Llevel_41_8006EE18
    /* 2BBA22C 8006EC90 00000000 */   nop
  .Llevel_41_8006EC94:
    /* 2BBA230 8006EC94 2EAC000C */  jal        func_8002B0B8
    /* 2BBA234 8006EC98 00000000 */   nop
    /* 2BBA238 8006EC9C 60004014 */  bnez       $v0, .Llevel_41_8006EE20
    /* 2BBA23C 8006ECA0 00000000 */   nop
    /* 2BBA240 8006ECA4 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 2BBA244 8006ECA8 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 2BBA248 8006ECAC 0780043C */  lui        $a0, %hi(D_80069FF0)
    /* 2BBA24C 8006ECB0 F09F8424 */  addiu      $a0, $a0, %lo(D_80069FF0)
    /* 2BBA250 8006ECB4 DB6F000C */  jal        func_8001BF6C
    /* 2BBA254 8006ECB8 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 2BBA258 8006ECBC 0780033C */  lui        $v1, %hi(D_8006A150)
    /* 2BBA25C 8006ECC0 50A1638C */  lw         $v1, %lo(D_8006A150)($v1)
    /* 2BBA260 8006ECC4 00000000 */  nop
    /* 2BBA264 8006ECC8 2A186200 */  slt        $v1, $v1, $v0
    /* 2BBA268 8006ECCC 54006010 */  beqz       $v1, .Llevel_41_8006EE20
    /* 2BBA26C 8006ECD0 10000424 */   addiu     $a0, $zero, 0x10
    /* 2BBA270 8006ECD4 86BB0108 */  j          .Llevel_41_8006EE18
    /* 2BBA274 8006ECD8 00000000 */   nop
  .Llevel_41_8006ECDC:
    /* 2BBA278 8006ECDC 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 2BBA27C 8006ECE0 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 2BBA280 8006ECE4 00000000 */  nop
    /* 2BBA284 8006ECE8 40004230 */  andi       $v0, $v0, 0x40
    /* 2BBA288 8006ECEC 03004010 */  beqz       $v0, .Llevel_41_8006ECFC
    /* 2BBA28C 8006ECF0 01000224 */   addiu     $v0, $zero, 0x1
    /* 2BBA290 8006ECF4 0780013C */  lui        $at, %hi(D_8006A1AE)
    /* 2BBA294 8006ECF8 AEA122A0 */  sb         $v0, %lo(D_8006A1AE)($at)
  .Llevel_41_8006ECFC:
    /* 2BBA298 8006ECFC 0780043C */  lui        $a0, %hi(D_8006A248)
    /* 2BBA29C 8006ED00 48A28424 */  addiu      $a0, $a0, %lo(D_8006A248)
    /* 2BBA2A0 8006ED04 0000828C */  lw         $v0, 0x0($a0)
    /* 2BBA2A4 8006ED08 00000000 */  nop
    /* 2BBA2A8 8006ED0C 0D004104 */  bgez       $v0, .Llevel_41_8006ED44
    /* 2BBA2AC 8006ED10 FF8F0234 */   ori       $v0, $zero, 0x8FFF
    /* 2BBA2B0 8006ED14 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 2BBA2B4 8006ED18 3CA1638C */  lw         $v1, %lo(D_8006A13C)($v1)
    /* 2BBA2B8 8006ED1C 00000000 */  nop
    /* 2BBA2BC 8006ED20 2A104300 */  slt        $v0, $v0, $v1
    /* 2BBA2C0 8006ED24 3E004010 */  beqz       $v0, .Llevel_41_8006EE20
    /* 2BBA2C4 8006ED28 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 2BBA2C8 8006ED2C 0780013C */  lui        $at, %hi(D_8006A254)
    /* 2BBA2CC 8006ED30 54A222AC */  sw         $v0, %lo(D_8006A254)($at)
    /* 2BBA2D0 8006ED34 9DCB000C */  jal        func_80032E74
    /* 2BBA2D4 8006ED38 00000000 */   nop
    /* 2BBA2D8 8006ED3C 88BB0108 */  j          .Llevel_41_8006EE20
    /* 2BBA2DC 8006ED40 00000000 */   nop
  .Llevel_41_8006ED44:
    /* 2BBA2E0 8006ED44 0780033C */  lui        $v1, %hi(D_8006A04C)
    /* 2BBA2E4 8006ED48 4CA0638C */  lw         $v1, %lo(D_8006A04C)($v1)
    /* 2BBA2E8 8006ED4C 00000000 */  nop
    /* 2BBA2EC 8006ED50 3D006228 */  slti       $v0, $v1, 0x3D
    /* 2BBA2F0 8006ED54 04004014 */  bnez       $v0, .Llevel_41_8006ED68
    /* 2BBA2F4 8006ED58 10006228 */   slti      $v0, $v1, 0x10
    /* 2BBA2F8 8006ED5C FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 2BBA2FC 8006ED60 88BB0108 */  j          .Llevel_41_8006EE20
    /* 2BBA300 8006ED64 000082AC */   sw        $v0, 0x0($a0)
  .Llevel_41_8006ED68:
    /* 2BBA304 8006ED68 2D004014 */  bnez       $v0, .Llevel_41_8006EE20
    /* 2BBA308 8006ED6C 00000000 */   nop
    /* 2BBA30C 8006ED70 0780023C */  lui        $v0, %hi(D_8006A1AE)
    /* 2BBA310 8006ED74 AEA14290 */  lbu        $v0, %lo(D_8006A1AE)($v0)
    /* 2BBA314 8006ED78 00000000 */  nop
    /* 2BBA318 8006ED7C 28004010 */  beqz       $v0, .Llevel_41_8006EE20
    /* 2BBA31C 8006ED80 00000000 */   nop
    /* 2BBA320 8006ED84 0780053C */  lui        $a1, %hi(D_8006A254)
    /* 2BBA324 8006ED88 54A2A58C */  lw         $a1, %lo(D_8006A254)($a1)
    /* 2BBA328 8006ED8C 00000000 */  nop
    /* 2BBA32C 8006ED90 2100A004 */  bltz       $a1, .Llevel_41_8006EE18
    /* 2BBA330 8006ED94 05000424 */   addiu     $a0, $zero, 0x5
    /* 2BBA334 8006ED98 0780043C */  lui        $a0, %hi(D_8006A258)
    /* 2BBA338 8006ED9C 58A2848C */  lw         $a0, %lo(D_8006A258)($a0)
    /* 2BBA33C 8006EDA0 C842010C */  jal        func_80050B20
    /* 2BBA340 8006EDA4 00000000 */   nop
    /* 2BBA344 8006EDA8 06004010 */  beqz       $v0, .Llevel_41_8006EDC4
    /* 2BBA348 8006EDAC FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 2BBA34C 8006EDB0 0780043C */  lui        $a0, %hi(D_8006A254)
    /* 2BBA350 8006EDB4 54A2848C */  lw         $a0, %lo(D_8006A254)($a0)
    /* 2BBA354 8006EDB8 9042010C */  jal        func_80050A40
    /* 2BBA358 8006EDBC 00000000 */   nop
    /* 2BBA35C 8006EDC0 FFFF0224 */  addiu      $v0, $zero, -0x1
  .Llevel_41_8006EDC4:
    /* 2BBA360 8006EDC4 0780013C */  lui        $at, %hi(D_8006A254)
    /* 2BBA364 8006EDC8 54A222AC */  sw         $v0, %lo(D_8006A254)($at)
    /* 2BBA368 8006EDCC 86BB0108 */  j          .Llevel_41_8006EE18
    /* 2BBA36C 8006EDD0 05000424 */   addiu     $a0, $zero, 0x5
  .Llevel_41_8006EDD4:
    /* 2BBA370 8006EDD4 2EAC000C */  jal        func_8002B0B8
    /* 2BBA374 8006EDD8 00000000 */   nop
    /* 2BBA378 8006EDDC 10004014 */  bnez       $v0, .Llevel_41_8006EE20
    /* 2BBA37C 8006EDE0 00000000 */   nop
    /* 2BBA380 8006EDE4 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 2BBA384 8006EDE8 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 2BBA388 8006EDEC 00000000 */  nop
    /* 2BBA38C 8006EDF0 04004228 */  slti       $v0, $v0, 0x4
    /* 2BBA390 8006EDF4 08004010 */  beqz       $v0, .Llevel_41_8006EE18
    /* 2BBA394 8006EDF8 06000424 */   addiu     $a0, $zero, 0x6
    /* 2BBA398 8006EDFC 0780023C */  lui        $v0, %hi(D_8006A13C)
    /* 2BBA39C 8006EE00 3CA1428C */  lw         $v0, %lo(D_8006A13C)($v0)
    /* 2BBA3A0 8006EE04 00000000 */  nop
    /* 2BBA3A4 8006EE08 10004228 */  slti       $v0, $v0, 0x10
    /* 2BBA3A8 8006EE0C 04004014 */  bnez       $v0, .Llevel_41_8006EE20
    /* 2BBA3AC 8006EE10 00000000 */   nop
  .Llevel_41_8006EE14:
    /* 2BBA3B0 8006EE14 21200000 */  addu       $a0, $zero, $zero
  .Llevel_41_8006EE18:
    /* 2BBA3B4 8006EE18 76D4000C */  jal        func_800351D8
    /* 2BBA3B8 8006EE1C 00000000 */   nop
  .Llevel_41_8006EE20:
    /* 2BBA3BC 8006EE20 1400BF8F */  lw         $ra, 0x14($sp)
    /* 2BBA3C0 8006EE24 1000B08F */  lw         $s0, 0x10($sp)
    /* 2BBA3C4 8006EE28 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2BBA3C8 8006EE2C 0800E003 */  jr         $ra
    /* 2BBA3CC 8006EE30 00000000 */   nop
endlabel func_level_41_8006E9F4
    /* 2BBA3D0 8006EE34 00000000 */  nop
