.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_41_8006D398

dlabel jtbl_level_41_8006D398
    /* 2BB8934 8006D398 F0E50680 */ .word .Llevel_41_8006E5F0
    /* 2BB8938 8006D39C E0E50680 */ .word .Llevel_41_8006E5E0
    /* 2BB893C 8006D3A0 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8940 8006D3A4 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8944 8006D3A8 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8948 8006D3AC FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB894C 8006D3B0 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8950 8006D3B4 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8954 8006D3B8 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8958 8006D3BC FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB895C 8006D3C0 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8960 8006D3C4 E0E50680 */ .word .Llevel_41_8006E5E0
    /* 2BB8964 8006D3C8 E0E50680 */ .word .Llevel_41_8006E5E0
    /* 2BB8968 8006D3CC FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB896C 8006D3D0 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8970 8006D3D4 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8974 8006D3D8 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8978 8006D3DC FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB897C 8006D3E0 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8980 8006D3E4 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8984 8006D3E8 E0E50680 */ .word .Llevel_41_8006E5E0
    /* 2BB8988 8006D3EC FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB898C 8006D3F0 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8990 8006D3F4 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8994 8006D3F8 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB8998 8006D3FC FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB899C 8006D400 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB89A0 8006D404 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB89A4 8006D408 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB89A8 8006D40C FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB89AC 8006D410 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB89B0 8006D414 E0E50680 */ .word .Llevel_41_8006E5E0
    /* 2BB89B4 8006D418 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB89B8 8006D41C FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB89BC 8006D420 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB89C0 8006D424 FCE50680 */ .word .Llevel_41_8006E5FC
    /* 2BB89C4 8006D428 E0E50680 */ .word .Llevel_41_8006E5E0
    /* 2BB89C8 8006D42C 00000000 */ .word 0x00000000
enddlabel jtbl_level_41_8006D398


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_41_8006E590, 0x7C

glabel func_level_41_8006E590
    /* 2BB9B2C 8006E590 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2BB9B30 8006E594 00210400 */  sll        $a0, $a0, 4
    /* 2BB9B34 8006E598 0780023C */  lui        $v0, %hi(D_800683B0)
    /* 2BB9B38 8006E59C B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* 2BB9B3C 8006E5A0 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 2BB9B40 8006E5A4 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 2BB9B44 8006E5A8 21208200 */  addu       $a0, $a0, $v0
    /* 2BB9B48 8006E5AC 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2BB9B4C 8006E5B0 0680013C */  lui        $at, %hi(D_80066F38)
    /* 2BB9B50 8006E5B4 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* 2BB9B54 8006E5B8 EEFF6324 */  addiu      $v1, $v1, -0x12
    /* 2BB9B58 8006E5BC 2500622C */  sltiu      $v0, $v1, 0x25
    /* 2BB9B5C 8006E5C0 0E004010 */  beqz       $v0, .Llevel_41_8006E5FC
    /* 2BB9B60 8006E5C4 80100300 */   sll       $v0, $v1, 2
    /* 2BB9B64 8006E5C8 0780013C */  lui        $at, %hi(jtbl_level_41_8006D398)
    /* 2BB9B68 8006E5CC 21082200 */  addu       $at, $at, $v0
    /* 2BB9B6C 8006E5D0 98D3228C */  lw         $v0, %lo(jtbl_level_41_8006D398)($at)
    /* 2BB9B70 8006E5D4 00000000 */  nop
    /* 2BB9B74 8006E5D8 08004000 */  jr         $v0
    /* 2BB9B78 8006E5DC 00000000 */   nop
  .Llevel_41_8006E5E0:
    /* 2BB9B7C 8006E5E0 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* 2BB9B80 8006E5E4 C4A08424 */  addiu      $a0, $a0, %lo(D_8006A0C4)
    /* 2BB9B84 8006E5E8 7DB90108 */  j          .Llevel_41_8006E5F4
    /* 2BB9B88 8006E5EC 00000000 */   nop
  .Llevel_41_8006E5F0:
    /* 2BB9B8C 8006E5F0 21200000 */  addu       $a0, $zero, $zero
  .Llevel_41_8006E5F4:
    /* 2BB9B90 8006E5F4 E3B6000C */  jal        func_8002DB8C
    /* 2BB9B94 8006E5F8 00000000 */   nop
  .Llevel_41_8006E5FC:
    /* 2BB9B98 8006E5FC 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2BB9B9C 8006E600 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2BB9BA0 8006E604 0800E003 */  jr         $ra
    /* 2BB9BA4 8006E608 00000000 */   nop
endlabel func_level_41_8006E590
