.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_34_8006D3B8

dlabel jtbl_level_34_8006D3B8
    /* 27AA154 8006D3B8 DCE80680 */ .word .Llevel_34_8006E8DC
    /* 27AA158 8006D3BC C4E80680 */ .word .Llevel_34_8006E8C4
    /* 27AA15C 8006D3C0 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA160 8006D3C4 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA164 8006D3C8 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA168 8006D3CC FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA16C 8006D3D0 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA170 8006D3D4 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA174 8006D3D8 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA178 8006D3DC FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA17C 8006D3E0 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA180 8006D3E4 C4E80680 */ .word .Llevel_34_8006E8C4
    /* 27AA184 8006D3E8 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA188 8006D3EC FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA18C 8006D3F0 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA190 8006D3F4 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA194 8006D3F8 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA198 8006D3FC FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA19C 8006D400 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1A0 8006D404 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1A4 8006D408 C4E80680 */ .word .Llevel_34_8006E8C4
    /* 27AA1A8 8006D40C FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1AC 8006D410 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1B0 8006D414 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1B4 8006D418 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1B8 8006D41C FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1BC 8006D420 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1C0 8006D424 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1C4 8006D428 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1C8 8006D42C ECE80680 */ .word .Llevel_34_8006E8EC
    /* 27AA1CC 8006D430 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1D0 8006D434 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1D4 8006D438 ECE80680 */ .word .Llevel_34_8006E8EC
    /* 27AA1D8 8006D43C ECE80680 */ .word .Llevel_34_8006E8EC
    /* 27AA1DC 8006D440 ECE80680 */ .word .Llevel_34_8006E8EC
    /* 27AA1E0 8006D444 C4E80680 */ .word .Llevel_34_8006E8C4
    /* 27AA1E4 8006D448 C4E80680 */ .word .Llevel_34_8006E8C4
    /* 27AA1E8 8006D44C FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1EC 8006D450 C4E80680 */ .word .Llevel_34_8006E8C4
    /* 27AA1F0 8006D454 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1F4 8006D458 FCE80680 */ .word .Llevel_34_8006E8FC
    /* 27AA1F8 8006D45C C4E80680 */ .word .Llevel_34_8006E8C4
enddlabel jtbl_level_34_8006D3B8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_34_8006E874, 0x98

glabel func_level_34_8006E874
    /* 27AB610 8006E874 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 27AB614 8006E878 00210400 */  sll        $a0, $a0, 4
    /* 27AB618 8006E87C 0780023C */  lui        $v0, %hi(D_800683B0)
    /* 27AB61C 8006E880 B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* 27AB620 8006E884 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 27AB624 8006E888 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 27AB628 8006E88C 21208200 */  addu       $a0, $a0, $v0
    /* 27AB62C 8006E890 1000BFAF */  sw         $ra, 0x10($sp)
    /* 27AB630 8006E894 0680013C */  lui        $at, %hi(D_80066F38)
    /* 27AB634 8006E898 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* 27AB638 8006E89C EEFF6324 */  addiu      $v1, $v1, -0x12
    /* 27AB63C 8006E8A0 2A00622C */  sltiu      $v0, $v1, 0x2A
    /* 27AB640 8006E8A4 15004010 */  beqz       $v0, .Llevel_34_8006E8FC
    /* 27AB644 8006E8A8 80100300 */   sll       $v0, $v1, 2
    /* 27AB648 8006E8AC 0780013C */  lui        $at, %hi(jtbl_level_34_8006D3B8)
    /* 27AB64C 8006E8B0 21082200 */  addu       $at, $at, $v0
    /* 27AB650 8006E8B4 B8D3228C */  lw         $v0, %lo(jtbl_level_34_8006D3B8)($at)
    /* 27AB654 8006E8B8 00000000 */  nop
    /* 27AB658 8006E8BC 08004000 */  jr         $v0
    /* 27AB65C 8006E8C0 00000000 */   nop
  .Llevel_34_8006E8C4:
    /* 27AB660 8006E8C4 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* 27AB664 8006E8C8 C4A08424 */  addiu      $a0, $a0, %lo(D_8006A0C4)
    /* 27AB668 8006E8CC E3B6000C */  jal        func_8002DB8C
    /* 27AB66C 8006E8D0 00000000 */   nop
    /* 27AB670 8006E8D4 3FBA0108 */  j          .Llevel_34_8006E8FC
    /* 27AB674 8006E8D8 00000000 */   nop
  .Llevel_34_8006E8DC:
    /* 27AB678 8006E8DC E3B6000C */  jal        func_8002DB8C
    /* 27AB67C 8006E8E0 21200000 */   addu      $a0, $zero, $zero
    /* 27AB680 8006E8E4 3FBA0108 */  j          .Llevel_34_8006E8FC
    /* 27AB684 8006E8E8 00000000 */   nop
  .Llevel_34_8006E8EC:
    /* 27AB688 8006E8EC 0780043C */  lui        $a0, %hi(D_8006A0D0)
    /* 27AB68C 8006E8F0 D0A08424 */  addiu      $a0, $a0, %lo(D_8006A0D0)
    /* 27AB690 8006E8F4 03B8000C */  jal        func_8002E00C
    /* 27AB694 8006E8F8 00000000 */   nop
  .Llevel_34_8006E8FC:
    /* 27AB698 8006E8FC 1000BF8F */  lw         $ra, 0x10($sp)
    /* 27AB69C 8006E900 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 27AB6A0 8006E904 0800E003 */  jr         $ra
    /* 27AB6A4 8006E908 00000000 */   nop
endlabel func_level_34_8006E874
