.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_34_8006D508

dlabel jtbl_level_34_8006D508
    /* 27AA2A4 8006D508 40F00680 */ .word .Llevel_34_8006F040
    /* 27AA2A8 8006D50C BCED0680 */ .word .Llevel_34_8006EDBC
    /* 27AA2AC 8006D510 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2B0 8006D514 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2B4 8006D518 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2B8 8006D51C 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2BC 8006D520 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2C0 8006D524 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2C4 8006D528 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2C8 8006D52C 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2CC 8006D530 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2D0 8006D534 D8EF0680 */ .word .Llevel_34_8006EFD8
    /* 27AA2D4 8006D538 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2D8 8006D53C 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2DC 8006D540 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2E0 8006D544 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2E4 8006D548 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2E8 8006D54C 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2EC 8006D550 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2F0 8006D554 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2F4 8006D558 BCED0680 */ .word .Llevel_34_8006EDBC
    /* 27AA2F8 8006D55C 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA2FC 8006D560 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA300 8006D564 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA304 8006D568 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA308 8006D56C 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA30C 8006D570 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA310 8006D574 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA314 8006D578 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA318 8006D57C 90F00680 */ .word .Llevel_34_8006F090
    /* 27AA31C 8006D580 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA320 8006D584 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA324 8006D588 F4F00680 */ .word .Llevel_34_8006F0F4
    /* 27AA328 8006D58C 9CF10680 */ .word .Llevel_34_8006F19C
    /* 27AA32C 8006D590 9CF10680 */ .word .Llevel_34_8006F19C
    /* 27AA330 8006D594 C0EF0680 */ .word .Llevel_34_8006EFC0
    /* 27AA334 8006D598 C0EF0680 */ .word .Llevel_34_8006EFC0
    /* 27AA338 8006D59C 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA33C 8006D5A0 64F20680 */ .word .Llevel_34_8006F264
    /* 27AA340 8006D5A4 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA344 8006D5A8 34F30680 */ .word .Llevel_34_8006F334
    /* 27AA348 8006D5AC 14F30680 */ .word .Llevel_34_8006F314
enddlabel jtbl_level_34_8006D508


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_34_8006ED80, 0x5C8

glabel func_level_34_8006ED80
    /* 27ABB1C 8006ED80 0780023C */  lui        $v0, %hi(D_8006A040)
    /* 27ABB20 8006ED84 40A0428C */  lw         $v0, %lo(D_8006A040)($v0)
    /* 27ABB24 8006ED88 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 27ABB28 8006ED8C 1400BFAF */  sw         $ra, 0x14($sp)
    /* 27ABB2C 8006ED90 EEFF4324 */  addiu      $v1, $v0, -0x12
    /* 27ABB30 8006ED94 2A00622C */  sltiu      $v0, $v1, 0x2A
    /* 27ABB34 8006ED98 66014010 */  beqz       $v0, .Llevel_34_8006F334
    /* 27ABB38 8006ED9C 1000B0AF */   sw        $s0, 0x10($sp)
    /* 27ABB3C 8006EDA0 80100300 */  sll        $v0, $v1, 2
    /* 27ABB40 8006EDA4 0780013C */  lui        $at, %hi(jtbl_level_34_8006D508)
    /* 27ABB44 8006EDA8 21082200 */  addu       $at, $at, $v0
    /* 27ABB48 8006EDAC 08D5228C */  lw         $v0, %lo(jtbl_level_34_8006D508)($at)
    /* 27ABB4C 8006EDB0 00000000 */  nop
    /* 27ABB50 8006EDB4 08004000 */  jr         $v0
    /* 27ABB54 8006EDB8 00000000 */   nop
  .Llevel_34_8006EDBC:
    /* 27ABB58 8006EDBC 2EAC000C */  jal        func_8002B0B8
    /* 27ABB5C 8006EDC0 00000000 */   nop
    /* 27ABB60 8006EDC4 5B014014 */  bnez       $v0, .Llevel_34_8006F334
    /* 27ABB64 8006EDC8 00000000 */   nop
    /* 27ABB68 8006EDCC 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 27ABB6C 8006EDD0 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 27ABB70 8006EDD4 00000000 */  nop
    /* 27ABB74 8006EDD8 40004230 */  andi       $v0, $v0, 0x40
    /* 27ABB78 8006EDDC 06014014 */  bnez       $v0, .Llevel_34_8006F1F8
    /* 27ABB7C 8006EDE0 00000000 */   nop
    /* 27ABB80 8006EDE4 0780043C */  lui        $a0, %hi(D_8006A104)
    /* 27ABB84 8006EDE8 04A1848C */  lw         $a0, %lo(D_8006A104)($a0)
    /* 27ABB88 8006EDEC 1EAC000C */  jal        func_8002B078
    /* 27ABB8C 8006EDF0 00000000 */   nop
    /* 27ABB90 8006EDF4 04000324 */  addiu      $v1, $zero, 0x4
    /* 27ABB94 8006EDF8 0A004314 */  bne        $v0, $v1, .Llevel_34_8006EE24
    /* 27ABB98 8006EDFC 00000000 */   nop
    /* 27ABB9C 8006EE00 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 27ABBA0 8006EE04 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 27ABBA4 8006EE08 00000000 */  nop
    /* 27ABBA8 8006EE0C 49014014 */  bnez       $v0, .Llevel_34_8006F334
    /* 27ABBAC 8006EE10 00000000 */   nop
    /* 27ABBB0 8006EE14 76D4000C */  jal        func_800351D8
    /* 27ABBB4 8006EE18 09000424 */   addiu     $a0, $zero, 0x9
    /* 27ABBB8 8006EE1C CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABBBC 8006EE20 00000000 */   nop
  .Llevel_34_8006EE24:
    /* 27ABBC0 8006EE24 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 27ABBC4 8006EE28 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 27ABBC8 8006EE2C 00000000 */  nop
    /* 27ABBCC 8006EE30 04004228 */  slti       $v0, $v0, 0x4
    /* 27ABBD0 8006EE34 2F014010 */  beqz       $v0, .Llevel_34_8006F2F4
    /* 27ABBD4 8006EE38 00000000 */   nop
    /* 27ABBD8 8006EE3C 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 27ABBDC 8006EE40 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 27ABBE0 8006EE44 00000000 */  nop
    /* 27ABBE4 8006EE48 17004228 */  slti       $v0, $v0, 0x17
    /* 27ABBE8 8006EE4C 29014010 */  beqz       $v0, .Llevel_34_8006F2F4
    /* 27ABBEC 8006EE50 00000000 */   nop
    /* 27ABBF0 8006EE54 0780033C */  lui        $v1, %hi(D_800683A0)
    /* 27ABBF4 8006EE58 A083638C */  lw         $v1, %lo(D_800683A0)($v1)
    /* 27ABBF8 8006EE5C 00000000 */  nop
    /* 27ABBFC 8006EE60 80006230 */  andi       $v0, $v1, 0x80
    /* 27ABC00 8006EE64 05004010 */  beqz       $v0, .Llevel_34_8006EE7C
    /* 27ABC04 8006EE68 00000000 */   nop
    /* 27ABC08 8006EE6C 76D4000C */  jal        func_800351D8
    /* 27ABC0C 8006EE70 0C000424 */   addiu     $a0, $zero, 0xC
    /* 27ABC10 8006EE74 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABC14 8006EE78 00000000 */   nop
  .Llevel_34_8006EE7C:
    /* 27ABC18 8006EE7C 0780023C */  lui        $v0, %hi(D_8006A0A0)
    /* 27ABC1C 8006EE80 A0A0428C */  lw         $v0, %lo(D_8006A0A0)($v0)
    /* 27ABC20 8006EE84 00000000 */  nop
    /* 27ABC24 8006EE88 02004104 */  bgez       $v0, .Llevel_34_8006EE94
    /* 27ABC28 8006EE8C 00000000 */   nop
    /* 27ABC2C 8006EE90 23100200 */  negu       $v0, $v0
  .Llevel_34_8006EE94:
    /* 27ABC30 8006EE94 11004228 */  slti       $v0, $v0, 0x11
    /* 27ABC34 8006EE98 09004010 */  beqz       $v0, .Llevel_34_8006EEC0
    /* 27ABC38 8006EE9C 0F006330 */   andi      $v1, $v1, 0xF
    /* 27ABC3C 8006EEA0 03000224 */  addiu      $v0, $zero, 0x3
    /* 27ABC40 8006EEA4 0A006210 */  beq        $v1, $v0, .Llevel_34_8006EED0
    /* 27ABC44 8006EEA8 00000000 */   nop
    /* 27ABC48 8006EEAC 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 27ABC4C 8006EEB0 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 27ABC50 8006EEB4 00000000 */  nop
    /* 27ABC54 8006EEB8 05004010 */  beqz       $v0, .Llevel_34_8006EED0
    /* 27ABC58 8006EEBC 00000000 */   nop
  .Llevel_34_8006EEC0:
    /* 27ABC5C 8006EEC0 76D4000C */  jal        func_800351D8
    /* 27ABC60 8006EEC4 01000424 */   addiu     $a0, $zero, 0x1
    /* 27ABC64 8006EEC8 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABC68 8006EECC 00000000 */   nop
  .Llevel_34_8006EED0:
    /* 27ABC6C 8006EED0 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 27ABC70 8006EED4 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 27ABC74 8006EED8 07000224 */  addiu      $v0, $zero, 0x7
    /* 27ABC78 8006EEDC 06006210 */  beq        $v1, $v0, .Llevel_34_8006EEF8
    /* 27ABC7C 8006EEE0 00000000 */   nop
    /* 27ABC80 8006EEE4 0780023C */  lui        $v0, %hi(D_8006A230)
    /* 27ABC84 8006EEE8 30A2428C */  lw         $v0, %lo(D_8006A230)($v0)
    /* 27ABC88 8006EEEC 00000000 */  nop
    /* 27ABC8C 8006EEF0 26004010 */  beqz       $v0, .Llevel_34_8006EF8C
    /* 27ABC90 8006EEF4 00000000 */   nop
  .Llevel_34_8006EEF8:
    /* 27ABC94 8006EEF8 0780103C */  lui        $s0, %hi(D_8006A040)
    /* 27ABC98 8006EEFC 40A01026 */  addiu      $s0, $s0, %lo(D_8006A040)
    /* 27ABC9C 8006EF00 0000028E */  lw         $v0, 0x0($s0)
    /* 27ABCA0 8006EF04 00000000 */  nop
    /* 27ABCA4 8006EF08 0A014010 */  beqz       $v0, .Llevel_34_8006F334
    /* 27ABCA8 8006EF0C 00000000 */   nop
    /* 27ABCAC 8006EF10 76D4000C */  jal        func_800351D8
    /* 27ABCB0 8006EF14 21200000 */   addu      $a0, $zero, $zero
    /* 27ABCB4 8006EF18 CCFF0292 */  lbu        $v0, -0x34($s0)
    /* 27ABCB8 8006EF1C 0680013C */  lui        $at, %hi(D_80062868)
    /* 27ABCBC 8006EF20 21082200 */  addu       $at, $at, $v0
    /* 27ABCC0 8006EF24 68282290 */  lbu        $v0, %lo(D_80062868)($at)
    /* 27ABCC4 8006EF28 00000000 */  nop
    /* 27ABCC8 8006EF2C 6000422C */  sltiu      $v0, $v0, 0x60
    /* 27ABCCC 8006EF30 09004014 */  bnez       $v0, .Llevel_34_8006EF58
    /* 27ABCD0 8006EF34 00000000 */   nop
    /* 27ABCD4 8006EF38 0780023C */  lui        $v0, %hi(D_8006A005)
    /* 27ABCD8 8006EF3C 05A04290 */  lbu        $v0, %lo(D_8006A005)($v0)
    /* 27ABCDC 8006EF40 0780033C */  lui        $v1, %hi(D_8006A007)
    /* 27ABCE0 8006EF44 07A06390 */  lbu        $v1, %lo(D_8006A007)($v1)
    /* 27ABCE4 8006EF48 0780013C */  lui        $at, %hi(D_8006A004)
    /* 27ABCE8 8006EF4C 04A022A0 */  sb         $v0, %lo(D_8006A004)($at)
    /* 27ABCEC 8006EF50 0780013C */  lui        $at, %hi(D_8006A006)
    /* 27ABCF0 8006EF54 06A023A0 */  sb         $v1, %lo(D_8006A006)($at)
  .Llevel_34_8006EF58:
    /* 27ABCF4 8006EF58 0780013C */  lui        $at, %hi(D_8006A007)
    /* 27ABCF8 8006EF5C 07A020A0 */  sb         $zero, %lo(D_8006A007)($at)
    /* 27ABCFC 8006EF60 0000038E */  lw         $v1, 0x0($s0)
    /* 27ABD00 8006EF64 71000224 */  addiu      $v0, $zero, 0x71
    /* 27ABD04 8006EF68 CCFF02A2 */  sb         $v0, -0x34($s0)
    /* 27ABD08 8006EF6C 0780013C */  lui        $at, %hi(D_8006A1E0)
    /* 27ABD0C 8006EF70 E0A120AC */  sw         $zero, %lo(D_8006A1E0)($at)
    /* 27ABD10 8006EF74 0780013C */  lui        $at, %hi(D_8006A005)
    /* 27ABD14 8006EF78 05A023A0 */  sb         $v1, %lo(D_8006A005)($at)
    /* 27ABD18 8006EF7C 0780013C */  lui        $at, %hi(D_8006A1DC)
    /* 27ABD1C 8006EF80 DCA123AC */  sw         $v1, %lo(D_8006A1DC)($at)
    /* 27ABD20 8006EF84 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABD24 8006EF88 00000000 */   nop
  .Llevel_34_8006EF8C:
    /* 27ABD28 8006EF8C 0780023C */  lui        $v0, %hi(D_8006A0F4)
    /* 27ABD2C 8006EF90 F4A04290 */  lbu        $v0, %lo(D_8006A0F4)($v0)
    /* 27ABD30 8006EF94 00000000 */  nop
    /* 27ABD34 8006EF98 05004010 */  beqz       $v0, .Llevel_34_8006EFB0
    /* 27ABD38 8006EF9C 00000000 */   nop
    /* 27ABD3C 8006EFA0 76D4000C */  jal        func_800351D8
    /* 27ABD40 8006EFA4 0E000424 */   addiu     $a0, $zero, 0xE
    /* 27ABD44 8006EFA8 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABD48 8006EFAC 00000000 */   nop
  .Llevel_34_8006EFB0:
    /* 27ABD4C 8006EFB0 0DCB000C */  jal        func_80032C34
    /* 27ABD50 8006EFB4 00000000 */   nop
    /* 27ABD54 8006EFB8 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABD58 8006EFBC 00000000 */   nop
  .Llevel_34_8006EFC0:
    /* 27ABD5C 8006EFC0 2EAC000C */  jal        func_8002B0B8
    /* 27ABD60 8006EFC4 00000000 */   nop
    /* 27ABD64 8006EFC8 CE004010 */  beqz       $v0, .Llevel_34_8006F304
    /* 27ABD68 8006EFCC 00000000 */   nop
    /* 27ABD6C 8006EFD0 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABD70 8006EFD4 00000000 */   nop
  .Llevel_34_8006EFD8:
    /* 27ABD74 8006EFD8 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 27ABD78 8006EFDC 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 27ABD7C 8006EFE0 00000000 */  nop
    /* 27ABD80 8006EFE4 19004228 */  slti       $v0, $v0, 0x19
    /* 27ABD84 8006EFE8 D2004014 */  bnez       $v0, .Llevel_34_8006F334
    /* 27ABD88 8006EFEC 00000000 */   nop
    /* 27ABD8C 8006EFF0 0780023C */  lui        $v0, %hi(D_8006A248)
    /* 27ABD90 8006EFF4 48A2428C */  lw         $v0, %lo(D_8006A248)($v0)
    /* 27ABD94 8006EFF8 00000000 */  nop
    /* 27ABD98 8006EFFC A4004004 */  bltz       $v0, .Llevel_34_8006F290
    /* 27ABD9C 8006F000 0A000224 */   addiu     $v0, $zero, 0xA
    /* 27ABDA0 8006F004 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 27ABDA4 8006F008 3CA1638C */  lw         $v1, %lo(D_8006A13C)($v1)
    /* 27ABDA8 8006F00C 00000000 */  nop
    /* 27ABDAC 8006F010 A8006210 */  beq        $v1, $v0, .Llevel_34_8006F2B4
    /* 27ABDB0 8006F014 F5FF6224 */   addiu     $v0, $v1, -0xB
    /* 27ABDB4 8006F018 0200422C */  sltiu      $v0, $v0, 0x2
    /* 27ABDB8 8006F01C AC004014 */  bnez       $v0, .Llevel_34_8006F2D0
    /* 27ABDBC 8006F020 00000000 */   nop
    /* 27ABDC0 8006F024 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 27ABDC4 8006F028 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 27ABDC8 8006F02C 00000000 */  nop
    /* 27ABDCC 8006F030 B4004010 */  beqz       $v0, .Llevel_34_8006F304
    /* 27ABDD0 8006F034 00000000 */   nop
    /* 27ABDD4 8006F038 BDBC0108 */  j          .Llevel_34_8006F2F4
    /* 27ABDD8 8006F03C 00000000 */   nop
  .Llevel_34_8006F040:
    /* 27ABDDC 8006F040 2EAC000C */  jal        func_8002B0B8
    /* 27ABDE0 8006F044 00000000 */   nop
    /* 27ABDE4 8006F048 BA004014 */  bnez       $v0, .Llevel_34_8006F334
    /* 27ABDE8 8006F04C 00000000 */   nop
    /* 27ABDEC 8006F050 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 27ABDF0 8006F054 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 27ABDF4 8006F058 0780043C */  lui        $a0, %hi(D_80069FF0)
    /* 27ABDF8 8006F05C F09F8424 */  addiu      $a0, $a0, %lo(D_80069FF0)
    /* 27ABDFC 8006F060 DB6F000C */  jal        func_8001BF6C
    /* 27ABE00 8006F064 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 27ABE04 8006F068 0780033C */  lui        $v1, %hi(D_8006A150)
    /* 27ABE08 8006F06C 50A1638C */  lw         $v1, %lo(D_8006A150)($v1)
    /* 27ABE0C 8006F070 00000000 */  nop
    /* 27ABE10 8006F074 2A186200 */  slt        $v1, $v1, $v0
    /* 27ABE14 8006F078 AE006010 */  beqz       $v1, .Llevel_34_8006F334
    /* 27ABE18 8006F07C 00000000 */   nop
    /* 27ABE1C 8006F080 76D4000C */  jal        func_800351D8
    /* 27ABE20 8006F084 10000424 */   addiu     $a0, $zero, 0x10
    /* 27ABE24 8006F088 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABE28 8006F08C 00000000 */   nop
  .Llevel_34_8006F090:
    /* 27ABE2C 8006F090 2EAC000C */  jal        func_8002B0B8
    /* 27ABE30 8006F094 00000000 */   nop
    /* 27ABE34 8006F098 A6004014 */  bnez       $v0, .Llevel_34_8006F334
    /* 27ABE38 8006F09C 00000000 */   nop
    /* 27ABE3C 8006F0A0 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 27ABE40 8006F0A4 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 27ABE44 8006F0A8 00000000 */  nop
    /* 27ABE48 8006F0AC 40004230 */  andi       $v0, $v0, 0x40
    /* 27ABE4C 8006F0B0 09004010 */  beqz       $v0, .Llevel_34_8006F0D8
    /* 27ABE50 8006F0B4 00000000 */   nop
  .Llevel_34_8006F0B8:
    /* 27ABE54 8006F0B8 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 27ABE58 8006F0BC A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 27ABE5C 8006F0C0 00000000 */  nop
    /* 27ABE60 8006F0C4 00404230 */  andi       $v0, $v0, 0x4000
    /* 27ABE64 8006F0C8 4B004010 */  beqz       $v0, .Llevel_34_8006F1F8
    /* 27ABE68 8006F0CC 00000000 */   nop
    /* 27ABE6C 8006F0D0 77BC0108 */  j          .Llevel_34_8006F1DC
    /* 27ABE70 8006F0D4 00000000 */   nop
  .Llevel_34_8006F0D8:
    /* 27ABE74 8006F0D8 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 27ABE78 8006F0DC A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 27ABE7C 8006F0E0 00000000 */  nop
    /* 27ABE80 8006F0E4 93004010 */  beqz       $v0, .Llevel_34_8006F334
    /* 27ABE84 8006F0E8 00000000 */   nop
    /* 27ABE88 8006F0EC 95BC0108 */  j          .Llevel_34_8006F254
    /* 27ABE8C 8006F0F0 00000000 */   nop
  .Llevel_34_8006F0F4:
    /* 27ABE90 8006F0F4 2EAC000C */  jal        func_8002B0B8
    /* 27ABE94 8006F0F8 00000000 */   nop
    /* 27ABE98 8006F0FC 8D004014 */  bnez       $v0, .Llevel_34_8006F334
    /* 27ABE9C 8006F100 00000000 */   nop
    /* 27ABEA0 8006F104 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 27ABEA4 8006F108 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 27ABEA8 8006F10C 00000000 */  nop
    /* 27ABEAC 8006F110 40004230 */  andi       $v0, $v0, 0x40
    /* 27ABEB0 8006F114 E8FF4014 */  bnez       $v0, .Llevel_34_8006F0B8
    /* 27ABEB4 8006F118 00000000 */   nop
    /* 27ABEB8 8006F11C 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 27ABEBC 8006F120 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 27ABEC0 8006F124 00000000 */  nop
    /* 27ABEC4 8006F128 3C004010 */  beqz       $v0, .Llevel_34_8006F21C
    /* 27ABEC8 8006F12C 00000000 */   nop
    /* 27ABECC 8006F130 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 27ABED0 8006F134 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 27ABED4 8006F138 0780033C */  lui        $v1, %hi(D_8006A0AC)
    /* 27ABED8 8006F13C ACA0638C */  lw         $v1, %lo(D_8006A0AC)($v1)
    /* 27ABEDC 8006F140 02004104 */  bgez       $v0, .Llevel_34_8006F14C
    /* 27ABEE0 8006F144 00000000 */   nop
    /* 27ABEE4 8006F148 23100200 */  negu       $v0, $v0
  .Llevel_34_8006F14C:
    /* 27ABEE8 8006F14C 2A104300 */  slt        $v0, $v0, $v1
    /* 27ABEEC 8006F150 78004010 */  beqz       $v0, .Llevel_34_8006F334
    /* 27ABEF0 8006F154 00000000 */   nop
    /* 27ABEF4 8006F158 0780023C */  lui        $v0, %hi(D_8006A09C)
    /* 27ABEF8 8006F15C 9CA0428C */  lw         $v0, %lo(D_8006A09C)($v0)
    /* 27ABEFC 8006F160 00000000 */  nop
    /* 27ABF00 8006F164 02004104 */  bgez       $v0, .Llevel_34_8006F170
    /* 27ABF04 8006F168 00000000 */   nop
    /* 27ABF08 8006F16C 23100200 */  negu       $v0, $v0
  .Llevel_34_8006F170:
    /* 27ABF0C 8006F170 00044228 */  slti       $v0, $v0, 0x400
    /* 27ABF10 8006F174 05004010 */  beqz       $v0, .Llevel_34_8006F18C
    /* 27ABF14 8006F178 00000000 */   nop
    /* 27ABF18 8006F17C 76D4000C */  jal        func_800351D8
    /* 27ABF1C 8006F180 33000424 */   addiu     $a0, $zero, 0x33
    /* 27ABF20 8006F184 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABF24 8006F188 00000000 */   nop
  .Llevel_34_8006F18C:
    /* 27ABF28 8006F18C 76D4000C */  jal        func_800351D8
    /* 27ABF2C 8006F190 34000424 */   addiu     $a0, $zero, 0x34
    /* 27ABF30 8006F194 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABF34 8006F198 00000000 */   nop
  .Llevel_34_8006F19C:
    /* 27ABF38 8006F19C 2EAC000C */  jal        func_8002B0B8
    /* 27ABF3C 8006F1A0 00000000 */   nop
    /* 27ABF40 8006F1A4 63004014 */  bnez       $v0, .Llevel_34_8006F334
    /* 27ABF44 8006F1A8 00000000 */   nop
    /* 27ABF48 8006F1AC 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 27ABF4C 8006F1B0 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 27ABF50 8006F1B4 00000000 */  nop
    /* 27ABF54 8006F1B8 40004230 */  andi       $v0, $v0, 0x40
    /* 27ABF58 8006F1BC 12004010 */  beqz       $v0, .Llevel_34_8006F208
    /* 27ABF5C 8006F1C0 00000000 */   nop
    /* 27ABF60 8006F1C4 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 27ABF64 8006F1C8 A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 27ABF68 8006F1CC 00000000 */  nop
    /* 27ABF6C 8006F1D0 00404230 */  andi       $v0, $v0, 0x4000
    /* 27ABF70 8006F1D4 08004010 */  beqz       $v0, .Llevel_34_8006F1F8
    /* 27ABF74 8006F1D8 00000000 */   nop
  .Llevel_34_8006F1DC:
    /* 27ABF78 8006F1DC 76D4000C */  jal        func_800351D8
    /* 27ABF7C 8006F1E0 06000424 */   addiu     $a0, $zero, 0x6
    /* 27ABF80 8006F1E4 03000224 */  addiu      $v0, $zero, 0x3
    /* 27ABF84 8006F1E8 0780013C */  lui        $at, %hi(D_8006A044)
    /* 27ABF88 8006F1EC 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 27ABF8C 8006F1F0 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABF90 8006F1F4 00000000 */   nop
  .Llevel_34_8006F1F8:
    /* 27ABF94 8006F1F8 76D4000C */  jal        func_800351D8
    /* 27ABF98 8006F1FC 05000424 */   addiu     $a0, $zero, 0x5
    /* 27ABF9C 8006F200 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABFA0 8006F204 00000000 */   nop
  .Llevel_34_8006F208:
    /* 27ABFA4 8006F208 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 27ABFA8 8006F20C A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 27ABFAC 8006F210 00000000 */  nop
    /* 27ABFB0 8006F214 05004014 */  bnez       $v0, .Llevel_34_8006F22C
    /* 27ABFB4 8006F218 00000000 */   nop
  .Llevel_34_8006F21C:
    /* 27ABFB8 8006F21C 76D4000C */  jal        func_800351D8
    /* 27ABFBC 8006F220 2F000424 */   addiu     $a0, $zero, 0x2F
    /* 27ABFC0 8006F224 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABFC4 8006F228 00000000 */   nop
  .Llevel_34_8006F22C:
    /* 27ABFC8 8006F22C 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 27ABFCC 8006F230 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 27ABFD0 8006F234 0780033C */  lui        $v1, %hi(D_8006A0AC)
    /* 27ABFD4 8006F238 ACA0638C */  lw         $v1, %lo(D_8006A0AC)($v1)
    /* 27ABFD8 8006F23C 02004104 */  bgez       $v0, .Llevel_34_8006F248
    /* 27ABFDC 8006F240 00000000 */   nop
    /* 27ABFE0 8006F244 23100200 */  negu       $v0, $v0
  .Llevel_34_8006F248:
    /* 27ABFE4 8006F248 2A104300 */  slt        $v0, $v0, $v1
    /* 27ABFE8 8006F24C 39004014 */  bnez       $v0, .Llevel_34_8006F334
    /* 27ABFEC 8006F250 00000000 */   nop
  .Llevel_34_8006F254:
    /* 27ABFF0 8006F254 76D4000C */  jal        func_800351D8
    /* 27ABFF4 8006F258 32000424 */   addiu     $a0, $zero, 0x32
    /* 27ABFF8 8006F25C CDBC0108 */  j          .Llevel_34_8006F334
    /* 27ABFFC 8006F260 00000000 */   nop
  .Llevel_34_8006F264:
    /* 27AC000 8006F264 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 27AC004 8006F268 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 27AC008 8006F26C 00000000 */  nop
    /* 27AC00C 8006F270 19004228 */  slti       $v0, $v0, 0x19
    /* 27AC010 8006F274 2F004014 */  bnez       $v0, .Llevel_34_8006F334
    /* 27AC014 8006F278 00000000 */   nop
    /* 27AC018 8006F27C 0780023C */  lui        $v0, %hi(D_8006A248)
    /* 27AC01C 8006F280 48A2428C */  lw         $v0, %lo(D_8006A248)($v0)
    /* 27AC020 8006F284 00000000 */  nop
    /* 27AC024 8006F288 05004104 */  bgez       $v0, .Llevel_34_8006F2A0
    /* 27AC028 8006F28C 0A000224 */   addiu     $v0, $zero, 0xA
  .Llevel_34_8006F290:
    /* 27AC02C 8006F290 76D4000C */  jal        func_800351D8
    /* 27AC030 8006F294 1F000424 */   addiu     $a0, $zero, 0x1F
    /* 27AC034 8006F298 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27AC038 8006F29C 00000000 */   nop
  .Llevel_34_8006F2A0:
    /* 27AC03C 8006F2A0 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 27AC040 8006F2A4 3CA1638C */  lw         $v1, %lo(D_8006A13C)($v1)
    /* 27AC044 8006F2A8 00000000 */  nop
    /* 27AC048 8006F2AC 05006214 */  bne        $v1, $v0, .Llevel_34_8006F2C4
    /* 27AC04C 8006F2B0 F5FF6224 */   addiu     $v0, $v1, -0xB
  .Llevel_34_8006F2B4:
    /* 27AC050 8006F2B4 76D4000C */  jal        func_800351D8
    /* 27AC054 8006F2B8 2C000424 */   addiu     $a0, $zero, 0x2C
    /* 27AC058 8006F2BC CDBC0108 */  j          .Llevel_34_8006F334
    /* 27AC05C 8006F2C0 00000000 */   nop
  .Llevel_34_8006F2C4:
    /* 27AC060 8006F2C4 0200422C */  sltiu      $v0, $v0, 0x2
    /* 27AC064 8006F2C8 05004010 */  beqz       $v0, .Llevel_34_8006F2E0
    /* 27AC068 8006F2CC 00000000 */   nop
  .Llevel_34_8006F2D0:
    /* 27AC06C 8006F2D0 76D4000C */  jal        func_800351D8
    /* 27AC070 8006F2D4 29000424 */   addiu     $a0, $zero, 0x29
    /* 27AC074 8006F2D8 CDBC0108 */  j          .Llevel_34_8006F334
    /* 27AC078 8006F2DC 00000000 */   nop
  .Llevel_34_8006F2E0:
    /* 27AC07C 8006F2E0 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 27AC080 8006F2E4 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 27AC084 8006F2E8 00000000 */  nop
    /* 27AC088 8006F2EC 05004010 */  beqz       $v0, .Llevel_34_8006F304
    /* 27AC08C 8006F2F0 00000000 */   nop
  .Llevel_34_8006F2F4:
    /* 27AC090 8006F2F4 76D4000C */  jal        func_800351D8
    /* 27AC094 8006F2F8 06000424 */   addiu     $a0, $zero, 0x6
    /* 27AC098 8006F2FC CDBC0108 */  j          .Llevel_34_8006F334
    /* 27AC09C 8006F300 00000000 */   nop
  .Llevel_34_8006F304:
    /* 27AC0A0 8006F304 76D4000C */  jal        func_800351D8
    /* 27AC0A4 8006F308 21200000 */   addu      $a0, $zero, $zero
    /* 27AC0A8 8006F30C CDBC0108 */  j          .Llevel_34_8006F334
    /* 27AC0AC 8006F310 00000000 */   nop
  .Llevel_34_8006F314:
    /* 27AC0B0 8006F314 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 27AC0B4 8006F318 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 27AC0B8 8006F31C 00000000 */  nop
    /* 27AC0BC 8006F320 63004228 */  slti       $v0, $v0, 0x63
    /* 27AC0C0 8006F324 03004014 */  bnez       $v0, .Llevel_34_8006F334
    /* 27AC0C4 8006F328 00000000 */   nop
    /* 27AC0C8 8006F32C 9DCB000C */  jal        func_80032E74
    /* 27AC0CC 8006F330 00000000 */   nop
  .Llevel_34_8006F334:
    /* 27AC0D0 8006F334 1400BF8F */  lw         $ra, 0x14($sp)
    /* 27AC0D4 8006F338 1000B08F */  lw         $s0, 0x10($sp)
    /* 27AC0D8 8006F33C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 27AC0DC 8006F340 0800E003 */  jr         $ra
    /* 27AC0E0 8006F344 00000000 */   nop
endlabel func_level_34_8006ED80
