.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_34_8006D268

dlabel jtbl_level_34_8006D268
    /* 27AA004 8006D268 F8DB0680 */ .word .Llevel_34_8006DBF8
    /* 27AA008 8006D26C A8DB0680 */ .word .Llevel_34_8006DBA8
    /* 27AA00C 8006D270 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA010 8006D274 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA014 8006D278 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA018 8006D27C E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA01C 8006D280 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA020 8006D284 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA024 8006D288 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA028 8006D28C E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA02C 8006D290 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA030 8006D294 0CDF0680 */ .word .Llevel_34_8006DF0C
    /* 27AA034 8006D298 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA038 8006D29C E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA03C 8006D2A0 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA040 8006D2A4 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA044 8006D2A8 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA048 8006D2AC E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA04C 8006D2B0 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA050 8006D2B4 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA054 8006D2B8 A8DB0680 */ .word .Llevel_34_8006DBA8
    /* 27AA058 8006D2BC E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA05C 8006D2C0 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA060 8006D2C4 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA064 8006D2C8 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA068 8006D2CC E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA06C 8006D2D0 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA070 8006D2D4 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA074 8006D2D8 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA078 8006D2DC 80E10680 */ .word .Llevel_34_8006E180
    /* 27AA07C 8006D2E0 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA080 8006D2E4 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA084 8006D2E8 A0E20680 */ .word .Llevel_34_8006E2A0
    /* 27AA088 8006D2EC A0E20680 */ .word .Llevel_34_8006E2A0
    /* 27AA08C 8006D2F0 A0E20680 */ .word .Llevel_34_8006E2A0
    /* 27AA090 8006D2F4 A8DB0680 */ .word .Llevel_34_8006DBA8
    /* 27AA094 8006D2F8 A8DB0680 */ .word .Llevel_34_8006DBA8
    /* 27AA098 8006D2FC E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA09C 8006D300 34E40680 */ .word .Llevel_34_8006E434
    /* 27AA0A0 8006D304 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA0A4 8006D308 E0E40680 */ .word .Llevel_34_8006E4E0
    /* 27AA0A8 8006D30C ECDF0680 */ .word .Llevel_34_8006DFEC
enddlabel jtbl_level_34_8006D268


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_34_8006DB40, 0x9BC

glabel func_level_34_8006DB40
    /* 27AA8DC 8006DB40 00110400 */  sll        $v0, $a0, 4
    /* 27AA8E0 8006DB44 0780033C */  lui        $v1, %hi(D_800683B0)
    /* 27AA8E4 8006DB48 B0836324 */  addiu      $v1, $v1, %lo(D_800683B0)
    /* 27AA8E8 8006DB4C 21104300 */  addu       $v0, $v0, $v1
    /* 27AA8EC 8006DB50 0680013C */  lui        $at, %hi(D_80066F38)
    /* 27AA8F0 8006DB54 386F22AC */  sw         $v0, %lo(D_80066F38)($at)
    /* 27AA8F4 8006DB58 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 27AA8F8 8006DB5C 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 27AA8FC 8006DB60 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 27AA900 8006DB64 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 27AA904 8006DB68 78FFBD27 */  addiu      $sp, $sp, -0x88
    /* 27AA908 8006DB6C 8400BFAF */  sw         $ra, 0x84($sp)
    /* 27AA90C 8006DB70 8000B2AF */  sw         $s2, 0x80($sp)
    /* 27AA910 8006DB74 7C00B1AF */  sw         $s1, 0x7C($sp)
    /* 27AA914 8006DB78 21204400 */  addu       $a0, $v0, $a0
    /* 27AA918 8006DB7C EEFF6324 */  addiu      $v1, $v1, -0x12
    /* 27AA91C 8006DB80 2A00622C */  sltiu      $v0, $v1, 0x2A
    /* 27AA920 8006DB84 56024010 */  beqz       $v0, .Llevel_34_8006E4E0
    /* 27AA924 8006DB88 7800B0AF */   sw        $s0, 0x78($sp)
    /* 27AA928 8006DB8C 80100300 */  sll        $v0, $v1, 2
    /* 27AA92C 8006DB90 0780013C */  lui        $at, %hi(jtbl_level_34_8006D268)
    /* 27AA930 8006DB94 21082200 */  addu       $at, $at, $v0
    /* 27AA934 8006DB98 68D2228C */  lw         $v0, %lo(jtbl_level_34_8006D268)($at)
    /* 27AA938 8006DB9C 00000000 */  nop
    /* 27AA93C 8006DBA0 08004000 */  jr         $v0
    /* 27AA940 8006DBA4 00000000 */   nop
  .Llevel_34_8006DBA8:
    /* 27AA944 8006DBA8 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 27AA948 8006DBAC 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 27AA94C 8006DBB0 686F000C */  jal        func_8001BDA0
    /* 27AA950 8006DBB4 21200002 */   addu      $a0, $s0, $zero
    /* 27AA954 8006DBB8 686F000C */  jal        func_8001BDA0
    /* 27AA958 8006DBBC 0C000426 */   addiu     $a0, $s0, 0xC
    /* 27AA95C 8006DBC0 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 27AA960 8006DBC4 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 27AA964 8006DBC8 07000224 */  addiu      $v0, $zero, 0x7
    /* 27AA968 8006DBCC 44026210 */  beq        $v1, $v0, .Llevel_34_8006E4E0
    /* 27AA96C 8006DBD0 00000000 */   nop
    /* 27AA970 8006DBD4 DBAC000C */  jal        func_8002B36C
    /* 27AA974 8006DBD8 00120424 */   addiu     $a0, $zero, 0x1200
    /* 27AA978 8006DBDC 1AAF000C */  jal        func_8002BC68
    /* 27AA97C 8006DBE0 00000000 */   nop
    /* 27AA980 8006DBE4 5A000424 */  addiu      $a0, $zero, 0x5A
    /* 27AA984 8006DBE8 C9AE000C */  jal        func_8002BB24
    /* 27AA988 8006DBEC 10000524 */   addiu     $a1, $zero, 0x10
    /* 27AA98C 8006DBF0 38B90108 */  j          .Llevel_34_8006E4E0
    /* 27AA990 8006DBF4 00000000 */   nop
  .Llevel_34_8006DBF8:
    /* 27AA994 8006DBF8 0780113C */  lui        $s1, %hi(D_80069FF8)
    /* 27AA998 8006DBFC F89F3126 */  addiu      $s1, $s1, %lo(D_80069FF8)
    /* 27AA99C 8006DC00 0000238E */  lw         $v1, 0x0($s1)
    /* 27AA9A0 8006DC04 4401228E */  lw         $v0, 0x144($s1)
    /* 27AA9A4 8006DC08 00000000 */  nop
    /* 27AA9A8 8006DC0C 23206200 */  subu       $a0, $v1, $v0
    /* 27AA9AC 8006DC10 00048228 */  slti       $v0, $a0, 0x400
    /* 27AA9B0 8006DC14 28004010 */  beqz       $v0, .Llevel_34_8006DCB8
    /* 27AA9B4 8006DC18 00000000 */   nop
    /* 27AA9B8 8006DC1C 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 27AA9BC 8006DC20 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 27AA9C0 8006DC24 00000000 */  nop
    /* 27AA9C4 8006DC28 80004224 */  addiu      $v0, $v0, 0x80
    /* 27AA9C8 8006DC2C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 27AA9CC 8006DC30 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 27AA9D0 8006DC34 C1124228 */  slti       $v0, $v0, 0x12C1
    /* 27AA9D4 8006DC38 04004014 */  bnez       $v0, .Llevel_34_8006DC4C
    /* 27AA9D8 8006DC3C 18008400 */   mult      $a0, $a0
    /* 27AA9DC 8006DC40 C0120224 */  addiu      $v0, $zero, 0x12C0
    /* 27AA9E0 8006DC44 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 27AA9E4 8006DC48 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_34_8006DC4C:
    /* 27AA9E8 8006DC4C 1000A427 */  addiu      $a0, $sp, 0x10
    /* 27AA9EC 8006DC50 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 27AA9F0 8006DC54 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 27AA9F4 8006DC58 0780033C */  lui        $v1, %hi(D_8006A140)
    /* 27AA9F8 8006DC5C 40A1638C */  lw         $v1, %lo(D_8006A140)($v1)
    /* 27AA9FC 8006DC60 12480000 */  mflo       $t1
    /* 27AAA00 8006DC64 C3120900 */  sra        $v0, $t1, 11
    /* 27AAA04 8006DC68 21804300 */  addu       $s0, $v0, $v1
    /* 27AAA08 8006DC6C 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 27AAA0C 8006DC70 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 27AAA10 8006DC74 6C6F000C */  jal        func_8001BDB0
    /* 27AAA14 8006DC78 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 27AAA18 8006DC7C 1000A427 */  addiu      $a0, $sp, 0x10
    /* 27AAA1C 8006DC80 21288000 */  addu       $a1, $a0, $zero
    /* 27AAA20 8006DC84 806F000C */  jal        func_8001BE00
    /* 27AAA24 8006DC88 F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 27AAA28 8006DC8C 1000A427 */  addiu      $a0, $sp, 0x10
    /* 27AAA2C 8006DC90 21280000 */  addu       $a1, $zero, $zero
    /* 27AAA30 8006DC94 886E000C */  jal        func_8001BA20
    /* 27AAA34 8006DC98 1800A0AF */   sw        $zero, 0x18($sp)
    /* 27AAA38 8006DC9C 21404000 */  addu       $t0, $v0, $zero
    /* 27AAA3C 8006DCA0 01040229 */  slti       $v0, $t0, 0x401
    /* 27AAA40 8006DCA4 91004014 */  bnez       $v0, .Llevel_34_8006DEEC
    /* 27AAA44 8006DCA8 1000A427 */   addiu     $a0, $sp, 0x10
    /* 27AAA48 8006DCAC 21280001 */  addu       $a1, $t0, $zero
    /* 27AAA4C 8006DCB0 B9B70108 */  j          .Llevel_34_8006DEE4
    /* 27AAA50 8006DCB4 00040624 */   addiu     $a2, $zero, 0x400
  .Llevel_34_8006DCB8:
    /* 27AAA54 8006DCB8 0780053C */  lui        $a1, %hi(D_8006A144)
    /* 27AAA58 8006DCBC 44A1A58C */  lw         $a1, %lo(D_8006A144)($a1)
    /* 27AAA5C 8006DCC0 00000000 */  nop
    /* 27AAA60 8006DCC4 23106500 */  subu       $v0, $v1, $a1
    /* 27AAA64 8006DCC8 00FC4228 */  slti       $v0, $v0, -0x400
    /* 27AAA68 8006DCCC 49004010 */  beqz       $v0, .Llevel_34_8006DDF4
    /* 27AAA6C 8006DCD0 2340A300 */   subu      $t0, $a1, $v1
    /* 27AAA70 8006DCD4 0780023C */  lui        $v0, %hi(D_8006A044)
    /* 27AAA74 8006DCD8 44A0428C */  lw         $v0, %lo(D_8006A044)($v0)
    /* 27AAA78 8006DCDC 00000000 */  nop
    /* 27AAA7C 8006DCE0 08004014 */  bnez       $v0, .Llevel_34_8006DD04
    /* 27AAA80 8006DCE4 01000324 */   addiu     $v1, $zero, 0x1
    /* 27AAA84 8006DCE8 0780023C */  lui        $v0, %hi(D_8006A140)
    /* 27AAA88 8006DCEC 40A1428C */  lw         $v0, %lo(D_8006A140)($v0)
    /* 27AAA8C 8006DCF0 0780013C */  lui        $at, %hi(D_8006A044)
    /* 27AAA90 8006DCF4 44A023AC */  sw         $v1, %lo(D_8006A044)($at)
    /* 27AAA94 8006DCF8 00024224 */  addiu      $v0, $v0, 0x200
    /* 27AAA98 8006DCFC 0780013C */  lui        $at, %hi(D_8006A140)
    /* 27AAA9C 8006DD00 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
  .Llevel_34_8006DD04:
    /* 27AAAA0 8006DD04 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 27AAAA4 8006DD08 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 27AAAA8 8006DD0C 00000000 */  nop
    /* 27AAAAC 8006DD10 80004224 */  addiu      $v0, $v0, 0x80
    /* 27AAAB0 8006DD14 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 27AAAB4 8006DD18 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 27AAAB8 8006DD1C C1124228 */  slti       $v0, $v0, 0x12C1
    /* 27AAABC 8006DD20 03004014 */  bnez       $v0, .Llevel_34_8006DD30
    /* 27AAAC0 8006DD24 C0120224 */   addiu     $v0, $zero, 0x12C0
    /* 27AAAC4 8006DD28 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 27AAAC8 8006DD2C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_34_8006DD30:
    /* 27AAACC 8006DD30 0780023C */  lui        $v0, %hi(D_8006A148)
    /* 27AAAD0 8006DD34 48A1428C */  lw         $v0, %lo(D_8006A148)($v0)
    /* 27AAAD4 8006DD38 00FC8824 */  addiu      $t0, $a0, -0x400
    /* 27AAAD8 8006DD3C 18004800 */  mult       $v0, $t0
    /* 27AAADC 8006DD40 12180000 */  mflo       $v1
    /* 27AAAE0 8006DD44 0780023C */  lui        $v0, %hi(D_8006A14C)
    /* 27AAAE4 8006DD48 4CA1428C */  lw         $v0, %lo(D_8006A14C)($v0)
    /* 27AAAE8 8006DD4C 00000000 */  nop
    /* 27AAAEC 8006DD50 1A006200 */  div        $zero, $v1, $v0
    /* 27AAAF0 8006DD54 02004014 */  bnez       $v0, .Llevel_34_8006DD60
    /* 27AAAF4 8006DD58 00000000 */   nop
    /* 27AAAF8 8006DD5C 0D000700 */  break      7
  .Llevel_34_8006DD60:
    /* 27AAAFC 8006DD60 FFFF0124 */  addiu      $at, $zero, -0x1
    /* 27AAB00 8006DD64 04004114 */  bne        $v0, $at, .Llevel_34_8006DD78
    /* 27AAB04 8006DD68 0080013C */   lui       $at, (0x80000000 >> 16)
    /* 27AAB08 8006DD6C 02006114 */  bne        $v1, $at, .Llevel_34_8006DD78
    /* 27AAB0C 8006DD70 00000000 */   nop
    /* 27AAB10 8006DD74 0D000600 */  break      6
  .Llevel_34_8006DD78:
    /* 27AAB14 8006DD78 12100000 */  mflo       $v0
    /* 27AAB18 8006DD7C 1000A427 */  addiu      $a0, $sp, 0x10
    /* 27AAB1C 8006DD80 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 27AAB20 8006DD84 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 27AAB24 8006DD88 0780033C */  lui        $v1, %hi(D_8006A140)
    /* 27AAB28 8006DD8C 40A1638C */  lw         $v1, %lo(D_8006A140)($v1)
    /* 27AAB2C 8006DD90 00000000 */  nop
    /* 27AAB30 8006DD94 21806200 */  addu       $s0, $v1, $v0
    /* 27AAB34 8006DD98 80120800 */  sll        $v0, $t0, 10
    /* 27AAB38 8006DD9C 83120200 */  sra        $v0, $v0, 10
    /* 27AAB3C 8006DDA0 21100202 */  addu       $v0, $s0, $v0
    /* 27AAB40 8006DDA4 FF0F5030 */  andi       $s0, $v0, 0xFFF
    /* 27AAB44 8006DDA8 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 27AAB48 8006DDAC 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 27AAB4C 8006DDB0 6C6F000C */  jal        func_8001BDB0
    /* 27AAB50 8006DDB4 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 27AAB54 8006DDB8 1000A427 */  addiu      $a0, $sp, 0x10
    /* 27AAB58 8006DDBC 21288000 */  addu       $a1, $a0, $zero
    /* 27AAB5C 8006DDC0 806F000C */  jal        func_8001BE00
    /* 27AAB60 8006DDC4 F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 27AAB64 8006DDC8 1000A427 */  addiu      $a0, $sp, 0x10
    /* 27AAB68 8006DDCC 21280000 */  addu       $a1, $zero, $zero
    /* 27AAB6C 8006DDD0 886E000C */  jal        func_8001BA20
    /* 27AAB70 8006DDD4 1800A0AF */   sw        $zero, 0x18($sp)
    /* 27AAB74 8006DDD8 21404000 */  addu       $t0, $v0, $zero
    /* 27AAB78 8006DDDC 01040229 */  slti       $v0, $t0, 0x401
    /* 27AAB7C 8006DDE0 42004014 */  bnez       $v0, .Llevel_34_8006DEEC
    /* 27AAB80 8006DDE4 1000A427 */   addiu     $a0, $sp, 0x10
    /* 27AAB84 8006DDE8 21280001 */  addu       $a1, $t0, $zero
    /* 27AAB88 8006DDEC B9B70108 */  j          .Llevel_34_8006DEE4
    /* 27AAB8C 8006DDF0 00040624 */   addiu     $a2, $zero, 0x400
  .Llevel_34_8006DDF4:
    /* 27AAB90 8006DDF4 80180800 */  sll        $v1, $t0, 2
    /* 27AAB94 8006DDF8 21186800 */  addu       $v1, $v1, $t0
    /* 27AAB98 8006DDFC 00110300 */  sll        $v0, $v1, 4
    /* 27AAB9C 8006DE00 23104300 */  subu       $v0, $v0, $v1
    /* 27AABA0 8006DE04 80110200 */  sll        $v0, $v0, 6
    /* 27AABA4 8006DE08 0780063C */  lui        $a2, %hi(D_8006A208)
    /* 27AABA8 8006DE0C 08A2C68C */  lw         $a2, %lo(D_8006A208)($a2)
    /* 27AABAC 8006DE10 83120200 */  sra        $v0, $v0, 10
    /* 27AABB0 8006DE14 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 27AABB4 8006DE18 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 27AABB8 8006DE1C 4600C790 */  lbu        $a3, 0x46($a2)
    /* 27AABBC 8006DE20 0780033C */  lui        $v1, %hi(D_8006A150)
    /* 27AABC0 8006DE24 50A1638C */  lw         $v1, %lo(D_8006A150)($v1)
    /* 27AABC4 8006DE28 40100700 */  sll        $v0, $a3, 1
    /* 27AABC8 8006DE2C 0680013C */  lui        $at, %hi(D_80061C58)
    /* 27AABCC 8006DE30 21082200 */  addu       $at, $at, $v0
    /* 27AABD0 8006DE34 581C2284 */  lh         $v0, %lo(D_80061C58)($at)
    /* 27AABD4 8006DE38 00046324 */  addiu      $v1, $v1, 0x400
    /* 27AABD8 8006DE3C 18006200 */  mult       $v1, $v0
    /* 27AABDC 8006DE40 12500000 */  mflo       $t2
    /* 27AABE0 8006DE44 00000000 */  nop
    /* 27AABE4 8006DE48 00000000 */  nop
    /* 27AABE8 8006DE4C 18000801 */  mult       $t0, $t0
    /* 27AABEC 8006DE50 03130A00 */  sra        $v0, $t2, 12
    /* 27AABF0 8006DE54 1000A2AF */  sw         $v0, 0x10($sp)
    /* 27AABF4 8006DE58 4600C290 */  lbu        $v0, 0x46($a2)
    /* 27AABF8 8006DE5C 00000000 */  nop
    /* 27AABFC 8006DE60 40100200 */  sll        $v0, $v0, 1
    /* 27AAC00 8006DE64 12400000 */  mflo       $t0
    /* 27AAC04 8006DE68 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 27AAC08 8006DE6C 21082200 */  addu       $at, $at, $v0
    /* 27AAC0C 8006DE70 D81B2284 */  lh         $v0, %lo(D_80061BD8)($at)
    /* 27AAC10 8006DE74 00000000 */  nop
    /* 27AAC14 8006DE78 18006200 */  mult       $v1, $v0
    /* 27AAC18 8006DE7C 1000A427 */  addiu      $a0, $sp, 0x10
    /* 27AAC1C 8006DE80 21288000 */  addu       $a1, $a0, $zero
    /* 27AAC20 8006DE84 00390700 */  sll        $a3, $a3, 4
    /* 27AAC24 8006DE88 0C00C624 */  addiu      $a2, $a2, 0xC
    /* 27AAC28 8006DE8C C3120800 */  sra        $v0, $t0, 11
    /* 27AAC2C 8006DE90 2380E200 */  subu       $s0, $a3, $v0
    /* 27AAC30 8006DE94 12180000 */  mflo       $v1
    /* 27AAC34 8006DE98 03130300 */  sra        $v0, $v1, 12
    /* 27AAC38 8006DE9C 736F000C */  jal        func_8001BDCC
    /* 27AAC3C 8006DEA0 1400A2AF */   sw        $v0, 0x14($sp)
    /* 27AAC40 8006DEA4 1000A427 */  addiu      $a0, $sp, 0x10
    /* 27AAC44 8006DEA8 21288000 */  addu       $a1, $a0, $zero
    /* 27AAC48 8006DEAC 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 27AAC4C 8006DEB0 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 27AAC50 8006DEB4 806F000C */  jal        func_8001BE00
    /* 27AAC54 8006DEB8 F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 27AAC58 8006DEBC 1000A427 */  addiu      $a0, $sp, 0x10
    /* 27AAC5C 8006DEC0 21280000 */  addu       $a1, $zero, $zero
    /* 27AAC60 8006DEC4 886E000C */  jal        func_8001BA20
    /* 27AAC64 8006DEC8 1800A0AF */   sw        $zero, 0x18($sp)
    /* 27AAC68 8006DECC 21404000 */  addu       $t0, $v0, $zero
    /* 27AAC6C 8006DED0 01080229 */  slti       $v0, $t0, 0x801
    /* 27AAC70 8006DED4 05004014 */  bnez       $v0, .Llevel_34_8006DEEC
    /* 27AAC74 8006DED8 1000A427 */   addiu     $a0, $sp, 0x10
    /* 27AAC78 8006DEDC 21280001 */  addu       $a1, $t0, $zero
    /* 27AAC7C 8006DEE0 00080624 */  addiu      $a2, $zero, 0x800
  .Llevel_34_8006DEE4:
    /* 27AAC80 8006DEE4 316F000C */  jal        func_8001BCC4
    /* 27AAC84 8006DEE8 00000000 */   nop
  .Llevel_34_8006DEEC:
    /* 27AAC88 8006DEEC 1000A28F */  lw         $v0, 0x10($sp)
    /* 27AAC8C 8006DEF0 1400A38F */  lw         $v1, 0x14($sp)
    /* 27AAC90 8006DEF4 0780013C */  lui        $at, %hi(D_8006A084)
    /* 27AAC94 8006DEF8 84A022AC */  sw         $v0, %lo(D_8006A084)($at)
    /* 27AAC98 8006DEFC 0780013C */  lui        $at, %hi(D_8006A088)
    /* 27AAC9C 8006DF00 88A023AC */  sw         $v1, %lo(D_8006A088)($at)
    /* 27AACA0 8006DF04 38B90108 */  j          .Llevel_34_8006E4E0
    /* 27AACA4 8006DF08 00000000 */   nop
  .Llevel_34_8006DF0C:
    /* 27AACA8 8006DF0C 2000B027 */  addiu      $s0, $sp, 0x20
    /* 27AACAC 8006DF10 686F000C */  jal        func_8001BDA0
    /* 27AACB0 8006DF14 21200002 */   addu      $a0, $s0, $zero
    /* 27AACB4 8006DF18 21200002 */  addu       $a0, $s0, $zero
    /* 27AACB8 8006DF1C 21280002 */  addu       $a1, $s0, $zero
    /* 27AACBC 8006DF20 0780113C */  lui        $s1, %hi(D_8006A084)
    /* 27AACC0 8006DF24 84A03126 */  addiu      $s1, $s1, %lo(D_8006A084)
    /* 27AACC4 8006DF28 806F000C */  jal        func_8001BE00
    /* 27AACC8 8006DF2C 21302002 */   addu      $a2, $s1, $zero
    /* 27AACCC 8006DF30 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 27AACD0 8006DF34 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 27AACD4 8006DF38 00000000 */  nop
    /* 27AACD8 8006DF3C 11004010 */  beqz       $v0, .Llevel_34_8006DF84
    /* 27AACDC 8006DF40 21200002 */   addu      $a0, $s0, $zero
    /* 27AACE0 8006DF44 2800A0AF */  sw         $zero, 0x28($sp)
    /* 27AACE4 8006DF48 886E000C */  jal        func_8001BA20
    /* 27AACE8 8006DF4C 21280000 */   addu      $a1, $zero, $zero
    /* 27AACEC 8006DF50 21284000 */  addu       $a1, $v0, $zero
    /* 27AACF0 8006DF54 4100A228 */  slti       $v0, $a1, 0x41
    /* 27AACF4 8006DF58 05004014 */  bnez       $v0, .Llevel_34_8006DF70
    /* 27AACF8 8006DF5C 40FF0224 */   addiu     $v0, $zero, -0xC0
    /* 27AACFC 8006DF60 21200002 */  addu       $a0, $s0, $zero
    /* 27AAD00 8006DF64 316F000C */  jal        func_8001BCC4
    /* 27AAD04 8006DF68 40000624 */   addiu     $a2, $zero, 0x40
    /* 27AAD08 8006DF6C 40FF0224 */  addiu      $v0, $zero, -0xC0
  .Llevel_34_8006DF70:
    /* 27AAD0C 8006DF70 2800A2AF */  sw         $v0, 0x28($sp)
    /* 27AAD10 8006DF74 F4FF2426 */  addiu      $a0, $s1, -0xC
    /* 27AAD14 8006DF78 21282002 */  addu       $a1, $s1, $zero
    /* 27AAD18 8006DF7C F1B70108 */  j          .Llevel_34_8006DFC4
    /* 27AAD1C 8006DF80 21300002 */   addu      $a2, $s0, $zero
  .Llevel_34_8006DF84:
    /* 27AAD20 8006DF84 886E000C */  jal        func_8001BA20
    /* 27AAD24 8006DF88 01000524 */   addiu     $a1, $zero, 0x1
    /* 27AAD28 8006DF8C 21284000 */  addu       $a1, $v0, $zero
    /* 27AAD2C 8006DF90 0101A228 */  slti       $v0, $a1, 0x101
    /* 27AAD30 8006DF94 05004014 */  bnez       $v0, .Llevel_34_8006DFAC
    /* 27AAD34 8006DF98 21202002 */   addu      $a0, $s1, $zero
    /* 27AAD38 8006DF9C 21200002 */  addu       $a0, $s0, $zero
    /* 27AAD3C 8006DFA0 316F000C */  jal        func_8001BCC4
    /* 27AAD40 8006DFA4 00010624 */   addiu     $a2, $zero, 0x100
    /* 27AAD44 8006DFA8 21202002 */  addu       $a0, $s1, $zero
  .Llevel_34_8006DFAC:
    /* 27AAD48 8006DFAC 21282002 */  addu       $a1, $s1, $zero
    /* 27AAD4C 8006DFB0 736F000C */  jal        func_8001BDCC
    /* 27AAD50 8006DFB4 21300002 */   addu      $a2, $s0, $zero
    /* 27AAD54 8006DFB8 F4FF2426 */  addiu      $a0, $s1, -0xC
    /* 27AAD58 8006DFBC 21282002 */  addu       $a1, $s1, $zero
    /* 27AAD5C 8006DFC0 5C00A624 */  addiu      $a2, $a1, 0x5C
  .Llevel_34_8006DFC4:
    /* 27AAD60 8006DFC4 736F000C */  jal        func_8001BDCC
    /* 27AAD64 8006DFC8 00000000 */   nop
    /* 27AAD68 8006DFCC 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 27AAD6C 8006DFD0 84A08424 */  addiu      $a0, $a0, %lo(D_8006A084)
    /* 27AAD70 8006DFD4 6C6F000C */  jal        func_8001BDB0
    /* 27AAD74 8006DFD8 21288000 */   addu      $a1, $a0, $zero
    /* 27AAD78 8006DFDC 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 27AAD7C 8006DFE0 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 27AAD80 8006DFE4 34B90108 */  j          .Llevel_34_8006E4D0
    /* 27AAD84 8006DFE8 00DD4228 */   slti      $v0, $v0, -0x2300
  .Llevel_34_8006DFEC:
    /* 27AAD88 8006DFEC 0780103C */  lui        $s0, %hi(D_8006A0B0)
    /* 27AAD8C 8006DFF0 B0A01026 */  addiu      $s0, $s0, %lo(D_8006A0B0)
    /* 27AAD90 8006DFF4 0000028E */  lw         $v0, 0x0($s0)
    /* 27AAD94 8006DFF8 00000000 */  nop
    /* 27AAD98 8006DFFC 1F004010 */  beqz       $v0, .Llevel_34_8006E07C
    /* 27AAD9C 8006E000 3000B127 */   addiu     $s1, $sp, 0x30
    /* 27AADA0 8006E004 686F000C */  jal        func_8001BDA0
    /* 27AADA4 8006E008 21202002 */   addu      $a0, $s1, $zero
    /* 27AADA8 8006E00C 21202002 */  addu       $a0, $s1, $zero
    /* 27AADAC 8006E010 21282002 */  addu       $a1, $s1, $zero
    /* 27AADB0 8006E014 D4FF1226 */  addiu      $s2, $s0, -0x2C
    /* 27AADB4 8006E018 806F000C */  jal        func_8001BE00
    /* 27AADB8 8006E01C 21304002 */   addu      $a2, $s2, $zero
    /* 27AADBC 8006E020 3800A0AF */  sw         $zero, 0x38($sp)
    /* 27AADC0 8006E024 21202002 */  addu       $a0, $s1, $zero
    /* 27AADC4 8006E028 886E000C */  jal        func_8001BA20
    /* 27AADC8 8006E02C 21280000 */   addu      $a1, $zero, $zero
    /* 27AADCC 8006E030 21284000 */  addu       $a1, $v0, $zero
    /* 27AADD0 8006E034 4100A228 */  slti       $v0, $a1, 0x41
    /* 27AADD4 8006E038 05004014 */  bnez       $v0, .Llevel_34_8006E050
    /* 27AADD8 8006E03C 40FF0224 */   addiu     $v0, $zero, -0xC0
    /* 27AADDC 8006E040 21202002 */  addu       $a0, $s1, $zero
    /* 27AADE0 8006E044 316F000C */  jal        func_8001BCC4
    /* 27AADE4 8006E048 40000624 */   addiu     $a2, $zero, 0x40
    /* 27AADE8 8006E04C 40FF0224 */  addiu      $v0, $zero, -0xC0
  .Llevel_34_8006E050:
    /* 27AADEC 8006E050 3800A2AF */  sw         $v0, 0x38($sp)
    /* 27AADF0 8006E054 C8FF1026 */  addiu      $s0, $s0, -0x38
    /* 27AADF4 8006E058 21200002 */  addu       $a0, $s0, $zero
    /* 27AADF8 8006E05C 21284002 */  addu       $a1, $s2, $zero
    /* 27AADFC 8006E060 736F000C */  jal        func_8001BDCC
    /* 27AAE00 8006E064 21302002 */   addu      $a2, $s1, $zero
    /* 27AAE04 8006E068 21204002 */  addu       $a0, $s2, $zero
    /* 27AAE08 8006E06C 6C6F000C */  jal        func_8001BDB0
    /* 27AAE0C 8006E070 21280002 */   addu      $a1, $s0, $zero
    /* 27AAE10 8006E074 23B80108 */  j          .Llevel_34_8006E08C
    /* 27AAE14 8006E078 00000000 */   nop
  .Llevel_34_8006E07C:
    /* 27AAE18 8006E07C 686F000C */  jal        func_8001BDA0
    /* 27AAE1C 8006E080 C8FF0426 */   addiu     $a0, $s0, -0x38
    /* 27AAE20 8006E084 686F000C */  jal        func_8001BDA0
    /* 27AAE24 8006E088 D4FF0426 */   addiu     $a0, $s0, -0x2C
  .Llevel_34_8006E08C:
    /* 27AAE28 8006E08C 0780053C */  lui        $a1, %hi(D_8006A08C)
    /* 27AAE2C 8006E090 8CA0A524 */  addiu      $a1, $a1, %lo(D_8006A08C)
    /* 27AAE30 8006E094 0000A28C */  lw         $v0, 0x0($a1)
    /* 27AAE34 8006E098 00000000 */  nop
    /* 27AAE38 8006E09C 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 27AAE3C 8006E0A0 02004010 */  beqz       $v0, .Llevel_34_8006E0AC
    /* 27AAE40 8006E0A4 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 27AAE44 8006E0A8 0000A2AC */  sw         $v0, 0x0($a1)
  .Llevel_34_8006E0AC:
    /* 27AAE48 8006E0AC 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 27AAE4C 8006E0B0 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 27AAE50 8006E0B4 3A000224 */  addiu      $v0, $zero, 0x3A
    /* 27AAE54 8006E0B8 09016214 */  bne        $v1, $v0, .Llevel_34_8006E4E0
    /* 27AAE58 8006E0BC 00000000 */   nop
    /* 27AAE5C 8006E0C0 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 27AAE60 8006E0C4 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 27AAE64 8006E0C8 00000000 */  nop
    /* 27AAE68 8006E0CC 04014010 */  beqz       $v0, .Llevel_34_8006E4E0
    /* 27AAE6C 8006E0D0 00000000 */   nop
    /* 27AAE70 8006E0D4 0680023C */  lui        $v0, %hi(D_80067008)
    /* 27AAE74 8006E0D8 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 27AAE78 8006E0DC 00000000 */  nop
    /* 27AAE7C 8006E0E0 01004230 */  andi       $v0, $v0, 0x1
    /* 27AAE80 8006E0E4 FE004010 */  beqz       $v0, .Llevel_34_8006E4E0
    /* 27AAE84 8006E0E8 5000B027 */   addiu     $s0, $sp, 0x50
    /* 27AAE88 8006E0EC 21200002 */  addu       $a0, $s0, $zero
    /* 27AAE8C 8006E0F0 64FFA524 */  addiu      $a1, $a1, -0x9C
    /* 27AAE90 8006E0F4 0E000224 */  addiu      $v0, $zero, 0xE
    /* 27AAE94 8006E0F8 4000A0AF */  sw         $zero, 0x40($sp)
    /* 27AAE98 8006E0FC 4400A0AF */  sw         $zero, 0x44($sp)
    /* 27AAE9C 8006E100 6C6F000C */  jal        func_8001BDB0
    /* 27AAEA0 8006E104 4800A2AF */   sw        $v0, 0x48($sp)
    /* 27AAEA4 8006E108 21200000 */  addu       $a0, $zero, $zero
    /* 27AAEA8 8006E10C 63E2000C */  jal        func_8003898C
    /* 27AAEAC 8006E110 2C010524 */   addiu     $a1, $zero, 0x12C
    /* 27AAEB0 8006E114 21200000 */  addu       $a0, $zero, $zero
    /* 27AAEB4 8006E118 5000A38F */  lw         $v1, 0x50($sp)
    /* 27AAEB8 8006E11C 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 27AAEBC 8006E120 21186200 */  addu       $v1, $v1, $v0
    /* 27AAEC0 8006E124 63E2000C */  jal        func_8003898C
    /* 27AAEC4 8006E128 5000A3AF */   sw        $v1, 0x50($sp)
    /* 27AAEC8 8006E12C 21200000 */  addu       $a0, $zero, $zero
    /* 27AAECC 8006E130 5400A38F */  lw         $v1, 0x54($sp)
    /* 27AAED0 8006E134 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 27AAED4 8006E138 21186200 */  addu       $v1, $v1, $v0
    /* 27AAED8 8006E13C 63E2000C */  jal        func_8003898C
    /* 27AAEDC 8006E140 5400A3AF */   sw        $v1, 0x54($sp)
    /* 27AAEE0 8006E144 01000424 */  addiu      $a0, $zero, 0x1
    /* 27AAEE4 8006E148 0D000524 */  addiu      $a1, $zero, 0xD
    /* 27AAEE8 8006E14C 5800A38F */  lw         $v1, 0x58($sp)
    /* 27AAEEC 8006E150 21300002 */  addu       $a2, $s0, $zero
    /* 27AAEF0 8006E154 21186200 */  addu       $v1, $v1, $v0
    /* 27AAEF4 8006E158 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 27AAEF8 8006E15C FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 27AAEFC 8006E160 4000A727 */  addiu      $a3, $sp, 0x40
    /* 27AAF00 8006E164 09F84000 */  jalr       $v0
    /* 27AAF04 8006E168 5800A3AF */   sw        $v1, 0x58($sp)
    /* 27AAF08 8006E16C 06000324 */  addiu      $v1, $zero, 0x6
    /* 27AAF0C 8006E170 020043A0 */  sb         $v1, 0x2($v0)
    /* 27AAF10 8006E174 20000324 */  addiu      $v1, $zero, 0x20
    /* 27AAF14 8006E178 38B90108 */  j          .Llevel_34_8006E4E0
    /* 27AAF18 8006E17C 0A0043A0 */   sb        $v1, 0xA($v0)
  .Llevel_34_8006E180:
    /* 27AAF1C 8006E180 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 27AAF20 8006E184 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 27AAF24 8006E188 07000224 */  addiu      $v0, $zero, 0x7
    /* 27AAF28 8006E18C 3A006210 */  beq        $v1, $v0, .Llevel_34_8006E278
    /* 27AAF2C 8006E190 4000A427 */   addiu     $a0, $sp, 0x40
    /* 27AAF30 8006E194 39AD000C */  jal        func_8002B4E4
    /* 27AAF34 8006E198 21280000 */   addu      $a1, $zero, $zero
    /* 27AAF38 8006E19C 4800A427 */  addiu      $a0, $sp, 0x48
    /* 27AAF3C 8006E1A0 4000A28F */  lw         $v0, 0x40($sp)
    /* 27AAF40 8006E1A4 4400A68F */  lw         $a2, 0x44($sp)
    /* 27AAF44 8006E1A8 21280000 */  addu       $a1, $zero, $zero
    /* 27AAF48 8006E1AC 4800A0AF */  sw         $zero, 0x48($sp)
    /* 27AAF4C 8006E1B0 C0180200 */  sll        $v1, $v0, 3
    /* 27AAF50 8006E1B4 21186200 */  addu       $v1, $v1, $v0
    /* 27AAF54 8006E1B8 C0190300 */  sll        $v1, $v1, 7
    /* 27AAF58 8006E1BC C3190300 */  sra        $v1, $v1, 7
    /* 27AAF5C 8006E1C0 40100600 */  sll        $v0, $a2, 1
    /* 27AAF60 8006E1C4 21104600 */  addu       $v0, $v0, $a2
    /* 27AAF64 8006E1C8 40120200 */  sll        $v0, $v0, 9
    /* 27AAF68 8006E1CC C3110200 */  sra        $v0, $v0, 7
    /* 27AAF6C 8006E1D0 4000A3AF */  sw         $v1, 0x40($sp)
    /* 27AAF70 8006E1D4 23180300 */  negu       $v1, $v1
    /* 27AAF74 8006E1D8 4400A2AF */  sw         $v0, 0x44($sp)
    /* 27AAF78 8006E1DC 4C00A3AF */  sw         $v1, 0x4C($sp)
    /* 27AAF7C 8006E1E0 886E000C */  jal        func_8001BA20
    /* 27AAF80 8006E1E4 5000A2AF */   sw        $v0, 0x50($sp)
    /* 27AAF84 8006E1E8 5000A48F */  lw         $a0, 0x50($sp)
    /* 27AAF88 8006E1EC 00000000 */  nop
    /* 27AAF8C 8006E1F0 02008104 */  bgez       $a0, .Llevel_34_8006E1FC
    /* 27AAF90 8006E1F4 21188000 */   addu      $v1, $a0, $zero
    /* 27AAF94 8006E1F8 23180300 */  negu       $v1, $v1
  .Llevel_34_8006E1FC:
    /* 27AAF98 8006E1FC 2A186200 */  slt        $v1, $v1, $v0
    /* 27AAF9C 8006E200 0C006010 */  beqz       $v1, .Llevel_34_8006E234
    /* 27AAFA0 8006E204 00000000 */   nop
    /* 27AAFA4 8006E208 4C00A28F */  lw         $v0, 0x4C($sp)
    /* 27AAFA8 8006E20C 5000A0AF */  sw         $zero, 0x50($sp)
    /* 27AAFAC 8006E210 02004018 */  blez       $v0, .Llevel_34_8006E21C
    /* 27AAFB0 8006E214 21200000 */   addu      $a0, $zero, $zero
    /* 27AAFB4 8006E218 01000424 */  addiu      $a0, $zero, 0x1
  .Llevel_34_8006E21C:
    /* 27AAFB8 8006E21C CAB4000C */  jal        func_8002D328
    /* 27AAFBC 8006E220 00000000 */   nop
    /* 27AAFC0 8006E224 0E004014 */  bnez       $v0, .Llevel_34_8006E260
    /* 27AAFC4 8006E228 4800A427 */   addiu     $a0, $sp, 0x48
    /* 27AAFC8 8006E22C 98B80108 */  j          .Llevel_34_8006E260
    /* 27AAFCC 8006E230 4C00A0AF */   sw        $zero, 0x4C($sp)
  .Llevel_34_8006E234:
    /* 27AAFD0 8006E234 4C00A0AF */  sw         $zero, 0x4C($sp)
    /* 27AAFD4 8006E238 03008018 */  blez       $a0, .Llevel_34_8006E248
    /* 27AAFD8 8006E23C 4800A0AF */   sw        $zero, 0x48($sp)
    /* 27AAFDC 8006E240 93B80108 */  j          .Llevel_34_8006E24C
    /* 27AAFE0 8006E244 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_34_8006E248:
    /* 27AAFE4 8006E248 03000424 */  addiu      $a0, $zero, 0x3
  .Llevel_34_8006E24C:
    /* 27AAFE8 8006E24C CAB4000C */  jal        func_8002D328
    /* 27AAFEC 8006E250 00000000 */   nop
    /* 27AAFF0 8006E254 02004014 */  bnez       $v0, .Llevel_34_8006E260
    /* 27AAFF4 8006E258 4800A427 */   addiu     $a0, $sp, 0x48
    /* 27AAFF8 8006E25C 5000A0AF */  sw         $zero, 0x50($sp)
  .Llevel_34_8006E260:
    /* 27AAFFC 8006E260 886E000C */  jal        func_8001BA20
    /* 27AB000 8006E264 01000524 */   addiu     $a1, $zero, 0x1
    /* 27AB004 8006E268 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 27AB008 8006E26C A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 27AB00C 8006E270 A0B80108 */  j          .Llevel_34_8006E280
    /* 27AB010 8006E274 00000000 */   nop
  .Llevel_34_8006E278:
    /* 27AB014 8006E278 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 27AB018 8006E27C A4A020AC */  sw         $zero, %lo(D_8006A0A4)($at)
  .Llevel_34_8006E280:
    /* 27AB01C 8006E280 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 27AB020 8006E284 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 27AB024 8006E288 686F000C */  jal        func_8001BDA0
    /* 27AB028 8006E28C 21200002 */   addu      $a0, $s0, $zero
    /* 27AB02C 8006E290 686F000C */  jal        func_8001BDA0
    /* 27AB030 8006E294 0C000426 */   addiu     $a0, $s0, 0xC
    /* 27AB034 8006E298 38B90108 */  j          .Llevel_34_8006E4E0
    /* 27AB038 8006E29C 00000000 */   nop
  .Llevel_34_8006E2A0:
    /* 27AB03C 8006E2A0 6000A427 */  addiu      $a0, $sp, 0x60
    /* 27AB040 8006E2A4 39AD000C */  jal        func_8002B4E4
    /* 27AB044 8006E2A8 21280000 */   addu      $a1, $zero, $zero
    /* 27AB048 8006E2AC 6800A427 */  addiu      $a0, $sp, 0x68
    /* 27AB04C 8006E2B0 6000A28F */  lw         $v0, 0x60($sp)
    /* 27AB050 8006E2B4 6400A68F */  lw         $a2, 0x64($sp)
    /* 27AB054 8006E2B8 21280000 */  addu       $a1, $zero, $zero
    /* 27AB058 8006E2BC 6800A0AF */  sw         $zero, 0x68($sp)
    /* 27AB05C 8006E2C0 C0180200 */  sll        $v1, $v0, 3
    /* 27AB060 8006E2C4 21186200 */  addu       $v1, $v1, $v0
    /* 27AB064 8006E2C8 C0190300 */  sll        $v1, $v1, 7
    /* 27AB068 8006E2CC C3190300 */  sra        $v1, $v1, 7
    /* 27AB06C 8006E2D0 40100600 */  sll        $v0, $a2, 1
    /* 27AB070 8006E2D4 21104600 */  addu       $v0, $v0, $a2
    /* 27AB074 8006E2D8 40120200 */  sll        $v0, $v0, 9
    /* 27AB078 8006E2DC C3110200 */  sra        $v0, $v0, 7
    /* 27AB07C 8006E2E0 6000A3AF */  sw         $v1, 0x60($sp)
    /* 27AB080 8006E2E4 23180300 */  negu       $v1, $v1
    /* 27AB084 8006E2E8 6400A2AF */  sw         $v0, 0x64($sp)
    /* 27AB088 8006E2EC 6C00A3AF */  sw         $v1, 0x6C($sp)
    /* 27AB08C 8006E2F0 886E000C */  jal        func_8001BA20
    /* 27AB090 8006E2F4 7000A2AF */   sw        $v0, 0x70($sp)
    /* 27AB094 8006E2F8 7000A48F */  lw         $a0, 0x70($sp)
    /* 27AB098 8006E2FC 00000000 */  nop
    /* 27AB09C 8006E300 02008104 */  bgez       $a0, .Llevel_34_8006E30C
    /* 27AB0A0 8006E304 21188000 */   addu      $v1, $a0, $zero
    /* 27AB0A4 8006E308 23180300 */  negu       $v1, $v1
  .Llevel_34_8006E30C:
    /* 27AB0A8 8006E30C 2A186200 */  slt        $v1, $v1, $v0
    /* 27AB0AC 8006E310 0C006010 */  beqz       $v1, .Llevel_34_8006E344
    /* 27AB0B0 8006E314 00000000 */   nop
    /* 27AB0B4 8006E318 6C00A28F */  lw         $v0, 0x6C($sp)
    /* 27AB0B8 8006E31C 7000A0AF */  sw         $zero, 0x70($sp)
    /* 27AB0BC 8006E320 02004018 */  blez       $v0, .Llevel_34_8006E32C
    /* 27AB0C0 8006E324 21200000 */   addu      $a0, $zero, $zero
    /* 27AB0C4 8006E328 01000424 */  addiu      $a0, $zero, 0x1
  .Llevel_34_8006E32C:
    /* 27AB0C8 8006E32C CAB4000C */  jal        func_8002D328
    /* 27AB0CC 8006E330 00000000 */   nop
    /* 27AB0D0 8006E334 0E004014 */  bnez       $v0, .Llevel_34_8006E370
    /* 27AB0D4 8006E338 6800B127 */   addiu     $s1, $sp, 0x68
    /* 27AB0D8 8006E33C DCB80108 */  j          .Llevel_34_8006E370
    /* 27AB0DC 8006E340 6C00A0AF */   sw        $zero, 0x6C($sp)
  .Llevel_34_8006E344:
    /* 27AB0E0 8006E344 6C00A0AF */  sw         $zero, 0x6C($sp)
    /* 27AB0E4 8006E348 03008018 */  blez       $a0, .Llevel_34_8006E358
    /* 27AB0E8 8006E34C 6800A0AF */   sw        $zero, 0x68($sp)
    /* 27AB0EC 8006E350 D7B80108 */  j          .Llevel_34_8006E35C
    /* 27AB0F0 8006E354 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_34_8006E358:
    /* 27AB0F4 8006E358 03000424 */  addiu      $a0, $zero, 0x3
  .Llevel_34_8006E35C:
    /* 27AB0F8 8006E35C CAB4000C */  jal        func_8002D328
    /* 27AB0FC 8006E360 00000000 */   nop
    /* 27AB100 8006E364 02004014 */  bnez       $v0, .Llevel_34_8006E370
    /* 27AB104 8006E368 6800B127 */   addiu     $s1, $sp, 0x68
    /* 27AB108 8006E36C 7000A0AF */  sw         $zero, 0x70($sp)
  .Llevel_34_8006E370:
    /* 27AB10C 8006E370 21202002 */  addu       $a0, $s1, $zero
    /* 27AB110 8006E374 886E000C */  jal        func_8001BA20
    /* 27AB114 8006E378 01000524 */   addiu     $a1, $zero, 0x1
    /* 27AB118 8006E37C 01000624 */  addiu      $a2, $zero, 0x1
    /* 27AB11C 8006E380 6000A48F */  lw         $a0, 0x60($sp)
    /* 27AB120 8006E384 6400A58F */  lw         $a1, 0x64($sp)
    /* 27AB124 8006E388 0780103C */  lui        $s0, %hi(D_8006A0A4)
    /* 27AB128 8006E38C A4A01026 */  addiu      $s0, $s0, %lo(D_8006A0A4)
    /* 27AB12C 8006E390 2E6D000C */  jal        func_8001B4B8
    /* 27AB130 8006E394 000002AE */   sw        $v0, 0x0($s0)
    /* 27AB134 8006E398 21184000 */  addu       $v1, $v0, $zero
    /* 27AB138 8006E39C 01086228 */  slti       $v0, $v1, 0x801
    /* 27AB13C 8006E3A0 0780013C */  lui        $at, %hi(D_8006A09C)
    /* 27AB140 8006E3A4 9CA023AC */  sw         $v1, %lo(D_8006A09C)($at)
    /* 27AB144 8006E3A8 04004014 */  bnez       $v0, .Llevel_34_8006E3BC
    /* 27AB148 8006E3AC 7CFF0426 */   addiu     $a0, $s0, -0x84
    /* 27AB14C 8006E3B0 00F06224 */  addiu      $v0, $v1, -0x1000
    /* 27AB150 8006E3B4 0780013C */  lui        $at, %hi(D_8006A09C)
    /* 27AB154 8006E3B8 9CA022AC */  sw         $v0, %lo(D_8006A09C)($at)
  .Llevel_34_8006E3BC:
    /* 27AB158 8006E3BC 21282002 */  addu       $a1, $s1, $zero
    /* 27AB15C 8006E3C0 6800A28F */  lw         $v0, 0x68($sp)
    /* 27AB160 8006E3C4 21302002 */  addu       $a2, $s1, $zero
    /* 27AB164 8006E3C8 00044224 */  addiu      $v0, $v0, 0x400
    /* 27AB168 8006E3CC 696E000C */  jal        func_8001B9A4
    /* 27AB16C 8006E3D0 6800A2AF */   sw        $v0, 0x68($sp)
    /* 27AB170 8006E3D4 21202002 */  addu       $a0, $s1, $zero
    /* 27AB174 8006E3D8 21282002 */  addu       $a1, $s1, $zero
    /* 27AB178 8006E3DC E0FF1226 */  addiu      $s2, $s0, -0x20
    /* 27AB17C 8006E3E0 806F000C */  jal        func_8001BE00
    /* 27AB180 8006E3E4 21304002 */   addu      $a2, $s2, $zero
    /* 27AB184 8006E3E8 21202002 */  addu       $a0, $s1, $zero
    /* 27AB188 8006E3EC 886E000C */  jal        func_8001BA20
    /* 27AB18C 8006E3F0 21280000 */   addu      $a1, $zero, $zero
    /* 27AB190 8006E3F4 21284000 */  addu       $a1, $v0, $zero
    /* 27AB194 8006E3F8 8101A228 */  slti       $v0, $a1, 0x181
    /* 27AB198 8006E3FC 03004014 */  bnez       $v0, .Llevel_34_8006E40C
    /* 27AB19C 8006E400 21202002 */   addu      $a0, $s1, $zero
    /* 27AB1A0 8006E404 316F000C */  jal        func_8001BCC4
    /* 27AB1A4 8006E408 80010624 */   addiu     $a2, $zero, 0x180
  .Llevel_34_8006E40C:
    /* 27AB1A8 8006E40C D4FF1026 */  addiu      $s0, $s0, -0x2C
    /* 27AB1AC 8006E410 21200002 */  addu       $a0, $s0, $zero
    /* 27AB1B0 8006E414 21284002 */  addu       $a1, $s2, $zero
    /* 27AB1B4 8006E418 736F000C */  jal        func_8001BDCC
    /* 27AB1B8 8006E41C 21302002 */   addu      $a2, $s1, $zero
    /* 27AB1BC 8006E420 21204002 */  addu       $a0, $s2, $zero
    /* 27AB1C0 8006E424 6C6F000C */  jal        func_8001BDB0
    /* 27AB1C4 8006E428 21280002 */   addu      $a1, $s0, $zero
    /* 27AB1C8 8006E42C 38B90108 */  j          .Llevel_34_8006E4E0
    /* 27AB1CC 8006E430 00000000 */   nop
  .Llevel_34_8006E434:
    /* 27AB1D0 8006E434 13008228 */  slti       $v0, $a0, 0x13
    /* 27AB1D4 8006E438 1A004014 */  bnez       $v0, .Llevel_34_8006E4A4
    /* 27AB1D8 8006E43C 00000000 */   nop
    /* 27AB1DC 8006E440 0780043C */  lui        $a0, %hi(D_8006A078)
    /* 27AB1E0 8006E444 78A08424 */  addiu      $a0, $a0, %lo(D_8006A078)
    /* 27AB1E4 8006E448 0780033C */  lui        $v1, %hi(D_8006A084)
    /* 27AB1E8 8006E44C 84A0638C */  lw         $v1, %lo(D_8006A084)($v1)
    /* 27AB1EC 8006E450 00000000 */  nop
    /* 27AB1F0 8006E454 C0100300 */  sll        $v0, $v1, 3
    /* 27AB1F4 8006E458 23104300 */  subu       $v0, $v0, $v1
    /* 27AB1F8 8006E45C 0780033C */  lui        $v1, %hi(D_8006A088)
    /* 27AB1FC 8006E460 88A0638C */  lw         $v1, %lo(D_8006A088)($v1)
    /* 27AB200 8006E464 40110200 */  sll        $v0, $v0, 5
    /* 27AB204 8006E468 000082AC */  sw         $v0, 0x0($a0)
    /* 27AB208 8006E46C C0100300 */  sll        $v0, $v1, 3
    /* 27AB20C 8006E470 23104300 */  subu       $v0, $v0, $v1
    /* 27AB210 8006E474 0780033C */  lui        $v1, %hi(D_8006A08C)
    /* 27AB214 8006E478 8CA0638C */  lw         $v1, %lo(D_8006A08C)($v1)
    /* 27AB218 8006E47C 40110200 */  sll        $v0, $v0, 5
    /* 27AB21C 8006E480 0780013C */  lui        $at, %hi(D_8006A07C)
    /* 27AB220 8006E484 7CA022AC */  sw         $v0, %lo(D_8006A07C)($at)
    /* 27AB224 8006E488 C0100300 */  sll        $v0, $v1, 3
    /* 27AB228 8006E48C 23104300 */  subu       $v0, $v0, $v1
    /* 27AB22C 8006E490 40110200 */  sll        $v0, $v0, 5
    /* 27AB230 8006E494 0780013C */  lui        $at, %hi(D_8006A080)
    /* 27AB234 8006E498 80A022AC */  sw         $v0, %lo(D_8006A080)($at)
    /* 27AB238 8006E49C 526F000C */  jal        func_8001BD48
    /* 27AB23C 8006E4A0 08000524 */   addiu     $a1, $zero, 0x8
  .Llevel_34_8006E4A4:
    /* 27AB240 8006E4A4 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 27AB244 8006E4A8 84A08424 */  addiu      $a0, $a0, %lo(D_8006A084)
    /* 27AB248 8006E4AC 6C6F000C */  jal        func_8001BDB0
    /* 27AB24C 8006E4B0 F4FF8524 */   addiu     $a1, $a0, -0xC
    /* 27AB250 8006E4B4 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 27AB254 8006E4B8 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 27AB258 8006E4BC 00000000 */  nop
    /* 27AB25C 8006E4C0 40FF4224 */  addiu      $v0, $v0, -0xC0
    /* 27AB260 8006E4C4 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 27AB264 8006E4C8 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 27AB268 8006E4CC 00DD4228 */  slti       $v0, $v0, -0x2300
  .Llevel_34_8006E4D0:
    /* 27AB26C 8006E4D0 03004010 */  beqz       $v0, .Llevel_34_8006E4E0
    /* 27AB270 8006E4D4 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 27AB274 8006E4D8 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 27AB278 8006E4DC 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_34_8006E4E0:
    /* 27AB27C 8006E4E0 8400BF8F */  lw         $ra, 0x84($sp)
    /* 27AB280 8006E4E4 8000B28F */  lw         $s2, 0x80($sp)
    /* 27AB284 8006E4E8 7C00B18F */  lw         $s1, 0x7C($sp)
    /* 27AB288 8006E4EC 7800B08F */  lw         $s0, 0x78($sp)
    /* 27AB28C 8006E4F0 8800BD27 */  addiu      $sp, $sp, 0x88
    /* 27AB290 8006E4F4 0800E003 */  jr         $ra
    /* 27AB294 8006E4F8 00000000 */   nop
endlabel func_level_34_8006DB40
