.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_35_8006D528

dlabel jtbl_level_35_8006D528
    /* 29D2AC4 8006D528 7CEF0680 */ .word .Llevel_35_8006EF7C
    /* 29D2AC8 8006D52C 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2ACC 8006D530 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2AD0 8006D534 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2AD4 8006D538 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2AD8 8006D53C 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2ADC 8006D540 50F10680 */ .word .Llevel_35_8006F150
    /* 29D2AE0 8006D544 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2AE4 8006D548 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2AE8 8006D54C 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2AEC 8006D550 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2AF0 8006D554 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2AF4 8006D558 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2AF8 8006D55C 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2AFC 8006D560 9CF20680 */ .word .Llevel_35_8006F29C
    /* 29D2B00 8006D564 04F40680 */ .word .Llevel_35_8006F404
    /* 29D2B04 8006D568 64F50680 */ .word .Llevel_35_8006F564
    /* 29D2B08 8006D56C 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B0C 8006D570 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B10 8006D574 7CEF0680 */ .word .Llevel_35_8006EF7C
    /* 29D2B14 8006D578 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B18 8006D57C 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B1C 8006D580 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B20 8006D584 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B24 8006D588 C4F60680 */ .word .Llevel_35_8006F6C4
    /* 29D2B28 8006D58C A8F70680 */ .word .Llevel_35_8006F7A8
    /* 29D2B2C 8006D590 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B30 8006D594 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B34 8006D598 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B38 8006D59C 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B3C 8006D5A0 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B40 8006D5A4 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B44 8006D5A8 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B48 8006D5AC 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B4C 8006D5B0 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B50 8006D5B4 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B54 8006D5B8 20F90680 */ .word .Llevel_35_8006F920
    /* 29D2B58 8006D5BC 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B5C 8006D5C0 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B60 8006D5C4 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B64 8006D5C8 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B68 8006D5CC 30FB0680 */ .word .Llevel_35_8006FB30
    /* 29D2B6C 8006D5D0 60F90680 */ .word .Llevel_35_8006F960
    /* 29D2B70 8006D5D4 00000000 */ .word 0x00000000
enddlabel jtbl_level_35_8006D528


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_35_8006EF3C, 0xC0C

glabel func_level_35_8006EF3C
    /* 29D44D8 8006EF3C 0780023C */  lui        $v0, %hi(D_8006A040)
    /* 29D44DC 8006EF40 40A0428C */  lw         $v0, %lo(D_8006A040)($v0)
    /* 29D44E0 8006EF44 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 29D44E4 8006EF48 1800BFAF */  sw         $ra, 0x18($sp)
    /* 29D44E8 8006EF4C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 29D44EC 8006EF50 EDFF4324 */  addiu      $v1, $v0, -0x13
    /* 29D44F0 8006EF54 2B00622C */  sltiu      $v0, $v1, 0x2B
    /* 29D44F4 8006EF58 F5024010 */  beqz       $v0, .Llevel_35_8006FB30
    /* 29D44F8 8006EF5C 1000B0AF */   sw        $s0, 0x10($sp)
    /* 29D44FC 8006EF60 80100300 */  sll        $v0, $v1, 2
    /* 29D4500 8006EF64 0780013C */  lui        $at, %hi(jtbl_level_35_8006D528)
    /* 29D4504 8006EF68 21082200 */  addu       $at, $at, $v0
    /* 29D4508 8006EF6C 28D5228C */  lw         $v0, %lo(jtbl_level_35_8006D528)($at)
    /* 29D450C 8006EF70 00000000 */  nop
    /* 29D4510 8006EF74 08004000 */  jr         $v0
    /* 29D4514 8006EF78 00000000 */   nop
  .Llevel_35_8006EF7C:
    /* 29D4518 8006EF7C 2EAC000C */  jal        func_8002B0B8
    /* 29D451C 8006EF80 00000000 */   nop
    /* 29D4520 8006EF84 EA024014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4524 8006EF88 00000000 */   nop
    /* 29D4528 8006EF8C 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 29D452C 8006EF90 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 29D4530 8006EF94 00000000 */  nop
    /* 29D4534 8006EF98 40004230 */  andi       $v0, $v0, 0x40
    /* 29D4538 8006EF9C E2024014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D453C 8006EFA0 05000424 */   addiu     $a0, $zero, 0x5
    /* 29D4540 8006EFA4 0780043C */  lui        $a0, %hi(D_8006A104)
    /* 29D4544 8006EFA8 04A1848C */  lw         $a0, %lo(D_8006A104)($a0)
    /* 29D4548 8006EFAC 1EAC000C */  jal        func_8002B078
    /* 29D454C 8006EFB0 00000000 */   nop
    /* 29D4550 8006EFB4 04000324 */  addiu      $v1, $zero, 0x4
    /* 29D4554 8006EFB8 08004314 */  bne        $v0, $v1, .Llevel_35_8006EFDC
    /* 29D4558 8006EFBC 00000000 */   nop
    /* 29D455C 8006EFC0 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 29D4560 8006EFC4 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 29D4564 8006EFC8 00000000 */  nop
    /* 29D4568 8006EFCC D8024014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D456C 8006EFD0 09000424 */   addiu     $a0, $zero, 0x9
    /* 29D4570 8006EFD4 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4574 8006EFD8 00000000 */   nop
  .Llevel_35_8006EFDC:
    /* 29D4578 8006EFDC 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 29D457C 8006EFE0 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 29D4580 8006EFE4 00000000 */  nop
    /* 29D4584 8006EFE8 04004228 */  slti       $v0, $v0, 0x4
    /* 29D4588 8006EFEC CE024010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D458C 8006EFF0 06000424 */   addiu     $a0, $zero, 0x6
    /* 29D4590 8006EFF4 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 29D4594 8006EFF8 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 29D4598 8006EFFC 00000000 */  nop
    /* 29D459C 8006F000 17004228 */  slti       $v0, $v0, 0x17
    /* 29D45A0 8006F004 C8024010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D45A4 8006F008 00000000 */   nop
    /* 29D45A8 8006F00C 0780033C */  lui        $v1, %hi(D_800683A0)
    /* 29D45AC 8006F010 A083638C */  lw         $v1, %lo(D_800683A0)($v1)
    /* 29D45B0 8006F014 00000000 */  nop
    /* 29D45B4 8006F018 80006230 */  andi       $v0, $v1, 0x80
    /* 29D45B8 8006F01C C2024014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D45BC 8006F020 0C000424 */   addiu     $a0, $zero, 0xC
    /* 29D45C0 8006F024 0780023C */  lui        $v0, %hi(D_8006A0A0)
    /* 29D45C4 8006F028 A0A0428C */  lw         $v0, %lo(D_8006A0A0)($v0)
    /* 29D45C8 8006F02C 00000000 */  nop
    /* 29D45CC 8006F030 02004104 */  bgez       $v0, .Llevel_35_8006F03C
    /* 29D45D0 8006F034 00000000 */   nop
    /* 29D45D4 8006F038 23100200 */  negu       $v0, $v0
  .Llevel_35_8006F03C:
    /* 29D45D8 8006F03C 11004228 */  slti       $v0, $v0, 0x11
    /* 29D45DC 8006F040 03004014 */  bnez       $v0, .Llevel_35_8006F050
    /* 29D45E0 8006F044 0F006330 */   andi      $v1, $v1, 0xF
    /* 29D45E4 8006F048 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D45E8 8006F04C 01000424 */   addiu     $a0, $zero, 0x1
  .Llevel_35_8006F050:
    /* 29D45EC 8006F050 03000224 */  addiu      $v0, $zero, 0x3
    /* 29D45F0 8006F054 06006210 */  beq        $v1, $v0, .Llevel_35_8006F070
    /* 29D45F4 8006F058 00000000 */   nop
    /* 29D45F8 8006F05C 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 29D45FC 8006F060 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 29D4600 8006F064 00000000 */  nop
    /* 29D4604 8006F068 AF024014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4608 8006F06C 01000424 */   addiu     $a0, $zero, 0x1
  .Llevel_35_8006F070:
    /* 29D460C 8006F070 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 29D4610 8006F074 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 29D4614 8006F078 07000224 */  addiu      $v0, $zero, 0x7
    /* 29D4618 8006F07C 06006210 */  beq        $v1, $v0, .Llevel_35_8006F098
    /* 29D461C 8006F080 00000000 */   nop
    /* 29D4620 8006F084 0780023C */  lui        $v0, %hi(D_8006A230)
    /* 29D4624 8006F088 30A2428C */  lw         $v0, %lo(D_8006A230)($v0)
    /* 29D4628 8006F08C 00000000 */  nop
    /* 29D462C 8006F090 26004010 */  beqz       $v0, .Llevel_35_8006F12C
    /* 29D4630 8006F094 00000000 */   nop
  .Llevel_35_8006F098:
    /* 29D4634 8006F098 0780103C */  lui        $s0, %hi(D_8006A040)
    /* 29D4638 8006F09C 40A01026 */  addiu      $s0, $s0, %lo(D_8006A040)
    /* 29D463C 8006F0A0 0000028E */  lw         $v0, 0x0($s0)
    /* 29D4640 8006F0A4 00000000 */  nop
    /* 29D4644 8006F0A8 A1024010 */  beqz       $v0, .Llevel_35_8006FB30
    /* 29D4648 8006F0AC 00000000 */   nop
    /* 29D464C 8006F0B0 76D4000C */  jal        func_800351D8
    /* 29D4650 8006F0B4 21200000 */   addu      $a0, $zero, $zero
    /* 29D4654 8006F0B8 CCFF0292 */  lbu        $v0, -0x34($s0)
    /* 29D4658 8006F0BC 0680013C */  lui        $at, %hi(D_80062868)
    /* 29D465C 8006F0C0 21082200 */  addu       $at, $at, $v0
    /* 29D4660 8006F0C4 68282290 */  lbu        $v0, %lo(D_80062868)($at)
    /* 29D4664 8006F0C8 00000000 */  nop
    /* 29D4668 8006F0CC 6000422C */  sltiu      $v0, $v0, 0x60
    /* 29D466C 8006F0D0 09004014 */  bnez       $v0, .Llevel_35_8006F0F8
    /* 29D4670 8006F0D4 00000000 */   nop
    /* 29D4674 8006F0D8 0780023C */  lui        $v0, %hi(D_8006A005)
    /* 29D4678 8006F0DC 05A04290 */  lbu        $v0, %lo(D_8006A005)($v0)
    /* 29D467C 8006F0E0 0780033C */  lui        $v1, %hi(D_8006A007)
    /* 29D4680 8006F0E4 07A06390 */  lbu        $v1, %lo(D_8006A007)($v1)
    /* 29D4684 8006F0E8 0780013C */  lui        $at, %hi(D_8006A004)
    /* 29D4688 8006F0EC 04A022A0 */  sb         $v0, %lo(D_8006A004)($at)
    /* 29D468C 8006F0F0 0780013C */  lui        $at, %hi(D_8006A006)
    /* 29D4690 8006F0F4 06A023A0 */  sb         $v1, %lo(D_8006A006)($at)
  .Llevel_35_8006F0F8:
    /* 29D4694 8006F0F8 0780013C */  lui        $at, %hi(D_8006A007)
    /* 29D4698 8006F0FC 07A020A0 */  sb         $zero, %lo(D_8006A007)($at)
    /* 29D469C 8006F100 0000038E */  lw         $v1, 0x0($s0)
    /* 29D46A0 8006F104 71000224 */  addiu      $v0, $zero, 0x71
    /* 29D46A4 8006F108 CCFF02A2 */  sb         $v0, -0x34($s0)
    /* 29D46A8 8006F10C 0780013C */  lui        $at, %hi(D_8006A1E0)
    /* 29D46AC 8006F110 E0A120AC */  sw         $zero, %lo(D_8006A1E0)($at)
    /* 29D46B0 8006F114 0780013C */  lui        $at, %hi(D_8006A005)
    /* 29D46B4 8006F118 05A023A0 */  sb         $v1, %lo(D_8006A005)($at)
    /* 29D46B8 8006F11C 0780013C */  lui        $at, %hi(D_8006A1DC)
    /* 29D46BC 8006F120 DCA123AC */  sw         $v1, %lo(D_8006A1DC)($at)
    /* 29D46C0 8006F124 CCBE0108 */  j          .Llevel_35_8006FB30
    /* 29D46C4 8006F128 00000000 */   nop
  .Llevel_35_8006F12C:
    /* 29D46C8 8006F12C 0780023C */  lui        $v0, %hi(D_8006A0F4)
    /* 29D46CC 8006F130 F4A04290 */  lbu        $v0, %lo(D_8006A0F4)($v0)
    /* 29D46D0 8006F134 00000000 */  nop
    /* 29D46D4 8006F138 7B024014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D46D8 8006F13C 0E000424 */   addiu     $a0, $zero, 0xE
    /* 29D46DC 8006F140 0DCB000C */  jal        func_80032C34
    /* 29D46E0 8006F144 00000000 */   nop
    /* 29D46E4 8006F148 CCBE0108 */  j          .Llevel_35_8006FB30
    /* 29D46E8 8006F14C 00000000 */   nop
  .Llevel_35_8006F150:
    /* 29D46EC 8006F150 8AAC000C */  jal        func_8002B228
    /* 29D46F0 8006F154 00000000 */   nop
    /* 29D46F4 8006F158 75024014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D46F8 8006F15C 00000000 */   nop
    /* 29D46FC 8006F160 0780023C */  lui        $v0, %hi(D_8006A1AD)
    /* 29D4700 8006F164 ADA14290 */  lbu        $v0, %lo(D_8006A1AD)($v0)
    /* 29D4704 8006F168 00000000 */  nop
    /* 29D4708 8006F16C 09004010 */  beqz       $v0, .Llevel_35_8006F194
    /* 29D470C 8006F170 00000000 */   nop
    /* 29D4710 8006F174 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 29D4714 8006F178 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 29D4718 8006F17C 00000000 */  nop
    /* 29D471C 8006F180 40004230 */  andi       $v0, $v0, 0x40
    /* 29D4720 8006F184 03004010 */  beqz       $v0, .Llevel_35_8006F194
    /* 29D4724 8006F188 01000224 */   addiu     $v0, $zero, 0x1
    /* 29D4728 8006F18C 0780013C */  lui        $at, %hi(D_8006A1AE)
    /* 29D472C 8006F190 AEA122A0 */  sb         $v0, %lo(D_8006A1AE)($at)
  .Llevel_35_8006F194:
    /* 29D4730 8006F194 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 29D4734 8006F198 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 29D4738 8006F19C 00000000 */  nop
    /* 29D473C 8006F1A0 17004228 */  slti       $v0, $v0, 0x17
    /* 29D4740 8006F1A4 12004014 */  bnez       $v0, .Llevel_35_8006F1F0
    /* 29D4744 8006F1A8 00000000 */   nop
    /* 29D4748 8006F1AC 0780033C */  lui        $v1, %hi(D_8006A084)
    /* 29D474C 8006F1B0 84A0638C */  lw         $v1, %lo(D_8006A084)($v1)
    /* 29D4750 8006F1B4 0780023C */  lui        $v0, %hi(D_8006A0C4)
    /* 29D4754 8006F1B8 C4A0428C */  lw         $v0, %lo(D_8006A0C4)($v0)
    /* 29D4758 8006F1BC 00000000 */  nop
    /* 29D475C 8006F1C0 18006200 */  mult       $v1, $v0
    /* 29D4760 8006F1C4 0780033C */  lui        $v1, %hi(D_8006A088)
    /* 29D4764 8006F1C8 88A0638C */  lw         $v1, %lo(D_8006A088)($v1)
    /* 29D4768 8006F1CC 12200000 */  mflo       $a0
    /* 29D476C 8006F1D0 0780023C */  lui        $v0, %hi(D_8006A0C8)
    /* 29D4770 8006F1D4 C8A0428C */  lw         $v0, %lo(D_8006A0C8)($v0)
    /* 29D4774 8006F1D8 00000000 */  nop
    /* 29D4778 8006F1DC 18006200 */  mult       $v1, $v0
    /* 29D477C 8006F1E0 12180000 */  mflo       $v1
    /* 29D4780 8006F1E4 21108300 */  addu       $v0, $a0, $v1
    /* 29D4784 8006F1E8 4F024004 */  bltz       $v0, .Llevel_35_8006FB28
    /* 29D4788 8006F1EC 0D000424 */   addiu     $a0, $zero, 0xD
  .Llevel_35_8006F1F0:
    /* 29D478C 8006F1F0 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 29D4790 8006F1F4 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 29D4794 8006F1F8 00000000 */  nop
    /* 29D4798 8006F1FC 810C6228 */  slti       $v0, $v1, 0xC81
    /* 29D479C 8006F200 08004014 */  bnez       $v0, .Llevel_35_8006F224
    /* 29D47A0 8006F204 00000000 */   nop
    /* 29D47A4 8006F208 0780023C */  lui        $v0, %hi(D_8006A0AC)
    /* 29D47A8 8006F20C ACA0428C */  lw         $v0, %lo(D_8006A0AC)($v0)
    /* 29D47AC 8006F210 00000000 */  nop
    /* 29D47B0 8006F214 40100200 */  sll        $v0, $v0, 1
    /* 29D47B4 8006F218 2A104300 */  slt        $v0, $v0, $v1
    /* 29D47B8 8006F21C 42024014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D47BC 8006F220 0D000424 */   addiu     $a0, $zero, 0xD
  .Llevel_35_8006F224:
    /* 29D47C0 8006F224 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 29D47C4 8006F228 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 29D47C8 8006F22C 00000000 */  nop
    /* 29D47CC 8006F230 07004014 */  bnez       $v0, .Llevel_35_8006F250
    /* 29D47D0 8006F234 00000000 */   nop
    /* 29D47D4 8006F238 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 29D47D8 8006F23C 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 29D47DC 8006F240 00000000 */  nop
    /* 29D47E0 8006F244 05004228 */  slti       $v0, $v0, 0x5
    /* 29D47E4 8006F248 37024010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D47E8 8006F24C 3D000424 */   addiu     $a0, $zero, 0x3D
  .Llevel_35_8006F250:
    /* 29D47EC 8006F250 0780023C */  lui        $v0, %hi(D_8006A1AE)
    /* 29D47F0 8006F254 AEA14290 */  lbu        $v0, %lo(D_8006A1AE)($v0)
    /* 29D47F4 8006F258 00000000 */  nop
    /* 29D47F8 8006F25C 08004010 */  beqz       $v0, .Llevel_35_8006F280
    /* 29D47FC 8006F260 00000000 */   nop
    /* 29D4800 8006F264 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 29D4804 8006F268 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 29D4808 8006F26C 00000000 */  nop
    /* 29D480C 8006F270 2F024104 */  bgez       $v0, .Llevel_35_8006FB30
    /* 29D4810 8006F274 10000424 */   addiu     $a0, $zero, 0x10
    /* 29D4814 8006F278 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4818 8006F27C 00000000 */   nop
  .Llevel_35_8006F280:
    /* 29D481C 8006F280 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 29D4820 8006F284 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 29D4824 8006F288 00000000 */  nop
    /* 29D4828 8006F28C 28024104 */  bgez       $v0, .Llevel_35_8006FB30
    /* 29D482C 8006F290 15000424 */   addiu     $a0, $zero, 0x15
    /* 29D4830 8006F294 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4834 8006F298 00000000 */   nop
  .Llevel_35_8006F29C:
    /* 29D4838 8006F29C 2EAC000C */  jal        func_8002B0B8
    /* 29D483C 8006F2A0 00000000 */   nop
    /* 29D4840 8006F2A4 22024014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4844 8006F2A8 00000000 */   nop
    /* 29D4848 8006F2AC 0780113C */  lui        $s1, %hi(D_8006A0B0)
    /* 29D484C 8006F2B0 B0A03126 */  addiu      $s1, $s1, %lo(D_8006A0B0)
    /* 29D4850 8006F2B4 0000228E */  lw         $v0, 0x0($s1)
    /* 29D4854 8006F2B8 00000000 */  nop
    /* 29D4858 8006F2BC 22004014 */  bnez       $v0, .Llevel_35_8006F348
    /* 29D485C 8006F2C0 00000000 */   nop
    /* 29D4860 8006F2C4 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 29D4864 8006F2C8 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 29D4868 8006F2CC 00000000 */  nop
    /* 29D486C 8006F2D0 17004228 */  slti       $v0, $v0, 0x17
    /* 29D4870 8006F2D4 03004014 */  bnez       $v0, .Llevel_35_8006F2E4
    /* 29D4874 8006F2D8 00000000 */   nop
    /* 29D4878 8006F2DC 76D4000C */  jal        func_800351D8
    /* 29D487C 8006F2E0 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_35_8006F2E4:
    /* 29D4880 8006F2E4 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 29D4884 8006F2E8 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 29D4888 8006F2EC 00000000 */  nop
    /* 29D488C 8006F2F0 0D004018 */  blez       $v0, .Llevel_35_8006F328
    /* 29D4890 8006F2F4 00000000 */   nop
    /* 29D4894 8006F2F8 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 29D4898 8006F2FC A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 29D489C 8006F300 00000000 */  nop
    /* 29D48A0 8006F304 010F6228 */  slti       $v0, $v1, 0xF01
    /* 29D48A4 8006F308 03004014 */  bnez       $v0, .Llevel_35_8006F318
    /* 29D48A8 8006F30C 81076228 */   slti      $v0, $v1, 0x781
    /* 29D48AC 8006F310 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D48B0 8006F314 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_35_8006F318:
    /* 29D48B4 8006F318 03024014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D48B8 8006F31C 01000424 */   addiu     $a0, $zero, 0x1
    /* 29D48BC 8006F320 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D48C0 8006F324 16000424 */   addiu     $a0, $zero, 0x16
  .Llevel_35_8006F328:
    /* 29D48C4 8006F328 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 29D48C8 8006F32C A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 29D48CC 8006F330 00000000 */  nop
    /* 29D48D0 8006F334 80074228 */  slti       $v0, $v0, 0x780
    /* 29D48D4 8006F338 FB014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D48D8 8006F33C 21200000 */   addu      $a0, $zero, $zero
    /* 29D48DC 8006F340 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D48E0 8006F344 03000424 */   addiu     $a0, $zero, 0x3
  .Llevel_35_8006F348:
    /* 29D48E4 8006F348 0780103C */  lui        $s0, %hi(D_800683A4)
    /* 29D48E8 8006F34C A4831026 */  addiu      $s0, $s0, %lo(D_800683A4)
    /* 29D48EC 8006F350 0000028E */  lw         $v0, 0x0($s0)
    /* 29D48F0 8006F354 00000000 */  nop
    /* 29D48F4 8006F358 80004230 */  andi       $v0, $v0, 0x80
    /* 29D48F8 8006F35C F2014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D48FC 8006F360 15000424 */   addiu     $a0, $zero, 0x15
    /* 29D4900 8006F364 CAB4000C */  jal        func_8002D328
    /* 29D4904 8006F368 04000424 */   addiu     $a0, $zero, 0x4
    /* 29D4908 8006F36C EE014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D490C 8006F370 2F000424 */   addiu     $a0, $zero, 0x2F
    /* 29D4910 8006F374 0780023C */  lui        $v0, %hi(D_8006A0B4)
    /* 29D4914 8006F378 B4A0428C */  lw         $v0, %lo(D_8006A0B4)($v0)
    /* 29D4918 8006F37C 00000000 */  nop
    /* 29D491C 8006F380 E9014010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D4920 8006F384 06000424 */   addiu     $a0, $zero, 0x6
    /* 29D4924 8006F388 0780023C */  lui        $v0, %hi(D_8006A1B4)
    /* 29D4928 8006F38C B4A1428C */  lw         $v0, %lo(D_8006A1B4)($v0)
    /* 29D492C 8006F390 00000000 */  nop
    /* 29D4930 8006F394 E4014010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D4934 8006F398 10000424 */   addiu     $a0, $zero, 0x10
    /* 29D4938 8006F39C 0000028E */  lw         $v0, 0x0($s0)
    /* 29D493C 8006F3A0 00000000 */  nop
    /* 29D4940 8006F3A4 10004230 */  andi       $v0, $v0, 0x10
    /* 29D4944 8006F3A8 DF014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4948 8006F3AC 11000424 */   addiu     $a0, $zero, 0x11
    /* 29D494C 8006F3B0 E0FF2426 */  addiu      $a0, $s1, -0x20
    /* 29D4950 8006F3B4 886E000C */  jal        func_8001BA20
    /* 29D4954 8006F3B8 01000524 */   addiu     $a1, $zero, 0x1
    /* 29D4958 8006F3BC 00044228 */  slti       $v0, $v0, 0x400
    /* 29D495C 8006F3C0 D9014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4960 8006F3C4 06000424 */   addiu     $a0, $zero, 0x6
    /* 29D4964 8006F3C8 0780023C */  lui        $v0, %hi(D_8006A044)
    /* 29D4968 8006F3CC 44A0428C */  lw         $v0, %lo(D_8006A044)($v0)
    /* 29D496C 8006F3D0 00000000 */  nop
    /* 29D4970 8006F3D4 D4014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4974 8006F3D8 22000424 */   addiu     $a0, $zero, 0x22
    /* 29D4978 8006F3DC 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 29D497C 8006F3E0 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 29D4980 8006F3E4 00000000 */  nop
    /* 29D4984 8006F3E8 6D016228 */  slti       $v0, $v1, 0x16D
    /* 29D4988 8006F3EC CE014010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D498C 8006F3F0 94FE6228 */   slti      $v0, $v1, -0x16C
    /* 29D4990 8006F3F4 CE014010 */  beqz       $v0, .Llevel_35_8006FB30
    /* 29D4994 8006F3F8 23000424 */   addiu     $a0, $zero, 0x23
    /* 29D4998 8006F3FC CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D499C 8006F400 00000000 */   nop
  .Llevel_35_8006F404:
    /* 29D49A0 8006F404 2EAC000C */  jal        func_8002B0B8
    /* 29D49A4 8006F408 00000000 */   nop
    /* 29D49A8 8006F40C C8014014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D49AC 8006F410 00000000 */   nop
    /* 29D49B0 8006F414 0780113C */  lui        $s1, %hi(D_8006A0B0)
    /* 29D49B4 8006F418 B0A03126 */  addiu      $s1, $s1, %lo(D_8006A0B0)
    /* 29D49B8 8006F41C 0000228E */  lw         $v0, 0x0($s1)
    /* 29D49BC 8006F420 00000000 */  nop
    /* 29D49C0 8006F424 22004014 */  bnez       $v0, .Llevel_35_8006F4B0
    /* 29D49C4 8006F428 00000000 */   nop
    /* 29D49C8 8006F42C 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 29D49CC 8006F430 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 29D49D0 8006F434 00000000 */  nop
    /* 29D49D4 8006F438 17004228 */  slti       $v0, $v0, 0x17
    /* 29D49D8 8006F43C 03004014 */  bnez       $v0, .Llevel_35_8006F44C
    /* 29D49DC 8006F440 00000000 */   nop
    /* 29D49E0 8006F444 76D4000C */  jal        func_800351D8
    /* 29D49E4 8006F448 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_35_8006F44C:
    /* 29D49E8 8006F44C 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 29D49EC 8006F450 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 29D49F0 8006F454 00000000 */  nop
    /* 29D49F4 8006F458 0D004018 */  blez       $v0, .Llevel_35_8006F490
    /* 29D49F8 8006F45C 00000000 */   nop
    /* 29D49FC 8006F460 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 29D4A00 8006F464 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 29D4A04 8006F468 00000000 */  nop
    /* 29D4A08 8006F46C 010F6228 */  slti       $v0, $v1, 0xF01
    /* 29D4A0C 8006F470 03004014 */  bnez       $v0, .Llevel_35_8006F480
    /* 29D4A10 8006F474 81076228 */   slti      $v0, $v1, 0x781
    /* 29D4A14 8006F478 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4A18 8006F47C 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_35_8006F480:
    /* 29D4A1C 8006F480 A9014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4A20 8006F484 01000424 */   addiu     $a0, $zero, 0x1
    /* 29D4A24 8006F488 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4A28 8006F48C 16000424 */   addiu     $a0, $zero, 0x16
  .Llevel_35_8006F490:
    /* 29D4A2C 8006F490 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 29D4A30 8006F494 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 29D4A34 8006F498 00000000 */  nop
    /* 29D4A38 8006F49C 80074228 */  slti       $v0, $v0, 0x780
    /* 29D4A3C 8006F4A0 A1014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4A40 8006F4A4 21200000 */   addu      $a0, $zero, $zero
    /* 29D4A44 8006F4A8 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4A48 8006F4AC 03000424 */   addiu     $a0, $zero, 0x3
  .Llevel_35_8006F4B0:
    /* 29D4A4C 8006F4B0 0780103C */  lui        $s0, %hi(D_800683A4)
    /* 29D4A50 8006F4B4 A4831026 */  addiu      $s0, $s0, %lo(D_800683A4)
    /* 29D4A54 8006F4B8 0000028E */  lw         $v0, 0x0($s0)
    /* 29D4A58 8006F4BC 00000000 */  nop
    /* 29D4A5C 8006F4C0 80004230 */  andi       $v0, $v0, 0x80
    /* 29D4A60 8006F4C4 98014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4A64 8006F4C8 15000424 */   addiu     $a0, $zero, 0x15
    /* 29D4A68 8006F4CC CAB4000C */  jal        func_8002D328
    /* 29D4A6C 8006F4D0 04000424 */   addiu     $a0, $zero, 0x4
    /* 29D4A70 8006F4D4 94014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4A74 8006F4D8 2F000424 */   addiu     $a0, $zero, 0x2F
    /* 29D4A78 8006F4DC 0780023C */  lui        $v0, %hi(D_8006A0B4)
    /* 29D4A7C 8006F4E0 B4A0428C */  lw         $v0, %lo(D_8006A0B4)($v0)
    /* 29D4A80 8006F4E4 00000000 */  nop
    /* 29D4A84 8006F4E8 8F014010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D4A88 8006F4EC 06000424 */   addiu     $a0, $zero, 0x6
    /* 29D4A8C 8006F4F0 0780023C */  lui        $v0, %hi(D_8006A1B4)
    /* 29D4A90 8006F4F4 B4A1428C */  lw         $v0, %lo(D_8006A1B4)($v0)
    /* 29D4A94 8006F4F8 00000000 */  nop
    /* 29D4A98 8006F4FC 8A014010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D4A9C 8006F500 10000424 */   addiu     $a0, $zero, 0x10
    /* 29D4AA0 8006F504 0000028E */  lw         $v0, 0x0($s0)
    /* 29D4AA4 8006F508 00000000 */  nop
    /* 29D4AA8 8006F50C 10004230 */  andi       $v0, $v0, 0x10
    /* 29D4AAC 8006F510 85014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4AB0 8006F514 11000424 */   addiu     $a0, $zero, 0x11
    /* 29D4AB4 8006F518 E0FF2426 */  addiu      $a0, $s1, -0x20
    /* 29D4AB8 8006F51C 886E000C */  jal        func_8001BA20
    /* 29D4ABC 8006F520 01000524 */   addiu     $a1, $zero, 0x1
    /* 29D4AC0 8006F524 00044228 */  slti       $v0, $v0, 0x400
    /* 29D4AC4 8006F528 7F014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4AC8 8006F52C 06000424 */   addiu     $a0, $zero, 0x6
    /* 29D4ACC 8006F530 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 29D4AD0 8006F534 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 29D4AD4 8006F538 00000000 */  nop
    /* 29D4AD8 8006F53C 00014228 */  slti       $v0, $v0, 0x100
    /* 29D4ADC 8006F540 7B014010 */  beqz       $v0, .Llevel_35_8006FB30
    /* 29D4AE0 8006F544 00000000 */   nop
    /* 29D4AE4 8006F548 0780023C */  lui        $v0, %hi(D_8006A044)
    /* 29D4AE8 8006F54C 44A0428C */  lw         $v0, %lo(D_8006A044)($v0)
    /* 29D4AEC 8006F550 00000000 */  nop
    /* 29D4AF0 8006F554 76014014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4AF4 8006F558 21000424 */   addiu     $a0, $zero, 0x21
    /* 29D4AF8 8006F55C CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4AFC 8006F560 00000000 */   nop
  .Llevel_35_8006F564:
    /* 29D4B00 8006F564 2EAC000C */  jal        func_8002B0B8
    /* 29D4B04 8006F568 00000000 */   nop
    /* 29D4B08 8006F56C 70014014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4B0C 8006F570 00000000 */   nop
    /* 29D4B10 8006F574 0780113C */  lui        $s1, %hi(D_8006A0B0)
    /* 29D4B14 8006F578 B0A03126 */  addiu      $s1, $s1, %lo(D_8006A0B0)
    /* 29D4B18 8006F57C 0000228E */  lw         $v0, 0x0($s1)
    /* 29D4B1C 8006F580 00000000 */  nop
    /* 29D4B20 8006F584 22004014 */  bnez       $v0, .Llevel_35_8006F610
    /* 29D4B24 8006F588 00000000 */   nop
    /* 29D4B28 8006F58C 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 29D4B2C 8006F590 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 29D4B30 8006F594 00000000 */  nop
    /* 29D4B34 8006F598 17004228 */  slti       $v0, $v0, 0x17
    /* 29D4B38 8006F59C 03004014 */  bnez       $v0, .Llevel_35_8006F5AC
    /* 29D4B3C 8006F5A0 00000000 */   nop
    /* 29D4B40 8006F5A4 76D4000C */  jal        func_800351D8
    /* 29D4B44 8006F5A8 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_35_8006F5AC:
    /* 29D4B48 8006F5AC 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 29D4B4C 8006F5B0 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 29D4B50 8006F5B4 00000000 */  nop
    /* 29D4B54 8006F5B8 0D004018 */  blez       $v0, .Llevel_35_8006F5F0
    /* 29D4B58 8006F5BC 00000000 */   nop
    /* 29D4B5C 8006F5C0 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 29D4B60 8006F5C4 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 29D4B64 8006F5C8 00000000 */  nop
    /* 29D4B68 8006F5CC 010F6228 */  slti       $v0, $v1, 0xF01
    /* 29D4B6C 8006F5D0 03004014 */  bnez       $v0, .Llevel_35_8006F5E0
    /* 29D4B70 8006F5D4 81076228 */   slti      $v0, $v1, 0x781
    /* 29D4B74 8006F5D8 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4B78 8006F5DC 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_35_8006F5E0:
    /* 29D4B7C 8006F5E0 51014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4B80 8006F5E4 01000424 */   addiu     $a0, $zero, 0x1
    /* 29D4B84 8006F5E8 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4B88 8006F5EC 16000424 */   addiu     $a0, $zero, 0x16
  .Llevel_35_8006F5F0:
    /* 29D4B8C 8006F5F0 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 29D4B90 8006F5F4 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 29D4B94 8006F5F8 00000000 */  nop
    /* 29D4B98 8006F5FC 80074228 */  slti       $v0, $v0, 0x780
    /* 29D4B9C 8006F600 49014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4BA0 8006F604 21200000 */   addu      $a0, $zero, $zero
    /* 29D4BA4 8006F608 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4BA8 8006F60C 03000424 */   addiu     $a0, $zero, 0x3
  .Llevel_35_8006F610:
    /* 29D4BAC 8006F610 0780103C */  lui        $s0, %hi(D_800683A4)
    /* 29D4BB0 8006F614 A4831026 */  addiu      $s0, $s0, %lo(D_800683A4)
    /* 29D4BB4 8006F618 0000028E */  lw         $v0, 0x0($s0)
    /* 29D4BB8 8006F61C 00000000 */  nop
    /* 29D4BBC 8006F620 80004230 */  andi       $v0, $v0, 0x80
    /* 29D4BC0 8006F624 40014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4BC4 8006F628 15000424 */   addiu     $a0, $zero, 0x15
    /* 29D4BC8 8006F62C CAB4000C */  jal        func_8002D328
    /* 29D4BCC 8006F630 04000424 */   addiu     $a0, $zero, 0x4
    /* 29D4BD0 8006F634 3C014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4BD4 8006F638 2F000424 */   addiu     $a0, $zero, 0x2F
    /* 29D4BD8 8006F63C 0780023C */  lui        $v0, %hi(D_8006A0B4)
    /* 29D4BDC 8006F640 B4A0428C */  lw         $v0, %lo(D_8006A0B4)($v0)
    /* 29D4BE0 8006F644 00000000 */  nop
    /* 29D4BE4 8006F648 37014010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D4BE8 8006F64C 06000424 */   addiu     $a0, $zero, 0x6
    /* 29D4BEC 8006F650 0780023C */  lui        $v0, %hi(D_8006A1B4)
    /* 29D4BF0 8006F654 B4A1428C */  lw         $v0, %lo(D_8006A1B4)($v0)
    /* 29D4BF4 8006F658 00000000 */  nop
    /* 29D4BF8 8006F65C 32014010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D4BFC 8006F660 10000424 */   addiu     $a0, $zero, 0x10
    /* 29D4C00 8006F664 0000028E */  lw         $v0, 0x0($s0)
    /* 29D4C04 8006F668 00000000 */  nop
    /* 29D4C08 8006F66C 10004230 */  andi       $v0, $v0, 0x10
    /* 29D4C0C 8006F670 2D014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4C10 8006F674 11000424 */   addiu     $a0, $zero, 0x11
    /* 29D4C14 8006F678 E0FF2426 */  addiu      $a0, $s1, -0x20
    /* 29D4C18 8006F67C 886E000C */  jal        func_8001BA20
    /* 29D4C1C 8006F680 01000524 */   addiu     $a1, $zero, 0x1
    /* 29D4C20 8006F684 00044228 */  slti       $v0, $v0, 0x400
    /* 29D4C24 8006F688 27014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4C28 8006F68C 06000424 */   addiu     $a0, $zero, 0x6
    /* 29D4C2C 8006F690 0780023C */  lui        $v0, %hi(D_8006A044)
    /* 29D4C30 8006F694 44A0428C */  lw         $v0, %lo(D_8006A044)($v0)
    /* 29D4C34 8006F698 00000000 */  nop
    /* 29D4C38 8006F69C 22014014 */  bnez       $v0, .Llevel_35_8006FB28
    /* 29D4C3C 8006F6A0 22000424 */   addiu     $a0, $zero, 0x22
    /* 29D4C40 8006F6A4 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 29D4C44 8006F6A8 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 29D4C48 8006F6AC 00000000 */  nop
    /* 29D4C4C 8006F6B0 01FF4228 */  slti       $v0, $v0, -0xFF
    /* 29D4C50 8006F6B4 1E014014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4C54 8006F6B8 21000424 */   addiu     $a0, $zero, 0x21
    /* 29D4C58 8006F6BC CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4C5C 8006F6C0 00000000 */   nop
  .Llevel_35_8006F6C4:
    /* 29D4C60 8006F6C4 2EAC000C */  jal        func_8002B0B8
    /* 29D4C64 8006F6C8 00000000 */   nop
    /* 29D4C68 8006F6CC 18014014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4C6C 8006F6D0 00000000 */   nop
    /* 29D4C70 8006F6D4 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 29D4C74 8006F6D8 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 29D4C78 8006F6DC 00000000 */  nop
    /* 29D4C7C 8006F6E0 40004230 */  andi       $v0, $v0, 0x40
    /* 29D4C80 8006F6E4 07004010 */  beqz       $v0, .Llevel_35_8006F704
    /* 29D4C84 8006F6E8 00000000 */   nop
    /* 29D4C88 8006F6EC 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 29D4C8C 8006F6F0 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 29D4C90 8006F6F4 00000000 */  nop
    /* 29D4C94 8006F6F8 09004228 */  slti       $v0, $v0, 0x9
    /* 29D4C98 8006F6FC 21004010 */  beqz       $v0, .Llevel_35_8006F784
    /* 29D4C9C 8006F700 05000424 */   addiu     $a0, $zero, 0x5
  .Llevel_35_8006F704:
    /* 29D4CA0 8006F704 0780043C */  lui        $a0, %hi(D_8006A0F8)
    /* 29D4CA4 8006F708 F8A08424 */  addiu      $a0, $a0, %lo(D_8006A0F8)
    /* 29D4CA8 8006F70C 00008290 */  lbu        $v0, 0x0($a0)
    /* 29D4CAC 8006F710 00000000 */  nop
    /* 29D4CB0 8006F714 1A004010 */  beqz       $v0, .Llevel_35_8006F780
    /* 29D4CB4 8006F718 00000000 */   nop
    /* 29D4CB8 8006F71C 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 29D4CBC 8006F720 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 29D4CC0 8006F724 00000000 */  nop
    /* 29D4CC4 8006F728 80004230 */  andi       $v0, $v0, 0x80
    /* 29D4CC8 8006F72C 17004010 */  beqz       $v0, .Llevel_35_8006F78C
    /* 29D4CCC 8006F730 00000000 */   nop
    /* 29D4CD0 8006F734 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 29D4CD4 8006F738 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 29D4CD8 8006F73C 00000000 */  nop
    /* 29D4CDC 8006F740 09004228 */  slti       $v0, $v0, 0x9
    /* 29D4CE0 8006F744 11004014 */  bnez       $v0, .Llevel_35_8006F78C
    /* 29D4CE4 8006F748 00000000 */   nop
    /* 29D4CE8 8006F74C 0680023C */  lui        $v0, %hi(D_80064682)
    /* 29D4CEC 8006F750 82464284 */  lh         $v0, %lo(D_80064682)($v0)
    /* 29D4CF0 8006F754 00000000 */  nop
    /* 29D4CF4 8006F758 0C004010 */  beqz       $v0, .Llevel_35_8006F78C
    /* 29D4CF8 8006F75C F8FE8424 */   addiu     $a0, $a0, -0x108
    /* 29D4CFC 8006F760 00040524 */  addiu      $a1, $zero, 0x400
    /* 29D4D00 8006F764 01000624 */  addiu      $a2, $zero, 0x1
    /* 29D4D04 8006F768 8FFB000C */  jal        func_8003EE3C
    /* 29D4D08 8006F76C 21380000 */   addu      $a3, $zero, $zero
    /* 29D4D0C 8006F770 06004014 */  bnez       $v0, .Llevel_35_8006F78C
    /* 29D4D10 8006F774 28000424 */   addiu     $a0, $zero, 0x28
    /* 29D4D14 8006F778 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4D18 8006F77C 00000000 */   nop
  .Llevel_35_8006F780:
    /* 29D4D1C 8006F780 06000424 */  addiu      $a0, $zero, 0x6
  .Llevel_35_8006F784:
    /* 29D4D20 8006F784 76D4000C */  jal        func_800351D8
    /* 29D4D24 8006F788 00000000 */   nop
  .Llevel_35_8006F78C:
    /* 29D4D28 8006F78C 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 29D4D2C 8006F790 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 29D4D30 8006F794 00000000 */  nop
    /* 29D4D34 8006F798 E5004010 */  beqz       $v0, .Llevel_35_8006FB30
    /* 29D4D38 8006F79C 2C000424 */   addiu     $a0, $zero, 0x2C
    /* 29D4D3C 8006F7A0 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4D40 8006F7A4 00000000 */   nop
  .Llevel_35_8006F7A8:
    /* 29D4D44 8006F7A8 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 29D4D48 8006F7AC 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 29D4D4C 8006F7B0 01000224 */  addiu      $v0, $zero, 0x1
    /* 29D4D50 8006F7B4 1F006214 */  bne        $v1, $v0, .Llevel_35_8006F834
    /* 29D4D54 8006F7B8 00000000 */   nop
    /* 29D4D58 8006F7BC 0780023C */  lui        $v0, %hi(D_8006ABF8)
    /* 29D4D5C 8006F7C0 F8AB4290 */  lbu        $v0, %lo(D_8006ABF8)($v0)
    /* 29D4D60 8006F7C4 00000000 */  nop
    /* 29D4D64 8006F7C8 D9004014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4D68 8006F7CC 00000000 */   nop
    /* 29D4D6C 8006F7D0 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 29D4D70 8006F7D4 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 29D4D74 8006F7D8 00000000 */  nop
    /* 29D4D78 8006F7DC 50084230 */  andi       $v0, $v0, 0x850
    /* 29D4D7C 8006F7E0 07004014 */  bnez       $v0, .Llevel_35_8006F800
    /* 29D4D80 8006F7E4 00000000 */   nop
    /* 29D4D84 8006F7E8 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 29D4D88 8006F7EC 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 29D4D8C 8006F7F0 00000000 */  nop
    /* 29D4D90 8006F7F4 3D004228 */  slti       $v0, $v0, 0x3D
    /* 29D4D94 8006F7F8 CD004014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4D98 8006F7FC 00000000 */   nop
  .Llevel_35_8006F800:
    /* 29D4D9C 8006F800 0680023C */  lui        $v0, %hi(D_80066F8C)
    /* 29D4DA0 8006F804 8C6F428C */  lw         $v0, %lo(D_80066F8C)($v0)
    /* 29D4DA4 8006F808 00000000 */  nop
    /* 29D4DA8 8006F80C 05004010 */  beqz       $v0, .Llevel_35_8006F824
    /* 29D4DAC 8006F810 00000000 */   nop
    /* 29D4DB0 8006F814 09F84000 */  jalr       $v0
    /* 29D4DB4 8006F818 00000000 */   nop
    /* 29D4DB8 8006F81C CCBE0108 */  j          .Llevel_35_8006FB30
    /* 29D4DBC 8006F820 00000000 */   nop
  .Llevel_35_8006F824:
    /* 29D4DC0 8006F824 9DCB000C */  jal        func_80032E74
    /* 29D4DC4 8006F828 00000000 */   nop
    /* 29D4DC8 8006F82C CCBE0108 */  j          .Llevel_35_8006FB30
    /* 29D4DCC 8006F830 00000000 */   nop
  .Llevel_35_8006F834:
    /* 29D4DD0 8006F834 2EAC000C */  jal        func_8002B0B8
    /* 29D4DD4 8006F838 00000000 */   nop
    /* 29D4DD8 8006F83C BC004014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4DDC 8006F840 00000000 */   nop
    /* 29D4DE0 8006F844 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 29D4DE4 8006F848 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 29D4DE8 8006F84C 00000000 */  nop
    /* 29D4DEC 8006F850 40004230 */  andi       $v0, $v0, 0x40
    /* 29D4DF0 8006F854 07004010 */  beqz       $v0, .Llevel_35_8006F874
    /* 29D4DF4 8006F858 00000000 */   nop
    /* 29D4DF8 8006F85C 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 29D4DFC 8006F860 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 29D4E00 8006F864 00000000 */  nop
    /* 29D4E04 8006F868 09004228 */  slti       $v0, $v0, 0x9
    /* 29D4E08 8006F86C AE004010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D4E0C 8006F870 05000424 */   addiu     $a0, $zero, 0x5
  .Llevel_35_8006F874:
    /* 29D4E10 8006F874 0780043C */  lui        $a0, %hi(D_8006A0F8)
    /* 29D4E14 8006F878 F8A08424 */  addiu      $a0, $a0, %lo(D_8006A0F8)
    /* 29D4E18 8006F87C 00008290 */  lbu        $v0, 0x0($a0)
    /* 29D4E1C 8006F880 00000000 */  nop
    /* 29D4E20 8006F884 03004014 */  bnez       $v0, .Llevel_35_8006F894
    /* 29D4E24 8006F888 00000000 */   nop
    /* 29D4E28 8006F88C CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4E2C 8006F890 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_35_8006F894:
    /* 29D4E30 8006F894 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 29D4E34 8006F898 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 29D4E38 8006F89C 00000000 */  nop
    /* 29D4E3C 8006F8A0 80004230 */  andi       $v0, $v0, 0x80
    /* 29D4E40 8006F8A4 12004010 */  beqz       $v0, .Llevel_35_8006F8F0
    /* 29D4E44 8006F8A8 00000000 */   nop
    /* 29D4E48 8006F8AC 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 29D4E4C 8006F8B0 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 29D4E50 8006F8B4 00000000 */  nop
    /* 29D4E54 8006F8B8 09004228 */  slti       $v0, $v0, 0x9
    /* 29D4E58 8006F8BC 0C004014 */  bnez       $v0, .Llevel_35_8006F8F0
    /* 29D4E5C 8006F8C0 00000000 */   nop
    /* 29D4E60 8006F8C4 0680023C */  lui        $v0, %hi(D_80064682)
    /* 29D4E64 8006F8C8 82464284 */  lh         $v0, %lo(D_80064682)($v0)
    /* 29D4E68 8006F8CC 00000000 */  nop
    /* 29D4E6C 8006F8D0 07004010 */  beqz       $v0, .Llevel_35_8006F8F0
    /* 29D4E70 8006F8D4 F8FE8424 */   addiu     $a0, $a0, -0x108
    /* 29D4E74 8006F8D8 00040524 */  addiu      $a1, $zero, 0x400
    /* 29D4E78 8006F8DC 01000624 */  addiu      $a2, $zero, 0x1
    /* 29D4E7C 8006F8E0 8FFB000C */  jal        func_8003EE3C
    /* 29D4E80 8006F8E4 21380000 */   addu      $a3, $zero, $zero
    /* 29D4E84 8006F8E8 8F004010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D4E88 8006F8EC 28000424 */   addiu     $a0, $zero, 0x28
  .Llevel_35_8006F8F0:
    /* 29D4E8C 8006F8F0 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 29D4E90 8006F8F4 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 29D4E94 8006F8F8 07000224 */  addiu      $v0, $zero, 0x7
    /* 29D4E98 8006F8FC 8C006210 */  beq        $v1, $v0, .Llevel_35_8006FB30
    /* 29D4E9C 8006F900 00000000 */   nop
    /* 29D4EA0 8006F904 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 29D4EA4 8006F908 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 29D4EA8 8006F90C 00000000 */  nop
    /* 29D4EAC 8006F910 87004014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4EB0 8006F914 2B000424 */   addiu     $a0, $zero, 0x2B
    /* 29D4EB4 8006F918 CABE0108 */  j          .Llevel_35_8006FB28
    /* 29D4EB8 8006F91C 00000000 */   nop
  .Llevel_35_8006F920:
    /* 29D4EBC 8006F920 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 29D4EC0 8006F924 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 29D4EC4 8006F928 00000000 */  nop
    /* 29D4EC8 8006F92C 65004228 */  slti       $v0, $v0, 0x65
    /* 29D4ECC 8006F930 7F004014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4ED0 8006F934 00000000 */   nop
    /* 29D4ED4 8006F938 76D4000C */  jal        func_800351D8
    /* 29D4ED8 8006F93C 2C000424 */   addiu     $a0, $zero, 0x2C
    /* 29D4EDC 8006F940 01000224 */  addiu      $v0, $zero, 0x1
    /* 29D4EE0 8006F944 0780013C */  lui        $at, %hi(D_8006A044)
    /* 29D4EE4 8006F948 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 29D4EE8 8006F94C 08000224 */  addiu      $v0, $zero, 0x8
    /* 29D4EEC 8006F950 0780013C */  lui        $at, %hi(D_8006A048)
    /* 29D4EF0 8006F954 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 29D4EF4 8006F958 CCBE0108 */  j          .Llevel_35_8006FB30
    /* 29D4EF8 8006F95C 00000000 */   nop
  .Llevel_35_8006F960:
    /* 29D4EFC 8006F960 8AAC000C */  jal        func_8002B228
    /* 29D4F00 8006F964 00000000 */   nop
    /* 29D4F04 8006F968 71004014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D4F08 8006F96C 01000224 */   addiu     $v0, $zero, 0x1
    /* 29D4F0C 8006F970 0780103C */  lui        $s0, %hi(D_8006A044)
    /* 29D4F10 8006F974 44A01026 */  addiu      $s0, $s0, %lo(D_8006A044)
    /* 29D4F14 8006F978 0000038E */  lw         $v1, 0x0($s0)
    /* 29D4F18 8006F97C 00000000 */  nop
    /* 29D4F1C 8006F980 10006214 */  bne        $v1, $v0, .Llevel_35_8006F9C4
    /* 29D4F20 8006F984 00000000 */   nop
    /* 29D4F24 8006F988 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 29D4F28 8006F98C B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 29D4F2C 8006F990 00000000 */  nop
    /* 29D4F30 8006F994 04004228 */  slti       $v0, $v0, 0x4
    /* 29D4F34 8006F998 10004010 */  beqz       $v0, .Llevel_35_8006F9DC
    /* 29D4F38 8006F99C 00000000 */   nop
    /* 29D4F3C 8006F9A0 0780043C */  lui        $a0, %hi(D_8006A104)
    /* 29D4F40 8006F9A4 04A1848C */  lw         $a0, %lo(D_8006A104)($a0)
    /* 29D4F44 8006F9A8 1EAC000C */  jal        func_8002B078
    /* 29D4F48 8006F9AC 00000000 */   nop
    /* 29D4F4C 8006F9B0 09000324 */  addiu      $v1, $zero, 0x9
    /* 29D4F50 8006F9B4 4F004310 */  beq        $v0, $v1, .Llevel_35_8006FAF4
    /* 29D4F54 8006F9B8 00000000 */   nop
    /* 29D4F58 8006F9BC BDBE0108 */  j          .Llevel_35_8006FAF4
    /* 29D4F5C 8006F9C0 000000AE */   sw        $zero, 0x0($s0)
  .Llevel_35_8006F9C4:
    /* 29D4F60 8006F9C4 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 29D4F64 8006F9C8 A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 29D4F68 8006F9CC 00000000 */  nop
    /* 29D4F6C 8006F9D0 40004230 */  andi       $v0, $v0, 0x40
    /* 29D4F70 8006F9D4 0D004010 */  beqz       $v0, .Llevel_35_8006FA0C
    /* 29D4F74 8006F9D8 00000000 */   nop
  .Llevel_35_8006F9DC:
    /* 29D4F78 8006F9DC 76D4000C */  jal        func_800351D8
    /* 29D4F7C 8006F9E0 19000424 */   addiu     $a0, $zero, 0x19
    /* 29D4F80 8006F9E4 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 29D4F84 8006F9E8 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 29D4F88 8006F9EC C00D0324 */  addiu      $v1, $zero, 0xDC0
    /* 29D4F8C 8006F9F0 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 29D4F90 8006F9F4 8CA023AC */  sw         $v1, %lo(D_8006A08C)($at)
    /* 29D4F94 8006F9F8 01004224 */  addiu      $v0, $v0, 0x1
    /* 29D4F98 8006F9FC 0780013C */  lui        $at, %hi(D_8006A0B0)
    /* 29D4F9C 8006FA00 B0A022AC */  sw         $v0, %lo(D_8006A0B0)($at)
    /* 29D4FA0 8006FA04 CCBE0108 */  j          .Llevel_35_8006FB30
    /* 29D4FA4 8006FA08 00000000 */   nop
  .Llevel_35_8006FA0C:
    /* 29D4FA8 8006FA0C 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 29D4FAC 8006FA10 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 29D4FB0 8006FA14 00000000 */  nop
    /* 29D4FB4 8006FA18 04004228 */  slti       $v0, $v0, 0x4
    /* 29D4FB8 8006FA1C 42004010 */  beqz       $v0, .Llevel_35_8006FB28
    /* 29D4FBC 8006FA20 19000424 */   addiu     $a0, $zero, 0x19
    /* 29D4FC0 8006FA24 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 29D4FC4 8006FA28 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 29D4FC8 8006FA2C 00000000 */  nop
    /* 29D4FCC 8006FA30 17004228 */  slti       $v0, $v0, 0x17
    /* 29D4FD0 8006FA34 12004014 */  bnez       $v0, .Llevel_35_8006FA80
    /* 29D4FD4 8006FA38 00000000 */   nop
    /* 29D4FD8 8006FA3C 0780033C */  lui        $v1, %hi(D_8006A0C4)
    /* 29D4FDC 8006FA40 C4A0638C */  lw         $v1, %lo(D_8006A0C4)($v1)
    /* 29D4FE0 8006FA44 0780023C */  lui        $v0, %hi(D_8006A084)
    /* 29D4FE4 8006FA48 84A0428C */  lw         $v0, %lo(D_8006A084)($v0)
    /* 29D4FE8 8006FA4C 00000000 */  nop
    /* 29D4FEC 8006FA50 18006200 */  mult       $v1, $v0
    /* 29D4FF0 8006FA54 0780033C */  lui        $v1, %hi(D_8006A0C8)
    /* 29D4FF4 8006FA58 C8A0638C */  lw         $v1, %lo(D_8006A0C8)($v1)
    /* 29D4FF8 8006FA5C 12200000 */  mflo       $a0
    /* 29D4FFC 8006FA60 0780023C */  lui        $v0, %hi(D_8006A088)
    /* 29D5000 8006FA64 88A0428C */  lw         $v0, %lo(D_8006A088)($v0)
    /* 29D5004 8006FA68 00000000 */  nop
    /* 29D5008 8006FA6C 18006200 */  mult       $v1, $v0
    /* 29D500C 8006FA70 12180000 */  mflo       $v1
    /* 29D5010 8006FA74 21108300 */  addu       $v0, $a0, $v1
    /* 29D5014 8006FA78 2B004004 */  bltz       $v0, .Llevel_35_8006FB28
    /* 29D5018 8006FA7C 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_35_8006FA80:
    /* 29D501C 8006FA80 0780043C */  lui        $a0, %hi(D_8006A044)
    /* 29D5020 8006FA84 44A08424 */  addiu      $a0, $a0, %lo(D_8006A044)
    /* 29D5024 8006FA88 0000838C */  lw         $v1, 0x0($a0)
    /* 29D5028 8006FA8C 02000224 */  addiu      $v0, $zero, 0x2
    /* 29D502C 8006FA90 08006214 */  bne        $v1, $v0, .Llevel_35_8006FAB4
    /* 29D5030 8006FA94 00000000 */   nop
    /* 29D5034 8006FA98 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 29D5038 8006FA9C 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 29D503C 8006FAA0 00000000 */  nop
    /* 29D5040 8006FAA4 10004228 */  slti       $v0, $v0, 0x10
    /* 29D5044 8006FAA8 02004014 */  bnez       $v0, .Llevel_35_8006FAB4
    /* 29D5048 8006FAAC 00000000 */   nop
    /* 29D504C 8006FAB0 000080AC */  sw         $zero, 0x0($a0)
  .Llevel_35_8006FAB4:
    /* 29D5050 8006FAB4 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 29D5054 8006FAB8 A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 29D5058 8006FABC 00000000 */  nop
    /* 29D505C 8006FAC0 80004230 */  andi       $v0, $v0, 0x80
    /* 29D5060 8006FAC4 0B004014 */  bnez       $v0, .Llevel_35_8006FAF4
    /* 29D5064 8006FAC8 00000000 */   nop
    /* 29D5068 8006FACC 0780023C */  lui        $v0, %hi(D_80069894)
    /* 29D506C 8006FAD0 9498428C */  lw         $v0, %lo(D_80069894)($v0)
    /* 29D5070 8006FAD4 00000000 */  nop
    /* 29D5074 8006FAD8 06004104 */  bgez       $v0, .Llevel_35_8006FAF4
    /* 29D5078 8006FADC 02000224 */   addiu     $v0, $zero, 0x2
    /* 29D507C 8006FAE0 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 29D5080 8006FAE4 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 29D5084 8006FAE8 00000000 */  nop
    /* 29D5088 8006FAEC 0E006214 */  bne        $v1, $v0, .Llevel_35_8006FB28
    /* 29D508C 8006FAF0 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_35_8006FAF4:
    /* 29D5090 8006FAF4 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 29D5094 8006FAF8 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 29D5098 8006FAFC 00000000 */  nop
    /* 29D509C 8006FB00 810C6228 */  slti       $v0, $v1, 0xC81
    /* 29D50A0 8006FB04 0A004014 */  bnez       $v0, .Llevel_35_8006FB30
    /* 29D50A4 8006FB08 00000000 */   nop
    /* 29D50A8 8006FB0C 0780023C */  lui        $v0, %hi(D_8006A0AC)
    /* 29D50AC 8006FB10 ACA0428C */  lw         $v0, %lo(D_8006A0AC)($v0)
    /* 29D50B0 8006FB14 00000000 */  nop
    /* 29D50B4 8006FB18 40100200 */  sll        $v0, $v0, 1
    /* 29D50B8 8006FB1C 2A104300 */  slt        $v0, $v0, $v1
    /* 29D50BC 8006FB20 03004010 */  beqz       $v0, .Llevel_35_8006FB30
    /* 29D50C0 8006FB24 0D000424 */   addiu     $a0, $zero, 0xD
  .Llevel_35_8006FB28:
    /* 29D50C4 8006FB28 76D4000C */  jal        func_800351D8
    /* 29D50C8 8006FB2C 00000000 */   nop
  .Llevel_35_8006FB30:
    /* 29D50CC 8006FB30 1800BF8F */  lw         $ra, 0x18($sp)
    /* 29D50D0 8006FB34 1400B18F */  lw         $s1, 0x14($sp)
    /* 29D50D4 8006FB38 1000B08F */  lw         $s0, 0x10($sp)
    /* 29D50D8 8006FB3C 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 29D50DC 8006FB40 0800E003 */  jr         $ra
    /* 29D50E0 8006FB44 00000000 */   nop
endlabel func_level_35_8006EF3C
