.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_35_8006D3C8

dlabel jtbl_level_35_8006D3C8
    /* 29D2964 8006D3C8 10EB0680 */ .word .Llevel_35_8006EB10
    /* 29D2968 8006D3CC 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D296C 8006D3D0 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2970 8006D3D4 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2974 8006D3D8 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2978 8006D3DC 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D297C 8006D3E0 F8EA0680 */ .word .Llevel_35_8006EAF8
    /* 29D2980 8006D3E4 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2984 8006D3E8 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2988 8006D3EC 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D298C 8006D3F0 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2990 8006D3F4 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2994 8006D3F8 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2998 8006D3FC 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D299C 8006D400 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29A0 8006D404 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29A4 8006D408 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29A8 8006D40C 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29AC 8006D410 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29B0 8006D414 10EB0680 */ .word .Llevel_35_8006EB10
    /* 29D29B4 8006D418 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29B8 8006D41C 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29BC 8006D420 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29C0 8006D424 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29C4 8006D428 10EB0680 */ .word .Llevel_35_8006EB10
    /* 29D29C8 8006D42C 10EB0680 */ .word .Llevel_35_8006EB10
    /* 29D29CC 8006D430 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29D0 8006D434 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29D4 8006D438 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29D8 8006D43C 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29DC 8006D440 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29E0 8006D444 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29E4 8006D448 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29E8 8006D44C 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29EC 8006D450 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29F0 8006D454 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29F4 8006D458 10EB0680 */ .word .Llevel_35_8006EB10
    /* 29D29F8 8006D45C 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D29FC 8006D460 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2A00 8006D464 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2A04 8006D468 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2A08 8006D46C 20EB0680 */ .word .Llevel_35_8006EB20
    /* 29D2A0C 8006D470 10EB0680 */ .word .Llevel_35_8006EB10
    /* 29D2A10 8006D474 00000000 */ .word 0x00000000
enddlabel jtbl_level_35_8006D3C8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_35_8006EAA8, 0x88

glabel func_level_35_8006EAA8
    /* 29D4044 8006EAA8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 29D4048 8006EAAC 00210400 */  sll        $a0, $a0, 4
    /* 29D404C 8006EAB0 0780023C */  lui        $v0, %hi(D_800683B0)
    /* 29D4050 8006EAB4 B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* 29D4054 8006EAB8 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 29D4058 8006EABC 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 29D405C 8006EAC0 21208200 */  addu       $a0, $a0, $v0
    /* 29D4060 8006EAC4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 29D4064 8006EAC8 0680013C */  lui        $at, %hi(D_80066F38)
    /* 29D4068 8006EACC 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* 29D406C 8006EAD0 EDFF6324 */  addiu      $v1, $v1, -0x13
    /* 29D4070 8006EAD4 2B00622C */  sltiu      $v0, $v1, 0x2B
    /* 29D4074 8006EAD8 11004010 */  beqz       $v0, .Llevel_35_8006EB20
    /* 29D4078 8006EADC 80100300 */   sll       $v0, $v1, 2
    /* 29D407C 8006EAE0 0780013C */  lui        $at, %hi(jtbl_level_35_8006D3C8)
    /* 29D4080 8006EAE4 21082200 */  addu       $at, $at, $v0
    /* 29D4084 8006EAE8 C8D3228C */  lw         $v0, %lo(jtbl_level_35_8006D3C8)($at)
    /* 29D4088 8006EAEC 00000000 */  nop
    /* 29D408C 8006EAF0 08004000 */  jr         $v0
    /* 29D4090 8006EAF4 00000000 */   nop
  .Llevel_35_8006EAF8:
    /* 29D4094 8006EAF8 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 29D4098 8006EAFC 84A08424 */  addiu      $a0, $a0, %lo(D_8006A084)
    /* 29D409C 8006EB00 B4B7000C */  jal        func_8002DED0
    /* 29D40A0 8006EB04 00000000 */   nop
    /* 29D40A4 8006EB08 C8BA0108 */  j          .Llevel_35_8006EB20
    /* 29D40A8 8006EB0C 00000000 */   nop
  .Llevel_35_8006EB10:
    /* 29D40AC 8006EB10 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* 29D40B0 8006EB14 C4A08424 */  addiu      $a0, $a0, %lo(D_8006A0C4)
    /* 29D40B4 8006EB18 E3B6000C */  jal        func_8002DB8C
    /* 29D40B8 8006EB1C 00000000 */   nop
  .Llevel_35_8006EB20:
    /* 29D40BC 8006EB20 1000BF8F */  lw         $ra, 0x10($sp)
    /* 29D40C0 8006EB24 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 29D40C4 8006EB28 0800E003 */  jr         $ra
    /* 29D40C8 8006EB2C 00000000 */   nop
endlabel func_level_35_8006EAA8
