.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_66_8006D5C8

dlabel jtbl_level_66_8006D5C8
    /* 44B8364 8006D5C8 E4F70680 */ .word .Llevel_66_8006F7E4
    /* 44B8368 8006D5CC 4C040780 */ .word .Llevel_66_8007044C
    /* 44B836C 8006D5D0 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8370 8006D5D4 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8374 8006D5D8 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8378 8006D5DC 4C040780 */ .word .Llevel_66_8007044C
    /* 44B837C 8006D5E0 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8380 8006D5E4 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8384 8006D5E8 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8388 8006D5EC 4C040780 */ .word .Llevel_66_8007044C
    /* 44B838C 8006D5F0 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8390 8006D5F4 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8394 8006D5F8 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8398 8006D5FC 4C040780 */ .word .Llevel_66_8007044C
    /* 44B839C 8006D600 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83A0 8006D604 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83A4 8006D608 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83A8 8006D60C ACFA0680 */ .word .Llevel_66_8006FAAC
    /* 44B83AC 8006D610 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83B0 8006D614 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83B4 8006D618 F8FB0680 */ .word .Llevel_66_8006FBF8
    /* 44B83B8 8006D61C 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83BC 8006D620 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83C0 8006D624 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83C4 8006D628 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83C8 8006D62C F4FD0680 */ .word .Llevel_66_8006FDF4
    /* 44B83CC 8006D630 5CFF0680 */ .word .Llevel_66_8006FF5C
    /* 44B83D0 8006D634 BC000780 */ .word .Llevel_66_800700BC
    /* 44B83D4 8006D638 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83D8 8006D63C 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83DC 8006D640 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83E0 8006D644 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83E4 8006D648 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83E8 8006D64C 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83EC 8006D650 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83F0 8006D654 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83F4 8006D658 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83F8 8006D65C 4C040780 */ .word .Llevel_66_8007044C
    /* 44B83FC 8006D660 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8400 8006D664 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8404 8006D668 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8408 8006D66C 4C040780 */ .word .Llevel_66_8007044C
    /* 44B840C 8006D670 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8410 8006D674 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8414 8006D678 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8418 8006D67C 4C040780 */ .word .Llevel_66_8007044C
    /* 44B841C 8006D680 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8420 8006D684 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8424 8006D688 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8428 8006D68C 4C040780 */ .word .Llevel_66_8007044C
    /* 44B842C 8006D690 1C020780 */ .word .Llevel_66_8007021C
    /* 44B8430 8006D694 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8434 8006D698 4C040780 */ .word .Llevel_66_8007044C
    /* 44B8438 8006D69C 7C020780 */ .word .Llevel_66_8007027C
enddlabel jtbl_level_66_8006D5C8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_66_8006F7A4, 0xCC0

glabel func_level_66_8006F7A4
    /* 44BA540 8006F7A4 0780023C */  lui        $v0, %hi(D_8006A040)
    /* 44BA544 8006F7A8 40A0428C */  lw         $v0, %lo(D_8006A040)($v0)
    /* 44BA548 8006F7AC E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 44BA54C 8006F7B0 1800BFAF */  sw         $ra, 0x18($sp)
    /* 44BA550 8006F7B4 1400B1AF */  sw         $s1, 0x14($sp)
    /* 44BA554 8006F7B8 F8FF4324 */  addiu      $v1, $v0, -0x8
    /* 44BA558 8006F7BC 3600622C */  sltiu      $v0, $v1, 0x36
    /* 44BA55C 8006F7C0 22034010 */  beqz       $v0, .Llevel_66_8007044C
    /* 44BA560 8006F7C4 1000B0AF */   sw        $s0, 0x10($sp)
    /* 44BA564 8006F7C8 80100300 */  sll        $v0, $v1, 2
    /* 44BA568 8006F7CC 0780013C */  lui        $at, %hi(jtbl_level_66_8006D5C8)
    /* 44BA56C 8006F7D0 21082200 */  addu       $at, $at, $v0
    /* 44BA570 8006F7D4 C8D5228C */  lw         $v0, %lo(jtbl_level_66_8006D5C8)($at)
    /* 44BA574 8006F7D8 00000000 */  nop
    /* 44BA578 8006F7DC 08004000 */  jr         $v0
    /* 44BA57C 8006F7E0 00000000 */   nop
  .Llevel_66_8006F7E4:
    /* 44BA580 8006F7E4 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 44BA584 8006F7E8 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 44BA588 8006F7EC 01000224 */  addiu      $v0, $zero, 0x1
    /* 44BA58C 8006F7F0 88006214 */  bne        $v1, $v0, .Llevel_66_8006FA14
    /* 44BA590 8006F7F4 00000000 */   nop
    /* 44BA594 8006F7F8 0780023C */  lui        $v0, %hi(D_8006A1AD)
    /* 44BA598 8006F7FC ADA14290 */  lbu        $v0, %lo(D_8006A1AD)($v0)
    /* 44BA59C 8006F800 00000000 */  nop
    /* 44BA5A0 8006F804 09004010 */  beqz       $v0, .Llevel_66_8006F82C
    /* 44BA5A4 8006F808 00000000 */   nop
    /* 44BA5A8 8006F80C 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 44BA5AC 8006F810 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 44BA5B0 8006F814 00000000 */  nop
    /* 44BA5B4 8006F818 40004230 */  andi       $v0, $v0, 0x40
    /* 44BA5B8 8006F81C 03004010 */  beqz       $v0, .Llevel_66_8006F82C
    /* 44BA5BC 8006F820 01000224 */   addiu     $v0, $zero, 0x1
    /* 44BA5C0 8006F824 0780013C */  lui        $at, %hi(D_8006A1AE)
    /* 44BA5C4 8006F828 AEA122A0 */  sb         $v0, %lo(D_8006A1AE)($at)
  .Llevel_66_8006F82C:
    /* 44BA5C8 8006F82C 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 44BA5CC 8006F830 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 44BA5D0 8006F834 00000000 */  nop
    /* 44BA5D4 8006F838 3F004014 */  bnez       $v0, .Llevel_66_8006F938
    /* 44BA5D8 8006F83C 00000000 */   nop
    /* 44BA5DC 8006F840 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 44BA5E0 8006F844 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 44BA5E4 8006F848 00000000 */  nop
    /* 44BA5E8 8006F84C 10004228 */  slti       $v0, $v0, 0x10
    /* 44BA5EC 8006F850 39004014 */  bnez       $v0, .Llevel_66_8006F938
    /* 44BA5F0 8006F854 00000000 */   nop
    /* 44BA5F4 8006F858 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 44BA5F8 8006F85C DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 44BA5FC 8006F860 00000000 */  nop
    /* 44BA600 8006F864 17004228 */  slti       $v0, $v0, 0x17
    /* 44BA604 8006F868 33004010 */  beqz       $v0, .Llevel_66_8006F938
    /* 44BA608 8006F86C 00000000 */   nop
    /* 44BA60C 8006F870 0780033C */  lui        $v1, %hi(D_8006A0C4)
    /* 44BA610 8006F874 C4A0638C */  lw         $v1, %lo(D_8006A0C4)($v1)
    /* 44BA614 8006F878 0780023C */  lui        $v0, %hi(D_8006A084)
    /* 44BA618 8006F87C 84A0428C */  lw         $v0, %lo(D_8006A084)($v0)
    /* 44BA61C 8006F880 00000000 */  nop
    /* 44BA620 8006F884 18006200 */  mult       $v1, $v0
    /* 44BA624 8006F888 0780033C */  lui        $v1, %hi(D_8006A0C8)
    /* 44BA628 8006F88C C8A0638C */  lw         $v1, %lo(D_8006A0C8)($v1)
    /* 44BA62C 8006F890 12280000 */  mflo       $a1
    /* 44BA630 8006F894 0780023C */  lui        $v0, %hi(D_8006A088)
    /* 44BA634 8006F898 88A0428C */  lw         $v0, %lo(D_8006A088)($v0)
    /* 44BA638 8006F89C 00000000 */  nop
    /* 44BA63C 8006F8A0 18006200 */  mult       $v1, $v0
    /* 44BA640 8006F8A4 0780033C */  lui        $v1, %hi(D_8006A0CC)
    /* 44BA644 8006F8A8 CCA0638C */  lw         $v1, %lo(D_8006A0CC)($v1)
    /* 44BA648 8006F8AC 12200000 */  mflo       $a0
    /* 44BA64C 8006F8B0 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 44BA650 8006F8B4 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 44BA654 8006F8B8 00000000 */  nop
    /* 44BA658 8006F8BC 18006200 */  mult       $v1, $v0
    /* 44BA65C 8006F8C0 2110A400 */  addu       $v0, $a1, $a0
    /* 44BA660 8006F8C4 12180000 */  mflo       $v1
    /* 44BA664 8006F8C8 21104300 */  addu       $v0, $v0, $v1
    /* 44BA668 8006F8CC 1A004104 */  bgez       $v0, .Llevel_66_8006F938
    /* 44BA66C 8006F8D0 00000000 */   nop
    /* 44BA670 8006F8D4 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 44BA674 8006F8D8 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 44BA678 8006F8DC 00000000 */  nop
    /* 44BA67C 8006F8E0 0D004010 */  beqz       $v0, .Llevel_66_8006F918
    /* 44BA680 8006F8E4 00000000 */   nop
    /* 44BA684 8006F8E8 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 44BA688 8006F8EC A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 44BA68C 8006F8F0 00000000 */  nop
    /* 44BA690 8006F8F4 010F6228 */  slti       $v0, $v1, 0xF01
    /* 44BA694 8006F8F8 03004014 */  bnez       $v0, .Llevel_66_8006F908
    /* 44BA698 8006F8FC 81076228 */   slti      $v0, $v1, 0x781
    /* 44BA69C 8006F900 11C10108 */  j          .Llevel_66_80070444
    /* 44BA6A0 8006F904 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_66_8006F908:
    /* 44BA6A4 8006F908 CE024014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BA6A8 8006F90C 01000424 */   addiu     $a0, $zero, 0x1
    /* 44BA6AC 8006F910 11C10108 */  j          .Llevel_66_80070444
    /* 44BA6B0 8006F914 16000424 */   addiu     $a0, $zero, 0x16
  .Llevel_66_8006F918:
    /* 44BA6B4 8006F918 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 44BA6B8 8006F91C A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 44BA6BC 8006F920 00000000 */  nop
    /* 44BA6C0 8006F924 80074228 */  slti       $v0, $v0, 0x780
    /* 44BA6C4 8006F928 C6024014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BA6C8 8006F92C 21200000 */   addu      $a0, $zero, $zero
    /* 44BA6CC 8006F930 11C10108 */  j          .Llevel_66_80070444
    /* 44BA6D0 8006F934 03000424 */   addiu     $a0, $zero, 0x3
  .Llevel_66_8006F938:
    /* 44BA6D4 8006F938 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 44BA6D8 8006F93C A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 44BA6DC 8006F940 00000000 */  nop
    /* 44BA6E0 8006F944 80004230 */  andi       $v0, $v0, 0x80
    /* 44BA6E4 8006F948 0C004010 */  beqz       $v0, .Llevel_66_8006F97C
    /* 44BA6E8 8006F94C 00000000 */   nop
    /* 44BA6EC 8006F950 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 44BA6F0 8006F954 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 44BA6F4 8006F958 00000000 */  nop
    /* 44BA6F8 8006F95C 07004104 */  bgez       $v0, .Llevel_66_8006F97C
    /* 44BA6FC 8006F960 00000000 */   nop
    /* 44BA700 8006F964 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 44BA704 8006F968 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 44BA708 8006F96C 00000000 */  nop
    /* 44BA70C 8006F970 05004228 */  slti       $v0, $v0, 0x5
    /* 44BA710 8006F974 B3024010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BA714 8006F978 15000424 */   addiu     $a0, $zero, 0x15
  .Llevel_66_8006F97C:
    /* 44BA718 8006F97C 0780023C */  lui        $v0, %hi(D_8006A1AD)
    /* 44BA71C 8006F980 ADA14290 */  lbu        $v0, %lo(D_8006A1AD)($v0)
    /* 44BA720 8006F984 00000000 */  nop
    /* 44BA724 8006F988 11004010 */  beqz       $v0, .Llevel_66_8006F9D0
    /* 44BA728 8006F98C 00000000 */   nop
    /* 44BA72C 8006F990 0780023C */  lui        $v0, %hi(D_8006A1AE)
    /* 44BA730 8006F994 AEA14290 */  lbu        $v0, %lo(D_8006A1AE)($v0)
    /* 44BA734 8006F998 00000000 */  nop
    /* 44BA738 8006F99C 0C004010 */  beqz       $v0, .Llevel_66_8006F9D0
    /* 44BA73C 8006F9A0 00000000 */   nop
    /* 44BA740 8006F9A4 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 44BA744 8006F9A8 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 44BA748 8006F9AC 00000000 */  nop
    /* 44BA74C 8006F9B0 A6024104 */  bgez       $v0, .Llevel_66_8007044C
    /* 44BA750 8006F9B4 00000000 */   nop
    /* 44BA754 8006F9B8 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 44BA758 8006F9BC 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 44BA75C 8006F9C0 00000000 */  nop
    /* 44BA760 8006F9C4 05004228 */  slti       $v0, $v0, 0x5
    /* 44BA764 8006F9C8 9E024010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BA768 8006F9CC 10000424 */   addiu     $a0, $zero, 0x10
  .Llevel_66_8006F9D0:
    /* 44BA76C 8006F9D0 0780033C */  lui        $v1, %hi(D_8006A098)
    /* 44BA770 8006F9D4 98A0638C */  lw         $v1, %lo(D_8006A098)($v1)
    /* 44BA774 8006F9D8 00000000 */  nop
    /* 44BA778 8006F9DC 9B026104 */  bgez       $v1, .Llevel_66_8007044C
    /* 44BA77C 8006F9E0 00000000 */   nop
    /* 44BA780 8006F9E4 0780043C */  lui        $a0, %hi(D_8006A04C)
    /* 44BA784 8006F9E8 4CA0848C */  lw         $a0, %lo(D_8006A04C)($a0)
    /* 44BA788 8006F9EC 00000000 */  nop
    /* 44BA78C 8006F9F0 05008228 */  slti       $v0, $a0, 0x5
    /* 44BA790 8006F9F4 95024014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BA794 8006F9F8 00E76228 */   slti      $v0, $v1, -0x1900
    /* 44BA798 8006F9FC 03004014 */  bnez       $v0, .Llevel_66_8006FA0C
    /* 44BA79C 8006FA00 5B008228 */   slti      $v0, $a0, 0x5B
    /* 44BA7A0 8006FA04 91024014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BA7A4 8006FA08 00000000 */   nop
  .Llevel_66_8006FA0C:
    /* 44BA7A8 8006FA0C 11C10108 */  j          .Llevel_66_80070444
    /* 44BA7AC 8006FA10 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_66_8006FA14:
    /* 44BA7B0 8006FA14 0780023C */  lui        $v0, %hi(D_8006A014)
    /* 44BA7B4 8006FA18 14A0428C */  lw         $v0, %lo(D_8006A014)($v0)
    /* 44BA7B8 8006FA1C 00000000 */  nop
    /* 44BA7BC 8006FA20 20004230 */  andi       $v0, $v0, 0x20
    /* 44BA7C0 8006FA24 89024014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BA7C4 8006FA28 00000000 */   nop
    /* 44BA7C8 8006FA2C 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 44BA7CC 8006FA30 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 44BA7D0 8006FA34 00000000 */  nop
    /* 44BA7D4 8006FA38 19004228 */  slti       $v0, $v0, 0x19
    /* 44BA7D8 8006FA3C 83024014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BA7DC 8006FA40 00000000 */   nop
    /* 44BA7E0 8006FA44 0780023C */  lui        $v0, %hi(D_8006A248)
    /* 44BA7E4 8006FA48 48A2428C */  lw         $v0, %lo(D_8006A248)($v0)
    /* 44BA7E8 8006FA4C 00000000 */  nop
    /* 44BA7EC 8006FA50 03004104 */  bgez       $v0, .Llevel_66_8006FA60
    /* 44BA7F0 8006FA54 0A000224 */   addiu     $v0, $zero, 0xA
    /* 44BA7F4 8006FA58 11C10108 */  j          .Llevel_66_80070444
    /* 44BA7F8 8006FA5C 1F000424 */   addiu     $a0, $zero, 0x1F
  .Llevel_66_8006FA60:
    /* 44BA7FC 8006FA60 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 44BA800 8006FA64 3CA1638C */  lw         $v1, %lo(D_8006A13C)($v1)
    /* 44BA804 8006FA68 00000000 */  nop
    /* 44BA808 8006FA6C 03006214 */  bne        $v1, $v0, .Llevel_66_8006FA7C
    /* 44BA80C 8006FA70 F5FF6224 */   addiu     $v0, $v1, -0xB
    /* 44BA810 8006FA74 11C10108 */  j          .Llevel_66_80070444
    /* 44BA814 8006FA78 2C000424 */   addiu     $a0, $zero, 0x2C
  .Llevel_66_8006FA7C:
    /* 44BA818 8006FA7C 0200422C */  sltiu      $v0, $v0, 0x2
    /* 44BA81C 8006FA80 03004010 */  beqz       $v0, .Llevel_66_8006FA90
    /* 44BA820 8006FA84 00000000 */   nop
    /* 44BA824 8006FA88 11C10108 */  j          .Llevel_66_80070444
    /* 44BA828 8006FA8C 29000424 */   addiu     $a0, $zero, 0x29
  .Llevel_66_8006FA90:
    /* 44BA82C 8006FA90 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 44BA830 8006FA94 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 44BA834 8006FA98 00000000 */  nop
    /* 44BA838 8006FA9C 69024010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BA83C 8006FAA0 21200000 */   addu      $a0, $zero, $zero
    /* 44BA840 8006FAA4 11C10108 */  j          .Llevel_66_80070444
    /* 44BA844 8006FAA8 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_66_8006FAAC:
    /* 44BA848 8006FAAC 8AAC000C */  jal        func_8002B228
    /* 44BA84C 8006FAB0 00000000 */   nop
    /* 44BA850 8006FAB4 65024014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BA854 8006FAB8 00000000 */   nop
    /* 44BA858 8006FABC 0780023C */  lui        $v0, %hi(D_8006A1AD)
    /* 44BA85C 8006FAC0 ADA14290 */  lbu        $v0, %lo(D_8006A1AD)($v0)
    /* 44BA860 8006FAC4 00000000 */  nop
    /* 44BA864 8006FAC8 09004010 */  beqz       $v0, .Llevel_66_8006FAF0
    /* 44BA868 8006FACC 00000000 */   nop
    /* 44BA86C 8006FAD0 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 44BA870 8006FAD4 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 44BA874 8006FAD8 00000000 */  nop
    /* 44BA878 8006FADC 40004230 */  andi       $v0, $v0, 0x40
    /* 44BA87C 8006FAE0 03004010 */  beqz       $v0, .Llevel_66_8006FAF0
    /* 44BA880 8006FAE4 01000224 */   addiu     $v0, $zero, 0x1
    /* 44BA884 8006FAE8 0780013C */  lui        $at, %hi(D_8006A1AE)
    /* 44BA888 8006FAEC AEA122A0 */  sb         $v0, %lo(D_8006A1AE)($at)
  .Llevel_66_8006FAF0:
    /* 44BA88C 8006FAF0 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 44BA890 8006FAF4 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 44BA894 8006FAF8 00000000 */  nop
    /* 44BA898 8006FAFC 17004228 */  slti       $v0, $v0, 0x17
    /* 44BA89C 8006FB00 12004014 */  bnez       $v0, .Llevel_66_8006FB4C
    /* 44BA8A0 8006FB04 00000000 */   nop
    /* 44BA8A4 8006FB08 0780033C */  lui        $v1, %hi(D_8006A084)
    /* 44BA8A8 8006FB0C 84A0638C */  lw         $v1, %lo(D_8006A084)($v1)
    /* 44BA8AC 8006FB10 0780023C */  lui        $v0, %hi(D_8006A0C4)
    /* 44BA8B0 8006FB14 C4A0428C */  lw         $v0, %lo(D_8006A0C4)($v0)
    /* 44BA8B4 8006FB18 00000000 */  nop
    /* 44BA8B8 8006FB1C 18006200 */  mult       $v1, $v0
    /* 44BA8BC 8006FB20 0780033C */  lui        $v1, %hi(D_8006A088)
    /* 44BA8C0 8006FB24 88A0638C */  lw         $v1, %lo(D_8006A088)($v1)
    /* 44BA8C4 8006FB28 12200000 */  mflo       $a0
    /* 44BA8C8 8006FB2C 0780023C */  lui        $v0, %hi(D_8006A0C8)
    /* 44BA8CC 8006FB30 C8A0428C */  lw         $v0, %lo(D_8006A0C8)($v0)
    /* 44BA8D0 8006FB34 00000000 */  nop
    /* 44BA8D4 8006FB38 18006200 */  mult       $v1, $v0
    /* 44BA8D8 8006FB3C 12180000 */  mflo       $v1
    /* 44BA8DC 8006FB40 21108300 */  addu       $v0, $a0, $v1
    /* 44BA8E0 8006FB44 3F024004 */  bltz       $v0, .Llevel_66_80070444
    /* 44BA8E4 8006FB48 0D000424 */   addiu     $a0, $zero, 0xD
  .Llevel_66_8006FB4C:
    /* 44BA8E8 8006FB4C 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 44BA8EC 8006FB50 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 44BA8F0 8006FB54 00000000 */  nop
    /* 44BA8F4 8006FB58 810C6228 */  slti       $v0, $v1, 0xC81
    /* 44BA8F8 8006FB5C 08004014 */  bnez       $v0, .Llevel_66_8006FB80
    /* 44BA8FC 8006FB60 00000000 */   nop
    /* 44BA900 8006FB64 0780023C */  lui        $v0, %hi(D_8006A0AC)
    /* 44BA904 8006FB68 ACA0428C */  lw         $v0, %lo(D_8006A0AC)($v0)
    /* 44BA908 8006FB6C 00000000 */  nop
    /* 44BA90C 8006FB70 40100200 */  sll        $v0, $v0, 1
    /* 44BA910 8006FB74 2A104300 */  slt        $v0, $v0, $v1
    /* 44BA914 8006FB78 32024014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BA918 8006FB7C 0D000424 */   addiu     $a0, $zero, 0xD
  .Llevel_66_8006FB80:
    /* 44BA91C 8006FB80 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 44BA920 8006FB84 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 44BA924 8006FB88 00000000 */  nop
    /* 44BA928 8006FB8C 07004014 */  bnez       $v0, .Llevel_66_8006FBAC
    /* 44BA92C 8006FB90 00000000 */   nop
    /* 44BA930 8006FB94 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 44BA934 8006FB98 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 44BA938 8006FB9C 00000000 */  nop
    /* 44BA93C 8006FBA0 05004228 */  slti       $v0, $v0, 0x5
    /* 44BA940 8006FBA4 27024010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BA944 8006FBA8 3D000424 */   addiu     $a0, $zero, 0x3D
  .Llevel_66_8006FBAC:
    /* 44BA948 8006FBAC 0780023C */  lui        $v0, %hi(D_8006A1AE)
    /* 44BA94C 8006FBB0 AEA14290 */  lbu        $v0, %lo(D_8006A1AE)($v0)
    /* 44BA950 8006FBB4 00000000 */  nop
    /* 44BA954 8006FBB8 08004010 */  beqz       $v0, .Llevel_66_8006FBDC
    /* 44BA958 8006FBBC 00000000 */   nop
    /* 44BA95C 8006FBC0 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 44BA960 8006FBC4 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 44BA964 8006FBC8 00000000 */  nop
    /* 44BA968 8006FBCC 1F024104 */  bgez       $v0, .Llevel_66_8007044C
    /* 44BA96C 8006FBD0 10000424 */   addiu     $a0, $zero, 0x10
    /* 44BA970 8006FBD4 11C10108 */  j          .Llevel_66_80070444
    /* 44BA974 8006FBD8 00000000 */   nop
  .Llevel_66_8006FBDC:
    /* 44BA978 8006FBDC 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 44BA97C 8006FBE0 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 44BA980 8006FBE4 00000000 */  nop
    /* 44BA984 8006FBE8 18024104 */  bgez       $v0, .Llevel_66_8007044C
    /* 44BA988 8006FBEC 15000424 */   addiu     $a0, $zero, 0x15
    /* 44BA98C 8006FBF0 11C10108 */  j          .Llevel_66_80070444
    /* 44BA990 8006FBF4 00000000 */   nop
  .Llevel_66_8006FBF8:
    /* 44BA994 8006FBF8 0780023C */  lui        $v0, %hi(D_8006A1AD)
    /* 44BA998 8006FBFC ADA14290 */  lbu        $v0, %lo(D_8006A1AD)($v0)
    /* 44BA99C 8006FC00 00000000 */  nop
    /* 44BA9A0 8006FC04 09004010 */  beqz       $v0, .Llevel_66_8006FC2C
    /* 44BA9A4 8006FC08 00000000 */   nop
    /* 44BA9A8 8006FC0C 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 44BA9AC 8006FC10 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 44BA9B0 8006FC14 00000000 */  nop
    /* 44BA9B4 8006FC18 40004230 */  andi       $v0, $v0, 0x40
    /* 44BA9B8 8006FC1C 03004010 */  beqz       $v0, .Llevel_66_8006FC2C
    /* 44BA9BC 8006FC20 01000224 */   addiu     $v0, $zero, 0x1
    /* 44BA9C0 8006FC24 0780013C */  lui        $at, %hi(D_8006A1AE)
    /* 44BA9C4 8006FC28 AEA122A0 */  sb         $v0, %lo(D_8006A1AE)($at)
  .Llevel_66_8006FC2C:
    /* 44BA9C8 8006FC2C 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 44BA9CC 8006FC30 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 44BA9D0 8006FC34 00000000 */  nop
    /* 44BA9D4 8006FC38 3F004014 */  bnez       $v0, .Llevel_66_8006FD38
    /* 44BA9D8 8006FC3C 00000000 */   nop
    /* 44BA9DC 8006FC40 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 44BA9E0 8006FC44 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 44BA9E4 8006FC48 00000000 */  nop
    /* 44BA9E8 8006FC4C 10004228 */  slti       $v0, $v0, 0x10
    /* 44BA9EC 8006FC50 39004014 */  bnez       $v0, .Llevel_66_8006FD38
    /* 44BA9F0 8006FC54 00000000 */   nop
    /* 44BA9F4 8006FC58 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 44BA9F8 8006FC5C DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 44BA9FC 8006FC60 00000000 */  nop
    /* 44BAA00 8006FC64 17004228 */  slti       $v0, $v0, 0x17
    /* 44BAA04 8006FC68 33004010 */  beqz       $v0, .Llevel_66_8006FD38
    /* 44BAA08 8006FC6C 00000000 */   nop
    /* 44BAA0C 8006FC70 0780033C */  lui        $v1, %hi(D_8006A0C4)
    /* 44BAA10 8006FC74 C4A0638C */  lw         $v1, %lo(D_8006A0C4)($v1)
    /* 44BAA14 8006FC78 0780023C */  lui        $v0, %hi(D_8006A084)
    /* 44BAA18 8006FC7C 84A0428C */  lw         $v0, %lo(D_8006A084)($v0)
    /* 44BAA1C 8006FC80 00000000 */  nop
    /* 44BAA20 8006FC84 18006200 */  mult       $v1, $v0
    /* 44BAA24 8006FC88 0780033C */  lui        $v1, %hi(D_8006A0C8)
    /* 44BAA28 8006FC8C C8A0638C */  lw         $v1, %lo(D_8006A0C8)($v1)
    /* 44BAA2C 8006FC90 12280000 */  mflo       $a1
    /* 44BAA30 8006FC94 0780023C */  lui        $v0, %hi(D_8006A088)
    /* 44BAA34 8006FC98 88A0428C */  lw         $v0, %lo(D_8006A088)($v0)
    /* 44BAA38 8006FC9C 00000000 */  nop
    /* 44BAA3C 8006FCA0 18006200 */  mult       $v1, $v0
    /* 44BAA40 8006FCA4 0780033C */  lui        $v1, %hi(D_8006A0CC)
    /* 44BAA44 8006FCA8 CCA0638C */  lw         $v1, %lo(D_8006A0CC)($v1)
    /* 44BAA48 8006FCAC 12200000 */  mflo       $a0
    /* 44BAA4C 8006FCB0 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 44BAA50 8006FCB4 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 44BAA54 8006FCB8 00000000 */  nop
    /* 44BAA58 8006FCBC 18006200 */  mult       $v1, $v0
    /* 44BAA5C 8006FCC0 2110A400 */  addu       $v0, $a1, $a0
    /* 44BAA60 8006FCC4 12180000 */  mflo       $v1
    /* 44BAA64 8006FCC8 21104300 */  addu       $v0, $v0, $v1
    /* 44BAA68 8006FCCC 1A004104 */  bgez       $v0, .Llevel_66_8006FD38
    /* 44BAA6C 8006FCD0 00000000 */   nop
    /* 44BAA70 8006FCD4 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 44BAA74 8006FCD8 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 44BAA78 8006FCDC 00000000 */  nop
    /* 44BAA7C 8006FCE0 0D004010 */  beqz       $v0, .Llevel_66_8006FD18
    /* 44BAA80 8006FCE4 00000000 */   nop
    /* 44BAA84 8006FCE8 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 44BAA88 8006FCEC A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 44BAA8C 8006FCF0 00000000 */  nop
    /* 44BAA90 8006FCF4 010F6228 */  slti       $v0, $v1, 0xF01
    /* 44BAA94 8006FCF8 03004014 */  bnez       $v0, .Llevel_66_8006FD08
    /* 44BAA98 8006FCFC 81076228 */   slti      $v0, $v1, 0x781
    /* 44BAA9C 8006FD00 11C10108 */  j          .Llevel_66_80070444
    /* 44BAAA0 8006FD04 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_66_8006FD08:
    /* 44BAAA4 8006FD08 CE014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAAA8 8006FD0C 01000424 */   addiu     $a0, $zero, 0x1
    /* 44BAAAC 8006FD10 11C10108 */  j          .Llevel_66_80070444
    /* 44BAAB0 8006FD14 16000424 */   addiu     $a0, $zero, 0x16
  .Llevel_66_8006FD18:
    /* 44BAAB4 8006FD18 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 44BAAB8 8006FD1C A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 44BAABC 8006FD20 00000000 */  nop
    /* 44BAAC0 8006FD24 80074228 */  slti       $v0, $v0, 0x780
    /* 44BAAC4 8006FD28 C6014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAAC8 8006FD2C 21200000 */   addu      $a0, $zero, $zero
    /* 44BAACC 8006FD30 11C10108 */  j          .Llevel_66_80070444
    /* 44BAAD0 8006FD34 03000424 */   addiu     $a0, $zero, 0x3
  .Llevel_66_8006FD38:
    /* 44BAAD4 8006FD38 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 44BAAD8 8006FD3C A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 44BAADC 8006FD40 00000000 */  nop
    /* 44BAAE0 8006FD44 80004230 */  andi       $v0, $v0, 0x80
    /* 44BAAE4 8006FD48 06004010 */  beqz       $v0, .Llevel_66_8006FD64
    /* 44BAAE8 8006FD4C 01000224 */   addiu     $v0, $zero, 0x1
    /* 44BAAEC 8006FD50 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 44BAAF0 8006FD54 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 44BAAF4 8006FD58 00000000 */  nop
    /* 44BAAF8 8006FD5C B9016210 */  beq        $v1, $v0, .Llevel_66_80070444
    /* 44BAAFC 8006FD60 15000424 */   addiu     $a0, $zero, 0x15
  .Llevel_66_8006FD64:
    /* 44BAB00 8006FD64 0780023C */  lui        $v0, %hi(D_8006A1AD)
    /* 44BAB04 8006FD68 ADA14290 */  lbu        $v0, %lo(D_8006A1AD)($v0)
    /* 44BAB08 8006FD6C 00000000 */  nop
    /* 44BAB0C 8006FD70 0D004010 */  beqz       $v0, .Llevel_66_8006FDA8
    /* 44BAB10 8006FD74 00000000 */   nop
    /* 44BAB14 8006FD78 0780023C */  lui        $v0, %hi(D_8006A1AE)
    /* 44BAB18 8006FD7C AEA14290 */  lbu        $v0, %lo(D_8006A1AE)($v0)
    /* 44BAB1C 8006FD80 00000000 */  nop
    /* 44BAB20 8006FD84 08004010 */  beqz       $v0, .Llevel_66_8006FDA8
    /* 44BAB24 8006FD88 01000224 */   addiu     $v0, $zero, 0x1
    /* 44BAB28 8006FD8C 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 44BAB2C 8006FD90 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 44BAB30 8006FD94 00000000 */  nop
    /* 44BAB34 8006FD98 AC016214 */  bne        $v1, $v0, .Llevel_66_8007044C
    /* 44BAB38 8006FD9C 10000424 */   addiu     $a0, $zero, 0x10
    /* 44BAB3C 8006FDA0 11C10108 */  j          .Llevel_66_80070444
    /* 44BAB40 8006FDA4 00000000 */   nop
  .Llevel_66_8006FDA8:
    /* 44BAB44 8006FDA8 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 44BAB48 8006FDAC 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 44BAB4C 8006FDB0 01000224 */  addiu      $v0, $zero, 0x1
    /* 44BAB50 8006FDB4 A5016214 */  bne        $v1, $v0, .Llevel_66_8007044C
    /* 44BAB54 8006FDB8 00000000 */   nop
    /* 44BAB58 8006FDBC 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 44BAB5C 8006FDC0 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 44BAB60 8006FDC4 00000000 */  nop
    /* 44BAB64 8006FDC8 00E74228 */  slti       $v0, $v0, -0x1900
    /* 44BAB68 8006FDCC 9D014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAB6C 8006FDD0 06000424 */   addiu     $a0, $zero, 0x6
    /* 44BAB70 8006FDD4 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 44BAB74 8006FDD8 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 44BAB78 8006FDDC 00000000 */  nop
    /* 44BAB7C 8006FDE0 5B004228 */  slti       $v0, $v0, 0x5B
    /* 44BAB80 8006FDE4 97014010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BAB84 8006FDE8 00000000 */   nop
    /* 44BAB88 8006FDEC 13C10108 */  j          .Llevel_66_8007044C
    /* 44BAB8C 8006FDF0 00000000 */   nop
  .Llevel_66_8006FDF4:
    /* 44BAB90 8006FDF4 2EAC000C */  jal        func_8002B0B8
    /* 44BAB94 8006FDF8 00000000 */   nop
    /* 44BAB98 8006FDFC 93014014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BAB9C 8006FE00 00000000 */   nop
    /* 44BABA0 8006FE04 0780113C */  lui        $s1, %hi(D_8006A0B0)
    /* 44BABA4 8006FE08 B0A03126 */  addiu      $s1, $s1, %lo(D_8006A0B0)
    /* 44BABA8 8006FE0C 0000228E */  lw         $v0, 0x0($s1)
    /* 44BABAC 8006FE10 00000000 */  nop
    /* 44BABB0 8006FE14 22004014 */  bnez       $v0, .Llevel_66_8006FEA0
    /* 44BABB4 8006FE18 00000000 */   nop
    /* 44BABB8 8006FE1C 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 44BABBC 8006FE20 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 44BABC0 8006FE24 00000000 */  nop
    /* 44BABC4 8006FE28 17004228 */  slti       $v0, $v0, 0x17
    /* 44BABC8 8006FE2C 03004014 */  bnez       $v0, .Llevel_66_8006FE3C
    /* 44BABCC 8006FE30 00000000 */   nop
    /* 44BABD0 8006FE34 76D4000C */  jal        func_800351D8
    /* 44BABD4 8006FE38 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_66_8006FE3C:
    /* 44BABD8 8006FE3C 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 44BABDC 8006FE40 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 44BABE0 8006FE44 00000000 */  nop
    /* 44BABE4 8006FE48 0D004018 */  blez       $v0, .Llevel_66_8006FE80
    /* 44BABE8 8006FE4C 00000000 */   nop
    /* 44BABEC 8006FE50 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 44BABF0 8006FE54 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 44BABF4 8006FE58 00000000 */  nop
    /* 44BABF8 8006FE5C 010F6228 */  slti       $v0, $v1, 0xF01
    /* 44BABFC 8006FE60 03004014 */  bnez       $v0, .Llevel_66_8006FE70
    /* 44BAC00 8006FE64 81076228 */   slti      $v0, $v1, 0x781
    /* 44BAC04 8006FE68 11C10108 */  j          .Llevel_66_80070444
    /* 44BAC08 8006FE6C 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_66_8006FE70:
    /* 44BAC0C 8006FE70 74014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAC10 8006FE74 01000424 */   addiu     $a0, $zero, 0x1
    /* 44BAC14 8006FE78 11C10108 */  j          .Llevel_66_80070444
    /* 44BAC18 8006FE7C 16000424 */   addiu     $a0, $zero, 0x16
  .Llevel_66_8006FE80:
    /* 44BAC1C 8006FE80 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 44BAC20 8006FE84 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 44BAC24 8006FE88 00000000 */  nop
    /* 44BAC28 8006FE8C 80074228 */  slti       $v0, $v0, 0x780
    /* 44BAC2C 8006FE90 6C014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAC30 8006FE94 21200000 */   addu      $a0, $zero, $zero
    /* 44BAC34 8006FE98 11C10108 */  j          .Llevel_66_80070444
    /* 44BAC38 8006FE9C 03000424 */   addiu     $a0, $zero, 0x3
  .Llevel_66_8006FEA0:
    /* 44BAC3C 8006FEA0 0780103C */  lui        $s0, %hi(D_800683A4)
    /* 44BAC40 8006FEA4 A4831026 */  addiu      $s0, $s0, %lo(D_800683A4)
    /* 44BAC44 8006FEA8 0000028E */  lw         $v0, 0x0($s0)
    /* 44BAC48 8006FEAC 00000000 */  nop
    /* 44BAC4C 8006FEB0 80004230 */  andi       $v0, $v0, 0x80
    /* 44BAC50 8006FEB4 63014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAC54 8006FEB8 15000424 */   addiu     $a0, $zero, 0x15
    /* 44BAC58 8006FEBC CAB4000C */  jal        func_8002D328
    /* 44BAC5C 8006FEC0 04000424 */   addiu     $a0, $zero, 0x4
    /* 44BAC60 8006FEC4 5F014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAC64 8006FEC8 2F000424 */   addiu     $a0, $zero, 0x2F
    /* 44BAC68 8006FECC 0780023C */  lui        $v0, %hi(D_8006A0B4)
    /* 44BAC6C 8006FED0 B4A0428C */  lw         $v0, %lo(D_8006A0B4)($v0)
    /* 44BAC70 8006FED4 00000000 */  nop
    /* 44BAC74 8006FED8 5A014010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BAC78 8006FEDC 06000424 */   addiu     $a0, $zero, 0x6
    /* 44BAC7C 8006FEE0 0780023C */  lui        $v0, %hi(D_8006A1B4)
    /* 44BAC80 8006FEE4 B4A1428C */  lw         $v0, %lo(D_8006A1B4)($v0)
    /* 44BAC84 8006FEE8 00000000 */  nop
    /* 44BAC88 8006FEEC 55014010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BAC8C 8006FEF0 10000424 */   addiu     $a0, $zero, 0x10
    /* 44BAC90 8006FEF4 0000028E */  lw         $v0, 0x0($s0)
    /* 44BAC94 8006FEF8 00000000 */  nop
    /* 44BAC98 8006FEFC 10004230 */  andi       $v0, $v0, 0x10
    /* 44BAC9C 8006FF00 50014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BACA0 8006FF04 11000424 */   addiu     $a0, $zero, 0x11
    /* 44BACA4 8006FF08 E0FF2426 */  addiu      $a0, $s1, -0x20
    /* 44BACA8 8006FF0C 886E000C */  jal        func_8001BA20
    /* 44BACAC 8006FF10 01000524 */   addiu     $a1, $zero, 0x1
    /* 44BACB0 8006FF14 00044228 */  slti       $v0, $v0, 0x400
    /* 44BACB4 8006FF18 4A014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BACB8 8006FF1C 06000424 */   addiu     $a0, $zero, 0x6
    /* 44BACBC 8006FF20 0780023C */  lui        $v0, %hi(D_8006A044)
    /* 44BACC0 8006FF24 44A0428C */  lw         $v0, %lo(D_8006A044)($v0)
    /* 44BACC4 8006FF28 00000000 */  nop
    /* 44BACC8 8006FF2C 45014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BACCC 8006FF30 22000424 */   addiu     $a0, $zero, 0x22
    /* 44BACD0 8006FF34 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 44BACD4 8006FF38 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 44BACD8 8006FF3C 00000000 */  nop
    /* 44BACDC 8006FF40 6D016228 */  slti       $v0, $v1, 0x16D
    /* 44BACE0 8006FF44 3F014010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BACE4 8006FF48 94FE6228 */   slti      $v0, $v1, -0x16C
    /* 44BACE8 8006FF4C 3F014010 */  beqz       $v0, .Llevel_66_8007044C
    /* 44BACEC 8006FF50 23000424 */   addiu     $a0, $zero, 0x23
    /* 44BACF0 8006FF54 11C10108 */  j          .Llevel_66_80070444
    /* 44BACF4 8006FF58 00000000 */   nop
  .Llevel_66_8006FF5C:
    /* 44BACF8 8006FF5C 2EAC000C */  jal        func_8002B0B8
    /* 44BACFC 8006FF60 00000000 */   nop
    /* 44BAD00 8006FF64 39014014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BAD04 8006FF68 00000000 */   nop
    /* 44BAD08 8006FF6C 0780113C */  lui        $s1, %hi(D_8006A0B0)
    /* 44BAD0C 8006FF70 B0A03126 */  addiu      $s1, $s1, %lo(D_8006A0B0)
    /* 44BAD10 8006FF74 0000228E */  lw         $v0, 0x0($s1)
    /* 44BAD14 8006FF78 00000000 */  nop
    /* 44BAD18 8006FF7C 22004014 */  bnez       $v0, .Llevel_66_80070008
    /* 44BAD1C 8006FF80 00000000 */   nop
    /* 44BAD20 8006FF84 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 44BAD24 8006FF88 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 44BAD28 8006FF8C 00000000 */  nop
    /* 44BAD2C 8006FF90 17004228 */  slti       $v0, $v0, 0x17
    /* 44BAD30 8006FF94 03004014 */  bnez       $v0, .Llevel_66_8006FFA4
    /* 44BAD34 8006FF98 00000000 */   nop
    /* 44BAD38 8006FF9C 76D4000C */  jal        func_800351D8
    /* 44BAD3C 8006FFA0 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_66_8006FFA4:
    /* 44BAD40 8006FFA4 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 44BAD44 8006FFA8 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 44BAD48 8006FFAC 00000000 */  nop
    /* 44BAD4C 8006FFB0 0D004018 */  blez       $v0, .Llevel_66_8006FFE8
    /* 44BAD50 8006FFB4 00000000 */   nop
    /* 44BAD54 8006FFB8 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 44BAD58 8006FFBC A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 44BAD5C 8006FFC0 00000000 */  nop
    /* 44BAD60 8006FFC4 010F6228 */  slti       $v0, $v1, 0xF01
    /* 44BAD64 8006FFC8 03004014 */  bnez       $v0, .Llevel_66_8006FFD8
    /* 44BAD68 8006FFCC 81076228 */   slti      $v0, $v1, 0x781
    /* 44BAD6C 8006FFD0 11C10108 */  j          .Llevel_66_80070444
    /* 44BAD70 8006FFD4 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_66_8006FFD8:
    /* 44BAD74 8006FFD8 1A014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAD78 8006FFDC 01000424 */   addiu     $a0, $zero, 0x1
    /* 44BAD7C 8006FFE0 11C10108 */  j          .Llevel_66_80070444
    /* 44BAD80 8006FFE4 16000424 */   addiu     $a0, $zero, 0x16
  .Llevel_66_8006FFE8:
    /* 44BAD84 8006FFE8 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 44BAD88 8006FFEC A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 44BAD8C 8006FFF0 00000000 */  nop
    /* 44BAD90 8006FFF4 80074228 */  slti       $v0, $v0, 0x780
    /* 44BAD94 8006FFF8 12014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAD98 8006FFFC 21200000 */   addu      $a0, $zero, $zero
    /* 44BAD9C 80070000 11C10108 */  j          .Llevel_66_80070444
    /* 44BADA0 80070004 03000424 */   addiu     $a0, $zero, 0x3
  .Llevel_66_80070008:
    /* 44BADA4 80070008 0780103C */  lui        $s0, %hi(D_800683A4)
    /* 44BADA8 8007000C A4831026 */  addiu      $s0, $s0, %lo(D_800683A4)
    /* 44BADAC 80070010 0000028E */  lw         $v0, 0x0($s0)
    /* 44BADB0 80070014 00000000 */  nop
    /* 44BADB4 80070018 80004230 */  andi       $v0, $v0, 0x80
    /* 44BADB8 8007001C 09014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BADBC 80070020 15000424 */   addiu     $a0, $zero, 0x15
    /* 44BADC0 80070024 CAB4000C */  jal        func_8002D328
    /* 44BADC4 80070028 04000424 */   addiu     $a0, $zero, 0x4
    /* 44BADC8 8007002C 05014014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BADCC 80070030 2F000424 */   addiu     $a0, $zero, 0x2F
    /* 44BADD0 80070034 0780023C */  lui        $v0, %hi(D_8006A0B4)
    /* 44BADD4 80070038 B4A0428C */  lw         $v0, %lo(D_8006A0B4)($v0)
    /* 44BADD8 8007003C 00000000 */  nop
    /* 44BADDC 80070040 00014010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BADE0 80070044 06000424 */   addiu     $a0, $zero, 0x6
    /* 44BADE4 80070048 0780023C */  lui        $v0, %hi(D_8006A1B4)
    /* 44BADE8 8007004C B4A1428C */  lw         $v0, %lo(D_8006A1B4)($v0)
    /* 44BADEC 80070050 00000000 */  nop
    /* 44BADF0 80070054 FB004010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BADF4 80070058 10000424 */   addiu     $a0, $zero, 0x10
    /* 44BADF8 8007005C 0000028E */  lw         $v0, 0x0($s0)
    /* 44BADFC 80070060 00000000 */  nop
    /* 44BAE00 80070064 10004230 */  andi       $v0, $v0, 0x10
    /* 44BAE04 80070068 F6004014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAE08 8007006C 11000424 */   addiu     $a0, $zero, 0x11
    /* 44BAE0C 80070070 E0FF2426 */  addiu      $a0, $s1, -0x20
    /* 44BAE10 80070074 886E000C */  jal        func_8001BA20
    /* 44BAE14 80070078 01000524 */   addiu     $a1, $zero, 0x1
    /* 44BAE18 8007007C 00044228 */  slti       $v0, $v0, 0x400
    /* 44BAE1C 80070080 F0004014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAE20 80070084 06000424 */   addiu     $a0, $zero, 0x6
    /* 44BAE24 80070088 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 44BAE28 8007008C 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 44BAE2C 80070090 00000000 */  nop
    /* 44BAE30 80070094 00014228 */  slti       $v0, $v0, 0x100
    /* 44BAE34 80070098 EC004010 */  beqz       $v0, .Llevel_66_8007044C
    /* 44BAE38 8007009C 00000000 */   nop
    /* 44BAE3C 800700A0 0780023C */  lui        $v0, %hi(D_8006A044)
    /* 44BAE40 800700A4 44A0428C */  lw         $v0, %lo(D_8006A044)($v0)
    /* 44BAE44 800700A8 00000000 */  nop
    /* 44BAE48 800700AC E7004014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BAE4C 800700B0 21000424 */   addiu     $a0, $zero, 0x21
    /* 44BAE50 800700B4 11C10108 */  j          .Llevel_66_80070444
    /* 44BAE54 800700B8 00000000 */   nop
  .Llevel_66_800700BC:
    /* 44BAE58 800700BC 2EAC000C */  jal        func_8002B0B8
    /* 44BAE5C 800700C0 00000000 */   nop
    /* 44BAE60 800700C4 E1004014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BAE64 800700C8 00000000 */   nop
    /* 44BAE68 800700CC 0780113C */  lui        $s1, %hi(D_8006A0B0)
    /* 44BAE6C 800700D0 B0A03126 */  addiu      $s1, $s1, %lo(D_8006A0B0)
    /* 44BAE70 800700D4 0000228E */  lw         $v0, 0x0($s1)
    /* 44BAE74 800700D8 00000000 */  nop
    /* 44BAE78 800700DC 22004014 */  bnez       $v0, .Llevel_66_80070168
    /* 44BAE7C 800700E0 00000000 */   nop
    /* 44BAE80 800700E4 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 44BAE84 800700E8 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 44BAE88 800700EC 00000000 */  nop
    /* 44BAE8C 800700F0 17004228 */  slti       $v0, $v0, 0x17
    /* 44BAE90 800700F4 03004014 */  bnez       $v0, .Llevel_66_80070104
    /* 44BAE94 800700F8 00000000 */   nop
    /* 44BAE98 800700FC 76D4000C */  jal        func_800351D8
    /* 44BAE9C 80070100 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_66_80070104:
    /* 44BAEA0 80070104 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 44BAEA4 80070108 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 44BAEA8 8007010C 00000000 */  nop
    /* 44BAEAC 80070110 0D004018 */  blez       $v0, .Llevel_66_80070148
    /* 44BAEB0 80070114 00000000 */   nop
    /* 44BAEB4 80070118 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 44BAEB8 8007011C A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 44BAEBC 80070120 00000000 */  nop
    /* 44BAEC0 80070124 010F6228 */  slti       $v0, $v1, 0xF01
    /* 44BAEC4 80070128 03004014 */  bnez       $v0, .Llevel_66_80070138
    /* 44BAEC8 8007012C 81076228 */   slti      $v0, $v1, 0x781
    /* 44BAECC 80070130 11C10108 */  j          .Llevel_66_80070444
    /* 44BAED0 80070134 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_66_80070138:
    /* 44BAED4 80070138 C2004014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAED8 8007013C 01000424 */   addiu     $a0, $zero, 0x1
    /* 44BAEDC 80070140 11C10108 */  j          .Llevel_66_80070444
    /* 44BAEE0 80070144 16000424 */   addiu     $a0, $zero, 0x16
  .Llevel_66_80070148:
    /* 44BAEE4 80070148 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 44BAEE8 8007014C A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 44BAEEC 80070150 00000000 */  nop
    /* 44BAEF0 80070154 80074228 */  slti       $v0, $v0, 0x780
    /* 44BAEF4 80070158 BA004014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAEF8 8007015C 21200000 */   addu      $a0, $zero, $zero
    /* 44BAEFC 80070160 11C10108 */  j          .Llevel_66_80070444
    /* 44BAF00 80070164 03000424 */   addiu     $a0, $zero, 0x3
  .Llevel_66_80070168:
    /* 44BAF04 80070168 0780103C */  lui        $s0, %hi(D_800683A4)
    /* 44BAF08 8007016C A4831026 */  addiu      $s0, $s0, %lo(D_800683A4)
    /* 44BAF0C 80070170 0000028E */  lw         $v0, 0x0($s0)
    /* 44BAF10 80070174 00000000 */  nop
    /* 44BAF14 80070178 80004230 */  andi       $v0, $v0, 0x80
    /* 44BAF18 8007017C B1004014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAF1C 80070180 15000424 */   addiu     $a0, $zero, 0x15
    /* 44BAF20 80070184 CAB4000C */  jal        func_8002D328
    /* 44BAF24 80070188 04000424 */   addiu     $a0, $zero, 0x4
    /* 44BAF28 8007018C AD004014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAF2C 80070190 2F000424 */   addiu     $a0, $zero, 0x2F
    /* 44BAF30 80070194 0780023C */  lui        $v0, %hi(D_8006A0B4)
    /* 44BAF34 80070198 B4A0428C */  lw         $v0, %lo(D_8006A0B4)($v0)
    /* 44BAF38 8007019C 00000000 */  nop
    /* 44BAF3C 800701A0 A8004010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BAF40 800701A4 06000424 */   addiu     $a0, $zero, 0x6
    /* 44BAF44 800701A8 0780023C */  lui        $v0, %hi(D_8006A1B4)
    /* 44BAF48 800701AC B4A1428C */  lw         $v0, %lo(D_8006A1B4)($v0)
    /* 44BAF4C 800701B0 00000000 */  nop
    /* 44BAF50 800701B4 A3004010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BAF54 800701B8 10000424 */   addiu     $a0, $zero, 0x10
    /* 44BAF58 800701BC 0000028E */  lw         $v0, 0x0($s0)
    /* 44BAF5C 800701C0 00000000 */  nop
    /* 44BAF60 800701C4 10004230 */  andi       $v0, $v0, 0x10
    /* 44BAF64 800701C8 9E004014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAF68 800701CC 11000424 */   addiu     $a0, $zero, 0x11
    /* 44BAF6C 800701D0 E0FF2426 */  addiu      $a0, $s1, -0x20
    /* 44BAF70 800701D4 886E000C */  jal        func_8001BA20
    /* 44BAF74 800701D8 01000524 */   addiu     $a1, $zero, 0x1
    /* 44BAF78 800701DC 00044228 */  slti       $v0, $v0, 0x400
    /* 44BAF7C 800701E0 98004014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAF80 800701E4 06000424 */   addiu     $a0, $zero, 0x6
    /* 44BAF84 800701E8 0780023C */  lui        $v0, %hi(D_8006A044)
    /* 44BAF88 800701EC 44A0428C */  lw         $v0, %lo(D_8006A044)($v0)
    /* 44BAF8C 800701F0 00000000 */  nop
    /* 44BAF90 800701F4 93004014 */  bnez       $v0, .Llevel_66_80070444
    /* 44BAF94 800701F8 22000424 */   addiu     $a0, $zero, 0x22
    /* 44BAF98 800701FC 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 44BAF9C 80070200 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 44BAFA0 80070204 00000000 */  nop
    /* 44BAFA4 80070208 01FF4228 */  slti       $v0, $v0, -0xFF
    /* 44BAFA8 8007020C 8F004014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BAFAC 80070210 21000424 */   addiu     $a0, $zero, 0x21
    /* 44BAFB0 80070214 11C10108 */  j          .Llevel_66_80070444
    /* 44BAFB4 80070218 00000000 */   nop
  .Llevel_66_8007021C:
    /* 44BAFB8 8007021C 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 44BAFBC 80070220 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 44BAFC0 80070224 00000000 */  nop
    /* 44BAFC4 80070228 89004228 */  slti       $v0, $v0, 0x89
    /* 44BAFC8 8007022C 87004014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BAFCC 80070230 00000000 */   nop
    /* 44BAFD0 80070234 0780023C */  lui        $v0, %hi(D_80069894)
    /* 44BAFD4 80070238 9498428C */  lw         $v0, %lo(D_80069894)($v0)
    /* 44BAFD8 8007023C 00000000 */  nop
    /* 44BAFDC 80070240 0A004004 */  bltz       $v0, .Llevel_66_8007026C
    /* 44BAFE0 80070244 00000000 */   nop
    /* 44BAFE4 80070248 0680023C */  lui        $v0, %hi(D_80066F8C)
    /* 44BAFE8 8007024C 8C6F428C */  lw         $v0, %lo(D_80066F8C)($v0)
    /* 44BAFEC 80070250 00000000 */  nop
    /* 44BAFF0 80070254 05004010 */  beqz       $v0, .Llevel_66_8007026C
    /* 44BAFF4 80070258 00000000 */   nop
    /* 44BAFF8 8007025C 09F84000 */  jalr       $v0
    /* 44BAFFC 80070260 00000000 */   nop
    /* 44BB000 80070264 13C10108 */  j          .Llevel_66_8007044C
    /* 44BB004 80070268 00000000 */   nop
  .Llevel_66_8007026C:
    /* 44BB008 8007026C 9DCB000C */  jal        func_80032E74
    /* 44BB00C 80070270 00000000 */   nop
    /* 44BB010 80070274 13C10108 */  j          .Llevel_66_8007044C
    /* 44BB014 80070278 00000000 */   nop
  .Llevel_66_8007027C:
    /* 44BB018 8007027C 8AAC000C */  jal        func_8002B228
    /* 44BB01C 80070280 00000000 */   nop
    /* 44BB020 80070284 71004014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BB024 80070288 01000224 */   addiu     $v0, $zero, 0x1
    /* 44BB028 8007028C 0780103C */  lui        $s0, %hi(D_8006A044)
    /* 44BB02C 80070290 44A01026 */  addiu      $s0, $s0, %lo(D_8006A044)
    /* 44BB030 80070294 0000038E */  lw         $v1, 0x0($s0)
    /* 44BB034 80070298 00000000 */  nop
    /* 44BB038 8007029C 10006214 */  bne        $v1, $v0, .Llevel_66_800702E0
    /* 44BB03C 800702A0 00000000 */   nop
    /* 44BB040 800702A4 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 44BB044 800702A8 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 44BB048 800702AC 00000000 */  nop
    /* 44BB04C 800702B0 04004228 */  slti       $v0, $v0, 0x4
    /* 44BB050 800702B4 10004010 */  beqz       $v0, .Llevel_66_800702F8
    /* 44BB054 800702B8 00000000 */   nop
    /* 44BB058 800702BC 0780043C */  lui        $a0, %hi(D_8006A104)
    /* 44BB05C 800702C0 04A1848C */  lw         $a0, %lo(D_8006A104)($a0)
    /* 44BB060 800702C4 1EAC000C */  jal        func_8002B078
    /* 44BB064 800702C8 00000000 */   nop
    /* 44BB068 800702CC 09000324 */  addiu      $v1, $zero, 0x9
    /* 44BB06C 800702D0 4F004310 */  beq        $v0, $v1, .Llevel_66_80070410
    /* 44BB070 800702D4 00000000 */   nop
    /* 44BB074 800702D8 04C10108 */  j          .Llevel_66_80070410
    /* 44BB078 800702DC 000000AE */   sw        $zero, 0x0($s0)
  .Llevel_66_800702E0:
    /* 44BB07C 800702E0 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 44BB080 800702E4 A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 44BB084 800702E8 00000000 */  nop
    /* 44BB088 800702EC 40004230 */  andi       $v0, $v0, 0x40
    /* 44BB08C 800702F0 0D004010 */  beqz       $v0, .Llevel_66_80070328
    /* 44BB090 800702F4 00000000 */   nop
  .Llevel_66_800702F8:
    /* 44BB094 800702F8 76D4000C */  jal        func_800351D8
    /* 44BB098 800702FC 19000424 */   addiu     $a0, $zero, 0x19
    /* 44BB09C 80070300 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 44BB0A0 80070304 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 44BB0A4 80070308 C00D0324 */  addiu      $v1, $zero, 0xDC0
    /* 44BB0A8 8007030C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 44BB0AC 80070310 8CA023AC */  sw         $v1, %lo(D_8006A08C)($at)
    /* 44BB0B0 80070314 01004224 */  addiu      $v0, $v0, 0x1
    /* 44BB0B4 80070318 0780013C */  lui        $at, %hi(D_8006A0B0)
    /* 44BB0B8 8007031C B0A022AC */  sw         $v0, %lo(D_8006A0B0)($at)
    /* 44BB0BC 80070320 13C10108 */  j          .Llevel_66_8007044C
    /* 44BB0C0 80070324 00000000 */   nop
  .Llevel_66_80070328:
    /* 44BB0C4 80070328 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 44BB0C8 8007032C B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 44BB0CC 80070330 00000000 */  nop
    /* 44BB0D0 80070334 04004228 */  slti       $v0, $v0, 0x4
    /* 44BB0D4 80070338 42004010 */  beqz       $v0, .Llevel_66_80070444
    /* 44BB0D8 8007033C 19000424 */   addiu     $a0, $zero, 0x19
    /* 44BB0DC 80070340 0780023C */  lui        $v0, %hi(D_8006A0DC)
    /* 44BB0E0 80070344 DCA0428C */  lw         $v0, %lo(D_8006A0DC)($v0)
    /* 44BB0E4 80070348 00000000 */  nop
    /* 44BB0E8 8007034C 17004228 */  slti       $v0, $v0, 0x17
    /* 44BB0EC 80070350 12004014 */  bnez       $v0, .Llevel_66_8007039C
    /* 44BB0F0 80070354 00000000 */   nop
    /* 44BB0F4 80070358 0780033C */  lui        $v1, %hi(D_8006A0C4)
    /* 44BB0F8 8007035C C4A0638C */  lw         $v1, %lo(D_8006A0C4)($v1)
    /* 44BB0FC 80070360 0780023C */  lui        $v0, %hi(D_8006A084)
    /* 44BB100 80070364 84A0428C */  lw         $v0, %lo(D_8006A084)($v0)
    /* 44BB104 80070368 00000000 */  nop
    /* 44BB108 8007036C 18006200 */  mult       $v1, $v0
    /* 44BB10C 80070370 0780033C */  lui        $v1, %hi(D_8006A0C8)
    /* 44BB110 80070374 C8A0638C */  lw         $v1, %lo(D_8006A0C8)($v1)
    /* 44BB114 80070378 12200000 */  mflo       $a0
    /* 44BB118 8007037C 0780023C */  lui        $v0, %hi(D_8006A088)
    /* 44BB11C 80070380 88A0428C */  lw         $v0, %lo(D_8006A088)($v0)
    /* 44BB120 80070384 00000000 */  nop
    /* 44BB124 80070388 18006200 */  mult       $v1, $v0
    /* 44BB128 8007038C 12180000 */  mflo       $v1
    /* 44BB12C 80070390 21108300 */  addu       $v0, $a0, $v1
    /* 44BB130 80070394 2B004004 */  bltz       $v0, .Llevel_66_80070444
    /* 44BB134 80070398 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_66_8007039C:
    /* 44BB138 8007039C 0780043C */  lui        $a0, %hi(D_8006A044)
    /* 44BB13C 800703A0 44A08424 */  addiu      $a0, $a0, %lo(D_8006A044)
    /* 44BB140 800703A4 0000838C */  lw         $v1, 0x0($a0)
    /* 44BB144 800703A8 02000224 */  addiu      $v0, $zero, 0x2
    /* 44BB148 800703AC 08006214 */  bne        $v1, $v0, .Llevel_66_800703D0
    /* 44BB14C 800703B0 00000000 */   nop
    /* 44BB150 800703B4 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 44BB154 800703B8 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 44BB158 800703BC 00000000 */  nop
    /* 44BB15C 800703C0 10004228 */  slti       $v0, $v0, 0x10
    /* 44BB160 800703C4 02004014 */  bnez       $v0, .Llevel_66_800703D0
    /* 44BB164 800703C8 00000000 */   nop
    /* 44BB168 800703CC 000080AC */  sw         $zero, 0x0($a0)
  .Llevel_66_800703D0:
    /* 44BB16C 800703D0 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 44BB170 800703D4 A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 44BB174 800703D8 00000000 */  nop
    /* 44BB178 800703DC 80004230 */  andi       $v0, $v0, 0x80
    /* 44BB17C 800703E0 0B004014 */  bnez       $v0, .Llevel_66_80070410
    /* 44BB180 800703E4 00000000 */   nop
    /* 44BB184 800703E8 0780023C */  lui        $v0, %hi(D_80069894)
    /* 44BB188 800703EC 9498428C */  lw         $v0, %lo(D_80069894)($v0)
    /* 44BB18C 800703F0 00000000 */  nop
    /* 44BB190 800703F4 06004104 */  bgez       $v0, .Llevel_66_80070410
    /* 44BB194 800703F8 02000224 */   addiu     $v0, $zero, 0x2
    /* 44BB198 800703FC 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 44BB19C 80070400 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 44BB1A0 80070404 00000000 */  nop
    /* 44BB1A4 80070408 0E006214 */  bne        $v1, $v0, .Llevel_66_80070444
    /* 44BB1A8 8007040C 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_66_80070410:
    /* 44BB1AC 80070410 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 44BB1B0 80070414 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 44BB1B4 80070418 00000000 */  nop
    /* 44BB1B8 8007041C 810C6228 */  slti       $v0, $v1, 0xC81
    /* 44BB1BC 80070420 0A004014 */  bnez       $v0, .Llevel_66_8007044C
    /* 44BB1C0 80070424 00000000 */   nop
    /* 44BB1C4 80070428 0780023C */  lui        $v0, %hi(D_8006A0AC)
    /* 44BB1C8 8007042C ACA0428C */  lw         $v0, %lo(D_8006A0AC)($v0)
    /* 44BB1CC 80070430 00000000 */  nop
    /* 44BB1D0 80070434 40100200 */  sll        $v0, $v0, 1
    /* 44BB1D4 80070438 2A104300 */  slt        $v0, $v0, $v1
    /* 44BB1D8 8007043C 03004010 */  beqz       $v0, .Llevel_66_8007044C
    /* 44BB1DC 80070440 0D000424 */   addiu     $a0, $zero, 0xD
  .Llevel_66_80070444:
    /* 44BB1E0 80070444 76D4000C */  jal        func_800351D8
    /* 44BB1E4 80070448 00000000 */   nop
  .Llevel_66_8007044C:
    /* 44BB1E8 8007044C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 44BB1EC 80070450 1400B18F */  lw         $s1, 0x14($sp)
    /* 44BB1F0 80070454 1000B08F */  lw         $s0, 0x10($sp)
    /* 44BB1F4 80070458 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 44BB1F8 8007045C 0800E003 */  jr         $ra
    /* 44BB1FC 80070460 00000000 */   nop
endlabel func_level_66_8006F7A4
    /* 44BB200 80070464 00000000 */  nop
