.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 3
nonmatching jtbl_titlescreen_and_loading_8006D6C0

dlabel jtbl_titlescreen_and_loading_8006D6C0
    /* 2345C 8006D6C0 28D10780 */ .word .Ltitlescreen_and_loading_8007D128
    /* 23460 8006D6C4 60D10780 */ .word .Ltitlescreen_and_loading_8007D160
    /* 23464 8006D6C8 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23468 8006D6CC 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 2346C 8006D6D0 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23470 8006D6D4 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23474 8006D6D8 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23478 8006D6DC 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 2347C 8006D6E0 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23480 8006D6E4 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23484 8006D6E8 74D10780 */ .word .Ltitlescreen_and_loading_8007D174
    /* 23488 8006D6EC 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 2348C 8006D6F0 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23490 8006D6F4 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23494 8006D6F8 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23498 8006D6FC 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 2349C 8006D700 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234A0 8006D704 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234A4 8006D708 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234A8 8006D70C 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234AC 8006D710 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234B0 8006D714 ECD10780 */ .word .Ltitlescreen_and_loading_8007D1EC
    /* 234B4 8006D718 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234B8 8006D71C 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234BC 8006D720 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234C0 8006D724 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234C4 8006D728 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234C8 8006D72C 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234CC 8006D730 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234D0 8006D734 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234D4 8006D738 0CD20780 */ .word .Ltitlescreen_and_loading_8007D20C
    /* 234D8 8006D73C 30D20780 */ .word .Ltitlescreen_and_loading_8007D230
    /* 234DC 8006D740 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234E0 8006D744 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234E4 8006D748 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234E8 8006D74C 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234EC 8006D750 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234F0 8006D754 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234F4 8006D758 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234F8 8006D75C 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 234FC 8006D760 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23500 8006D764 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23504 8006D768 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23508 8006D76C 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 2350C 8006D770 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23510 8006D774 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23514 8006D778 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23518 8006D77C 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 2351C 8006D780 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23520 8006D784 78D30780 */ .word .Ltitlescreen_and_loading_8007D378
    /* 23524 8006D788 30D30780 */ .word .Ltitlescreen_and_loading_8007D330
enddlabel jtbl_titlescreen_and_loading_8006D6C0

nonmatching D_titlescreen_and_loading_8006D78C

dlabel D_titlescreen_and_loading_8006D78C
    /* 23528 8006D78C 41636365 */ .word 0x65636341
enddlabel D_titlescreen_and_loading_8006D78C

.align 2
nonmatching D_titlescreen_and_loading_8006D790

dlabel D_titlescreen_and_loading_8006D790
    /* 2352C 8006D790 */ .asciz "ss Denied. : file already open.\n"
    /* 73732044656E6965642E203A2066696C6520616C7265616479206F70656E2E0A00000000 */
.align 2
enddlabel D_titlescreen_and_loading_8006D790

.align 2
nonmatching D_titlescreen_and_loading_8006D7B4

dlabel D_titlescreen_and_loading_8006D7B4
    /* 23550 8006D7B4 */ .asciz "Access Denied. : file not open.\n"
    /* 4163636573732044656E6965642E203A2066696C65206E6F74206F70656E2E0A00000000 */
.align 2
enddlabel D_titlescreen_and_loading_8006D7B4

.align 2
nonmatching D_titlescreen_and_loading_8006D7D8

dlabel D_titlescreen_and_loading_8006D7D8
    /* 23574 8006D7D8 */ .asciz "Access Denied. : invalid data size align\n"
    /* 4163636573732044656E6965642E203A20696E76616C696420646174612073697A6520616C69676E0A000000 */
.align 2
enddlabel D_titlescreen_and_loading_8006D7D8

.align 2
nonmatching D_titlescreen_and_loading_8006D804

dlabel D_titlescreen_and_loading_8006D804
    /* 235A0 8006D804 */ .asciz "Access Denied. : invalid offset value align\n"
    /* 4163636573732044656E6965642E203A20696E76616C6964206F66667365742076616C756520616C69676E0A00000000 */
.align 2
enddlabel D_titlescreen_and_loading_8006D804

.align 2
nonmatching D_titlescreen_and_loading_8006D834

dlabel D_titlescreen_and_loading_8006D834
    /* 235D0 8006D834 */ .asciz "Access Denied. : system busy\n"
    /* 4163636573732044656E6965642E203A2073797374656D20627573790A000000 */
.align 2
.align 2
    /* 235F0 8006D854 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_titlescreen_and_loading_8006D834

.align 3
nonmatching jtbl_titlescreen_and_loading_8006D858

dlabel jtbl_titlescreen_and_loading_8006D858
    /* 235F4 8006D858 D0D80780 */ .word .Ltitlescreen_and_loading_8007D8D0
    /* 235F8 8006D85C B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 235FC 8006D860 B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 23600 8006D864 B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 23604 8006D868 B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 23608 8006D86C B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 2360C 8006D870 B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 23610 8006D874 B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 23614 8006D878 B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 23618 8006D87C B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 2361C 8006D880 ECD80780 */ .word .Ltitlescreen_and_loading_8007D8EC
    /* 23620 8006D884 2CD90780 */ .word .Ltitlescreen_and_loading_8007D92C
    /* 23624 8006D888 B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 23628 8006D88C B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 2362C 8006D890 B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
    /* 23630 8006D894 B8D90780 */ .word .Ltitlescreen_and_loading_8007D9B8
enddlabel jtbl_titlescreen_and_loading_8006D858

nonmatching D_titlescreen_and_loading_8006D898

dlabel D_titlescreen_and_loading_8006D898
    /* 23634 8006D898 B8D90780 */ .word 0x8007D9B8
    /* 23638 8006D89C B8D90780 */ .word 0x8007D9B8
    /* 2363C 8006D8A0 B8D90780 */ .word 0x8007D9B8
    /* 23640 8006D8A4 B8D90780 */ .word 0x8007D9B8
    /* 23644 8006D8A8 48D90780 */ .word 0x8007D948
    /* 23648 8006D8AC B8D90780 */ .word 0x8007D9B8
enddlabel D_titlescreen_and_loading_8006D898

nonmatching D_titlescreen_and_loading_8006D8B0

dlabel D_titlescreen_and_loading_8006D8B0
    /* 2364C 8006D8B0 98D90780 */ .word 0x8007D998
    /* 23650 8006D8B4 00000000 */ .word 0x00000000
enddlabel D_titlescreen_and_loading_8006D8B0

.align 3
nonmatching jtbl_titlescreen_and_loading_8006D8B8

dlabel jtbl_titlescreen_and_loading_8006D8B8
    /* 23654 8006D8B8 28DB0780 */ .word .Ltitlescreen_and_loading_8007DB28
    /* 23658 8006D8BC 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 2365C 8006D8C0 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 23660 8006D8C4 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 23664 8006D8C8 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 23668 8006D8CC 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 2366C 8006D8D0 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 23670 8006D8D4 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 23674 8006D8D8 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 23678 8006D8DC 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 2367C 8006D8E0 44DB0780 */ .word .Ltitlescreen_and_loading_8007DB44
    /* 23680 8006D8E4 84DB0780 */ .word .Ltitlescreen_and_loading_8007DB84
    /* 23684 8006D8E8 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 23688 8006D8EC 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 2368C 8006D8F0 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 23690 8006D8F4 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 23694 8006D8F8 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 23698 8006D8FC 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 2369C 8006D900 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 236A0 8006D904 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 236A4 8006D908 A0DB0780 */ .word .Ltitlescreen_and_loading_8007DBA0
    /* 236A8 8006D90C 10DC0780 */ .word .Ltitlescreen_and_loading_8007DC10
    /* 236AC 8006D910 F0DB0780 */ .word .Ltitlescreen_and_loading_8007DBF0
enddlabel jtbl_titlescreen_and_loading_8006D8B8

.align 2
nonmatching D_titlescreen_and_loading_8006D914

dlabel D_titlescreen_and_loading_8006D914
    /* 236B0 8006D914 */ .asciz "bu00:"
    /* 627530303A000000 */
.align 2
.align 2
    /* 236B8 8006D91C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_titlescreen_and_loading_8006D914

nonmatching D_titlescreen_and_loading_8006D920

dlabel D_titlescreen_and_loading_8006D920
    /* 236BC 8006D920 6C69626D */ .word 0x6D62696C
    /* 236C0 8006D924 6372643A */ .word 0x3A647263
    /* 236C4 8006D928 20657665 */ .word 0x65766520
    /* 236C8 8006D92C 6E74206F */ .word 0x6F20746E
enddlabel D_titlescreen_and_loading_8006D920

.align 2
nonmatching D_titlescreen_and_loading_8006D930

dlabel D_titlescreen_and_loading_8006D930
    /* 236CC 8006D930 */ .asciz "verflow\n"
    /* 766572666C6F770A00000000 */
.align 2
.align 2
    /* 236D8 8006D93C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_titlescreen_and_loading_8006D930

nonmatching D_titlescreen_and_loading_8006D940

dlabel D_titlescreen_and_loading_8006D940
    /* 236DC 8006D940 63617264 */ .word 0x64726163
    /* 236E0 8006D944 20726561 */ .word 0x61657220
enddlabel D_titlescreen_and_loading_8006D940

.align 2
nonmatching D_titlescreen_and_loading_8006D948

dlabel D_titlescreen_and_loading_8006D948
    /* 236E4 8006D948 */ .asciz "d error\n"
    /* 64206572726F720A00000000 */
.align 2
.align 2
    /* 236F0 8006D954 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 236F4 8006D958 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 236F8 8006D95C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_titlescreen_and_loading_8006D948
