.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_51_8006D3A8

dlabel jtbl_level_51_8006D3A8
    /* 38D2944 8006D3A8 58F30680 */ .word .Llevel_51_8006F358
    /* 38D2948 8006D3AC 48F30680 */ .word .Llevel_51_8006F348
    /* 38D294C 8006D3B0 64F30680 */ .word .Llevel_51_8006F364
    /* 38D2950 8006D3B4 64F30680 */ .word .Llevel_51_8006F364
    /* 38D2954 8006D3B8 64F30680 */ .word .Llevel_51_8006F364
    /* 38D2958 8006D3BC 64F30680 */ .word .Llevel_51_8006F364
    /* 38D295C 8006D3C0 64F30680 */ .word .Llevel_51_8006F364
    /* 38D2960 8006D3C4 64F30680 */ .word .Llevel_51_8006F364
    /* 38D2964 8006D3C8 48F30680 */ .word .Llevel_51_8006F348
    /* 38D2968 8006D3CC 58F30680 */ .word .Llevel_51_8006F358
    /* 38D296C 8006D3D0 64F30680 */ .word .Llevel_51_8006F364
    /* 38D2970 8006D3D4 48F30680 */ .word .Llevel_51_8006F348
    /* 38D2974 8006D3D8 48F30680 */ .word .Llevel_51_8006F348
    /* 38D2978 8006D3DC 64F30680 */ .word .Llevel_51_8006F364
    /* 38D297C 8006D3E0 48F30680 */ .word .Llevel_51_8006F348
    /* 38D2980 8006D3E4 64F30680 */ .word .Llevel_51_8006F364
    /* 38D2984 8006D3E8 64F30680 */ .word .Llevel_51_8006F364
    /* 38D2988 8006D3EC 64F30680 */ .word .Llevel_51_8006F364
    /* 38D298C 8006D3F0 64F30680 */ .word .Llevel_51_8006F364
    /* 38D2990 8006D3F4 64F30680 */ .word .Llevel_51_8006F364
    /* 38D2994 8006D3F8 48F30680 */ .word .Llevel_51_8006F348
    /* 38D2998 8006D3FC 64F30680 */ .word .Llevel_51_8006F364
    /* 38D299C 8006D400 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29A0 8006D404 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29A4 8006D408 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29A8 8006D40C 48F30680 */ .word .Llevel_51_8006F348
    /* 38D29AC 8006D410 48F30680 */ .word .Llevel_51_8006F348
    /* 38D29B0 8006D414 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29B4 8006D418 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29B8 8006D41C 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29BC 8006D420 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29C0 8006D424 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29C4 8006D428 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29C8 8006D42C 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29CC 8006D430 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29D0 8006D434 48F30680 */ .word .Llevel_51_8006F348
    /* 38D29D4 8006D438 48F30680 */ .word .Llevel_51_8006F348
    /* 38D29D8 8006D43C 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29DC 8006D440 64F30680 */ .word .Llevel_51_8006F364
    /* 38D29E0 8006D444 64F30680 */ .word .Llevel_51_8006F364
enddlabel jtbl_level_51_8006D3A8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_51_8006F2F8, 0x7C

glabel func_level_51_8006F2F8
    /* 38D4894 8006F2F8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 38D4898 8006F2FC 00210400 */  sll        $a0, $a0, 4
    /* 38D489C 8006F300 0780023C */  lui        $v0, %hi(D_800683B0)
    /* 38D48A0 8006F304 B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* 38D48A4 8006F308 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 38D48A8 8006F30C 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 38D48AC 8006F310 21208200 */  addu       $a0, $a0, $v0
    /* 38D48B0 8006F314 1000BFAF */  sw         $ra, 0x10($sp)
    /* 38D48B4 8006F318 0680013C */  lui        $at, %hi(D_80066F38)
    /* 38D48B8 8006F31C 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* 38D48BC 8006F320 EEFF6324 */  addiu      $v1, $v1, -0x12
    /* 38D48C0 8006F324 2800622C */  sltiu      $v0, $v1, 0x28
    /* 38D48C4 8006F328 0E004010 */  beqz       $v0, .Llevel_51_8006F364
    /* 38D48C8 8006F32C 80100300 */   sll       $v0, $v1, 2
    /* 38D48CC 8006F330 0780013C */  lui        $at, %hi(jtbl_level_51_8006D3A8)
    /* 38D48D0 8006F334 21082200 */  addu       $at, $at, $v0
    /* 38D48D4 8006F338 A8D3228C */  lw         $v0, %lo(jtbl_level_51_8006D3A8)($at)
    /* 38D48D8 8006F33C 00000000 */  nop
    /* 38D48DC 8006F340 08004000 */  jr         $v0
    /* 38D48E0 8006F344 00000000 */   nop
  .Llevel_51_8006F348:
    /* 38D48E4 8006F348 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* 38D48E8 8006F34C C4A08424 */  addiu      $a0, $a0, %lo(D_8006A0C4)
    /* 38D48EC 8006F350 D7BC0108 */  j          .Llevel_51_8006F35C
    /* 38D48F0 8006F354 00000000 */   nop
  .Llevel_51_8006F358:
    /* 38D48F4 8006F358 21200000 */  addu       $a0, $zero, $zero
  .Llevel_51_8006F35C:
    /* 38D48F8 8006F35C E3B6000C */  jal        func_8002DB8C
    /* 38D48FC 8006F360 00000000 */   nop
  .Llevel_51_8006F364:
    /* 38D4900 8006F364 1000BF8F */  lw         $ra, 0x10($sp)
    /* 38D4904 8006F368 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 38D4908 8006F36C 0800E003 */  jr         $ra
    /* 38D490C 8006F370 00000000 */   nop
endlabel func_level_51_8006F2F8
