.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_31_8006D308

dlabel jtbl_level_31_8006D308
    /* 21358A4 8006D308 D8E30680 */ .word .Llevel_31_8006E3D8
    /* 21358A8 8006D30C DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358AC 8006D310 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358B0 8006D314 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358B4 8006D318 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358B8 8006D31C DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358BC 8006D320 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358C0 8006D324 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358C4 8006D328 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358C8 8006D32C 48E40680 */ .word .Llevel_31_8006E448
    /* 21358CC 8006D330 28E40680 */ .word .Llevel_31_8006E428
    /* 21358D0 8006D334 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358D4 8006D338 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358D8 8006D33C DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358DC 8006D340 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358E0 8006D344 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358E4 8006D348 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358E8 8006D34C DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358EC 8006D350 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358F0 8006D354 D8E30680 */ .word .Llevel_31_8006E3D8
    /* 21358F4 8006D358 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358F8 8006D35C DCE40680 */ .word .Llevel_31_8006E4DC
    /* 21358FC 8006D360 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 2135900 8006D364 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 2135904 8006D368 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 2135908 8006D36C DCE40680 */ .word .Llevel_31_8006E4DC
    /* 213590C 8006D370 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 2135910 8006D374 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 2135914 8006D378 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 2135918 8006D37C DCE40680 */ .word .Llevel_31_8006E4DC
    /* 213591C 8006D380 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 2135920 8006D384 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 2135924 8006D388 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 2135928 8006D38C DCE40680 */ .word .Llevel_31_8006E4DC
    /* 213592C 8006D390 08E40680 */ .word .Llevel_31_8006E408
    /* 2135930 8006D394 08E40680 */ .word .Llevel_31_8006E408
    /* 2135934 8006D398 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 2135938 8006D39C DCE40680 */ .word .Llevel_31_8006E4DC
    /* 213593C 8006D3A0 DCE40680 */ .word .Llevel_31_8006E4DC
    /* 2135940 8006D3A4 9CE40680 */ .word .Llevel_31_8006E49C
enddlabel jtbl_level_31_8006D308


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_31_8006E3A0, 0x14C

glabel func_level_31_8006E3A0
    /* 213693C 8006E3A0 0780023C */  lui        $v0, %hi(D_8006A040)
    /* 2136940 8006E3A4 40A0428C */  lw         $v0, %lo(D_8006A040)($v0)
    /* 2136944 8006E3A8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2136948 8006E3AC EDFF4324 */  addiu      $v1, $v0, -0x13
    /* 213694C 8006E3B0 2800622C */  sltiu      $v0, $v1, 0x28
    /* 2136950 8006E3B4 49004010 */  beqz       $v0, .Llevel_31_8006E4DC
    /* 2136954 8006E3B8 1000BFAF */   sw        $ra, 0x10($sp)
    /* 2136958 8006E3BC 80100300 */  sll        $v0, $v1, 2
    /* 213695C 8006E3C0 0780013C */  lui        $at, %hi(jtbl_level_31_8006D308)
    /* 2136960 8006E3C4 21082200 */  addu       $at, $at, $v0
    /* 2136964 8006E3C8 08D3228C */  lw         $v0, %lo(jtbl_level_31_8006D308)($at)
    /* 2136968 8006E3CC 00000000 */  nop
    /* 213696C 8006E3D0 08004000 */  jr         $v0
    /* 2136970 8006E3D4 00000000 */   nop
  .Llevel_31_8006E3D8:
    /* 2136974 8006E3D8 71B6000C */  jal        func_8002D9C4
    /* 2136978 8006E3DC 00000000 */   nop
    /* 213697C 8006E3E0 03004014 */  bnez       $v0, .Llevel_31_8006E3F0
    /* 2136980 8006E3E4 00000000 */   nop
    /* 2136984 8006E3E8 FEB5000C */  jal        func_8002D7F8
    /* 2136988 8006E3EC 00000000 */   nop
  .Llevel_31_8006E3F0:
    /* 213698C 8006E3F0 3DB0000C */  jal        func_8002C0F4
    /* 2136990 8006E3F4 00000000 */   nop
    /* 2136994 8006E3F8 0780013C */  lui        $at, %hi(D_8006A0B4)
    /* 2136998 8006E3FC B4A020AC */  sw         $zero, %lo(D_8006A0B4)($at)
    /* 213699C 8006E400 04B90108 */  j          .Llevel_31_8006E410
    /* 21369A0 8006E404 00000000 */   nop
  .Llevel_31_8006E408:
    /* 21369A4 8006E408 3DB0000C */  jal        func_8002C0F4
    /* 21369A8 8006E40C 00000000 */   nop
  .Llevel_31_8006E410:
    /* 21369AC 8006E410 22B3000C */  jal        func_8002CC88
    /* 21369B0 8006E414 00000000 */   nop
  .Llevel_31_8006E418:
    /* 21369B4 8006E418 0780013C */  lui        $at, %hi(D_8006A018)
    /* 21369B8 8006E41C 18A020AC */  sw         $zero, %lo(D_8006A018)($at)
    /* 21369BC 8006E420 37B90108 */  j          .Llevel_31_8006E4DC
    /* 21369C0 8006E424 00000000 */   nop
  .Llevel_31_8006E428:
    /* 21369C4 8006E428 3DB0000C */  jal        func_8002C0F4
    /* 21369C8 8006E42C 00000000 */   nop
    /* 21369CC 8006E430 22B3000C */  jal        func_8002CC88
    /* 21369D0 8006E434 00000000 */   nop
    /* 21369D4 8006E438 C2B6000C */  jal        func_8002DB08
    /* 21369D8 8006E43C 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 21369DC 8006E440 06B90108 */  j          .Llevel_31_8006E418
    /* 21369E0 8006E444 00000000 */   nop
  .Llevel_31_8006E448:
    /* 21369E4 8006E448 3DB0000C */  jal        func_8002C0F4
    /* 21369E8 8006E44C 00000000 */   nop
    /* 21369EC 8006E450 22B3000C */  jal        func_8002CC88
    /* 21369F0 8006E454 00000000 */   nop
    /* 21369F4 8006E458 81AF000C */  jal        func_8002BE04
    /* 21369F8 8006E45C 00000000 */   nop
    /* 21369FC 8006E460 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 2136A00 8006E464 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 2136A04 8006E468 00000000 */  nop
    /* 2136A08 8006E46C EAFF4104 */  bgez       $v0, .Llevel_31_8006E418
    /* 2136A0C 8006E470 00000000 */   nop
    /* 2136A10 8006E474 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 2136A14 8006E478 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 2136A18 8006E47C 00000000 */  nop
    /* 2136A1C 8006E480 04004228 */  slti       $v0, $v0, 0x4
    /* 2136A20 8006E484 E4FF4014 */  bnez       $v0, .Llevel_31_8006E418
    /* 2136A24 8006E488 01000224 */   addiu     $v0, $zero, 0x1
    /* 2136A28 8006E48C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2136A2C 8006E490 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 2136A30 8006E494 06B90108 */  j          .Llevel_31_8006E418
    /* 2136A34 8006E498 00000000 */   nop
  .Llevel_31_8006E49C:
    /* 2136A38 8006E49C 3DB0000C */  jal        func_8002C0F4
    /* 2136A3C 8006E4A0 00000000 */   nop
    /* 2136A40 8006E4A4 22B3000C */  jal        func_8002CC88
    /* 2136A44 8006E4A8 00000000 */   nop
    /* 2136A48 8006E4AC FF000224 */  addiu      $v0, $zero, 0xFF
    /* 2136A4C 8006E4B0 0780013C */  lui        $at, %hi(D_8006A013)
    /* 2136A50 8006E4B4 13A022A0 */  sb         $v0, %lo(D_8006A013)($at)
    /* 2136A54 8006E4B8 20000224 */  addiu      $v0, $zero, 0x20
    /* 2136A58 8006E4BC 0780013C */  lui        $at, %hi(D_8006A018)
    /* 2136A5C 8006E4C0 18A020AC */  sw         $zero, %lo(D_8006A018)($at)
    /* 2136A60 8006E4C4 0780013C */  lui        $at, %hi(D_8006A012)
    /* 2136A64 8006E4C8 12A022A0 */  sb         $v0, %lo(D_8006A012)($at)
    /* 2136A68 8006E4CC 0780013C */  lui        $at, %hi(D_8006A011)
    /* 2136A6C 8006E4D0 11A022A0 */  sb         $v0, %lo(D_8006A011)($at)
    /* 2136A70 8006E4D4 0780013C */  lui        $at, %hi(D_8006A010)
    /* 2136A74 8006E4D8 10A022A0 */  sb         $v0, %lo(D_8006A010)($at)
  .Llevel_31_8006E4DC:
    /* 2136A78 8006E4DC 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2136A7C 8006E4E0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2136A80 8006E4E4 0800E003 */  jr         $ra
    /* 2136A84 8006E4E8 00000000 */   nop
endlabel func_level_31_8006E3A0
