.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_21_8006D478

dlabel jtbl_level_21_8006D478
    /* 1565214 8006D478 68E80680 */ .word .Llevel_21_8006E868
    /* 1565218 8006D47C D8E70680 */ .word .Llevel_21_8006E7D8
    /* 156521C 8006D480 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565220 8006D484 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565224 8006D488 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565228 8006D48C 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 156522C 8006D490 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565230 8006D494 FCE90680 */ .word .Llevel_21_8006E9FC
    /* 1565234 8006D498 4CEA0680 */ .word .Llevel_21_8006EA4C
    /* 1565238 8006D49C 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 156523C 8006D4A0 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565240 8006D4A4 48E90680 */ .word .Llevel_21_8006E948
    /* 1565244 8006D4A8 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565248 8006D4AC 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 156524C 8006D4B0 CCEA0680 */ .word .Llevel_21_8006EACC
    /* 1565250 8006D4B4 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565254 8006D4B8 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565258 8006D4BC 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 156525C 8006D4C0 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565260 8006D4C4 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565264 8006D4C8 D8E70680 */ .word .Llevel_21_8006E7D8
    /* 1565268 8006D4CC 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 156526C 8006D4D0 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565270 8006D4D4 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565274 8006D4D8 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565278 8006D4DC 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 156527C 8006D4E0 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565280 8006D4E4 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565284 8006D4E8 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565288 8006D4EC 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 156528C 8006D4F0 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565290 8006D4F4 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565294 8006D4F8 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 1565298 8006D4FC 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 156529C 8006D500 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 15652A0 8006D504 20EB0680 */ .word .Llevel_21_8006EB20
    /* 15652A4 8006D508 20EB0680 */ .word .Llevel_21_8006EB20
    /* 15652A8 8006D50C 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 15652AC 8006D510 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 15652B0 8006D514 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 15652B4 8006D518 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 15652B8 8006D51C 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 15652BC 8006D520 2CEC0680 */ .word .Llevel_21_8006EC2C
    /* 15652C0 8006D524 4CEB0680 */ .word .Llevel_21_8006EB4C
enddlabel jtbl_level_21_8006D478


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_21_8006E7A0, 0x4A0

glabel func_level_21_8006E7A0
    /* 156653C 8006E7A0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 1566540 8006E7A4 1000B0AF */  sw         $s0, 0x10($sp)
    /* 1566544 8006E7A8 21808000 */  addu       $s0, $a0, $zero
    /* 1566548 8006E7AC EEFF0326 */  addiu      $v1, $s0, -0x12
    /* 156654C 8006E7B0 2C00622C */  sltiu      $v0, $v1, 0x2C
    /* 1566550 8006E7B4 1D014010 */  beqz       $v0, .Llevel_21_8006EC2C
    /* 1566554 8006E7B8 1400BFAF */   sw        $ra, 0x14($sp)
    /* 1566558 8006E7BC 80100300 */  sll        $v0, $v1, 2
    /* 156655C 8006E7C0 0780013C */  lui        $at, %hi(jtbl_level_21_8006D478)
    /* 1566560 8006E7C4 21082200 */  addu       $at, $at, $v0
    /* 1566564 8006E7C8 78D4228C */  lw         $v0, %lo(jtbl_level_21_8006D478)($at)
    /* 1566568 8006E7CC 00000000 */  nop
    /* 156656C 8006E7D0 08004000 */  jr         $v0
    /* 1566570 8006E7D4 00000000 */   nop
  .Llevel_21_8006E7D8:
    /* 1566574 8006E7D8 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1566578 8006E7DC 48A020AC */  sw         $zero, %lo(D_8006A048)($at)
    /* 156657C 8006E7E0 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1566580 8006E7E4 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1566584 8006E7E8 AFB8000C */  jal        func_8002E2BC
    /* 1566588 8006E7EC 00000000 */   nop
    /* 156658C 8006E7F0 01000224 */  addiu      $v0, $zero, 0x1
    /* 1566590 8006E7F4 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1566594 8006E7F8 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 1566598 8006E7FC 25000224 */  addiu      $v0, $zero, 0x25
    /* 156659C 8006E800 04000216 */  bne        $s0, $v0, .Llevel_21_8006E814
    /* 15665A0 8006E804 01000424 */   addiu     $a0, $zero, 0x1
    /* 15665A4 8006E808 05000424 */  addiu      $a0, $zero, 0x5
    /* 15665A8 8006E80C 06BA0108 */  j          .Llevel_21_8006E818
    /* 15665AC 8006E810 08000524 */   addiu     $a1, $zero, 0x8
  .Llevel_21_8006E814:
    /* 15665B0 8006E814 03000524 */  addiu      $a1, $zero, 0x3
  .Llevel_21_8006E818:
    /* 15665B4 8006E818 47E2000C */  jal        func_8003891C
    /* 15665B8 8006E81C 00000000 */   nop
    /* 15665BC 8006E820 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 15665C0 8006E824 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* 15665C4 8006E828 0680033C */  lui        $v1, %hi(D_800670B4)
    /* 15665C8 8006E82C B470638C */  lw         $v1, %lo(D_800670B4)($v1)
    /* 15665CC 8006E830 0780013C */  lui        $at, %hi(D_8006A140)
    /* 15665D0 8006E834 40A120AC */  sw         $zero, %lo(D_8006A140)($at)
    /* 15665D4 8006E838 FC006010 */  beqz       $v1, .Llevel_21_8006EC2C
    /* 15665D8 8006E83C 25000224 */   addiu     $v0, $zero, 0x25
    /* 15665DC 8006E840 03000216 */  bne        $s0, $v0, .Llevel_21_8006E850
    /* 15665E0 8006E844 27000224 */   addiu     $v0, $zero, 0x27
    /* 15665E4 8006E848 16BA0108 */  j          .Llevel_21_8006E858
    /* 15665E8 8006E84C F1010424 */   addiu     $a0, $zero, 0x1F1
  .Llevel_21_8006E850:
    /* 15665EC 8006E850 F6000216 */  bne        $s0, $v0, .Llevel_21_8006EC2C
    /* 15665F0 8006E854 DB010424 */   addiu     $a0, $zero, 0x1DB
  .Llevel_21_8006E858:
    /* 15665F4 8006E858 09F86000 */  jalr       $v1
    /* 15665F8 8006E85C 21280000 */   addu      $a1, $zero, $zero
    /* 15665FC 8006E860 0BBB0108 */  j          .Llevel_21_8006EC2C
    /* 1566600 8006E864 00000000 */   nop
  .Llevel_21_8006E868:
    /* 1566604 8006E868 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 1566608 8006E86C 48A06324 */  addiu      $v1, $v1, %lo(D_8006A048)
    /* 156660C 8006E870 0780023C */  lui        $v0, %hi(D_8006A208)
    /* 1566610 8006E874 08A2428C */  lw         $v0, %lo(D_8006A208)($v0)
    /* 1566614 8006E878 00000000 */  nop
    /* 1566618 8006E87C 0000508C */  lw         $s0, 0x0($v0)
    /* 156661C 8006E880 0E000224 */  addiu      $v0, $zero, 0xE
    /* 1566620 8006E884 000062AC */  sw         $v0, 0x0($v1)
    /* 1566624 8006E888 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1566628 8006E88C 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 156662C 8006E890 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1566630 8006E894 ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 1566634 8006E898 686F000C */  jal        func_8001BDA0
    /* 1566638 8006E89C 3C006424 */   addiu     $a0, $v1, 0x3C
    /* 156663C 8006E8A0 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 1566640 8006E8A4 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 1566644 8006E8A8 0780063C */  lui        $a2, %hi(D_8006A05C)
    /* 1566648 8006E8AC 5CA0C68C */  lw         $a2, %lo(D_8006A05C)($a2)
    /* 156664C 8006E8B0 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 1566650 8006E8B4 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 1566654 8006E8B8 1400A38C */  lw         $v1, 0x14($a1)
    /* 1566658 8006E8BC 0000048E */  lw         $a0, 0x0($s0)
    /* 156665C 8006E8C0 0780013C */  lui        $at, %hi(D_8006A140)
    /* 1566660 8006E8C4 40A126AC */  sw         $a2, %lo(D_8006A140)($at)
    /* 1566664 8006E8C8 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 1566668 8006E8CC 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* 156666C 8006E8D0 21186400 */  addu       $v1, $v1, $a0
    /* 1566670 8006E8D4 0780013C */  lui        $at, %hi(D_8006A144)
    /* 1566674 8006E8D8 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 1566678 8006E8DC 23186200 */  subu       $v1, $v1, $v0
    /* 156667C 8006E8E0 00F86324 */  addiu      $v1, $v1, -0x800
    /* 1566680 8006E8E4 0780013C */  lui        $at, %hi(D_8006A14C)
    /* 1566684 8006E8E8 4CA123AC */  sw         $v1, %lo(D_8006A14C)($at)
    /* 1566688 8006E8EC 801A0300 */  sll        $v1, $v1, 10
    /* 156668C 8006E8F0 831A0300 */  sra        $v1, $v1, 10
    /* 1566690 8006E8F4 00046324 */  addiu      $v1, $v1, 0x400
    /* 1566694 8006E8F8 0780013C */  lui        $at, %hi(D_8006A148)
    /* 1566698 8006E8FC 48A123AC */  sw         $v1, %lo(D_8006A148)($at)
    /* 156669C 8006E900 4600A290 */  lbu        $v0, 0x46($a1)
    /* 15666A0 8006E904 00000000 */  nop
    /* 15666A4 8006E908 00110200 */  sll        $v0, $v0, 4
    /* 15666A8 8006E90C 23104600 */  subu       $v0, $v0, $a2
    /* 15666AC 8006E910 23104300 */  subu       $v0, $v0, $v1
    /* 15666B0 8006E914 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 15666B4 8006E918 01086228 */  slti       $v0, $v1, 0x801
    /* 15666B8 8006E91C 0780013C */  lui        $at, %hi(D_8006A148)
    /* 15666BC 8006E920 48A123AC */  sw         $v1, %lo(D_8006A148)($at)
    /* 15666C0 8006E924 03004014 */  bnez       $v0, .Llevel_21_8006E934
    /* 15666C4 8006E928 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 15666C8 8006E92C 0780013C */  lui        $at, %hi(D_8006A148)
    /* 15666CC 8006E930 48A122AC */  sw         $v0, %lo(D_8006A148)($at)
  .Llevel_21_8006E934:
    /* 15666D0 8006E934 0400028E */  lw         $v0, 0x4($s0)
    /* 15666D4 8006E938 0780013C */  lui        $at, %hi(D_8006A150)
    /* 15666D8 8006E93C 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 15666DC 8006E940 0BBB0108 */  j          .Llevel_21_8006EC2C
    /* 15666E0 8006E944 00000000 */   nop
  .Llevel_21_8006E948:
    /* 15666E4 8006E948 0780043C */  lui        $a0, %hi(D_8006A048)
    /* 15666E8 8006E94C 48A0848C */  lw         $a0, %lo(D_8006A048)($a0)
    /* 15666EC 8006E950 0780033C */  lui        $v1, %hi(D_8006A20C)
    /* 15666F0 8006E954 0CA2638C */  lw         $v1, %lo(D_8006A20C)($v1)
    /* 15666F4 8006E958 07000224 */  addiu      $v0, $zero, 0x7
    /* 15666F8 8006E95C 0780013C */  lui        $at, %hi(D_8006A048)
    /* 15666FC 8006E960 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 1566700 8006E964 0780023C */  lui        $v0, %hi(D_8006A210)
    /* 1566704 8006E968 10A2428C */  lw         $v0, %lo(D_8006A210)($v0)
    /* 1566708 8006E96C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 156670C 8006E970 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1566710 8006E974 80190300 */  sll        $v1, $v1, 6
    /* 1566714 8006E978 0780013C */  lui        $at, %hi(D_8006A084)
    /* 1566718 8006E97C 84A023AC */  sw         $v1, %lo(D_8006A084)($at)
    /* 156671C 8006E980 0780033C */  lui        $v1, %hi(D_8006A214)
    /* 1566720 8006E984 14A2638C */  lw         $v1, %lo(D_8006A214)($v1)
    /* 1566724 8006E988 80110200 */  sll        $v0, $v0, 6
    /* 1566728 8006E98C 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 156672C 8006E990 3CA124AC */  sw         $a0, %lo(D_8006A13C)($at)
    /* 1566730 8006E994 0780013C */  lui        $at, %hi(D_8006A088)
    /* 1566734 8006E998 88A022AC */  sw         $v0, %lo(D_8006A088)($at)
    /* 1566738 8006E99C 03006014 */  bnez       $v1, .Llevel_21_8006E9AC
    /* 156673C 8006E9A0 80110300 */   sll       $v0, $v1, 6
    /* 1566740 8006E9A4 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 1566744 8006E9A8 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
  .Llevel_21_8006E9AC:
    /* 1566748 8006E9AC 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 156674C 8006E9B0 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1566750 8006E9B4 C2B6000C */  jal        func_8002DB08
    /* 1566754 8006E9B8 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 1566758 8006E9BC 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 156675C 8006E9C0 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 1566760 8006E9C4 01000224 */  addiu      $v0, $zero, 0x1
    /* 1566764 8006E9C8 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1566768 8006E9CC ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 156676C 8006E9D0 0F000224 */  addiu      $v0, $zero, 0xF
    /* 1566770 8006E9D4 0780013C */  lui        $at, %hi(D_8006838C)
    /* 1566774 8006E9D8 8C8322AC */  sw         $v0, %lo(D_8006838C)($at)
    /* 1566778 8006E9DC 93006010 */  beqz       $v1, .Llevel_21_8006EC2C
    /* 156677C 8006E9E0 05000424 */   addiu     $a0, $zero, 0x5
    /* 1566780 8006E9E4 0A000524 */  addiu      $a1, $zero, 0xA
    /* 1566784 8006E9E8 21300000 */  addu       $a2, $zero, $zero
    /* 1566788 8006E9EC 09F86000 */  jalr       $v1
    /* 156678C 8006E9F0 21380000 */   addu      $a3, $zero, $zero
    /* 1566790 8006E9F4 0BBB0108 */  j          .Llevel_21_8006EC2C
    /* 1566794 8006E9F8 00000000 */   nop
  .Llevel_21_8006E9FC:
    /* 1566798 8006E9FC 0680033C */  lui        $v1, %hi(D_80067020)
    /* 156679C 8006EA00 2070638C */  lw         $v1, %lo(D_80067020)($v1)
    /* 15667A0 8006EA04 09000224 */  addiu      $v0, $zero, 0x9
    /* 15667A4 8006EA08 0780013C */  lui        $at, %hi(D_8006A048)
    /* 15667A8 8006EA0C 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 15667AC 8006EA10 0600023C */  lui        $v0, (0x60000 >> 16)
    /* 15667B0 8006EA14 0780013C */  lui        $at, %hi(D_8006A128)
    /* 15667B4 8006EA18 28A122AC */  sw         $v0, %lo(D_8006A128)($at)
    /* 15667B8 8006EA1C 01000224 */  addiu      $v0, $zero, 0x1
    /* 15667BC 8006EA20 0780013C */  lui        $at, %hi(D_8006A044)
    /* 15667C0 8006EA24 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 15667C4 8006EA28 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 15667C8 8006EA2C 3CA120AC */  sw         $zero, %lo(D_8006A13C)($at)
    /* 15667CC 8006EA30 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 15667D0 8006EA34 ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 15667D4 8006EA38 0780013C */  lui        $at, %hi(D_8006A1AD)
    /* 15667D8 8006EA3C ADA122A0 */  sb         $v0, %lo(D_8006A1AD)($at)
    /* 15667DC 8006EA40 22006490 */  lbu        $a0, 0x22($v1)
    /* 15667E0 8006EA44 C4BA0108 */  j          .Llevel_21_8006EB10
    /* 15667E4 8006EA48 21280000 */   addu      $a1, $zero, $zero
  .Llevel_21_8006EA4C:
    /* 15667E8 8006EA4C 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 15667EC 8006EA50 3CA16324 */  addiu      $v1, $v1, %lo(D_8006A13C)
    /* 15667F0 8006EA54 48FF6424 */  addiu      $a0, $v1, -0xB8
    /* 15667F4 8006EA58 0780053C */  lui        $a1, %hi(D_8006A048)
    /* 15667F8 8006EA5C 48A0A58C */  lw         $a1, %lo(D_8006A048)($a1)
    /* 15667FC 8006EA60 07000224 */  addiu      $v0, $zero, 0x7
    /* 1566800 8006EA64 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1566804 8006EA68 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 1566808 8006EA6C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 156680C 8006EA70 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1566810 8006EA74 686F000C */  jal        func_8001BDA0
    /* 1566814 8006EA78 000065AC */   sw        $a1, 0x0($v1)
    /* 1566818 8006EA7C 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 156681C 8006EA80 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 1566820 8006EA84 01000224 */  addiu      $v0, $zero, 0x1
    /* 1566824 8006EA88 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1566828 8006EA8C ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 156682C 8006EA90 0F000224 */  addiu      $v0, $zero, 0xF
    /* 1566830 8006EA94 0780013C */  lui        $at, %hi(D_8006838C)
    /* 1566834 8006EA98 8C8322AC */  sw         $v0, %lo(D_8006838C)($at)
    /* 1566838 8006EA9C 05006010 */  beqz       $v1, .Llevel_21_8006EAB4
    /* 156683C 8006EAA0 05000424 */   addiu     $a0, $zero, 0x5
    /* 1566840 8006EAA4 0A000524 */  addiu      $a1, $zero, 0xA
    /* 1566844 8006EAA8 21300000 */  addu       $a2, $zero, $zero
    /* 1566848 8006EAAC 09F86000 */  jalr       $v1
    /* 156684C 8006EAB0 21380000 */   addu      $a3, $zero, $zero
  .Llevel_21_8006EAB4:
    /* 1566850 8006EAB4 0680023C */  lui        $v0, %hi(D_80067020)
    /* 1566854 8006EAB8 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 1566858 8006EABC 00000000 */  nop
    /* 156685C 8006EAC0 09004490 */  lbu        $a0, 0x9($v0)
    /* 1566860 8006EAC4 C4BA0108 */  j          .Llevel_21_8006EB10
    /* 1566864 8006EAC8 21280000 */   addu      $a1, $zero, $zero
  .Llevel_21_8006EACC:
    /* 1566868 8006EACC 08000224 */  addiu      $v0, $zero, 0x8
    /* 156686C 8006EAD0 0780013C */  lui        $at, %hi(D_8006A048)
    /* 1566870 8006EAD4 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 1566874 8006EAD8 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1566878 8006EADC 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 156687C 8006EAE0 C2B6000C */  jal        func_8002DB08
    /* 1566880 8006EAE4 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 1566884 8006EAE8 01000224 */  addiu      $v0, $zero, 0x1
    /* 1566888 8006EAEC 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 156688C 8006EAF0 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 1566890 8006EAF4 3A000224 */  addiu      $v0, $zero, 0x3A
    /* 1566894 8006EAF8 4C000216 */  bne        $s0, $v0, .Llevel_21_8006EC2C
    /* 1566898 8006EAFC 21280000 */   addu      $a1, $zero, $zero
    /* 156689C 8006EB00 0680023C */  lui        $v0, %hi(D_80067020)
    /* 15668A0 8006EB04 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 15668A4 8006EB08 00000000 */  nop
    /* 15668A8 8006EB0C 0C004490 */  lbu        $a0, 0xC($v0)
  .Llevel_21_8006EB10:
    /* 15668AC 8006EB10 C841010C */  jal        func_80050720
    /* 15668B0 8006EB14 21300000 */   addu      $a2, $zero, $zero
    /* 15668B4 8006EB18 0BBB0108 */  j          .Llevel_21_8006EC2C
    /* 15668B8 8006EB1C 00000000 */   nop
  .Llevel_21_8006EB20:
    /* 15668BC 8006EB20 0780013C */  lui        $at, %hi(D_8006A048)
    /* 15668C0 8006EB24 48A020AC */  sw         $zero, %lo(D_8006A048)($at)
    /* 15668C4 8006EB28 0780013C */  lui        $at, %hi(D_8006A044)
    /* 15668C8 8006EB2C 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 15668CC 8006EB30 AFB8000C */  jal        func_8002E2BC
    /* 15668D0 8006EB34 00000000 */   nop
    /* 15668D4 8006EB38 01000224 */  addiu      $v0, $zero, 0x1
    /* 15668D8 8006EB3C 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 15668DC 8006EB40 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 15668E0 8006EB44 0BBB0108 */  j          .Llevel_21_8006EC2C
    /* 15668E4 8006EB48 00000000 */   nop
  .Llevel_21_8006EB4C:
    /* 15668E8 8006EB4C 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 15668EC 8006EB50 48A06324 */  addiu      $v1, $v1, %lo(D_8006A048)
    /* 15668F0 8006EB54 48006424 */  addiu      $a0, $v1, 0x48
    /* 15668F4 8006EB58 09000224 */  addiu      $v0, $zero, 0x9
    /* 15668F8 8006EB5C 000062AC */  sw         $v0, 0x0($v1)
    /* 15668FC 8006EB60 0600023C */  lui        $v0, (0x60000 >> 16)
    /* 1566900 8006EB64 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1566904 8006EB68 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 1566908 8006EB6C 0780013C */  lui        $at, %hi(D_8006A128)
    /* 156690C 8006EB70 28A122AC */  sw         $v0, %lo(D_8006A128)($at)
    /* 1566910 8006EB74 886E000C */  jal        func_8001BA20
    /* 1566914 8006EB78 21280000 */   addu      $a1, $zero, $zero
    /* 1566918 8006EB7C 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 156691C 8006EB80 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 1566920 8006EB84 801E0224 */  addiu      $v0, $zero, 0x1E80
    /* 1566924 8006EB88 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 1566928 8006EB8C A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 156692C 8006EB90 C2B6000C */  jal        func_8002DB08
    /* 1566930 8006EB94 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 1566934 8006EB98 0780033C */  lui        $v1, %hi(D_8006A15C)
    /* 1566938 8006EB9C 5CA1638C */  lw         $v1, %lo(D_8006A15C)($v1)
    /* 156693C 8006EBA0 01000224 */  addiu      $v0, $zero, 0x1
    /* 1566940 8006EBA4 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 1566944 8006EBA8 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 1566948 8006EBAC 0B006014 */  bnez       $v1, .Llevel_21_8006EBDC
    /* 156694C 8006EBB0 00000000 */   nop
    /* 1566950 8006EBB4 0780023C */  lui        $v0, %hi(D_8006A1EC)
    /* 1566954 8006EBB8 ECA1428C */  lw         $v0, %lo(D_8006A1EC)($v0)
    /* 1566958 8006EBBC 00000000 */  nop
    /* 156695C 8006EBC0 06004014 */  bnez       $v0, .Llevel_21_8006EBDC
    /* 1566960 8006EBC4 06000224 */   addiu     $v0, $zero, 0x6
    /* 1566964 8006EBC8 0780033C */  lui        $v1, %hi(D_8006A1F0)
    /* 1566968 8006EBCC F0A1638C */  lw         $v1, %lo(D_8006A1F0)($v1)
    /* 156696C 8006EBD0 00000000 */  nop
    /* 1566970 8006EBD4 15006210 */  beq        $v1, $v0, .Llevel_21_8006EC2C
    /* 1566974 8006EBD8 00000000 */   nop
  .Llevel_21_8006EBDC:
    /* 1566978 8006EBDC 0780043C */  lui        $a0, %hi(D_8006A15C)
    /* 156697C 8006EBE0 5CA18424 */  addiu      $a0, $a0, %lo(D_8006A15C)
    /* 1566980 8006EBE4 0000838C */  lw         $v1, 0x0($a0)
    /* 1566984 8006EBE8 00000000 */  nop
    /* 1566988 8006EBEC FDFF6224 */  addiu      $v0, $v1, -0x3
    /* 156698C 8006EBF0 0200422C */  sltiu      $v0, $v0, 0x2
    /* 1566990 8006EBF4 03004014 */  bnez       $v0, .Llevel_21_8006EC04
    /* 1566994 8006EBF8 05000224 */   addiu     $v0, $zero, 0x5
    /* 1566998 8006EBFC 03006214 */  bne        $v1, $v0, .Llevel_21_8006EC0C
    /* 156699C 8006EC00 00000000 */   nop
  .Llevel_21_8006EC04:
    /* 15669A0 8006EC04 04BB0108 */  j          .Llevel_21_8006EC10
    /* 15669A4 8006EC08 000082AC */   sw        $v0, 0x0($a0)
  .Llevel_21_8006EC0C:
    /* 15669A8 8006EC0C 000080AC */  sw         $zero, 0x0($a0)
  .Llevel_21_8006EC10:
    /* 15669AC 8006EC10 06000224 */  addiu      $v0, $zero, 0x6
    /* 15669B0 8006EC14 0780013C */  lui        $at, %hi(D_8006A1EC)
    /* 15669B4 8006EC18 ECA120AC */  sw         $zero, %lo(D_8006A1EC)($at)
    /* 15669B8 8006EC1C 0780013C */  lui        $at, %hi(D_8006A1F0)
    /* 15669BC 8006EC20 F0A122AC */  sw         $v0, %lo(D_8006A1F0)($at)
    /* 15669C0 8006EC24 85C2000C */  jal        func_80030A14
    /* 15669C4 8006EC28 00000000 */   nop
  .Llevel_21_8006EC2C:
    /* 15669C8 8006EC2C 1400BF8F */  lw         $ra, 0x14($sp)
    /* 15669CC 8006EC30 1000B08F */  lw         $s0, 0x10($sp)
    /* 15669D0 8006EC34 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 15669D4 8006EC38 0800E003 */  jr         $ra
    /* 15669D8 8006EC3C 00000000 */   nop
endlabel func_level_21_8006E7A0
