.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_50_8006D388

dlabel jtbl_level_50_8006D388
    /* 370D924 8006D388 80EF0680 */ .word .Llevel_50_8006EF80
    /* 370D928 8006D38C 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D92C 8006D390 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D930 8006D394 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D934 8006D398 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D938 8006D39C 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D93C 8006D3A0 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D940 8006D3A4 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D944 8006D3A8 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D948 8006D3AC 90EF0680 */ .word .Llevel_50_8006EF90
    /* 370D94C 8006D3B0 80EF0680 */ .word .Llevel_50_8006EF80
    /* 370D950 8006D3B4 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D954 8006D3B8 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D958 8006D3BC 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D95C 8006D3C0 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D960 8006D3C4 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D964 8006D3C8 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D968 8006D3CC 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D96C 8006D3D0 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D970 8006D3D4 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D974 8006D3D8 80EF0680 */ .word .Llevel_50_8006EF80
    /* 370D978 8006D3DC 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D97C 8006D3E0 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D980 8006D3E4 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D984 8006D3E8 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D988 8006D3EC 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D98C 8006D3F0 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D990 8006D3F4 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D994 8006D3F8 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D998 8006D3FC 80EF0680 */ .word .Llevel_50_8006EF80
    /* 370D99C 8006D400 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D9A0 8006D404 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D9A4 8006D408 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D9A8 8006D40C 9CEF0680 */ .word .Llevel_50_8006EF9C
    /* 370D9AC 8006D410 80EF0680 */ .word .Llevel_50_8006EF80
    /* 370D9B0 8006D414 80EF0680 */ .word .Llevel_50_8006EF80
enddlabel jtbl_level_50_8006D388


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_50_8006EF30, 0x7C

glabel func_level_50_8006EF30
    /* 370F4CC 8006EF30 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 370F4D0 8006EF34 00210400 */  sll        $a0, $a0, 4
    /* 370F4D4 8006EF38 0780023C */  lui        $v0, %hi(D_800683B0)
    /* 370F4D8 8006EF3C B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* 370F4DC 8006EF40 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 370F4E0 8006EF44 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 370F4E4 8006EF48 21208200 */  addu       $a0, $a0, $v0
    /* 370F4E8 8006EF4C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 370F4EC 8006EF50 0680013C */  lui        $at, %hi(D_80066F38)
    /* 370F4F0 8006EF54 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* 370F4F4 8006EF58 F7FF6324 */  addiu      $v1, $v1, -0x9
    /* 370F4F8 8006EF5C 2400622C */  sltiu      $v0, $v1, 0x24
    /* 370F4FC 8006EF60 0E004010 */  beqz       $v0, .Llevel_50_8006EF9C
    /* 370F500 8006EF64 80100300 */   sll       $v0, $v1, 2
    /* 370F504 8006EF68 0780013C */  lui        $at, %hi(jtbl_level_50_8006D388)
    /* 370F508 8006EF6C 21082200 */  addu       $at, $at, $v0
    /* 370F50C 8006EF70 88D3228C */  lw         $v0, %lo(jtbl_level_50_8006D388)($at)
    /* 370F510 8006EF74 00000000 */  nop
    /* 370F514 8006EF78 08004000 */  jr         $v0
    /* 370F518 8006EF7C 00000000 */   nop
  .Llevel_50_8006EF80:
    /* 370F51C 8006EF80 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* 370F520 8006EF84 C4A08424 */  addiu      $a0, $a0, %lo(D_8006A0C4)
    /* 370F524 8006EF88 E5BB0108 */  j          .Llevel_50_8006EF94
    /* 370F528 8006EF8C 00000000 */   nop
  .Llevel_50_8006EF90:
    /* 370F52C 8006EF90 21200000 */  addu       $a0, $zero, $zero
  .Llevel_50_8006EF94:
    /* 370F530 8006EF94 E3B6000C */  jal        func_8002DB8C
    /* 370F534 8006EF98 00000000 */   nop
  .Llevel_50_8006EF9C:
    /* 370F538 8006EF9C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 370F53C 8006EFA0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 370F540 8006EFA4 0800E003 */  jr         $ra
    /* 370F544 8006EFA8 00000000 */   nop
endlabel func_level_50_8006EF30
