.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_43_8006D4D0

dlabel jtbl_level_43_8006D4D0
    /* 2FC4A6C 8006D4D0 50F30680 */ .word .Llevel_43_8006F350
    /* 2FC4A70 8006D4D4 C0F20680 */ .word .Llevel_43_8006F2C0
    /* 2FC4A74 8006D4D8 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4A78 8006D4DC 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4A7C 8006D4E0 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4A80 8006D4E4 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4A84 8006D4E8 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4A88 8006D4EC 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4A8C 8006D4F0 E4F40680 */ .word .Llevel_43_8006F4E4
    /* 2FC4A90 8006D4F4 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4A94 8006D4F8 64F50680 */ .word .Llevel_43_8006F564
    /* 2FC4A98 8006D4FC 30F40680 */ .word .Llevel_43_8006F430
    /* 2FC4A9C 8006D500 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4AA0 8006D504 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4AA4 8006D508 F8F50680 */ .word .Llevel_43_8006F5F8
    /* 2FC4AA8 8006D50C 4CF60680 */ .word .Llevel_43_8006F64C
    /* 2FC4AAC 8006D510 4CF60680 */ .word .Llevel_43_8006F64C
    /* 2FC4AB0 8006D514 4CF60680 */ .word .Llevel_43_8006F64C
    /* 2FC4AB4 8006D518 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4AB8 8006D51C 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4ABC 8006D520 C0F20680 */ .word .Llevel_43_8006F2C0
    /* 2FC4AC0 8006D524 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4AC4 8006D528 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4AC8 8006D52C 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4ACC 8006D530 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4AD0 8006D534 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4AD4 8006D538 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4AD8 8006D53C 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4ADC 8006D540 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4AE0 8006D544 E8F60680 */ .word .Llevel_43_8006F6E8
    /* 2FC4AE4 8006D548 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4AE8 8006D54C 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4AEC 8006D550 1CF70680 */ .word .Llevel_43_8006F71C
    /* 2FC4AF0 8006D554 1CF70680 */ .word .Llevel_43_8006F71C
    /* 2FC4AF4 8006D558 1CF70680 */ .word .Llevel_43_8006F71C
    /* 2FC4AF8 8006D55C 50F70680 */ .word .Llevel_43_8006F750
    /* 2FC4AFC 8006D560 50F70680 */ .word .Llevel_43_8006F750
    /* 2FC4B00 8006D564 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4B04 8006D568 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4B08 8006D56C 74F70680 */ .word .Llevel_43_8006F774
    /* 2FC4B0C 8006D570 F8F50680 */ .word .Llevel_43_8006F5F8
    /* 2FC4B10 8006D574 00000000 */ .word 0x00000000
enddlabel jtbl_level_43_8006D4D0


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_43_8006F288, 0x500

glabel func_level_43_8006F288
    /* 2FC6824 8006F288 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2FC6828 8006F28C 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2FC682C 8006F290 21808000 */  addu       $s0, $a0, $zero
    /* 2FC6830 8006F294 EEFF0326 */  addiu      $v1, $s0, -0x12
    /* 2FC6834 8006F298 2900622C */  sltiu      $v0, $v1, 0x29
    /* 2FC6838 8006F29C 35014010 */  beqz       $v0, .Llevel_43_8006F774
    /* 2FC683C 8006F2A0 1400BFAF */   sw        $ra, 0x14($sp)
    /* 2FC6840 8006F2A4 80100300 */  sll        $v0, $v1, 2
    /* 2FC6844 8006F2A8 0780013C */  lui        $at, %hi(jtbl_level_43_8006D4D0)
    /* 2FC6848 8006F2AC 21082200 */  addu       $at, $at, $v0
    /* 2FC684C 8006F2B0 D0D4228C */  lw         $v0, %lo(jtbl_level_43_8006D4D0)($at)
    /* 2FC6850 8006F2B4 00000000 */  nop
    /* 2FC6854 8006F2B8 08004000 */  jr         $v0
    /* 2FC6858 8006F2BC 00000000 */   nop
  .Llevel_43_8006F2C0:
    /* 2FC685C 8006F2C0 0780013C */  lui        $at, %hi(D_8006A048)
    /* 2FC6860 8006F2C4 48A020AC */  sw         $zero, %lo(D_8006A048)($at)
    /* 2FC6864 8006F2C8 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2FC6868 8006F2CC 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 2FC686C 8006F2D0 AFB8000C */  jal        func_8002E2BC
    /* 2FC6870 8006F2D4 00000000 */   nop
    /* 2FC6874 8006F2D8 01000224 */  addiu      $v0, $zero, 0x1
    /* 2FC6878 8006F2DC 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 2FC687C 8006F2E0 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 2FC6880 8006F2E4 25000224 */  addiu      $v0, $zero, 0x25
    /* 2FC6884 8006F2E8 04000216 */  bne        $s0, $v0, .Llevel_43_8006F2FC
    /* 2FC6888 8006F2EC 01000424 */   addiu     $a0, $zero, 0x1
    /* 2FC688C 8006F2F0 05000424 */  addiu      $a0, $zero, 0x5
    /* 2FC6890 8006F2F4 C0BC0108 */  j          .Llevel_43_8006F300
    /* 2FC6894 8006F2F8 08000524 */   addiu     $a1, $zero, 0x8
  .Llevel_43_8006F2FC:
    /* 2FC6898 8006F2FC 03000524 */  addiu      $a1, $zero, 0x3
  .Llevel_43_8006F300:
    /* 2FC689C 8006F300 47E2000C */  jal        func_8003891C
    /* 2FC68A0 8006F304 00000000 */   nop
    /* 2FC68A4 8006F308 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 2FC68A8 8006F30C 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* 2FC68AC 8006F310 0680033C */  lui        $v1, %hi(D_800670B4)
    /* 2FC68B0 8006F314 B470638C */  lw         $v1, %lo(D_800670B4)($v1)
    /* 2FC68B4 8006F318 0780013C */  lui        $at, %hi(D_8006A140)
    /* 2FC68B8 8006F31C 40A120AC */  sw         $zero, %lo(D_8006A140)($at)
    /* 2FC68BC 8006F320 14016010 */  beqz       $v1, .Llevel_43_8006F774
    /* 2FC68C0 8006F324 25000224 */   addiu     $v0, $zero, 0x25
    /* 2FC68C4 8006F328 03000216 */  bne        $s0, $v0, .Llevel_43_8006F338
    /* 2FC68C8 8006F32C 27000224 */   addiu     $v0, $zero, 0x27
    /* 2FC68CC 8006F330 D0BC0108 */  j          .Llevel_43_8006F340
    /* 2FC68D0 8006F334 F1010424 */   addiu     $a0, $zero, 0x1F1
  .Llevel_43_8006F338:
    /* 2FC68D4 8006F338 0E010216 */  bne        $s0, $v0, .Llevel_43_8006F774
    /* 2FC68D8 8006F33C DB010424 */   addiu     $a0, $zero, 0x1DB
  .Llevel_43_8006F340:
    /* 2FC68DC 8006F340 09F86000 */  jalr       $v1
    /* 2FC68E0 8006F344 21280000 */   addu      $a1, $zero, $zero
    /* 2FC68E4 8006F348 DDBD0108 */  j          .Llevel_43_8006F774
    /* 2FC68E8 8006F34C 00000000 */   nop
  .Llevel_43_8006F350:
    /* 2FC68EC 8006F350 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 2FC68F0 8006F354 48A06324 */  addiu      $v1, $v1, %lo(D_8006A048)
    /* 2FC68F4 8006F358 0780023C */  lui        $v0, %hi(D_8006A208)
    /* 2FC68F8 8006F35C 08A2428C */  lw         $v0, %lo(D_8006A208)($v0)
    /* 2FC68FC 8006F360 00000000 */  nop
    /* 2FC6900 8006F364 0000508C */  lw         $s0, 0x0($v0)
    /* 2FC6904 8006F368 0E000224 */  addiu      $v0, $zero, 0xE
    /* 2FC6908 8006F36C 000062AC */  sw         $v0, 0x0($v1)
    /* 2FC690C 8006F370 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2FC6910 8006F374 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 2FC6914 8006F378 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 2FC6918 8006F37C ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 2FC691C 8006F380 686F000C */  jal        func_8001BDA0
    /* 2FC6920 8006F384 3C006424 */   addiu     $a0, $v1, 0x3C
    /* 2FC6924 8006F388 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 2FC6928 8006F38C 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 2FC692C 8006F390 0780063C */  lui        $a2, %hi(D_8006A05C)
    /* 2FC6930 8006F394 5CA0C68C */  lw         $a2, %lo(D_8006A05C)($a2)
    /* 2FC6934 8006F398 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 2FC6938 8006F39C F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 2FC693C 8006F3A0 1400A38C */  lw         $v1, 0x14($a1)
    /* 2FC6940 8006F3A4 0000048E */  lw         $a0, 0x0($s0)
    /* 2FC6944 8006F3A8 0780013C */  lui        $at, %hi(D_8006A140)
    /* 2FC6948 8006F3AC 40A126AC */  sw         $a2, %lo(D_8006A140)($at)
    /* 2FC694C 8006F3B0 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 2FC6950 8006F3B4 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* 2FC6954 8006F3B8 21186400 */  addu       $v1, $v1, $a0
    /* 2FC6958 8006F3BC 0780013C */  lui        $at, %hi(D_8006A144)
    /* 2FC695C 8006F3C0 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 2FC6960 8006F3C4 23186200 */  subu       $v1, $v1, $v0
    /* 2FC6964 8006F3C8 00F86324 */  addiu      $v1, $v1, -0x800
    /* 2FC6968 8006F3CC 0780013C */  lui        $at, %hi(D_8006A14C)
    /* 2FC696C 8006F3D0 4CA123AC */  sw         $v1, %lo(D_8006A14C)($at)
    /* 2FC6970 8006F3D4 801A0300 */  sll        $v1, $v1, 10
    /* 2FC6974 8006F3D8 831A0300 */  sra        $v1, $v1, 10
    /* 2FC6978 8006F3DC 00046324 */  addiu      $v1, $v1, 0x400
    /* 2FC697C 8006F3E0 0780013C */  lui        $at, %hi(D_8006A148)
    /* 2FC6980 8006F3E4 48A123AC */  sw         $v1, %lo(D_8006A148)($at)
    /* 2FC6984 8006F3E8 4600A290 */  lbu        $v0, 0x46($a1)
    /* 2FC6988 8006F3EC 00000000 */  nop
    /* 2FC698C 8006F3F0 00110200 */  sll        $v0, $v0, 4
    /* 2FC6990 8006F3F4 23104600 */  subu       $v0, $v0, $a2
    /* 2FC6994 8006F3F8 23104300 */  subu       $v0, $v0, $v1
    /* 2FC6998 8006F3FC FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 2FC699C 8006F400 01086228 */  slti       $v0, $v1, 0x801
    /* 2FC69A0 8006F404 0780013C */  lui        $at, %hi(D_8006A148)
    /* 2FC69A4 8006F408 48A123AC */  sw         $v1, %lo(D_8006A148)($at)
    /* 2FC69A8 8006F40C 03004014 */  bnez       $v0, .Llevel_43_8006F41C
    /* 2FC69AC 8006F410 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 2FC69B0 8006F414 0780013C */  lui        $at, %hi(D_8006A148)
    /* 2FC69B4 8006F418 48A122AC */  sw         $v0, %lo(D_8006A148)($at)
  .Llevel_43_8006F41C:
    /* 2FC69B8 8006F41C 0400028E */  lw         $v0, 0x4($s0)
    /* 2FC69BC 8006F420 0780013C */  lui        $at, %hi(D_8006A150)
    /* 2FC69C0 8006F424 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 2FC69C4 8006F428 DDBD0108 */  j          .Llevel_43_8006F774
    /* 2FC69C8 8006F42C 00000000 */   nop
  .Llevel_43_8006F430:
    /* 2FC69CC 8006F430 0780043C */  lui        $a0, %hi(D_8006A048)
    /* 2FC69D0 8006F434 48A0848C */  lw         $a0, %lo(D_8006A048)($a0)
    /* 2FC69D4 8006F438 0780033C */  lui        $v1, %hi(D_8006A20C)
    /* 2FC69D8 8006F43C 0CA2638C */  lw         $v1, %lo(D_8006A20C)($v1)
    /* 2FC69DC 8006F440 07000224 */  addiu      $v0, $zero, 0x7
    /* 2FC69E0 8006F444 0780013C */  lui        $at, %hi(D_8006A048)
    /* 2FC69E4 8006F448 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 2FC69E8 8006F44C 0780023C */  lui        $v0, %hi(D_8006A210)
    /* 2FC69EC 8006F450 10A2428C */  lw         $v0, %lo(D_8006A210)($v0)
    /* 2FC69F0 8006F454 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2FC69F4 8006F458 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 2FC69F8 8006F45C 80190300 */  sll        $v1, $v1, 6
    /* 2FC69FC 8006F460 0780013C */  lui        $at, %hi(D_8006A084)
    /* 2FC6A00 8006F464 84A023AC */  sw         $v1, %lo(D_8006A084)($at)
    /* 2FC6A04 8006F468 0780033C */  lui        $v1, %hi(D_8006A214)
    /* 2FC6A08 8006F46C 14A2638C */  lw         $v1, %lo(D_8006A214)($v1)
    /* 2FC6A0C 8006F470 80110200 */  sll        $v0, $v0, 6
    /* 2FC6A10 8006F474 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 2FC6A14 8006F478 3CA124AC */  sw         $a0, %lo(D_8006A13C)($at)
    /* 2FC6A18 8006F47C 0780013C */  lui        $at, %hi(D_8006A088)
    /* 2FC6A1C 8006F480 88A022AC */  sw         $v0, %lo(D_8006A088)($at)
    /* 2FC6A20 8006F484 03006014 */  bnez       $v1, .Llevel_43_8006F494
    /* 2FC6A24 8006F488 80110300 */   sll       $v0, $v1, 6
    /* 2FC6A28 8006F48C 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 2FC6A2C 8006F490 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
  .Llevel_43_8006F494:
    /* 2FC6A30 8006F494 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 2FC6A34 8006F498 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 2FC6A38 8006F49C C2B6000C */  jal        func_8002DB08
    /* 2FC6A3C 8006F4A0 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 2FC6A40 8006F4A4 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 2FC6A44 8006F4A8 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 2FC6A48 8006F4AC 01000224 */  addiu      $v0, $zero, 0x1
    /* 2FC6A4C 8006F4B0 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 2FC6A50 8006F4B4 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 2FC6A54 8006F4B8 0F000224 */  addiu      $v0, $zero, 0xF
    /* 2FC6A58 8006F4BC 0780013C */  lui        $at, %hi(D_8006838C)
    /* 2FC6A5C 8006F4C0 8C8322AC */  sw         $v0, %lo(D_8006838C)($at)
    /* 2FC6A60 8006F4C4 AB006010 */  beqz       $v1, .Llevel_43_8006F774
    /* 2FC6A64 8006F4C8 05000424 */   addiu     $a0, $zero, 0x5
    /* 2FC6A68 8006F4CC 0A000524 */  addiu      $a1, $zero, 0xA
    /* 2FC6A6C 8006F4D0 21300000 */  addu       $a2, $zero, $zero
    /* 2FC6A70 8006F4D4 09F86000 */  jalr       $v1
    /* 2FC6A74 8006F4D8 21380000 */   addu      $a3, $zero, $zero
    /* 2FC6A78 8006F4DC DDBD0108 */  j          .Llevel_43_8006F774
    /* 2FC6A7C 8006F4E0 00000000 */   nop
  .Llevel_43_8006F4E4:
    /* 2FC6A80 8006F4E4 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 2FC6A84 8006F4E8 3CA16324 */  addiu      $v1, $v1, %lo(D_8006A13C)
    /* 2FC6A88 8006F4EC 48FF6424 */  addiu      $a0, $v1, -0xB8
    /* 2FC6A8C 8006F4F0 0780053C */  lui        $a1, %hi(D_8006A048)
    /* 2FC6A90 8006F4F4 48A0A58C */  lw         $a1, %lo(D_8006A048)($a1)
    /* 2FC6A94 8006F4F8 07000224 */  addiu      $v0, $zero, 0x7
    /* 2FC6A98 8006F4FC 0780013C */  lui        $at, %hi(D_8006A048)
    /* 2FC6A9C 8006F500 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 2FC6AA0 8006F504 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2FC6AA4 8006F508 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 2FC6AA8 8006F50C 686F000C */  jal        func_8001BDA0
    /* 2FC6AAC 8006F510 000065AC */   sw        $a1, 0x0($v1)
    /* 2FC6AB0 8006F514 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 2FC6AB4 8006F518 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 2FC6AB8 8006F51C 01000224 */  addiu      $v0, $zero, 0x1
    /* 2FC6ABC 8006F520 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 2FC6AC0 8006F524 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 2FC6AC4 8006F528 0F000224 */  addiu      $v0, $zero, 0xF
    /* 2FC6AC8 8006F52C 0780013C */  lui        $at, %hi(D_8006838C)
    /* 2FC6ACC 8006F530 8C8322AC */  sw         $v0, %lo(D_8006838C)($at)
    /* 2FC6AD0 8006F534 05006010 */  beqz       $v1, .Llevel_43_8006F54C
    /* 2FC6AD4 8006F538 05000424 */   addiu     $a0, $zero, 0x5
    /* 2FC6AD8 8006F53C 0A000524 */  addiu      $a1, $zero, 0xA
    /* 2FC6ADC 8006F540 21300000 */  addu       $a2, $zero, $zero
    /* 2FC6AE0 8006F544 09F86000 */  jalr       $v1
    /* 2FC6AE4 8006F548 21380000 */   addu      $a3, $zero, $zero
  .Llevel_43_8006F54C:
    /* 2FC6AE8 8006F54C 0680023C */  lui        $v0, %hi(D_80067020)
    /* 2FC6AEC 8006F550 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 2FC6AF0 8006F554 00000000 */  nop
    /* 2FC6AF4 8006F558 09004490 */  lbu        $a0, 0x9($v0)
    /* 2FC6AF8 8006F55C 8FBD0108 */  j          .Llevel_43_8006F63C
    /* 2FC6AFC 8006F560 21280000 */   addu      $a1, $zero, $zero
  .Llevel_43_8006F564:
    /* 2FC6B00 8006F564 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 2FC6B04 8006F568 3CA16324 */  addiu      $v1, $v1, %lo(D_8006A13C)
    /* 2FC6B08 8006F56C 48FF6424 */  addiu      $a0, $v1, -0xB8
    /* 2FC6B0C 8006F570 54FF7024 */  addiu      $s0, $v1, -0xAC
    /* 2FC6B10 8006F574 21280002 */  addu       $a1, $s0, $zero
    /* 2FC6B14 8006F578 0780063C */  lui        $a2, %hi(D_8006A048)
    /* 2FC6B18 8006F57C 48A0C68C */  lw         $a2, %lo(D_8006A048)($a2)
    /* 2FC6B1C 8006F580 07000224 */  addiu      $v0, $zero, 0x7
    /* 2FC6B20 8006F584 0780013C */  lui        $at, %hi(D_8006A048)
    /* 2FC6B24 8006F588 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 2FC6B28 8006F58C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2FC6B2C 8006F590 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 2FC6B30 8006F594 6C6F000C */  jal        func_8001BDB0
    /* 2FC6B34 8006F598 000066AC */   sw        $a2, 0x0($v1)
    /* 2FC6B38 8006F59C 21200002 */  addu       $a0, $s0, $zero
    /* 2FC6B3C 8006F5A0 886E000C */  jal        func_8001BA20
    /* 2FC6B40 8006F5A4 21280000 */   addu      $a1, $zero, $zero
    /* 2FC6B44 8006F5A8 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 2FC6B48 8006F5AC FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 2FC6B4C 8006F5B0 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 2FC6B50 8006F5B4 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 2FC6B54 8006F5B8 C00D0224 */  addiu      $v0, $zero, 0xDC0
    /* 2FC6B58 8006F5BC 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 2FC6B5C 8006F5C0 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 2FC6B60 8006F5C4 0F000224 */  addiu      $v0, $zero, 0xF
    /* 2FC6B64 8006F5C8 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 2FC6B68 8006F5CC ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 2FC6B6C 8006F5D0 0780013C */  lui        $at, %hi(D_8006838C)
    /* 2FC6B70 8006F5D4 8C8322AC */  sw         $v0, %lo(D_8006838C)($at)
    /* 2FC6B74 8006F5D8 14006010 */  beqz       $v1, .Llevel_43_8006F62C
    /* 2FC6B78 8006F5DC 05000424 */   addiu     $a0, $zero, 0x5
    /* 2FC6B7C 8006F5E0 0A000524 */  addiu      $a1, $zero, 0xA
    /* 2FC6B80 8006F5E4 21300000 */  addu       $a2, $zero, $zero
    /* 2FC6B84 8006F5E8 09F86000 */  jalr       $v1
    /* 2FC6B88 8006F5EC 21380000 */   addu      $a3, $zero, $zero
    /* 2FC6B8C 8006F5F0 8BBD0108 */  j          .Llevel_43_8006F62C
    /* 2FC6B90 8006F5F4 00000000 */   nop
  .Llevel_43_8006F5F8:
    /* 2FC6B94 8006F5F8 08000224 */  addiu      $v0, $zero, 0x8
    /* 2FC6B98 8006F5FC 0780013C */  lui        $at, %hi(D_8006A048)
    /* 2FC6B9C 8006F600 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 2FC6BA0 8006F604 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2FC6BA4 8006F608 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 2FC6BA8 8006F60C C2B6000C */  jal        func_8002DB08
    /* 2FC6BAC 8006F610 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 2FC6BB0 8006F614 01000224 */  addiu      $v0, $zero, 0x1
    /* 2FC6BB4 8006F618 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 2FC6BB8 8006F61C ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 2FC6BBC 8006F620 3A000224 */  addiu      $v0, $zero, 0x3A
    /* 2FC6BC0 8006F624 53000216 */  bne        $s0, $v0, .Llevel_43_8006F774
    /* 2FC6BC4 8006F628 00000000 */   nop
  .Llevel_43_8006F62C:
    /* 2FC6BC8 8006F62C 0680023C */  lui        $v0, %hi(D_80067020)
    /* 2FC6BCC 8006F630 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 2FC6BD0 8006F634 21280000 */  addu       $a1, $zero, $zero
    /* 2FC6BD4 8006F638 0C004490 */  lbu        $a0, 0xC($v0)
  .Llevel_43_8006F63C:
    /* 2FC6BD8 8006F63C C841010C */  jal        func_80050720
    /* 2FC6BDC 8006F640 21300000 */   addu      $a2, $zero, $zero
    /* 2FC6BE0 8006F644 DDBD0108 */  j          .Llevel_43_8006F774
    /* 2FC6BE4 8006F648 00000000 */   nop
  .Llevel_43_8006F64C:
    /* 2FC6BE8 8006F64C 0780103C */  lui        $s0, %hi(D_8006A048)
    /* 2FC6BEC 8006F650 48A01026 */  addiu      $s0, $s0, %lo(D_8006A048)
    /* 2FC6BF0 8006F654 0000028E */  lw         $v0, 0x0($s0)
    /* 2FC6BF4 8006F658 06000324 */  addiu      $v1, $zero, 0x6
    /* 2FC6BF8 8006F65C 45004310 */  beq        $v0, $v1, .Llevel_43_8006F774
    /* 2FC6BFC 8006F660 00000000 */   nop
    /* 2FC6C00 8006F664 000003AE */  sw         $v1, 0x0($s0)
    /* 2FC6C04 8006F668 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2FC6C08 8006F66C 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 2FC6C0C 8006F670 686F000C */  jal        func_8001BDA0
    /* 2FC6C10 8006F674 FC000426 */   addiu     $a0, $s0, 0xFC
    /* 2FC6C14 8006F678 48000426 */  addiu      $a0, $s0, 0x48
    /* 2FC6C18 8006F67C 0780013C */  lui        $at, %hi(D_8006A150)
    /* 2FC6C1C 8006F680 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 2FC6C20 8006F684 886E000C */  jal        func_8001BA20
    /* 2FC6C24 8006F688 21280000 */   addu      $a1, $zero, $zero
    /* 2FC6C28 8006F68C 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 2FC6C2C 8006F690 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 2FC6C30 8006F694 00084228 */  slti       $v0, $v0, 0x800
    /* 2FC6C34 8006F698 03004010 */  beqz       $v0, .Llevel_43_8006F6A8
    /* 2FC6C38 8006F69C 00080224 */   addiu     $v0, $zero, 0x800
    /* 2FC6C3C 8006F6A0 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 2FC6C40 8006F6A4 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_43_8006F6A8:
    /* 2FC6C44 8006F6A8 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 2FC6C48 8006F6AC A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 2FC6C4C 8006F6B0 00000000 */  nop
    /* 2FC6C50 8006F6B4 014B4228 */  slti       $v0, $v0, 0x4B01
    /* 2FC6C54 8006F6B8 03004014 */  bnez       $v0, .Llevel_43_8006F6C8
    /* 2FC6C58 8006F6BC 004B0224 */   addiu     $v0, $zero, 0x4B00
    /* 2FC6C5C 8006F6C0 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 2FC6C60 8006F6C4 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_43_8006F6C8:
    /* 2FC6C64 8006F6C8 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 2FC6C68 8006F6CC 3CA120AC */  sw         $zero, %lo(D_8006A13C)($at)
    /* 2FC6C6C 8006F6D0 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 2FC6C70 8006F6D4 ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 2FC6C74 8006F6D8 0780013C */  lui        $at, %hi(D_8006A1AD)
    /* 2FC6C78 8006F6DC ADA120A0 */  sb         $zero, %lo(D_8006A1AD)($at)
    /* 2FC6C7C 8006F6E0 DDBD0108 */  j          .Llevel_43_8006F774
    /* 2FC6C80 8006F6E4 00000000 */   nop
  .Llevel_43_8006F6E8:
    /* 2FC6C84 8006F6E8 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 2FC6C88 8006F6EC 48A06324 */  addiu      $v1, $v1, %lo(D_8006A048)
    /* 2FC6C8C 8006F6F0 0000628C */  lw         $v0, 0x0($v1)
    /* 2FC6C90 8006F6F4 0D000624 */  addiu      $a2, $zero, 0xD
    /* 2FC6C94 8006F6F8 1E004610 */  beq        $v0, $a2, .Llevel_43_8006F774
    /* 2FC6C98 8006F6FC 3C006424 */   addiu     $a0, $v1, 0x3C
    /* 2FC6C9C 8006F700 000066AC */  sw         $a2, 0x0($v1)
    /* 2FC6CA0 8006F704 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2FC6CA4 8006F708 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 2FC6CA8 8006F70C 6C6F000C */  jal        func_8001BDB0
    /* 2FC6CAC 8006F710 48006524 */   addiu     $a1, $v1, 0x48
    /* 2FC6CB0 8006F714 DBBD0108 */  j          .Llevel_43_8006F76C
    /* 2FC6CB4 8006F718 01000224 */   addiu     $v0, $zero, 0x1
  .Llevel_43_8006F71C:
    /* 2FC6CB8 8006F71C 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 2FC6CBC 8006F720 48A06324 */  addiu      $v1, $v1, %lo(D_8006A048)
    /* 2FC6CC0 8006F724 0000628C */  lw         $v0, 0x0($v1)
    /* 2FC6CC4 8006F728 0D000624 */  addiu      $a2, $zero, 0xD
    /* 2FC6CC8 8006F72C 11004610 */  beq        $v0, $a2, .Llevel_43_8006F774
    /* 2FC6CCC 8006F730 3C006424 */   addiu     $a0, $v1, 0x3C
    /* 2FC6CD0 8006F734 000066AC */  sw         $a2, 0x0($v1)
    /* 2FC6CD4 8006F738 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2FC6CD8 8006F73C 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 2FC6CDC 8006F740 6C6F000C */  jal        func_8001BDB0
    /* 2FC6CE0 8006F744 48006524 */   addiu     $a1, $v1, 0x48
    /* 2FC6CE4 8006F748 DBBD0108 */  j          .Llevel_43_8006F76C
    /* 2FC6CE8 8006F74C 01000224 */   addiu     $v0, $zero, 0x1
  .Llevel_43_8006F750:
    /* 2FC6CEC 8006F750 0780013C */  lui        $at, %hi(D_8006A048)
    /* 2FC6CF0 8006F754 48A020AC */  sw         $zero, %lo(D_8006A048)($at)
    /* 2FC6CF4 8006F758 0780013C */  lui        $at, %hi(D_8006A044)
    /* 2FC6CF8 8006F75C 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 2FC6CFC 8006F760 AFB8000C */  jal        func_8002E2BC
    /* 2FC6D00 8006F764 00000000 */   nop
    /* 2FC6D04 8006F768 01000224 */  addiu      $v0, $zero, 0x1
  .Llevel_43_8006F76C:
    /* 2FC6D08 8006F76C 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 2FC6D0C 8006F770 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
  .Llevel_43_8006F774:
    /* 2FC6D10 8006F774 1400BF8F */  lw         $ra, 0x14($sp)
    /* 2FC6D14 8006F778 1000B08F */  lw         $s0, 0x10($sp)
    /* 2FC6D18 8006F77C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2FC6D1C 8006F780 0800E003 */  jr         $ra
    /* 2FC6D20 8006F784 00000000 */   nop
endlabel func_level_43_8006F288
