.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_43_8006D3B8

dlabel jtbl_level_43_8006D3B8
    /* 2FC4954 8006D3B8 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4958 8006D3BC D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC495C 8006D3C0 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4960 8006D3C4 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4964 8006D3C8 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4968 8006D3CC D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC496C 8006D3D0 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4970 8006D3D4 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4974 8006D3D8 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4978 8006D3DC D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC497C 8006D3E0 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4980 8006D3E4 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4984 8006D3E8 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4988 8006D3EC D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC498C 8006D3F0 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4990 8006D3F4 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4994 8006D3F8 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC4998 8006D3FC D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC499C 8006D400 C8F00680 */ .word .Llevel_43_8006F0C8
    /* 2FC49A0 8006D404 28F10680 */ .word .Llevel_43_8006F128
    /* 2FC49A4 8006D408 28F10680 */ .word .Llevel_43_8006F128
    /* 2FC49A8 8006D40C D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC49AC 8006D410 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC49B0 8006D414 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC49B4 8006D418 D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC49B8 8006D41C D8F10680 */ .word .Llevel_43_8006F1D8
    /* 2FC49BC 8006D420 9CF10680 */ .word .Llevel_43_8006F19C
    /* 2FC49C0 8006D424 00000000 */ .word 0x00000000
enddlabel jtbl_level_43_8006D3B8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_43_8006F088, 0x168

glabel func_level_43_8006F088
    /* 2FC6624 8006F088 0780023C */  lui        $v0, %hi(D_8006A004)
    /* 2FC6628 8006F08C 04A04290 */  lbu        $v0, %lo(D_8006A004)($v0)
    /* 2FC662C 8006F090 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2FC6630 8006F094 1800BFAF */  sw         $ra, 0x18($sp)
    /* 2FC6634 8006F098 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2FC6638 8006F09C E0FF4324 */  addiu      $v1, $v0, -0x20
    /* 2FC663C 8006F0A0 1B00622C */  sltiu      $v0, $v1, 0x1B
    /* 2FC6640 8006F0A4 4C004010 */  beqz       $v0, .Llevel_43_8006F1D8
    /* 2FC6644 8006F0A8 1000B0AF */   sw        $s0, 0x10($sp)
    /* 2FC6648 8006F0AC 80100300 */  sll        $v0, $v1, 2
    /* 2FC664C 8006F0B0 0780013C */  lui        $at, %hi(jtbl_level_43_8006D3B8)
    /* 2FC6650 8006F0B4 21082200 */  addu       $at, $at, $v0
    /* 2FC6654 8006F0B8 B8D3228C */  lw         $v0, %lo(jtbl_level_43_8006D3B8)($at)
    /* 2FC6658 8006F0BC 00000000 */  nop
    /* 2FC665C 8006F0C0 08004000 */  jr         $v0
    /* 2FC6660 8006F0C4 00000000 */   nop
  .Llevel_43_8006F0C8:
    /* 2FC6664 8006F0C8 0780103C */  lui        $s0, %hi(D_8006A006)
    /* 2FC6668 8006F0CC 06A01026 */  addiu      $s0, $s0, %lo(D_8006A006)
    /* 2FC666C 8006F0D0 00000392 */  lbu        $v1, 0x0($s0)
    /* 2FC6670 8006F0D4 03000224 */  addiu      $v0, $zero, 0x3
    /* 2FC6674 8006F0D8 03006210 */  beq        $v1, $v0, .Llevel_43_8006F0E8
    /* 2FC6678 8006F0DC 0A000224 */   addiu     $v0, $zero, 0xA
    /* 2FC667C 8006F0E0 3D006214 */  bne        $v1, $v0, .Llevel_43_8006F1D8
    /* 2FC6680 8006F0E4 00000000 */   nop
  .Llevel_43_8006F0E8:
    /* 2FC6684 8006F0E8 0680023C */  lui        $v0, %hi(D_80067020)
    /* 2FC6688 8006F0EC 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 2FC668C 8006F0F0 21280000 */  addu       $a1, $zero, $zero
    /* 2FC6690 8006F0F4 11004490 */  lbu        $a0, 0x11($v0)
    /* 2FC6694 8006F0F8 C841010C */  jal        func_80050720
    /* 2FC6698 8006F0FC 21300000 */   addu      $a2, $zero, $zero
    /* 2FC669C 8006F100 00000392 */  lbu        $v1, 0x0($s0)
    /* 2FC66A0 8006F104 21204000 */  addu       $a0, $v0, $zero
    /* 2FC66A4 8006F108 0780013C */  lui        $at, %hi(D_8006A268)
    /* 2FC66A8 8006F10C 68A223AC */  sw         $v1, %lo(D_8006A268)($at)
    /* 2FC66AC 8006F110 31008004 */  bltz       $a0, .Llevel_43_8006F1D8
    /* 2FC66B0 8006F114 0A000224 */   addiu     $v0, $zero, 0xA
    /* 2FC66B4 8006F118 1C006210 */  beq        $v1, $v0, .Llevel_43_8006F18C
    /* 2FC66B8 8006F11C 00000000 */   nop
    /* 2FC66BC 8006F120 76BC0108 */  j          .Llevel_43_8006F1D8
    /* 2FC66C0 8006F124 00000000 */   nop
  .Llevel_43_8006F128:
    /* 2FC66C4 8006F128 0780103C */  lui        $s0, %hi(D_8006A006)
    /* 2FC66C8 8006F12C 06A01026 */  addiu      $s0, $s0, %lo(D_8006A006)
    /* 2FC66CC 8006F130 00000392 */  lbu        $v1, 0x0($s0)
    /* 2FC66D0 8006F134 01001124 */  addiu      $s1, $zero, 0x1
    /* 2FC66D4 8006F138 03007110 */  beq        $v1, $s1, .Llevel_43_8006F148
    /* 2FC66D8 8006F13C 03000224 */   addiu     $v0, $zero, 0x3
    /* 2FC66DC 8006F140 25006214 */  bne        $v1, $v0, .Llevel_43_8006F1D8
    /* 2FC66E0 8006F144 00000000 */   nop
  .Llevel_43_8006F148:
    /* 2FC66E4 8006F148 0680023C */  lui        $v0, %hi(D_80067020)
    /* 2FC66E8 8006F14C 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 2FC66EC 8006F150 21280000 */  addu       $a1, $zero, $zero
    /* 2FC66F0 8006F154 11004490 */  lbu        $a0, 0x11($v0)
    /* 2FC66F4 8006F158 C841010C */  jal        func_80050720
    /* 2FC66F8 8006F15C 21300000 */   addu      $a2, $zero, $zero
    /* 2FC66FC 8006F160 00000392 */  lbu        $v1, 0x0($s0)
    /* 2FC6700 8006F164 21804000 */  addu       $s0, $v0, $zero
    /* 2FC6704 8006F168 0780013C */  lui        $at, %hi(D_8006A268)
    /* 2FC6708 8006F16C 68A223AC */  sw         $v1, %lo(D_8006A268)($at)
    /* 2FC670C 8006F170 19000006 */  bltz       $s0, .Llevel_43_8006F1D8
    /* 2FC6710 8006F174 00000000 */   nop
    /* 2FC6714 8006F178 17007114 */  bne        $v1, $s1, .Llevel_43_8006F1D8
    /* 2FC6718 8006F17C 21200002 */   addu      $a0, $s0, $zero
    /* 2FC671C 8006F180 3D43010C */  jal        func_80050CF4
    /* 2FC6720 8006F184 000C0524 */   addiu     $a1, $zero, 0xC00
    /* 2FC6724 8006F188 21200002 */  addu       $a0, $s0, $zero
  .Llevel_43_8006F18C:
    /* 2FC6728 8006F18C 1943010C */  jal        func_80050C64
    /* 2FC672C 8006F190 00120524 */   addiu     $a1, $zero, 0x1200
    /* 2FC6730 8006F194 76BC0108 */  j          .Llevel_43_8006F1D8
    /* 2FC6734 8006F198 00000000 */   nop
  .Llevel_43_8006F19C:
    /* 2FC6738 8006F19C 0780103C */  lui        $s0, %hi(D_8006A006)
    /* 2FC673C 8006F1A0 06A01026 */  addiu      $s0, $s0, %lo(D_8006A006)
    /* 2FC6740 8006F1A4 00000392 */  lbu        $v1, 0x0($s0)
    /* 2FC6744 8006F1A8 0D000224 */  addiu      $v0, $zero, 0xD
    /* 2FC6748 8006F1AC 0A006214 */  bne        $v1, $v0, .Llevel_43_8006F1D8
    /* 2FC674C 8006F1B0 21280000 */   addu      $a1, $zero, $zero
    /* 2FC6750 8006F1B4 0680023C */  lui        $v0, %hi(D_80067020)
    /* 2FC6754 8006F1B8 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 2FC6758 8006F1BC 00000000 */  nop
    /* 2FC675C 8006F1C0 0D004490 */  lbu        $a0, 0xD($v0)
    /* 2FC6760 8006F1C4 C841010C */  jal        func_80050720
    /* 2FC6764 8006F1C8 21300000 */   addu      $a2, $zero, $zero
    /* 2FC6768 8006F1CC 00000292 */  lbu        $v0, 0x0($s0)
    /* 2FC676C 8006F1D0 0780013C */  lui        $at, %hi(D_8006A268)
    /* 2FC6770 8006F1D4 68A222AC */  sw         $v0, %lo(D_8006A268)($at)
  .Llevel_43_8006F1D8:
    /* 2FC6774 8006F1D8 1800BF8F */  lw         $ra, 0x18($sp)
    /* 2FC6778 8006F1DC 1400B18F */  lw         $s1, 0x14($sp)
    /* 2FC677C 8006F1E0 1000B08F */  lw         $s0, 0x10($sp)
    /* 2FC6780 8006F1E4 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 2FC6784 8006F1E8 0800E003 */  jr         $ra
    /* 2FC6788 8006F1EC 00000000 */   nop
endlabel func_level_43_8006F088
