.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_30_8006D268

dlabel jtbl_level_30_8006D268
    /* 1F2B004 8006D268 00D90680 */ .word .Llevel_30_8006D900
    /* 1F2B008 8006D26C B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B00C 8006D270 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B010 8006D274 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B014 8006D278 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B018 8006D27C B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B01C 8006D280 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B020 8006D284 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B024 8006D288 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B028 8006D28C B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B02C 8006D290 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B030 8006D294 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B034 8006D298 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B038 8006D29C B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B03C 8006D2A0 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B040 8006D2A4 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B044 8006D2A8 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B048 8006D2AC B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B04C 8006D2B0 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B050 8006D2B4 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B054 8006D2B8 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B058 8006D2BC B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B05C 8006D2C0 14DC0680 */ .word .Llevel_30_8006DC14
    /* 1F2B060 8006D2C4 FCDE0680 */ .word .Llevel_30_8006DEFC
    /* 1F2B064 8006D2C8 08E10680 */ .word .Llevel_30_8006E108
    /* 1F2B068 8006D2CC 9CE30680 */ .word .Llevel_30_8006E39C
    /* 1F2B06C 8006D2D0 9CE30680 */ .word .Llevel_30_8006E39C
    /* 1F2B070 8006D2D4 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B074 8006D2D8 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B078 8006D2DC F4E60680 */ .word .Llevel_30_8006E6F4
    /* 1F2B07C 8006D2E0 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B080 8006D2E4 B0E90680 */ .word .Llevel_30_8006E9B0
    /* 1F2B084 8006D2E8 24E80680 */ .word .Llevel_30_8006E824
    /* 1F2B088 8006D2EC 24E80680 */ .word .Llevel_30_8006E824
    /* 1F2B08C 8006D2F0 24E80680 */ .word .Llevel_30_8006E824
    /* 1F2B090 8006D2F4 00000000 */ .word 0x00000000
enddlabel jtbl_level_30_8006D268


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_30_8006D898, 0x113C

glabel func_level_30_8006D898
    /* 1F2B634 8006D898 38FFBD27 */  addiu      $sp, $sp, -0xC8
    /* 1F2B638 8006D89C B800B2AF */  sw         $s2, 0xB8($sp)
    /* 1F2B63C 8006D8A0 21908000 */  addu       $s2, $a0, $zero
    /* 1F2B640 8006D8A4 00111200 */  sll        $v0, $s2, 4
    /* 1F2B644 8006D8A8 0780033C */  lui        $v1, %hi(D_800683B0)
    /* 1F2B648 8006D8AC B0836324 */  addiu      $v1, $v1, %lo(D_800683B0)
    /* 1F2B64C 8006D8B0 0780043C */  lui        $a0, %hi(D_8006A040)
    /* 1F2B650 8006D8B4 40A0848C */  lw         $a0, %lo(D_8006A040)($a0)
    /* 1F2B654 8006D8B8 21104300 */  addu       $v0, $v0, $v1
    /* 1F2B658 8006D8BC C400BFAF */  sw         $ra, 0xC4($sp)
    /* 1F2B65C 8006D8C0 C000B4AF */  sw         $s4, 0xC0($sp)
    /* 1F2B660 8006D8C4 BC00B3AF */  sw         $s3, 0xBC($sp)
    /* 1F2B664 8006D8C8 B400B1AF */  sw         $s1, 0xB4($sp)
    /* 1F2B668 8006D8CC B000B0AF */  sw         $s0, 0xB0($sp)
    /* 1F2B66C 8006D8D0 0680013C */  lui        $at, %hi(D_80066F38)
    /* 1F2B670 8006D8D4 386F22AC */  sw         $v0, %lo(D_80066F38)($at)
    /* 1F2B674 8006D8D8 EEFF8424 */  addiu      $a0, $a0, -0x12
    /* 1F2B678 8006D8DC 2300822C */  sltiu      $v0, $a0, 0x23
    /* 1F2B67C 8006D8E0 33044010 */  beqz       $v0, .Llevel_30_8006E9B0
    /* 1F2B680 8006D8E4 80100400 */   sll       $v0, $a0, 2
    /* 1F2B684 8006D8E8 0780013C */  lui        $at, %hi(jtbl_level_30_8006D268)
    /* 1F2B688 8006D8EC 21082200 */  addu       $at, $at, $v0
    /* 1F2B68C 8006D8F0 68D2228C */  lw         $v0, %lo(jtbl_level_30_8006D268)($at)
    /* 1F2B690 8006D8F4 00000000 */  nop
    /* 1F2B694 8006D8F8 08004000 */  jr         $v0
    /* 1F2B698 8006D8FC 00000000 */   nop
  .Llevel_30_8006D900:
    /* 1F2B69C 8006D900 0780113C */  lui        $s1, %hi(D_80069FF8)
    /* 1F2B6A0 8006D904 F89F3126 */  addiu      $s1, $s1, %lo(D_80069FF8)
    /* 1F2B6A4 8006D908 0000238E */  lw         $v1, 0x0($s1)
    /* 1F2B6A8 8006D90C 4401228E */  lw         $v0, 0x144($s1)
    /* 1F2B6AC 8006D910 00000000 */  nop
    /* 1F2B6B0 8006D914 23206200 */  subu       $a0, $v1, $v0
    /* 1F2B6B4 8006D918 00048228 */  slti       $v0, $a0, 0x400
    /* 1F2B6B8 8006D91C 28004010 */  beqz       $v0, .Llevel_30_8006D9C0
    /* 1F2B6BC 8006D920 00000000 */   nop
    /* 1F2B6C0 8006D924 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 1F2B6C4 8006D928 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 1F2B6C8 8006D92C 00000000 */  nop
    /* 1F2B6CC 8006D930 80004224 */  addiu      $v0, $v0, 0x80
    /* 1F2B6D0 8006D934 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1F2B6D4 8006D938 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1F2B6D8 8006D93C C1124228 */  slti       $v0, $v0, 0x12C1
    /* 1F2B6DC 8006D940 04004014 */  bnez       $v0, .Llevel_30_8006D954
    /* 1F2B6E0 8006D944 18008400 */   mult      $a0, $a0
    /* 1F2B6E4 8006D948 C0120224 */  addiu      $v0, $zero, 0x12C0
    /* 1F2B6E8 8006D94C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1F2B6EC 8006D950 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_30_8006D954:
    /* 1F2B6F0 8006D954 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1F2B6F4 8006D958 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 1F2B6F8 8006D95C 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 1F2B6FC 8006D960 0780033C */  lui        $v1, %hi(D_8006A140)
    /* 1F2B700 8006D964 40A1638C */  lw         $v1, %lo(D_8006A140)($v1)
    /* 1F2B704 8006D968 12480000 */  mflo       $t1
    /* 1F2B708 8006D96C C3120900 */  sra        $v0, $t1, 11
    /* 1F2B70C 8006D970 21804300 */  addu       $s0, $v0, $v1
    /* 1F2B710 8006D974 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 1F2B714 8006D978 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 1F2B718 8006D97C 6C6F000C */  jal        func_8001BDB0
    /* 1F2B71C 8006D980 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 1F2B720 8006D984 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1F2B724 8006D988 21288000 */  addu       $a1, $a0, $zero
    /* 1F2B728 8006D98C 806F000C */  jal        func_8001BE00
    /* 1F2B72C 8006D990 F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 1F2B730 8006D994 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1F2B734 8006D998 21280000 */  addu       $a1, $zero, $zero
    /* 1F2B738 8006D99C 886E000C */  jal        func_8001BA20
    /* 1F2B73C 8006D9A0 1800A0AF */   sw        $zero, 0x18($sp)
    /* 1F2B740 8006D9A4 21404000 */  addu       $t0, $v0, $zero
    /* 1F2B744 8006D9A8 01040229 */  slti       $v0, $t0, 0x401
    /* 1F2B748 8006D9AC 91004014 */  bnez       $v0, .Llevel_30_8006DBF4
    /* 1F2B74C 8006D9B0 1000A427 */   addiu     $a0, $sp, 0x10
    /* 1F2B750 8006D9B4 21280001 */  addu       $a1, $t0, $zero
    /* 1F2B754 8006D9B8 FBB60108 */  j          .Llevel_30_8006DBEC
    /* 1F2B758 8006D9BC 00040624 */   addiu     $a2, $zero, 0x400
  .Llevel_30_8006D9C0:
    /* 1F2B75C 8006D9C0 0780053C */  lui        $a1, %hi(D_8006A144)
    /* 1F2B760 8006D9C4 44A1A58C */  lw         $a1, %lo(D_8006A144)($a1)
    /* 1F2B764 8006D9C8 00000000 */  nop
    /* 1F2B768 8006D9CC 23106500 */  subu       $v0, $v1, $a1
    /* 1F2B76C 8006D9D0 00FC4228 */  slti       $v0, $v0, -0x400
    /* 1F2B770 8006D9D4 49004010 */  beqz       $v0, .Llevel_30_8006DAFC
    /* 1F2B774 8006D9D8 2340A300 */   subu      $t0, $a1, $v1
    /* 1F2B778 8006D9DC 0780023C */  lui        $v0, %hi(D_8006A044)
    /* 1F2B77C 8006D9E0 44A0428C */  lw         $v0, %lo(D_8006A044)($v0)
    /* 1F2B780 8006D9E4 00000000 */  nop
    /* 1F2B784 8006D9E8 08004014 */  bnez       $v0, .Llevel_30_8006DA0C
    /* 1F2B788 8006D9EC 01000324 */   addiu     $v1, $zero, 0x1
    /* 1F2B78C 8006D9F0 0780023C */  lui        $v0, %hi(D_8006A140)
    /* 1F2B790 8006D9F4 40A1428C */  lw         $v0, %lo(D_8006A140)($v0)
    /* 1F2B794 8006D9F8 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1F2B798 8006D9FC 44A023AC */  sw         $v1, %lo(D_8006A044)($at)
    /* 1F2B79C 8006DA00 00024224 */  addiu      $v0, $v0, 0x200
    /* 1F2B7A0 8006DA04 0780013C */  lui        $at, %hi(D_8006A140)
    /* 1F2B7A4 8006DA08 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
  .Llevel_30_8006DA0C:
    /* 1F2B7A8 8006DA0C 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 1F2B7AC 8006DA10 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 1F2B7B0 8006DA14 00000000 */  nop
    /* 1F2B7B4 8006DA18 80004224 */  addiu      $v0, $v0, 0x80
    /* 1F2B7B8 8006DA1C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1F2B7BC 8006DA20 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1F2B7C0 8006DA24 C1124228 */  slti       $v0, $v0, 0x12C1
    /* 1F2B7C4 8006DA28 03004014 */  bnez       $v0, .Llevel_30_8006DA38
    /* 1F2B7C8 8006DA2C C0120224 */   addiu     $v0, $zero, 0x12C0
    /* 1F2B7CC 8006DA30 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1F2B7D0 8006DA34 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_30_8006DA38:
    /* 1F2B7D4 8006DA38 0780023C */  lui        $v0, %hi(D_8006A148)
    /* 1F2B7D8 8006DA3C 48A1428C */  lw         $v0, %lo(D_8006A148)($v0)
    /* 1F2B7DC 8006DA40 00FC8824 */  addiu      $t0, $a0, -0x400
    /* 1F2B7E0 8006DA44 18004800 */  mult       $v0, $t0
    /* 1F2B7E4 8006DA48 12180000 */  mflo       $v1
    /* 1F2B7E8 8006DA4C 0780023C */  lui        $v0, %hi(D_8006A14C)
    /* 1F2B7EC 8006DA50 4CA1428C */  lw         $v0, %lo(D_8006A14C)($v0)
    /* 1F2B7F0 8006DA54 00000000 */  nop
    /* 1F2B7F4 8006DA58 1A006200 */  div        $zero, $v1, $v0
    /* 1F2B7F8 8006DA5C 02004014 */  bnez       $v0, .Llevel_30_8006DA68
    /* 1F2B7FC 8006DA60 00000000 */   nop
    /* 1F2B800 8006DA64 0D000700 */  break      7
  .Llevel_30_8006DA68:
    /* 1F2B804 8006DA68 FFFF0124 */  addiu      $at, $zero, -0x1
    /* 1F2B808 8006DA6C 04004114 */  bne        $v0, $at, .Llevel_30_8006DA80
    /* 1F2B80C 8006DA70 0080013C */   lui       $at, (0x80000000 >> 16)
    /* 1F2B810 8006DA74 02006114 */  bne        $v1, $at, .Llevel_30_8006DA80
    /* 1F2B814 8006DA78 00000000 */   nop
    /* 1F2B818 8006DA7C 0D000600 */  break      6
  .Llevel_30_8006DA80:
    /* 1F2B81C 8006DA80 12100000 */  mflo       $v0
    /* 1F2B820 8006DA84 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1F2B824 8006DA88 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 1F2B828 8006DA8C 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 1F2B82C 8006DA90 0780033C */  lui        $v1, %hi(D_8006A140)
    /* 1F2B830 8006DA94 40A1638C */  lw         $v1, %lo(D_8006A140)($v1)
    /* 1F2B834 8006DA98 00000000 */  nop
    /* 1F2B838 8006DA9C 21806200 */  addu       $s0, $v1, $v0
    /* 1F2B83C 8006DAA0 80120800 */  sll        $v0, $t0, 10
    /* 1F2B840 8006DAA4 83120200 */  sra        $v0, $v0, 10
    /* 1F2B844 8006DAA8 21100202 */  addu       $v0, $s0, $v0
    /* 1F2B848 8006DAAC FF0F5030 */  andi       $s0, $v0, 0xFFF
    /* 1F2B84C 8006DAB0 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 1F2B850 8006DAB4 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 1F2B854 8006DAB8 6C6F000C */  jal        func_8001BDB0
    /* 1F2B858 8006DABC 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 1F2B85C 8006DAC0 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1F2B860 8006DAC4 21288000 */  addu       $a1, $a0, $zero
    /* 1F2B864 8006DAC8 806F000C */  jal        func_8001BE00
    /* 1F2B868 8006DACC F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 1F2B86C 8006DAD0 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1F2B870 8006DAD4 21280000 */  addu       $a1, $zero, $zero
    /* 1F2B874 8006DAD8 886E000C */  jal        func_8001BA20
    /* 1F2B878 8006DADC 1800A0AF */   sw        $zero, 0x18($sp)
    /* 1F2B87C 8006DAE0 21404000 */  addu       $t0, $v0, $zero
    /* 1F2B880 8006DAE4 01040229 */  slti       $v0, $t0, 0x401
    /* 1F2B884 8006DAE8 42004014 */  bnez       $v0, .Llevel_30_8006DBF4
    /* 1F2B888 8006DAEC 1000A427 */   addiu     $a0, $sp, 0x10
    /* 1F2B88C 8006DAF0 21280001 */  addu       $a1, $t0, $zero
    /* 1F2B890 8006DAF4 FBB60108 */  j          .Llevel_30_8006DBEC
    /* 1F2B894 8006DAF8 00040624 */   addiu     $a2, $zero, 0x400
  .Llevel_30_8006DAFC:
    /* 1F2B898 8006DAFC 80180800 */  sll        $v1, $t0, 2
    /* 1F2B89C 8006DB00 21186800 */  addu       $v1, $v1, $t0
    /* 1F2B8A0 8006DB04 00110300 */  sll        $v0, $v1, 4
    /* 1F2B8A4 8006DB08 23104300 */  subu       $v0, $v0, $v1
    /* 1F2B8A8 8006DB0C 80110200 */  sll        $v0, $v0, 6
    /* 1F2B8AC 8006DB10 0780063C */  lui        $a2, %hi(D_8006A208)
    /* 1F2B8B0 8006DB14 08A2C68C */  lw         $a2, %lo(D_8006A208)($a2)
    /* 1F2B8B4 8006DB18 83120200 */  sra        $v0, $v0, 10
    /* 1F2B8B8 8006DB1C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1F2B8BC 8006DB20 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 1F2B8C0 8006DB24 4600C790 */  lbu        $a3, 0x46($a2)
    /* 1F2B8C4 8006DB28 0780033C */  lui        $v1, %hi(D_8006A150)
    /* 1F2B8C8 8006DB2C 50A1638C */  lw         $v1, %lo(D_8006A150)($v1)
    /* 1F2B8CC 8006DB30 40100700 */  sll        $v0, $a3, 1
    /* 1F2B8D0 8006DB34 0680013C */  lui        $at, %hi(D_80061C58)
    /* 1F2B8D4 8006DB38 21082200 */  addu       $at, $at, $v0
    /* 1F2B8D8 8006DB3C 581C2284 */  lh         $v0, %lo(D_80061C58)($at)
    /* 1F2B8DC 8006DB40 00046324 */  addiu      $v1, $v1, 0x400
    /* 1F2B8E0 8006DB44 18006200 */  mult       $v1, $v0
    /* 1F2B8E4 8006DB48 12500000 */  mflo       $t2
    /* 1F2B8E8 8006DB4C 00000000 */  nop
    /* 1F2B8EC 8006DB50 00000000 */  nop
    /* 1F2B8F0 8006DB54 18000801 */  mult       $t0, $t0
    /* 1F2B8F4 8006DB58 03130A00 */  sra        $v0, $t2, 12
    /* 1F2B8F8 8006DB5C 1000A2AF */  sw         $v0, 0x10($sp)
    /* 1F2B8FC 8006DB60 4600C290 */  lbu        $v0, 0x46($a2)
    /* 1F2B900 8006DB64 00000000 */  nop
    /* 1F2B904 8006DB68 40100200 */  sll        $v0, $v0, 1
    /* 1F2B908 8006DB6C 12400000 */  mflo       $t0
    /* 1F2B90C 8006DB70 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 1F2B910 8006DB74 21082200 */  addu       $at, $at, $v0
    /* 1F2B914 8006DB78 D81B2284 */  lh         $v0, %lo(D_80061BD8)($at)
    /* 1F2B918 8006DB7C 00000000 */  nop
    /* 1F2B91C 8006DB80 18006200 */  mult       $v1, $v0
    /* 1F2B920 8006DB84 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1F2B924 8006DB88 21288000 */  addu       $a1, $a0, $zero
    /* 1F2B928 8006DB8C 00390700 */  sll        $a3, $a3, 4
    /* 1F2B92C 8006DB90 0C00C624 */  addiu      $a2, $a2, 0xC
    /* 1F2B930 8006DB94 C3120800 */  sra        $v0, $t0, 11
    /* 1F2B934 8006DB98 2380E200 */  subu       $s0, $a3, $v0
    /* 1F2B938 8006DB9C 12180000 */  mflo       $v1
    /* 1F2B93C 8006DBA0 03130300 */  sra        $v0, $v1, 12
    /* 1F2B940 8006DBA4 736F000C */  jal        func_8001BDCC
    /* 1F2B944 8006DBA8 1400A2AF */   sw        $v0, 0x14($sp)
    /* 1F2B948 8006DBAC 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1F2B94C 8006DBB0 21288000 */  addu       $a1, $a0, $zero
    /* 1F2B950 8006DBB4 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 1F2B954 8006DBB8 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 1F2B958 8006DBBC 806F000C */  jal        func_8001BE00
    /* 1F2B95C 8006DBC0 F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 1F2B960 8006DBC4 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1F2B964 8006DBC8 21280000 */  addu       $a1, $zero, $zero
    /* 1F2B968 8006DBCC 886E000C */  jal        func_8001BA20
    /* 1F2B96C 8006DBD0 1800A0AF */   sw        $zero, 0x18($sp)
    /* 1F2B970 8006DBD4 21404000 */  addu       $t0, $v0, $zero
    /* 1F2B974 8006DBD8 01080229 */  slti       $v0, $t0, 0x801
    /* 1F2B978 8006DBDC 05004014 */  bnez       $v0, .Llevel_30_8006DBF4
    /* 1F2B97C 8006DBE0 1000A427 */   addiu     $a0, $sp, 0x10
    /* 1F2B980 8006DBE4 21280001 */  addu       $a1, $t0, $zero
    /* 1F2B984 8006DBE8 00080624 */  addiu      $a2, $zero, 0x800
  .Llevel_30_8006DBEC:
    /* 1F2B988 8006DBEC 316F000C */  jal        func_8001BCC4
    /* 1F2B98C 8006DBF0 00000000 */   nop
  .Llevel_30_8006DBF4:
    /* 1F2B990 8006DBF4 1000A28F */  lw         $v0, 0x10($sp)
    /* 1F2B994 8006DBF8 1400A38F */  lw         $v1, 0x14($sp)
    /* 1F2B998 8006DBFC 0780013C */  lui        $at, %hi(D_8006A084)
    /* 1F2B99C 8006DC00 84A022AC */  sw         $v0, %lo(D_8006A084)($at)
    /* 1F2B9A0 8006DC04 0780013C */  lui        $at, %hi(D_8006A088)
    /* 1F2B9A4 8006DC08 88A023AC */  sw         $v1, %lo(D_8006A088)($at)
    /* 1F2B9A8 8006DC0C 6CBA0108 */  j          .Llevel_30_8006E9B0
    /* 1F2B9AC 8006DC10 00000000 */   nop
  .Llevel_30_8006DC14:
    /* 1F2B9B0 8006DC14 2000A427 */  addiu      $a0, $sp, 0x20
    /* 1F2B9B4 8006DC18 0780053C */  lui        $a1, %hi(D_8006A144)
    /* 1F2B9B8 8006DC1C 44A1A524 */  addiu      $a1, $a1, %lo(D_8006A144)
    /* 1F2B9BC 8006DC20 A5AD000C */  jal        func_8002B694
    /* 1F2B9C0 8006DC24 21300000 */   addu      $a2, $zero, $zero
    /* 1F2B9C4 8006DC28 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 1F2B9C8 8006DC2C 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 1F2B9CC 8006DC30 01000224 */  addiu      $v0, $zero, 0x1
    /* 1F2B9D0 8006DC34 19006214 */  bne        $v1, $v0, .Llevel_30_8006DC9C
    /* 1F2B9D4 8006DC38 00020224 */   addiu     $v0, $zero, 0x200
    /* 1F2B9D8 8006DC3C 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 1F2B9DC 8006DC40 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 1F2B9E0 8006DC44 0780043C */  lui        $a0, %hi(D_8006A13C)
    /* 1F2B9E4 8006DC48 3CA1848C */  lw         $a0, %lo(D_8006A13C)($a0)
    /* 1F2B9E8 8006DC4C 23104300 */  subu       $v0, $v0, $v1
    /* 1F2B9EC 8006DC50 00190400 */  sll        $v1, $a0, 4
    /* 1F2B9F0 8006DC54 23104300 */  subu       $v0, $v0, $v1
    /* 1F2B9F4 8006DC58 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 1F2B9F8 8006DC5C 01086228 */  slti       $v0, $v1, 0x801
    /* 1F2B9FC 8006DC60 03004014 */  bnez       $v0, .Llevel_30_8006DC70
    /* 1F2BA00 8006DC64 2400A3AF */   sw        $v1, 0x24($sp)
    /* 1F2BA04 8006DC68 00F06224 */  addiu      $v0, $v1, -0x1000
    /* 1F2BA08 8006DC6C 2400A2AF */  sw         $v0, 0x24($sp)
  .Llevel_30_8006DC70:
    /* 1F2BA0C 8006DC70 2400A28F */  lw         $v0, 0x24($sp)
    /* 1F2BA10 8006DC74 01008324 */  addiu      $v1, $a0, 0x1
    /* 1F2BA14 8006DC78 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 1F2BA18 8006DC7C 3CA123AC */  sw         $v1, %lo(D_8006A13C)($at)
    /* 1F2BA1C 8006DC80 15006328 */  slti       $v1, $v1, 0x15
    /* 1F2BA20 8006DC84 C0110200 */  sll        $v0, $v0, 7
    /* 1F2BA24 8006DC88 03120200 */  sra        $v0, $v0, 8
    /* 1F2BA28 8006DC8C 03006014 */  bnez       $v1, .Llevel_30_8006DC9C
    /* 1F2BA2C 8006DC90 2400A2AF */   sw        $v0, 0x24($sp)
    /* 1F2BA30 8006DC94 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1F2BA34 8006DC98 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
  .Llevel_30_8006DC9C:
    /* 1F2BA38 8006DC9C 0780053C */  lui        $a1, %hi(D_8006A05C)
    /* 1F2BA3C 8006DCA0 5CA0A524 */  addiu      $a1, $a1, %lo(D_8006A05C)
    /* 1F2BA40 8006DCA4 2000A38F */  lw         $v1, 0x20($sp)
    /* 1F2BA44 8006DCA8 2400A48F */  lw         $a0, 0x24($sp)
    /* 1F2BA48 8006DCAC 80100300 */  sll        $v0, $v1, 2
    /* 1F2BA4C 8006DCB0 21104300 */  addu       $v0, $v0, $v1
    /* 1F2BA50 8006DCB4 80100200 */  sll        $v0, $v0, 2
    /* 1F2BA54 8006DCB8 C3890200 */  sra        $s1, $v0, 7
    /* 1F2BA58 8006DCBC 00110400 */  sll        $v0, $a0, 4
    /* 1F2BA5C 8006DCC0 0000A38C */  lw         $v1, 0x0($a1)
    /* 1F2BA60 8006DCC4 23208200 */  subu       $a0, $a0, $v0
    /* 1F2BA64 8006DCC8 21187100 */  addu       $v1, $v1, $s1
    /* 1F2BA68 8006DCCC FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 1F2BA6C 8006DCD0 0000A3AC */  sw         $v1, 0x0($a1)
    /* 1F2BA70 8006DCD4 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 1F2BA74 8006DCD8 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 1F2BA78 8006DCDC C3210400 */  sra        $a0, $a0, 7
    /* 1F2BA7C 8006DCE0 21104400 */  addu       $v0, $v0, $a0
    /* 1F2BA80 8006DCE4 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 1F2BA84 8006DCE8 01086228 */  slti       $v0, $v1, 0x801
    /* 1F2BA88 8006DCEC 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BA8C 8006DCF0 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 1F2BA90 8006DCF4 03004014 */  bnez       $v0, .Llevel_30_8006DD04
    /* 1F2BA94 8006DCF8 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 1F2BA98 8006DCFC 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BA9C 8006DD00 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_30_8006DD04:
    /* 1F2BAA0 8006DD04 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 1F2BAA4 8006DD08 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 1F2BAA8 8006DD0C 00000000 */  nop
    /* 1F2BAAC 8006DD10 E0FC4228 */  slti       $v0, $v0, -0x320
    /* 1F2BAB0 8006DD14 03004010 */  beqz       $v0, .Llevel_30_8006DD24
    /* 1F2BAB4 8006DD18 E0FC0224 */   addiu     $v0, $zero, -0x320
    /* 1F2BAB8 8006DD1C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BABC 8006DD20 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_30_8006DD24:
    /* 1F2BAC0 8006DD24 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 1F2BAC4 8006DD28 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 1F2BAC8 8006DD2C 00000000 */  nop
    /* 1F2BACC 8006DD30 21034228 */  slti       $v0, $v0, 0x321
    /* 1F2BAD0 8006DD34 03004014 */  bnez       $v0, .Llevel_30_8006DD44
    /* 1F2BAD4 8006DD38 20030224 */   addiu     $v0, $zero, 0x320
    /* 1F2BAD8 8006DD3C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BADC 8006DD40 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_30_8006DD44:
    /* 1F2BAE0 8006DD44 0680023C */  lui        $v0, %hi(D_80066F38)
    /* 1F2BAE4 8006DD48 386F428C */  lw         $v0, %lo(D_80066F38)($v0)
    /* 1F2BAE8 8006DD4C 00000000 */  nop
    /* 1F2BAEC 8006DD50 0000428C */  lw         $v0, 0x0($v0)
    /* 1F2BAF0 8006DD54 00000000 */  nop
    /* 1F2BAF4 8006DD58 40004230 */  andi       $v0, $v0, 0x40
    /* 1F2BAF8 8006DD5C 06004014 */  bnez       $v0, .Llevel_30_8006DD78
    /* 1F2BAFC 8006DD60 000E0224 */   addiu     $v0, $zero, 0xE00
    /* 1F2BB00 8006DD64 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 1F2BB04 8006DD68 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 1F2BB08 8006DD6C 01000224 */  addiu      $v0, $zero, 0x1
    /* 1F2BB0C 8006DD70 05006214 */  bne        $v1, $v0, .Llevel_30_8006DD88
    /* 1F2BB10 8006DD74 000E0224 */   addiu     $v0, $zero, 0xE00
  .Llevel_30_8006DD78:
    /* 1F2BB14 8006DD78 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 1F2BB18 8006DD7C A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 1F2BB1C 8006DD80 64B70108 */  j          .Llevel_30_8006DD90
    /* 1F2BB20 8006DD84 00000000 */   nop
  .Llevel_30_8006DD88:
    /* 1F2BB24 8006DD88 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 1F2BB28 8006DD8C A4A020AC */  sw         $zero, %lo(D_8006A0A4)($at)
  .Llevel_30_8006DD90:
    /* 1F2BB2C 8006DD90 0780103C */  lui        $s0, %hi(D_8006A044)
    /* 1F2BB30 8006DD94 44A01026 */  addiu      $s0, $s0, %lo(D_8006A044)
    /* 1F2BB34 8006DD98 0000038E */  lw         $v1, 0x0($s0)
    /* 1F2BB38 8006DD9C 02000224 */  addiu      $v0, $zero, 0x2
    /* 1F2BB3C 8006DDA0 0B006214 */  bne        $v1, $v0, .Llevel_30_8006DDD0
    /* 1F2BB40 8006DDA4 C0000424 */   addiu     $a0, $zero, 0xC0
    /* 1F2BB44 8006DDA8 5CAF000C */  jal        func_8002BD70
    /* 1F2BB48 8006DDAC C0000524 */   addiu     $a1, $zero, 0xC0
    /* 1F2BB4C 8006DDB0 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 1F2BB50 8006DDB4 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 1F2BB54 8006DDB8 00000000 */  nop
    /* 1F2BB58 8006DDBC 010E4228 */  slti       $v0, $v0, 0xE01
    /* 1F2BB5C 8006DDC0 05004010 */  beqz       $v0, .Llevel_30_8006DDD8
    /* 1F2BB60 8006DDC4 00000000 */   nop
    /* 1F2BB64 8006DDC8 76B70108 */  j          .Llevel_30_8006DDD8
    /* 1F2BB68 8006DDCC 000000AE */   sw        $zero, 0x0($s0)
  .Llevel_30_8006DDD0:
    /* 1F2BB6C 8006DDD0 5CAF000C */  jal        func_8002BD70
    /* 1F2BB70 8006DDD4 30000524 */   addiu     $a1, $zero, 0x30
  .Llevel_30_8006DDD8:
    /* 1F2BB74 8006DDD8 0780103C */  lui        $s0, %hi(D_8006A058)
    /* 1F2BB78 8006DDDC 58A01026 */  addiu      $s0, $s0, %lo(D_8006A058)
    /* 1F2BB7C 8006DDE0 0000048E */  lw         $a0, 0x0($s0)
    /* 1F2BB80 8006DDE4 996D000C */  jal        func_8001B664
    /* 1F2BB84 8006DDE8 00000000 */   nop
    /* 1F2BB88 8006DDEC 40110200 */  sll        $v0, $v0, 5
    /* 1F2BB8C 8006DDF0 23100200 */  negu       $v0, $v0
    /* 1F2BB90 8006DDF4 18002202 */  mult       $s1, $v0
    /* 1F2BB94 8006DDF8 0780033C */  lui        $v1, %hi(D_8006A144)
    /* 1F2BB98 8006DDFC 44A1638C */  lw         $v1, %lo(D_8006A144)($v1)
    /* 1F2BB9C 8006DE00 0780053C */  lui        $a1, %hi(D_8006A054)
    /* 1F2BBA0 8006DE04 54A0A58C */  lw         $a1, %lo(D_8006A054)($a1)
    /* 1F2BBA4 8006DE08 00110300 */  sll        $v0, $v1, 4
    /* 1F2BBA8 8006DE0C 83110200 */  sra        $v0, $v0, 6
    /* 1F2BBAC 8006DE10 12480000 */  mflo       $t1
    /* 1F2BBB0 8006DE14 03230900 */  sra        $a0, $t1, 12
    /* 1F2BBB4 8006DE18 23208200 */  subu       $a0, $a0, $v0
    /* 1F2BBB8 8006DE1C 80110500 */  sll        $v0, $a1, 6
    /* 1F2BBBC 8006DE20 83110200 */  sra        $v0, $v0, 6
    /* 1F2BBC0 8006DE24 23208200 */  subu       $a0, $a0, $v0
    /* 1F2BBC4 8006DE28 21186400 */  addu       $v1, $v1, $a0
    /* 1F2BBC8 8006DE2C 0780013C */  lui        $at, %hi(D_8006A144)
    /* 1F2BBCC 8006DE30 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 1F2BBD0 8006DE34 83190300 */  sra        $v1, $v1, 6
    /* 1F2BBD4 8006DE38 2128A300 */  addu       $a1, $a1, $v1
    /* 1F2BBD8 8006DE3C FF0FA530 */  andi       $a1, $a1, 0xFFF
    /* 1F2BBDC 8006DE40 0108A228 */  slti       $v0, $a1, 0x801
    /* 1F2BBE0 8006DE44 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2BBE4 8006DE48 54A025AC */  sw         $a1, %lo(D_8006A054)($at)
    /* 1F2BBE8 8006DE4C 03004014 */  bnez       $v0, .Llevel_30_8006DE5C
    /* 1F2BBEC 8006DE50 00F0A224 */   addiu     $v0, $a1, -0x1000
    /* 1F2BBF0 8006DE54 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2BBF4 8006DE58 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_30_8006DE5C:
    /* 1F2BBF8 8006DE5C 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 1F2BBFC 8006DE60 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 1F2BC00 8006DE64 00000000 */  nop
    /* 1F2BC04 8006DE68 00FD4228 */  slti       $v0, $v0, -0x300
    /* 1F2BC08 8006DE6C 03004010 */  beqz       $v0, .Llevel_30_8006DE7C
    /* 1F2BC0C 8006DE70 00FD0224 */   addiu     $v0, $zero, -0x300
    /* 1F2BC10 8006DE74 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2BC14 8006DE78 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_30_8006DE7C:
    /* 1F2BC18 8006DE7C 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 1F2BC1C 8006DE80 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 1F2BC20 8006DE84 00000000 */  nop
    /* 1F2BC24 8006DE88 01034228 */  slti       $v0, $v0, 0x301
    /* 1F2BC28 8006DE8C 03004014 */  bnez       $v0, .Llevel_30_8006DE9C
    /* 1F2BC2C 8006DE90 00030224 */   addiu     $v0, $zero, 0x300
    /* 1F2BC30 8006DE94 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2BC34 8006DE98 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_30_8006DE9C:
    /* 1F2BC38 8006DE9C 6FAF000C */  jal        func_8002BDBC
    /* 1F2BC3C 8006DEA0 00000000 */   nop
    /* 1F2BC40 8006DEA4 2C000426 */  addiu      $a0, $s0, 0x2C
    /* 1F2BC44 8006DEA8 6C6F000C */  jal        func_8001BDB0
    /* 1F2BC48 8006DEAC 20000526 */   addiu     $a1, $s0, 0x20
    /* 1F2BC4C 8006DEB0 4B67010C */  jal        func_80059D2C
    /* 1F2BC50 8006DEB4 00000000 */   nop
    /* 1F2BC54 8006DEB8 1F004230 */  andi       $v0, $v0, 0x1F
    /* 1F2BC58 8006DEBC 8B004014 */  bnez       $v0, .Llevel_30_8006E0EC
    /* 1F2BC5C 8006DEC0 00000000 */   nop
    /* 1F2BC60 8006DEC4 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 1F2BC64 8006DEC8 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 1F2BC68 8006DECC 00000000 */  nop
    /* 1F2BC6C 8006DED0 86006010 */  beqz       $v1, .Llevel_30_8006E0EC
    /* 1F2BC70 8006DED4 01000424 */   addiu     $a0, $zero, 0x1
    /* 1F2BC74 8006DED8 2C000524 */  addiu      $a1, $zero, 0x2C
    /* 1F2BC78 8006DEDC 2800A627 */  addiu      $a2, $sp, 0x28
    /* 1F2BC7C 8006DEE0 21380000 */  addu       $a3, $zero, $zero
    /* 1F2BC80 8006DEE4 20020224 */  addiu      $v0, $zero, 0x220
    /* 1F2BC84 8006DEE8 2800A2AF */  sw         $v0, 0x28($sp)
    /* 1F2BC88 8006DEEC 40000224 */  addiu      $v0, $zero, 0x40
    /* 1F2BC8C 8006DEF0 2C00A0AF */  sw         $zero, 0x2C($sp)
    /* 1F2BC90 8006DEF4 39B80108 */  j          .Llevel_30_8006E0E4
    /* 1F2BC94 8006DEF8 3000A2AF */   sw        $v0, 0x30($sp)
  .Llevel_30_8006DEFC:
    /* 1F2BC98 8006DEFC 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 1F2BC9C 8006DF00 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 1F2BCA0 8006DF04 07000224 */  addiu      $v0, $zero, 0x7
    /* 1F2BCA4 8006DF08 5E006210 */  beq        $v1, $v0, .Llevel_30_8006E084
    /* 1F2BCA8 8006DF0C 2800A427 */   addiu     $a0, $sp, 0x28
    /* 1F2BCAC 8006DF10 0780113C */  lui        $s1, %hi(D_8006A144)
    /* 1F2BCB0 8006DF14 44A13126 */  addiu      $s1, $s1, %lo(D_8006A144)
    /* 1F2BCB4 8006DF18 21282002 */  addu       $a1, $s1, $zero
    /* 1F2BCB8 8006DF1C A5AD000C */  jal        func_8002B694
    /* 1F2BCBC 8006DF20 21300000 */   addu      $a2, $zero, $zero
    /* 1F2BCC0 8006DF24 2800A38F */  lw         $v1, 0x28($sp)
    /* 1F2BCC4 8006DF28 2C00A48F */  lw         $a0, 0x2C($sp)
    /* 1F2BCC8 8006DF2C 80100300 */  sll        $v0, $v1, 2
    /* 1F2BCCC 8006DF30 21104300 */  addu       $v0, $v0, $v1
    /* 1F2BCD0 8006DF34 80100200 */  sll        $v0, $v0, 2
    /* 1F2BCD4 8006DF38 C3810200 */  sra        $s0, $v0, 7
    /* 1F2BCD8 8006DF3C 00110400 */  sll        $v0, $a0, 4
    /* 1F2BCDC 8006DF40 23208200 */  subu       $a0, $a0, $v0
    /* 1F2BCE0 8006DF44 C3210400 */  sra        $a0, $a0, 7
    /* 1F2BCE4 8006DF48 0780033C */  lui        $v1, %hi(D_8006A05C)
    /* 1F2BCE8 8006DF4C 5CA0638C */  lw         $v1, %lo(D_8006A05C)($v1)
    /* 1F2BCEC 8006DF50 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 1F2BCF0 8006DF54 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 1F2BCF4 8006DF58 21187000 */  addu       $v1, $v1, $s0
    /* 1F2BCF8 8006DF5C FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 1F2BCFC 8006DF60 21104400 */  addu       $v0, $v0, $a0
    /* 1F2BD00 8006DF64 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 1F2BD04 8006DF68 5CA023AC */  sw         $v1, %lo(D_8006A05C)($at)
    /* 1F2BD08 8006DF6C FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 1F2BD0C 8006DF70 01086228 */  slti       $v0, $v1, 0x801
    /* 1F2BD10 8006DF74 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BD14 8006DF78 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 1F2BD18 8006DF7C 03004014 */  bnez       $v0, .Llevel_30_8006DF8C
    /* 1F2BD1C 8006DF80 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 1F2BD20 8006DF84 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BD24 8006DF88 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_30_8006DF8C:
    /* 1F2BD28 8006DF8C 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 1F2BD2C 8006DF90 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 1F2BD30 8006DF94 00000000 */  nop
    /* 1F2BD34 8006DF98 E0FC4228 */  slti       $v0, $v0, -0x320
    /* 1F2BD38 8006DF9C 03004010 */  beqz       $v0, .Llevel_30_8006DFAC
    /* 1F2BD3C 8006DFA0 E0FC0224 */   addiu     $v0, $zero, -0x320
    /* 1F2BD40 8006DFA4 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BD44 8006DFA8 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_30_8006DFAC:
    /* 1F2BD48 8006DFAC 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 1F2BD4C 8006DFB0 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 1F2BD50 8006DFB4 00000000 */  nop
    /* 1F2BD54 8006DFB8 21034228 */  slti       $v0, $v0, 0x321
    /* 1F2BD58 8006DFBC 03004014 */  bnez       $v0, .Llevel_30_8006DFCC
    /* 1F2BD5C 8006DFC0 20030224 */   addiu     $v0, $zero, 0x320
    /* 1F2BD60 8006DFC4 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BD64 8006DFC8 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_30_8006DFCC:
    /* 1F2BD68 8006DFCC 0780043C */  lui        $a0, %hi(D_8006A058)
    /* 1F2BD6C 8006DFD0 58A0848C */  lw         $a0, %lo(D_8006A058)($a0)
    /* 1F2BD70 8006DFD4 996D000C */  jal        func_8001B664
    /* 1F2BD74 8006DFD8 00000000 */   nop
    /* 1F2BD78 8006DFDC 40110200 */  sll        $v0, $v0, 5
    /* 1F2BD7C 8006DFE0 23100200 */  negu       $v0, $v0
    /* 1F2BD80 8006DFE4 18000202 */  mult       $s0, $v0
    /* 1F2BD84 8006DFE8 0000238E */  lw         $v1, 0x0($s1)
    /* 1F2BD88 8006DFEC 0780053C */  lui        $a1, %hi(D_8006A054)
    /* 1F2BD8C 8006DFF0 54A0A58C */  lw         $a1, %lo(D_8006A054)($a1)
    /* 1F2BD90 8006DFF4 00110300 */  sll        $v0, $v1, 4
    /* 1F2BD94 8006DFF8 83110200 */  sra        $v0, $v0, 6
    /* 1F2BD98 8006DFFC 12480000 */  mflo       $t1
    /* 1F2BD9C 8006E000 03230900 */  sra        $a0, $t1, 12
    /* 1F2BDA0 8006E004 23208200 */  subu       $a0, $a0, $v0
    /* 1F2BDA4 8006E008 80110500 */  sll        $v0, $a1, 6
    /* 1F2BDA8 8006E00C 83110200 */  sra        $v0, $v0, 6
    /* 1F2BDAC 8006E010 23208200 */  subu       $a0, $a0, $v0
    /* 1F2BDB0 8006E014 21186400 */  addu       $v1, $v1, $a0
    /* 1F2BDB4 8006E018 000023AE */  sw         $v1, 0x0($s1)
    /* 1F2BDB8 8006E01C 83190300 */  sra        $v1, $v1, 6
    /* 1F2BDBC 8006E020 2128A300 */  addu       $a1, $a1, $v1
    /* 1F2BDC0 8006E024 FF0FA530 */  andi       $a1, $a1, 0xFFF
    /* 1F2BDC4 8006E028 0108A228 */  slti       $v0, $a1, 0x801
    /* 1F2BDC8 8006E02C 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2BDCC 8006E030 54A025AC */  sw         $a1, %lo(D_8006A054)($at)
    /* 1F2BDD0 8006E034 03004014 */  bnez       $v0, .Llevel_30_8006E044
    /* 1F2BDD4 8006E038 00F0A224 */   addiu     $v0, $a1, -0x1000
    /* 1F2BDD8 8006E03C 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2BDDC 8006E040 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_30_8006E044:
    /* 1F2BDE0 8006E044 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 1F2BDE4 8006E048 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 1F2BDE8 8006E04C 00000000 */  nop
    /* 1F2BDEC 8006E050 00FD4228 */  slti       $v0, $v0, -0x300
    /* 1F2BDF0 8006E054 03004010 */  beqz       $v0, .Llevel_30_8006E064
    /* 1F2BDF4 8006E058 00FD0224 */   addiu     $v0, $zero, -0x300
    /* 1F2BDF8 8006E05C 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2BDFC 8006E060 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_30_8006E064:
    /* 1F2BE00 8006E064 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 1F2BE04 8006E068 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 1F2BE08 8006E06C 00000000 */  nop
    /* 1F2BE0C 8006E070 01034228 */  slti       $v0, $v0, 0x301
    /* 1F2BE10 8006E074 03004014 */  bnez       $v0, .Llevel_30_8006E084
    /* 1F2BE14 8006E078 00030224 */   addiu     $v0, $zero, 0x300
    /* 1F2BE18 8006E07C 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2BE1C 8006E080 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_30_8006E084:
    /* 1F2BE20 8006E084 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 1F2BE24 8006E088 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 1F2BE28 8006E08C 686F000C */  jal        func_8001BDA0
    /* 1F2BE2C 8006E090 21200002 */   addu      $a0, $s0, $zero
    /* 1F2BE30 8006E094 686F000C */  jal        func_8001BDA0
    /* 1F2BE34 8006E098 0C000426 */   addiu     $a0, $s0, 0xC
    /* 1F2BE38 8006E09C 4B67010C */  jal        func_80059D2C
    /* 1F2BE3C 8006E0A0 00000000 */   nop
    /* 1F2BE40 8006E0A4 1F004230 */  andi       $v0, $v0, 0x1F
    /* 1F2BE44 8006E0A8 10004014 */  bnez       $v0, .Llevel_30_8006E0EC
    /* 1F2BE48 8006E0AC 00000000 */   nop
    /* 1F2BE4C 8006E0B0 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 1F2BE50 8006E0B4 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 1F2BE54 8006E0B8 00000000 */  nop
    /* 1F2BE58 8006E0BC 0B006010 */  beqz       $v1, .Llevel_30_8006E0EC
    /* 1F2BE5C 8006E0C0 01000424 */   addiu     $a0, $zero, 0x1
    /* 1F2BE60 8006E0C4 2C000524 */  addiu      $a1, $zero, 0x2C
    /* 1F2BE64 8006E0C8 3800A627 */  addiu      $a2, $sp, 0x38
    /* 1F2BE68 8006E0CC 21380000 */  addu       $a3, $zero, $zero
    /* 1F2BE6C 8006E0D0 20020224 */  addiu      $v0, $zero, 0x220
    /* 1F2BE70 8006E0D4 3800A2AF */  sw         $v0, 0x38($sp)
    /* 1F2BE74 8006E0D8 40000224 */  addiu      $v0, $zero, 0x40
    /* 1F2BE78 8006E0DC 3C00A0AF */  sw         $zero, 0x3C($sp)
    /* 1F2BE7C 8006E0E0 4000A2AF */  sw         $v0, 0x40($sp)
  .Llevel_30_8006E0E4:
    /* 1F2BE80 8006E0E4 09F86000 */  jalr       $v1
    /* 1F2BE84 8006E0E8 00000000 */   nop
  .Llevel_30_8006E0EC:
    /* 1F2BE88 8006E0EC 0780033C */  lui        $v1, %hi(D_8006A150)
    /* 1F2BE8C 8006E0F0 50A16324 */  addiu      $v1, $v1, %lo(D_8006A150)
    /* 1F2BE90 8006E0F4 0000628C */  lw         $v0, 0x0($v1)
    /* 1F2BE94 8006E0F8 00000000 */  nop
    /* 1F2BE98 8006E0FC 01004224 */  addiu      $v0, $v0, 0x1
    /* 1F2BE9C 8006E100 6CBA0108 */  j          .Llevel_30_8006E9B0
    /* 1F2BEA0 8006E104 000062AC */   sw        $v0, 0x0($v1)
  .Llevel_30_8006E108:
    /* 1F2BEA4 8006E108 3800A427 */  addiu      $a0, $sp, 0x38
    /* 1F2BEA8 8006E10C 0780053C */  lui        $a1, %hi(D_8006A144)
    /* 1F2BEAC 8006E110 44A1A524 */  addiu      $a1, $a1, %lo(D_8006A144)
    /* 1F2BEB0 8006E114 A5AD000C */  jal        func_8002B694
    /* 1F2BEB4 8006E118 21300000 */   addu      $a2, $zero, $zero
    /* 1F2BEB8 8006E11C 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 1F2BEBC 8006E120 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 1F2BEC0 8006E124 01000224 */  addiu      $v0, $zero, 0x1
    /* 1F2BEC4 8006E128 1B006214 */  bne        $v1, $v0, .Llevel_30_8006E198
    /* 1F2BEC8 8006E12C 00020224 */   addiu     $v0, $zero, 0x200
    /* 1F2BECC 8006E130 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 1F2BED0 8006E134 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 1F2BED4 8006E138 0780053C */  lui        $a1, %hi(D_8006A13C)
    /* 1F2BED8 8006E13C 3CA1A58C */  lw         $a1, %lo(D_8006A13C)($a1)
    /* 1F2BEDC 8006E140 23104300 */  subu       $v0, $v0, $v1
    /* 1F2BEE0 8006E144 00190500 */  sll        $v1, $a1, 4
    /* 1F2BEE4 8006E148 23104300 */  subu       $v0, $v0, $v1
    /* 1F2BEE8 8006E14C FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 1F2BEEC 8006E150 01086228 */  slti       $v0, $v1, 0x801
    /* 1F2BEF0 8006E154 03004014 */  bnez       $v0, .Llevel_30_8006E164
    /* 1F2BEF4 8006E158 3C00A3AF */   sw        $v1, 0x3C($sp)
    /* 1F2BEF8 8006E15C 00F06224 */  addiu      $v0, $v1, -0x1000
    /* 1F2BEFC 8006E160 3C00A2AF */  sw         $v0, 0x3C($sp)
  .Llevel_30_8006E164:
    /* 1F2BF00 8006E164 3C00A48F */  lw         $a0, 0x3C($sp)
    /* 1F2BF04 8006E168 0100A324 */  addiu      $v1, $a1, 0x1
    /* 1F2BF08 8006E16C 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 1F2BF0C 8006E170 3CA123AC */  sw         $v1, %lo(D_8006A13C)($at)
    /* 1F2BF10 8006E174 0D006328 */  slti       $v1, $v1, 0xD
    /* 1F2BF14 8006E178 40100400 */  sll        $v0, $a0, 1
    /* 1F2BF18 8006E17C 21104400 */  addu       $v0, $v0, $a0
    /* 1F2BF1C 8006E180 40110200 */  sll        $v0, $v0, 5
    /* 1F2BF20 8006E184 03120200 */  sra        $v0, $v0, 8
    /* 1F2BF24 8006E188 03006014 */  bnez       $v1, .Llevel_30_8006E198
    /* 1F2BF28 8006E18C 3C00A2AF */   sw        $v0, 0x3C($sp)
    /* 1F2BF2C 8006E190 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1F2BF30 8006E194 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
  .Llevel_30_8006E198:
    /* 1F2BF34 8006E198 0780113C */  lui        $s1, %hi(D_8006A05C)
    /* 1F2BF38 8006E19C 5CA03126 */  addiu      $s1, $s1, %lo(D_8006A05C)
    /* 1F2BF3C 8006E1A0 3800A38F */  lw         $v1, 0x38($sp)
    /* 1F2BF40 8006E1A4 3C00A48F */  lw         $a0, 0x3C($sp)
    /* 1F2BF44 8006E1A8 80100300 */  sll        $v0, $v1, 2
    /* 1F2BF48 8006E1AC 21104300 */  addu       $v0, $v0, $v1
    /* 1F2BF4C 8006E1B0 80100200 */  sll        $v0, $v0, 2
    /* 1F2BF50 8006E1B4 C3810200 */  sra        $s0, $v0, 7
    /* 1F2BF54 8006E1B8 00110400 */  sll        $v0, $a0, 4
    /* 1F2BF58 8006E1BC 0000238E */  lw         $v1, 0x0($s1)
    /* 1F2BF5C 8006E1C0 23208200 */  subu       $a0, $a0, $v0
    /* 1F2BF60 8006E1C4 21187000 */  addu       $v1, $v1, $s0
    /* 1F2BF64 8006E1C8 FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 1F2BF68 8006E1CC 000023AE */  sw         $v1, 0x0($s1)
    /* 1F2BF6C 8006E1D0 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 1F2BF70 8006E1D4 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 1F2BF74 8006E1D8 C3210400 */  sra        $a0, $a0, 7
    /* 1F2BF78 8006E1DC 21104400 */  addu       $v0, $v0, $a0
    /* 1F2BF7C 8006E1E0 FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 1F2BF80 8006E1E4 01086228 */  slti       $v0, $v1, 0x801
    /* 1F2BF84 8006E1E8 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BF88 8006E1EC 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 1F2BF8C 8006E1F0 03004014 */  bnez       $v0, .Llevel_30_8006E200
    /* 1F2BF90 8006E1F4 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 1F2BF94 8006E1F8 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BF98 8006E1FC 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_30_8006E200:
    /* 1F2BF9C 8006E200 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 1F2BFA0 8006E204 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 1F2BFA4 8006E208 00000000 */  nop
    /* 1F2BFA8 8006E20C E0FC4228 */  slti       $v0, $v0, -0x320
    /* 1F2BFAC 8006E210 03004010 */  beqz       $v0, .Llevel_30_8006E220
    /* 1F2BFB0 8006E214 E0FC0224 */   addiu     $v0, $zero, -0x320
    /* 1F2BFB4 8006E218 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BFB8 8006E21C 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_30_8006E220:
    /* 1F2BFBC 8006E220 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 1F2BFC0 8006E224 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 1F2BFC4 8006E228 00000000 */  nop
    /* 1F2BFC8 8006E22C 21034228 */  slti       $v0, $v0, 0x321
    /* 1F2BFCC 8006E230 04004014 */  bnez       $v0, .Llevel_30_8006E244
    /* 1F2BFD0 8006E234 40020424 */   addiu     $a0, $zero, 0x240
    /* 1F2BFD4 8006E238 20030224 */  addiu      $v0, $zero, 0x320
    /* 1F2BFD8 8006E23C 0780013C */  lui        $at, %hi(D_8006A058)
    /* 1F2BFDC 8006E240 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_30_8006E244:
    /* 1F2BFE0 8006E244 001C0224 */  addiu      $v0, $zero, 0x1C00
    /* 1F2BFE4 8006E248 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 1F2BFE8 8006E24C A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 1F2BFEC 8006E250 5CAF000C */  jal        func_8002BD70
    /* 1F2BFF0 8006E254 30000524 */   addiu     $a1, $zero, 0x30
    /* 1F2BFF4 8006E258 0780043C */  lui        $a0, %hi(D_8006A058)
    /* 1F2BFF8 8006E25C 58A0848C */  lw         $a0, %lo(D_8006A058)($a0)
    /* 1F2BFFC 8006E260 996D000C */  jal        func_8001B664
    /* 1F2C000 8006E264 00000000 */   nop
    /* 1F2C004 8006E268 40110200 */  sll        $v0, $v0, 5
    /* 1F2C008 8006E26C 23100200 */  negu       $v0, $v0
    /* 1F2C00C 8006E270 18000202 */  mult       $s0, $v0
    /* 1F2C010 8006E274 0780033C */  lui        $v1, %hi(D_8006A144)
    /* 1F2C014 8006E278 44A1638C */  lw         $v1, %lo(D_8006A144)($v1)
    /* 1F2C018 8006E27C 0780053C */  lui        $a1, %hi(D_8006A054)
    /* 1F2C01C 8006E280 54A0A58C */  lw         $a1, %lo(D_8006A054)($a1)
    /* 1F2C020 8006E284 00110300 */  sll        $v0, $v1, 4
    /* 1F2C024 8006E288 83110200 */  sra        $v0, $v0, 6
    /* 1F2C028 8006E28C 12480000 */  mflo       $t1
    /* 1F2C02C 8006E290 03230900 */  sra        $a0, $t1, 12
    /* 1F2C030 8006E294 23208200 */  subu       $a0, $a0, $v0
    /* 1F2C034 8006E298 80110500 */  sll        $v0, $a1, 6
    /* 1F2C038 8006E29C 83110200 */  sra        $v0, $v0, 6
    /* 1F2C03C 8006E2A0 23208200 */  subu       $a0, $a0, $v0
    /* 1F2C040 8006E2A4 21186400 */  addu       $v1, $v1, $a0
    /* 1F2C044 8006E2A8 0780013C */  lui        $at, %hi(D_8006A144)
    /* 1F2C048 8006E2AC 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 1F2C04C 8006E2B0 83190300 */  sra        $v1, $v1, 6
    /* 1F2C050 8006E2B4 2128A300 */  addu       $a1, $a1, $v1
    /* 1F2C054 8006E2B8 FF0FA530 */  andi       $a1, $a1, 0xFFF
    /* 1F2C058 8006E2BC 0108A228 */  slti       $v0, $a1, 0x801
    /* 1F2C05C 8006E2C0 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2C060 8006E2C4 54A025AC */  sw         $a1, %lo(D_8006A054)($at)
    /* 1F2C064 8006E2C8 03004014 */  bnez       $v0, .Llevel_30_8006E2D8
    /* 1F2C068 8006E2CC 00F0A224 */   addiu     $v0, $a1, -0x1000
    /* 1F2C06C 8006E2D0 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2C070 8006E2D4 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_30_8006E2D8:
    /* 1F2C074 8006E2D8 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 1F2C078 8006E2DC 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 1F2C07C 8006E2E0 00000000 */  nop
    /* 1F2C080 8006E2E4 00FD4228 */  slti       $v0, $v0, -0x300
    /* 1F2C084 8006E2E8 03004010 */  beqz       $v0, .Llevel_30_8006E2F8
    /* 1F2C088 8006E2EC 00FD0224 */   addiu     $v0, $zero, -0x300
    /* 1F2C08C 8006E2F0 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2C090 8006E2F4 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_30_8006E2F8:
    /* 1F2C094 8006E2F8 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 1F2C098 8006E2FC 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 1F2C09C 8006E300 00000000 */  nop
    /* 1F2C0A0 8006E304 01034228 */  slti       $v0, $v0, 0x301
    /* 1F2C0A4 8006E308 03004014 */  bnez       $v0, .Llevel_30_8006E318
    /* 1F2C0A8 8006E30C 00030224 */   addiu     $v0, $zero, 0x300
    /* 1F2C0AC 8006E310 0780013C */  lui        $at, %hi(D_8006A054)
    /* 1F2C0B0 8006E314 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_30_8006E318:
    /* 1F2C0B4 8006E318 6FAF000C */  jal        func_8002BDBC
    /* 1F2C0B8 8006E31C 00000000 */   nop
    /* 1F2C0BC 8006E320 28002426 */  addiu      $a0, $s1, 0x28
    /* 1F2C0C0 8006E324 6C6F000C */  jal        func_8001BDB0
    /* 1F2C0C4 8006E328 1C002526 */   addiu     $a1, $s1, 0x1C
    /* 1F2C0C8 8006E32C 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 1F2C0CC 8006E330 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 1F2C0D0 8006E334 00000000 */  nop
    /* 1F2C0D4 8006E338 9D014010 */  beqz       $v0, .Llevel_30_8006E9B0
    /* 1F2C0D8 8006E33C 00000000 */   nop
    /* 1F2C0DC 8006E340 0780023C */  lui        $v0, %hi(D_8006A0AC)
    /* 1F2C0E0 8006E344 ACA0428C */  lw         $v0, %lo(D_8006A0AC)($v0)
    /* 1F2C0E4 8006E348 00000000 */  nop
    /* 1F2C0E8 8006E34C D1074228 */  slti       $v0, $v0, 0x7D1
    /* 1F2C0EC 8006E350 97014014 */  bnez       $v0, .Llevel_30_8006E9B0
    /* 1F2C0F0 8006E354 70FE0224 */   addiu     $v0, $zero, -0x190
    /* 1F2C0F4 8006E358 4B67010C */  jal        func_80059D2C
    /* 1F2C0F8 8006E35C 4800A2AF */   sw        $v0, 0x48($sp)
    /* 1F2C0FC 8006E360 01000424 */  addiu      $a0, $zero, 0x1
    /* 1F2C100 8006E364 2C000524 */  addiu      $a1, $zero, 0x2C
    /* 1F2C104 8006E368 4800A627 */  addiu      $a2, $sp, 0x48
    /* 1F2C108 8006E36C 21380000 */  addu       $a3, $zero, $zero
    /* 1F2C10C 8006E370 7F004230 */  andi       $v0, $v0, 0x7F
    /* 1F2C110 8006E374 40000324 */  addiu      $v1, $zero, 0x40
    /* 1F2C114 8006E378 23186200 */  subu       $v1, $v1, $v0
    /* 1F2C118 8006E37C 4C00A3AF */  sw         $v1, 0x4C($sp)
    /* 1F2C11C 8006E380 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 1F2C120 8006E384 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 1F2C124 8006E388 D4FE0224 */  addiu      $v0, $zero, -0x12C
    /* 1F2C128 8006E38C 09F86000 */  jalr       $v1
    /* 1F2C12C 8006E390 5000A2AF */   sw        $v0, 0x50($sp)
    /* 1F2C130 8006E394 6CBA0108 */  j          .Llevel_30_8006E9B0
    /* 1F2C134 8006E398 00000000 */   nop
  .Llevel_30_8006E39C:
    /* 1F2C138 8006E39C 0780103C */  lui        $s0, %hi(D_8006A044)
    /* 1F2C13C 8006E3A0 44A01026 */  addiu      $s0, $s0, %lo(D_8006A044)
    /* 1F2C140 8006E3A4 0000038E */  lw         $v1, 0x0($s0)
    /* 1F2C144 8006E3A8 01000224 */  addiu      $v0, $zero, 0x1
    /* 1F2C148 8006E3AC 13016210 */  beq        $v1, $v0, .Llevel_30_8006E7FC
    /* 1F2C14C 8006E3B0 07000224 */   addiu     $v0, $zero, 0x7
    /* 1F2C150 8006E3B4 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 1F2C154 8006E3B8 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 1F2C158 8006E3BC 00000000 */  nop
    /* 1F2C15C 8006E3C0 05006214 */  bne        $v1, $v0, .Llevel_30_8006E3D8
    /* 1F2C160 8006E3C4 00000000 */   nop
    /* 1F2C164 8006E3C8 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 1F2C168 8006E3CC A8A020AC */  sw         $zero, %lo(D_8006A0A8)($at)
    /* 1F2C16C 8006E3D0 0FB90108 */  j          .Llevel_30_8006E43C
    /* 1F2C170 8006E3D4 00000000 */   nop
  .Llevel_30_8006E3D8:
    /* 1F2C174 8006E3D8 DBAC000C */  jal        func_8002B36C
    /* 1F2C178 8006E3DC 80090424 */   addiu     $a0, $zero, 0x980
    /* 1F2C17C 8006E3E0 5A000424 */  addiu      $a0, $zero, 0x5A
    /* 1F2C180 8006E3E4 C9AE000C */  jal        func_8002BB24
    /* 1F2C184 8006E3E8 10000524 */   addiu     $a1, $zero, 0x10
    /* 1F2C188 8006E3EC 02004104 */  bgez       $v0, .Llevel_30_8006E3F8
    /* 1F2C18C 8006E3F0 00000000 */   nop
    /* 1F2C190 8006E3F4 23100200 */  negu       $v0, $v0
  .Llevel_30_8006E3F8:
    /* 1F2C194 8006E3F8 01024228 */  slti       $v0, $v0, 0x201
    /* 1F2C198 8006E3FC 03004014 */  bnez       $v0, .Llevel_30_8006E40C
    /* 1F2C19C 8006E400 00000000 */   nop
    /* 1F2C1A0 8006E404 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 1F2C1A4 8006E408 A4A020AC */  sw         $zero, %lo(D_8006A0A4)($at)
  .Llevel_30_8006E40C:
    /* 1F2C1A8 8006E40C 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 1F2C1AC 8006E410 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 1F2C1B0 8006E414 00000000 */  nop
    /* 1F2C1B4 8006E418 810C4228 */  slti       $v0, $v0, 0xC81
    /* 1F2C1B8 8006E41C 04004014 */  bnez       $v0, .Llevel_30_8006E430
    /* 1F2C1BC 8006E420 C0000424 */   addiu     $a0, $zero, 0xC0
    /* 1F2C1C0 8006E424 21200000 */  addu       $a0, $zero, $zero
    /* 1F2C1C4 8006E428 0DB90108 */  j          .Llevel_30_8006E434
    /* 1F2C1C8 8006E42C C0000524 */   addiu     $a1, $zero, 0xC0
  .Llevel_30_8006E430:
    /* 1F2C1CC 8006E430 40000524 */  addiu      $a1, $zero, 0x40
  .Llevel_30_8006E434:
    /* 1F2C1D0 8006E434 5CAF000C */  jal        func_8002BD70
    /* 1F2C1D4 8006E438 00000000 */   nop
  .Llevel_30_8006E43C:
    /* 1F2C1D8 8006E43C 0780103C */  lui        $s0, %hi(D_8006A0A8)
    /* 1F2C1DC 8006E440 A8A01026 */  addiu      $s0, $s0, %lo(D_8006A0A8)
    /* 1F2C1E0 8006E444 0000028E */  lw         $v0, 0x0($s0)
    /* 1F2C1E4 8006E448 00000000 */  nop
    /* 1F2C1E8 8006E44C 09004010 */  beqz       $v0, .Llevel_30_8006E474
    /* 1F2C1EC 8006E450 00000000 */   nop
    /* 1F2C1F0 8006E454 6FAF000C */  jal        func_8002BDBC
    /* 1F2C1F4 8006E458 00000000 */   nop
    /* 1F2C1F8 8006E45C 0EB0000C */  jal        func_8002C038
    /* 1F2C1FC 8006E460 00000000 */   nop
    /* 1F2C200 8006E464 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 1F2C204 8006E468 8CA020AC */  sw         $zero, %lo(D_8006A08C)($at)
    /* 1F2C208 8006E46C 21B90108 */  j          .Llevel_30_8006E484
    /* 1F2C20C 8006E470 00000000 */   nop
  .Llevel_30_8006E474:
    /* 1F2C210 8006E474 686F000C */  jal        func_8001BDA0
    /* 1F2C214 8006E478 D0FF0426 */   addiu     $a0, $s0, -0x30
    /* 1F2C218 8006E47C 686F000C */  jal        func_8001BDA0
    /* 1F2C21C 8006E480 DCFF0426 */   addiu     $a0, $s0, -0x24
  .Llevel_30_8006E484:
    /* 1F2C220 8006E484 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 1F2C224 8006E488 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 1F2C228 8006E48C 00000000 */  nop
    /* 1F2C22C 8006E490 79004010 */  beqz       $v0, .Llevel_30_8006E678
    /* 1F2C230 8006E494 00000000 */   nop
    /* 1F2C234 8006E498 0780143C */  lui        $s4, %hi(D_8006A018)
    /* 1F2C238 8006E49C 18A09426 */  addiu      $s4, $s4, %lo(D_8006A018)
    /* 1F2C23C 8006E4A0 0000828E */  lw         $v0, 0x0($s4)
    /* 1F2C240 8006E4A4 00000000 */  nop
    /* 1F2C244 8006E4A8 73004104 */  bgez       $v0, .Llevel_30_8006E678
    /* 1F2C248 8006E4AC 00000000 */   nop
    /* 1F2C24C 8006E4B0 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 1F2C250 8006E4B4 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 1F2C254 8006E4B8 00000000 */  nop
    /* 1F2C258 8006E4BC 01044228 */  slti       $v0, $v0, 0x401
    /* 1F2C25C 8006E4C0 42004014 */  bnez       $v0, .Llevel_30_8006E5CC
    /* 1F2C260 8006E4C4 0200422A */   slti      $v0, $s2, 0x2
    /* 1F2C264 8006E4C8 40004010 */  beqz       $v0, .Llevel_30_8006E5CC
    /* 1F2C268 8006E4CC 00000000 */   nop
    /* 1F2C26C 8006E4D0 0680023C */  lui        $v0, %hi(D_80067008)
    /* 1F2C270 8006E4D4 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 1F2C274 8006E4D8 00000000 */  nop
    /* 1F2C278 8006E4DC 01004230 */  andi       $v0, $v0, 0x1
    /* 1F2C27C 8006E4E0 3A004010 */  beqz       $v0, .Llevel_30_8006E5CC
    /* 1F2C280 8006E4E4 4800B327 */   addiu     $s3, $sp, 0x48
    /* 1F2C284 8006E4E8 21206002 */  addu       $a0, $s3, $zero
    /* 1F2C288 8006E4EC 6C6F000C */  jal        func_8001BDB0
    /* 1F2C28C 8006E4F0 D8FF8526 */   addiu     $a1, $s4, -0x28
    /* 1F2C290 8006E4F4 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 1F2C294 8006E4F8 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 1F2C298 8006E4FC 40000224 */  addiu      $v0, $zero, 0x40
    /* 1F2C29C 8006E500 5C00A2AF */  sw         $v0, 0x5C($sp)
    /* 1F2C2A0 8006E504 6000A0AF */  sw         $zero, 0x60($sp)
    /* 1F2C2A4 8006E508 43190300 */  sra        $v1, $v1, 5
    /* 1F2C2A8 8006E50C 03004012 */  beqz       $s2, .Llevel_30_8006E51C
    /* 1F2C2AC 8006E510 5800A3AF */   sw        $v1, 0x58($sp)
    /* 1F2C2B0 8006E514 C0FF0224 */  addiu      $v0, $zero, -0x40
    /* 1F2C2B4 8006E518 5C00A2AF */  sw         $v0, 0x5C($sp)
  .Llevel_30_8006E51C:
    /* 1F2C2B8 8006E51C 08009226 */  addiu      $s2, $s4, 0x8
    /* 1F2C2BC 8006E520 21204002 */  addu       $a0, $s2, $zero
    /* 1F2C2C0 8006E524 5800B127 */  addiu      $s1, $sp, 0x58
    /* 1F2C2C4 8006E528 21282002 */  addu       $a1, $s1, $zero
    /* 1F2C2C8 8006E52C 6800B027 */  addiu      $s0, $sp, 0x68
    /* 1F2C2CC 8006E530 696E000C */  jal        func_8001B9A4
    /* 1F2C2D0 8006E534 21300002 */   addu      $a2, $s0, $zero
    /* 1F2C2D4 8006E538 21206002 */  addu       $a0, $s3, $zero
    /* 1F2C2D8 8006E53C 21286002 */  addu       $a1, $s3, $zero
    /* 1F2C2DC 8006E540 736F000C */  jal        func_8001BDCC
    /* 1F2C2E0 8006E544 21300002 */   addu      $a2, $s0, $zero
    /* 1F2C2E4 8006E548 21204002 */  addu       $a0, $s2, $zero
    /* 1F2C2E8 8006E54C 21282002 */  addu       $a1, $s1, $zero
    /* 1F2C2EC 8006E550 0000828E */  lw         $v0, 0x0($s4)
    /* 1F2C2F0 8006E554 21302002 */  addu       $a2, $s1, $zero
    /* 1F2C2F4 8006E558 5800A0AF */  sw         $zero, 0x58($sp)
    /* 1F2C2F8 8006E55C 23100200 */  negu       $v0, $v0
    /* 1F2C2FC 8006E560 696E000C */  jal        func_8001B9A4
    /* 1F2C300 8006E564 5000A2AF */   sw        $v0, 0x50($sp)
    /* 1F2C304 8006E568 21202002 */  addu       $a0, $s1, $zero
    /* 1F2C308 8006E56C 526F000C */  jal        func_8001BD48
    /* 1F2C30C 8006E570 03000524 */   addiu     $a1, $zero, 0x3
    /* 1F2C310 8006E574 01000424 */  addiu      $a0, $zero, 0x1
    /* 1F2C314 8006E578 2A000524 */  addiu      $a1, $zero, 0x2A
    /* 1F2C318 8006E57C 21306002 */  addu       $a2, $s3, $zero
    /* 1F2C31C 8006E580 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 1F2C320 8006E584 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 1F2C324 8006E588 00000000 */  nop
    /* 1F2C328 8006E58C 09F84000 */  jalr       $v0
    /* 1F2C32C 8006E590 21382002 */   addu      $a3, $s1, $zero
    /* 1F2C330 8006E594 4B67010C */  jal        func_80059D2C
    /* 1F2C334 8006E598 00000000 */   nop
    /* 1F2C338 8006E59C 1F004230 */  andi       $v0, $v0, 0x1F
    /* 1F2C33C 8006E5A0 35004014 */  bnez       $v0, .Llevel_30_8006E678
    /* 1F2C340 8006E5A4 01000424 */   addiu     $a0, $zero, 0x1
    /* 1F2C344 8006E5A8 29000524 */  addiu      $a1, $zero, 0x29
    /* 1F2C348 8006E5AC 21306002 */  addu       $a2, $s3, $zero
    /* 1F2C34C 8006E5B0 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 1F2C350 8006E5B4 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 1F2C354 8006E5B8 00000000 */  nop
    /* 1F2C358 8006E5BC 09F84000 */  jalr       $v0
    /* 1F2C35C 8006E5C0 21380000 */   addu      $a3, $zero, $zero
    /* 1F2C360 8006E5C4 9EB90108 */  j          .Llevel_30_8006E678
    /* 1F2C364 8006E5C8 00000000 */   nop
  .Llevel_30_8006E5CC:
    /* 1F2C368 8006E5CC 0780113C */  lui        $s1, %hi(D_8006A0A8)
    /* 1F2C36C 8006E5D0 A8A03126 */  addiu      $s1, $s1, %lo(D_8006A0A8)
    /* 1F2C370 8006E5D4 0000228E */  lw         $v0, 0x0($s1)
    /* 1F2C374 8006E5D8 00000000 */  nop
    /* 1F2C378 8006E5DC 01024228 */  slti       $v0, $v0, 0x201
    /* 1F2C37C 8006E5E0 25004010 */  beqz       $v0, .Llevel_30_8006E678
    /* 1F2C380 8006E5E4 00000000 */   nop
    /* 1F2C384 8006E5E8 23004016 */  bnez       $s2, .Llevel_30_8006E678
    /* 1F2C388 8006E5EC 00000000 */   nop
    /* 1F2C38C 8006E5F0 0680023C */  lui        $v0, %hi(D_80067008)
    /* 1F2C390 8006E5F4 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 1F2C394 8006E5F8 00000000 */  nop
    /* 1F2C398 8006E5FC 07004230 */  andi       $v0, $v0, 0x7
    /* 1F2C39C 8006E600 1D004014 */  bnez       $v0, .Llevel_30_8006E678
    /* 1F2C3A0 8006E604 00000000 */   nop
    /* 1F2C3A4 8006E608 4B67010C */  jal        func_80059D2C
    /* 1F2C3A8 8006E60C 00000000 */   nop
    /* 1F2C3AC 8006E610 03004230 */  andi       $v0, $v0, 0x3
    /* 1F2C3B0 8006E614 18004014 */  bnez       $v0, .Llevel_30_8006E678
    /* 1F2C3B4 8006E618 78FF2426 */   addiu     $a0, $s1, -0x88
    /* 1F2C3B8 8006E61C 7800B027 */  addiu      $s0, $sp, 0x78
    /* 1F2C3BC 8006E620 21280002 */  addu       $a1, $s0, $zero
    /* 1F2C3C0 8006E624 21300002 */  addu       $a2, $s0, $zero
    /* 1F2C3C4 8006E628 80000224 */  addiu      $v0, $zero, 0x80
    /* 1F2C3C8 8006E62C 7800A2AF */  sw         $v0, 0x78($sp)
    /* 1F2C3CC 8006E630 7C00A0AF */  sw         $zero, 0x7C($sp)
    /* 1F2C3D0 8006E634 696E000C */  jal        func_8001B9A4
    /* 1F2C3D4 8006E638 8000A0AF */   sw        $zero, 0x80($sp)
    /* 1F2C3D8 8006E63C 21200002 */  addu       $a0, $s0, $zero
    /* 1F2C3DC 8006E640 21280002 */  addu       $a1, $s0, $zero
    /* 1F2C3E0 8006E644 736F000C */  jal        func_8001BDCC
    /* 1F2C3E4 8006E648 48FF2626 */   addiu     $a2, $s1, -0xB8
    /* 1F2C3E8 8006E64C 01000424 */  addiu      $a0, $zero, 0x1
    /* 1F2C3EC 8006E650 2B000524 */  addiu      $a1, $zero, 0x2B
    /* 1F2C3F0 8006E654 21300002 */  addu       $a2, $s0, $zero
    /* 1F2C3F4 8006E658 01000724 */  addiu      $a3, $zero, 0x1
    /* 1F2C3F8 8006E65C 0780023C */  lui        $v0, %hi(D_8006A018)
    /* 1F2C3FC 8006E660 18A0428C */  lw         $v0, %lo(D_8006A018)($v0)
    /* 1F2C400 8006E664 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 1F2C404 8006E668 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 1F2C408 8006E66C 23100200 */  negu       $v0, $v0
    /* 1F2C40C 8006E670 09F86000 */  jalr       $v1
    /* 1F2C410 8006E674 8000A2AF */   sw        $v0, 0x80($sp)
  .Llevel_30_8006E678:
    /* 1F2C414 8006E678 0780063C */  lui        $a2, %hi(D_8006A13C)
    /* 1F2C418 8006E67C 3CA1C624 */  addiu      $a2, $a2, %lo(D_8006A13C)
    /* 1F2C41C 8006E680 0780043C */  lui        $a0, %hi(D_8006A140)
    /* 1F2C420 8006E684 40A1848C */  lw         $a0, %lo(D_8006A140)($a0)
    /* 1F2C424 8006E688 0000C58C */  lw         $a1, 0x0($a2)
    /* 1F2C428 8006E68C 40180400 */  sll        $v1, $a0, 1
    /* 1F2C42C 8006E690 80100500 */  sll        $v0, $a1, 2
    /* 1F2C430 8006E694 21104500 */  addu       $v0, $v0, $a1
    /* 1F2C434 8006E698 80100200 */  sll        $v0, $v0, 2
    /* 1F2C438 8006E69C 21186200 */  addu       $v1, $v1, $v0
    /* 1F2C43C 8006E6A0 031A0300 */  sra        $v1, $v1, 8
    /* 1F2C440 8006E6A4 2328A300 */  subu       $a1, $a1, $v1
    /* 1F2C444 8006E6A8 21208500 */  addu       $a0, $a0, $a1
    /* 1F2C448 8006E6AC 0000C5AC */  sw         $a1, 0x0($a2)
    /* 1F2C44C 8006E6B0 0780013C */  lui        $at, %hi(D_8006A140)
    /* 1F2C450 8006E6B4 40A124AC */  sw         $a0, %lo(D_8006A140)($at)
    /* 1F2C454 8006E6B8 01598428 */  slti       $a0, $a0, 0x5901
    /* 1F2C458 8006E6BC 03008014 */  bnez       $a0, .Llevel_30_8006E6CC
    /* 1F2C45C 8006E6C0 00590224 */   addiu     $v0, $zero, 0x5900
    /* 1F2C460 8006E6C4 0780013C */  lui        $at, %hi(D_8006A140)
    /* 1F2C464 8006E6C8 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
  .Llevel_30_8006E6CC:
    /* 1F2C468 8006E6CC 0780023C */  lui        $v0, %hi(D_8006A140)
    /* 1F2C46C 8006E6D0 40A1428C */  lw         $v0, %lo(D_8006A140)($v0)
    /* 1F2C470 8006E6D4 00000000 */  nop
    /* 1F2C474 8006E6D8 00A74228 */  slti       $v0, $v0, -0x5900
    /* 1F2C478 8006E6DC B4004010 */  beqz       $v0, .Llevel_30_8006E9B0
    /* 1F2C47C 8006E6E0 00A70224 */   addiu     $v0, $zero, -0x5900
    /* 1F2C480 8006E6E4 0780013C */  lui        $at, %hi(D_8006A140)
    /* 1F2C484 8006E6E8 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
    /* 1F2C488 8006E6EC 6CBA0108 */  j          .Llevel_30_8006E9B0
    /* 1F2C48C 8006E6F0 00000000 */   nop
  .Llevel_30_8006E6F4:
    /* 1F2C490 8006E6F4 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 1F2C494 8006E6F8 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 1F2C498 8006E6FC 07000224 */  addiu      $v0, $zero, 0x7
    /* 1F2C49C 8006E700 3A006210 */  beq        $v1, $v0, .Llevel_30_8006E7EC
    /* 1F2C4A0 8006E704 6800A427 */   addiu     $a0, $sp, 0x68
    /* 1F2C4A4 8006E708 39AD000C */  jal        func_8002B4E4
    /* 1F2C4A8 8006E70C 21280000 */   addu      $a1, $zero, $zero
    /* 1F2C4AC 8006E710 8800A427 */  addiu      $a0, $sp, 0x88
    /* 1F2C4B0 8006E714 6800A28F */  lw         $v0, 0x68($sp)
    /* 1F2C4B4 8006E718 6C00A68F */  lw         $a2, 0x6C($sp)
    /* 1F2C4B8 8006E71C 21280000 */  addu       $a1, $zero, $zero
    /* 1F2C4BC 8006E720 8800A0AF */  sw         $zero, 0x88($sp)
    /* 1F2C4C0 8006E724 C0180200 */  sll        $v1, $v0, 3
    /* 1F2C4C4 8006E728 21186200 */  addu       $v1, $v1, $v0
    /* 1F2C4C8 8006E72C C0190300 */  sll        $v1, $v1, 7
    /* 1F2C4CC 8006E730 C3190300 */  sra        $v1, $v1, 7
    /* 1F2C4D0 8006E734 40100600 */  sll        $v0, $a2, 1
    /* 1F2C4D4 8006E738 21104600 */  addu       $v0, $v0, $a2
    /* 1F2C4D8 8006E73C 40120200 */  sll        $v0, $v0, 9
    /* 1F2C4DC 8006E740 C3110200 */  sra        $v0, $v0, 7
    /* 1F2C4E0 8006E744 6800A3AF */  sw         $v1, 0x68($sp)
    /* 1F2C4E4 8006E748 23180300 */  negu       $v1, $v1
    /* 1F2C4E8 8006E74C 6C00A2AF */  sw         $v0, 0x6C($sp)
    /* 1F2C4EC 8006E750 8C00A3AF */  sw         $v1, 0x8C($sp)
    /* 1F2C4F0 8006E754 886E000C */  jal        func_8001BA20
    /* 1F2C4F4 8006E758 9000A2AF */   sw        $v0, 0x90($sp)
    /* 1F2C4F8 8006E75C 9000A48F */  lw         $a0, 0x90($sp)
    /* 1F2C4FC 8006E760 00000000 */  nop
    /* 1F2C500 8006E764 02008104 */  bgez       $a0, .Llevel_30_8006E770
    /* 1F2C504 8006E768 21188000 */   addu      $v1, $a0, $zero
    /* 1F2C508 8006E76C 23180300 */  negu       $v1, $v1
  .Llevel_30_8006E770:
    /* 1F2C50C 8006E770 2A186200 */  slt        $v1, $v1, $v0
    /* 1F2C510 8006E774 0C006010 */  beqz       $v1, .Llevel_30_8006E7A8
    /* 1F2C514 8006E778 00000000 */   nop
    /* 1F2C518 8006E77C 8C00A28F */  lw         $v0, 0x8C($sp)
    /* 1F2C51C 8006E780 9000A0AF */  sw         $zero, 0x90($sp)
    /* 1F2C520 8006E784 02004018 */  blez       $v0, .Llevel_30_8006E790
    /* 1F2C524 8006E788 21200000 */   addu      $a0, $zero, $zero
    /* 1F2C528 8006E78C 01000424 */  addiu      $a0, $zero, 0x1
  .Llevel_30_8006E790:
    /* 1F2C52C 8006E790 CAB4000C */  jal        func_8002D328
    /* 1F2C530 8006E794 00000000 */   nop
    /* 1F2C534 8006E798 0E004014 */  bnez       $v0, .Llevel_30_8006E7D4
    /* 1F2C538 8006E79C 8800A427 */   addiu     $a0, $sp, 0x88
    /* 1F2C53C 8006E7A0 F5B90108 */  j          .Llevel_30_8006E7D4
    /* 1F2C540 8006E7A4 8C00A0AF */   sw        $zero, 0x8C($sp)
  .Llevel_30_8006E7A8:
    /* 1F2C544 8006E7A8 8C00A0AF */  sw         $zero, 0x8C($sp)
    /* 1F2C548 8006E7AC 03008018 */  blez       $a0, .Llevel_30_8006E7BC
    /* 1F2C54C 8006E7B0 8800A0AF */   sw        $zero, 0x88($sp)
    /* 1F2C550 8006E7B4 F0B90108 */  j          .Llevel_30_8006E7C0
    /* 1F2C554 8006E7B8 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_30_8006E7BC:
    /* 1F2C558 8006E7BC 03000424 */  addiu      $a0, $zero, 0x3
  .Llevel_30_8006E7C0:
    /* 1F2C55C 8006E7C0 CAB4000C */  jal        func_8002D328
    /* 1F2C560 8006E7C4 00000000 */   nop
    /* 1F2C564 8006E7C8 02004014 */  bnez       $v0, .Llevel_30_8006E7D4
    /* 1F2C568 8006E7CC 8800A427 */   addiu     $a0, $sp, 0x88
    /* 1F2C56C 8006E7D0 9000A0AF */  sw         $zero, 0x90($sp)
  .Llevel_30_8006E7D4:
    /* 1F2C570 8006E7D4 886E000C */  jal        func_8001BA20
    /* 1F2C574 8006E7D8 01000524 */   addiu     $a1, $zero, 0x1
    /* 1F2C578 8006E7DC 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 1F2C57C 8006E7E0 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 1F2C580 8006E7E4 FDB90108 */  j          .Llevel_30_8006E7F4
    /* 1F2C584 8006E7E8 00000000 */   nop
  .Llevel_30_8006E7EC:
    /* 1F2C588 8006E7EC 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 1F2C58C 8006E7F0 A4A020AC */  sw         $zero, %lo(D_8006A0A4)($at)
  .Llevel_30_8006E7F4:
    /* 1F2C590 8006E7F4 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 1F2C594 8006E7F8 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
  .Llevel_30_8006E7FC:
    /* 1F2C598 8006E7FC 0780043C */  lui        $a0, %hi(D_8006A078)
    /* 1F2C59C 8006E800 78A08424 */  addiu      $a0, $a0, %lo(D_8006A078)
    /* 1F2C5A0 8006E804 686F000C */  jal        func_8001BDA0
    /* 1F2C5A4 8006E808 00000000 */   nop
    /* 1F2C5A8 8006E80C 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 1F2C5AC 8006E810 84A08424 */  addiu      $a0, $a0, %lo(D_8006A084)
    /* 1F2C5B0 8006E814 686F000C */  jal        func_8001BDA0
    /* 1F2C5B4 8006E818 00000000 */   nop
    /* 1F2C5B8 8006E81C 6CBA0108 */  j          .Llevel_30_8006E9B0
    /* 1F2C5BC 8006E820 00000000 */   nop
  .Llevel_30_8006E824:
    /* 1F2C5C0 8006E824 9800A427 */  addiu      $a0, $sp, 0x98
    /* 1F2C5C4 8006E828 39AD000C */  jal        func_8002B4E4
    /* 1F2C5C8 8006E82C 21280000 */   addu      $a1, $zero, $zero
    /* 1F2C5CC 8006E830 A000A427 */  addiu      $a0, $sp, 0xA0
    /* 1F2C5D0 8006E834 9800A28F */  lw         $v0, 0x98($sp)
    /* 1F2C5D4 8006E838 9C00A68F */  lw         $a2, 0x9C($sp)
    /* 1F2C5D8 8006E83C 21280000 */  addu       $a1, $zero, $zero
    /* 1F2C5DC 8006E840 A000A0AF */  sw         $zero, 0xA0($sp)
    /* 1F2C5E0 8006E844 C0180200 */  sll        $v1, $v0, 3
    /* 1F2C5E4 8006E848 21186200 */  addu       $v1, $v1, $v0
    /* 1F2C5E8 8006E84C C0190300 */  sll        $v1, $v1, 7
    /* 1F2C5EC 8006E850 C3190300 */  sra        $v1, $v1, 7
    /* 1F2C5F0 8006E854 40100600 */  sll        $v0, $a2, 1
    /* 1F2C5F4 8006E858 21104600 */  addu       $v0, $v0, $a2
    /* 1F2C5F8 8006E85C 40120200 */  sll        $v0, $v0, 9
    /* 1F2C5FC 8006E860 C3110200 */  sra        $v0, $v0, 7
    /* 1F2C600 8006E864 9800A3AF */  sw         $v1, 0x98($sp)
    /* 1F2C604 8006E868 23180300 */  negu       $v1, $v1
    /* 1F2C608 8006E86C 9C00A2AF */  sw         $v0, 0x9C($sp)
    /* 1F2C60C 8006E870 A400A3AF */  sw         $v1, 0xA4($sp)
    /* 1F2C610 8006E874 886E000C */  jal        func_8001BA20
    /* 1F2C614 8006E878 A800A2AF */   sw        $v0, 0xA8($sp)
    /* 1F2C618 8006E87C A800A48F */  lw         $a0, 0xA8($sp)
    /* 1F2C61C 8006E880 00000000 */  nop
    /* 1F2C620 8006E884 02008104 */  bgez       $a0, .Llevel_30_8006E890
    /* 1F2C624 8006E888 21188000 */   addu      $v1, $a0, $zero
    /* 1F2C628 8006E88C 23180300 */  negu       $v1, $v1
  .Llevel_30_8006E890:
    /* 1F2C62C 8006E890 2A186200 */  slt        $v1, $v1, $v0
    /* 1F2C630 8006E894 0C006010 */  beqz       $v1, .Llevel_30_8006E8C8
    /* 1F2C634 8006E898 00000000 */   nop
    /* 1F2C638 8006E89C A400A28F */  lw         $v0, 0xA4($sp)
    /* 1F2C63C 8006E8A0 A800A0AF */  sw         $zero, 0xA8($sp)
    /* 1F2C640 8006E8A4 02004018 */  blez       $v0, .Llevel_30_8006E8B0
    /* 1F2C644 8006E8A8 21200000 */   addu      $a0, $zero, $zero
    /* 1F2C648 8006E8AC 01000424 */  addiu      $a0, $zero, 0x1
  .Llevel_30_8006E8B0:
    /* 1F2C64C 8006E8B0 CAB4000C */  jal        func_8002D328
    /* 1F2C650 8006E8B4 00000000 */   nop
    /* 1F2C654 8006E8B8 0E004014 */  bnez       $v0, .Llevel_30_8006E8F4
    /* 1F2C658 8006E8BC A000B127 */   addiu     $s1, $sp, 0xA0
    /* 1F2C65C 8006E8C0 3DBA0108 */  j          .Llevel_30_8006E8F4
    /* 1F2C660 8006E8C4 A400A0AF */   sw        $zero, 0xA4($sp)
  .Llevel_30_8006E8C8:
    /* 1F2C664 8006E8C8 A400A0AF */  sw         $zero, 0xA4($sp)
    /* 1F2C668 8006E8CC 03008018 */  blez       $a0, .Llevel_30_8006E8DC
    /* 1F2C66C 8006E8D0 A000A0AF */   sw        $zero, 0xA0($sp)
    /* 1F2C670 8006E8D4 38BA0108 */  j          .Llevel_30_8006E8E0
    /* 1F2C674 8006E8D8 02000424 */   addiu     $a0, $zero, 0x2
  .Llevel_30_8006E8DC:
    /* 1F2C678 8006E8DC 03000424 */  addiu      $a0, $zero, 0x3
  .Llevel_30_8006E8E0:
    /* 1F2C67C 8006E8E0 CAB4000C */  jal        func_8002D328
    /* 1F2C680 8006E8E4 00000000 */   nop
    /* 1F2C684 8006E8E8 02004014 */  bnez       $v0, .Llevel_30_8006E8F4
    /* 1F2C688 8006E8EC A000B127 */   addiu     $s1, $sp, 0xA0
    /* 1F2C68C 8006E8F0 A800A0AF */  sw         $zero, 0xA8($sp)
  .Llevel_30_8006E8F4:
    /* 1F2C690 8006E8F4 21202002 */  addu       $a0, $s1, $zero
    /* 1F2C694 8006E8F8 886E000C */  jal        func_8001BA20
    /* 1F2C698 8006E8FC 01000524 */   addiu     $a1, $zero, 0x1
    /* 1F2C69C 8006E900 01000624 */  addiu      $a2, $zero, 0x1
    /* 1F2C6A0 8006E904 9800A48F */  lw         $a0, 0x98($sp)
    /* 1F2C6A4 8006E908 9C00A58F */  lw         $a1, 0x9C($sp)
    /* 1F2C6A8 8006E90C 0780103C */  lui        $s0, %hi(D_8006A0A4)
    /* 1F2C6AC 8006E910 A4A01026 */  addiu      $s0, $s0, %lo(D_8006A0A4)
    /* 1F2C6B0 8006E914 2E6D000C */  jal        func_8001B4B8
    /* 1F2C6B4 8006E918 000002AE */   sw        $v0, 0x0($s0)
    /* 1F2C6B8 8006E91C 21184000 */  addu       $v1, $v0, $zero
    /* 1F2C6BC 8006E920 01086228 */  slti       $v0, $v1, 0x801
    /* 1F2C6C0 8006E924 0780013C */  lui        $at, %hi(D_8006A09C)
    /* 1F2C6C4 8006E928 9CA023AC */  sw         $v1, %lo(D_8006A09C)($at)
    /* 1F2C6C8 8006E92C 04004014 */  bnez       $v0, .Llevel_30_8006E940
    /* 1F2C6CC 8006E930 7CFF0426 */   addiu     $a0, $s0, -0x84
    /* 1F2C6D0 8006E934 00F06224 */  addiu      $v0, $v1, -0x1000
    /* 1F2C6D4 8006E938 0780013C */  lui        $at, %hi(D_8006A09C)
    /* 1F2C6D8 8006E93C 9CA022AC */  sw         $v0, %lo(D_8006A09C)($at)
  .Llevel_30_8006E940:
    /* 1F2C6DC 8006E940 21282002 */  addu       $a1, $s1, $zero
    /* 1F2C6E0 8006E944 A000A28F */  lw         $v0, 0xA0($sp)
    /* 1F2C6E4 8006E948 21302002 */  addu       $a2, $s1, $zero
    /* 1F2C6E8 8006E94C 00044224 */  addiu      $v0, $v0, 0x400
    /* 1F2C6EC 8006E950 696E000C */  jal        func_8001B9A4
    /* 1F2C6F0 8006E954 A000A2AF */   sw        $v0, 0xA0($sp)
    /* 1F2C6F4 8006E958 21202002 */  addu       $a0, $s1, $zero
    /* 1F2C6F8 8006E95C 21282002 */  addu       $a1, $s1, $zero
    /* 1F2C6FC 8006E960 E0FF1226 */  addiu      $s2, $s0, -0x20
    /* 1F2C700 8006E964 806F000C */  jal        func_8001BE00
    /* 1F2C704 8006E968 21304002 */   addu      $a2, $s2, $zero
    /* 1F2C708 8006E96C 21202002 */  addu       $a0, $s1, $zero
    /* 1F2C70C 8006E970 886E000C */  jal        func_8001BA20
    /* 1F2C710 8006E974 21280000 */   addu      $a1, $zero, $zero
    /* 1F2C714 8006E978 21284000 */  addu       $a1, $v0, $zero
    /* 1F2C718 8006E97C 8101A228 */  slti       $v0, $a1, 0x181
    /* 1F2C71C 8006E980 03004014 */  bnez       $v0, .Llevel_30_8006E990
    /* 1F2C720 8006E984 21202002 */   addu      $a0, $s1, $zero
    /* 1F2C724 8006E988 316F000C */  jal        func_8001BCC4
    /* 1F2C728 8006E98C 80010624 */   addiu     $a2, $zero, 0x180
  .Llevel_30_8006E990:
    /* 1F2C72C 8006E990 D4FF1026 */  addiu      $s0, $s0, -0x2C
    /* 1F2C730 8006E994 21200002 */  addu       $a0, $s0, $zero
    /* 1F2C734 8006E998 21284002 */  addu       $a1, $s2, $zero
    /* 1F2C738 8006E99C 736F000C */  jal        func_8001BDCC
    /* 1F2C73C 8006E9A0 21302002 */   addu      $a2, $s1, $zero
    /* 1F2C740 8006E9A4 21204002 */  addu       $a0, $s2, $zero
    /* 1F2C744 8006E9A8 6C6F000C */  jal        func_8001BDB0
    /* 1F2C748 8006E9AC 21280002 */   addu      $a1, $s0, $zero
  .Llevel_30_8006E9B0:
    /* 1F2C74C 8006E9B0 C400BF8F */  lw         $ra, 0xC4($sp)
    /* 1F2C750 8006E9B4 C000B48F */  lw         $s4, 0xC0($sp)
    /* 1F2C754 8006E9B8 BC00B38F */  lw         $s3, 0xBC($sp)
    /* 1F2C758 8006E9BC B800B28F */  lw         $s2, 0xB8($sp)
    /* 1F2C75C 8006E9C0 B400B18F */  lw         $s1, 0xB4($sp)
    /* 1F2C760 8006E9C4 B000B08F */  lw         $s0, 0xB0($sp)
    /* 1F2C764 8006E9C8 C800BD27 */  addiu      $sp, $sp, 0xC8
    /* 1F2C768 8006E9CC 0800E003 */  jr         $ra
    /* 1F2C76C 8006E9D0 00000000 */   nop
endlabel func_level_30_8006D898
