.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_30_8006D4A8

dlabel jtbl_level_30_8006D4A8
    /* 1F2B244 8006D4A8 7CF60680 */ .word .Llevel_30_8006F67C
    /* 1F2B248 8006D4AC C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B24C 8006D4B0 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B250 8006D4B4 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B254 8006D4B8 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B258 8006D4BC C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B25C 8006D4C0 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B260 8006D4C4 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B264 8006D4C8 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B268 8006D4CC C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B26C 8006D4D0 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B270 8006D4D4 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B274 8006D4D8 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B278 8006D4DC C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B27C 8006D4E0 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B280 8006D4E4 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B284 8006D4E8 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B288 8006D4EC C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B28C 8006D4F0 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B290 8006D4F4 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B294 8006D4F8 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B298 8006D4FC C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B29C 8006D500 C4F60680 */ .word .Llevel_30_8006F6C4
    /* 1F2B2A0 8006D504 1CF70680 */ .word .Llevel_30_8006F71C
    /* 1F2B2A4 8006D508 70F70680 */ .word .Llevel_30_8006F770
    /* 1F2B2A8 8006D50C B4F70680 */ .word .Llevel_30_8006F7B4
    /* 1F2B2AC 8006D510 98F80680 */ .word .Llevel_30_8006F898
    /* 1F2B2B0 8006D514 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B2B4 8006D518 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B2B8 8006D51C 10FA0680 */ .word .Llevel_30_8006FA10
    /* 1F2B2BC 8006D520 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B2C0 8006D524 C4FB0680 */ .word .Llevel_30_8006FBC4
    /* 1F2B2C4 8006D528 74FA0680 */ .word .Llevel_30_8006FA74
    /* 1F2B2C8 8006D52C 24FB0680 */ .word .Llevel_30_8006FB24
    /* 1F2B2CC 8006D530 24FB0680 */ .word .Llevel_30_8006FB24
    /* 1F2B2D0 8006D534 00000000 */ .word 0x00000000
enddlabel jtbl_level_30_8006D4A8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_30_8006F644, 0x590

glabel func_level_30_8006F644
    /* 1F2D3E0 8006F644 0780023C */  lui        $v0, %hi(D_8006A040)
    /* 1F2D3E4 8006F648 40A0428C */  lw         $v0, %lo(D_8006A040)($v0)
    /* 1F2D3E8 8006F64C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 1F2D3EC 8006F650 EEFF4324 */  addiu      $v1, $v0, -0x12
    /* 1F2D3F0 8006F654 2300622C */  sltiu      $v0, $v1, 0x23
    /* 1F2D3F4 8006F658 5A014010 */  beqz       $v0, .Llevel_30_8006FBC4
    /* 1F2D3F8 8006F65C 1000BFAF */   sw        $ra, 0x10($sp)
    /* 1F2D3FC 8006F660 80100300 */  sll        $v0, $v1, 2
    /* 1F2D400 8006F664 0780013C */  lui        $at, %hi(jtbl_level_30_8006D4A8)
    /* 1F2D404 8006F668 21082200 */  addu       $at, $at, $v0
    /* 1F2D408 8006F66C A8D4228C */  lw         $v0, %lo(jtbl_level_30_8006D4A8)($at)
    /* 1F2D40C 8006F670 00000000 */  nop
    /* 1F2D410 8006F674 08004000 */  jr         $v0
    /* 1F2D414 8006F678 00000000 */   nop
  .Llevel_30_8006F67C:
    /* 1F2D418 8006F67C 2EAC000C */  jal        func_8002B0B8
    /* 1F2D41C 8006F680 00000000 */   nop
    /* 1F2D420 8006F684 4F014014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D424 8006F688 00000000 */   nop
    /* 1F2D428 8006F68C 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 1F2D42C 8006F690 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 1F2D430 8006F694 0780043C */  lui        $a0, %hi(D_80069FF0)
    /* 1F2D434 8006F698 F09F8424 */  addiu      $a0, $a0, %lo(D_80069FF0)
    /* 1F2D438 8006F69C DB6F000C */  jal        func_8001BF6C
    /* 1F2D43C 8006F6A0 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 1F2D440 8006F6A4 0780033C */  lui        $v1, %hi(D_8006A150)
    /* 1F2D444 8006F6A8 50A1638C */  lw         $v1, %lo(D_8006A150)($v1)
    /* 1F2D448 8006F6AC 00000000 */  nop
    /* 1F2D44C 8006F6B0 2A186200 */  slt        $v1, $v1, $v0
    /* 1F2D450 8006F6B4 43016010 */  beqz       $v1, .Llevel_30_8006FBC4
    /* 1F2D454 8006F6B8 10000424 */   addiu     $a0, $zero, 0x10
    /* 1F2D458 8006F6BC EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D45C 8006F6C0 00000000 */   nop
  .Llevel_30_8006F6C4:
    /* 1F2D460 8006F6C4 2EAC000C */  jal        func_8002B0B8
    /* 1F2D464 8006F6C8 00000000 */   nop
    /* 1F2D468 8006F6CC 3D014014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D46C 8006F6D0 00000000 */   nop
    /* 1F2D470 8006F6D4 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 1F2D474 8006F6D8 A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 1F2D478 8006F6DC 00000000 */  nop
    /* 1F2D47C 8006F6E0 80004230 */  andi       $v0, $v0, 0x80
    /* 1F2D480 8006F6E4 06004010 */  beqz       $v0, .Llevel_30_8006F700
    /* 1F2D484 8006F6E8 01000224 */   addiu     $v0, $zero, 0x1
    /* 1F2D488 8006F6EC 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 1F2D48C 8006F6F0 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 1F2D490 8006F6F4 00000000 */  nop
    /* 1F2D494 8006F6F8 30016214 */  bne        $v1, $v0, .Llevel_30_8006FBBC
    /* 1F2D498 8006F6FC 2A000424 */   addiu     $a0, $zero, 0x2A
  .Llevel_30_8006F700:
    /* 1F2D49C 8006F700 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 1F2D4A0 8006F704 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 1F2D4A4 8006F708 00000000 */  nop
    /* 1F2D4A8 8006F70C 2D014014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D4AC 8006F710 29000424 */   addiu     $a0, $zero, 0x29
    /* 1F2D4B0 8006F714 EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D4B4 8006F718 00000000 */   nop
  .Llevel_30_8006F71C:
    /* 1F2D4B8 8006F71C 2EAC000C */  jal        func_8002B0B8
    /* 1F2D4BC 8006F720 00000000 */   nop
    /* 1F2D4C0 8006F724 27014014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D4C4 8006F728 00000000 */   nop
    /* 1F2D4C8 8006F72C 0780043C */  lui        $a0, %hi(D_800683A0)
    /* 1F2D4CC 8006F730 A083848C */  lw         $a0, %lo(D_800683A0)($a0)
    /* 1F2D4D0 8006F734 00000000 */  nop
    /* 1F2D4D4 8006F738 80008230 */  andi       $v0, $a0, 0x80
    /* 1F2D4D8 8006F73C 03004010 */  beqz       $v0, .Llevel_30_8006F74C
    /* 1F2D4DC 8006F740 07000224 */   addiu     $v0, $zero, 0x7
    /* 1F2D4E0 8006F744 EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D4E4 8006F748 2A000424 */   addiu     $a0, $zero, 0x2A
  .Llevel_30_8006F74C:
    /* 1F2D4E8 8006F74C 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 1F2D4EC 8006F750 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 1F2D4F0 8006F754 00000000 */  nop
    /* 1F2D4F4 8006F758 1A016210 */  beq        $v1, $v0, .Llevel_30_8006FBC4
    /* 1F2D4F8 8006F75C 40008230 */   andi      $v0, $a0, 0x40
    /* 1F2D4FC 8006F760 18014010 */  beqz       $v0, .Llevel_30_8006FBC4
    /* 1F2D500 8006F764 28000424 */   addiu     $a0, $zero, 0x28
    /* 1F2D504 8006F768 EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D508 8006F76C 00000000 */   nop
  .Llevel_30_8006F770:
    /* 1F2D50C 8006F770 8AAC000C */  jal        func_8002B228
    /* 1F2D510 8006F774 00000000 */   nop
    /* 1F2D514 8006F778 12014014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D518 8006F77C 00000000 */   nop
    /* 1F2D51C 8006F780 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 1F2D520 8006F784 A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 1F2D524 8006F788 00000000 */  nop
    /* 1F2D528 8006F78C 80004230 */  andi       $v0, $v0, 0x80
    /* 1F2D52C 8006F790 0C014014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D530 8006F794 01000224 */   addiu     $v0, $zero, 0x1
    /* 1F2D534 8006F798 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 1F2D538 8006F79C 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 1F2D53C 8006F7A0 00000000 */  nop
    /* 1F2D540 8006F7A4 07016210 */  beq        $v1, $v0, .Llevel_30_8006FBC4
    /* 1F2D544 8006F7A8 28000424 */   addiu     $a0, $zero, 0x28
    /* 1F2D548 8006F7AC EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D54C 8006F7B0 00000000 */   nop
  .Llevel_30_8006F7B4:
    /* 1F2D550 8006F7B4 2EAC000C */  jal        func_8002B0B8
    /* 1F2D554 8006F7B8 00000000 */   nop
    /* 1F2D558 8006F7BC 01014014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D55C 8006F7C0 00000000 */   nop
    /* 1F2D560 8006F7C4 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 1F2D564 8006F7C8 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 1F2D568 8006F7CC 00000000 */  nop
    /* 1F2D56C 8006F7D0 40004230 */  andi       $v0, $v0, 0x40
    /* 1F2D570 8006F7D4 07004010 */  beqz       $v0, .Llevel_30_8006F7F4
    /* 1F2D574 8006F7D8 00000000 */   nop
    /* 1F2D578 8006F7DC 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 1F2D57C 8006F7E0 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 1F2D580 8006F7E4 00000000 */  nop
    /* 1F2D584 8006F7E8 09004228 */  slti       $v0, $v0, 0x9
    /* 1F2D588 8006F7EC 21004010 */  beqz       $v0, .Llevel_30_8006F874
    /* 1F2D58C 8006F7F0 05000424 */   addiu     $a0, $zero, 0x5
  .Llevel_30_8006F7F4:
    /* 1F2D590 8006F7F4 0780043C */  lui        $a0, %hi(D_8006A0F8)
    /* 1F2D594 8006F7F8 F8A08424 */  addiu      $a0, $a0, %lo(D_8006A0F8)
    /* 1F2D598 8006F7FC 00008290 */  lbu        $v0, 0x0($a0)
    /* 1F2D59C 8006F800 00000000 */  nop
    /* 1F2D5A0 8006F804 1A004010 */  beqz       $v0, .Llevel_30_8006F870
    /* 1F2D5A4 8006F808 00000000 */   nop
    /* 1F2D5A8 8006F80C 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 1F2D5AC 8006F810 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 1F2D5B0 8006F814 00000000 */  nop
    /* 1F2D5B4 8006F818 80004230 */  andi       $v0, $v0, 0x80
    /* 1F2D5B8 8006F81C 17004010 */  beqz       $v0, .Llevel_30_8006F87C
    /* 1F2D5BC 8006F820 00000000 */   nop
    /* 1F2D5C0 8006F824 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 1F2D5C4 8006F828 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 1F2D5C8 8006F82C 00000000 */  nop
    /* 1F2D5CC 8006F830 09004228 */  slti       $v0, $v0, 0x9
    /* 1F2D5D0 8006F834 11004014 */  bnez       $v0, .Llevel_30_8006F87C
    /* 1F2D5D4 8006F838 00000000 */   nop
    /* 1F2D5D8 8006F83C 0680023C */  lui        $v0, %hi(D_80064682)
    /* 1F2D5DC 8006F840 82464284 */  lh         $v0, %lo(D_80064682)($v0)
    /* 1F2D5E0 8006F844 00000000 */  nop
    /* 1F2D5E4 8006F848 0C004010 */  beqz       $v0, .Llevel_30_8006F87C
    /* 1F2D5E8 8006F84C F8FE8424 */   addiu     $a0, $a0, -0x108
    /* 1F2D5EC 8006F850 00040524 */  addiu      $a1, $zero, 0x400
    /* 1F2D5F0 8006F854 01000624 */  addiu      $a2, $zero, 0x1
    /* 1F2D5F4 8006F858 8FFB000C */  jal        func_8003EE3C
    /* 1F2D5F8 8006F85C 21380000 */   addu      $a3, $zero, $zero
    /* 1F2D5FC 8006F860 06004014 */  bnez       $v0, .Llevel_30_8006F87C
    /* 1F2D600 8006F864 28000424 */   addiu     $a0, $zero, 0x28
    /* 1F2D604 8006F868 EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D608 8006F86C 00000000 */   nop
  .Llevel_30_8006F870:
    /* 1F2D60C 8006F870 06000424 */  addiu      $a0, $zero, 0x6
  .Llevel_30_8006F874:
    /* 1F2D610 8006F874 76D4000C */  jal        func_800351D8
    /* 1F2D614 8006F878 00000000 */   nop
  .Llevel_30_8006F87C:
    /* 1F2D618 8006F87C 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 1F2D61C 8006F880 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 1F2D620 8006F884 00000000 */  nop
    /* 1F2D624 8006F888 CE004010 */  beqz       $v0, .Llevel_30_8006FBC4
    /* 1F2D628 8006F88C 2C000424 */   addiu     $a0, $zero, 0x2C
    /* 1F2D62C 8006F890 EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D630 8006F894 00000000 */   nop
  .Llevel_30_8006F898:
    /* 1F2D634 8006F898 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 1F2D638 8006F89C 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 1F2D63C 8006F8A0 01000224 */  addiu      $v0, $zero, 0x1
    /* 1F2D640 8006F8A4 1F006214 */  bne        $v1, $v0, .Llevel_30_8006F924
    /* 1F2D644 8006F8A8 00000000 */   nop
    /* 1F2D648 8006F8AC 0780023C */  lui        $v0, %hi(D_8006ABF8)
    /* 1F2D64C 8006F8B0 F8AB4290 */  lbu        $v0, %lo(D_8006ABF8)($v0)
    /* 1F2D650 8006F8B4 00000000 */  nop
    /* 1F2D654 8006F8B8 C2004014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D658 8006F8BC 00000000 */   nop
    /* 1F2D65C 8006F8C0 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 1F2D660 8006F8C4 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 1F2D664 8006F8C8 00000000 */  nop
    /* 1F2D668 8006F8CC 50084230 */  andi       $v0, $v0, 0x850
    /* 1F2D66C 8006F8D0 07004014 */  bnez       $v0, .Llevel_30_8006F8F0
    /* 1F2D670 8006F8D4 00000000 */   nop
    /* 1F2D674 8006F8D8 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 1F2D678 8006F8DC 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 1F2D67C 8006F8E0 00000000 */  nop
    /* 1F2D680 8006F8E4 3D004228 */  slti       $v0, $v0, 0x3D
    /* 1F2D684 8006F8E8 B6004014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D688 8006F8EC 00000000 */   nop
  .Llevel_30_8006F8F0:
    /* 1F2D68C 8006F8F0 0680023C */  lui        $v0, %hi(D_80066F8C)
    /* 1F2D690 8006F8F4 8C6F428C */  lw         $v0, %lo(D_80066F8C)($v0)
    /* 1F2D694 8006F8F8 00000000 */  nop
    /* 1F2D698 8006F8FC 05004010 */  beqz       $v0, .Llevel_30_8006F914
    /* 1F2D69C 8006F900 00000000 */   nop
    /* 1F2D6A0 8006F904 09F84000 */  jalr       $v0
    /* 1F2D6A4 8006F908 00000000 */   nop
    /* 1F2D6A8 8006F90C F1BE0108 */  j          .Llevel_30_8006FBC4
    /* 1F2D6AC 8006F910 00000000 */   nop
  .Llevel_30_8006F914:
    /* 1F2D6B0 8006F914 9DCB000C */  jal        func_80032E74
    /* 1F2D6B4 8006F918 00000000 */   nop
    /* 1F2D6B8 8006F91C F1BE0108 */  j          .Llevel_30_8006FBC4
    /* 1F2D6BC 8006F920 00000000 */   nop
  .Llevel_30_8006F924:
    /* 1F2D6C0 8006F924 2EAC000C */  jal        func_8002B0B8
    /* 1F2D6C4 8006F928 00000000 */   nop
    /* 1F2D6C8 8006F92C A5004014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D6CC 8006F930 00000000 */   nop
    /* 1F2D6D0 8006F934 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 1F2D6D4 8006F938 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 1F2D6D8 8006F93C 00000000 */  nop
    /* 1F2D6DC 8006F940 40004230 */  andi       $v0, $v0, 0x40
    /* 1F2D6E0 8006F944 07004010 */  beqz       $v0, .Llevel_30_8006F964
    /* 1F2D6E4 8006F948 00000000 */   nop
    /* 1F2D6E8 8006F94C 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 1F2D6EC 8006F950 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 1F2D6F0 8006F954 00000000 */  nop
    /* 1F2D6F4 8006F958 09004228 */  slti       $v0, $v0, 0x9
    /* 1F2D6F8 8006F95C 97004010 */  beqz       $v0, .Llevel_30_8006FBBC
    /* 1F2D6FC 8006F960 05000424 */   addiu     $a0, $zero, 0x5
  .Llevel_30_8006F964:
    /* 1F2D700 8006F964 0780043C */  lui        $a0, %hi(D_8006A0F8)
    /* 1F2D704 8006F968 F8A08424 */  addiu      $a0, $a0, %lo(D_8006A0F8)
    /* 1F2D708 8006F96C 00008290 */  lbu        $v0, 0x0($a0)
    /* 1F2D70C 8006F970 00000000 */  nop
    /* 1F2D710 8006F974 03004014 */  bnez       $v0, .Llevel_30_8006F984
    /* 1F2D714 8006F978 00000000 */   nop
    /* 1F2D718 8006F97C EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D71C 8006F980 06000424 */   addiu     $a0, $zero, 0x6
  .Llevel_30_8006F984:
    /* 1F2D720 8006F984 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 1F2D724 8006F988 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 1F2D728 8006F98C 00000000 */  nop
    /* 1F2D72C 8006F990 80004230 */  andi       $v0, $v0, 0x80
    /* 1F2D730 8006F994 12004010 */  beqz       $v0, .Llevel_30_8006F9E0
    /* 1F2D734 8006F998 00000000 */   nop
    /* 1F2D738 8006F99C 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 1F2D73C 8006F9A0 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 1F2D740 8006F9A4 00000000 */  nop
    /* 1F2D744 8006F9A8 09004228 */  slti       $v0, $v0, 0x9
    /* 1F2D748 8006F9AC 0C004014 */  bnez       $v0, .Llevel_30_8006F9E0
    /* 1F2D74C 8006F9B0 00000000 */   nop
    /* 1F2D750 8006F9B4 0680023C */  lui        $v0, %hi(D_80064682)
    /* 1F2D754 8006F9B8 82464284 */  lh         $v0, %lo(D_80064682)($v0)
    /* 1F2D758 8006F9BC 00000000 */  nop
    /* 1F2D75C 8006F9C0 07004010 */  beqz       $v0, .Llevel_30_8006F9E0
    /* 1F2D760 8006F9C4 F8FE8424 */   addiu     $a0, $a0, -0x108
    /* 1F2D764 8006F9C8 00040524 */  addiu      $a1, $zero, 0x400
    /* 1F2D768 8006F9CC 01000624 */  addiu      $a2, $zero, 0x1
    /* 1F2D76C 8006F9D0 8FFB000C */  jal        func_8003EE3C
    /* 1F2D770 8006F9D4 21380000 */   addu      $a3, $zero, $zero
    /* 1F2D774 8006F9D8 78004010 */  beqz       $v0, .Llevel_30_8006FBBC
    /* 1F2D778 8006F9DC 28000424 */   addiu     $a0, $zero, 0x28
  .Llevel_30_8006F9E0:
    /* 1F2D77C 8006F9E0 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 1F2D780 8006F9E4 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 1F2D784 8006F9E8 07000224 */  addiu      $v0, $zero, 0x7
    /* 1F2D788 8006F9EC 75006210 */  beq        $v1, $v0, .Llevel_30_8006FBC4
    /* 1F2D78C 8006F9F0 00000000 */   nop
    /* 1F2D790 8006F9F4 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 1F2D794 8006F9F8 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 1F2D798 8006F9FC 00000000 */  nop
    /* 1F2D79C 8006FA00 70004014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D7A0 8006FA04 2B000424 */   addiu     $a0, $zero, 0x2B
    /* 1F2D7A4 8006FA08 EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D7A8 8006FA0C 00000000 */   nop
  .Llevel_30_8006FA10:
    /* 1F2D7AC 8006FA10 2EAC000C */  jal        func_8002B0B8
    /* 1F2D7B0 8006FA14 00000000 */   nop
    /* 1F2D7B4 8006FA18 6A004014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D7B8 8006FA1C 00000000 */   nop
    /* 1F2D7BC 8006FA20 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 1F2D7C0 8006FA24 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 1F2D7C4 8006FA28 00000000 */  nop
    /* 1F2D7C8 8006FA2C 40004230 */  andi       $v0, $v0, 0x40
    /* 1F2D7CC 8006FA30 09004010 */  beqz       $v0, .Llevel_30_8006FA58
    /* 1F2D7D0 8006FA34 00000000 */   nop
    /* 1F2D7D4 8006FA38 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 1F2D7D8 8006FA3C A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 1F2D7DC 8006FA40 00000000 */  nop
    /* 1F2D7E0 8006FA44 00404230 */  andi       $v0, $v0, 0x4000
    /* 1F2D7E4 8006FA48 46004014 */  bnez       $v0, .Llevel_30_8006FB64
    /* 1F2D7E8 8006FA4C 05000424 */   addiu     $a0, $zero, 0x5
    /* 1F2D7EC 8006FA50 EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D7F0 8006FA54 00000000 */   nop
  .Llevel_30_8006FA58:
    /* 1F2D7F4 8006FA58 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 1F2D7F8 8006FA5C A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 1F2D7FC 8006FA60 00000000 */  nop
    /* 1F2D800 8006FA64 57004010 */  beqz       $v0, .Llevel_30_8006FBC4
    /* 1F2D804 8006FA68 32000424 */   addiu     $a0, $zero, 0x32
    /* 1F2D808 8006FA6C EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D80C 8006FA70 00000000 */   nop
  .Llevel_30_8006FA74:
    /* 1F2D810 8006FA74 2EAC000C */  jal        func_8002B0B8
    /* 1F2D814 8006FA78 00000000 */   nop
    /* 1F2D818 8006FA7C 51004014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D81C 8006FA80 00000000 */   nop
    /* 1F2D820 8006FA84 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 1F2D824 8006FA88 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 1F2D828 8006FA8C 00000000 */  nop
    /* 1F2D82C 8006FA90 40004230 */  andi       $v0, $v0, 0x40
    /* 1F2D830 8006FA94 09004010 */  beqz       $v0, .Llevel_30_8006FABC
    /* 1F2D834 8006FA98 00000000 */   nop
    /* 1F2D838 8006FA9C 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 1F2D83C 8006FAA0 A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 1F2D840 8006FAA4 00000000 */  nop
    /* 1F2D844 8006FAA8 00404230 */  andi       $v0, $v0, 0x4000
    /* 1F2D848 8006FAAC 2D004014 */  bnez       $v0, .Llevel_30_8006FB64
    /* 1F2D84C 8006FAB0 05000424 */   addiu     $a0, $zero, 0x5
    /* 1F2D850 8006FAB4 EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D854 8006FAB8 00000000 */   nop
  .Llevel_30_8006FABC:
    /* 1F2D858 8006FABC 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 1F2D85C 8006FAC0 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 1F2D860 8006FAC4 00000000 */  nop
    /* 1F2D864 8006FAC8 3C004010 */  beqz       $v0, .Llevel_30_8006FBBC
    /* 1F2D868 8006FACC 2F000424 */   addiu     $a0, $zero, 0x2F
    /* 1F2D86C 8006FAD0 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 1F2D870 8006FAD4 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 1F2D874 8006FAD8 0780033C */  lui        $v1, %hi(D_8006A0AC)
    /* 1F2D878 8006FADC ACA0638C */  lw         $v1, %lo(D_8006A0AC)($v1)
    /* 1F2D87C 8006FAE0 02004104 */  bgez       $v0, .Llevel_30_8006FAEC
    /* 1F2D880 8006FAE4 00000000 */   nop
    /* 1F2D884 8006FAE8 23100200 */  negu       $v0, $v0
  .Llevel_30_8006FAEC:
    /* 1F2D888 8006FAEC 2A104300 */  slt        $v0, $v0, $v1
    /* 1F2D88C 8006FAF0 34004010 */  beqz       $v0, .Llevel_30_8006FBC4
    /* 1F2D890 8006FAF4 00000000 */   nop
    /* 1F2D894 8006FAF8 0780023C */  lui        $v0, %hi(D_8006A09C)
    /* 1F2D898 8006FAFC 9CA0428C */  lw         $v0, %lo(D_8006A09C)($v0)
    /* 1F2D89C 8006FB00 00000000 */  nop
    /* 1F2D8A0 8006FB04 02004104 */  bgez       $v0, .Llevel_30_8006FB10
    /* 1F2D8A4 8006FB08 00000000 */   nop
    /* 1F2D8A8 8006FB0C 23100200 */  negu       $v0, $v0
  .Llevel_30_8006FB10:
    /* 1F2D8AC 8006FB10 00044228 */  slti       $v0, $v0, 0x400
    /* 1F2D8B0 8006FB14 29004010 */  beqz       $v0, .Llevel_30_8006FBBC
    /* 1F2D8B4 8006FB18 34000424 */   addiu     $a0, $zero, 0x34
    /* 1F2D8B8 8006FB1C EFBE0108 */  j          .Llevel_30_8006FBBC
    /* 1F2D8BC 8006FB20 33000424 */   addiu     $a0, $zero, 0x33
  .Llevel_30_8006FB24:
    /* 1F2D8C0 8006FB24 2EAC000C */  jal        func_8002B0B8
    /* 1F2D8C4 8006FB28 00000000 */   nop
    /* 1F2D8C8 8006FB2C 25004014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D8CC 8006FB30 00000000 */   nop
    /* 1F2D8D0 8006FB34 0780023C */  lui        $v0, %hi(D_800683A4)
    /* 1F2D8D4 8006FB38 A483428C */  lw         $v0, %lo(D_800683A4)($v0)
    /* 1F2D8D8 8006FB3C 00000000 */  nop
    /* 1F2D8DC 8006FB40 40004230 */  andi       $v0, $v0, 0x40
    /* 1F2D8E0 8006FB44 0E004010 */  beqz       $v0, .Llevel_30_8006FB80
    /* 1F2D8E4 8006FB48 00000000 */   nop
    /* 1F2D8E8 8006FB4C 0780023C */  lui        $v0, %hi(D_800683A0)
    /* 1F2D8EC 8006FB50 A083428C */  lw         $v0, %lo(D_800683A0)($v0)
    /* 1F2D8F0 8006FB54 00000000 */  nop
    /* 1F2D8F4 8006FB58 00404230 */  andi       $v0, $v0, 0x4000
    /* 1F2D8F8 8006FB5C 17004010 */  beqz       $v0, .Llevel_30_8006FBBC
    /* 1F2D8FC 8006FB60 05000424 */   addiu     $a0, $zero, 0x5
  .Llevel_30_8006FB64:
    /* 1F2D900 8006FB64 76D4000C */  jal        func_800351D8
    /* 1F2D904 8006FB68 06000424 */   addiu     $a0, $zero, 0x6
    /* 1F2D908 8006FB6C 03000224 */  addiu      $v0, $zero, 0x3
    /* 1F2D90C 8006FB70 0780013C */  lui        $at, %hi(D_8006A044)
    /* 1F2D910 8006FB74 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 1F2D914 8006FB78 F1BE0108 */  j          .Llevel_30_8006FBC4
    /* 1F2D918 8006FB7C 00000000 */   nop
  .Llevel_30_8006FB80:
    /* 1F2D91C 8006FB80 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 1F2D920 8006FB84 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 1F2D924 8006FB88 00000000 */  nop
    /* 1F2D928 8006FB8C 0B004010 */  beqz       $v0, .Llevel_30_8006FBBC
    /* 1F2D92C 8006FB90 2F000424 */   addiu     $a0, $zero, 0x2F
    /* 1F2D930 8006FB94 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 1F2D934 8006FB98 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 1F2D938 8006FB9C 0780033C */  lui        $v1, %hi(D_8006A0AC)
    /* 1F2D93C 8006FBA0 ACA0638C */  lw         $v1, %lo(D_8006A0AC)($v1)
    /* 1F2D940 8006FBA4 02004104 */  bgez       $v0, .Llevel_30_8006FBB0
    /* 1F2D944 8006FBA8 00000000 */   nop
    /* 1F2D948 8006FBAC 23100200 */  negu       $v0, $v0
  .Llevel_30_8006FBB0:
    /* 1F2D94C 8006FBB0 2A104300 */  slt        $v0, $v0, $v1
    /* 1F2D950 8006FBB4 03004014 */  bnez       $v0, .Llevel_30_8006FBC4
    /* 1F2D954 8006FBB8 32000424 */   addiu     $a0, $zero, 0x32
  .Llevel_30_8006FBBC:
    /* 1F2D958 8006FBBC 76D4000C */  jal        func_800351D8
    /* 1F2D95C 8006FBC0 00000000 */   nop
  .Llevel_30_8006FBC4:
    /* 1F2D960 8006FBC4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 1F2D964 8006FBC8 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 1F2D968 8006FBCC 0800E003 */  jr         $ra
    /* 1F2D96C 8006FBD0 00000000 */   nop
endlabel func_level_30_8006F644
    /* 1F2D970 8006FBD4 00000000 */  nop
