.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_30_8006D2F8

dlabel jtbl_level_30_8006D2F8
    /* 1F2B094 8006D2F8 10EA0680 */ .word .Llevel_30_8006EA10
    /* 1F2B098 8006D2FC E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B09C 8006D300 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0A0 8006D304 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0A4 8006D308 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0A8 8006D30C E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0AC 8006D310 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0B0 8006D314 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0B4 8006D318 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0B8 8006D31C E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0BC 8006D320 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0C0 8006D324 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0C4 8006D328 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0C8 8006D32C E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0CC 8006D330 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0D0 8006D334 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0D4 8006D338 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0D8 8006D33C E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0DC 8006D340 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0E0 8006D344 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0E4 8006D348 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0E8 8006D34C E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B0EC 8006D350 38EA0680 */ .word .Llevel_30_8006EA38
    /* 1F2B0F0 8006D354 38EA0680 */ .word .Llevel_30_8006EA38
    /* 1F2B0F4 8006D358 F8EA0680 */ .word .Llevel_30_8006EAF8
    /* 1F2B0F8 8006D35C 38EC0680 */ .word .Llevel_30_8006EC38
    /* 1F2B0FC 8006D360 38EC0680 */ .word .Llevel_30_8006EC38
    /* 1F2B100 8006D364 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B104 8006D368 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B108 8006D36C C0EC0680 */ .word .Llevel_30_8006ECC0
    /* 1F2B10C 8006D370 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B110 8006D374 E8ED0680 */ .word .Llevel_30_8006EDE8
    /* 1F2B114 8006D378 E8EC0680 */ .word .Llevel_30_8006ECE8
    /* 1F2B118 8006D37C 60ED0680 */ .word .Llevel_30_8006ED60
    /* 1F2B11C 8006D380 60ED0680 */ .word .Llevel_30_8006ED60
    /* 1F2B120 8006D384 00000000 */ .word 0x00000000
enddlabel jtbl_level_30_8006D2F8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_30_8006E9D4, 0x428

glabel func_level_30_8006E9D4
    /* 1F2C770 8006E9D4 0780023C */  lui        $v0, %hi(D_8006A040)
    /* 1F2C774 8006E9D8 40A0428C */  lw         $v0, %lo(D_8006A040)($v0)
    /* 1F2C778 8006E9DC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 1F2C77C 8006E9E0 1400BFAF */  sw         $ra, 0x14($sp)
    /* 1F2C780 8006E9E4 EEFF4324 */  addiu      $v1, $v0, -0x12
    /* 1F2C784 8006E9E8 2300622C */  sltiu      $v0, $v1, 0x23
    /* 1F2C788 8006E9EC FE004010 */  beqz       $v0, .Llevel_30_8006EDE8
    /* 1F2C78C 8006E9F0 1000B0AF */   sw        $s0, 0x10($sp)
    /* 1F2C790 8006E9F4 80100300 */  sll        $v0, $v1, 2
    /* 1F2C794 8006E9F8 0780013C */  lui        $at, %hi(jtbl_level_30_8006D2F8)
    /* 1F2C798 8006E9FC 21082200 */  addu       $at, $at, $v0
    /* 1F2C79C 8006EA00 F8D2228C */  lw         $v0, %lo(jtbl_level_30_8006D2F8)($at)
    /* 1F2C7A0 8006EA04 00000000 */  nop
    /* 1F2C7A4 8006EA08 08004000 */  jr         $v0
    /* 1F2C7A8 8006EA0C 00000000 */   nop
  .Llevel_30_8006EA10:
    /* 1F2C7AC 8006EA10 3DB0000C */  jal        func_8002C0F4
    /* 1F2C7B0 8006EA14 00000000 */   nop
    /* 1F2C7B4 8006EA18 22B3000C */  jal        func_8002CC88
    /* 1F2C7B8 8006EA1C 00000000 */   nop
    /* 1F2C7BC 8006EA20 81AF000C */  jal        func_8002BE04
    /* 1F2C7C0 8006EA24 00000000 */   nop
  .Llevel_30_8006EA28:
    /* 1F2C7C4 8006EA28 0780013C */  lui        $at, %hi(D_8006A018)
    /* 1F2C7C8 8006EA2C 18A020AC */  sw         $zero, %lo(D_8006A018)($at)
    /* 1F2C7CC 8006EA30 7ABB0108 */  j          .Llevel_30_8006EDE8
    /* 1F2C7D0 8006EA34 00000000 */   nop
  .Llevel_30_8006EA38:
    /* 1F2C7D4 8006EA38 3DB0000C */  jal        func_8002C0F4
    /* 1F2C7D8 8006EA3C 00000000 */   nop
    /* 1F2C7DC 8006EA40 22B3000C */  jal        func_8002CC88
    /* 1F2C7E0 8006EA44 00000000 */   nop
    /* 1F2C7E4 8006EA48 0780103C */  lui        $s0, %hi(D_8006A254)
    /* 1F2C7E8 8006EA4C 54A21026 */  addiu      $s0, $s0, %lo(D_8006A254)
    /* 1F2C7EC 8006EA50 0680023C */  lui        $v0, %hi(D_80067020)
    /* 1F2C7F0 8006EA54 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 1F2C7F4 8006EA58 0000058E */  lw         $a1, 0x0($s0)
    /* 1F2C7F8 8006EA5C 06004490 */  lbu        $a0, 0x6($v0)
    /* 1F2C7FC 8006EA60 C842010C */  jal        func_80050B20
    /* 1F2C800 8006EA64 00000000 */   nop
    /* 1F2C804 8006EA68 EFFF4010 */  beqz       $v0, .Llevel_30_8006EA28
    /* 1F2C808 8006EA6C 00000000 */   nop
    /* 1F2C80C 8006EA70 0000028E */  lw         $v0, 0x0($s0)
    /* 1F2C810 8006EA74 00000000 */  nop
    /* 1F2C814 8006EA78 40180200 */  sll        $v1, $v0, 1
    /* 1F2C818 8006EA7C 21186200 */  addu       $v1, $v1, $v0
    /* 1F2C81C 8006EA80 80180300 */  sll        $v1, $v1, 2
    /* 1F2C820 8006EA84 23186200 */  subu       $v1, $v1, $v0
    /* 1F2C824 8006EA88 80180300 */  sll        $v1, $v1, 2
    /* 1F2C828 8006EA8C 0780013C */  lui        $at, %hi(D_80069A1C)
    /* 1F2C82C 8006EA90 21082300 */  addu       $at, $at, $v1
    /* 1F2C830 8006EA94 1C9A248C */  lw         $a0, %lo(D_80069A1C)($at)
    /* 1F2C834 8006EA98 00000000 */  nop
    /* 1F2C838 8006EA9C C8008228 */  slti       $v0, $a0, 0xC8
    /* 1F2C83C 8006EAA0 04004010 */  beqz       $v0, .Llevel_30_8006EAB4
    /* 1F2C840 8006EAA4 38FF8224 */   addiu     $v0, $a0, -0xC8
    /* 1F2C844 8006EAA8 0780013C */  lui        $at, %hi(D_80069A1C)
    /* 1F2C848 8006EAAC 21082300 */  addu       $at, $at, $v1
    /* 1F2C84C 8006EAB0 1C9A22AC */  sw         $v0, %lo(D_80069A1C)($at)
  .Llevel_30_8006EAB4:
    /* 1F2C850 8006EAB4 0000028E */  lw         $v0, 0x0($s0)
    /* 1F2C854 8006EAB8 00000000 */  nop
    /* 1F2C858 8006EABC 40180200 */  sll        $v1, $v0, 1
    /* 1F2C85C 8006EAC0 21186200 */  addu       $v1, $v1, $v0
    /* 1F2C860 8006EAC4 80180300 */  sll        $v1, $v1, 2
    /* 1F2C864 8006EAC8 23186200 */  subu       $v1, $v1, $v0
    /* 1F2C868 8006EACC 80180300 */  sll        $v1, $v1, 2
    /* 1F2C86C 8006EAD0 0780013C */  lui        $at, %hi(D_80069A12)
    /* 1F2C870 8006EAD4 21082300 */  addu       $at, $at, $v1
    /* 1F2C874 8006EAD8 129A2290 */  lbu        $v0, %lo(D_80069A12)($at)
    /* 1F2C878 8006EADC 00000000 */  nop
    /* 1F2C87C 8006EAE0 10004234 */  ori        $v0, $v0, 0x10
    /* 1F2C880 8006EAE4 0780013C */  lui        $at, %hi(D_80069A12)
    /* 1F2C884 8006EAE8 21082300 */  addu       $at, $at, $v1
    /* 1F2C888 8006EAEC 129A22A0 */  sb         $v0, %lo(D_80069A12)($at)
    /* 1F2C88C 8006EAF0 8ABA0108 */  j          .Llevel_30_8006EA28
    /* 1F2C890 8006EAF4 00000000 */   nop
  .Llevel_30_8006EAF8:
    /* 1F2C894 8006EAF8 3DB0000C */  jal        func_8002C0F4
    /* 1F2C898 8006EAFC 00000000 */   nop
    /* 1F2C89C 8006EB00 22B3000C */  jal        func_8002CC88
    /* 1F2C8A0 8006EB04 00000000 */   nop
    /* 1F2C8A4 8006EB08 E5CA000C */  jal        func_80032B94
    /* 1F2C8A8 8006EB0C 00000000 */   nop
    /* 1F2C8AC 8006EB10 0780103C */  lui        $s0, %hi(D_8006A254)
    /* 1F2C8B0 8006EB14 54A21026 */  addiu      $s0, $s0, %lo(D_8006A254)
    /* 1F2C8B4 8006EB18 0680023C */  lui        $v0, %hi(D_80067020)
    /* 1F2C8B8 8006EB1C 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 1F2C8BC 8006EB20 0000058E */  lw         $a1, 0x0($s0)
    /* 1F2C8C0 8006EB24 06004490 */  lbu        $a0, 0x6($v0)
    /* 1F2C8C4 8006EB28 C842010C */  jal        func_80050B20
    /* 1F2C8C8 8006EB2C 00000000 */   nop
    /* 1F2C8CC 8006EB30 17004014 */  bnez       $v0, .Llevel_30_8006EB90
    /* 1F2C8D0 8006EB34 21280000 */   addu      $a1, $zero, $zero
    /* 1F2C8D4 8006EB38 0680023C */  lui        $v0, %hi(D_80067020)
    /* 1F2C8D8 8006EB3C 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 1F2C8DC 8006EB40 00000000 */  nop
    /* 1F2C8E0 8006EB44 06004490 */  lbu        $a0, 0x6($v0)
    /* 1F2C8E4 8006EB48 C841010C */  jal        func_80050720
    /* 1F2C8E8 8006EB4C 04000624 */   addiu     $a2, $zero, 0x4
    /* 1F2C8EC 8006EB50 07004004 */  bltz       $v0, .Llevel_30_8006EB70
    /* 1F2C8F0 8006EB54 000002AE */   sw        $v0, 0x0($s0)
    /* 1F2C8F4 8006EB58 21204000 */  addu       $a0, $v0, $zero
    /* 1F2C8F8 8006EB5C 1943010C */  jal        func_80050C64
    /* 1F2C8FC 8006EB60 7C150524 */   addiu     $a1, $zero, 0x157C
    /* 1F2C900 8006EB64 0000048E */  lw         $a0, 0x0($s0)
    /* 1F2C904 8006EB68 3D43010C */  jal        func_80050CF4
    /* 1F2C908 8006EB6C 90010524 */   addiu     $a1, $zero, 0x190
  .Llevel_30_8006EB70:
    /* 1F2C90C 8006EB70 0680023C */  lui        $v0, %hi(D_80067020)
    /* 1F2C910 8006EB74 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 1F2C914 8006EB78 00000000 */  nop
    /* 1F2C918 8006EB7C 06004290 */  lbu        $v0, 0x6($v0)
    /* 1F2C91C 8006EB80 0780013C */  lui        $at, %hi(D_8006A258)
    /* 1F2C920 8006EB84 58A222AC */  sw         $v0, %lo(D_8006A258)($at)
    /* 1F2C924 8006EB88 0780103C */  lui        $s0, %hi(D_8006A254)
    /* 1F2C928 8006EB8C 54A21026 */  addiu      $s0, $s0, %lo(D_8006A254)
  .Llevel_30_8006EB90:
    /* 1F2C92C 8006EB90 0680023C */  lui        $v0, %hi(D_80067020)
    /* 1F2C930 8006EB94 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 1F2C934 8006EB98 0000058E */  lw         $a1, 0x0($s0)
    /* 1F2C938 8006EB9C 06004490 */  lbu        $a0, 0x6($v0)
    /* 1F2C93C 8006EBA0 C842010C */  jal        func_80050B20
    /* 1F2C940 8006EBA4 00000000 */   nop
    /* 1F2C944 8006EBA8 9FFF4010 */  beqz       $v0, .Llevel_30_8006EA28
    /* 1F2C948 8006EBAC 00000000 */   nop
    /* 1F2C94C 8006EBB0 0000028E */  lw         $v0, 0x0($s0)
    /* 1F2C950 8006EBB4 00000000 */  nop
    /* 1F2C954 8006EBB8 40180200 */  sll        $v1, $v0, 1
    /* 1F2C958 8006EBBC 21186200 */  addu       $v1, $v1, $v0
    /* 1F2C95C 8006EBC0 80180300 */  sll        $v1, $v1, 2
    /* 1F2C960 8006EBC4 23186200 */  subu       $v1, $v1, $v0
    /* 1F2C964 8006EBC8 80180300 */  sll        $v1, $v1, 2
    /* 1F2C968 8006EBCC 0780013C */  lui        $at, %hi(D_80069A1C)
    /* 1F2C96C 8006EBD0 21082300 */  addu       $at, $at, $v1
    /* 1F2C970 8006EBD4 1C9A248C */  lw         $a0, %lo(D_80069A1C)($at)
    /* 1F2C974 8006EBD8 00000000 */  nop
    /* 1F2C978 8006EBDC E8138228 */  slti       $v0, $a0, 0x13E8
    /* 1F2C97C 8006EBE0 04004010 */  beqz       $v0, .Llevel_30_8006EBF4
    /* 1F2C980 8006EBE4 C8008224 */   addiu     $v0, $a0, 0xC8
    /* 1F2C984 8006EBE8 0780013C */  lui        $at, %hi(D_80069A1C)
    /* 1F2C988 8006EBEC 21082300 */  addu       $at, $at, $v1
    /* 1F2C98C 8006EBF0 1C9A22AC */  sw         $v0, %lo(D_80069A1C)($at)
  .Llevel_30_8006EBF4:
    /* 1F2C990 8006EBF4 0000028E */  lw         $v0, 0x0($s0)
    /* 1F2C994 8006EBF8 00000000 */  nop
    /* 1F2C998 8006EBFC 40180200 */  sll        $v1, $v0, 1
    /* 1F2C99C 8006EC00 21186200 */  addu       $v1, $v1, $v0
    /* 1F2C9A0 8006EC04 80180300 */  sll        $v1, $v1, 2
    /* 1F2C9A4 8006EC08 23186200 */  subu       $v1, $v1, $v0
    /* 1F2C9A8 8006EC0C 80180300 */  sll        $v1, $v1, 2
    /* 1F2C9AC 8006EC10 0780013C */  lui        $at, %hi(D_80069A12)
    /* 1F2C9B0 8006EC14 21082300 */  addu       $at, $at, $v1
    /* 1F2C9B4 8006EC18 129A2290 */  lbu        $v0, %lo(D_80069A12)($at)
    /* 1F2C9B8 8006EC1C 00000000 */  nop
    /* 1F2C9BC 8006EC20 10004234 */  ori        $v0, $v0, 0x10
    /* 1F2C9C0 8006EC24 0780013C */  lui        $at, %hi(D_80069A12)
    /* 1F2C9C4 8006EC28 21082300 */  addu       $at, $at, $v1
    /* 1F2C9C8 8006EC2C 129A22A0 */  sb         $v0, %lo(D_80069A12)($at)
    /* 1F2C9CC 8006EC30 8ABA0108 */  j          .Llevel_30_8006EA28
    /* 1F2C9D0 8006EC34 00000000 */   nop
  .Llevel_30_8006EC38:
    /* 1F2C9D4 8006EC38 3DB0000C */  jal        func_8002C0F4
    /* 1F2C9D8 8006EC3C 00000000 */   nop
    /* 1F2C9DC 8006EC40 22B3000C */  jal        func_8002CC88
    /* 1F2C9E0 8006EC44 00000000 */   nop
    /* 1F2C9E4 8006EC48 EFAF000C */  jal        func_8002BFBC
    /* 1F2C9E8 8006EC4C 00000000 */   nop
    /* 1F2C9EC 8006EC50 0780023C */  lui        $v0, %hi(D_8006A0F8)
    /* 1F2C9F0 8006EC54 F8A04290 */  lbu        $v0, %lo(D_8006A0F8)($v0)
    /* 1F2C9F4 8006EC58 00000000 */  nop
    /* 1F2C9F8 8006EC5C 62004010 */  beqz       $v0, .Llevel_30_8006EDE8
    /* 1F2C9FC 8006EC60 00000000 */   nop
    /* 1F2CA00 8006EC64 0780043C */  lui        $a0, %hi(D_80069FF0)
    /* 1F2CA04 8006EC68 F09F848C */  lw         $a0, %lo(D_80069FF0)($a0)
    /* 1F2CA08 8006EC6C 0780053C */  lui        $a1, %hi(D_80069FF4)
    /* 1F2CA0C 8006EC70 F49FA58C */  lw         $a1, %lo(D_80069FF4)($a1)
    /* 1F2CA10 8006EC74 2CE6000C */  jal        func_800398B0
    /* 1F2CA14 8006EC78 00000000 */   nop
    /* 1F2CA18 8006EC7C 0780043C */  lui        $a0, %hi(D_8006A0EC)
    /* 1F2CA1C 8006EC80 ECA0848C */  lw         $a0, %lo(D_8006A0EC)($a0)
    /* 1F2CA20 8006EC84 0780033C */  lui        $v1, %hi(D_8006A260)
    /* 1F2CA24 8006EC88 60A2638C */  lw         $v1, %lo(D_8006A260)($v1)
    /* 1F2CA28 8006EC8C 23200400 */  negu       $a0, $a0
    /* 1F2CA2C 8006EC90 23208200 */  subu       $a0, $a0, $v0
    /* 1F2CA30 8006EC94 0780023C */  lui        $v0, %hi(D_8006A140)
    /* 1F2CA34 8006EC98 40A1428C */  lw         $v0, %lo(D_8006A140)($v0)
    /* 1F2CA38 8006EC9C 23186400 */  subu       $v1, $v1, $a0
    /* 1F2CA3C 8006ECA0 0780013C */  lui        $at, %hi(D_8006A018)
    /* 1F2CA40 8006ECA4 18A024AC */  sw         $a0, %lo(D_8006A018)($at)
    /* 1F2CA44 8006ECA8 83110200 */  sra        $v0, $v0, 6
    /* 1F2CA48 8006ECAC 23186200 */  subu       $v1, $v1, $v0
    /* 1F2CA4C 8006ECB0 0780013C */  lui        $at, %hi(D_80069FF8)
    /* 1F2CA50 8006ECB4 F89F23AC */  sw         $v1, %lo(D_80069FF8)($at)
    /* 1F2CA54 8006ECB8 7ABB0108 */  j          .Llevel_30_8006EDE8
    /* 1F2CA58 8006ECBC 00000000 */   nop
  .Llevel_30_8006ECC0:
    /* 1F2CA5C 8006ECC0 3DB0000C */  jal        func_8002C0F4
    /* 1F2CA60 8006ECC4 00000000 */   nop
    /* 1F2CA64 8006ECC8 22B3000C */  jal        func_8002CC88
    /* 1F2CA68 8006ECCC 00000000 */   nop
    /* 1F2CA6C 8006ECD0 81AF000C */  jal        func_8002BE04
    /* 1F2CA70 8006ECD4 00000000 */   nop
    /* 1F2CA74 8006ECD8 3EB4000C */  jal        func_8002D0F8
    /* 1F2CA78 8006ECDC 00000000 */   nop
    /* 1F2CA7C 8006ECE0 8ABA0108 */  j          .Llevel_30_8006EA28
    /* 1F2CA80 8006ECE4 00000000 */   nop
  .Llevel_30_8006ECE8:
    /* 1F2CA84 8006ECE8 3DB0000C */  jal        func_8002C0F4
    /* 1F2CA88 8006ECEC 00000000 */   nop
    /* 1F2CA8C 8006ECF0 22B3000C */  jal        func_8002CC88
    /* 1F2CA90 8006ECF4 00000000 */   nop
    /* 1F2CA94 8006ECF8 81AF000C */  jal        func_8002BE04
    /* 1F2CA98 8006ECFC 00000000 */   nop
    /* 1F2CA9C 8006ED00 3EB4000C */  jal        func_8002D0F8
    /* 1F2CAA0 8006ED04 00000000 */   nop
    /* 1F2CAA4 8006ED08 AA2A033C */  lui        $v1, (0x2AAAAAAB >> 16)
    /* 1F2CAA8 8006ED0C 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 1F2CAAC 8006ED10 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 1F2CAB0 8006ED14 ABAA6334 */  ori        $v1, $v1, (0x2AAAAAAB & 0xFFFF)
    /* 1F2CAB4 8006ED18 80100200 */  sll        $v0, $v0, 2
    /* 1F2CAB8 8006ED1C 02004104 */  bgez       $v0, .Llevel_30_8006ED28
    /* 1F2CABC 8006ED20 00000000 */   nop
    /* 1F2CAC0 8006ED24 23100200 */  negu       $v0, $v0
  .Llevel_30_8006ED28:
    /* 1F2CAC4 8006ED28 00034224 */  addiu      $v0, $v0, 0x300
    /* 1F2CAC8 8006ED2C 18004300 */  mult       $v0, $v1
    /* 1F2CACC 8006ED30 0780013C */  lui        $at, %hi(D_8006A018)
    /* 1F2CAD0 8006ED34 18A020AC */  sw         $zero, %lo(D_8006A018)($at)
    /* 1F2CAD4 8006ED38 C3170200 */  sra        $v0, $v0, 31
    /* 1F2CAD8 8006ED3C 10380000 */  mfhi       $a3
    /* 1F2CADC 8006ED40 031A0700 */  sra        $v1, $a3, 8
    /* 1F2CAE0 8006ED44 23186200 */  subu       $v1, $v1, $v0
    /* 1F2CAE4 8006ED48 00210300 */  sll        $a0, $v1, 4
    /* 1F2CAE8 8006ED4C 10008228 */  slti       $v0, $a0, 0x10
    /* 1F2CAEC 8006ED50 20004010 */  beqz       $v0, .Llevel_30_8006EDD4
    /* 1F2CAF0 8006ED54 41008228 */   slti      $v0, $a0, 0x41
    /* 1F2CAF4 8006ED58 74BB0108 */  j          .Llevel_30_8006EDD0
    /* 1F2CAF8 8006ED5C 10000424 */   addiu     $a0, $zero, 0x10
  .Llevel_30_8006ED60:
    /* 1F2CAFC 8006ED60 3DB0000C */  jal        func_8002C0F4
    /* 1F2CB00 8006ED64 00000000 */   nop
    /* 1F2CB04 8006ED68 22B3000C */  jal        func_8002CC88
    /* 1F2CB08 8006ED6C 00000000 */   nop
    /* 1F2CB0C 8006ED70 81AF000C */  jal        func_8002BE04
    /* 1F2CB10 8006ED74 00000000 */   nop
    /* 1F2CB14 8006ED78 3EB4000C */  jal        func_8002D0F8
    /* 1F2CB18 8006ED7C 00000000 */   nop
    /* 1F2CB1C 8006ED80 0780043C */  lui        $a0, %hi(D_8006A018)
    /* 1F2CB20 8006ED84 18A08424 */  addiu      $a0, $a0, %lo(D_8006A018)
    /* 1F2CB24 8006ED88 000080AC */  sw         $zero, 0x0($a0)
    /* 1F2CB28 8006ED8C 78008424 */  addiu      $a0, $a0, 0x78
    /* 1F2CB2C 8006ED90 886E000C */  jal        func_8001BA20
    /* 1F2CB30 8006ED94 21280000 */   addu      $a1, $zero, $zero
    /* 1F2CB34 8006ED98 AA2A033C */  lui        $v1, (0x2AAAAAAB >> 16)
    /* 1F2CB38 8006ED9C ABAA6334 */  ori        $v1, $v1, (0x2AAAAAAB & 0xFFFF)
    /* 1F2CB3C 8006EDA0 80100200 */  sll        $v0, $v0, 2
    /* 1F2CB40 8006EDA4 00034224 */  addiu      $v0, $v0, 0x300
    /* 1F2CB44 8006EDA8 18004300 */  mult       $v0, $v1
    /* 1F2CB48 8006EDAC C3170200 */  sra        $v0, $v0, 31
    /* 1F2CB4C 8006EDB0 10380000 */  mfhi       $a3
    /* 1F2CB50 8006EDB4 031A0700 */  sra        $v1, $a3, 8
    /* 1F2CB54 8006EDB8 23186200 */  subu       $v1, $v1, $v0
    /* 1F2CB58 8006EDBC 00210300 */  sll        $a0, $v1, 4
    /* 1F2CB5C 8006EDC0 08008228 */  slti       $v0, $a0, 0x8
    /* 1F2CB60 8006EDC4 03004010 */  beqz       $v0, .Llevel_30_8006EDD4
    /* 1F2CB64 8006EDC8 41008228 */   slti      $v0, $a0, 0x41
    /* 1F2CB68 8006EDCC 08000424 */  addiu      $a0, $zero, 0x8
  .Llevel_30_8006EDD0:
    /* 1F2CB6C 8006EDD0 41008228 */  slti       $v0, $a0, 0x41
  .Llevel_30_8006EDD4:
    /* 1F2CB70 8006EDD4 02004014 */  bnez       $v0, .Llevel_30_8006EDE0
    /* 1F2CB74 8006EDD8 00000000 */   nop
    /* 1F2CB78 8006EDDC 40000424 */  addiu      $a0, $zero, 0x40
  .Llevel_30_8006EDE0:
    /* 1F2CB7C 8006EDE0 FEB8000C */  jal        func_8002E3F8
    /* 1F2CB80 8006EDE4 00000000 */   nop
  .Llevel_30_8006EDE8:
    /* 1F2CB84 8006EDE8 1400BF8F */  lw         $ra, 0x14($sp)
    /* 1F2CB88 8006EDEC 1000B08F */  lw         $s0, 0x10($sp)
    /* 1F2CB8C 8006EDF0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 1F2CB90 8006EDF4 0800E003 */  jr         $ra
    /* 1F2CB94 8006EDF8 00000000 */   nop
endlabel func_level_30_8006E9D4
