.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_13_8006D268

dlabel jtbl_level_13_8006D268
    /* 1339804 8006D268 D4E00680 */ .word .Llevel_13_8006E0D4
    /* 1339808 8006D26C B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 133980C 8006D270 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339810 8006D274 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339814 8006D278 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339818 8006D27C B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 133981C 8006D280 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339820 8006D284 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339824 8006D288 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339828 8006D28C 04E30680 */ .word .Llevel_13_8006E304
    /* 133982C 8006D290 84E00680 */ .word .Llevel_13_8006E084
    /* 1339830 8006D294 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339834 8006D298 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339838 8006D29C B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 133983C 8006D2A0 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339840 8006D2A4 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339844 8006D2A8 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339848 8006D2AC 1CE70680 */ .word .Llevel_13_8006E71C
    /* 133984C 8006D2B0 8CE70680 */ .word .Llevel_13_8006E78C
    /* 1339850 8006D2B4 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339854 8006D2B8 24E60680 */ .word .Llevel_13_8006E624
    /* 1339858 8006D2BC B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 133985C 8006D2C0 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339860 8006D2C4 C4E80680 */ .word .Llevel_13_8006E8C4
    /* 1339864 8006D2C8 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339868 8006D2CC B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 133986C 8006D2D0 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339870 8006D2D4 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339874 8006D2D8 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339878 8006D2DC B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 133987C 8006D2E0 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339880 8006D2E4 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339884 8006D2E8 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339888 8006D2EC B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 133988C 8006D2F0 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339890 8006D2F4 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339894 8006D2F8 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 1339898 8006D2FC B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 133989C 8006D300 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 13398A0 8006D304 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 13398A4 8006D308 58EA0680 */ .word .Llevel_13_8006EA58
    /* 13398A8 8006D30C B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 13398AC 8006D310 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 13398B0 8006D314 B0EB0680 */ .word .Llevel_13_8006EBB0
    /* 13398B4 8006D318 84E00680 */ .word .Llevel_13_8006E084
    /* 13398B8 8006D31C 84E00680 */ .word .Llevel_13_8006E084
enddlabel jtbl_level_13_8006D268


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_13_8006E018, 0xBB8

glabel func_level_13_8006E018
    /* 133A5B4 8006E018 00110400 */  sll        $v0, $a0, 4
    /* 133A5B8 8006E01C 0780033C */  lui        $v1, %hi(D_800683B0)
    /* 133A5BC 8006E020 B0836324 */  addiu      $v1, $v1, %lo(D_800683B0)
    /* 133A5C0 8006E024 21104300 */  addu       $v0, $v0, $v1
    /* 133A5C4 8006E028 0680013C */  lui        $at, %hi(D_80066F38)
    /* 133A5C8 8006E02C 386F22AC */  sw         $v0, %lo(D_80066F38)($at)
    /* 133A5CC 8006E030 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 133A5D0 8006E034 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 133A5D4 8006E038 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 133A5D8 8006E03C 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 133A5DC 8006E040 70FFBD27 */  addiu      $sp, $sp, -0x90
    /* 133A5E0 8006E044 8800BFAF */  sw         $ra, 0x88($sp)
    /* 133A5E4 8006E048 8400B3AF */  sw         $s3, 0x84($sp)
    /* 133A5E8 8006E04C 8000B2AF */  sw         $s2, 0x80($sp)
    /* 133A5EC 8006E050 7C00B1AF */  sw         $s1, 0x7C($sp)
    /* 133A5F0 8006E054 21984400 */  addu       $s3, $v0, $a0
    /* 133A5F4 8006E058 F7FF6324 */  addiu      $v1, $v1, -0x9
    /* 133A5F8 8006E05C 2E00622C */  sltiu      $v0, $v1, 0x2E
    /* 133A5FC 8006E060 D3024010 */  beqz       $v0, .Llevel_13_8006EBB0
    /* 133A600 8006E064 7800B0AF */   sw        $s0, 0x78($sp)
    /* 133A604 8006E068 80100300 */  sll        $v0, $v1, 2
    /* 133A608 8006E06C 0780013C */  lui        $at, %hi(jtbl_level_13_8006D268)
    /* 133A60C 8006E070 21082200 */  addu       $at, $at, $v0
    /* 133A610 8006E074 68D2228C */  lw         $v0, %lo(jtbl_level_13_8006D268)($at)
    /* 133A614 8006E078 00000000 */  nop
    /* 133A618 8006E07C 08004000 */  jr         $v0
    /* 133A61C 8006E080 00000000 */   nop
  .Llevel_13_8006E084:
    /* 133A620 8006E084 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 133A624 8006E088 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 133A628 8006E08C 686F000C */  jal        func_8001BDA0
    /* 133A62C 8006E090 21200002 */   addu      $a0, $s0, $zero
    /* 133A630 8006E094 686F000C */  jal        func_8001BDA0
    /* 133A634 8006E098 0C000426 */   addiu     $a0, $s0, 0xC
    /* 133A638 8006E09C 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 133A63C 8006E0A0 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 133A640 8006E0A4 07000224 */  addiu      $v0, $zero, 0x7
    /* 133A644 8006E0A8 C1026210 */  beq        $v1, $v0, .Llevel_13_8006EBB0
    /* 133A648 8006E0AC 00000000 */   nop
    /* 133A64C 8006E0B0 DBAC000C */  jal        func_8002B36C
    /* 133A650 8006E0B4 00120424 */   addiu     $a0, $zero, 0x1200
    /* 133A654 8006E0B8 1AAF000C */  jal        func_8002BC68
    /* 133A658 8006E0BC 00000000 */   nop
    /* 133A65C 8006E0C0 5A000424 */  addiu      $a0, $zero, 0x5A
    /* 133A660 8006E0C4 C9AE000C */  jal        func_8002BB24
    /* 133A664 8006E0C8 10000524 */   addiu     $a1, $zero, 0x10
    /* 133A668 8006E0CC ECBA0108 */  j          .Llevel_13_8006EBB0
    /* 133A66C 8006E0D0 00000000 */   nop
  .Llevel_13_8006E0D4:
    /* 133A670 8006E0D4 0680033C */  lui        $v1, %hi(D_80066F90)
    /* 133A674 8006E0D8 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* 133A678 8006E0DC 3E000224 */  addiu      $v0, $zero, 0x3E
    /* 133A67C 8006E0E0 0B006214 */  bne        $v1, $v0, .Llevel_13_8006E110
    /* 133A680 8006E0E4 00000000 */   nop
    /* 133A684 8006E0E8 DBAC000C */  jal        func_8002B36C
    /* 133A688 8006E0EC 000F0424 */   addiu     $a0, $zero, 0xF00
    /* 133A68C 8006E0F0 000F0224 */  addiu      $v0, $zero, 0xF00
    /* 133A690 8006E0F4 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 133A694 8006E0F8 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 133A698 8006E0FC 19000424 */  addiu      $a0, $zero, 0x19
    /* 133A69C 8006E100 C9AE000C */  jal        func_8002BB24
    /* 133A6A0 8006E104 05000524 */   addiu     $a1, $zero, 0x5
    /* 133A6A4 8006E108 A0B80108 */  j          .Llevel_13_8006E280
    /* 133A6A8 8006E10C 40010424 */   addiu     $a0, $zero, 0x140
  .Llevel_13_8006E110:
    /* 133A6AC 8006E110 0780023C */  lui        $v0, %hi(D_8006839D)
    /* 133A6B0 8006E114 9D834290 */  lbu        $v0, %lo(D_8006839D)($v0)
    /* 133A6B4 8006E118 00000000 */  nop
    /* 133A6B8 8006E11C 16004010 */  beqz       $v0, .Llevel_13_8006E178
    /* 133A6BC 8006E120 1000A427 */   addiu     $a0, $sp, 0x10
    /* 133A6C0 8006E124 0780023C */  lui        $v0, %hi(D_8006A0F6)
    /* 133A6C4 8006E128 F6A04290 */  lbu        $v0, %lo(D_8006A0F6)($v0)
    /* 133A6C8 8006E12C 00000000 */  nop
    /* 133A6CC 8006E130 11004010 */  beqz       $v0, .Llevel_13_8006E178
    /* 133A6D0 8006E134 00000000 */   nop
    /* 133A6D4 8006E138 0780043C */  lui        $a0, %hi(D_8006A0D0)
    /* 133A6D8 8006E13C D0A0848C */  lw         $a0, %lo(D_8006A0D0)($a0)
    /* 133A6DC 8006E140 0780053C */  lui        $a1, %hi(D_8006A0D4)
    /* 133A6E0 8006E144 D4A0A58C */  lw         $a1, %lo(D_8006A0D4)($a1)
    /* 133A6E4 8006E148 2E6D000C */  jal        func_8001B4B8
    /* 133A6E8 8006E14C 21300000 */   addu      $a2, $zero, $zero
    /* 133A6EC 8006E150 0780033C */  lui        $v1, %hi(D_8006A05C)
    /* 133A6F0 8006E154 5CA0638C */  lw         $v1, %lo(D_8006A05C)($v1)
    /* 133A6F4 8006E158 00000000 */  nop
    /* 133A6F8 8006E15C 23104300 */  subu       $v0, $v0, $v1
    /* 133A6FC 8006E160 FF0F4430 */  andi       $a0, $v0, 0xFFF
    /* 133A700 8006E164 01088228 */  slti       $v0, $a0, 0x801
    /* 133A704 8006E168 0C004014 */  bnez       $v0, .Llevel_13_8006E19C
    /* 133A708 8006E16C 00000000 */   nop
    /* 133A70C 8006E170 67B80108 */  j          .Llevel_13_8006E19C
    /* 133A710 8006E174 00F08424 */   addiu     $a0, $a0, -0x1000
  .Llevel_13_8006E178:
    /* 133A714 8006E178 39AD000C */  jal        func_8002B4E4
    /* 133A718 8006E17C 01000524 */   addiu     $a1, $zero, 0x1
    /* 133A71C 8006E180 1000A38F */  lw         $v1, 0x10($sp)
    /* 133A720 8006E184 00000000 */  nop
    /* 133A724 8006E188 40100300 */  sll        $v0, $v1, 1
    /* 133A728 8006E18C 21104300 */  addu       $v0, $v0, $v1
    /* 133A72C 8006E190 C0100200 */  sll        $v0, $v0, 3
    /* 133A730 8006E194 21104300 */  addu       $v0, $v0, $v1
    /* 133A734 8006E198 C3210200 */  sra        $a0, $v0, 7
  .Llevel_13_8006E19C:
    /* 133A738 8006E19C 05008014 */  bnez       $a0, .Llevel_13_8006E1B4
    /* 133A73C 8006E1A0 00000000 */   nop
    /* 133A740 8006E1A4 0780013C */  lui        $at, %hi(D_8006A0A0)
    /* 133A744 8006E1A8 A0A020AC */  sw         $zero, %lo(D_8006A0A0)($at)
    /* 133A748 8006E1AC 7EB80108 */  j          .Llevel_13_8006E1F8
    /* 133A74C 8006E1B0 00000000 */   nop
  .Llevel_13_8006E1B4:
    /* 133A750 8006E1B4 09008104 */  bgez       $a0, .Llevel_13_8006E1DC
    /* 133A754 8006E1B8 00000000 */   nop
    /* 133A758 8006E1BC 0780033C */  lui        $v1, %hi(D_8006A0A0)
    /* 133A75C 8006E1C0 A0A06324 */  addiu      $v1, $v1, %lo(D_8006A0A0)
    /* 133A760 8006E1C4 0000628C */  lw         $v0, 0x0($v1)
    /* 133A764 8006E1C8 00000000 */  nop
    /* 133A768 8006E1CC 0A004018 */  blez       $v0, .Llevel_13_8006E1F8
    /* 133A76C 8006E1D0 00000000 */   nop
    /* 133A770 8006E1D4 7EB80108 */  j          .Llevel_13_8006E1F8
    /* 133A774 8006E1D8 000060AC */   sw        $zero, 0x0($v1)
  .Llevel_13_8006E1DC:
    /* 133A778 8006E1DC 0780033C */  lui        $v1, %hi(D_8006A0A0)
    /* 133A77C 8006E1E0 A0A06324 */  addiu      $v1, $v1, %lo(D_8006A0A0)
    /* 133A780 8006E1E4 0000628C */  lw         $v0, 0x0($v1)
    /* 133A784 8006E1E8 00000000 */  nop
    /* 133A788 8006E1EC 02004104 */  bgez       $v0, .Llevel_13_8006E1F8
    /* 133A78C 8006E1F0 00000000 */   nop
    /* 133A790 8006E1F4 000060AC */  sw         $zero, 0x0($v1)
  .Llevel_13_8006E1F8:
    /* 133A794 8006E1F8 0780053C */  lui        $a1, %hi(D_8006A0A0)
    /* 133A798 8006E1FC A0A0A524 */  addiu      $a1, $a1, %lo(D_8006A0A0)
    /* 133A79C 8006E200 0000A38C */  lw         $v1, 0x0($a1)
    /* 133A7A0 8006E204 00000000 */  nop
    /* 133A7A4 8006E208 2A106400 */  slt        $v0, $v1, $a0
    /* 133A7A8 8006E20C 04004010 */  beqz       $v0, .Llevel_13_8006E220
    /* 133A7AC 8006E210 05006224 */   addiu     $v0, $v1, 0x5
    /* 133A7B0 8006E214 0000A2AC */  sw         $v0, 0x0($a1)
    /* 133A7B4 8006E218 8BB80108 */  j          .Llevel_13_8006E22C
    /* 133A7B8 8006E21C 2A108200 */   slt       $v0, $a0, $v0
  .Llevel_13_8006E220:
    /* 133A7BC 8006E220 FBFF6224 */  addiu      $v0, $v1, -0x5
    /* 133A7C0 8006E224 0000A2AC */  sw         $v0, 0x0($a1)
    /* 133A7C4 8006E228 2A104400 */  slt        $v0, $v0, $a0
  .Llevel_13_8006E22C:
    /* 133A7C8 8006E22C 02004010 */  beqz       $v0, .Llevel_13_8006E238
    /* 133A7CC 8006E230 00000000 */   nop
    /* 133A7D0 8006E234 0000A4AC */  sw         $a0, 0x0($a1)
  .Llevel_13_8006E238:
    /* 133A7D4 8006E238 0780043C */  lui        $a0, %hi(D_8006A0A0)
    /* 133A7D8 8006E23C A0A0848C */  lw         $a0, %lo(D_8006A0A0)($a0)
    /* 133A7DC 8006E240 68AE000C */  jal        func_8002B9A0
    /* 133A7E0 8006E244 00000000 */   nop
    /* 133A7E4 8006E248 1400A38F */  lw         $v1, 0x14($sp)
    /* 133A7E8 8006E24C 00000000 */  nop
    /* 133A7EC 8006E250 04006104 */  bgez       $v1, .Llevel_13_8006E264
    /* 133A7F0 8006E254 00110300 */   sll       $v0, $v1, 4
    /* 133A7F4 8006E258 23104300 */  subu       $v0, $v0, $v1
    /* 133A7F8 8006E25C 9BB80108 */  j          .Llevel_13_8006E26C
    /* 133A7FC 8006E260 C0110200 */   sll       $v0, $v0, 7
  .Llevel_13_8006E264:
    /* 133A800 8006E264 23104300 */  subu       $v0, $v0, $v1
    /* 133A804 8006E268 80110200 */  sll        $v0, $v0, 6
  .Llevel_13_8006E26C:
    /* 133A808 8006E26C C3110200 */  sra        $v0, $v0, 7
    /* 133A80C 8006E270 000F4224 */  addiu      $v0, $v0, 0xF00
    /* 133A810 8006E274 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 133A814 8006E278 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 133A818 8006E27C 40010424 */  addiu      $a0, $zero, 0x140
  .Llevel_13_8006E280:
    /* 133A81C 8006E280 5CAF000C */  jal        func_8002BD70
    /* 133A820 8006E284 C0000524 */   addiu     $a1, $zero, 0xC0
    /* 133A824 8006E288 0780043C */  lui        $a0, %hi(D_8006A0F9)
    /* 133A828 8006E28C F9A08424 */  addiu      $a0, $a0, %lo(D_8006A0F9)
    /* 133A82C 8006E290 00008290 */  lbu        $v0, 0x0($a0)
    /* 133A830 8006E294 00000000 */  nop
    /* 133A834 8006E298 05004010 */  beqz       $v0, .Llevel_13_8006E2B0
    /* 133A838 8006E29C 00000000 */   nop
    /* 133A83C 8006E2A0 686F000C */  jal        func_8001BDA0
    /* 133A840 8006E2A4 8BFF8424 */   addiu     $a0, $a0, -0x75
    /* 133A844 8006E2A8 B0B80108 */  j          .Llevel_13_8006E2C0
    /* 133A848 8006E2AC 00000000 */   nop
  .Llevel_13_8006E2B0:
    /* 133A84C 8006E2B0 6FAF000C */  jal        func_8002BDBC
    /* 133A850 8006E2B4 00000000 */   nop
    /* 133A854 8006E2B8 0EB0000C */  jal        func_8002C038
    /* 133A858 8006E2BC 00000000 */   nop
  .Llevel_13_8006E2C0:
    /* 133A85C 8006E2C0 0780103C */  lui        $s0, %hi(D_8006A084)
    /* 133A860 8006E2C4 84A01026 */  addiu      $s0, $s0, %lo(D_8006A084)
    /* 133A864 8006E2C8 21200002 */  addu       $a0, $s0, $zero
    /* 133A868 8006E2CC 6C6F000C */  jal        func_8001BDB0
    /* 133A86C 8006E2D0 F4FF0526 */   addiu     $a1, $s0, -0xC
    /* 133A870 8006E2D4 0780023C */  lui        $v0, %hi(D_8006A0F4)
    /* 133A874 8006E2D8 F4A04290 */  lbu        $v0, %lo(D_8006A0F4)($v0)
    /* 133A878 8006E2DC 00000000 */  nop
    /* 133A87C 8006E2E0 26024014 */  bnez       $v0, .Llevel_13_8006EB7C
    /* 133A880 8006E2E4 00000000 */   nop
    /* 133A884 8006E2E8 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 133A888 8006E2EC B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 133A88C 8006E2F0 00000000 */  nop
    /* 133A890 8006E2F4 21024014 */  bnez       $v0, .Llevel_13_8006EB7C
    /* 133A894 8006E2F8 21200002 */   addu      $a0, $s0, $zero
    /* 133A898 8006E2FC E8BA0108 */  j          .Llevel_13_8006EBA0
    /* 133A89C 8006E300 21288000 */   addu      $a1, $a0, $zero
  .Llevel_13_8006E304:
    /* 133A8A0 8006E304 0780123C */  lui        $s2, %hi(D_80069FF8)
    /* 133A8A4 8006E308 F89F5226 */  addiu      $s2, $s2, %lo(D_80069FF8)
    /* 133A8A8 8006E30C 0000438E */  lw         $v1, 0x0($s2)
    /* 133A8AC 8006E310 4401428E */  lw         $v0, 0x144($s2)
    /* 133A8B0 8006E314 00000000 */  nop
    /* 133A8B4 8006E318 23206200 */  subu       $a0, $v1, $v0
    /* 133A8B8 8006E31C 00048228 */  slti       $v0, $a0, 0x400
    /* 133A8BC 8006E320 29004010 */  beqz       $v0, .Llevel_13_8006E3C8
    /* 133A8C0 8006E324 00000000 */   nop
    /* 133A8C4 8006E328 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 133A8C8 8006E32C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 133A8CC 8006E330 00000000 */  nop
    /* 133A8D0 8006E334 80004224 */  addiu      $v0, $v0, 0x80
    /* 133A8D4 8006E338 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 133A8D8 8006E33C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 133A8DC 8006E340 C1124228 */  slti       $v0, $v0, 0x12C1
    /* 133A8E0 8006E344 04004014 */  bnez       $v0, .Llevel_13_8006E358
    /* 133A8E4 8006E348 18008400 */   mult      $a0, $a0
    /* 133A8E8 8006E34C C0120224 */  addiu      $v0, $zero, 0x12C0
    /* 133A8EC 8006E350 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 133A8F0 8006E354 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_13_8006E358:
    /* 133A8F4 8006E358 1800B127 */  addiu      $s1, $sp, 0x18
    /* 133A8F8 8006E35C 21202002 */  addu       $a0, $s1, $zero
    /* 133A8FC 8006E360 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 133A900 8006E364 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 133A904 8006E368 0780033C */  lui        $v1, %hi(D_8006A140)
    /* 133A908 8006E36C 40A1638C */  lw         $v1, %lo(D_8006A140)($v1)
    /* 133A90C 8006E370 12480000 */  mflo       $t1
    /* 133A910 8006E374 C3120900 */  sra        $v0, $t1, 11
    /* 133A914 8006E378 21804300 */  addu       $s0, $v0, $v1
    /* 133A918 8006E37C 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 133A91C 8006E380 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 133A920 8006E384 6C6F000C */  jal        func_8001BDB0
    /* 133A924 8006E388 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 133A928 8006E38C 21202002 */  addu       $a0, $s1, $zero
    /* 133A92C 8006E390 21282002 */  addu       $a1, $s1, $zero
    /* 133A930 8006E394 806F000C */  jal        func_8001BE00
    /* 133A934 8006E398 F8FF4626 */   addiu     $a2, $s2, -0x8
    /* 133A938 8006E39C 21202002 */  addu       $a0, $s1, $zero
    /* 133A93C 8006E3A0 21280000 */  addu       $a1, $zero, $zero
    /* 133A940 8006E3A4 886E000C */  jal        func_8001BA20
    /* 133A944 8006E3A8 2000A0AF */   sw        $zero, 0x20($sp)
    /* 133A948 8006E3AC 21404000 */  addu       $t0, $v0, $zero
    /* 133A94C 8006E3B0 01040229 */  slti       $v0, $t0, 0x401
    /* 133A950 8006E3B4 93004014 */  bnez       $v0, .Llevel_13_8006E604
    /* 133A954 8006E3B8 21202002 */   addu      $a0, $s1, $zero
    /* 133A958 8006E3BC 21280001 */  addu       $a1, $t0, $zero
    /* 133A95C 8006E3C0 7FB90108 */  j          .Llevel_13_8006E5FC
    /* 133A960 8006E3C4 00040624 */   addiu     $a2, $zero, 0x400
  .Llevel_13_8006E3C8:
    /* 133A964 8006E3C8 0780053C */  lui        $a1, %hi(D_8006A144)
    /* 133A968 8006E3CC 44A1A58C */  lw         $a1, %lo(D_8006A144)($a1)
    /* 133A96C 8006E3D0 00000000 */  nop
    /* 133A970 8006E3D4 23106500 */  subu       $v0, $v1, $a1
    /* 133A974 8006E3D8 00FC4228 */  slti       $v0, $v0, -0x400
    /* 133A978 8006E3DC 4A004010 */  beqz       $v0, .Llevel_13_8006E508
    /* 133A97C 8006E3E0 2340A300 */   subu      $t0, $a1, $v1
    /* 133A980 8006E3E4 0780023C */  lui        $v0, %hi(D_8006A044)
    /* 133A984 8006E3E8 44A0428C */  lw         $v0, %lo(D_8006A044)($v0)
    /* 133A988 8006E3EC 00000000 */  nop
    /* 133A98C 8006E3F0 08004014 */  bnez       $v0, .Llevel_13_8006E414
    /* 133A990 8006E3F4 01000324 */   addiu     $v1, $zero, 0x1
    /* 133A994 8006E3F8 0780023C */  lui        $v0, %hi(D_8006A140)
    /* 133A998 8006E3FC 40A1428C */  lw         $v0, %lo(D_8006A140)($v0)
    /* 133A99C 8006E400 0780013C */  lui        $at, %hi(D_8006A044)
    /* 133A9A0 8006E404 44A023AC */  sw         $v1, %lo(D_8006A044)($at)
    /* 133A9A4 8006E408 00024224 */  addiu      $v0, $v0, 0x200
    /* 133A9A8 8006E40C 0780013C */  lui        $at, %hi(D_8006A140)
    /* 133A9AC 8006E410 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
  .Llevel_13_8006E414:
    /* 133A9B0 8006E414 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 133A9B4 8006E418 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 133A9B8 8006E41C 00000000 */  nop
    /* 133A9BC 8006E420 80004224 */  addiu      $v0, $v0, 0x80
    /* 133A9C0 8006E424 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 133A9C4 8006E428 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 133A9C8 8006E42C C1124228 */  slti       $v0, $v0, 0x12C1
    /* 133A9CC 8006E430 03004014 */  bnez       $v0, .Llevel_13_8006E440
    /* 133A9D0 8006E434 C0120224 */   addiu     $v0, $zero, 0x12C0
    /* 133A9D4 8006E438 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 133A9D8 8006E43C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_13_8006E440:
    /* 133A9DC 8006E440 0780023C */  lui        $v0, %hi(D_8006A148)
    /* 133A9E0 8006E444 48A1428C */  lw         $v0, %lo(D_8006A148)($v0)
    /* 133A9E4 8006E448 00FC8824 */  addiu      $t0, $a0, -0x400
    /* 133A9E8 8006E44C 18004800 */  mult       $v0, $t0
    /* 133A9EC 8006E450 12180000 */  mflo       $v1
    /* 133A9F0 8006E454 0780023C */  lui        $v0, %hi(D_8006A14C)
    /* 133A9F4 8006E458 4CA1428C */  lw         $v0, %lo(D_8006A14C)($v0)
    /* 133A9F8 8006E45C 00000000 */  nop
    /* 133A9FC 8006E460 1A006200 */  div        $zero, $v1, $v0
    /* 133AA00 8006E464 02004014 */  bnez       $v0, .Llevel_13_8006E470
    /* 133AA04 8006E468 00000000 */   nop
    /* 133AA08 8006E46C 0D000700 */  break      7
  .Llevel_13_8006E470:
    /* 133AA0C 8006E470 FFFF0124 */  addiu      $at, $zero, -0x1
    /* 133AA10 8006E474 04004114 */  bne        $v0, $at, .Llevel_13_8006E488
    /* 133AA14 8006E478 0080013C */   lui       $at, (0x80000000 >> 16)
    /* 133AA18 8006E47C 02006114 */  bne        $v1, $at, .Llevel_13_8006E488
    /* 133AA1C 8006E480 00000000 */   nop
    /* 133AA20 8006E484 0D000600 */  break      6
  .Llevel_13_8006E488:
    /* 133AA24 8006E488 12100000 */  mflo       $v0
    /* 133AA28 8006E48C 1800B127 */  addiu      $s1, $sp, 0x18
    /* 133AA2C 8006E490 21202002 */  addu       $a0, $s1, $zero
    /* 133AA30 8006E494 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 133AA34 8006E498 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 133AA38 8006E49C 0780033C */  lui        $v1, %hi(D_8006A140)
    /* 133AA3C 8006E4A0 40A1638C */  lw         $v1, %lo(D_8006A140)($v1)
    /* 133AA40 8006E4A4 00000000 */  nop
    /* 133AA44 8006E4A8 21806200 */  addu       $s0, $v1, $v0
    /* 133AA48 8006E4AC 80120800 */  sll        $v0, $t0, 10
    /* 133AA4C 8006E4B0 83120200 */  sra        $v0, $v0, 10
    /* 133AA50 8006E4B4 21100202 */  addu       $v0, $s0, $v0
    /* 133AA54 8006E4B8 FF0F5030 */  andi       $s0, $v0, 0xFFF
    /* 133AA58 8006E4BC 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 133AA5C 8006E4C0 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 133AA60 8006E4C4 6C6F000C */  jal        func_8001BDB0
    /* 133AA64 8006E4C8 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 133AA68 8006E4CC 21202002 */  addu       $a0, $s1, $zero
    /* 133AA6C 8006E4D0 21282002 */  addu       $a1, $s1, $zero
    /* 133AA70 8006E4D4 806F000C */  jal        func_8001BE00
    /* 133AA74 8006E4D8 F8FF4626 */   addiu     $a2, $s2, -0x8
    /* 133AA78 8006E4DC 21202002 */  addu       $a0, $s1, $zero
    /* 133AA7C 8006E4E0 21280000 */  addu       $a1, $zero, $zero
    /* 133AA80 8006E4E4 886E000C */  jal        func_8001BA20
    /* 133AA84 8006E4E8 2000A0AF */   sw        $zero, 0x20($sp)
    /* 133AA88 8006E4EC 21404000 */  addu       $t0, $v0, $zero
    /* 133AA8C 8006E4F0 01040229 */  slti       $v0, $t0, 0x401
    /* 133AA90 8006E4F4 43004014 */  bnez       $v0, .Llevel_13_8006E604
    /* 133AA94 8006E4F8 21202002 */   addu      $a0, $s1, $zero
    /* 133AA98 8006E4FC 21280001 */  addu       $a1, $t0, $zero
    /* 133AA9C 8006E500 7FB90108 */  j          .Llevel_13_8006E5FC
    /* 133AAA0 8006E504 00040624 */   addiu     $a2, $zero, 0x400
  .Llevel_13_8006E508:
    /* 133AAA4 8006E508 80180800 */  sll        $v1, $t0, 2
    /* 133AAA8 8006E50C 21186800 */  addu       $v1, $v1, $t0
    /* 133AAAC 8006E510 00110300 */  sll        $v0, $v1, 4
    /* 133AAB0 8006E514 23104300 */  subu       $v0, $v0, $v1
    /* 133AAB4 8006E518 80110200 */  sll        $v0, $v0, 6
    /* 133AAB8 8006E51C 0780063C */  lui        $a2, %hi(D_8006A208)
    /* 133AABC 8006E520 08A2C68C */  lw         $a2, %lo(D_8006A208)($a2)
    /* 133AAC0 8006E524 83120200 */  sra        $v0, $v0, 10
    /* 133AAC4 8006E528 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 133AAC8 8006E52C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 133AACC 8006E530 4600C790 */  lbu        $a3, 0x46($a2)
    /* 133AAD0 8006E534 0780033C */  lui        $v1, %hi(D_8006A150)
    /* 133AAD4 8006E538 50A1638C */  lw         $v1, %lo(D_8006A150)($v1)
    /* 133AAD8 8006E53C 40100700 */  sll        $v0, $a3, 1
    /* 133AADC 8006E540 0680013C */  lui        $at, %hi(D_80061C58)
    /* 133AAE0 8006E544 21082200 */  addu       $at, $at, $v0
    /* 133AAE4 8006E548 581C2284 */  lh         $v0, %lo(D_80061C58)($at)
    /* 133AAE8 8006E54C 00046324 */  addiu      $v1, $v1, 0x400
    /* 133AAEC 8006E550 18006200 */  mult       $v1, $v0
    /* 133AAF0 8006E554 12500000 */  mflo       $t2
    /* 133AAF4 8006E558 00000000 */  nop
    /* 133AAF8 8006E55C 00000000 */  nop
    /* 133AAFC 8006E560 18000801 */  mult       $t0, $t0
    /* 133AB00 8006E564 03130A00 */  sra        $v0, $t2, 12
    /* 133AB04 8006E568 1800A2AF */  sw         $v0, 0x18($sp)
    /* 133AB08 8006E56C 4600C290 */  lbu        $v0, 0x46($a2)
    /* 133AB0C 8006E570 00000000 */  nop
    /* 133AB10 8006E574 40100200 */  sll        $v0, $v0, 1
    /* 133AB14 8006E578 12400000 */  mflo       $t0
    /* 133AB18 8006E57C 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 133AB1C 8006E580 21082200 */  addu       $at, $at, $v0
    /* 133AB20 8006E584 D81B2284 */  lh         $v0, %lo(D_80061BD8)($at)
    /* 133AB24 8006E588 00000000 */  nop
    /* 133AB28 8006E58C 18006200 */  mult       $v1, $v0
    /* 133AB2C 8006E590 1800B127 */  addiu      $s1, $sp, 0x18
    /* 133AB30 8006E594 21202002 */  addu       $a0, $s1, $zero
    /* 133AB34 8006E598 21282002 */  addu       $a1, $s1, $zero
    /* 133AB38 8006E59C 00390700 */  sll        $a3, $a3, 4
    /* 133AB3C 8006E5A0 0C00C624 */  addiu      $a2, $a2, 0xC
    /* 133AB40 8006E5A4 C3120800 */  sra        $v0, $t0, 11
    /* 133AB44 8006E5A8 2380E200 */  subu       $s0, $a3, $v0
    /* 133AB48 8006E5AC 12180000 */  mflo       $v1
    /* 133AB4C 8006E5B0 03130300 */  sra        $v0, $v1, 12
    /* 133AB50 8006E5B4 736F000C */  jal        func_8001BDCC
    /* 133AB54 8006E5B8 1C00A2AF */   sw        $v0, 0x1C($sp)
    /* 133AB58 8006E5BC 21202002 */  addu       $a0, $s1, $zero
    /* 133AB5C 8006E5C0 21282002 */  addu       $a1, $s1, $zero
    /* 133AB60 8006E5C4 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 133AB64 8006E5C8 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 133AB68 8006E5CC 806F000C */  jal        func_8001BE00
    /* 133AB6C 8006E5D0 F8FF4626 */   addiu     $a2, $s2, -0x8
    /* 133AB70 8006E5D4 21202002 */  addu       $a0, $s1, $zero
    /* 133AB74 8006E5D8 21280000 */  addu       $a1, $zero, $zero
    /* 133AB78 8006E5DC 886E000C */  jal        func_8001BA20
    /* 133AB7C 8006E5E0 2000A0AF */   sw        $zero, 0x20($sp)
    /* 133AB80 8006E5E4 21404000 */  addu       $t0, $v0, $zero
    /* 133AB84 8006E5E8 01080229 */  slti       $v0, $t0, 0x801
    /* 133AB88 8006E5EC 05004014 */  bnez       $v0, .Llevel_13_8006E604
    /* 133AB8C 8006E5F0 21202002 */   addu      $a0, $s1, $zero
    /* 133AB90 8006E5F4 21280001 */  addu       $a1, $t0, $zero
    /* 133AB94 8006E5F8 00080624 */  addiu      $a2, $zero, 0x800
  .Llevel_13_8006E5FC:
    /* 133AB98 8006E5FC 316F000C */  jal        func_8001BCC4
    /* 133AB9C 8006E600 00000000 */   nop
  .Llevel_13_8006E604:
    /* 133ABA0 8006E604 1800A28F */  lw         $v0, 0x18($sp)
    /* 133ABA4 8006E608 1C00A38F */  lw         $v1, 0x1C($sp)
    /* 133ABA8 8006E60C 0780013C */  lui        $at, %hi(D_8006A084)
    /* 133ABAC 8006E610 84A022AC */  sw         $v0, %lo(D_8006A084)($at)
    /* 133ABB0 8006E614 0780013C */  lui        $at, %hi(D_8006A088)
    /* 133ABB4 8006E618 88A023AC */  sw         $v1, %lo(D_8006A088)($at)
    /* 133ABB8 8006E61C ECBA0108 */  j          .Llevel_13_8006EBB0
    /* 133ABBC 8006E620 00000000 */   nop
  .Llevel_13_8006E624:
    /* 133ABC0 8006E624 2800B027 */  addiu      $s0, $sp, 0x28
    /* 133ABC4 8006E628 686F000C */  jal        func_8001BDA0
    /* 133ABC8 8006E62C 21200002 */   addu      $a0, $s0, $zero
    /* 133ABCC 8006E630 21200002 */  addu       $a0, $s0, $zero
    /* 133ABD0 8006E634 21280002 */  addu       $a1, $s0, $zero
    /* 133ABD4 8006E638 0780113C */  lui        $s1, %hi(D_8006A084)
    /* 133ABD8 8006E63C 84A03126 */  addiu      $s1, $s1, %lo(D_8006A084)
    /* 133ABDC 8006E640 806F000C */  jal        func_8001BE00
    /* 133ABE0 8006E644 21302002 */   addu      $a2, $s1, $zero
    /* 133ABE4 8006E648 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 133ABE8 8006E64C B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 133ABEC 8006E650 00000000 */  nop
    /* 133ABF0 8006E654 11004010 */  beqz       $v0, .Llevel_13_8006E69C
    /* 133ABF4 8006E658 21200002 */   addu      $a0, $s0, $zero
    /* 133ABF8 8006E65C 3000A0AF */  sw         $zero, 0x30($sp)
    /* 133ABFC 8006E660 886E000C */  jal        func_8001BA20
    /* 133AC00 8006E664 21280000 */   addu      $a1, $zero, $zero
    /* 133AC04 8006E668 21284000 */  addu       $a1, $v0, $zero
    /* 133AC08 8006E66C 4100A228 */  slti       $v0, $a1, 0x41
    /* 133AC0C 8006E670 05004014 */  bnez       $v0, .Llevel_13_8006E688
    /* 133AC10 8006E674 40FF0224 */   addiu     $v0, $zero, -0xC0
    /* 133AC14 8006E678 21200002 */  addu       $a0, $s0, $zero
    /* 133AC18 8006E67C 316F000C */  jal        func_8001BCC4
    /* 133AC1C 8006E680 40000624 */   addiu     $a2, $zero, 0x40
    /* 133AC20 8006E684 40FF0224 */  addiu      $v0, $zero, -0xC0
  .Llevel_13_8006E688:
    /* 133AC24 8006E688 3000A2AF */  sw         $v0, 0x30($sp)
    /* 133AC28 8006E68C F4FF2426 */  addiu      $a0, $s1, -0xC
    /* 133AC2C 8006E690 21282002 */  addu       $a1, $s1, $zero
    /* 133AC30 8006E694 B7B90108 */  j          .Llevel_13_8006E6DC
    /* 133AC34 8006E698 21300002 */   addu      $a2, $s0, $zero
  .Llevel_13_8006E69C:
    /* 133AC38 8006E69C 886E000C */  jal        func_8001BA20
    /* 133AC3C 8006E6A0 01000524 */   addiu     $a1, $zero, 0x1
    /* 133AC40 8006E6A4 21284000 */  addu       $a1, $v0, $zero
    /* 133AC44 8006E6A8 0101A228 */  slti       $v0, $a1, 0x101
    /* 133AC48 8006E6AC 05004014 */  bnez       $v0, .Llevel_13_8006E6C4
    /* 133AC4C 8006E6B0 21202002 */   addu      $a0, $s1, $zero
    /* 133AC50 8006E6B4 21200002 */  addu       $a0, $s0, $zero
    /* 133AC54 8006E6B8 316F000C */  jal        func_8001BCC4
    /* 133AC58 8006E6BC 00010624 */   addiu     $a2, $zero, 0x100
    /* 133AC5C 8006E6C0 21202002 */  addu       $a0, $s1, $zero
  .Llevel_13_8006E6C4:
    /* 133AC60 8006E6C4 21282002 */  addu       $a1, $s1, $zero
    /* 133AC64 8006E6C8 736F000C */  jal        func_8001BDCC
    /* 133AC68 8006E6CC 21300002 */   addu      $a2, $s0, $zero
    /* 133AC6C 8006E6D0 F4FF2426 */  addiu      $a0, $s1, -0xC
    /* 133AC70 8006E6D4 21282002 */  addu       $a1, $s1, $zero
    /* 133AC74 8006E6D8 5C00A624 */  addiu      $a2, $a1, 0x5C
  .Llevel_13_8006E6DC:
    /* 133AC78 8006E6DC 736F000C */  jal        func_8001BDCC
    /* 133AC7C 8006E6E0 00000000 */   nop
    /* 133AC80 8006E6E4 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 133AC84 8006E6E8 84A08424 */  addiu      $a0, $a0, %lo(D_8006A084)
    /* 133AC88 8006E6EC 6C6F000C */  jal        func_8001BDB0
    /* 133AC8C 8006E6F0 21288000 */   addu      $a1, $a0, $zero
    /* 133AC90 8006E6F4 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 133AC94 8006E6F8 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 133AC98 8006E6FC 00000000 */  nop
    /* 133AC9C 8006E700 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 133ACA0 8006E704 2A014010 */  beqz       $v0, .Llevel_13_8006EBB0
    /* 133ACA4 8006E708 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 133ACA8 8006E70C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 133ACAC 8006E710 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 133ACB0 8006E714 ECBA0108 */  j          .Llevel_13_8006EBB0
    /* 133ACB4 8006E718 00000000 */   nop
  .Llevel_13_8006E71C:
    /* 133ACB8 8006E71C 0780103C */  lui        $s0, %hi(D_8006A0B0)
    /* 133ACBC 8006E720 B0A01026 */  addiu      $s0, $s0, %lo(D_8006A0B0)
    /* 133ACC0 8006E724 0000028E */  lw         $v0, 0x0($s0)
    /* 133ACC4 8006E728 00000000 */  nop
    /* 133ACC8 8006E72C 11004010 */  beqz       $v0, .Llevel_13_8006E774
    /* 133ACCC 8006E730 00000000 */   nop
    /* 133ACD0 8006E734 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 133ACD4 8006E738 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 133ACD8 8006E73C 00000000 */  nop
    /* 133ACDC 8006E740 00FA4224 */  addiu      $v0, $v0, -0x600
    /* 133ACE0 8006E744 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 133ACE4 8006E748 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 133ACE8 8006E74C 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 133ACEC 8006E750 03004010 */  beqz       $v0, .Llevel_13_8006E760
    /* 133ACF0 8006E754 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 133ACF4 8006E758 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 133ACF8 8006E75C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_13_8006E760:
    /* 133ACFC 8006E760 C8FF0426 */  addiu      $a0, $s0, -0x38
    /* 133AD00 8006E764 6C6F000C */  jal        func_8001BDB0
    /* 133AD04 8006E768 D4FF0526 */   addiu     $a1, $s0, -0x2C
    /* 133AD08 8006E76C ECBA0108 */  j          .Llevel_13_8006EBB0
    /* 133AD0C 8006E770 00000000 */   nop
  .Llevel_13_8006E774:
    /* 133AD10 8006E774 686F000C */  jal        func_8001BDA0
    /* 133AD14 8006E778 C8FF0426 */   addiu     $a0, $s0, -0x38
    /* 133AD18 8006E77C 686F000C */  jal        func_8001BDA0
    /* 133AD1C 8006E780 D4FF0426 */   addiu     $a0, $s0, -0x2C
    /* 133AD20 8006E784 ECBA0108 */  j          .Llevel_13_8006EBB0
    /* 133AD24 8006E788 00000000 */   nop
  .Llevel_13_8006E78C:
    /* 133AD28 8006E78C DBAC000C */  jal        func_8002B36C
    /* 133AD2C 8006E790 800C0424 */   addiu     $a0, $zero, 0xC80
    /* 133AD30 8006E794 28000424 */  addiu      $a0, $zero, 0x28
    /* 133AD34 8006E798 08000524 */  addiu      $a1, $zero, 0x8
    /* 133AD38 8006E79C 0780113C */  lui        $s1, %hi(D_8006A0A4)
    /* 133AD3C 8006E7A0 A4A03126 */  addiu      $s1, $s1, %lo(D_8006A0A4)
    /* 133AD40 8006E7A4 00190224 */  addiu      $v0, $zero, 0x1900
    /* 133AD44 8006E7A8 C9AE000C */  jal        func_8002BB24
    /* 133AD48 8006E7AC 000022AE */   sw        $v0, 0x0($s1)
    /* 133AD4C 8006E7B0 40010424 */  addiu      $a0, $zero, 0x140
    /* 133AD50 8006E7B4 5CAF000C */  jal        func_8002BD70
    /* 133AD54 8006E7B8 C0000524 */   addiu     $a1, $zero, 0xC0
    /* 133AD58 8006E7BC 0780043C */  lui        $a0, %hi(D_8006A09C)
    /* 133AD5C 8006E7C0 9CA0848C */  lw         $a0, %lo(D_8006A09C)($a0)
    /* 133AD60 8006E7C4 996D000C */  jal        func_8001B664
    /* 133AD64 8006E7C8 E0FF3226 */   addiu     $s2, $s1, -0x20
    /* 133AD68 8006E7CC 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 133AD6C 8006E7D0 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 133AD70 8006E7D4 00000000 */  nop
    /* 133AD74 8006E7D8 18006200 */  mult       $v1, $v0
    /* 133AD78 8006E7DC 0780043C */  lui        $a0, %hi(D_8006A09C)
    /* 133AD7C 8006E7E0 9CA0848C */  lw         $a0, %lo(D_8006A09C)($a0)
    /* 133AD80 8006E7E4 12480000 */  mflo       $t1
    /* 133AD84 8006E7E8 03130900 */  sra        $v0, $t1, 12
    /* 133AD88 8006E7EC 876D000C */  jal        func_8001B61C
    /* 133AD8C 8006E7F0 3800A2AF */   sw        $v0, 0x38($sp)
    /* 133AD90 8006E7F4 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 133AD94 8006E7F8 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 133AD98 8006E7FC 00000000 */  nop
    /* 133AD9C 8006E800 18006200 */  mult       $v1, $v0
    /* 133ADA0 8006E804 3800B027 */  addiu      $s0, $sp, 0x38
    /* 133ADA4 8006E808 21200002 */  addu       $a0, $s0, $zero
    /* 133ADA8 8006E80C 21280002 */  addu       $a1, $s0, $zero
    /* 133ADAC 8006E810 21304002 */  addu       $a2, $s2, $zero
    /* 133ADB0 8006E814 12480000 */  mflo       $t1
    /* 133ADB4 8006E818 03130900 */  sra        $v0, $t1, 12
    /* 133ADB8 8006E81C 806F000C */  jal        func_8001BE00
    /* 133ADBC 8006E820 3C00A2AF */   sw        $v0, 0x3C($sp)
    /* 133ADC0 8006E824 21200002 */  addu       $a0, $s0, $zero
    /* 133ADC4 8006E828 21280000 */  addu       $a1, $zero, $zero
    /* 133ADC8 8006E82C 886E000C */  jal        func_8001BA20
    /* 133ADCC 8006E830 4000A0AF */   sw        $zero, 0x40($sp)
    /* 133ADD0 8006E834 21284000 */  addu       $a1, $v0, $zero
    /* 133ADD4 8006E838 8102A228 */  slti       $v0, $a1, 0x281
    /* 133ADD8 8006E83C 05004014 */  bnez       $v0, .Llevel_13_8006E854
    /* 133ADDC 8006E840 D4FF2426 */   addiu     $a0, $s1, -0x2C
    /* 133ADE0 8006E844 21200002 */  addu       $a0, $s0, $zero
    /* 133ADE4 8006E848 316F000C */  jal        func_8001BCC4
    /* 133ADE8 8006E84C 80020624 */   addiu     $a2, $zero, 0x280
    /* 133ADEC 8006E850 D4FF2426 */  addiu      $a0, $s1, -0x2C
  .Llevel_13_8006E854:
    /* 133ADF0 8006E854 21284002 */  addu       $a1, $s2, $zero
    /* 133ADF4 8006E858 736F000C */  jal        func_8001BDCC
    /* 133ADF8 8006E85C 21300002 */   addu      $a2, $s0, $zero
    /* 133ADFC 8006E860 0EB0000C */  jal        func_8002C038
    /* 133AE00 8006E864 00000000 */   nop
    /* 133AE04 8006E868 1500622A */  slti       $v0, $s3, 0x15
    /* 133AE08 8006E86C 0E004010 */  beqz       $v0, .Llevel_13_8006E8A8
    /* 133AE0C 8006E870 03000224 */   addiu     $v0, $zero, 0x3
    /* 133AE10 8006E874 0780033C */  lui        $v1, %hi(D_8006A044)
    /* 133AE14 8006E878 44A0638C */  lw         $v1, %lo(D_8006A044)($v1)
    /* 133AE18 8006E87C 00000000 */  nop
    /* 133AE1C 8006E880 09006214 */  bne        $v1, $v0, .Llevel_13_8006E8A8
    /* 133AE20 8006E884 00000000 */   nop
    /* 133AE24 8006E888 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 133AE28 8006E88C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 133AE2C 8006E890 00000000 */  nop
    /* 133AE30 8006E894 C0004224 */  addiu      $v0, $v0, 0xC0
    /* 133AE34 8006E898 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 133AE38 8006E89C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 133AE3C 8006E8A0 ECBA0108 */  j          .Llevel_13_8006EBB0
    /* 133AE40 8006E8A4 00000000 */   nop
  .Llevel_13_8006E8A8:
    /* 133AE44 8006E8A8 0780033C */  lui        $v1, %hi(D_8006A08C)
    /* 133AE48 8006E8AC 8CA06324 */  addiu      $v1, $v1, %lo(D_8006A08C)
    /* 133AE4C 8006E8B0 0000628C */  lw         $v0, 0x0($v1)
    /* 133AE50 8006E8B4 00000000 */  nop
    /* 133AE54 8006E8B8 40FF4224 */  addiu      $v0, $v0, -0xC0
    /* 133AE58 8006E8BC ECBA0108 */  j          .Llevel_13_8006EBB0
    /* 133AE5C 8006E8C0 000062AC */   sw        $v0, 0x0($v1)
  .Llevel_13_8006E8C4:
    /* 133AE60 8006E8C4 0780103C */  lui        $s0, %hi(D_8006A0B0)
    /* 133AE64 8006E8C8 B0A01026 */  addiu      $s0, $s0, %lo(D_8006A0B0)
    /* 133AE68 8006E8CC 0000028E */  lw         $v0, 0x0($s0)
    /* 133AE6C 8006E8D0 00000000 */  nop
    /* 133AE70 8006E8D4 1F004010 */  beqz       $v0, .Llevel_13_8006E954
    /* 133AE74 8006E8D8 4800B127 */   addiu     $s1, $sp, 0x48
    /* 133AE78 8006E8DC 686F000C */  jal        func_8001BDA0
    /* 133AE7C 8006E8E0 21202002 */   addu      $a0, $s1, $zero
    /* 133AE80 8006E8E4 21202002 */  addu       $a0, $s1, $zero
    /* 133AE84 8006E8E8 21282002 */  addu       $a1, $s1, $zero
    /* 133AE88 8006E8EC D4FF1226 */  addiu      $s2, $s0, -0x2C
    /* 133AE8C 8006E8F0 806F000C */  jal        func_8001BE00
    /* 133AE90 8006E8F4 21304002 */   addu      $a2, $s2, $zero
    /* 133AE94 8006E8F8 5000A0AF */  sw         $zero, 0x50($sp)
    /* 133AE98 8006E8FC 21202002 */  addu       $a0, $s1, $zero
    /* 133AE9C 8006E900 886E000C */  jal        func_8001BA20
    /* 133AEA0 8006E904 21280000 */   addu      $a1, $zero, $zero
    /* 133AEA4 8006E908 21284000 */  addu       $a1, $v0, $zero
    /* 133AEA8 8006E90C 4100A228 */  slti       $v0, $a1, 0x41
    /* 133AEAC 8006E910 05004014 */  bnez       $v0, .Llevel_13_8006E928
    /* 133AEB0 8006E914 40FF0224 */   addiu     $v0, $zero, -0xC0
    /* 133AEB4 8006E918 21202002 */  addu       $a0, $s1, $zero
    /* 133AEB8 8006E91C 316F000C */  jal        func_8001BCC4
    /* 133AEBC 8006E920 40000624 */   addiu     $a2, $zero, 0x40
    /* 133AEC0 8006E924 40FF0224 */  addiu      $v0, $zero, -0xC0
  .Llevel_13_8006E928:
    /* 133AEC4 8006E928 5000A2AF */  sw         $v0, 0x50($sp)
    /* 133AEC8 8006E92C C8FF1026 */  addiu      $s0, $s0, -0x38
    /* 133AECC 8006E930 21200002 */  addu       $a0, $s0, $zero
    /* 133AED0 8006E934 21284002 */  addu       $a1, $s2, $zero
    /* 133AED4 8006E938 736F000C */  jal        func_8001BDCC
    /* 133AED8 8006E93C 21302002 */   addu      $a2, $s1, $zero
    /* 133AEDC 8006E940 21204002 */  addu       $a0, $s2, $zero
    /* 133AEE0 8006E944 6C6F000C */  jal        func_8001BDB0
    /* 133AEE4 8006E948 21280002 */   addu      $a1, $s0, $zero
    /* 133AEE8 8006E94C 59BA0108 */  j          .Llevel_13_8006E964
    /* 133AEEC 8006E950 00000000 */   nop
  .Llevel_13_8006E954:
    /* 133AEF0 8006E954 686F000C */  jal        func_8001BDA0
    /* 133AEF4 8006E958 C8FF0426 */   addiu     $a0, $s0, -0x38
    /* 133AEF8 8006E95C 686F000C */  jal        func_8001BDA0
    /* 133AEFC 8006E960 D4FF0426 */   addiu     $a0, $s0, -0x2C
  .Llevel_13_8006E964:
    /* 133AF00 8006E964 0780053C */  lui        $a1, %hi(D_8006A08C)
    /* 133AF04 8006E968 8CA0A524 */  addiu      $a1, $a1, %lo(D_8006A08C)
    /* 133AF08 8006E96C 0000A28C */  lw         $v0, 0x0($a1)
    /* 133AF0C 8006E970 00000000 */  nop
    /* 133AF10 8006E974 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 133AF14 8006E978 02004010 */  beqz       $v0, .Llevel_13_8006E984
    /* 133AF18 8006E97C 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 133AF1C 8006E980 0000A2AC */  sw         $v0, 0x0($a1)
  .Llevel_13_8006E984:
    /* 133AF20 8006E984 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 133AF24 8006E988 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 133AF28 8006E98C 3A000224 */  addiu      $v0, $zero, 0x3A
    /* 133AF2C 8006E990 87006214 */  bne        $v1, $v0, .Llevel_13_8006EBB0
    /* 133AF30 8006E994 00000000 */   nop
    /* 133AF34 8006E998 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 133AF38 8006E99C FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 133AF3C 8006E9A0 00000000 */  nop
    /* 133AF40 8006E9A4 82004010 */  beqz       $v0, .Llevel_13_8006EBB0
    /* 133AF44 8006E9A8 00000000 */   nop
    /* 133AF48 8006E9AC 0680023C */  lui        $v0, %hi(D_80067008)
    /* 133AF4C 8006E9B0 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 133AF50 8006E9B4 00000000 */  nop
    /* 133AF54 8006E9B8 01004230 */  andi       $v0, $v0, 0x1
    /* 133AF58 8006E9BC 7C004010 */  beqz       $v0, .Llevel_13_8006EBB0
    /* 133AF5C 8006E9C0 6800B027 */   addiu     $s0, $sp, 0x68
    /* 133AF60 8006E9C4 21200002 */  addu       $a0, $s0, $zero
    /* 133AF64 8006E9C8 64FFA524 */  addiu      $a1, $a1, -0x9C
    /* 133AF68 8006E9CC 0E000224 */  addiu      $v0, $zero, 0xE
    /* 133AF6C 8006E9D0 5800A0AF */  sw         $zero, 0x58($sp)
    /* 133AF70 8006E9D4 5C00A0AF */  sw         $zero, 0x5C($sp)
    /* 133AF74 8006E9D8 6C6F000C */  jal        func_8001BDB0
    /* 133AF78 8006E9DC 6000A2AF */   sw        $v0, 0x60($sp)
    /* 133AF7C 8006E9E0 21200000 */  addu       $a0, $zero, $zero
    /* 133AF80 8006E9E4 63E2000C */  jal        func_8003898C
    /* 133AF84 8006E9E8 2C010524 */   addiu     $a1, $zero, 0x12C
    /* 133AF88 8006E9EC 21200000 */  addu       $a0, $zero, $zero
    /* 133AF8C 8006E9F0 6800A38F */  lw         $v1, 0x68($sp)
    /* 133AF90 8006E9F4 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 133AF94 8006E9F8 21186200 */  addu       $v1, $v1, $v0
    /* 133AF98 8006E9FC 63E2000C */  jal        func_8003898C
    /* 133AF9C 8006EA00 6800A3AF */   sw        $v1, 0x68($sp)
    /* 133AFA0 8006EA04 21200000 */  addu       $a0, $zero, $zero
    /* 133AFA4 8006EA08 6C00A38F */  lw         $v1, 0x6C($sp)
    /* 133AFA8 8006EA0C 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 133AFAC 8006EA10 21186200 */  addu       $v1, $v1, $v0
    /* 133AFB0 8006EA14 63E2000C */  jal        func_8003898C
    /* 133AFB4 8006EA18 6C00A3AF */   sw        $v1, 0x6C($sp)
    /* 133AFB8 8006EA1C 01000424 */  addiu      $a0, $zero, 0x1
    /* 133AFBC 8006EA20 0D000524 */  addiu      $a1, $zero, 0xD
    /* 133AFC0 8006EA24 7000A38F */  lw         $v1, 0x70($sp)
    /* 133AFC4 8006EA28 21300002 */  addu       $a2, $s0, $zero
    /* 133AFC8 8006EA2C 21186200 */  addu       $v1, $v1, $v0
    /* 133AFCC 8006EA30 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 133AFD0 8006EA34 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 133AFD4 8006EA38 5800A727 */  addiu      $a3, $sp, 0x58
    /* 133AFD8 8006EA3C 09F84000 */  jalr       $v0
    /* 133AFDC 8006EA40 7000A3AF */   sw        $v1, 0x70($sp)
    /* 133AFE0 8006EA44 06000324 */  addiu      $v1, $zero, 0x6
    /* 133AFE4 8006EA48 020043A0 */  sb         $v1, 0x2($v0)
    /* 133AFE8 8006EA4C 20000324 */  addiu      $v1, $zero, 0x20
    /* 133AFEC 8006EA50 ECBA0108 */  j          .Llevel_13_8006EBB0
    /* 133AFF0 8006EA54 0A0043A0 */   sb        $v1, 0xA($v0)
  .Llevel_13_8006EA58:
    /* 133AFF4 8006EA58 0780123C */  lui        $s2, %hi(D_8006A0DC)
    /* 133AFF8 8006EA5C DCA05226 */  addiu      $s2, $s2, %lo(D_8006A0DC)
    /* 133AFFC 8006EA60 0000428E */  lw         $v0, 0x0($s2)
    /* 133B000 8006EA64 00000000 */  nop
    /* 133B004 8006EA68 0B004228 */  slti       $v0, $v0, 0xB
    /* 133B008 8006EA6C 0A004014 */  bnez       $v0, .Llevel_13_8006EA98
    /* 133B00C 8006EA70 80000424 */   addiu     $a0, $zero, 0x80
    /* 133B010 8006EA74 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* 133B014 8006EA78 C4A0848C */  lw         $a0, %lo(D_8006A0C4)($a0)
    /* 133B018 8006EA7C 0780053C */  lui        $a1, %hi(D_8006A0C8)
    /* 133B01C 8006EA80 C8A0A58C */  lw         $a1, %lo(D_8006A0C8)($a1)
    /* 133B020 8006EA84 2E6D000C */  jal        func_8001B4B8
    /* 133B024 8006EA88 01000624 */   addiu     $a2, $zero, 0x1
    /* 133B028 8006EA8C 0780013C */  lui        $at, %hi(D_8006A140)
    /* 133B02C 8006EA90 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
    /* 133B030 8006EA94 80000424 */  addiu      $a0, $zero, 0x80
  .Llevel_13_8006EA98:
    /* 133B034 8006EA98 000F0224 */  addiu      $v0, $zero, 0xF00
    /* 133B038 8006EA9C 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 133B03C 8006EAA0 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 133B040 8006EAA4 5CAF000C */  jal        func_8002BD70
    /* 133B044 8006EAA8 C0000524 */   addiu     $a1, $zero, 0xC0
    /* 133B048 8006EAAC 0780043C */  lui        $a0, %hi(D_8006A140)
    /* 133B04C 8006EAB0 40A1848C */  lw         $a0, %lo(D_8006A140)($a0)
    /* 133B050 8006EAB4 996D000C */  jal        func_8001B664
    /* 133B054 8006EAB8 9CFF5126 */   addiu     $s1, $s2, -0x64
    /* 133B058 8006EABC 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 133B05C 8006EAC0 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 133B060 8006EAC4 00000000 */  nop
    /* 133B064 8006EAC8 18006200 */  mult       $v1, $v0
    /* 133B068 8006EACC 0780043C */  lui        $a0, %hi(D_8006A140)
    /* 133B06C 8006EAD0 40A1848C */  lw         $a0, %lo(D_8006A140)($a0)
    /* 133B070 8006EAD4 12480000 */  mflo       $t1
    /* 133B074 8006EAD8 03130900 */  sra        $v0, $t1, 12
    /* 133B078 8006EADC 876D000C */  jal        func_8001B61C
    /* 133B07C 8006EAE0 5800A2AF */   sw        $v0, 0x58($sp)
    /* 133B080 8006EAE4 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 133B084 8006EAE8 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 133B088 8006EAEC 00000000 */  nop
    /* 133B08C 8006EAF0 18006200 */  mult       $v1, $v0
    /* 133B090 8006EAF4 5800B027 */  addiu      $s0, $sp, 0x58
    /* 133B094 8006EAF8 21200002 */  addu       $a0, $s0, $zero
    /* 133B098 8006EAFC 21280002 */  addu       $a1, $s0, $zero
    /* 133B09C 8006EB00 21302002 */  addu       $a2, $s1, $zero
    /* 133B0A0 8006EB04 6000A0AF */  sw         $zero, 0x60($sp)
    /* 133B0A4 8006EB08 12480000 */  mflo       $t1
    /* 133B0A8 8006EB0C 03130900 */  sra        $v0, $t1, 12
    /* 133B0AC 8006EB10 806F000C */  jal        func_8001BE00
    /* 133B0B0 8006EB14 5C00A2AF */   sw        $v0, 0x5C($sp)
    /* 133B0B4 8006EB18 21200002 */  addu       $a0, $s0, $zero
    /* 133B0B8 8006EB1C 21280000 */  addu       $a1, $zero, $zero
    /* 133B0BC 8006EB20 886E000C */  jal        func_8001BA20
    /* 133B0C0 8006EB24 6000A0AF */   sw        $zero, 0x60($sp)
    /* 133B0C4 8006EB28 21284000 */  addu       $a1, $v0, $zero
    /* 133B0C8 8006EB2C 0101A228 */  slti       $v0, $a1, 0x101
    /* 133B0CC 8006EB30 05004014 */  bnez       $v0, .Llevel_13_8006EB48
    /* 133B0D0 8006EB34 21202002 */   addu      $a0, $s1, $zero
    /* 133B0D4 8006EB38 21200002 */  addu       $a0, $s0, $zero
    /* 133B0D8 8006EB3C 316F000C */  jal        func_8001BCC4
    /* 133B0DC 8006EB40 00010624 */   addiu     $a2, $zero, 0x100
    /* 133B0E0 8006EB44 21202002 */  addu       $a0, $s1, $zero
  .Llevel_13_8006EB48:
    /* 133B0E4 8006EB48 21282002 */  addu       $a1, $s1, $zero
    /* 133B0E8 8006EB4C 736F000C */  jal        func_8001BDCC
    /* 133B0EC 8006EB50 21300002 */   addu      $a2, $s0, $zero
    /* 133B0F0 8006EB54 0780023C */  lui        $v0, %hi(D_8006A0F4)
    /* 133B0F4 8006EB58 F4A04290 */  lbu        $v0, %lo(D_8006A0F4)($v0)
    /* 133B0F8 8006EB5C 00000000 */  nop
    /* 133B0FC 8006EB60 06004014 */  bnez       $v0, .Llevel_13_8006EB7C
    /* 133B100 8006EB64 00000000 */   nop
    /* 133B104 8006EB68 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 133B108 8006EB6C B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 133B10C 8006EB70 00000000 */  nop
    /* 133B110 8006EB74 09004010 */  beqz       $v0, .Llevel_13_8006EB9C
    /* 133B114 8006EB78 A8FF4426 */   addiu     $a0, $s2, -0x58
  .Llevel_13_8006EB7C:
    /* 133B118 8006EB7C 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 133B11C 8006EB80 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 133B120 8006EB84 00000000 */  nop
    /* 133B124 8006EB88 40FF4224 */  addiu      $v0, $v0, -0xC0
    /* 133B128 8006EB8C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 133B12C 8006EB90 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 133B130 8006EB94 ECBA0108 */  j          .Llevel_13_8006EBB0
    /* 133B134 8006EB98 00000000 */   nop
  .Llevel_13_8006EB9C:
    /* 133B138 8006EB9C 21282002 */  addu       $a1, $s1, $zero
  .Llevel_13_8006EBA0:
    /* 133B13C 8006EBA0 0780063C */  lui        $a2, %hi(D_8006A0E0)
    /* 133B140 8006EBA4 E0A0C624 */  addiu      $a2, $a2, %lo(D_8006A0E0)
    /* 133B144 8006EBA8 736F000C */  jal        func_8001BDCC
    /* 133B148 8006EBAC 00000000 */   nop
  .Llevel_13_8006EBB0:
    /* 133B14C 8006EBB0 8800BF8F */  lw         $ra, 0x88($sp)
    /* 133B150 8006EBB4 8400B38F */  lw         $s3, 0x84($sp)
    /* 133B154 8006EBB8 8000B28F */  lw         $s2, 0x80($sp)
    /* 133B158 8006EBBC 7C00B18F */  lw         $s1, 0x7C($sp)
    /* 133B15C 8006EBC0 7800B08F */  lw         $s0, 0x78($sp)
    /* 133B160 8006EBC4 9000BD27 */  addiu      $sp, $sp, 0x90
    /* 133B164 8006EBC8 0800E003 */  jr         $ra
    /* 133B168 8006EBCC 00000000 */   nop
endlabel func_level_13_8006E018
