.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_55_8006D268

dlabel jtbl_level_55_8006D268
    /* 3D1D804 8006D268 BCD90680 */ .word .Llevel_55_8006D9BC
    /* 3D1D808 8006D26C D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D80C 8006D270 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D810 8006D274 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D814 8006D278 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D818 8006D27C D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D81C 8006D280 0CDA0680 */ .word .Llevel_55_8006DA0C
    /* 3D1D820 8006D284 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D824 8006D288 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D828 8006D28C 4CDB0680 */ .word .Llevel_55_8006DB4C
    /* 3D1D82C 8006D290 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D830 8006D294 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D834 8006D298 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D838 8006D29C D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D83C 8006D2A0 40DF0680 */ .word .Llevel_55_8006DF40
    /* 3D1D840 8006D2A4 40DF0680 */ .word .Llevel_55_8006DF40
    /* 3D1D844 8006D2A8 40DF0680 */ .word .Llevel_55_8006DF40
    /* 3D1D848 8006D2AC D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D84C 8006D2B0 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D850 8006D2B4 BCD90680 */ .word .Llevel_55_8006D9BC
    /* 3D1D854 8006D2B8 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D858 8006D2BC D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D85C 8006D2C0 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D860 8006D2C4 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D864 8006D2C8 78E50680 */ .word .Llevel_55_8006E578
    /* 3D1D868 8006D2CC 78E50680 */ .word .Llevel_55_8006E578
    /* 3D1D86C 8006D2D0 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D870 8006D2D4 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D874 8006D2D8 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D878 8006D2DC D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D87C 8006D2E0 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D880 8006D2E4 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D884 8006D2E8 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D888 8006D2EC D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D88C 8006D2F0 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D890 8006D2F4 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D894 8006D2F8 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D898 8006D2FC D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D89C 8006D300 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D8A0 8006D304 ACDD0680 */ .word .Llevel_55_8006DDAC
    /* 3D1D8A4 8006D308 D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D8A8 8006D30C D8EA0680 */ .word .Llevel_55_8006EAD8
    /* 3D1D8AC 8006D310 E8E80680 */ .word .Llevel_55_8006E8E8
    /* 3D1D8B0 8006D314 00000000 */ .word 0x00000000
enddlabel jtbl_level_55_8006D268


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_55_8006D940, 0x11BC

glabel func_level_55_8006D940
    /* 3D1DEDC 8006D940 28C30780 */  lb         $a3, -0x3CD8($zero)
    /* 3D1DEE0 8006D944 3CC30780 */  lb         $a3, -0x3CC4($zero)
    /* 3D1DEE4 8006D948 40FFBD27 */  addiu      $sp, $sp, -0xC0
    /* 3D1DEE8 8006D94C B000B2AF */  sw         $s2, 0xB0($sp)
    /* 3D1DEEC 8006D950 21908000 */  addu       $s2, $a0, $zero
    /* 3D1DEF0 8006D954 00111200 */  sll        $v0, $s2, 4
    /* 3D1DEF4 8006D958 0780033C */  lui        $v1, %hi(D_800683B0)
    /* 3D1DEF8 8006D95C B0836324 */  addiu      $v1, $v1, %lo(D_800683B0)
    /* 3D1DEFC 8006D960 21104300 */  addu       $v0, $v0, $v1
    /* 3D1DF00 8006D964 0680013C */  lui        $at, %hi(D_80066F38)
    /* 3D1DF04 8006D968 386F22AC */  sw         $v0, %lo(D_80066F38)($at)
    /* 3D1DF08 8006D96C 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 3D1DF0C 8006D970 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 3D1DF10 8006D974 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 3D1DF14 8006D978 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 3D1DF18 8006D97C BC00BFAF */  sw         $ra, 0xBC($sp)
    /* 3D1DF1C 8006D980 B800B4AF */  sw         $s4, 0xB8($sp)
    /* 3D1DF20 8006D984 B400B3AF */  sw         $s3, 0xB4($sp)
    /* 3D1DF24 8006D988 AC00B1AF */  sw         $s1, 0xAC($sp)
    /* 3D1DF28 8006D98C 21985200 */  addu       $s3, $v0, $s2
    /* 3D1DF2C 8006D990 EDFF6324 */  addiu      $v1, $v1, -0x13
    /* 3D1DF30 8006D994 2B00622C */  sltiu      $v0, $v1, 0x2B
    /* 3D1DF34 8006D998 4F044010 */  beqz       $v0, .Llevel_55_8006EAD8
    /* 3D1DF38 8006D99C A800B0AF */   sw        $s0, 0xA8($sp)
    /* 3D1DF3C 8006D9A0 80100300 */  sll        $v0, $v1, 2
    /* 3D1DF40 8006D9A4 0780013C */  lui        $at, %hi(jtbl_level_55_8006D268)
    /* 3D1DF44 8006D9A8 21082200 */  addu       $at, $at, $v0
    /* 3D1DF48 8006D9AC 68D2228C */  lw         $v0, %lo(jtbl_level_55_8006D268)($at)
    /* 3D1DF4C 8006D9B0 00000000 */  nop
    /* 3D1DF50 8006D9B4 08004000 */  jr         $v0
    /* 3D1DF54 8006D9B8 00000000 */   nop
  .Llevel_55_8006D9BC:
    /* 3D1DF58 8006D9BC 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 3D1DF5C 8006D9C0 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 3D1DF60 8006D9C4 686F000C */  jal        func_8001BDA0
    /* 3D1DF64 8006D9C8 21200002 */   addu      $a0, $s0, $zero
    /* 3D1DF68 8006D9CC 686F000C */  jal        func_8001BDA0
    /* 3D1DF6C 8006D9D0 0C000426 */   addiu     $a0, $s0, 0xC
    /* 3D1DF70 8006D9D4 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 3D1DF74 8006D9D8 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 3D1DF78 8006D9DC 07000224 */  addiu      $v0, $zero, 0x7
    /* 3D1DF7C 8006D9E0 3D046210 */  beq        $v1, $v0, .Llevel_55_8006EAD8
    /* 3D1DF80 8006D9E4 00000000 */   nop
    /* 3D1DF84 8006D9E8 DBAC000C */  jal        func_8002B36C
    /* 3D1DF88 8006D9EC 00120424 */   addiu     $a0, $zero, 0x1200
    /* 3D1DF8C 8006D9F0 1AAF000C */  jal        func_8002BC68
    /* 3D1DF90 8006D9F4 00000000 */   nop
    /* 3D1DF94 8006D9F8 5A000424 */  addiu      $a0, $zero, 0x5A
    /* 3D1DF98 8006D9FC C9AE000C */  jal        func_8002BB24
    /* 3D1DF9C 8006DA00 10000524 */   addiu     $a1, $zero, 0x10
    /* 3D1DFA0 8006DA04 B6BA0108 */  j          .Llevel_55_8006EAD8
    /* 3D1DFA4 8006DA08 00000000 */   nop
  .Llevel_55_8006DA0C:
    /* 3D1DFA8 8006DA0C 1000A427 */  addiu      $a0, $sp, 0x10
    /* 3D1DFAC 8006DA10 39AD000C */  jal        func_8002B4E4
    /* 3D1DFB0 8006DA14 01000524 */   addiu     $a1, $zero, 0x1
    /* 3D1DFB4 8006DA18 1000A28F */  lw         $v0, 0x10($sp)
    /* 3D1DFB8 8006DA1C 0780043C */  lui        $a0, %hi(D_8006A0A0)
    /* 3D1DFBC 8006DA20 A0A08424 */  addiu      $a0, $a0, %lo(D_8006A0A0)
    /* 3D1DFC0 8006DA24 43100200 */  sra        $v0, $v0, 1
    /* 3D1DFC4 8006DA28 000082AC */  sw         $v0, 0x0($a0)
    /* 3D1DFC8 8006DA2C E7FF4228 */  slti       $v0, $v0, -0x19
    /* 3D1DFCC 8006DA30 02004010 */  beqz       $v0, .Llevel_55_8006DA3C
    /* 3D1DFD0 8006DA34 E7FF0224 */   addiu     $v0, $zero, -0x19
    /* 3D1DFD4 8006DA38 000082AC */  sw         $v0, 0x0($a0)
  .Llevel_55_8006DA3C:
    /* 3D1DFD8 8006DA3C 0000828C */  lw         $v0, 0x0($a0)
    /* 3D1DFDC 8006DA40 00000000 */  nop
    /* 3D1DFE0 8006DA44 1A004228 */  slti       $v0, $v0, 0x1A
    /* 3D1DFE4 8006DA48 02004014 */  bnez       $v0, .Llevel_55_8006DA54
    /* 3D1DFE8 8006DA4C 19000224 */   addiu     $v0, $zero, 0x19
    /* 3D1DFEC 8006DA50 000082AC */  sw         $v0, 0x0($a0)
  .Llevel_55_8006DA54:
    /* 3D1DFF0 8006DA54 0000848C */  lw         $a0, 0x0($a0)
    /* 3D1DFF4 8006DA58 68AE000C */  jal        func_8002B9A0
    /* 3D1DFF8 8006DA5C 00000000 */   nop
    /* 3D1DFFC 8006DA60 40020424 */  addiu      $a0, $zero, 0x240
    /* 3D1E000 8006DA64 5CAF000C */  jal        func_8002BD70
    /* 3D1E004 8006DA68 80010524 */   addiu     $a1, $zero, 0x180
    /* 3D1E008 8006DA6C 0780043C */  lui        $a0, %hi(D_8006A05C)
    /* 3D1E00C 8006DA70 5CA0848C */  lw         $a0, %lo(D_8006A05C)($a0)
    /* 3D1E010 8006DA74 996D000C */  jal        func_8001B664
    /* 3D1E014 8006DA78 00000000 */   nop
    /* 3D1E018 8006DA7C 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 3D1E01C 8006DA80 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 3D1E020 8006DA84 00000000 */  nop
    /* 3D1E024 8006DA88 18006200 */  mult       $v1, $v0
    /* 3D1E028 8006DA8C 0780043C */  lui        $a0, %hi(D_8006A05C)
    /* 3D1E02C 8006DA90 5CA0848C */  lw         $a0, %lo(D_8006A05C)($a0)
    /* 3D1E030 8006DA94 12480000 */  mflo       $t1
    /* 3D1E034 8006DA98 03130900 */  sra        $v0, $t1, 12
    /* 3D1E038 8006DA9C 0780013C */  lui        $at, %hi(D_8006A078)
    /* 3D1E03C 8006DAA0 78A022AC */  sw         $v0, %lo(D_8006A078)($at)
    /* 3D1E040 8006DAA4 876D000C */  jal        func_8001B61C
    /* 3D1E044 8006DAA8 00000000 */   nop
    /* 3D1E048 8006DAAC 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 3D1E04C 8006DAB0 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 3D1E050 8006DAB4 00000000 */  nop
    /* 3D1E054 8006DAB8 18006200 */  mult       $v1, $v0
    /* 3D1E058 8006DABC 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 3D1E05C 8006DAC0 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 3D1E060 8006DAC4 0780013C */  lui        $at, %hi(D_8006A080)
    /* 3D1E064 8006DAC8 80A022AC */  sw         $v0, %lo(D_8006A080)($at)
    /* 3D1E068 8006DACC 12480000 */  mflo       $t1
    /* 3D1E06C 8006DAD0 03130900 */  sra        $v0, $t1, 12
    /* 3D1E070 8006DAD4 0780013C */  lui        $at, %hi(D_8006A07C)
    /* 3D1E074 8006DAD8 7CA022AC */  sw         $v0, %lo(D_8006A07C)($at)
    /* 3D1E078 8006DADC 0EB0000C */  jal        func_8002C038
    /* 3D1E07C 8006DAE0 00000000 */   nop
    /* 3D1E080 8006DAE4 0780023C */  lui        $v0, %hi(D_8006A13C)
    /* 3D1E084 8006DAE8 3CA1428C */  lw         $v0, %lo(D_8006A13C)($v0)
    /* 3D1E088 8006DAEC 00000000 */  nop
    /* 3D1E08C 8006DAF0 0C004224 */  addiu      $v0, $v0, 0xC
    /* 3D1E090 8006DAF4 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 3D1E094 8006DAF8 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* 3D1E098 8006DAFC C1004228 */  slti       $v0, $v0, 0xC1
    /* 3D1E09C 8006DB00 03004014 */  bnez       $v0, .Llevel_55_8006DB10
    /* 3D1E0A0 8006DB04 C0000224 */   addiu     $v0, $zero, 0xC0
    /* 3D1E0A4 8006DB08 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 3D1E0A8 8006DB0C 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
  .Llevel_55_8006DB10:
    /* 3D1E0AC 8006DB10 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 3D1E0B0 8006DB14 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 3D1E0B4 8006DB18 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 3D1E0B8 8006DB1C 3CA1638C */  lw         $v1, %lo(D_8006A13C)($v1)
    /* 3D1E0BC 8006DB20 00000000 */  nop
    /* 3D1E0C0 8006DB24 23104300 */  subu       $v0, $v0, $v1
    /* 3D1E0C4 8006DB28 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 3D1E0C8 8006DB2C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 3D1E0CC 8006DB30 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 3D1E0D0 8006DB34 E8034010 */  beqz       $v0, .Llevel_55_8006EAD8
    /* 3D1E0D4 8006DB38 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 3D1E0D8 8006DB3C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 3D1E0DC 8006DB40 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 3D1E0E0 8006DB44 B6BA0108 */  j          .Llevel_55_8006EAD8
    /* 3D1E0E4 8006DB48 00000000 */   nop
  .Llevel_55_8006DB4C:
    /* 3D1E0E8 8006DB4C DBAC000C */  jal        func_8002B36C
    /* 3D1E0EC 8006DB50 800C0424 */   addiu     $a0, $zero, 0xC80
    /* 3D1E0F0 8006DB54 28000424 */  addiu      $a0, $zero, 0x28
    /* 3D1E0F4 8006DB58 C9AE000C */  jal        func_8002BB24
    /* 3D1E0F8 8006DB5C 08000524 */   addiu     $a1, $zero, 0x8
    /* 3D1E0FC 8006DB60 40010424 */  addiu      $a0, $zero, 0x140
    /* 3D1E100 8006DB64 5CAF000C */  jal        func_8002BD70
    /* 3D1E104 8006DB68 C0000524 */   addiu     $a1, $zero, 0xC0
    /* 3D1E108 8006DB6C 0780113C */  lui        $s1, %hi(D_8006A09C)
    /* 3D1E10C 8006DB70 9CA03126 */  addiu      $s1, $s1, %lo(D_8006A09C)
    /* 3D1E110 8006DB74 0000248E */  lw         $a0, 0x0($s1)
    /* 3D1E114 8006DB78 996D000C */  jal        func_8001B664
    /* 3D1E118 8006DB7C E8FF3226 */   addiu     $s2, $s1, -0x18
    /* 3D1E11C 8006DB80 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 3D1E120 8006DB84 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 3D1E124 8006DB88 00000000 */  nop
    /* 3D1E128 8006DB8C 18006200 */  mult       $v1, $v0
    /* 3D1E12C 8006DB90 0000248E */  lw         $a0, 0x0($s1)
    /* 3D1E130 8006DB94 12480000 */  mflo       $t1
    /* 3D1E134 8006DB98 03130900 */  sra        $v0, $t1, 12
    /* 3D1E138 8006DB9C 876D000C */  jal        func_8001B61C
    /* 3D1E13C 8006DBA0 1800A2AF */   sw        $v0, 0x18($sp)
    /* 3D1E140 8006DBA4 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 3D1E144 8006DBA8 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 3D1E148 8006DBAC 00000000 */  nop
    /* 3D1E14C 8006DBB0 18006200 */  mult       $v1, $v0
    /* 3D1E150 8006DBB4 1800B027 */  addiu      $s0, $sp, 0x18
    /* 3D1E154 8006DBB8 21200002 */  addu       $a0, $s0, $zero
    /* 3D1E158 8006DBBC 21280002 */  addu       $a1, $s0, $zero
    /* 3D1E15C 8006DBC0 21304002 */  addu       $a2, $s2, $zero
    /* 3D1E160 8006DBC4 12480000 */  mflo       $t1
    /* 3D1E164 8006DBC8 03130900 */  sra        $v0, $t1, 12
    /* 3D1E168 8006DBCC 806F000C */  jal        func_8001BE00
    /* 3D1E16C 8006DBD0 1C00A2AF */   sw        $v0, 0x1C($sp)
    /* 3D1E170 8006DBD4 21200002 */  addu       $a0, $s0, $zero
    /* 3D1E174 8006DBD8 21280000 */  addu       $a1, $zero, $zero
    /* 3D1E178 8006DBDC 886E000C */  jal        func_8001BA20
    /* 3D1E17C 8006DBE0 2000A0AF */   sw        $zero, 0x20($sp)
    /* 3D1E180 8006DBE4 21284000 */  addu       $a1, $v0, $zero
    /* 3D1E184 8006DBE8 8102A228 */  slti       $v0, $a1, 0x281
    /* 3D1E188 8006DBEC 05004014 */  bnez       $v0, .Llevel_55_8006DC04
    /* 3D1E18C 8006DBF0 DCFF2426 */   addiu     $a0, $s1, -0x24
    /* 3D1E190 8006DBF4 21200002 */  addu       $a0, $s0, $zero
    /* 3D1E194 8006DBF8 316F000C */  jal        func_8001BCC4
    /* 3D1E198 8006DBFC 80020624 */   addiu     $a2, $zero, 0x280
    /* 3D1E19C 8006DC00 DCFF2426 */  addiu      $a0, $s1, -0x24
  .Llevel_55_8006DC04:
    /* 3D1E1A0 8006DC04 21284002 */  addu       $a1, $s2, $zero
    /* 3D1E1A4 8006DC08 736F000C */  jal        func_8001BDCC
    /* 3D1E1A8 8006DC0C 21300002 */   addu      $a2, $s0, $zero
    /* 3D1E1AC 8006DC10 0EB0000C */  jal        func_8002C038
    /* 3D1E1B0 8006DC14 00000000 */   nop
    /* 3D1E1B4 8006DC18 0D00622A */  slti       $v0, $s3, 0xD
    /* 3D1E1B8 8006DC1C 05004010 */  beqz       $v0, .Llevel_55_8006DC34
    /* 3D1E1BC 8006DC20 00000000 */   nop
    /* 3D1E1C0 8006DC24 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 3D1E1C4 8006DC28 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 3D1E1C8 8006DC2C 11B70108 */  j          .Llevel_55_8006DC44
    /* 3D1E1CC 8006DC30 17004224 */   addiu     $v0, $v0, 0x17
  .Llevel_55_8006DC34:
    /* 3D1E1D0 8006DC34 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 3D1E1D4 8006DC38 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 3D1E1D8 8006DC3C 00000000 */  nop
    /* 3D1E1DC 8006DC40 40FF4224 */  addiu      $v0, $v0, -0xC0
  .Llevel_55_8006DC44:
    /* 3D1E1E0 8006DC44 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 3D1E1E4 8006DC48 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 3D1E1E8 8006DC4C 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 3D1E1EC 8006DC50 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 3D1E1F0 8006DC54 00000000 */  nop
    /* 3D1E1F4 8006DC58 9F034010 */  beqz       $v0, .Llevel_55_8006EAD8
    /* 3D1E1F8 8006DC5C 21880000 */   addu      $s1, $zero, $zero
    /* 3D1E1FC 8006DC60 80101300 */  sll        $v0, $s3, 2
    /* 3D1E200 8006DC64 21985300 */  addu       $s3, $v0, $s3
    /* 3D1E204 8006DC68 0780123C */  lui        $s2, %hi(D_80069FFE)
    /* 3D1E208 8006DC6C FE9F5226 */  addiu      $s2, $s2, %lo(D_80069FFE)
    /* 3D1E20C 8006DC70 3800B027 */  addiu      $s0, $sp, 0x38
  .Llevel_55_8006DC74:
    /* 3D1E210 8006DC74 4B67010C */  jal        func_80059D2C
    /* 3D1E214 8006DC78 00000000 */   nop
    /* 3D1E218 8006DC7C FF004230 */  andi       $v0, $v0, 0xFF
    /* 3D1E21C 8006DC80 2A106202 */  slt        $v0, $s3, $v0
    /* 3D1E220 8006DC84 43004010 */  beqz       $v0, .Llevel_55_8006DD94
    /* 3D1E224 8006DC88 21200000 */   addu      $a0, $zero, $zero
    /* 3D1E228 8006DC8C 63E2000C */  jal        func_8003898C
    /* 3D1E22C 8006DC90 0C000524 */   addiu     $a1, $zero, 0xC
    /* 3D1E230 8006DC94 22004426 */  addiu      $a0, $s2, 0x22
    /* 3D1E234 8006DC98 00004392 */  lbu        $v1, 0x0($s2)
    /* 3D1E238 8006DC9C 21280002 */  addu       $a1, $s0, $zero
    /* 3D1E23C 8006DCA0 80006324 */  addiu      $v1, $v1, 0x80
    /* 3D1E240 8006DCA4 21186200 */  addu       $v1, $v1, $v0
    /* 3D1E244 8006DCA8 FF006330 */  andi       $v1, $v1, 0xFF
    /* 3D1E248 8006DCAC 40180300 */  sll        $v1, $v1, 1
    /* 3D1E24C 8006DCB0 0680013C */  lui        $at, %hi(D_80061C58)
    /* 3D1E250 8006DCB4 21082300 */  addu       $at, $at, $v1
    /* 3D1E254 8006DCB8 581C2784 */  lh         $a3, %lo(D_80061C58)($at)
    /* 3D1E258 8006DCBC 21300002 */  addu       $a2, $s0, $zero
    /* 3D1E25C 8006DCC0 80100700 */  sll        $v0, $a3, 2
    /* 3D1E260 8006DCC4 21104700 */  addu       $v0, $v0, $a3
    /* 3D1E264 8006DCC8 83120200 */  sra        $v0, $v0, 10
    /* 3D1E268 8006DCCC 2800A2AF */  sw         $v0, 0x28($sp)
    /* 3D1E26C 8006DCD0 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 3D1E270 8006DCD4 21082300 */  addu       $at, $at, $v1
    /* 3D1E274 8006DCD8 D81B2384 */  lh         $v1, %lo(D_80061BD8)($at)
    /* 3D1E278 8006DCDC 0E000224 */  addiu      $v0, $zero, 0xE
    /* 3D1E27C 8006DCE0 3000A2AF */  sw         $v0, 0x30($sp)
    /* 3D1E280 8006DCE4 D4FE0224 */  addiu      $v0, $zero, -0x12C
    /* 3D1E284 8006DCE8 3800A2AF */  sw         $v0, 0x38($sp)
    /* 3D1E288 8006DCEC 38FF0224 */  addiu      $v0, $zero, -0xC8
    /* 3D1E28C 8006DCF0 3C00A0AF */  sw         $zero, 0x3C($sp)
    /* 3D1E290 8006DCF4 4000A2AF */  sw         $v0, 0x40($sp)
    /* 3D1E294 8006DCF8 80100300 */  sll        $v0, $v1, 2
    /* 3D1E298 8006DCFC 21104300 */  addu       $v0, $v0, $v1
    /* 3D1E29C 8006DD00 83120200 */  sra        $v0, $v0, 10
    /* 3D1E2A0 8006DD04 696E000C */  jal        func_8001B9A4
    /* 3D1E2A4 8006DD08 2C00A2AF */   sw        $v0, 0x2C($sp)
    /* 3D1E2A8 8006DD0C 21200000 */  addu       $a0, $zero, $zero
    /* 3D1E2AC 8006DD10 63E2000C */  jal        func_8003898C
    /* 3D1E2B0 8006DD14 50000524 */   addiu     $a1, $zero, 0x50
    /* 3D1E2B4 8006DD18 21200000 */  addu       $a0, $zero, $zero
    /* 3D1E2B8 8006DD1C 3800A38F */  lw         $v1, 0x38($sp)
    /* 3D1E2BC 8006DD20 50000524 */  addiu      $a1, $zero, 0x50
    /* 3D1E2C0 8006DD24 21186200 */  addu       $v1, $v1, $v0
    /* 3D1E2C4 8006DD28 63E2000C */  jal        func_8003898C
    /* 3D1E2C8 8006DD2C 3800A3AF */   sw        $v1, 0x38($sp)
    /* 3D1E2CC 8006DD30 21200000 */  addu       $a0, $zero, $zero
    /* 3D1E2D0 8006DD34 3C00A38F */  lw         $v1, 0x3C($sp)
    /* 3D1E2D4 8006DD38 50000524 */  addiu      $a1, $zero, 0x50
    /* 3D1E2D8 8006DD3C 21186200 */  addu       $v1, $v1, $v0
    /* 3D1E2DC 8006DD40 63E2000C */  jal        func_8003898C
    /* 3D1E2E0 8006DD44 3C00A3AF */   sw        $v1, 0x3C($sp)
    /* 3D1E2E4 8006DD48 21200002 */  addu       $a0, $s0, $zero
    /* 3D1E2E8 8006DD4C 21280002 */  addu       $a1, $s0, $zero
    /* 3D1E2EC 8006DD50 4000A38F */  lw         $v1, 0x40($sp)
    /* 3D1E2F0 8006DD54 F2FF4626 */  addiu      $a2, $s2, -0xE
    /* 3D1E2F4 8006DD58 21186200 */  addu       $v1, $v1, $v0
    /* 3D1E2F8 8006DD5C 736F000C */  jal        func_8001BDCC
    /* 3D1E2FC 8006DD60 4000A3AF */   sw        $v1, 0x40($sp)
    /* 3D1E300 8006DD64 01000424 */  addiu      $a0, $zero, 0x1
    /* 3D1E304 8006DD68 0D000524 */  addiu      $a1, $zero, 0xD
    /* 3D1E308 8006DD6C 21300002 */  addu       $a2, $s0, $zero
    /* 3D1E30C 8006DD70 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 3D1E310 8006DD74 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 3D1E314 8006DD78 00000000 */  nop
    /* 3D1E318 8006DD7C 09F84000 */  jalr       $v0
    /* 3D1E31C 8006DD80 2800A727 */   addiu     $a3, $sp, 0x28
    /* 3D1E320 8006DD84 08000324 */  addiu      $v1, $zero, 0x8
    /* 3D1E324 8006DD88 020043A0 */  sb         $v1, 0x2($v0)
    /* 3D1E328 8006DD8C 20000324 */  addiu      $v1, $zero, 0x20
    /* 3D1E32C 8006DD90 0A0043A0 */  sb         $v1, 0xA($v0)
  .Llevel_55_8006DD94:
    /* 3D1E330 8006DD94 01003126 */  addiu      $s1, $s1, 0x1
    /* 3D1E334 8006DD98 0200222A */  slti       $v0, $s1, 0x2
    /* 3D1E338 8006DD9C 4E034010 */  beqz       $v0, .Llevel_55_8006EAD8
    /* 3D1E33C 8006DDA0 00000000 */   nop
    /* 3D1E340 8006DDA4 1DB70108 */  j          .Llevel_55_8006DC74
    /* 3D1E344 8006DDA8 00000000 */   nop
  .Llevel_55_8006DDAC:
    /* 3D1E348 8006DDAC 0780103C */  lui        $s0, %hi(D_8006A0B0)
    /* 3D1E34C 8006DDB0 B0A01026 */  addiu      $s0, $s0, %lo(D_8006A0B0)
    /* 3D1E350 8006DDB4 0000028E */  lw         $v0, 0x0($s0)
    /* 3D1E354 8006DDB8 00000000 */  nop
    /* 3D1E358 8006DDBC 1F004010 */  beqz       $v0, .Llevel_55_8006DE3C
    /* 3D1E35C 8006DDC0 2800B127 */   addiu     $s1, $sp, 0x28
    /* 3D1E360 8006DDC4 686F000C */  jal        func_8001BDA0
    /* 3D1E364 8006DDC8 21202002 */   addu      $a0, $s1, $zero
    /* 3D1E368 8006DDCC 21202002 */  addu       $a0, $s1, $zero
    /* 3D1E36C 8006DDD0 21282002 */  addu       $a1, $s1, $zero
    /* 3D1E370 8006DDD4 D4FF1226 */  addiu      $s2, $s0, -0x2C
    /* 3D1E374 8006DDD8 806F000C */  jal        func_8001BE00
    /* 3D1E378 8006DDDC 21304002 */   addu      $a2, $s2, $zero
    /* 3D1E37C 8006DDE0 3000A0AF */  sw         $zero, 0x30($sp)
    /* 3D1E380 8006DDE4 21202002 */  addu       $a0, $s1, $zero
    /* 3D1E384 8006DDE8 886E000C */  jal        func_8001BA20
    /* 3D1E388 8006DDEC 21280000 */   addu      $a1, $zero, $zero
    /* 3D1E38C 8006DDF0 21284000 */  addu       $a1, $v0, $zero
    /* 3D1E390 8006DDF4 4100A228 */  slti       $v0, $a1, 0x41
    /* 3D1E394 8006DDF8 05004014 */  bnez       $v0, .Llevel_55_8006DE10
    /* 3D1E398 8006DDFC 40FF0224 */   addiu     $v0, $zero, -0xC0
    /* 3D1E39C 8006DE00 21202002 */  addu       $a0, $s1, $zero
    /* 3D1E3A0 8006DE04 316F000C */  jal        func_8001BCC4
    /* 3D1E3A4 8006DE08 40000624 */   addiu     $a2, $zero, 0x40
    /* 3D1E3A8 8006DE0C 40FF0224 */  addiu      $v0, $zero, -0xC0
  .Llevel_55_8006DE10:
    /* 3D1E3AC 8006DE10 3000A2AF */  sw         $v0, 0x30($sp)
    /* 3D1E3B0 8006DE14 C8FF1026 */  addiu      $s0, $s0, -0x38
    /* 3D1E3B4 8006DE18 21200002 */  addu       $a0, $s0, $zero
    /* 3D1E3B8 8006DE1C 21284002 */  addu       $a1, $s2, $zero
    /* 3D1E3BC 8006DE20 736F000C */  jal        func_8001BDCC
    /* 3D1E3C0 8006DE24 21302002 */   addu      $a2, $s1, $zero
    /* 3D1E3C4 8006DE28 21204002 */  addu       $a0, $s2, $zero
    /* 3D1E3C8 8006DE2C 6C6F000C */  jal        func_8001BDB0
    /* 3D1E3CC 8006DE30 21280002 */   addu      $a1, $s0, $zero
    /* 3D1E3D0 8006DE34 93B70108 */  j          .Llevel_55_8006DE4C
    /* 3D1E3D4 8006DE38 00000000 */   nop
  .Llevel_55_8006DE3C:
    /* 3D1E3D8 8006DE3C 686F000C */  jal        func_8001BDA0
    /* 3D1E3DC 8006DE40 C8FF0426 */   addiu     $a0, $s0, -0x38
    /* 3D1E3E0 8006DE44 686F000C */  jal        func_8001BDA0
    /* 3D1E3E4 8006DE48 D4FF0426 */   addiu     $a0, $s0, -0x2C
  .Llevel_55_8006DE4C:
    /* 3D1E3E8 8006DE4C 0780053C */  lui        $a1, %hi(D_8006A08C)
    /* 3D1E3EC 8006DE50 8CA0A524 */  addiu      $a1, $a1, %lo(D_8006A08C)
    /* 3D1E3F0 8006DE54 0000A28C */  lw         $v0, 0x0($a1)
    /* 3D1E3F4 8006DE58 00000000 */  nop
    /* 3D1E3F8 8006DE5C 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 3D1E3FC 8006DE60 02004010 */  beqz       $v0, .Llevel_55_8006DE6C
    /* 3D1E400 8006DE64 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 3D1E404 8006DE68 0000A2AC */  sw         $v0, 0x0($a1)
  .Llevel_55_8006DE6C:
    /* 3D1E408 8006DE6C 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 3D1E40C 8006DE70 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 3D1E410 8006DE74 3A000224 */  addiu      $v0, $zero, 0x3A
    /* 3D1E414 8006DE78 17036214 */  bne        $v1, $v0, .Llevel_55_8006EAD8
    /* 3D1E418 8006DE7C 00000000 */   nop
    /* 3D1E41C 8006DE80 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 3D1E420 8006DE84 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 3D1E424 8006DE88 00000000 */  nop
    /* 3D1E428 8006DE8C 12034010 */  beqz       $v0, .Llevel_55_8006EAD8
    /* 3D1E42C 8006DE90 00000000 */   nop
    /* 3D1E430 8006DE94 0680023C */  lui        $v0, %hi(D_80067008)
    /* 3D1E434 8006DE98 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 3D1E438 8006DE9C 00000000 */  nop
    /* 3D1E43C 8006DEA0 01004230 */  andi       $v0, $v0, 0x1
    /* 3D1E440 8006DEA4 0C034010 */  beqz       $v0, .Llevel_55_8006EAD8
    /* 3D1E444 8006DEA8 5800B027 */   addiu     $s0, $sp, 0x58
    /* 3D1E448 8006DEAC 21200002 */  addu       $a0, $s0, $zero
    /* 3D1E44C 8006DEB0 64FFA524 */  addiu      $a1, $a1, -0x9C
    /* 3D1E450 8006DEB4 0E000224 */  addiu      $v0, $zero, 0xE
    /* 3D1E454 8006DEB8 4800A0AF */  sw         $zero, 0x48($sp)
    /* 3D1E458 8006DEBC 4C00A0AF */  sw         $zero, 0x4C($sp)
    /* 3D1E45C 8006DEC0 6C6F000C */  jal        func_8001BDB0
    /* 3D1E460 8006DEC4 5000A2AF */   sw        $v0, 0x50($sp)
    /* 3D1E464 8006DEC8 21200000 */  addu       $a0, $zero, $zero
    /* 3D1E468 8006DECC 63E2000C */  jal        func_8003898C
    /* 3D1E46C 8006DED0 2C010524 */   addiu     $a1, $zero, 0x12C
    /* 3D1E470 8006DED4 21200000 */  addu       $a0, $zero, $zero
    /* 3D1E474 8006DED8 5800A38F */  lw         $v1, 0x58($sp)
    /* 3D1E478 8006DEDC 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 3D1E47C 8006DEE0 21186200 */  addu       $v1, $v1, $v0
    /* 3D1E480 8006DEE4 63E2000C */  jal        func_8003898C
    /* 3D1E484 8006DEE8 5800A3AF */   sw        $v1, 0x58($sp)
    /* 3D1E488 8006DEEC 21200000 */  addu       $a0, $zero, $zero
    /* 3D1E48C 8006DEF0 5C00A38F */  lw         $v1, 0x5C($sp)
    /* 3D1E490 8006DEF4 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 3D1E494 8006DEF8 21186200 */  addu       $v1, $v1, $v0
    /* 3D1E498 8006DEFC 63E2000C */  jal        func_8003898C
    /* 3D1E49C 8006DF00 5C00A3AF */   sw        $v1, 0x5C($sp)
    /* 3D1E4A0 8006DF04 01000424 */  addiu      $a0, $zero, 0x1
    /* 3D1E4A4 8006DF08 0D000524 */  addiu      $a1, $zero, 0xD
    /* 3D1E4A8 8006DF0C 21300002 */  addu       $a2, $s0, $zero
    /* 3D1E4AC 8006DF10 4800A727 */  addiu      $a3, $sp, 0x48
    /* 3D1E4B0 8006DF14 6000A38F */  lw         $v1, 0x60($sp)
    /* 3D1E4B4 8006DF18 0680083C */  lui        $t0, %hi(D_800670FC)
    /* 3D1E4B8 8006DF1C FC70088D */  lw         $t0, %lo(D_800670FC)($t0)
    /* 3D1E4BC 8006DF20 21186200 */  addu       $v1, $v1, $v0
    /* 3D1E4C0 8006DF24 09F80001 */  jalr       $t0
    /* 3D1E4C4 8006DF28 6000A3AF */   sw        $v1, 0x60($sp)
    /* 3D1E4C8 8006DF2C 06000324 */  addiu      $v1, $zero, 0x6
    /* 3D1E4CC 8006DF30 020043A0 */  sb         $v1, 0x2($v0)
    /* 3D1E4D0 8006DF34 20000324 */  addiu      $v1, $zero, 0x20
    /* 3D1E4D4 8006DF38 B6BA0108 */  j          .Llevel_55_8006EAD8
    /* 3D1E4D8 8006DF3C 0A0043A0 */   sb        $v1, 0xA($v0)
  .Llevel_55_8006DF40:
    /* 3D1E4DC 8006DF40 4800A427 */  addiu      $a0, $sp, 0x48
    /* 3D1E4E0 8006DF44 0780113C */  lui        $s1, %hi(D_8006A144)
    /* 3D1E4E4 8006DF48 44A13126 */  addiu      $s1, $s1, %lo(D_8006A144)
    /* 3D1E4E8 8006DF4C 21282002 */  addu       $a1, $s1, $zero
    /* 3D1E4EC 8006DF50 A5AD000C */  jal        func_8002B694
    /* 3D1E4F0 8006DF54 21300000 */   addu      $a2, $zero, $zero
    /* 3D1E4F4 8006DF58 4C00A28F */  lw         $v0, 0x4C($sp)
    /* 3D1E4F8 8006DF5C 0780043C */  lui        $a0, %hi(D_8006A08C)
    /* 3D1E4FC 8006DF60 8CA0848C */  lw         $a0, %lo(D_8006A08C)($a0)
    /* 3D1E500 8006DF64 23100200 */  negu       $v0, $v0
    /* 3D1E504 8006DF68 80180200 */  sll        $v1, $v0, 2
    /* 3D1E508 8006DF6C 21186200 */  addu       $v1, $v1, $v0
    /* 3D1E50C 8006DF70 80180300 */  sll        $v1, $v1, 2
    /* 3D1E510 8006DF74 C3910300 */  sra        $s2, $v1, 7
    /* 3D1E514 8006DF78 C3200400 */  sra        $a0, $a0, 3
    /* 3D1E518 8006DF7C 4800A38F */  lw         $v1, 0x48($sp)
    /* 3D1E51C 8006DF80 00FC8424 */  addiu      $a0, $a0, -0x400
    /* 3D1E520 8006DF84 5800A4AF */  sw         $a0, 0x58($sp)
    /* 3D1E524 8006DF88 80100300 */  sll        $v0, $v1, 2
    /* 3D1E528 8006DF8C 21104300 */  addu       $v0, $v0, $v1
    /* 3D1E52C 8006DF90 80100200 */  sll        $v0, $v0, 2
    /* 3D1E530 8006DF94 24008104 */  bgez       $a0, .Llevel_55_8006E028
    /* 3D1E534 8006DF98 C3990200 */   sra       $s3, $v0, 7
    /* 3D1E538 8006DF9C 5000B027 */  addiu      $s0, $sp, 0x50
    /* 3D1E53C 8006DFA0 21200002 */  addu       $a0, $s0, $zero
    /* 3D1E540 8006DFA4 21280002 */  addu       $a1, $s0, $zero
    /* 3D1E544 8006DFA8 ACFE3126 */  addiu      $s1, $s1, -0x154
    /* 3D1E548 8006DFAC 21302002 */  addu       $a2, $s1, $zero
    /* 3D1E54C 8006DFB0 0780023C */  lui        $v0, %hi(D_8006A084)
    /* 3D1E550 8006DFB4 84A0428C */  lw         $v0, %lo(D_8006A084)($v0)
    /* 3D1E554 8006DFB8 0780033C */  lui        $v1, %hi(D_8006A088)
    /* 3D1E558 8006DFBC 88A0638C */  lw         $v1, %lo(D_8006A088)($v1)
    /* 3D1E55C 8006DFC0 C3100200 */  sra        $v0, $v0, 3
    /* 3D1E560 8006DFC4 C3180300 */  sra        $v1, $v1, 3
    /* 3D1E564 8006DFC8 5000A2AF */  sw         $v0, 0x50($sp)
    /* 3D1E568 8006DFCC 736F000C */  jal        func_8001BDCC
    /* 3D1E56C 8006DFD0 5400A3AF */   sw        $v1, 0x54($sp)
    /* 3D1E570 8006DFD4 21202002 */  addu       $a0, $s1, $zero
    /* 3D1E574 8006DFD8 21280002 */  addu       $a1, $s0, $zero
    /* 3D1E578 8006DFDC 867D000C */  jal        func_8001F618
    /* 3D1E57C 8006DFE0 02000624 */   addiu     $a2, $zero, 0x2
    /* 3D1E580 8006DFE4 11004014 */  bnez       $v0, .Llevel_55_8006E02C
    /* 3D1E584 8006DFE8 19000224 */   addiu     $v0, $zero, 0x19
    /* 3D1E588 8006DFEC 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 3D1E58C 8006DFF0 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 3D1E590 8006DFF4 0780033C */  lui        $v1, %hi(D_8006AB78)
    /* 3D1E594 8006DFF8 78AB638C */  lw         $v1, %lo(D_8006AB78)($v1)
    /* 3D1E598 8006DFFC 00000000 */  nop
    /* 3D1E59C 8006E000 23104300 */  subu       $v0, $v0, $v1
    /* 3D1E5A0 8006E004 C3100200 */  sra        $v0, $v0, 3
    /* 3D1E5A4 8006E008 4C00A2AF */  sw         $v0, 0x4C($sp)
    /* 3D1E5A8 8006E00C 0B004228 */  slti       $v0, $v0, 0xB
    /* 3D1E5AC 8006E010 02004014 */  bnez       $v0, .Llevel_55_8006E01C
    /* 3D1E5B0 8006E014 0A000224 */   addiu     $v0, $zero, 0xA
    /* 3D1E5B4 8006E018 4C00A2AF */  sw         $v0, 0x4C($sp)
  .Llevel_55_8006E01C:
    /* 3D1E5B8 8006E01C 4C00A28F */  lw         $v0, 0x4C($sp)
    /* 3D1E5BC 8006E020 00000000 */  nop
    /* 3D1E5C0 8006E024 21904202 */  addu       $s2, $s2, $v0
  .Llevel_55_8006E028:
    /* 3D1E5C4 8006E028 19000224 */  addiu      $v0, $zero, 0x19
  .Llevel_55_8006E02C:
    /* 3D1E5C8 8006E02C 0680033C */  lui        $v1, %hi(D_80066F90)
    /* 3D1E5CC 8006E030 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* 3D1E5D0 8006E034 0780043C */  lui        $a0, %hi(D_8006A0F0)
    /* 3D1E5D4 8006E038 F0A0848C */  lw         $a0, %lo(D_8006A0F0)($a0)
    /* 3D1E5D8 8006E03C 07006214 */  bne        $v1, $v0, .Llevel_55_8006E05C
    /* 3D1E5DC 8006E040 00000000 */   nop
    /* 3D1E5E0 8006E044 0780023C */  lui        $v0, %hi(D_8006ABF8)
    /* 3D1E5E4 8006E048 F8AB4290 */  lbu        $v0, %lo(D_8006ABF8)($v0)
    /* 3D1E5E8 8006E04C 00000000 */  nop
    /* 3D1E5EC 8006E050 02004010 */  beqz       $v0, .Llevel_55_8006E05C
    /* 3D1E5F0 8006E054 00000000 */   nop
    /* 3D1E5F4 8006E058 08CF0434 */  ori        $a0, $zero, 0xCF08
  .Llevel_55_8006E05C:
    /* 3D1E5F8 8006E05C 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 3D1E5FC 8006E060 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 3D1E600 8006E064 00000000 */  nop
    /* 3D1E604 8006E068 23188200 */  subu       $v1, $a0, $v0
    /* 3D1E608 8006E06C 00106228 */  slti       $v0, $v1, 0x1000
    /* 3D1E60C 8006E070 12004010 */  beqz       $v0, .Llevel_55_8006E0BC
    /* 3D1E610 8006E074 40100300 */   sll       $v0, $v1, 1
    /* 3D1E614 8006E078 21104300 */  addu       $v0, $v0, $v1
    /* 3D1E618 8006E07C C0100200 */  sll        $v0, $v0, 3
    /* 3D1E61C 8006E080 21104300 */  addu       $v0, $v0, $v1
    /* 3D1E620 8006E084 40110200 */  sll        $v0, $v0, 5
    /* 3D1E624 8006E088 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 3D1E628 8006E08C 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 3D1E62C 8006E090 03230200 */  sra        $a0, $v0, 12
    /* 3D1E630 8006E094 23188300 */  subu       $v1, $a0, $v1
    /* 3D1E634 8006E098 FF0F6430 */  andi       $a0, $v1, 0xFFF
    /* 3D1E638 8006E09C 01088228 */  slti       $v0, $a0, 0x801
    /* 3D1E63C 8006E0A0 03004014 */  bnez       $v0, .Llevel_55_8006E0B0
    /* 3D1E640 8006E0A4 2A109200 */   slt       $v0, $a0, $s2
    /* 3D1E644 8006E0A8 00F08424 */  addiu      $a0, $a0, -0x1000
    /* 3D1E648 8006E0AC 2A109200 */  slt        $v0, $a0, $s2
  .Llevel_55_8006E0B0:
    /* 3D1E64C 8006E0B0 02004010 */  beqz       $v0, .Llevel_55_8006E0BC
    /* 3D1E650 8006E0B4 00000000 */   nop
    /* 3D1E654 8006E0B8 21908000 */  addu       $s2, $a0, $zero
  .Llevel_55_8006E0BC:
    /* 3D1E658 8006E0BC 0780043C */  lui        $a0, %hi(D_8006A05C)
    /* 3D1E65C 8006E0C0 5CA08424 */  addiu      $a0, $a0, %lo(D_8006A05C)
    /* 3D1E660 8006E0C4 0000828C */  lw         $v0, 0x0($a0)
    /* 3D1E664 8006E0C8 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 3D1E668 8006E0CC 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 3D1E66C 8006E0D0 21105300 */  addu       $v0, $v0, $s3
    /* 3D1E670 8006E0D4 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* 3D1E674 8006E0D8 21187200 */  addu       $v1, $v1, $s2
    /* 3D1E678 8006E0DC FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 3D1E67C 8006E0E0 000082AC */  sw         $v0, 0x0($a0)
    /* 3D1E680 8006E0E4 01086228 */  slti       $v0, $v1, 0x801
    /* 3D1E684 8006E0E8 0780013C */  lui        $at, %hi(D_8006A058)
    /* 3D1E688 8006E0EC 58A023AC */  sw         $v1, %lo(D_8006A058)($at)
    /* 3D1E68C 8006E0F0 03004014 */  bnez       $v0, .Llevel_55_8006E100
    /* 3D1E690 8006E0F4 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 3D1E694 8006E0F8 0780013C */  lui        $at, %hi(D_8006A058)
    /* 3D1E698 8006E0FC 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_55_8006E100:
    /* 3D1E69C 8006E100 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 3D1E6A0 8006E104 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 3D1E6A4 8006E108 00000000 */  nop
    /* 3D1E6A8 8006E10C E0FC4228 */  slti       $v0, $v0, -0x320
    /* 3D1E6AC 8006E110 03004010 */  beqz       $v0, .Llevel_55_8006E120
    /* 3D1E6B0 8006E114 E0FC0224 */   addiu     $v0, $zero, -0x320
    /* 3D1E6B4 8006E118 0780013C */  lui        $at, %hi(D_8006A058)
    /* 3D1E6B8 8006E11C 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_55_8006E120:
    /* 3D1E6BC 8006E120 0780023C */  lui        $v0, %hi(D_8006A058)
    /* 3D1E6C0 8006E124 58A0428C */  lw         $v0, %lo(D_8006A058)($v0)
    /* 3D1E6C4 8006E128 00000000 */  nop
    /* 3D1E6C8 8006E12C 21034228 */  slti       $v0, $v0, 0x321
    /* 3D1E6CC 8006E130 03004014 */  bnez       $v0, .Llevel_55_8006E140
    /* 3D1E6D0 8006E134 20030224 */   addiu     $v0, $zero, 0x320
    /* 3D1E6D4 8006E138 0780013C */  lui        $at, %hi(D_8006A058)
    /* 3D1E6D8 8006E13C 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
  .Llevel_55_8006E140:
    /* 3D1E6DC 8006E140 0780023C */  lui        $v0, %hi(D_80069894)
    /* 3D1E6E0 8006E144 9498428C */  lw         $v0, %lo(D_80069894)($v0)
    /* 3D1E6E4 8006E148 00000000 */  nop
    /* 3D1E6E8 8006E14C 46004104 */  bgez       $v0, .Llevel_55_8006E268
    /* 3D1E6EC 8006E150 00000000 */   nop
    /* 3D1E6F0 8006E154 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 3D1E6F4 8006E158 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 3D1E6F8 8006E15C 00000000 */  nop
    /* 3D1E6FC 8006E160 07006104 */  bgez       $v1, .Llevel_55_8006E180
    /* 3D1E700 8006E164 00000000 */   nop
    /* 3D1E704 8006E168 0680043C */  lui        $a0, %hi(D_80060184)
    /* 3D1E708 8006E16C 8401848C */  lw         $a0, %lo(D_80060184)($a0)
    /* 3D1E70C 8006E170 0680023C */  lui        $v0, %hi(D_80060180)
    /* 3D1E710 8006E174 8001428C */  lw         $v0, %lo(D_80060180)($v0)
    /* 3D1E714 8006E178 68B80108 */  j          .Llevel_55_8006E1A0
    /* 3D1E718 8006E17C 23108200 */   subu      $v0, $a0, $v0
  .Llevel_55_8006E180:
    /* 3D1E71C 8006E180 15006018 */  blez       $v1, .Llevel_55_8006E1D8
    /* 3D1E720 8006E184 00000000 */   nop
    /* 3D1E724 8006E188 0680023C */  lui        $v0, %hi(D_80060188)
    /* 3D1E728 8006E18C 8801428C */  lw         $v0, %lo(D_80060188)($v0)
    /* 3D1E72C 8006E190 0680043C */  lui        $a0, %hi(D_80060184)
    /* 3D1E730 8006E194 8401848C */  lw         $a0, %lo(D_80060184)($a0)
    /* 3D1E734 8006E198 00000000 */  nop
    /* 3D1E738 8006E19C 23104400 */  subu       $v0, $v0, $a0
  .Llevel_55_8006E1A0:
    /* 3D1E73C 8006E1A0 18006200 */  mult       $v1, $v0
    /* 3D1E740 8006E1A4 12100000 */  mflo       $v0
    /* 3D1E744 8006E1A8 EB51033C */  lui        $v1, (0x51EB851F >> 16)
    /* 3D1E748 8006E1AC 1F856334 */  ori        $v1, $v1, (0x51EB851F & 0xFFFF)
    /* 3D1E74C 8006E1B0 18004300 */  mult       $v0, $v1
    /* 3D1E750 8006E1B4 C3170200 */  sra        $v0, $v0, 31
    /* 3D1E754 8006E1B8 10480000 */  mfhi       $t1
    /* 3D1E758 8006E1BC 031A0900 */  sra        $v1, $t1, 8
    /* 3D1E75C 8006E1C0 23186200 */  subu       $v1, $v1, $v0
    /* 3D1E760 8006E1C4 21208300 */  addu       $a0, $a0, $v1
    /* 3D1E764 8006E1C8 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 3D1E768 8006E1CC A4A024AC */  sw         $a0, %lo(D_8006A0A4)($at)
    /* 3D1E76C 8006E1D0 7AB80108 */  j          .Llevel_55_8006E1E8
    /* 3D1E770 8006E1D4 00000000 */   nop
  .Llevel_55_8006E1D8:
    /* 3D1E774 8006E1D8 0680023C */  lui        $v0, %hi(D_80060184)
    /* 3D1E778 8006E1DC 8401428C */  lw         $v0, %lo(D_80060184)($v0)
    /* 3D1E77C 8006E1E0 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 3D1E780 8006E1E4 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
  .Llevel_55_8006E1E8:
    /* 3D1E784 8006E1E8 0780053C */  lui        $a1, %hi(D_8006A13C)
    /* 3D1E788 8006E1EC 3CA1A524 */  addiu      $a1, $a1, %lo(D_8006A13C)
    /* 3D1E78C 8006E1F0 0780023C */  lui        $v0, %hi(D_8006A0A4)
    /* 3D1E790 8006E1F4 A4A0428C */  lw         $v0, %lo(D_8006A0A4)($v0)
    /* 3D1E794 8006E1F8 0780043C */  lui        $a0, %hi(D_8006A0A8)
    /* 3D1E798 8006E1FC A8A0848C */  lw         $a0, %lo(D_8006A0A8)($a0)
    /* 3D1E79C 8006E200 0000A38C */  lw         $v1, 0x0($a1)
    /* 3D1E7A0 8006E204 23104400 */  subu       $v0, $v0, $a0
    /* 3D1E7A4 8006E208 23104300 */  subu       $v0, $v0, $v1
    /* 3D1E7A8 8006E20C 80110200 */  sll        $v0, $v0, 6
    /* 3D1E7AC 8006E210 83110200 */  sra        $v0, $v0, 6
    /* 3D1E7B0 8006E214 21186200 */  addu       $v1, $v1, $v0
    /* 3D1E7B4 8006E218 0000A3AC */  sw         $v1, 0x0($a1)
    /* 3D1E7B8 8006E21C 83190300 */  sra        $v1, $v1, 6
    /* 3D1E7BC 8006E220 21208300 */  addu       $a0, $a0, $v1
    /* 3D1E7C0 8006E224 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 3D1E7C4 8006E228 A8A024AC */  sw         $a0, %lo(D_8006A0A8)($at)
    /* 3D1E7C8 8006E22C 00088428 */  slti       $a0, $a0, 0x800
    /* 3D1E7CC 8006E230 03008010 */  beqz       $a0, .Llevel_55_8006E240
    /* 3D1E7D0 8006E234 00080224 */   addiu     $v0, $zero, 0x800
    /* 3D1E7D4 8006E238 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 3D1E7D8 8006E23C A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_55_8006E240:
    /* 3D1E7DC 8006E240 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 3D1E7E0 8006E244 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 3D1E7E4 8006E248 00000000 */  nop
    /* 3D1E7E8 8006E24C 014B4228 */  slti       $v0, $v0, 0x4B01
    /* 3D1E7EC 8006E250 41004014 */  bnez       $v0, .Llevel_55_8006E358
    /* 3D1E7F0 8006E254 004B0224 */   addiu     $v0, $zero, 0x4B00
    /* 3D1E7F4 8006E258 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 3D1E7F8 8006E25C A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 3D1E7FC 8006E260 D6B80108 */  j          .Llevel_55_8006E358
    /* 3D1E800 8006E264 00000000 */   nop
  .Llevel_55_8006E268:
    /* 3D1E804 8006E268 0680033C */  lui        $v1, %hi(D_80066F90)
    /* 3D1E808 8006E26C 906F638C */  lw         $v1, %lo(D_80066F90)($v1)
    /* 3D1E80C 8006E270 19000224 */  addiu      $v0, $zero, 0x19
    /* 3D1E810 8006E274 13006214 */  bne        $v1, $v0, .Llevel_55_8006E2C4
    /* 3D1E814 8006E278 00000000 */   nop
    /* 3D1E818 8006E27C 0780023C */  lui        $v0, %hi(D_8006ABF8)
    /* 3D1E81C 8006E280 F8AB4290 */  lbu        $v0, %lo(D_8006ABF8)($v0)
    /* 3D1E820 8006E284 00000000 */  nop
    /* 3D1E824 8006E288 0E004010 */  beqz       $v0, .Llevel_55_8006E2C4
    /* 3D1E828 8006E28C 08CF0234 */   ori       $v0, $zero, 0xCF08
    /* 3D1E82C 8006E290 0780033C */  lui        $v1, %hi(D_80069FF8)
    /* 3D1E830 8006E294 F89F638C */  lw         $v1, %lo(D_80069FF8)($v1)
    /* 3D1E834 8006E298 00000000 */  nop
    /* 3D1E838 8006E29C 23204300 */  subu       $a0, $v0, $v1
    /* 3D1E83C 8006E2A0 03008104 */  bgez       $a0, .Llevel_55_8006E2B0
    /* 3D1E840 8006E2A4 00000000 */   nop
    /* 3D1E844 8006E2A8 C6B80108 */  j          .Llevel_55_8006E318
    /* 3D1E848 8006E2AC 00080224 */   addiu     $v0, $zero, 0x800
  .Llevel_55_8006E2B0:
    /* 3D1E84C 8006E2B0 F06F000C */  jal        func_8001BFC0
    /* 3D1E850 8006E2B4 00000000 */   nop
    /* 3D1E854 8006E2B8 80110200 */  sll        $v0, $v0, 6
    /* 3D1E858 8006E2BC C6B80108 */  j          .Llevel_55_8006E318
    /* 3D1E85C 8006E2C0 00084224 */   addiu     $v0, $v0, 0x800
  .Llevel_55_8006E2C4:
    /* 3D1E860 8006E2C4 0780033C */  lui        $v1, %hi(D_8006A0F0)
    /* 3D1E864 8006E2C8 F0A0638C */  lw         $v1, %lo(D_8006A0F0)($v1)
    /* 3D1E868 8006E2CC 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 3D1E86C 8006E2D0 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 3D1E870 8006E2D4 00000000 */  nop
    /* 3D1E874 8006E2D8 23206200 */  subu       $a0, $v1, $v0
    /* 3D1E878 8006E2DC 0A008104 */  bgez       $a0, .Llevel_55_8006E308
    /* 3D1E87C 8006E2E0 00000000 */   nop
    /* 3D1E880 8006E2E4 F06F000C */  jal        func_8001BFC0
    /* 3D1E884 8006E2E8 23200400 */   negu      $a0, $a0
    /* 3D1E888 8006E2EC C0110200 */  sll        $v0, $v0, 7
    /* 3D1E88C 8006E2F0 40100324 */  addiu      $v1, $zero, 0x1040
    /* 3D1E890 8006E2F4 23186200 */  subu       $v1, $v1, $v0
    /* 3D1E894 8006E2F8 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 3D1E898 8006E2FC A8A023AC */  sw         $v1, %lo(D_8006A0A8)($at)
    /* 3D1E89C 8006E300 C8B80108 */  j          .Llevel_55_8006E320
    /* 3D1E8A0 8006E304 00000000 */   nop
  .Llevel_55_8006E308:
    /* 3D1E8A4 8006E308 F06F000C */  jal        func_8001BFC0
    /* 3D1E8A8 8006E30C 00000000 */   nop
    /* 3D1E8AC 8006E310 80110200 */  sll        $v0, $v0, 6
    /* 3D1E8B0 8006E314 40104224 */  addiu      $v0, $v0, 0x1040
  .Llevel_55_8006E318:
    /* 3D1E8B4 8006E318 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 3D1E8B8 8006E31C A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
  .Llevel_55_8006E320:
    /* 3D1E8BC 8006E320 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 3D1E8C0 8006E324 A8A06324 */  addiu      $v1, $v1, %lo(D_8006A0A8)
    /* 3D1E8C4 8006E328 0000628C */  lw         $v0, 0x0($v1)
    /* 3D1E8C8 8006E32C 00000000 */  nop
    /* 3D1E8CC 8006E330 01594228 */  slti       $v0, $v0, 0x5901
    /* 3D1E8D0 8006E334 02004014 */  bnez       $v0, .Llevel_55_8006E340
    /* 3D1E8D4 8006E338 00590224 */   addiu     $v0, $zero, 0x5900
    /* 3D1E8D8 8006E33C 000062AC */  sw         $v0, 0x0($v1)
  .Llevel_55_8006E340:
    /* 3D1E8DC 8006E340 0000628C */  lw         $v0, 0x0($v1)
    /* 3D1E8E0 8006E344 00000000 */  nop
    /* 3D1E8E4 8006E348 00084228 */  slti       $v0, $v0, 0x800
    /* 3D1E8E8 8006E34C 02004010 */  beqz       $v0, .Llevel_55_8006E358
    /* 3D1E8EC 8006E350 00080224 */   addiu     $v0, $zero, 0x800
    /* 3D1E8F0 8006E354 000062AC */  sw         $v0, 0x0($v1)
  .Llevel_55_8006E358:
    /* 3D1E8F4 8006E358 0780043C */  lui        $a0, %hi(D_8006A058)
    /* 3D1E8F8 8006E35C 58A0848C */  lw         $a0, %lo(D_8006A058)($a0)
    /* 3D1E8FC 8006E360 996D000C */  jal        func_8001B664
    /* 3D1E900 8006E364 00000000 */   nop
    /* 3D1E904 8006E368 40110200 */  sll        $v0, $v0, 5
    /* 3D1E908 8006E36C 23100200 */  negu       $v0, $v0
    /* 3D1E90C 8006E370 18006202 */  mult       $s3, $v0
    /* 3D1E910 8006E374 0780033C */  lui        $v1, %hi(D_8006A144)
    /* 3D1E914 8006E378 44A1638C */  lw         $v1, %lo(D_8006A144)($v1)
    /* 3D1E918 8006E37C 0780053C */  lui        $a1, %hi(D_8006A054)
    /* 3D1E91C 8006E380 54A0A58C */  lw         $a1, %lo(D_8006A054)($a1)
    /* 3D1E920 8006E384 00110300 */  sll        $v0, $v1, 4
    /* 3D1E924 8006E388 83110200 */  sra        $v0, $v0, 6
    /* 3D1E928 8006E38C 12480000 */  mflo       $t1
    /* 3D1E92C 8006E390 03230900 */  sra        $a0, $t1, 12
    /* 3D1E930 8006E394 23208200 */  subu       $a0, $a0, $v0
    /* 3D1E934 8006E398 80110500 */  sll        $v0, $a1, 6
    /* 3D1E938 8006E39C 83110200 */  sra        $v0, $v0, 6
    /* 3D1E93C 8006E3A0 23208200 */  subu       $a0, $a0, $v0
    /* 3D1E940 8006E3A4 21186400 */  addu       $v1, $v1, $a0
    /* 3D1E944 8006E3A8 0780013C */  lui        $at, %hi(D_8006A144)
    /* 3D1E948 8006E3AC 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 3D1E94C 8006E3B0 83190300 */  sra        $v1, $v1, 6
    /* 3D1E950 8006E3B4 2128A300 */  addu       $a1, $a1, $v1
    /* 3D1E954 8006E3B8 FF0FA530 */  andi       $a1, $a1, 0xFFF
    /* 3D1E958 8006E3BC 0108A228 */  slti       $v0, $a1, 0x801
    /* 3D1E95C 8006E3C0 0780013C */  lui        $at, %hi(D_8006A054)
    /* 3D1E960 8006E3C4 54A025AC */  sw         $a1, %lo(D_8006A054)($at)
    /* 3D1E964 8006E3C8 03004014 */  bnez       $v0, .Llevel_55_8006E3D8
    /* 3D1E968 8006E3CC 00F0A224 */   addiu     $v0, $a1, -0x1000
    /* 3D1E96C 8006E3D0 0780013C */  lui        $at, %hi(D_8006A054)
    /* 3D1E970 8006E3D4 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_55_8006E3D8:
    /* 3D1E974 8006E3D8 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 3D1E978 8006E3DC 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 3D1E97C 8006E3E0 00000000 */  nop
    /* 3D1E980 8006E3E4 00FD4228 */  slti       $v0, $v0, -0x300
    /* 3D1E984 8006E3E8 03004010 */  beqz       $v0, .Llevel_55_8006E3F8
    /* 3D1E988 8006E3EC 00FD0224 */   addiu     $v0, $zero, -0x300
    /* 3D1E98C 8006E3F0 0780013C */  lui        $at, %hi(D_8006A054)
    /* 3D1E990 8006E3F4 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_55_8006E3F8:
    /* 3D1E994 8006E3F8 0780023C */  lui        $v0, %hi(D_8006A054)
    /* 3D1E998 8006E3FC 54A0428C */  lw         $v0, %lo(D_8006A054)($v0)
    /* 3D1E99C 8006E400 00000000 */  nop
    /* 3D1E9A0 8006E404 01034228 */  slti       $v0, $v0, 0x301
    /* 3D1E9A4 8006E408 03004014 */  bnez       $v0, .Llevel_55_8006E418
    /* 3D1E9A8 8006E40C 00030224 */   addiu     $v0, $zero, 0x300
    /* 3D1E9AC 8006E410 0780013C */  lui        $at, %hi(D_8006A054)
    /* 3D1E9B0 8006E414 54A022AC */  sw         $v0, %lo(D_8006A054)($at)
  .Llevel_55_8006E418:
    /* 3D1E9B4 8006E418 6FAF000C */  jal        func_8002BDBC
    /* 3D1E9B8 8006E41C 00000000 */   nop
    /* 3D1E9BC 8006E420 0780043C */  lui        $a0, %hi(D_8006A044)
    /* 3D1E9C0 8006E424 44A0848C */  lw         $a0, %lo(D_8006A044)($a0)
    /* 3D1E9C4 8006E428 00000000 */  nop
    /* 3D1E9C8 8006E42C 1C008014 */  bnez       $a0, .Llevel_55_8006E4A0
    /* 3D1E9CC 8006E430 00000000 */   nop
    /* 3D1E9D0 8006E434 0680023C */  lui        $v0, %hi(D_80066F38)
    /* 3D1E9D4 8006E438 386F428C */  lw         $v0, %lo(D_80066F38)($v0)
    /* 3D1E9D8 8006E43C 00000000 */  nop
    /* 3D1E9DC 8006E440 0400428C */  lw         $v0, 0x4($v0)
    /* 3D1E9E0 8006E444 00000000 */  nop
    /* 3D1E9E4 8006E448 40004230 */  andi       $v0, $v0, 0x40
    /* 3D1E9E8 8006E44C 46004010 */  beqz       $v0, .Llevel_55_8006E568
    /* 3D1E9EC 8006E450 00000000 */   nop
    /* 3D1E9F0 8006E454 0780023C */  lui        $v0, %hi(D_8006A0F0)
    /* 3D1E9F4 8006E458 F0A0428C */  lw         $v0, %lo(D_8006A0F0)($v0)
    /* 3D1E9F8 8006E45C 0780033C */  lui        $v1, %hi(D_80069FF8)
    /* 3D1E9FC 8006E460 F89F638C */  lw         $v1, %lo(D_80069FF8)($v1)
    /* 3D1EA00 8006E464 00FE4224 */  addiu      $v0, $v0, -0x200
    /* 3D1EA04 8006E468 2A186200 */  slt        $v1, $v1, $v0
    /* 3D1EA08 8006E46C 3E006010 */  beqz       $v1, .Llevel_55_8006E568
    /* 3D1EA0C 8006E470 21000224 */   addiu     $v0, $zero, 0x21
    /* 3D1EA10 8006E474 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 3D1EA14 8006E478 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 3D1EA18 8006E47C 00000000 */  nop
    /* 3D1EA1C 8006E480 39006214 */  bne        $v1, $v0, .Llevel_55_8006E568
    /* 3D1EA20 8006E484 01000224 */   addiu     $v0, $zero, 0x1
    /* 3D1EA24 8006E488 0780013C */  lui        $at, %hi(D_8006A044)
    /* 3D1EA28 8006E48C 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 3D1EA2C 8006E490 0780013C */  lui        $at, %hi(D_8006A150)
    /* 3D1EA30 8006E494 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 3D1EA34 8006E498 5AB90108 */  j          .Llevel_55_8006E568
    /* 3D1EA38 8006E49C 00000000 */   nop
  .Llevel_55_8006E4A0:
    /* 3D1EA3C 8006E4A0 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 3D1EA40 8006E4A4 F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 3D1EA44 8006E4A8 0780033C */  lui        $v1, %hi(D_8006A0F0)
    /* 3D1EA48 8006E4AC F0A0638C */  lw         $v1, %lo(D_8006A0F0)($v1)
    /* 3D1EA4C 8006E4B0 00000000 */  nop
    /* 3D1EA50 8006E4B4 2A104300 */  slt        $v0, $v0, $v1
    /* 3D1EA54 8006E4B8 05004014 */  bnez       $v0, .Llevel_55_8006E4D0
    /* 3D1EA58 8006E4BC 01000224 */   addiu     $v0, $zero, 0x1
    /* 3D1EA5C 8006E4C0 0780013C */  lui        $at, %hi(D_8006A044)
    /* 3D1EA60 8006E4C4 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 3D1EA64 8006E4C8 5AB90108 */  j          .Llevel_55_8006E568
    /* 3D1EA68 8006E4CC 00000000 */   nop
  .Llevel_55_8006E4D0:
    /* 3D1EA6C 8006E4D0 11008214 */  bne        $a0, $v0, .Llevel_55_8006E518
    /* 3D1EA70 8006E4D4 00000000 */   nop
    /* 3D1EA74 8006E4D8 0780023C */  lui        $v0, %hi(D_8006A150)
    /* 3D1EA78 8006E4DC 50A1428C */  lw         $v0, %lo(D_8006A150)($v0)
    /* 3D1EA7C 8006E4E0 00000000 */  nop
    /* 3D1EA80 8006E4E4 00024224 */  addiu      $v0, $v0, 0x200
    /* 3D1EA84 8006E4E8 0780013C */  lui        $at, %hi(D_8006A150)
    /* 3D1EA88 8006E4EC 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 3D1EA8C 8006E4F0 00184228 */  slti       $v0, $v0, 0x1800
    /* 3D1EA90 8006E4F4 14004014 */  bnez       $v0, .Llevel_55_8006E548
    /* 3D1EA94 8006E4F8 00180224 */   addiu     $v0, $zero, 0x1800
    /* 3D1EA98 8006E4FC 0780013C */  lui        $at, %hi(D_8006A150)
    /* 3D1EA9C 8006E500 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 3D1EAA0 8006E504 02000224 */  addiu      $v0, $zero, 0x2
    /* 3D1EAA4 8006E508 0780013C */  lui        $at, %hi(D_8006A044)
    /* 3D1EAA8 8006E50C 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 3D1EAAC 8006E510 52B90108 */  j          .Llevel_55_8006E548
    /* 3D1EAB0 8006E514 00000000 */   nop
  .Llevel_55_8006E518:
    /* 3D1EAB4 8006E518 0780023C */  lui        $v0, %hi(D_8006A150)
    /* 3D1EAB8 8006E51C 50A1428C */  lw         $v0, %lo(D_8006A150)($v0)
    /* 3D1EABC 8006E520 00000000 */  nop
    /* 3D1EAC0 8006E524 00FF4224 */  addiu      $v0, $v0, -0x100
    /* 3D1EAC4 8006E528 0780013C */  lui        $at, %hi(D_8006A150)
    /* 3D1EAC8 8006E52C 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 3D1EACC 8006E530 0500401C */  bgtz       $v0, .Llevel_55_8006E548
    /* 3D1EAD0 8006E534 00000000 */   nop
    /* 3D1EAD4 8006E538 0780013C */  lui        $at, %hi(D_8006A150)
    /* 3D1EAD8 8006E53C 50A120AC */  sw         $zero, %lo(D_8006A150)($at)
    /* 3D1EADC 8006E540 0780013C */  lui        $at, %hi(D_8006A044)
    /* 3D1EAE0 8006E544 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
  .Llevel_55_8006E548:
    /* 3D1EAE4 8006E548 0780023C */  lui        $v0, %hi(D_8006A080)
    /* 3D1EAE8 8006E54C 80A04224 */  addiu      $v0, $v0, %lo(D_8006A080)
    /* 3D1EAEC 8006E550 0000438C */  lw         $v1, 0x0($v0)
    /* 3D1EAF0 8006E554 0780043C */  lui        $a0, %hi(D_8006A150)
    /* 3D1EAF4 8006E558 50A1848C */  lw         $a0, %lo(D_8006A150)($a0)
    /* 3D1EAF8 8006E55C 00000000 */  nop
    /* 3D1EAFC 8006E560 21186400 */  addu       $v1, $v1, $a0
    /* 3D1EB00 8006E564 000043AC */  sw         $v1, 0x0($v0)
  .Llevel_55_8006E568:
    /* 3D1EB04 8006E568 0EB0000C */  jal        func_8002C038
    /* 3D1EB08 8006E56C 00000000 */   nop
    /* 3D1EB0C 8006E570 B6BA0108 */  j          .Llevel_55_8006EAD8
    /* 3D1EB10 8006E574 00000000 */   nop
  .Llevel_55_8006E578:
    /* 3D1EB14 8006E578 0780103C */  lui        $s0, %hi(D_8006A044)
    /* 3D1EB18 8006E57C 44A01026 */  addiu      $s0, $s0, %lo(D_8006A044)
    /* 3D1EB1C 8006E580 0000038E */  lw         $v1, 0x0($s0)
    /* 3D1EB20 8006E584 01000224 */  addiu      $v0, $zero, 0x1
    /* 3D1EB24 8006E588 07006214 */  bne        $v1, $v0, .Llevel_55_8006E5A8
    /* 3D1EB28 8006E58C 07000224 */   addiu     $v0, $zero, 0x7
    /* 3D1EB2C 8006E590 686F000C */  jal        func_8001BDA0
    /* 3D1EB30 8006E594 34000426 */   addiu     $a0, $s0, 0x34
    /* 3D1EB34 8006E598 686F000C */  jal        func_8001BDA0
    /* 3D1EB38 8006E59C 40000426 */   addiu     $a0, $s0, 0x40
    /* 3D1EB3C 8006E5A0 B6BA0108 */  j          .Llevel_55_8006EAD8
    /* 3D1EB40 8006E5A4 00000000 */   nop
  .Llevel_55_8006E5A8:
    /* 3D1EB44 8006E5A8 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 3D1EB48 8006E5AC D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 3D1EB4C 8006E5B0 00000000 */  nop
    /* 3D1EB50 8006E5B4 05006214 */  bne        $v1, $v0, .Llevel_55_8006E5CC
    /* 3D1EB54 8006E5B8 00000000 */   nop
    /* 3D1EB58 8006E5BC 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 3D1EB5C 8006E5C0 A8A020AC */  sw         $zero, %lo(D_8006A0A8)($at)
    /* 3D1EB60 8006E5C4 8CB90108 */  j          .Llevel_55_8006E630
    /* 3D1EB64 8006E5C8 00000000 */   nop
  .Llevel_55_8006E5CC:
    /* 3D1EB68 8006E5CC DBAC000C */  jal        func_8002B36C
    /* 3D1EB6C 8006E5D0 80090424 */   addiu     $a0, $zero, 0x980
    /* 3D1EB70 8006E5D4 5A000424 */  addiu      $a0, $zero, 0x5A
    /* 3D1EB74 8006E5D8 C9AE000C */  jal        func_8002BB24
    /* 3D1EB78 8006E5DC 10000524 */   addiu     $a1, $zero, 0x10
    /* 3D1EB7C 8006E5E0 02004104 */  bgez       $v0, .Llevel_55_8006E5EC
    /* 3D1EB80 8006E5E4 00000000 */   nop
    /* 3D1EB84 8006E5E8 23100200 */  negu       $v0, $v0
  .Llevel_55_8006E5EC:
    /* 3D1EB88 8006E5EC 01024228 */  slti       $v0, $v0, 0x201
    /* 3D1EB8C 8006E5F0 03004014 */  bnez       $v0, .Llevel_55_8006E600
    /* 3D1EB90 8006E5F4 00000000 */   nop
    /* 3D1EB94 8006E5F8 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 3D1EB98 8006E5FC A4A020AC */  sw         $zero, %lo(D_8006A0A4)($at)
  .Llevel_55_8006E600:
    /* 3D1EB9C 8006E600 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 3D1EBA0 8006E604 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 3D1EBA4 8006E608 00000000 */  nop
    /* 3D1EBA8 8006E60C 810C4228 */  slti       $v0, $v0, 0xC81
    /* 3D1EBAC 8006E610 04004014 */  bnez       $v0, .Llevel_55_8006E624
    /* 3D1EBB0 8006E614 C0000424 */   addiu     $a0, $zero, 0xC0
    /* 3D1EBB4 8006E618 21200000 */  addu       $a0, $zero, $zero
    /* 3D1EBB8 8006E61C 8AB90108 */  j          .Llevel_55_8006E628
    /* 3D1EBBC 8006E620 C0000524 */   addiu     $a1, $zero, 0xC0
  .Llevel_55_8006E624:
    /* 3D1EBC0 8006E624 40000524 */  addiu      $a1, $zero, 0x40
  .Llevel_55_8006E628:
    /* 3D1EBC4 8006E628 5CAF000C */  jal        func_8002BD70
    /* 3D1EBC8 8006E62C 00000000 */   nop
  .Llevel_55_8006E630:
    /* 3D1EBCC 8006E630 0780103C */  lui        $s0, %hi(D_8006A0A8)
    /* 3D1EBD0 8006E634 A8A01026 */  addiu      $s0, $s0, %lo(D_8006A0A8)
    /* 3D1EBD4 8006E638 0000028E */  lw         $v0, 0x0($s0)
    /* 3D1EBD8 8006E63C 00000000 */  nop
    /* 3D1EBDC 8006E640 09004010 */  beqz       $v0, .Llevel_55_8006E668
    /* 3D1EBE0 8006E644 00000000 */   nop
    /* 3D1EBE4 8006E648 6FAF000C */  jal        func_8002BDBC
    /* 3D1EBE8 8006E64C 00000000 */   nop
    /* 3D1EBEC 8006E650 0EB0000C */  jal        func_8002C038
    /* 3D1EBF0 8006E654 00000000 */   nop
    /* 3D1EBF4 8006E658 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 3D1EBF8 8006E65C 8CA020AC */  sw         $zero, %lo(D_8006A08C)($at)
    /* 3D1EBFC 8006E660 9EB90108 */  j          .Llevel_55_8006E678
    /* 3D1EC00 8006E664 00000000 */   nop
  .Llevel_55_8006E668:
    /* 3D1EC04 8006E668 686F000C */  jal        func_8001BDA0
    /* 3D1EC08 8006E66C D0FF0426 */   addiu     $a0, $s0, -0x30
    /* 3D1EC0C 8006E670 686F000C */  jal        func_8001BDA0
    /* 3D1EC10 8006E674 DCFF0426 */   addiu     $a0, $s0, -0x24
  .Llevel_55_8006E678:
    /* 3D1EC14 8006E678 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 3D1EC18 8006E67C FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 3D1EC1C 8006E680 00000000 */  nop
    /* 3D1EC20 8006E684 79004010 */  beqz       $v0, .Llevel_55_8006E86C
    /* 3D1EC24 8006E688 00000000 */   nop
    /* 3D1EC28 8006E68C 0780143C */  lui        $s4, %hi(D_8006A018)
    /* 3D1EC2C 8006E690 18A09426 */  addiu      $s4, $s4, %lo(D_8006A018)
    /* 3D1EC30 8006E694 0000828E */  lw         $v0, 0x0($s4)
    /* 3D1EC34 8006E698 00000000 */  nop
    /* 3D1EC38 8006E69C 73004104 */  bgez       $v0, .Llevel_55_8006E86C
    /* 3D1EC3C 8006E6A0 00000000 */   nop
    /* 3D1EC40 8006E6A4 0780023C */  lui        $v0, %hi(D_8006A0A8)
    /* 3D1EC44 8006E6A8 A8A0428C */  lw         $v0, %lo(D_8006A0A8)($v0)
    /* 3D1EC48 8006E6AC 00000000 */  nop
    /* 3D1EC4C 8006E6B0 01044228 */  slti       $v0, $v0, 0x401
    /* 3D1EC50 8006E6B4 42004014 */  bnez       $v0, .Llevel_55_8006E7C0
    /* 3D1EC54 8006E6B8 0200422A */   slti      $v0, $s2, 0x2
    /* 3D1EC58 8006E6BC 40004010 */  beqz       $v0, .Llevel_55_8006E7C0
    /* 3D1EC5C 8006E6C0 00000000 */   nop
    /* 3D1EC60 8006E6C4 0680023C */  lui        $v0, %hi(D_80067008)
    /* 3D1EC64 8006E6C8 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 3D1EC68 8006E6CC 00000000 */  nop
    /* 3D1EC6C 8006E6D0 01004230 */  andi       $v0, $v0, 0x1
    /* 3D1EC70 8006E6D4 3A004010 */  beqz       $v0, .Llevel_55_8006E7C0
    /* 3D1EC74 8006E6D8 6800B327 */   addiu     $s3, $sp, 0x68
    /* 3D1EC78 8006E6DC 21206002 */  addu       $a0, $s3, $zero
    /* 3D1EC7C 8006E6E0 6C6F000C */  jal        func_8001BDB0
    /* 3D1EC80 8006E6E4 D8FF8526 */   addiu     $a1, $s4, -0x28
    /* 3D1EC84 8006E6E8 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 3D1EC88 8006E6EC A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 3D1EC8C 8006E6F0 40000224 */  addiu      $v0, $zero, 0x40
    /* 3D1EC90 8006E6F4 7C00A2AF */  sw         $v0, 0x7C($sp)
    /* 3D1EC94 8006E6F8 8000A0AF */  sw         $zero, 0x80($sp)
    /* 3D1EC98 8006E6FC 43190300 */  sra        $v1, $v1, 5
    /* 3D1EC9C 8006E700 03004012 */  beqz       $s2, .Llevel_55_8006E710
    /* 3D1ECA0 8006E704 7800A3AF */   sw        $v1, 0x78($sp)
    /* 3D1ECA4 8006E708 C0FF0224 */  addiu      $v0, $zero, -0x40
    /* 3D1ECA8 8006E70C 7C00A2AF */  sw         $v0, 0x7C($sp)
  .Llevel_55_8006E710:
    /* 3D1ECAC 8006E710 08009226 */  addiu      $s2, $s4, 0x8
    /* 3D1ECB0 8006E714 21204002 */  addu       $a0, $s2, $zero
    /* 3D1ECB4 8006E718 7800B127 */  addiu      $s1, $sp, 0x78
    /* 3D1ECB8 8006E71C 21282002 */  addu       $a1, $s1, $zero
    /* 3D1ECBC 8006E720 8800B027 */  addiu      $s0, $sp, 0x88
    /* 3D1ECC0 8006E724 696E000C */  jal        func_8001B9A4
    /* 3D1ECC4 8006E728 21300002 */   addu      $a2, $s0, $zero
    /* 3D1ECC8 8006E72C 21206002 */  addu       $a0, $s3, $zero
    /* 3D1ECCC 8006E730 21286002 */  addu       $a1, $s3, $zero
    /* 3D1ECD0 8006E734 736F000C */  jal        func_8001BDCC
    /* 3D1ECD4 8006E738 21300002 */   addu      $a2, $s0, $zero
    /* 3D1ECD8 8006E73C 21204002 */  addu       $a0, $s2, $zero
    /* 3D1ECDC 8006E740 21282002 */  addu       $a1, $s1, $zero
    /* 3D1ECE0 8006E744 0000828E */  lw         $v0, 0x0($s4)
    /* 3D1ECE4 8006E748 21302002 */  addu       $a2, $s1, $zero
    /* 3D1ECE8 8006E74C 7800A0AF */  sw         $zero, 0x78($sp)
    /* 3D1ECEC 8006E750 23100200 */  negu       $v0, $v0
    /* 3D1ECF0 8006E754 696E000C */  jal        func_8001B9A4
    /* 3D1ECF4 8006E758 7000A2AF */   sw        $v0, 0x70($sp)
    /* 3D1ECF8 8006E75C 21202002 */  addu       $a0, $s1, $zero
    /* 3D1ECFC 8006E760 526F000C */  jal        func_8001BD48
    /* 3D1ED00 8006E764 03000524 */   addiu     $a1, $zero, 0x3
    /* 3D1ED04 8006E768 01000424 */  addiu      $a0, $zero, 0x1
    /* 3D1ED08 8006E76C 2A000524 */  addiu      $a1, $zero, 0x2A
    /* 3D1ED0C 8006E770 21306002 */  addu       $a2, $s3, $zero
    /* 3D1ED10 8006E774 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 3D1ED14 8006E778 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 3D1ED18 8006E77C 00000000 */  nop
    /* 3D1ED1C 8006E780 09F84000 */  jalr       $v0
    /* 3D1ED20 8006E784 21382002 */   addu      $a3, $s1, $zero
    /* 3D1ED24 8006E788 4B67010C */  jal        func_80059D2C
    /* 3D1ED28 8006E78C 00000000 */   nop
    /* 3D1ED2C 8006E790 1F004230 */  andi       $v0, $v0, 0x1F
    /* 3D1ED30 8006E794 35004014 */  bnez       $v0, .Llevel_55_8006E86C
    /* 3D1ED34 8006E798 01000424 */   addiu     $a0, $zero, 0x1
    /* 3D1ED38 8006E79C 29000524 */  addiu      $a1, $zero, 0x29
    /* 3D1ED3C 8006E7A0 21306002 */  addu       $a2, $s3, $zero
    /* 3D1ED40 8006E7A4 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 3D1ED44 8006E7A8 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 3D1ED48 8006E7AC 00000000 */  nop
    /* 3D1ED4C 8006E7B0 09F84000 */  jalr       $v0
    /* 3D1ED50 8006E7B4 21380000 */   addu      $a3, $zero, $zero
    /* 3D1ED54 8006E7B8 1BBA0108 */  j          .Llevel_55_8006E86C
    /* 3D1ED58 8006E7BC 00000000 */   nop
  .Llevel_55_8006E7C0:
    /* 3D1ED5C 8006E7C0 0780113C */  lui        $s1, %hi(D_8006A0A8)
    /* 3D1ED60 8006E7C4 A8A03126 */  addiu      $s1, $s1, %lo(D_8006A0A8)
    /* 3D1ED64 8006E7C8 0000228E */  lw         $v0, 0x0($s1)
    /* 3D1ED68 8006E7CC 00000000 */  nop
    /* 3D1ED6C 8006E7D0 01024228 */  slti       $v0, $v0, 0x201
    /* 3D1ED70 8006E7D4 25004010 */  beqz       $v0, .Llevel_55_8006E86C
    /* 3D1ED74 8006E7D8 00000000 */   nop
    /* 3D1ED78 8006E7DC 23004016 */  bnez       $s2, .Llevel_55_8006E86C
    /* 3D1ED7C 8006E7E0 00000000 */   nop
    /* 3D1ED80 8006E7E4 0680023C */  lui        $v0, %hi(D_80067008)
    /* 3D1ED84 8006E7E8 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 3D1ED88 8006E7EC 00000000 */  nop
    /* 3D1ED8C 8006E7F0 07004230 */  andi       $v0, $v0, 0x7
    /* 3D1ED90 8006E7F4 1D004014 */  bnez       $v0, .Llevel_55_8006E86C
    /* 3D1ED94 8006E7F8 00000000 */   nop
    /* 3D1ED98 8006E7FC 4B67010C */  jal        func_80059D2C
    /* 3D1ED9C 8006E800 00000000 */   nop
    /* 3D1EDA0 8006E804 03004230 */  andi       $v0, $v0, 0x3
    /* 3D1EDA4 8006E808 18004014 */  bnez       $v0, .Llevel_55_8006E86C
    /* 3D1EDA8 8006E80C 78FF2426 */   addiu     $a0, $s1, -0x88
    /* 3D1EDAC 8006E810 9800B027 */  addiu      $s0, $sp, 0x98
    /* 3D1EDB0 8006E814 21280002 */  addu       $a1, $s0, $zero
    /* 3D1EDB4 8006E818 21300002 */  addu       $a2, $s0, $zero
    /* 3D1EDB8 8006E81C 80000224 */  addiu      $v0, $zero, 0x80
    /* 3D1EDBC 8006E820 9800A2AF */  sw         $v0, 0x98($sp)
    /* 3D1EDC0 8006E824 9C00A0AF */  sw         $zero, 0x9C($sp)
    /* 3D1EDC4 8006E828 696E000C */  jal        func_8001B9A4
    /* 3D1EDC8 8006E82C A000A0AF */   sw        $zero, 0xA0($sp)
    /* 3D1EDCC 8006E830 21200002 */  addu       $a0, $s0, $zero
    /* 3D1EDD0 8006E834 21280002 */  addu       $a1, $s0, $zero
    /* 3D1EDD4 8006E838 736F000C */  jal        func_8001BDCC
    /* 3D1EDD8 8006E83C 48FF2626 */   addiu     $a2, $s1, -0xB8
    /* 3D1EDDC 8006E840 01000424 */  addiu      $a0, $zero, 0x1
    /* 3D1EDE0 8006E844 2B000524 */  addiu      $a1, $zero, 0x2B
    /* 3D1EDE4 8006E848 21300002 */  addu       $a2, $s0, $zero
    /* 3D1EDE8 8006E84C 01000724 */  addiu      $a3, $zero, 0x1
    /* 3D1EDEC 8006E850 0780023C */  lui        $v0, %hi(D_8006A018)
    /* 3D1EDF0 8006E854 18A0428C */  lw         $v0, %lo(D_8006A018)($v0)
    /* 3D1EDF4 8006E858 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 3D1EDF8 8006E85C FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 3D1EDFC 8006E860 23100200 */  negu       $v0, $v0
    /* 3D1EE00 8006E864 09F86000 */  jalr       $v1
    /* 3D1EE04 8006E868 A000A2AF */   sw        $v0, 0xA0($sp)
  .Llevel_55_8006E86C:
    /* 3D1EE08 8006E86C 0780063C */  lui        $a2, %hi(D_8006A13C)
    /* 3D1EE0C 8006E870 3CA1C624 */  addiu      $a2, $a2, %lo(D_8006A13C)
    /* 3D1EE10 8006E874 0780043C */  lui        $a0, %hi(D_8006A140)
    /* 3D1EE14 8006E878 40A1848C */  lw         $a0, %lo(D_8006A140)($a0)
    /* 3D1EE18 8006E87C 0000C58C */  lw         $a1, 0x0($a2)
    /* 3D1EE1C 8006E880 40180400 */  sll        $v1, $a0, 1
    /* 3D1EE20 8006E884 80100500 */  sll        $v0, $a1, 2
    /* 3D1EE24 8006E888 21104500 */  addu       $v0, $v0, $a1
    /* 3D1EE28 8006E88C 80100200 */  sll        $v0, $v0, 2
    /* 3D1EE2C 8006E890 21186200 */  addu       $v1, $v1, $v0
    /* 3D1EE30 8006E894 031A0300 */  sra        $v1, $v1, 8
    /* 3D1EE34 8006E898 2328A300 */  subu       $a1, $a1, $v1
    /* 3D1EE38 8006E89C 21208500 */  addu       $a0, $a0, $a1
    /* 3D1EE3C 8006E8A0 0000C5AC */  sw         $a1, 0x0($a2)
    /* 3D1EE40 8006E8A4 0780013C */  lui        $at, %hi(D_8006A140)
    /* 3D1EE44 8006E8A8 40A124AC */  sw         $a0, %lo(D_8006A140)($at)
    /* 3D1EE48 8006E8AC 01598428 */  slti       $a0, $a0, 0x5901
    /* 3D1EE4C 8006E8B0 03008014 */  bnez       $a0, .Llevel_55_8006E8C0
    /* 3D1EE50 8006E8B4 00590224 */   addiu     $v0, $zero, 0x5900
    /* 3D1EE54 8006E8B8 0780013C */  lui        $at, %hi(D_8006A140)
    /* 3D1EE58 8006E8BC 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
  .Llevel_55_8006E8C0:
    /* 3D1EE5C 8006E8C0 0780023C */  lui        $v0, %hi(D_8006A140)
    /* 3D1EE60 8006E8C4 40A1428C */  lw         $v0, %lo(D_8006A140)($v0)
    /* 3D1EE64 8006E8C8 00000000 */  nop
    /* 3D1EE68 8006E8CC 00A74228 */  slti       $v0, $v0, -0x5900
    /* 3D1EE6C 8006E8D0 81004010 */  beqz       $v0, .Llevel_55_8006EAD8
    /* 3D1EE70 8006E8D4 00A70224 */   addiu     $v0, $zero, -0x5900
    /* 3D1EE74 8006E8D8 0780013C */  lui        $at, %hi(D_8006A140)
    /* 3D1EE78 8006E8DC 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
    /* 3D1EE7C 8006E8E0 B6BA0108 */  j          .Llevel_55_8006EAD8
    /* 3D1EE80 8006E8E4 00000000 */   nop
  .Llevel_55_8006E8E8:
    /* 3D1EE84 8006E8E8 8800A427 */  addiu      $a0, $sp, 0x88
    /* 3D1EE88 8006E8EC 39AD000C */  jal        func_8002B4E4
    /* 3D1EE8C 8006E8F0 01000524 */   addiu     $a1, $zero, 0x1
    /* 3D1EE90 8006E8F4 8800A38F */  lw         $v1, 0x88($sp)
    /* 3D1EE94 8006E8F8 00000000 */  nop
    /* 3D1EE98 8006E8FC C0100300 */  sll        $v0, $v1, 3
    /* 3D1EE9C 8006E900 21104300 */  addu       $v0, $v0, $v1
    /* 3D1EEA0 8006E904 80100200 */  sll        $v0, $v0, 2
    /* 3D1EEA4 8006E908 23104300 */  subu       $v0, $v0, $v1
    /* 3D1EEA8 8006E90C C3210200 */  sra        $a0, $v0, 7
    /* 3D1EEAC 8006E910 05008014 */  bnez       $a0, .Llevel_55_8006E928
    /* 3D1EEB0 8006E914 00000000 */   nop
    /* 3D1EEB4 8006E918 0780013C */  lui        $at, %hi(D_8006A0A0)
    /* 3D1EEB8 8006E91C A0A020AC */  sw         $zero, %lo(D_8006A0A0)($at)
    /* 3D1EEBC 8006E920 5BBA0108 */  j          .Llevel_55_8006E96C
    /* 3D1EEC0 8006E924 00000000 */   nop
  .Llevel_55_8006E928:
    /* 3D1EEC4 8006E928 09008104 */  bgez       $a0, .Llevel_55_8006E950
    /* 3D1EEC8 8006E92C 00000000 */   nop
    /* 3D1EECC 8006E930 0780033C */  lui        $v1, %hi(D_8006A0A0)
    /* 3D1EED0 8006E934 A0A06324 */  addiu      $v1, $v1, %lo(D_8006A0A0)
    /* 3D1EED4 8006E938 0000628C */  lw         $v0, 0x0($v1)
    /* 3D1EED8 8006E93C 00000000 */  nop
    /* 3D1EEDC 8006E940 0A004018 */  blez       $v0, .Llevel_55_8006E96C
    /* 3D1EEE0 8006E944 00000000 */   nop
    /* 3D1EEE4 8006E948 5BBA0108 */  j          .Llevel_55_8006E96C
    /* 3D1EEE8 8006E94C 000060AC */   sw        $zero, 0x0($v1)
  .Llevel_55_8006E950:
    /* 3D1EEEC 8006E950 0780033C */  lui        $v1, %hi(D_8006A0A0)
    /* 3D1EEF0 8006E954 A0A06324 */  addiu      $v1, $v1, %lo(D_8006A0A0)
    /* 3D1EEF4 8006E958 0000628C */  lw         $v0, 0x0($v1)
    /* 3D1EEF8 8006E95C 00000000 */  nop
    /* 3D1EEFC 8006E960 02004104 */  bgez       $v0, .Llevel_55_8006E96C
    /* 3D1EF00 8006E964 00000000 */   nop
    /* 3D1EF04 8006E968 000060AC */  sw         $zero, 0x0($v1)
  .Llevel_55_8006E96C:
    /* 3D1EF08 8006E96C 0780053C */  lui        $a1, %hi(D_8006A0A0)
    /* 3D1EF0C 8006E970 A0A0A524 */  addiu      $a1, $a1, %lo(D_8006A0A0)
    /* 3D1EF10 8006E974 0000A38C */  lw         $v1, 0x0($a1)
    /* 3D1EF14 8006E978 00000000 */  nop
    /* 3D1EF18 8006E97C 2A106400 */  slt        $v0, $v1, $a0
    /* 3D1EF1C 8006E980 04004010 */  beqz       $v0, .Llevel_55_8006E994
    /* 3D1EF20 8006E984 08006224 */   addiu     $v0, $v1, 0x8
    /* 3D1EF24 8006E988 0000A2AC */  sw         $v0, 0x0($a1)
    /* 3D1EF28 8006E98C 68BA0108 */  j          .Llevel_55_8006E9A0
    /* 3D1EF2C 8006E990 2A108200 */   slt       $v0, $a0, $v0
  .Llevel_55_8006E994:
    /* 3D1EF30 8006E994 F8FF6224 */  addiu      $v0, $v1, -0x8
    /* 3D1EF34 8006E998 0000A2AC */  sw         $v0, 0x0($a1)
    /* 3D1EF38 8006E99C 2A104400 */  slt        $v0, $v0, $a0
  .Llevel_55_8006E9A0:
    /* 3D1EF3C 8006E9A0 02004010 */  beqz       $v0, .Llevel_55_8006E9AC
    /* 3D1EF40 8006E9A4 00000000 */   nop
    /* 3D1EF44 8006E9A8 0000A4AC */  sw         $a0, 0x0($a1)
  .Llevel_55_8006E9AC:
    /* 3D1EF48 8006E9AC 0780043C */  lui        $a0, %hi(D_8006A0A0)
    /* 3D1EF4C 8006E9B0 A0A0848C */  lw         $a0, %lo(D_8006A0A0)($a0)
    /* 3D1EF50 8006E9B4 68AE000C */  jal        func_8002B9A0
    /* 3D1EF54 8006E9B8 00000000 */   nop
    /* 3D1EF58 8006E9BC 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 3D1EF5C 8006E9C0 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 3D1EF60 8006E9C4 00000000 */  nop
    /* 3D1EF64 8006E9C8 01086228 */  slti       $v0, $v1, 0x801
    /* 3D1EF68 8006E9CC 05004014 */  bnez       $v0, .Llevel_55_8006E9E4
    /* 3D1EF6C 8006E9D0 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 3D1EF70 8006E9D4 0780013C */  lui        $at, %hi(D_8006A058)
    /* 3D1EF74 8006E9D8 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
    /* 3D1EF78 8006E9DC 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 3D1EF7C 8006E9E0 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
  .Llevel_55_8006E9E4:
    /* 3D1EF80 8006E9E4 00000000 */  nop
    /* 3D1EF84 8006E9E8 07006104 */  bgez       $v1, .Llevel_55_8006EA08
    /* 3D1EF88 8006E9EC 00000000 */   nop
    /* 3D1EF8C 8006E9F0 0680043C */  lui        $a0, %hi(D_8006019C)
    /* 3D1EF90 8006E9F4 9C01848C */  lw         $a0, %lo(D_8006019C)($a0)
    /* 3D1EF94 8006E9F8 0680023C */  lui        $v0, %hi(D_80060198)
    /* 3D1EF98 8006E9FC 9801428C */  lw         $v0, %lo(D_80060198)($v0)
    /* 3D1EF9C 8006EA00 8ABA0108 */  j          .Llevel_55_8006EA28
    /* 3D1EFA0 8006EA04 23108200 */   subu      $v0, $a0, $v0
  .Llevel_55_8006EA08:
    /* 3D1EFA4 8006EA08 15006018 */  blez       $v1, .Llevel_55_8006EA60
    /* 3D1EFA8 8006EA0C 40020424 */   addiu     $a0, $zero, 0x240
    /* 3D1EFAC 8006EA10 0680023C */  lui        $v0, %hi(D_800601A0)
    /* 3D1EFB0 8006EA14 A001428C */  lw         $v0, %lo(D_800601A0)($v0)
    /* 3D1EFB4 8006EA18 0680043C */  lui        $a0, %hi(D_8006019C)
    /* 3D1EFB8 8006EA1C 9C01848C */  lw         $a0, %lo(D_8006019C)($a0)
    /* 3D1EFBC 8006EA20 00000000 */  nop
    /* 3D1EFC0 8006EA24 23104400 */  subu       $v0, $v0, $a0
  .Llevel_55_8006EA28:
    /* 3D1EFC4 8006EA28 18006200 */  mult       $v1, $v0
    /* 3D1EFC8 8006EA2C 12100000 */  mflo       $v0
    /* 3D1EFCC 8006EA30 8B2E033C */  lui        $v1, (0x2E8BA2E9 >> 16)
    /* 3D1EFD0 8006EA34 E9A26334 */  ori        $v1, $v1, (0x2E8BA2E9 & 0xFFFF)
    /* 3D1EFD4 8006EA38 18004300 */  mult       $v0, $v1
    /* 3D1EFD8 8006EA3C C3170200 */  sra        $v0, $v0, 31
    /* 3D1EFDC 8006EA40 10480000 */  mfhi       $t1
    /* 3D1EFE0 8006EA44 83190900 */  sra        $v1, $t1, 6
    /* 3D1EFE4 8006EA48 23186200 */  subu       $v1, $v1, $v0
    /* 3D1EFE8 8006EA4C 21208300 */  addu       $a0, $a0, $v1
    /* 3D1EFEC 8006EA50 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 3D1EFF0 8006EA54 A4A024AC */  sw         $a0, %lo(D_8006A0A4)($at)
    /* 3D1EFF4 8006EA58 9CBA0108 */  j          .Llevel_55_8006EA70
    /* 3D1EFF8 8006EA5C 40020424 */   addiu     $a0, $zero, 0x240
  .Llevel_55_8006EA60:
    /* 3D1EFFC 8006EA60 0680023C */  lui        $v0, %hi(D_8006019C)
    /* 3D1F000 8006EA64 9C01428C */  lw         $v0, %lo(D_8006019C)($v0)
    /* 3D1F004 8006EA68 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 3D1F008 8006EA6C A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
  .Llevel_55_8006EA70:
    /* 3D1F00C 8006EA70 5CAF000C */  jal        func_8002BD70
    /* 3D1F010 8006EA74 80010524 */   addiu     $a1, $zero, 0x180
    /* 3D1F014 8006EA78 6FAF000C */  jal        func_8002BDBC
    /* 3D1F018 8006EA7C 00000000 */   nop
    /* 3D1F01C 8006EA80 0780063C */  lui        $a2, %hi(D_8006A0F4)
    /* 3D1F020 8006EA84 F4A0C624 */  addiu      $a2, $a2, %lo(D_8006A0F4)
    /* 3D1F024 8006EA88 0000C290 */  lbu        $v0, 0x0($a2)
    /* 3D1F028 8006EA8C 00000000 */  nop
    /* 3D1F02C 8006EA90 06004014 */  bnez       $v0, .Llevel_55_8006EAAC
    /* 3D1F030 8006EA94 00000000 */   nop
    /* 3D1F034 8006EA98 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 3D1F038 8006EA9C B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 3D1F03C 8006EAA0 00000000 */  nop
    /* 3D1F040 8006EAA4 09004010 */  beqz       $v0, .Llevel_55_8006EACC
    /* 3D1F044 8006EAA8 90FFC424 */   addiu     $a0, $a2, -0x70
  .Llevel_55_8006EAAC:
    /* 3D1F048 8006EAAC 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 3D1F04C 8006EAB0 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 3D1F050 8006EAB4 00000000 */  nop
    /* 3D1F054 8006EAB8 40FF4224 */  addiu      $v0, $v0, -0xC0
    /* 3D1F058 8006EABC 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 3D1F05C 8006EAC0 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 3D1F060 8006EAC4 B6BA0108 */  j          .Llevel_55_8006EAD8
    /* 3D1F064 8006EAC8 00000000 */   nop
  .Llevel_55_8006EACC:
    /* 3D1F068 8006EACC 84FFC524 */  addiu      $a1, $a2, -0x7C
    /* 3D1F06C 8006EAD0 736F000C */  jal        func_8001BDCC
    /* 3D1F070 8006EAD4 ECFFC624 */   addiu     $a2, $a2, -0x14
  .Llevel_55_8006EAD8:
    /* 3D1F074 8006EAD8 BC00BF8F */  lw         $ra, 0xBC($sp)
    /* 3D1F078 8006EADC B800B48F */  lw         $s4, 0xB8($sp)
    /* 3D1F07C 8006EAE0 B400B38F */  lw         $s3, 0xB4($sp)
    /* 3D1F080 8006EAE4 B000B28F */  lw         $s2, 0xB0($sp)
    /* 3D1F084 8006EAE8 AC00B18F */  lw         $s1, 0xAC($sp)
    /* 3D1F088 8006EAEC A800B08F */  lw         $s0, 0xA8($sp)
    /* 3D1F08C 8006EAF0 C000BD27 */  addiu      $sp, $sp, 0xC0
    /* 3D1F090 8006EAF4 0800E003 */  jr         $ra
    /* 3D1F094 8006EAF8 00000000 */   nop
endlabel func_level_55_8006D940
