.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_55_8006D3C8

dlabel jtbl_level_55_8006D3C8
    /* 3D1D964 8006D3C8 74EF0680 */ .word .Llevel_55_8006EF74
    /* 3D1D968 8006D3CC 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D96C 8006D3D0 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D970 8006D3D4 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D974 8006D3D8 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D978 8006D3DC 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D97C 8006D3E0 5CEF0680 */ .word .Llevel_55_8006EF5C
    /* 3D1D980 8006D3E4 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D984 8006D3E8 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D988 8006D3EC 54EF0680 */ .word .Llevel_55_8006EF54
    /* 3D1D98C 8006D3F0 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D990 8006D3F4 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D994 8006D3F8 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D998 8006D3FC 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D99C 8006D400 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9A0 8006D404 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9A4 8006D408 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9A8 8006D40C 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9AC 8006D410 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9B0 8006D414 74EF0680 */ .word .Llevel_55_8006EF74
    /* 3D1D9B4 8006D418 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9B8 8006D41C 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9BC 8006D420 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9C0 8006D424 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9C4 8006D428 74EF0680 */ .word .Llevel_55_8006EF74
    /* 3D1D9C8 8006D42C 74EF0680 */ .word .Llevel_55_8006EF74
    /* 3D1D9CC 8006D430 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9D0 8006D434 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9D4 8006D438 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9D8 8006D43C 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9DC 8006D440 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9E0 8006D444 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9E4 8006D448 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9E8 8006D44C 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9EC 8006D450 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9F0 8006D454 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9F4 8006D458 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9F8 8006D45C 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1D9FC 8006D460 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1DA00 8006D464 74EF0680 */ .word .Llevel_55_8006EF74
    /* 3D1DA04 8006D468 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1DA08 8006D46C 84EF0680 */ .word .Llevel_55_8006EF84
    /* 3D1DA0C 8006D470 74EF0680 */ .word .Llevel_55_8006EF74
    /* 3D1DA10 8006D474 00000000 */ .word 0x00000000
enddlabel jtbl_level_55_8006D3C8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_55_8006EF04, 0x90

glabel func_level_55_8006EF04
    /* 3D1F4A0 8006EF04 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 3D1F4A4 8006EF08 00210400 */  sll        $a0, $a0, 4
    /* 3D1F4A8 8006EF0C 0780023C */  lui        $v0, %hi(D_800683B0)
    /* 3D1F4AC 8006EF10 B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* 3D1F4B0 8006EF14 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 3D1F4B4 8006EF18 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 3D1F4B8 8006EF1C 21208200 */  addu       $a0, $a0, $v0
    /* 3D1F4BC 8006EF20 1000BFAF */  sw         $ra, 0x10($sp)
    /* 3D1F4C0 8006EF24 0680013C */  lui        $at, %hi(D_80066F38)
    /* 3D1F4C4 8006EF28 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* 3D1F4C8 8006EF2C EDFF6324 */  addiu      $v1, $v1, -0x13
    /* 3D1F4CC 8006EF30 2B00622C */  sltiu      $v0, $v1, 0x2B
    /* 3D1F4D0 8006EF34 13004010 */  beqz       $v0, .Llevel_55_8006EF84
    /* 3D1F4D4 8006EF38 80100300 */   sll       $v0, $v1, 2
    /* 3D1F4D8 8006EF3C 0780013C */  lui        $at, %hi(jtbl_level_55_8006D3C8)
    /* 3D1F4DC 8006EF40 21082200 */  addu       $at, $at, $v0
    /* 3D1F4E0 8006EF44 C8D3228C */  lw         $v0, %lo(jtbl_level_55_8006D3C8)($at)
    /* 3D1F4E4 8006EF48 00000000 */  nop
    /* 3D1F4E8 8006EF4C 08004000 */  jr         $v0
    /* 3D1F4EC 8006EF50 00000000 */   nop
  .Llevel_55_8006EF54:
    /* 3D1F4F0 8006EF54 DFBB0108 */  j          .Llevel_55_8006EF7C
    /* 3D1F4F4 8006EF58 21200000 */   addu      $a0, $zero, $zero
  .Llevel_55_8006EF5C:
    /* 3D1F4F8 8006EF5C 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 3D1F4FC 8006EF60 84A08424 */  addiu      $a0, $a0, %lo(D_8006A084)
    /* 3D1F500 8006EF64 B4B7000C */  jal        func_8002DED0
    /* 3D1F504 8006EF68 00000000 */   nop
    /* 3D1F508 8006EF6C E1BB0108 */  j          .Llevel_55_8006EF84
    /* 3D1F50C 8006EF70 00000000 */   nop
  .Llevel_55_8006EF74:
    /* 3D1F510 8006EF74 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* 3D1F514 8006EF78 C4A08424 */  addiu      $a0, $a0, %lo(D_8006A0C4)
  .Llevel_55_8006EF7C:
    /* 3D1F518 8006EF7C E3B6000C */  jal        func_8002DB8C
    /* 3D1F51C 8006EF80 00000000 */   nop
  .Llevel_55_8006EF84:
    /* 3D1F520 8006EF84 1000BF8F */  lw         $ra, 0x10($sp)
    /* 3D1F524 8006EF88 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 3D1F528 8006EF8C 0800E003 */  jr         $ra
    /* 3D1F52C 8006EF90 00000000 */   nop
endlabel func_level_55_8006EF04
