.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_46_8006D3A8

dlabel jtbl_level_46_8006D3A8
    /* 3581144 8006D3A8 2CE20680 */ .word .Llevel_46_8006E22C
    /* 3581148 8006D3AC 48E20680 */ .word .Llevel_46_8006E248
    /* 358114C 8006D3B0 48E20680 */ .word .Llevel_46_8006E248
    /* 3581150 8006D3B4 48E20680 */ .word .Llevel_46_8006E248
    /* 3581154 8006D3B8 48E20680 */ .word .Llevel_46_8006E248
    /* 3581158 8006D3BC 48E20680 */ .word .Llevel_46_8006E248
    /* 358115C 8006D3C0 48E20680 */ .word .Llevel_46_8006E248
    /* 3581160 8006D3C4 2CE20680 */ .word .Llevel_46_8006E22C
    /* 3581164 8006D3C8 48E20680 */ .word .Llevel_46_8006E248
    /* 3581168 8006D3CC 3CE20680 */ .word .Llevel_46_8006E23C
    /* 358116C 8006D3D0 48E20680 */ .word .Llevel_46_8006E248
    /* 3581170 8006D3D4 48E20680 */ .word .Llevel_46_8006E248
    /* 3581174 8006D3D8 48E20680 */ .word .Llevel_46_8006E248
    /* 3581178 8006D3DC 2CE20680 */ .word .Llevel_46_8006E22C
    /* 358117C 8006D3E0 48E20680 */ .word .Llevel_46_8006E248
    /* 3581180 8006D3E4 48E20680 */ .word .Llevel_46_8006E248
    /* 3581184 8006D3E8 48E20680 */ .word .Llevel_46_8006E248
    /* 3581188 8006D3EC 48E20680 */ .word .Llevel_46_8006E248
    /* 358118C 8006D3F0 48E20680 */ .word .Llevel_46_8006E248
    /* 3581190 8006D3F4 2CE20680 */ .word .Llevel_46_8006E22C
    /* 3581194 8006D3F8 48E20680 */ .word .Llevel_46_8006E248
    /* 3581198 8006D3FC 48E20680 */ .word .Llevel_46_8006E248
    /* 358119C 8006D400 48E20680 */ .word .Llevel_46_8006E248
    /* 35811A0 8006D404 48E20680 */ .word .Llevel_46_8006E248
    /* 35811A4 8006D408 48E20680 */ .word .Llevel_46_8006E248
    /* 35811A8 8006D40C 48E20680 */ .word .Llevel_46_8006E248
    /* 35811AC 8006D410 48E20680 */ .word .Llevel_46_8006E248
    /* 35811B0 8006D414 48E20680 */ .word .Llevel_46_8006E248
    /* 35811B4 8006D418 48E20680 */ .word .Llevel_46_8006E248
    /* 35811B8 8006D41C 48E20680 */ .word .Llevel_46_8006E248
    /* 35811BC 8006D420 48E20680 */ .word .Llevel_46_8006E248
    /* 35811C0 8006D424 48E20680 */ .word .Llevel_46_8006E248
    /* 35811C4 8006D428 48E20680 */ .word .Llevel_46_8006E248
    /* 35811C8 8006D42C 48E20680 */ .word .Llevel_46_8006E248
    /* 35811CC 8006D430 2CE20680 */ .word .Llevel_46_8006E22C
    /* 35811D0 8006D434 2CE20680 */ .word .Llevel_46_8006E22C
    /* 35811D4 8006D438 48E20680 */ .word .Llevel_46_8006E248
    /* 35811D8 8006D43C 48E20680 */ .word .Llevel_46_8006E248
    /* 35811DC 8006D440 48E20680 */ .word .Llevel_46_8006E248
    /* 35811E0 8006D444 2CE20680 */ .word .Llevel_46_8006E22C
enddlabel jtbl_level_46_8006D3A8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_46_8006E1DC, 0x7C

glabel func_level_46_8006E1DC
    /* 3581F78 8006E1DC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 3581F7C 8006E1E0 00210400 */  sll        $a0, $a0, 4
    /* 3581F80 8006E1E4 0780023C */  lui        $v0, %hi(D_800683B0)
    /* 3581F84 8006E1E8 B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* 3581F88 8006E1EC 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 3581F8C 8006E1F0 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 3581F90 8006E1F4 21208200 */  addu       $a0, $a0, $v0
    /* 3581F94 8006E1F8 1000BFAF */  sw         $ra, 0x10($sp)
    /* 3581F98 8006E1FC 0680013C */  lui        $at, %hi(D_80066F38)
    /* 3581F9C 8006E200 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* 3581FA0 8006E204 EDFF6324 */  addiu      $v1, $v1, -0x13
    /* 3581FA4 8006E208 2800622C */  sltiu      $v0, $v1, 0x28
    /* 3581FA8 8006E20C 0E004010 */  beqz       $v0, .Llevel_46_8006E248
    /* 3581FAC 8006E210 80100300 */   sll       $v0, $v1, 2
    /* 3581FB0 8006E214 0780013C */  lui        $at, %hi(jtbl_level_46_8006D3A8)
    /* 3581FB4 8006E218 21082200 */  addu       $at, $at, $v0
    /* 3581FB8 8006E21C A8D3228C */  lw         $v0, %lo(jtbl_level_46_8006D3A8)($at)
    /* 3581FBC 8006E220 00000000 */  nop
    /* 3581FC0 8006E224 08004000 */  jr         $v0
    /* 3581FC4 8006E228 00000000 */   nop
  .Llevel_46_8006E22C:
    /* 3581FC8 8006E22C 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* 3581FCC 8006E230 C4A08424 */  addiu      $a0, $a0, %lo(D_8006A0C4)
    /* 3581FD0 8006E234 90B80108 */  j          .Llevel_46_8006E240
    /* 3581FD4 8006E238 00000000 */   nop
  .Llevel_46_8006E23C:
    /* 3581FD8 8006E23C 21200000 */  addu       $a0, $zero, $zero
  .Llevel_46_8006E240:
    /* 3581FDC 8006E240 E3B6000C */  jal        func_8002DB8C
    /* 3581FE0 8006E244 00000000 */   nop
  .Llevel_46_8006E248:
    /* 3581FE4 8006E248 1000BF8F */  lw         $ra, 0x10($sp)
    /* 3581FE8 8006E24C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 3581FEC 8006E250 0800E003 */  jr         $ra
    /* 3581FF0 8006E254 00000000 */   nop
endlabel func_level_46_8006E1DC
