.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_46_8006D308

dlabel jtbl_level_46_8006D308
    /* 35810A4 8006D308 58E00680 */ .word .Llevel_46_8006E058
    /* 35810A8 8006D30C 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810AC 8006D310 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810B0 8006D314 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810B4 8006D318 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810B8 8006D31C 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810BC 8006D320 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810C0 8006D324 A8E00680 */ .word .Llevel_46_8006E0A8
    /* 35810C4 8006D328 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810C8 8006D32C C8E00680 */ .word .Llevel_46_8006E0C8
    /* 35810CC 8006D330 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810D0 8006D334 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810D4 8006D338 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810D8 8006D33C 88E00680 */ .word .Llevel_46_8006E088
    /* 35810DC 8006D340 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810E0 8006D344 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810E4 8006D348 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810E8 8006D34C 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810EC 8006D350 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810F0 8006D354 58E00680 */ .word .Llevel_46_8006E058
    /* 35810F4 8006D358 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810F8 8006D35C 5CE10680 */ .word .Llevel_46_8006E15C
    /* 35810FC 8006D360 5CE10680 */ .word .Llevel_46_8006E15C
    /* 3581100 8006D364 5CE10680 */ .word .Llevel_46_8006E15C
    /* 3581104 8006D368 5CE10680 */ .word .Llevel_46_8006E15C
    /* 3581108 8006D36C 5CE10680 */ .word .Llevel_46_8006E15C
    /* 358110C 8006D370 5CE10680 */ .word .Llevel_46_8006E15C
    /* 3581110 8006D374 5CE10680 */ .word .Llevel_46_8006E15C
    /* 3581114 8006D378 5CE10680 */ .word .Llevel_46_8006E15C
    /* 3581118 8006D37C 5CE10680 */ .word .Llevel_46_8006E15C
    /* 358111C 8006D380 5CE10680 */ .word .Llevel_46_8006E15C
    /* 3581120 8006D384 5CE10680 */ .word .Llevel_46_8006E15C
    /* 3581124 8006D388 5CE10680 */ .word .Llevel_46_8006E15C
    /* 3581128 8006D38C 5CE10680 */ .word .Llevel_46_8006E15C
    /* 358112C 8006D390 88E00680 */ .word .Llevel_46_8006E088
    /* 3581130 8006D394 88E00680 */ .word .Llevel_46_8006E088
    /* 3581134 8006D398 5CE10680 */ .word .Llevel_46_8006E15C
    /* 3581138 8006D39C 5CE10680 */ .word .Llevel_46_8006E15C
    /* 358113C 8006D3A0 5CE10680 */ .word .Llevel_46_8006E15C
    /* 3581140 8006D3A4 1CE10680 */ .word .Llevel_46_8006E11C
enddlabel jtbl_level_46_8006D308


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_46_8006E020, 0x14C

glabel func_level_46_8006E020
    /* 3581DBC 8006E020 0780023C */  lui        $v0, %hi(D_8006A040)
    /* 3581DC0 8006E024 40A0428C */  lw         $v0, %lo(D_8006A040)($v0)
    /* 3581DC4 8006E028 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 3581DC8 8006E02C EDFF4324 */  addiu      $v1, $v0, -0x13
    /* 3581DCC 8006E030 2800622C */  sltiu      $v0, $v1, 0x28
    /* 3581DD0 8006E034 49004010 */  beqz       $v0, .Llevel_46_8006E15C
    /* 3581DD4 8006E038 1000BFAF */   sw        $ra, 0x10($sp)
    /* 3581DD8 8006E03C 80100300 */  sll        $v0, $v1, 2
    /* 3581DDC 8006E040 0780013C */  lui        $at, %hi(jtbl_level_46_8006D308)
    /* 3581DE0 8006E044 21082200 */  addu       $at, $at, $v0
    /* 3581DE4 8006E048 08D3228C */  lw         $v0, %lo(jtbl_level_46_8006D308)($at)
    /* 3581DE8 8006E04C 00000000 */  nop
    /* 3581DEC 8006E050 08004000 */  jr         $v0
    /* 3581DF0 8006E054 00000000 */   nop
  .Llevel_46_8006E058:
    /* 3581DF4 8006E058 71B6000C */  jal        func_8002D9C4
    /* 3581DF8 8006E05C 00000000 */   nop
    /* 3581DFC 8006E060 03004014 */  bnez       $v0, .Llevel_46_8006E070
    /* 3581E00 8006E064 00000000 */   nop
    /* 3581E04 8006E068 FEB5000C */  jal        func_8002D7F8
    /* 3581E08 8006E06C 00000000 */   nop
  .Llevel_46_8006E070:
    /* 3581E0C 8006E070 3DB0000C */  jal        func_8002C0F4
    /* 3581E10 8006E074 00000000 */   nop
    /* 3581E14 8006E078 0780013C */  lui        $at, %hi(D_8006A0B4)
    /* 3581E18 8006E07C B4A020AC */  sw         $zero, %lo(D_8006A0B4)($at)
    /* 3581E1C 8006E080 24B80108 */  j          .Llevel_46_8006E090
    /* 3581E20 8006E084 00000000 */   nop
  .Llevel_46_8006E088:
    /* 3581E24 8006E088 3DB0000C */  jal        func_8002C0F4
    /* 3581E28 8006E08C 00000000 */   nop
  .Llevel_46_8006E090:
    /* 3581E2C 8006E090 22B3000C */  jal        func_8002CC88
    /* 3581E30 8006E094 00000000 */   nop
  .Llevel_46_8006E098:
    /* 3581E34 8006E098 0780013C */  lui        $at, %hi(D_8006A018)
    /* 3581E38 8006E09C 18A020AC */  sw         $zero, %lo(D_8006A018)($at)
    /* 3581E3C 8006E0A0 57B80108 */  j          .Llevel_46_8006E15C
    /* 3581E40 8006E0A4 00000000 */   nop
  .Llevel_46_8006E0A8:
    /* 3581E44 8006E0A8 3DB0000C */  jal        func_8002C0F4
    /* 3581E48 8006E0AC 00000000 */   nop
    /* 3581E4C 8006E0B0 22B3000C */  jal        func_8002CC88
    /* 3581E50 8006E0B4 00000000 */   nop
    /* 3581E54 8006E0B8 C2B6000C */  jal        func_8002DB08
    /* 3581E58 8006E0BC 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 3581E5C 8006E0C0 26B80108 */  j          .Llevel_46_8006E098
    /* 3581E60 8006E0C4 00000000 */   nop
  .Llevel_46_8006E0C8:
    /* 3581E64 8006E0C8 3DB0000C */  jal        func_8002C0F4
    /* 3581E68 8006E0CC 00000000 */   nop
    /* 3581E6C 8006E0D0 22B3000C */  jal        func_8002CC88
    /* 3581E70 8006E0D4 00000000 */   nop
    /* 3581E74 8006E0D8 81AF000C */  jal        func_8002BE04
    /* 3581E78 8006E0DC 00000000 */   nop
    /* 3581E7C 8006E0E0 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 3581E80 8006E0E4 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 3581E84 8006E0E8 00000000 */  nop
    /* 3581E88 8006E0EC EAFF4104 */  bgez       $v0, .Llevel_46_8006E098
    /* 3581E8C 8006E0F0 00000000 */   nop
    /* 3581E90 8006E0F4 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 3581E94 8006E0F8 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 3581E98 8006E0FC 00000000 */  nop
    /* 3581E9C 8006E100 04004228 */  slti       $v0, $v0, 0x4
    /* 3581EA0 8006E104 E4FF4014 */  bnez       $v0, .Llevel_46_8006E098
    /* 3581EA4 8006E108 01000224 */   addiu     $v0, $zero, 0x1
    /* 3581EA8 8006E10C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 3581EAC 8006E110 44A022AC */  sw         $v0, %lo(D_8006A044)($at)
    /* 3581EB0 8006E114 26B80108 */  j          .Llevel_46_8006E098
    /* 3581EB4 8006E118 00000000 */   nop
  .Llevel_46_8006E11C:
    /* 3581EB8 8006E11C 3DB0000C */  jal        func_8002C0F4
    /* 3581EBC 8006E120 00000000 */   nop
    /* 3581EC0 8006E124 22B3000C */  jal        func_8002CC88
    /* 3581EC4 8006E128 00000000 */   nop
    /* 3581EC8 8006E12C FF000224 */  addiu      $v0, $zero, 0xFF
    /* 3581ECC 8006E130 0780013C */  lui        $at, %hi(D_8006A013)
    /* 3581ED0 8006E134 13A022A0 */  sb         $v0, %lo(D_8006A013)($at)
    /* 3581ED4 8006E138 20000224 */  addiu      $v0, $zero, 0x20
    /* 3581ED8 8006E13C 0780013C */  lui        $at, %hi(D_8006A018)
    /* 3581EDC 8006E140 18A020AC */  sw         $zero, %lo(D_8006A018)($at)
    /* 3581EE0 8006E144 0780013C */  lui        $at, %hi(D_8006A012)
    /* 3581EE4 8006E148 12A022A0 */  sb         $v0, %lo(D_8006A012)($at)
    /* 3581EE8 8006E14C 0780013C */  lui        $at, %hi(D_8006A011)
    /* 3581EEC 8006E150 11A022A0 */  sb         $v0, %lo(D_8006A011)($at)
    /* 3581EF0 8006E154 0780013C */  lui        $at, %hi(D_8006A010)
    /* 3581EF4 8006E158 10A022A0 */  sb         $v0, %lo(D_8006A010)($at)
  .Llevel_46_8006E15C:
    /* 3581EF8 8006E15C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 3581EFC 8006E160 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 3581F00 8006E164 0800E003 */  jr         $ra
    /* 3581F04 8006E168 00000000 */   nop
endlabel func_level_46_8006E020
