.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_44_8006D478

dlabel jtbl_level_44_8006D478
    /* 31D4A14 8006D478 80ED0680 */ .word .Llevel_44_8006ED80
    /* 31D4A18 8006D47C F0EC0680 */ .word .Llevel_44_8006ECF0
    /* 31D4A1C 8006D480 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A20 8006D484 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A24 8006D488 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A28 8006D48C 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A2C 8006D490 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A30 8006D494 14EF0680 */ .word .Llevel_44_8006EF14
    /* 31D4A34 8006D498 64EF0680 */ .word .Llevel_44_8006EF64
    /* 31D4A38 8006D49C 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A3C 8006D4A0 E4EF0680 */ .word .Llevel_44_8006EFE4
    /* 31D4A40 8006D4A4 60EE0680 */ .word .Llevel_44_8006EE60
    /* 31D4A44 8006D4A8 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A48 8006D4AC 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A4C 8006D4B0 78F00680 */ .word .Llevel_44_8006F078
    /* 31D4A50 8006D4B4 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A54 8006D4B8 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A58 8006D4BC 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A5C 8006D4C0 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A60 8006D4C4 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A64 8006D4C8 F0EC0680 */ .word .Llevel_44_8006ECF0
    /* 31D4A68 8006D4CC 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A6C 8006D4D0 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A70 8006D4D4 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A74 8006D4D8 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A78 8006D4DC 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A7C 8006D4E0 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A80 8006D4E4 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A84 8006D4E8 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A88 8006D4EC 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A8C 8006D4F0 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A90 8006D4F4 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A94 8006D4F8 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A98 8006D4FC 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4A9C 8006D500 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4AA0 8006D504 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4AA4 8006D508 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4AA8 8006D50C 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4AAC 8006D510 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4AB0 8006D514 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4AB4 8006D518 78F00680 */ .word .Llevel_44_8006F078
    /* 31D4AB8 8006D51C 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4ABC 8006D520 7CF10680 */ .word .Llevel_44_8006F17C
    /* 31D4AC0 8006D524 CCF00680 */ .word .Llevel_44_8006F0CC
enddlabel jtbl_level_44_8006D478


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_44_8006ECB8, 0x4D8

glabel func_level_44_8006ECB8
    /* 31D6254 8006ECB8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 31D6258 8006ECBC 1000B0AF */  sw         $s0, 0x10($sp)
    /* 31D625C 8006ECC0 21808000 */  addu       $s0, $a0, $zero
    /* 31D6260 8006ECC4 EEFF0326 */  addiu      $v1, $s0, -0x12
    /* 31D6264 8006ECC8 2C00622C */  sltiu      $v0, $v1, 0x2C
    /* 31D6268 8006ECCC 2B014010 */  beqz       $v0, .Llevel_44_8006F17C
    /* 31D626C 8006ECD0 1400BFAF */   sw        $ra, 0x14($sp)
    /* 31D6270 8006ECD4 80100300 */  sll        $v0, $v1, 2
    /* 31D6274 8006ECD8 0780013C */  lui        $at, %hi(jtbl_level_44_8006D478)
    /* 31D6278 8006ECDC 21082200 */  addu       $at, $at, $v0
    /* 31D627C 8006ECE0 78D4228C */  lw         $v0, %lo(jtbl_level_44_8006D478)($at)
    /* 31D6280 8006ECE4 00000000 */  nop
    /* 31D6284 8006ECE8 08004000 */  jr         $v0
    /* 31D6288 8006ECEC 00000000 */   nop
  .Llevel_44_8006ECF0:
    /* 31D628C 8006ECF0 0780013C */  lui        $at, %hi(D_8006A048)
    /* 31D6290 8006ECF4 48A020AC */  sw         $zero, %lo(D_8006A048)($at)
    /* 31D6294 8006ECF8 0780013C */  lui        $at, %hi(D_8006A044)
    /* 31D6298 8006ECFC 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 31D629C 8006ED00 AFB8000C */  jal        func_8002E2BC
    /* 31D62A0 8006ED04 00000000 */   nop
    /* 31D62A4 8006ED08 01000224 */  addiu      $v0, $zero, 0x1
    /* 31D62A8 8006ED0C 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 31D62AC 8006ED10 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 31D62B0 8006ED14 25000224 */  addiu      $v0, $zero, 0x25
    /* 31D62B4 8006ED18 04000216 */  bne        $s0, $v0, .Llevel_44_8006ED2C
    /* 31D62B8 8006ED1C 01000424 */   addiu     $a0, $zero, 0x1
    /* 31D62BC 8006ED20 05000424 */  addiu      $a0, $zero, 0x5
    /* 31D62C0 8006ED24 4CBB0108 */  j          .Llevel_44_8006ED30
    /* 31D62C4 8006ED28 08000524 */   addiu     $a1, $zero, 0x8
  .Llevel_44_8006ED2C:
    /* 31D62C8 8006ED2C 03000524 */  addiu      $a1, $zero, 0x3
  .Llevel_44_8006ED30:
    /* 31D62CC 8006ED30 47E2000C */  jal        func_8003891C
    /* 31D62D0 8006ED34 00000000 */   nop
    /* 31D62D4 8006ED38 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 31D62D8 8006ED3C 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* 31D62DC 8006ED40 0680033C */  lui        $v1, %hi(D_800670B4)
    /* 31D62E0 8006ED44 B470638C */  lw         $v1, %lo(D_800670B4)($v1)
    /* 31D62E4 8006ED48 0780013C */  lui        $at, %hi(D_8006A140)
    /* 31D62E8 8006ED4C 40A120AC */  sw         $zero, %lo(D_8006A140)($at)
    /* 31D62EC 8006ED50 0A016010 */  beqz       $v1, .Llevel_44_8006F17C
    /* 31D62F0 8006ED54 25000224 */   addiu     $v0, $zero, 0x25
    /* 31D62F4 8006ED58 03000216 */  bne        $s0, $v0, .Llevel_44_8006ED68
    /* 31D62F8 8006ED5C 27000224 */   addiu     $v0, $zero, 0x27
    /* 31D62FC 8006ED60 5CBB0108 */  j          .Llevel_44_8006ED70
    /* 31D6300 8006ED64 F1010424 */   addiu     $a0, $zero, 0x1F1
  .Llevel_44_8006ED68:
    /* 31D6304 8006ED68 04010216 */  bne        $s0, $v0, .Llevel_44_8006F17C
    /* 31D6308 8006ED6C DB010424 */   addiu     $a0, $zero, 0x1DB
  .Llevel_44_8006ED70:
    /* 31D630C 8006ED70 09F86000 */  jalr       $v1
    /* 31D6310 8006ED74 21280000 */   addu      $a1, $zero, $zero
    /* 31D6314 8006ED78 5FBC0108 */  j          .Llevel_44_8006F17C
    /* 31D6318 8006ED7C 00000000 */   nop
  .Llevel_44_8006ED80:
    /* 31D631C 8006ED80 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 31D6320 8006ED84 48A06324 */  addiu      $v1, $v1, %lo(D_8006A048)
    /* 31D6324 8006ED88 0780023C */  lui        $v0, %hi(D_8006A208)
    /* 31D6328 8006ED8C 08A2428C */  lw         $v0, %lo(D_8006A208)($v0)
    /* 31D632C 8006ED90 00000000 */  nop
    /* 31D6330 8006ED94 0000508C */  lw         $s0, 0x0($v0)
    /* 31D6334 8006ED98 0E000224 */  addiu      $v0, $zero, 0xE
    /* 31D6338 8006ED9C 000062AC */  sw         $v0, 0x0($v1)
    /* 31D633C 8006EDA0 0780013C */  lui        $at, %hi(D_8006A044)
    /* 31D6340 8006EDA4 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 31D6344 8006EDA8 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 31D6348 8006EDAC ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 31D634C 8006EDB0 686F000C */  jal        func_8001BDA0
    /* 31D6350 8006EDB4 3C006424 */   addiu     $a0, $v1, 0x3C
    /* 31D6354 8006EDB8 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 31D6358 8006EDBC 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 31D635C 8006EDC0 0780063C */  lui        $a2, %hi(D_8006A05C)
    /* 31D6360 8006EDC4 5CA0C68C */  lw         $a2, %lo(D_8006A05C)($a2)
    /* 31D6364 8006EDC8 0780023C */  lui        $v0, %hi(D_80069FF8)
    /* 31D6368 8006EDCC F89F428C */  lw         $v0, %lo(D_80069FF8)($v0)
    /* 31D636C 8006EDD0 1400A38C */  lw         $v1, 0x14($a1)
    /* 31D6370 8006EDD4 0000048E */  lw         $a0, 0x0($s0)
    /* 31D6374 8006EDD8 0780013C */  lui        $at, %hi(D_8006A140)
    /* 31D6378 8006EDDC 40A126AC */  sw         $a2, %lo(D_8006A140)($at)
    /* 31D637C 8006EDE0 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 31D6380 8006EDE4 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* 31D6384 8006EDE8 21186400 */  addu       $v1, $v1, $a0
    /* 31D6388 8006EDEC 0780013C */  lui        $at, %hi(D_8006A144)
    /* 31D638C 8006EDF0 44A123AC */  sw         $v1, %lo(D_8006A144)($at)
    /* 31D6390 8006EDF4 23186200 */  subu       $v1, $v1, $v0
    /* 31D6394 8006EDF8 00F86324 */  addiu      $v1, $v1, -0x800
    /* 31D6398 8006EDFC 0780013C */  lui        $at, %hi(D_8006A14C)
    /* 31D639C 8006EE00 4CA123AC */  sw         $v1, %lo(D_8006A14C)($at)
    /* 31D63A0 8006EE04 801A0300 */  sll        $v1, $v1, 10
    /* 31D63A4 8006EE08 831A0300 */  sra        $v1, $v1, 10
    /* 31D63A8 8006EE0C 00046324 */  addiu      $v1, $v1, 0x400
    /* 31D63AC 8006EE10 0780013C */  lui        $at, %hi(D_8006A148)
    /* 31D63B0 8006EE14 48A123AC */  sw         $v1, %lo(D_8006A148)($at)
    /* 31D63B4 8006EE18 4600A290 */  lbu        $v0, 0x46($a1)
    /* 31D63B8 8006EE1C 00000000 */  nop
    /* 31D63BC 8006EE20 00110200 */  sll        $v0, $v0, 4
    /* 31D63C0 8006EE24 23104600 */  subu       $v0, $v0, $a2
    /* 31D63C4 8006EE28 23104300 */  subu       $v0, $v0, $v1
    /* 31D63C8 8006EE2C FF0F4330 */  andi       $v1, $v0, 0xFFF
    /* 31D63CC 8006EE30 01086228 */  slti       $v0, $v1, 0x801
    /* 31D63D0 8006EE34 0780013C */  lui        $at, %hi(D_8006A148)
    /* 31D63D4 8006EE38 48A123AC */  sw         $v1, %lo(D_8006A148)($at)
    /* 31D63D8 8006EE3C 03004014 */  bnez       $v0, .Llevel_44_8006EE4C
    /* 31D63DC 8006EE40 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 31D63E0 8006EE44 0780013C */  lui        $at, %hi(D_8006A148)
    /* 31D63E4 8006EE48 48A122AC */  sw         $v0, %lo(D_8006A148)($at)
  .Llevel_44_8006EE4C:
    /* 31D63E8 8006EE4C 0400028E */  lw         $v0, 0x4($s0)
    /* 31D63EC 8006EE50 0780013C */  lui        $at, %hi(D_8006A150)
    /* 31D63F0 8006EE54 50A122AC */  sw         $v0, %lo(D_8006A150)($at)
    /* 31D63F4 8006EE58 5FBC0108 */  j          .Llevel_44_8006F17C
    /* 31D63F8 8006EE5C 00000000 */   nop
  .Llevel_44_8006EE60:
    /* 31D63FC 8006EE60 0780043C */  lui        $a0, %hi(D_8006A048)
    /* 31D6400 8006EE64 48A0848C */  lw         $a0, %lo(D_8006A048)($a0)
    /* 31D6404 8006EE68 0780033C */  lui        $v1, %hi(D_8006A20C)
    /* 31D6408 8006EE6C 0CA2638C */  lw         $v1, %lo(D_8006A20C)($v1)
    /* 31D640C 8006EE70 07000224 */  addiu      $v0, $zero, 0x7
    /* 31D6410 8006EE74 0780013C */  lui        $at, %hi(D_8006A048)
    /* 31D6414 8006EE78 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 31D6418 8006EE7C 0780023C */  lui        $v0, %hi(D_8006A210)
    /* 31D641C 8006EE80 10A2428C */  lw         $v0, %lo(D_8006A210)($v0)
    /* 31D6420 8006EE84 0780013C */  lui        $at, %hi(D_8006A044)
    /* 31D6424 8006EE88 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 31D6428 8006EE8C 80190300 */  sll        $v1, $v1, 6
    /* 31D642C 8006EE90 0780013C */  lui        $at, %hi(D_8006A084)
    /* 31D6430 8006EE94 84A023AC */  sw         $v1, %lo(D_8006A084)($at)
    /* 31D6434 8006EE98 0780033C */  lui        $v1, %hi(D_8006A214)
    /* 31D6438 8006EE9C 14A2638C */  lw         $v1, %lo(D_8006A214)($v1)
    /* 31D643C 8006EEA0 80110200 */  sll        $v0, $v0, 6
    /* 31D6440 8006EEA4 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 31D6444 8006EEA8 3CA124AC */  sw         $a0, %lo(D_8006A13C)($at)
    /* 31D6448 8006EEAC 0780013C */  lui        $at, %hi(D_8006A088)
    /* 31D644C 8006EEB0 88A022AC */  sw         $v0, %lo(D_8006A088)($at)
    /* 31D6450 8006EEB4 03006014 */  bnez       $v1, .Llevel_44_8006EEC4
    /* 31D6454 8006EEB8 80110300 */   sll       $v0, $v1, 6
    /* 31D6458 8006EEBC 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 31D645C 8006EEC0 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
  .Llevel_44_8006EEC4:
    /* 31D6460 8006EEC4 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D6464 8006EEC8 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 31D6468 8006EECC C2B6000C */  jal        func_8002DB08
    /* 31D646C 8006EED0 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 31D6470 8006EED4 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 31D6474 8006EED8 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 31D6478 8006EEDC 01000224 */  addiu      $v0, $zero, 0x1
    /* 31D647C 8006EEE0 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 31D6480 8006EEE4 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 31D6484 8006EEE8 0F000224 */  addiu      $v0, $zero, 0xF
    /* 31D6488 8006EEEC 0780013C */  lui        $at, %hi(D_8006838C)
    /* 31D648C 8006EEF0 8C8322AC */  sw         $v0, %lo(D_8006838C)($at)
    /* 31D6490 8006EEF4 A1006010 */  beqz       $v1, .Llevel_44_8006F17C
    /* 31D6494 8006EEF8 05000424 */   addiu     $a0, $zero, 0x5
    /* 31D6498 8006EEFC 0A000524 */  addiu      $a1, $zero, 0xA
    /* 31D649C 8006EF00 21300000 */  addu       $a2, $zero, $zero
    /* 31D64A0 8006EF04 09F86000 */  jalr       $v1
    /* 31D64A4 8006EF08 21380000 */   addu      $a3, $zero, $zero
    /* 31D64A8 8006EF0C 5FBC0108 */  j          .Llevel_44_8006F17C
    /* 31D64AC 8006EF10 00000000 */   nop
  .Llevel_44_8006EF14:
    /* 31D64B0 8006EF14 0680033C */  lui        $v1, %hi(D_80067020)
    /* 31D64B4 8006EF18 2070638C */  lw         $v1, %lo(D_80067020)($v1)
    /* 31D64B8 8006EF1C 09000224 */  addiu      $v0, $zero, 0x9
    /* 31D64BC 8006EF20 0780013C */  lui        $at, %hi(D_8006A048)
    /* 31D64C0 8006EF24 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 31D64C4 8006EF28 0600023C */  lui        $v0, (0x60000 >> 16)
    /* 31D64C8 8006EF2C 0780013C */  lui        $at, %hi(D_8006A128)
    /* 31D64CC 8006EF30 28A122AC */  sw         $v0, %lo(D_8006A128)($at)
    /* 31D64D0 8006EF34 01000224 */  addiu      $v0, $zero, 0x1
    /* 31D64D4 8006EF38 0780013C */  lui        $at, %hi(D_8006A044)
    /* 31D64D8 8006EF3C 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 31D64DC 8006EF40 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 31D64E0 8006EF44 3CA120AC */  sw         $zero, %lo(D_8006A13C)($at)
    /* 31D64E4 8006EF48 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 31D64E8 8006EF4C ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 31D64EC 8006EF50 0780013C */  lui        $at, %hi(D_8006A1AD)
    /* 31D64F0 8006EF54 ADA122A0 */  sb         $v0, %lo(D_8006A1AD)($at)
    /* 31D64F4 8006EF58 22006490 */  lbu        $a0, 0x22($v1)
    /* 31D64F8 8006EF5C 2FBC0108 */  j          .Llevel_44_8006F0BC
    /* 31D64FC 8006EF60 21280000 */   addu      $a1, $zero, $zero
  .Llevel_44_8006EF64:
    /* 31D6500 8006EF64 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 31D6504 8006EF68 3CA16324 */  addiu      $v1, $v1, %lo(D_8006A13C)
    /* 31D6508 8006EF6C 48FF6424 */  addiu      $a0, $v1, -0xB8
    /* 31D650C 8006EF70 0780053C */  lui        $a1, %hi(D_8006A048)
    /* 31D6510 8006EF74 48A0A58C */  lw         $a1, %lo(D_8006A048)($a1)
    /* 31D6514 8006EF78 07000224 */  addiu      $v0, $zero, 0x7
    /* 31D6518 8006EF7C 0780013C */  lui        $at, %hi(D_8006A048)
    /* 31D651C 8006EF80 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 31D6520 8006EF84 0780013C */  lui        $at, %hi(D_8006A044)
    /* 31D6524 8006EF88 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 31D6528 8006EF8C 686F000C */  jal        func_8001BDA0
    /* 31D652C 8006EF90 000065AC */   sw        $a1, 0x0($v1)
    /* 31D6530 8006EF94 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 31D6534 8006EF98 FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 31D6538 8006EF9C 01000224 */  addiu      $v0, $zero, 0x1
    /* 31D653C 8006EFA0 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 31D6540 8006EFA4 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 31D6544 8006EFA8 0F000224 */  addiu      $v0, $zero, 0xF
    /* 31D6548 8006EFAC 0780013C */  lui        $at, %hi(D_8006838C)
    /* 31D654C 8006EFB0 8C8322AC */  sw         $v0, %lo(D_8006838C)($at)
    /* 31D6550 8006EFB4 05006010 */  beqz       $v1, .Llevel_44_8006EFCC
    /* 31D6554 8006EFB8 05000424 */   addiu     $a0, $zero, 0x5
    /* 31D6558 8006EFBC 0A000524 */  addiu      $a1, $zero, 0xA
    /* 31D655C 8006EFC0 21300000 */  addu       $a2, $zero, $zero
    /* 31D6560 8006EFC4 09F86000 */  jalr       $v1
    /* 31D6564 8006EFC8 21380000 */   addu      $a3, $zero, $zero
  .Llevel_44_8006EFCC:
    /* 31D6568 8006EFCC 0680023C */  lui        $v0, %hi(D_80067020)
    /* 31D656C 8006EFD0 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 31D6570 8006EFD4 00000000 */  nop
    /* 31D6574 8006EFD8 09004490 */  lbu        $a0, 0x9($v0)
    /* 31D6578 8006EFDC 2FBC0108 */  j          .Llevel_44_8006F0BC
    /* 31D657C 8006EFE0 21280000 */   addu      $a1, $zero, $zero
  .Llevel_44_8006EFE4:
    /* 31D6580 8006EFE4 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 31D6584 8006EFE8 3CA16324 */  addiu      $v1, $v1, %lo(D_8006A13C)
    /* 31D6588 8006EFEC 48FF6424 */  addiu      $a0, $v1, -0xB8
    /* 31D658C 8006EFF0 54FF7024 */  addiu      $s0, $v1, -0xAC
    /* 31D6590 8006EFF4 21280002 */  addu       $a1, $s0, $zero
    /* 31D6594 8006EFF8 0780063C */  lui        $a2, %hi(D_8006A048)
    /* 31D6598 8006EFFC 48A0C68C */  lw         $a2, %lo(D_8006A048)($a2)
    /* 31D659C 8006F000 07000224 */  addiu      $v0, $zero, 0x7
    /* 31D65A0 8006F004 0780013C */  lui        $at, %hi(D_8006A048)
    /* 31D65A4 8006F008 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 31D65A8 8006F00C 0780013C */  lui        $at, %hi(D_8006A044)
    /* 31D65AC 8006F010 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 31D65B0 8006F014 6C6F000C */  jal        func_8001BDB0
    /* 31D65B4 8006F018 000066AC */   sw        $a2, 0x0($v1)
    /* 31D65B8 8006F01C 21200002 */  addu       $a0, $s0, $zero
    /* 31D65BC 8006F020 886E000C */  jal        func_8001BA20
    /* 31D65C0 8006F024 21280000 */   addu      $a1, $zero, $zero
    /* 31D65C4 8006F028 0680033C */  lui        $v1, %hi(D_800670FC)
    /* 31D65C8 8006F02C FC70638C */  lw         $v1, %lo(D_800670FC)($v1)
    /* 31D65CC 8006F030 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 31D65D0 8006F034 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 31D65D4 8006F038 C00D0224 */  addiu      $v0, $zero, 0xDC0
    /* 31D65D8 8006F03C 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D65DC 8006F040 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 31D65E0 8006F044 0F000224 */  addiu      $v0, $zero, 0xF
    /* 31D65E4 8006F048 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 31D65E8 8006F04C ACA120A0 */  sb         $zero, %lo(D_8006A1AC)($at)
    /* 31D65EC 8006F050 0780013C */  lui        $at, %hi(D_8006838C)
    /* 31D65F0 8006F054 8C8322AC */  sw         $v0, %lo(D_8006838C)($at)
    /* 31D65F4 8006F058 14006010 */  beqz       $v1, .Llevel_44_8006F0AC
    /* 31D65F8 8006F05C 05000424 */   addiu     $a0, $zero, 0x5
    /* 31D65FC 8006F060 0A000524 */  addiu      $a1, $zero, 0xA
    /* 31D6600 8006F064 21300000 */  addu       $a2, $zero, $zero
    /* 31D6604 8006F068 09F86000 */  jalr       $v1
    /* 31D6608 8006F06C 21380000 */   addu      $a3, $zero, $zero
    /* 31D660C 8006F070 2BBC0108 */  j          .Llevel_44_8006F0AC
    /* 31D6610 8006F074 00000000 */   nop
  .Llevel_44_8006F078:
    /* 31D6614 8006F078 08000224 */  addiu      $v0, $zero, 0x8
    /* 31D6618 8006F07C 0780013C */  lui        $at, %hi(D_8006A048)
    /* 31D661C 8006F080 48A022AC */  sw         $v0, %lo(D_8006A048)($at)
    /* 31D6620 8006F084 0780013C */  lui        $at, %hi(D_8006A044)
    /* 31D6624 8006F088 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 31D6628 8006F08C C2B6000C */  jal        func_8002DB08
    /* 31D662C 8006F090 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 31D6630 8006F094 01000224 */  addiu      $v0, $zero, 0x1
    /* 31D6634 8006F098 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 31D6638 8006F09C ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 31D663C 8006F0A0 3A000224 */  addiu      $v0, $zero, 0x3A
    /* 31D6640 8006F0A4 35000216 */  bne        $s0, $v0, .Llevel_44_8006F17C
    /* 31D6644 8006F0A8 00000000 */   nop
  .Llevel_44_8006F0AC:
    /* 31D6648 8006F0AC 0680023C */  lui        $v0, %hi(D_80067020)
    /* 31D664C 8006F0B0 2070428C */  lw         $v0, %lo(D_80067020)($v0)
    /* 31D6650 8006F0B4 21280000 */  addu       $a1, $zero, $zero
    /* 31D6654 8006F0B8 0C004490 */  lbu        $a0, 0xC($v0)
  .Llevel_44_8006F0BC:
    /* 31D6658 8006F0BC C841010C */  jal        func_80050720
    /* 31D665C 8006F0C0 21300000 */   addu      $a2, $zero, $zero
    /* 31D6660 8006F0C4 5FBC0108 */  j          .Llevel_44_8006F17C
    /* 31D6664 8006F0C8 00000000 */   nop
  .Llevel_44_8006F0CC:
    /* 31D6668 8006F0CC 0780033C */  lui        $v1, %hi(D_8006A048)
    /* 31D666C 8006F0D0 48A06324 */  addiu      $v1, $v1, %lo(D_8006A048)
    /* 31D6670 8006F0D4 48006424 */  addiu      $a0, $v1, 0x48
    /* 31D6674 8006F0D8 09000224 */  addiu      $v0, $zero, 0x9
    /* 31D6678 8006F0DC 000062AC */  sw         $v0, 0x0($v1)
    /* 31D667C 8006F0E0 0600023C */  lui        $v0, (0x60000 >> 16)
    /* 31D6680 8006F0E4 0780013C */  lui        $at, %hi(D_8006A044)
    /* 31D6684 8006F0E8 44A020AC */  sw         $zero, %lo(D_8006A044)($at)
    /* 31D6688 8006F0EC 0780013C */  lui        $at, %hi(D_8006A128)
    /* 31D668C 8006F0F0 28A122AC */  sw         $v0, %lo(D_8006A128)($at)
    /* 31D6690 8006F0F4 886E000C */  jal        func_8001BA20
    /* 31D6694 8006F0F8 21280000 */   addu      $a1, $zero, $zero
    /* 31D6698 8006F0FC 0780013C */  lui        $at, %hi(D_8006A0A8)
    /* 31D669C 8006F100 A8A022AC */  sw         $v0, %lo(D_8006A0A8)($at)
    /* 31D66A0 8006F104 801E0224 */  addiu      $v0, $zero, 0x1E80
    /* 31D66A4 8006F108 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 31D66A8 8006F10C A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
    /* 31D66AC 8006F110 C2B6000C */  jal        func_8002DB08
    /* 31D66B0 8006F114 000C0424 */   addiu     $a0, $zero, 0xC00
    /* 31D66B4 8006F118 0780033C */  lui        $v1, %hi(D_8006A15C)
    /* 31D66B8 8006F11C 5CA1638C */  lw         $v1, %lo(D_8006A15C)($v1)
    /* 31D66BC 8006F120 01000224 */  addiu      $v0, $zero, 0x1
    /* 31D66C0 8006F124 0780013C */  lui        $at, %hi(D_8006A1AC)
    /* 31D66C4 8006F128 ACA122A0 */  sb         $v0, %lo(D_8006A1AC)($at)
    /* 31D66C8 8006F12C 0B006014 */  bnez       $v1, .Llevel_44_8006F15C
    /* 31D66CC 8006F130 06000224 */   addiu     $v0, $zero, 0x6
    /* 31D66D0 8006F134 0780023C */  lui        $v0, %hi(D_8006A1EC)
    /* 31D66D4 8006F138 ECA1428C */  lw         $v0, %lo(D_8006A1EC)($v0)
    /* 31D66D8 8006F13C 00000000 */  nop
    /* 31D66DC 8006F140 06004014 */  bnez       $v0, .Llevel_44_8006F15C
    /* 31D66E0 8006F144 06000224 */   addiu     $v0, $zero, 0x6
    /* 31D66E4 8006F148 0780033C */  lui        $v1, %hi(D_8006A1F0)
    /* 31D66E8 8006F14C F0A1638C */  lw         $v1, %lo(D_8006A1F0)($v1)
    /* 31D66EC 8006F150 00000000 */  nop
    /* 31D66F0 8006F154 09006210 */  beq        $v1, $v0, .Llevel_44_8006F17C
    /* 31D66F4 8006F158 00000000 */   nop
  .Llevel_44_8006F15C:
    /* 31D66F8 8006F15C 0780013C */  lui        $at, %hi(D_8006A15C)
    /* 31D66FC 8006F160 5CA120AC */  sw         $zero, %lo(D_8006A15C)($at)
    /* 31D6700 8006F164 0780013C */  lui        $at, %hi(D_8006A1EC)
    /* 31D6704 8006F168 ECA120AC */  sw         $zero, %lo(D_8006A1EC)($at)
    /* 31D6708 8006F16C 0780013C */  lui        $at, %hi(D_8006A1F0)
    /* 31D670C 8006F170 F0A122AC */  sw         $v0, %lo(D_8006A1F0)($at)
    /* 31D6710 8006F174 85C2000C */  jal        func_80030A14
    /* 31D6714 8006F178 00000000 */   nop
  .Llevel_44_8006F17C:
    /* 31D6718 8006F17C 1400BF8F */  lw         $ra, 0x14($sp)
    /* 31D671C 8006F180 1000B08F */  lw         $s0, 0x10($sp)
    /* 31D6720 8006F184 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 31D6724 8006F188 0800E003 */  jr         $ra
    /* 31D6728 8006F18C 00000000 */   nop
endlabel func_level_44_8006ECB8
