.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_44_8006D268

dlabel jtbl_level_44_8006D268
    /* 31D4804 8006D268 04DD0680 */ .word .Llevel_44_8006DD04
    /* 31D4808 8006D26C B4DC0680 */ .word .Llevel_44_8006DCB4
    /* 31D480C 8006D270 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4810 8006D274 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4814 8006D278 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4818 8006D27C 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D481C 8006D280 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4820 8006D284 F8E00680 */ .word .Llevel_44_8006E0F8
    /* 31D4824 8006D288 38E20680 */ .word .Llevel_44_8006E238
    /* 31D4828 8006D28C 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D482C 8006D290 A8E20680 */ .word .Llevel_44_8006E2A8
    /* 31D4830 8006D294 18E00680 */ .word .Llevel_44_8006E018
    /* 31D4834 8006D298 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4838 8006D29C 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D483C 8006D2A0 08E50680 */ .word .Llevel_44_8006E508
    /* 31D4840 8006D2A4 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4844 8006D2A8 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4848 8006D2AC 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D484C 8006D2B0 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4850 8006D2B4 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4854 8006D2B8 B4DC0680 */ .word .Llevel_44_8006DCB4
    /* 31D4858 8006D2BC 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D485C 8006D2C0 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4860 8006D2C4 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4864 8006D2C8 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4868 8006D2CC 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D486C 8006D2D0 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4870 8006D2D4 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4874 8006D2D8 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4878 8006D2DC 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D487C 8006D2E0 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4880 8006D2E4 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4884 8006D2E8 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4888 8006D2EC 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D488C 8006D2F0 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4890 8006D2F4 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4894 8006D2F8 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D4898 8006D2FC 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D489C 8006D300 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D48A0 8006D304 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D48A4 8006D308 08E50680 */ .word .Llevel_44_8006E508
    /* 31D48A8 8006D30C 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D48AC 8006D310 8CE80680 */ .word .Llevel_44_8006E88C
    /* 31D48B0 8006D314 9CE60680 */ .word .Llevel_44_8006E69C
enddlabel jtbl_level_44_8006D268


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_44_8006DC48, 0xC64

glabel func_level_44_8006DC48
    /* 31D51E4 8006DC48 00110400 */  sll        $v0, $a0, 4
    /* 31D51E8 8006DC4C 0780033C */  lui        $v1, %hi(D_800683B0)
    /* 31D51EC 8006DC50 B0836324 */  addiu      $v1, $v1, %lo(D_800683B0)
    /* 31D51F0 8006DC54 21104300 */  addu       $v0, $v0, $v1
    /* 31D51F4 8006DC58 0680013C */  lui        $at, %hi(D_80066F38)
    /* 31D51F8 8006DC5C 386F22AC */  sw         $v0, %lo(D_80066F38)($at)
    /* 31D51FC 8006DC60 0780023C */  lui        $v0, %hi(D_8006A04C)
    /* 31D5200 8006DC64 4CA0428C */  lw         $v0, %lo(D_8006A04C)($v0)
    /* 31D5204 8006DC68 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 31D5208 8006DC6C 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 31D520C 8006DC70 60FFBD27 */  addiu      $sp, $sp, -0xA0
    /* 31D5210 8006DC74 9800BFAF */  sw         $ra, 0x98($sp)
    /* 31D5214 8006DC78 9400B3AF */  sw         $s3, 0x94($sp)
    /* 31D5218 8006DC7C 9000B2AF */  sw         $s2, 0x90($sp)
    /* 31D521C 8006DC80 8C00B1AF */  sw         $s1, 0x8C($sp)
    /* 31D5220 8006DC84 21904400 */  addu       $s2, $v0, $a0
    /* 31D5224 8006DC88 EEFF6324 */  addiu      $v1, $v1, -0x12
    /* 31D5228 8006DC8C 2C00622C */  sltiu      $v0, $v1, 0x2C
    /* 31D522C 8006DC90 FE024010 */  beqz       $v0, .Llevel_44_8006E88C
    /* 31D5230 8006DC94 8800B0AF */   sw        $s0, 0x88($sp)
    /* 31D5234 8006DC98 80100300 */  sll        $v0, $v1, 2
    /* 31D5238 8006DC9C 0780013C */  lui        $at, %hi(jtbl_level_44_8006D268)
    /* 31D523C 8006DCA0 21082200 */  addu       $at, $at, $v0
    /* 31D5240 8006DCA4 68D2228C */  lw         $v0, %lo(jtbl_level_44_8006D268)($at)
    /* 31D5244 8006DCA8 00000000 */  nop
    /* 31D5248 8006DCAC 08004000 */  jr         $v0
    /* 31D524C 8006DCB0 00000000 */   nop
  .Llevel_44_8006DCB4:
    /* 31D5250 8006DCB4 0780103C */  lui        $s0, %hi(D_8006A078)
    /* 31D5254 8006DCB8 78A01026 */  addiu      $s0, $s0, %lo(D_8006A078)
    /* 31D5258 8006DCBC 686F000C */  jal        func_8001BDA0
    /* 31D525C 8006DCC0 21200002 */   addu      $a0, $s0, $zero
    /* 31D5260 8006DCC4 686F000C */  jal        func_8001BDA0
    /* 31D5264 8006DCC8 0C000426 */   addiu     $a0, $s0, 0xC
    /* 31D5268 8006DCCC 0680033C */  lui        $v1, %hi(D_80067ED0)
    /* 31D526C 8006DCD0 D07E638C */  lw         $v1, %lo(D_80067ED0)($v1)
    /* 31D5270 8006DCD4 07000224 */  addiu      $v0, $zero, 0x7
    /* 31D5274 8006DCD8 EC026210 */  beq        $v1, $v0, .Llevel_44_8006E88C
    /* 31D5278 8006DCDC 00000000 */   nop
    /* 31D527C 8006DCE0 DBAC000C */  jal        func_8002B36C
    /* 31D5280 8006DCE4 00120424 */   addiu     $a0, $zero, 0x1200
    /* 31D5284 8006DCE8 1AAF000C */  jal        func_8002BC68
    /* 31D5288 8006DCEC 00000000 */   nop
    /* 31D528C 8006DCF0 5A000424 */  addiu      $a0, $zero, 0x5A
    /* 31D5290 8006DCF4 C9AE000C */  jal        func_8002BB24
    /* 31D5294 8006DCF8 10000524 */   addiu     $a1, $zero, 0x10
    /* 31D5298 8006DCFC 23BA0108 */  j          .Llevel_44_8006E88C
    /* 31D529C 8006DD00 00000000 */   nop
  .Llevel_44_8006DD04:
    /* 31D52A0 8006DD04 0780113C */  lui        $s1, %hi(D_80069FF8)
    /* 31D52A4 8006DD08 F89F3126 */  addiu      $s1, $s1, %lo(D_80069FF8)
    /* 31D52A8 8006DD0C 0000238E */  lw         $v1, 0x0($s1)
    /* 31D52AC 8006DD10 4401228E */  lw         $v0, 0x144($s1)
    /* 31D52B0 8006DD14 00000000 */  nop
    /* 31D52B4 8006DD18 23206200 */  subu       $a0, $v1, $v0
    /* 31D52B8 8006DD1C 00048228 */  slti       $v0, $a0, 0x400
    /* 31D52BC 8006DD20 28004010 */  beqz       $v0, .Llevel_44_8006DDC4
    /* 31D52C0 8006DD24 00000000 */   nop
    /* 31D52C4 8006DD28 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 31D52C8 8006DD2C 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 31D52CC 8006DD30 00000000 */  nop
    /* 31D52D0 8006DD34 80004224 */  addiu      $v0, $v0, 0x80
    /* 31D52D4 8006DD38 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D52D8 8006DD3C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 31D52DC 8006DD40 C1124228 */  slti       $v0, $v0, 0x12C1
    /* 31D52E0 8006DD44 04004014 */  bnez       $v0, .Llevel_44_8006DD58
    /* 31D52E4 8006DD48 18008400 */   mult      $a0, $a0
    /* 31D52E8 8006DD4C C0120224 */  addiu      $v0, $zero, 0x12C0
    /* 31D52EC 8006DD50 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D52F0 8006DD54 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_44_8006DD58:
    /* 31D52F4 8006DD58 1000A427 */  addiu      $a0, $sp, 0x10
    /* 31D52F8 8006DD5C 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 31D52FC 8006DD60 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 31D5300 8006DD64 0780033C */  lui        $v1, %hi(D_8006A140)
    /* 31D5304 8006DD68 40A1638C */  lw         $v1, %lo(D_8006A140)($v1)
    /* 31D5308 8006DD6C 12480000 */  mflo       $t1
    /* 31D530C 8006DD70 C3120900 */  sra        $v0, $t1, 11
    /* 31D5310 8006DD74 21804300 */  addu       $s0, $v0, $v1
    /* 31D5314 8006DD78 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 31D5318 8006DD7C 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 31D531C 8006DD80 6C6F000C */  jal        func_8001BDB0
    /* 31D5320 8006DD84 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 31D5324 8006DD88 1000A427 */  addiu      $a0, $sp, 0x10
    /* 31D5328 8006DD8C 21288000 */  addu       $a1, $a0, $zero
    /* 31D532C 8006DD90 806F000C */  jal        func_8001BE00
    /* 31D5330 8006DD94 F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 31D5334 8006DD98 1000A427 */  addiu      $a0, $sp, 0x10
    /* 31D5338 8006DD9C 21280000 */  addu       $a1, $zero, $zero
    /* 31D533C 8006DDA0 886E000C */  jal        func_8001BA20
    /* 31D5340 8006DDA4 1800A0AF */   sw        $zero, 0x18($sp)
    /* 31D5344 8006DDA8 21404000 */  addu       $t0, $v0, $zero
    /* 31D5348 8006DDAC 01040229 */  slti       $v0, $t0, 0x401
    /* 31D534C 8006DDB0 91004014 */  bnez       $v0, .Llevel_44_8006DFF8
    /* 31D5350 8006DDB4 1000A427 */   addiu     $a0, $sp, 0x10
    /* 31D5354 8006DDB8 21280001 */  addu       $a1, $t0, $zero
    /* 31D5358 8006DDBC FCB70108 */  j          .Llevel_44_8006DFF0
    /* 31D535C 8006DDC0 00040624 */   addiu     $a2, $zero, 0x400
  .Llevel_44_8006DDC4:
    /* 31D5360 8006DDC4 0780053C */  lui        $a1, %hi(D_8006A144)
    /* 31D5364 8006DDC8 44A1A58C */  lw         $a1, %lo(D_8006A144)($a1)
    /* 31D5368 8006DDCC 00000000 */  nop
    /* 31D536C 8006DDD0 23106500 */  subu       $v0, $v1, $a1
    /* 31D5370 8006DDD4 00FC4228 */  slti       $v0, $v0, -0x400
    /* 31D5374 8006DDD8 49004010 */  beqz       $v0, .Llevel_44_8006DF00
    /* 31D5378 8006DDDC 2340A300 */   subu      $t0, $a1, $v1
    /* 31D537C 8006DDE0 0780023C */  lui        $v0, %hi(D_8006A044)
    /* 31D5380 8006DDE4 44A0428C */  lw         $v0, %lo(D_8006A044)($v0)
    /* 31D5384 8006DDE8 00000000 */  nop
    /* 31D5388 8006DDEC 08004014 */  bnez       $v0, .Llevel_44_8006DE10
    /* 31D538C 8006DDF0 01000324 */   addiu     $v1, $zero, 0x1
    /* 31D5390 8006DDF4 0780023C */  lui        $v0, %hi(D_8006A140)
    /* 31D5394 8006DDF8 40A1428C */  lw         $v0, %lo(D_8006A140)($v0)
    /* 31D5398 8006DDFC 0780013C */  lui        $at, %hi(D_8006A044)
    /* 31D539C 8006DE00 44A023AC */  sw         $v1, %lo(D_8006A044)($at)
    /* 31D53A0 8006DE04 00024224 */  addiu      $v0, $v0, 0x200
    /* 31D53A4 8006DE08 0780013C */  lui        $at, %hi(D_8006A140)
    /* 31D53A8 8006DE0C 40A122AC */  sw         $v0, %lo(D_8006A140)($at)
  .Llevel_44_8006DE10:
    /* 31D53AC 8006DE10 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 31D53B0 8006DE14 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 31D53B4 8006DE18 00000000 */  nop
    /* 31D53B8 8006DE1C 80004224 */  addiu      $v0, $v0, 0x80
    /* 31D53BC 8006DE20 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D53C0 8006DE24 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 31D53C4 8006DE28 C1124228 */  slti       $v0, $v0, 0x12C1
    /* 31D53C8 8006DE2C 03004014 */  bnez       $v0, .Llevel_44_8006DE3C
    /* 31D53CC 8006DE30 C0120224 */   addiu     $v0, $zero, 0x12C0
    /* 31D53D0 8006DE34 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D53D4 8006DE38 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_44_8006DE3C:
    /* 31D53D8 8006DE3C 0780023C */  lui        $v0, %hi(D_8006A148)
    /* 31D53DC 8006DE40 48A1428C */  lw         $v0, %lo(D_8006A148)($v0)
    /* 31D53E0 8006DE44 00FC8824 */  addiu      $t0, $a0, -0x400
    /* 31D53E4 8006DE48 18004800 */  mult       $v0, $t0
    /* 31D53E8 8006DE4C 12180000 */  mflo       $v1
    /* 31D53EC 8006DE50 0780023C */  lui        $v0, %hi(D_8006A14C)
    /* 31D53F0 8006DE54 4CA1428C */  lw         $v0, %lo(D_8006A14C)($v0)
    /* 31D53F4 8006DE58 00000000 */  nop
    /* 31D53F8 8006DE5C 1A006200 */  div        $zero, $v1, $v0
    /* 31D53FC 8006DE60 02004014 */  bnez       $v0, .Llevel_44_8006DE6C
    /* 31D5400 8006DE64 00000000 */   nop
    /* 31D5404 8006DE68 0D000700 */  break      7
  .Llevel_44_8006DE6C:
    /* 31D5408 8006DE6C FFFF0124 */  addiu      $at, $zero, -0x1
    /* 31D540C 8006DE70 04004114 */  bne        $v0, $at, .Llevel_44_8006DE84
    /* 31D5410 8006DE74 0080013C */   lui       $at, (0x80000000 >> 16)
    /* 31D5414 8006DE78 02006114 */  bne        $v1, $at, .Llevel_44_8006DE84
    /* 31D5418 8006DE7C 00000000 */   nop
    /* 31D541C 8006DE80 0D000600 */  break      6
  .Llevel_44_8006DE84:
    /* 31D5420 8006DE84 12100000 */  mflo       $v0
    /* 31D5424 8006DE88 1000A427 */  addiu      $a0, $sp, 0x10
    /* 31D5428 8006DE8C 0780053C */  lui        $a1, %hi(D_8006A208)
    /* 31D542C 8006DE90 08A2A58C */  lw         $a1, %lo(D_8006A208)($a1)
    /* 31D5430 8006DE94 0780033C */  lui        $v1, %hi(D_8006A140)
    /* 31D5434 8006DE98 40A1638C */  lw         $v1, %lo(D_8006A140)($v1)
    /* 31D5438 8006DE9C 00000000 */  nop
    /* 31D543C 8006DEA0 21806200 */  addu       $s0, $v1, $v0
    /* 31D5440 8006DEA4 80120800 */  sll        $v0, $t0, 10
    /* 31D5444 8006DEA8 83120200 */  sra        $v0, $v0, 10
    /* 31D5448 8006DEAC 21100202 */  addu       $v0, $s0, $v0
    /* 31D544C 8006DEB0 FF0F5030 */  andi       $s0, $v0, 0xFFF
    /* 31D5450 8006DEB4 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 31D5454 8006DEB8 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 31D5458 8006DEBC 6C6F000C */  jal        func_8001BDB0
    /* 31D545C 8006DEC0 0C00A524 */   addiu     $a1, $a1, 0xC
    /* 31D5460 8006DEC4 1000A427 */  addiu      $a0, $sp, 0x10
    /* 31D5464 8006DEC8 21288000 */  addu       $a1, $a0, $zero
    /* 31D5468 8006DECC 806F000C */  jal        func_8001BE00
    /* 31D546C 8006DED0 F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 31D5470 8006DED4 1000A427 */  addiu      $a0, $sp, 0x10
    /* 31D5474 8006DED8 21280000 */  addu       $a1, $zero, $zero
    /* 31D5478 8006DEDC 886E000C */  jal        func_8001BA20
    /* 31D547C 8006DEE0 1800A0AF */   sw        $zero, 0x18($sp)
    /* 31D5480 8006DEE4 21404000 */  addu       $t0, $v0, $zero
    /* 31D5484 8006DEE8 01040229 */  slti       $v0, $t0, 0x401
    /* 31D5488 8006DEEC 42004014 */  bnez       $v0, .Llevel_44_8006DFF8
    /* 31D548C 8006DEF0 1000A427 */   addiu     $a0, $sp, 0x10
    /* 31D5490 8006DEF4 21280001 */  addu       $a1, $t0, $zero
    /* 31D5494 8006DEF8 FCB70108 */  j          .Llevel_44_8006DFF0
    /* 31D5498 8006DEFC 00040624 */   addiu     $a2, $zero, 0x400
  .Llevel_44_8006DF00:
    /* 31D549C 8006DF00 80180800 */  sll        $v1, $t0, 2
    /* 31D54A0 8006DF04 21186800 */  addu       $v1, $v1, $t0
    /* 31D54A4 8006DF08 00110300 */  sll        $v0, $v1, 4
    /* 31D54A8 8006DF0C 23104300 */  subu       $v0, $v0, $v1
    /* 31D54AC 8006DF10 80110200 */  sll        $v0, $v0, 6
    /* 31D54B0 8006DF14 0780063C */  lui        $a2, %hi(D_8006A208)
    /* 31D54B4 8006DF18 08A2C68C */  lw         $a2, %lo(D_8006A208)($a2)
    /* 31D54B8 8006DF1C 83120200 */  sra        $v0, $v0, 10
    /* 31D54BC 8006DF20 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D54C0 8006DF24 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 31D54C4 8006DF28 4600C790 */  lbu        $a3, 0x46($a2)
    /* 31D54C8 8006DF2C 0780033C */  lui        $v1, %hi(D_8006A150)
    /* 31D54CC 8006DF30 50A1638C */  lw         $v1, %lo(D_8006A150)($v1)
    /* 31D54D0 8006DF34 40100700 */  sll        $v0, $a3, 1
    /* 31D54D4 8006DF38 0680013C */  lui        $at, %hi(D_80061C58)
    /* 31D54D8 8006DF3C 21082200 */  addu       $at, $at, $v0
    /* 31D54DC 8006DF40 581C2284 */  lh         $v0, %lo(D_80061C58)($at)
    /* 31D54E0 8006DF44 00046324 */  addiu      $v1, $v1, 0x400
    /* 31D54E4 8006DF48 18006200 */  mult       $v1, $v0
    /* 31D54E8 8006DF4C 12500000 */  mflo       $t2
    /* 31D54EC 8006DF50 00000000 */  nop
    /* 31D54F0 8006DF54 00000000 */  nop
    /* 31D54F4 8006DF58 18000801 */  mult       $t0, $t0
    /* 31D54F8 8006DF5C 03130A00 */  sra        $v0, $t2, 12
    /* 31D54FC 8006DF60 1000A2AF */  sw         $v0, 0x10($sp)
    /* 31D5500 8006DF64 4600C290 */  lbu        $v0, 0x46($a2)
    /* 31D5504 8006DF68 00000000 */  nop
    /* 31D5508 8006DF6C 40100200 */  sll        $v0, $v0, 1
    /* 31D550C 8006DF70 12400000 */  mflo       $t0
    /* 31D5510 8006DF74 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 31D5514 8006DF78 21082200 */  addu       $at, $at, $v0
    /* 31D5518 8006DF7C D81B2284 */  lh         $v0, %lo(D_80061BD8)($at)
    /* 31D551C 8006DF80 00000000 */  nop
    /* 31D5520 8006DF84 18006200 */  mult       $v1, $v0
    /* 31D5524 8006DF88 1000A427 */  addiu      $a0, $sp, 0x10
    /* 31D5528 8006DF8C 21288000 */  addu       $a1, $a0, $zero
    /* 31D552C 8006DF90 00390700 */  sll        $a3, $a3, 4
    /* 31D5530 8006DF94 0C00C624 */  addiu      $a2, $a2, 0xC
    /* 31D5534 8006DF98 C3120800 */  sra        $v0, $t0, 11
    /* 31D5538 8006DF9C 2380E200 */  subu       $s0, $a3, $v0
    /* 31D553C 8006DFA0 12180000 */  mflo       $v1
    /* 31D5540 8006DFA4 03130300 */  sra        $v0, $v1, 12
    /* 31D5544 8006DFA8 736F000C */  jal        func_8001BDCC
    /* 31D5548 8006DFAC 1400A2AF */   sw        $v0, 0x14($sp)
    /* 31D554C 8006DFB0 1000A427 */  addiu      $a0, $sp, 0x10
    /* 31D5550 8006DFB4 21288000 */  addu       $a1, $a0, $zero
    /* 31D5554 8006DFB8 0780013C */  lui        $at, %hi(D_8006A05C)
    /* 31D5558 8006DFBC 5CA030AC */  sw         $s0, %lo(D_8006A05C)($at)
    /* 31D555C 8006DFC0 806F000C */  jal        func_8001BE00
    /* 31D5560 8006DFC4 F8FF2626 */   addiu     $a2, $s1, -0x8
    /* 31D5564 8006DFC8 1000A427 */  addiu      $a0, $sp, 0x10
    /* 31D5568 8006DFCC 21280000 */  addu       $a1, $zero, $zero
    /* 31D556C 8006DFD0 886E000C */  jal        func_8001BA20
    /* 31D5570 8006DFD4 1800A0AF */   sw        $zero, 0x18($sp)
    /* 31D5574 8006DFD8 21404000 */  addu       $t0, $v0, $zero
    /* 31D5578 8006DFDC 01080229 */  slti       $v0, $t0, 0x801
    /* 31D557C 8006DFE0 05004014 */  bnez       $v0, .Llevel_44_8006DFF8
    /* 31D5580 8006DFE4 1000A427 */   addiu     $a0, $sp, 0x10
    /* 31D5584 8006DFE8 21280001 */  addu       $a1, $t0, $zero
    /* 31D5588 8006DFEC 00080624 */  addiu      $a2, $zero, 0x800
  .Llevel_44_8006DFF0:
    /* 31D558C 8006DFF0 316F000C */  jal        func_8001BCC4
    /* 31D5590 8006DFF4 00000000 */   nop
  .Llevel_44_8006DFF8:
    /* 31D5594 8006DFF8 1000A28F */  lw         $v0, 0x10($sp)
    /* 31D5598 8006DFFC 1400A38F */  lw         $v1, 0x14($sp)
    /* 31D559C 8006E000 0780013C */  lui        $at, %hi(D_8006A084)
    /* 31D55A0 8006E004 84A022AC */  sw         $v0, %lo(D_8006A084)($at)
    /* 31D55A4 8006E008 0780013C */  lui        $at, %hi(D_8006A088)
    /* 31D55A8 8006E00C 88A023AC */  sw         $v1, %lo(D_8006A088)($at)
    /* 31D55AC 8006E010 23BA0108 */  j          .Llevel_44_8006E88C
    /* 31D55B0 8006E014 00000000 */   nop
  .Llevel_44_8006E018:
    /* 31D55B4 8006E018 2000B027 */  addiu      $s0, $sp, 0x20
    /* 31D55B8 8006E01C 686F000C */  jal        func_8001BDA0
    /* 31D55BC 8006E020 21200002 */   addu      $a0, $s0, $zero
    /* 31D55C0 8006E024 21200002 */  addu       $a0, $s0, $zero
    /* 31D55C4 8006E028 21280002 */  addu       $a1, $s0, $zero
    /* 31D55C8 8006E02C 0780113C */  lui        $s1, %hi(D_8006A084)
    /* 31D55CC 8006E030 84A03126 */  addiu      $s1, $s1, %lo(D_8006A084)
    /* 31D55D0 8006E034 806F000C */  jal        func_8001BE00
    /* 31D55D4 8006E038 21302002 */   addu      $a2, $s1, $zero
    /* 31D55D8 8006E03C 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 31D55DC 8006E040 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 31D55E0 8006E044 00000000 */  nop
    /* 31D55E4 8006E048 11004010 */  beqz       $v0, .Llevel_44_8006E090
    /* 31D55E8 8006E04C 21200002 */   addu      $a0, $s0, $zero
    /* 31D55EC 8006E050 2800A0AF */  sw         $zero, 0x28($sp)
    /* 31D55F0 8006E054 886E000C */  jal        func_8001BA20
    /* 31D55F4 8006E058 21280000 */   addu      $a1, $zero, $zero
    /* 31D55F8 8006E05C 21284000 */  addu       $a1, $v0, $zero
    /* 31D55FC 8006E060 4100A228 */  slti       $v0, $a1, 0x41
    /* 31D5600 8006E064 05004014 */  bnez       $v0, .Llevel_44_8006E07C
    /* 31D5604 8006E068 40FF0224 */   addiu     $v0, $zero, -0xC0
    /* 31D5608 8006E06C 21200002 */  addu       $a0, $s0, $zero
    /* 31D560C 8006E070 316F000C */  jal        func_8001BCC4
    /* 31D5610 8006E074 40000624 */   addiu     $a2, $zero, 0x40
    /* 31D5614 8006E078 40FF0224 */  addiu      $v0, $zero, -0xC0
  .Llevel_44_8006E07C:
    /* 31D5618 8006E07C 2800A2AF */  sw         $v0, 0x28($sp)
    /* 31D561C 8006E080 F4FF2426 */  addiu      $a0, $s1, -0xC
    /* 31D5620 8006E084 21282002 */  addu       $a1, $s1, $zero
    /* 31D5624 8006E088 34B80108 */  j          .Llevel_44_8006E0D0
    /* 31D5628 8006E08C 21300002 */   addu      $a2, $s0, $zero
  .Llevel_44_8006E090:
    /* 31D562C 8006E090 886E000C */  jal        func_8001BA20
    /* 31D5630 8006E094 01000524 */   addiu     $a1, $zero, 0x1
    /* 31D5634 8006E098 21284000 */  addu       $a1, $v0, $zero
    /* 31D5638 8006E09C 0101A228 */  slti       $v0, $a1, 0x101
    /* 31D563C 8006E0A0 05004014 */  bnez       $v0, .Llevel_44_8006E0B8
    /* 31D5640 8006E0A4 21202002 */   addu      $a0, $s1, $zero
    /* 31D5644 8006E0A8 21200002 */  addu       $a0, $s0, $zero
    /* 31D5648 8006E0AC 316F000C */  jal        func_8001BCC4
    /* 31D564C 8006E0B0 00010624 */   addiu     $a2, $zero, 0x100
    /* 31D5650 8006E0B4 21202002 */  addu       $a0, $s1, $zero
  .Llevel_44_8006E0B8:
    /* 31D5654 8006E0B8 21282002 */  addu       $a1, $s1, $zero
    /* 31D5658 8006E0BC 736F000C */  jal        func_8001BDCC
    /* 31D565C 8006E0C0 21300002 */   addu      $a2, $s0, $zero
    /* 31D5660 8006E0C4 F4FF2426 */  addiu      $a0, $s1, -0xC
    /* 31D5664 8006E0C8 21282002 */  addu       $a1, $s1, $zero
    /* 31D5668 8006E0CC 5C00A624 */  addiu      $a2, $a1, 0x5C
  .Llevel_44_8006E0D0:
    /* 31D566C 8006E0D0 736F000C */  jal        func_8001BDCC
    /* 31D5670 8006E0D4 00000000 */   nop
    /* 31D5674 8006E0D8 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 31D5678 8006E0DC 84A08424 */  addiu      $a0, $a0, %lo(D_8006A084)
    /* 31D567C 8006E0E0 6C6F000C */  jal        func_8001BDB0
    /* 31D5680 8006E0E4 21288000 */   addu      $a1, $a0, $zero
    /* 31D5684 8006E0E8 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 31D5688 8006E0EC 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 31D568C 8006E0F0 88B80108 */  j          .Llevel_44_8006E220
    /* 31D5690 8006E0F4 00DD4228 */   slti      $v0, $v0, -0x2300
  .Llevel_44_8006E0F8:
    /* 31D5694 8006E0F8 3000A427 */  addiu      $a0, $sp, 0x30
    /* 31D5698 8006E0FC 39AD000C */  jal        func_8002B4E4
    /* 31D569C 8006E100 01000524 */   addiu     $a1, $zero, 0x1
    /* 31D56A0 8006E104 3000A28F */  lw         $v0, 0x30($sp)
    /* 31D56A4 8006E108 0780043C */  lui        $a0, %hi(D_8006A0A0)
    /* 31D56A8 8006E10C A0A08424 */  addiu      $a0, $a0, %lo(D_8006A0A0)
    /* 31D56AC 8006E110 43100200 */  sra        $v0, $v0, 1
    /* 31D56B0 8006E114 000082AC */  sw         $v0, 0x0($a0)
    /* 31D56B4 8006E118 E7FF4228 */  slti       $v0, $v0, -0x19
    /* 31D56B8 8006E11C 02004010 */  beqz       $v0, .Llevel_44_8006E128
    /* 31D56BC 8006E120 E7FF0224 */   addiu     $v0, $zero, -0x19
    /* 31D56C0 8006E124 000082AC */  sw         $v0, 0x0($a0)
  .Llevel_44_8006E128:
    /* 31D56C4 8006E128 0000828C */  lw         $v0, 0x0($a0)
    /* 31D56C8 8006E12C 00000000 */  nop
    /* 31D56CC 8006E130 1A004228 */  slti       $v0, $v0, 0x1A
    /* 31D56D0 8006E134 02004014 */  bnez       $v0, .Llevel_44_8006E140
    /* 31D56D4 8006E138 19000224 */   addiu     $v0, $zero, 0x19
    /* 31D56D8 8006E13C 000082AC */  sw         $v0, 0x0($a0)
  .Llevel_44_8006E140:
    /* 31D56DC 8006E140 0000848C */  lw         $a0, 0x0($a0)
    /* 31D56E0 8006E144 68AE000C */  jal        func_8002B9A0
    /* 31D56E4 8006E148 00000000 */   nop
    /* 31D56E8 8006E14C 40020424 */  addiu      $a0, $zero, 0x240
    /* 31D56EC 8006E150 5CAF000C */  jal        func_8002BD70
    /* 31D56F0 8006E154 80010524 */   addiu     $a1, $zero, 0x180
    /* 31D56F4 8006E158 0780043C */  lui        $a0, %hi(D_8006A05C)
    /* 31D56F8 8006E15C 5CA0848C */  lw         $a0, %lo(D_8006A05C)($a0)
    /* 31D56FC 8006E160 996D000C */  jal        func_8001B664
    /* 31D5700 8006E164 00000000 */   nop
    /* 31D5704 8006E168 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 31D5708 8006E16C A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 31D570C 8006E170 00000000 */  nop
    /* 31D5710 8006E174 18006200 */  mult       $v1, $v0
    /* 31D5714 8006E178 0780043C */  lui        $a0, %hi(D_8006A05C)
    /* 31D5718 8006E17C 5CA0848C */  lw         $a0, %lo(D_8006A05C)($a0)
    /* 31D571C 8006E180 12480000 */  mflo       $t1
    /* 31D5720 8006E184 03130900 */  sra        $v0, $t1, 12
    /* 31D5724 8006E188 0780013C */  lui        $at, %hi(D_8006A078)
    /* 31D5728 8006E18C 78A022AC */  sw         $v0, %lo(D_8006A078)($at)
    /* 31D572C 8006E190 876D000C */  jal        func_8001B61C
    /* 31D5730 8006E194 00000000 */   nop
    /* 31D5734 8006E198 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 31D5738 8006E19C A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 31D573C 8006E1A0 00000000 */  nop
    /* 31D5740 8006E1A4 18006200 */  mult       $v1, $v0
    /* 31D5744 8006E1A8 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 31D5748 8006E1AC 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 31D574C 8006E1B0 0780013C */  lui        $at, %hi(D_8006A080)
    /* 31D5750 8006E1B4 80A022AC */  sw         $v0, %lo(D_8006A080)($at)
    /* 31D5754 8006E1B8 12480000 */  mflo       $t1
    /* 31D5758 8006E1BC 03130900 */  sra        $v0, $t1, 12
    /* 31D575C 8006E1C0 0780013C */  lui        $at, %hi(D_8006A07C)
    /* 31D5760 8006E1C4 7CA022AC */  sw         $v0, %lo(D_8006A07C)($at)
    /* 31D5764 8006E1C8 0EB0000C */  jal        func_8002C038
    /* 31D5768 8006E1CC 00000000 */   nop
    /* 31D576C 8006E1D0 0780023C */  lui        $v0, %hi(D_8006A13C)
    /* 31D5770 8006E1D4 3CA1428C */  lw         $v0, %lo(D_8006A13C)($v0)
    /* 31D5774 8006E1D8 00000000 */  nop
    /* 31D5778 8006E1DC 0C004224 */  addiu      $v0, $v0, 0xC
    /* 31D577C 8006E1E0 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 31D5780 8006E1E4 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
    /* 31D5784 8006E1E8 C1004228 */  slti       $v0, $v0, 0xC1
    /* 31D5788 8006E1EC 03004014 */  bnez       $v0, .Llevel_44_8006E1FC
    /* 31D578C 8006E1F0 C0000224 */   addiu     $v0, $zero, 0xC0
    /* 31D5790 8006E1F4 0780013C */  lui        $at, %hi(D_8006A13C)
    /* 31D5794 8006E1F8 3CA122AC */  sw         $v0, %lo(D_8006A13C)($at)
  .Llevel_44_8006E1FC:
    /* 31D5798 8006E1FC 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 31D579C 8006E200 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 31D57A0 8006E204 0780033C */  lui        $v1, %hi(D_8006A13C)
    /* 31D57A4 8006E208 3CA1638C */  lw         $v1, %lo(D_8006A13C)($v1)
    /* 31D57A8 8006E20C 00000000 */  nop
    /* 31D57AC 8006E210 23104300 */  subu       $v0, $v0, $v1
    /* 31D57B0 8006E214 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D57B4 8006E218 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 31D57B8 8006E21C 00DD4228 */  slti       $v0, $v0, -0x2300
  .Llevel_44_8006E220:
    /* 31D57BC 8006E220 9A014010 */  beqz       $v0, .Llevel_44_8006E88C
    /* 31D57C0 8006E224 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 31D57C4 8006E228 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D57C8 8006E22C 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 31D57CC 8006E230 23BA0108 */  j          .Llevel_44_8006E88C
    /* 31D57D0 8006E234 00000000 */   nop
  .Llevel_44_8006E238:
    /* 31D57D4 8006E238 0780103C */  lui        $s0, %hi(D_8006A0B0)
    /* 31D57D8 8006E23C B0A01026 */  addiu      $s0, $s0, %lo(D_8006A0B0)
    /* 31D57DC 8006E240 0000028E */  lw         $v0, 0x0($s0)
    /* 31D57E0 8006E244 00000000 */  nop
    /* 31D57E4 8006E248 11004010 */  beqz       $v0, .Llevel_44_8006E290
    /* 31D57E8 8006E24C 00000000 */   nop
    /* 31D57EC 8006E250 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 31D57F0 8006E254 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 31D57F4 8006E258 00000000 */  nop
    /* 31D57F8 8006E25C 00FA4224 */  addiu      $v0, $v0, -0x600
    /* 31D57FC 8006E260 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D5800 8006E264 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 31D5804 8006E268 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 31D5808 8006E26C 03004010 */  beqz       $v0, .Llevel_44_8006E27C
    /* 31D580C 8006E270 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 31D5810 8006E274 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D5814 8006E278 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
  .Llevel_44_8006E27C:
    /* 31D5818 8006E27C C8FF0426 */  addiu      $a0, $s0, -0x38
    /* 31D581C 8006E280 6C6F000C */  jal        func_8001BDB0
    /* 31D5820 8006E284 D4FF0526 */   addiu     $a1, $s0, -0x2C
    /* 31D5824 8006E288 23BA0108 */  j          .Llevel_44_8006E88C
    /* 31D5828 8006E28C 00000000 */   nop
  .Llevel_44_8006E290:
    /* 31D582C 8006E290 686F000C */  jal        func_8001BDA0
    /* 31D5830 8006E294 C8FF0426 */   addiu     $a0, $s0, -0x38
    /* 31D5834 8006E298 686F000C */  jal        func_8001BDA0
    /* 31D5838 8006E29C D4FF0426 */   addiu     $a0, $s0, -0x2C
    /* 31D583C 8006E2A0 23BA0108 */  j          .Llevel_44_8006E88C
    /* 31D5840 8006E2A4 00000000 */   nop
  .Llevel_44_8006E2A8:
    /* 31D5844 8006E2A8 DBAC000C */  jal        func_8002B36C
    /* 31D5848 8006E2AC 800C0424 */   addiu     $a0, $zero, 0xC80
    /* 31D584C 8006E2B0 28000424 */  addiu      $a0, $zero, 0x28
    /* 31D5850 8006E2B4 C9AE000C */  jal        func_8002BB24
    /* 31D5854 8006E2B8 08000524 */   addiu     $a1, $zero, 0x8
    /* 31D5858 8006E2BC 40010424 */  addiu      $a0, $zero, 0x140
    /* 31D585C 8006E2C0 5CAF000C */  jal        func_8002BD70
    /* 31D5860 8006E2C4 C0000524 */   addiu     $a1, $zero, 0xC0
    /* 31D5864 8006E2C8 0780113C */  lui        $s1, %hi(D_8006A09C)
    /* 31D5868 8006E2CC 9CA03126 */  addiu      $s1, $s1, %lo(D_8006A09C)
    /* 31D586C 8006E2D0 0000248E */  lw         $a0, 0x0($s1)
    /* 31D5870 8006E2D4 996D000C */  jal        func_8001B664
    /* 31D5874 8006E2D8 E8FF3326 */   addiu     $s3, $s1, -0x18
    /* 31D5878 8006E2DC 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 31D587C 8006E2E0 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 31D5880 8006E2E4 00000000 */  nop
    /* 31D5884 8006E2E8 18006200 */  mult       $v1, $v0
    /* 31D5888 8006E2EC 0000248E */  lw         $a0, 0x0($s1)
    /* 31D588C 8006E2F0 12480000 */  mflo       $t1
    /* 31D5890 8006E2F4 03130900 */  sra        $v0, $t1, 12
    /* 31D5894 8006E2F8 876D000C */  jal        func_8001B61C
    /* 31D5898 8006E2FC 3800A2AF */   sw        $v0, 0x38($sp)
    /* 31D589C 8006E300 0780033C */  lui        $v1, %hi(D_8006A0A8)
    /* 31D58A0 8006E304 A8A0638C */  lw         $v1, %lo(D_8006A0A8)($v1)
    /* 31D58A4 8006E308 00000000 */  nop
    /* 31D58A8 8006E30C 18006200 */  mult       $v1, $v0
    /* 31D58AC 8006E310 3800B027 */  addiu      $s0, $sp, 0x38
    /* 31D58B0 8006E314 21200002 */  addu       $a0, $s0, $zero
    /* 31D58B4 8006E318 21280002 */  addu       $a1, $s0, $zero
    /* 31D58B8 8006E31C 21306002 */  addu       $a2, $s3, $zero
    /* 31D58BC 8006E320 12480000 */  mflo       $t1
    /* 31D58C0 8006E324 03130900 */  sra        $v0, $t1, 12
    /* 31D58C4 8006E328 806F000C */  jal        func_8001BE00
    /* 31D58C8 8006E32C 3C00A2AF */   sw        $v0, 0x3C($sp)
    /* 31D58CC 8006E330 21200002 */  addu       $a0, $s0, $zero
    /* 31D58D0 8006E334 21280000 */  addu       $a1, $zero, $zero
    /* 31D58D4 8006E338 886E000C */  jal        func_8001BA20
    /* 31D58D8 8006E33C 4000A0AF */   sw        $zero, 0x40($sp)
    /* 31D58DC 8006E340 21284000 */  addu       $a1, $v0, $zero
    /* 31D58E0 8006E344 8102A228 */  slti       $v0, $a1, 0x281
    /* 31D58E4 8006E348 05004014 */  bnez       $v0, .Llevel_44_8006E360
    /* 31D58E8 8006E34C DCFF2426 */   addiu     $a0, $s1, -0x24
    /* 31D58EC 8006E350 21200002 */  addu       $a0, $s0, $zero
    /* 31D58F0 8006E354 316F000C */  jal        func_8001BCC4
    /* 31D58F4 8006E358 80020624 */   addiu     $a2, $zero, 0x280
    /* 31D58F8 8006E35C DCFF2426 */  addiu      $a0, $s1, -0x24
  .Llevel_44_8006E360:
    /* 31D58FC 8006E360 21286002 */  addu       $a1, $s3, $zero
    /* 31D5900 8006E364 736F000C */  jal        func_8001BDCC
    /* 31D5904 8006E368 21300002 */   addu      $a2, $s0, $zero
    /* 31D5908 8006E36C 0EB0000C */  jal        func_8002C038
    /* 31D590C 8006E370 00000000 */   nop
    /* 31D5910 8006E374 0D00422A */  slti       $v0, $s2, 0xD
    /* 31D5914 8006E378 05004010 */  beqz       $v0, .Llevel_44_8006E390
    /* 31D5918 8006E37C 00000000 */   nop
    /* 31D591C 8006E380 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 31D5920 8006E384 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 31D5924 8006E388 E8B80108 */  j          .Llevel_44_8006E3A0
    /* 31D5928 8006E38C 17004224 */   addiu     $v0, $v0, 0x17
  .Llevel_44_8006E390:
    /* 31D592C 8006E390 0780023C */  lui        $v0, %hi(D_8006A08C)
    /* 31D5930 8006E394 8CA0428C */  lw         $v0, %lo(D_8006A08C)($v0)
    /* 31D5934 8006E398 00000000 */  nop
    /* 31D5938 8006E39C 40FF4224 */  addiu      $v0, $v0, -0xC0
  .Llevel_44_8006E3A0:
    /* 31D593C 8006E3A0 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D5940 8006E3A4 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 31D5944 8006E3A8 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 31D5948 8006E3AC FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 31D594C 8006E3B0 00000000 */  nop
    /* 31D5950 8006E3B4 35014010 */  beqz       $v0, .Llevel_44_8006E88C
    /* 31D5954 8006E3B8 21880000 */   addu      $s1, $zero, $zero
    /* 31D5958 8006E3BC 80101200 */  sll        $v0, $s2, 2
    /* 31D595C 8006E3C0 21985200 */  addu       $s3, $v0, $s2
    /* 31D5960 8006E3C4 0780123C */  lui        $s2, %hi(D_80069FFE)
    /* 31D5964 8006E3C8 FE9F5226 */  addiu      $s2, $s2, %lo(D_80069FFE)
    /* 31D5968 8006E3CC 5800B027 */  addiu      $s0, $sp, 0x58
  .Llevel_44_8006E3D0:
    /* 31D596C 8006E3D0 4B67010C */  jal        func_80059D2C
    /* 31D5970 8006E3D4 00000000 */   nop
    /* 31D5974 8006E3D8 FF004230 */  andi       $v0, $v0, 0xFF
    /* 31D5978 8006E3DC 2A106202 */  slt        $v0, $s3, $v0
    /* 31D597C 8006E3E0 43004010 */  beqz       $v0, .Llevel_44_8006E4F0
    /* 31D5980 8006E3E4 21200000 */   addu      $a0, $zero, $zero
    /* 31D5984 8006E3E8 63E2000C */  jal        func_8003898C
    /* 31D5988 8006E3EC 0C000524 */   addiu     $a1, $zero, 0xC
    /* 31D598C 8006E3F0 22004426 */  addiu      $a0, $s2, 0x22
    /* 31D5990 8006E3F4 00004392 */  lbu        $v1, 0x0($s2)
    /* 31D5994 8006E3F8 21280002 */  addu       $a1, $s0, $zero
    /* 31D5998 8006E3FC 80006324 */  addiu      $v1, $v1, 0x80
    /* 31D599C 8006E400 21186200 */  addu       $v1, $v1, $v0
    /* 31D59A0 8006E404 FF006330 */  andi       $v1, $v1, 0xFF
    /* 31D59A4 8006E408 40180300 */  sll        $v1, $v1, 1
    /* 31D59A8 8006E40C 0680013C */  lui        $at, %hi(D_80061C58)
    /* 31D59AC 8006E410 21082300 */  addu       $at, $at, $v1
    /* 31D59B0 8006E414 581C2784 */  lh         $a3, %lo(D_80061C58)($at)
    /* 31D59B4 8006E418 21300002 */  addu       $a2, $s0, $zero
    /* 31D59B8 8006E41C 80100700 */  sll        $v0, $a3, 2
    /* 31D59BC 8006E420 21104700 */  addu       $v0, $v0, $a3
    /* 31D59C0 8006E424 83120200 */  sra        $v0, $v0, 10
    /* 31D59C4 8006E428 4800A2AF */  sw         $v0, 0x48($sp)
    /* 31D59C8 8006E42C 0680013C */  lui        $at, %hi(D_80061BD8)
    /* 31D59CC 8006E430 21082300 */  addu       $at, $at, $v1
    /* 31D59D0 8006E434 D81B2384 */  lh         $v1, %lo(D_80061BD8)($at)
    /* 31D59D4 8006E438 0E000224 */  addiu      $v0, $zero, 0xE
    /* 31D59D8 8006E43C 5000A2AF */  sw         $v0, 0x50($sp)
    /* 31D59DC 8006E440 D4FE0224 */  addiu      $v0, $zero, -0x12C
    /* 31D59E0 8006E444 5800A2AF */  sw         $v0, 0x58($sp)
    /* 31D59E4 8006E448 38FF0224 */  addiu      $v0, $zero, -0xC8
    /* 31D59E8 8006E44C 5C00A0AF */  sw         $zero, 0x5C($sp)
    /* 31D59EC 8006E450 6000A2AF */  sw         $v0, 0x60($sp)
    /* 31D59F0 8006E454 80100300 */  sll        $v0, $v1, 2
    /* 31D59F4 8006E458 21104300 */  addu       $v0, $v0, $v1
    /* 31D59F8 8006E45C 83120200 */  sra        $v0, $v0, 10
    /* 31D59FC 8006E460 696E000C */  jal        func_8001B9A4
    /* 31D5A00 8006E464 4C00A2AF */   sw        $v0, 0x4C($sp)
    /* 31D5A04 8006E468 21200000 */  addu       $a0, $zero, $zero
    /* 31D5A08 8006E46C 63E2000C */  jal        func_8003898C
    /* 31D5A0C 8006E470 50000524 */   addiu     $a1, $zero, 0x50
    /* 31D5A10 8006E474 21200000 */  addu       $a0, $zero, $zero
    /* 31D5A14 8006E478 5800A38F */  lw         $v1, 0x58($sp)
    /* 31D5A18 8006E47C 50000524 */  addiu      $a1, $zero, 0x50
    /* 31D5A1C 8006E480 21186200 */  addu       $v1, $v1, $v0
    /* 31D5A20 8006E484 63E2000C */  jal        func_8003898C
    /* 31D5A24 8006E488 5800A3AF */   sw        $v1, 0x58($sp)
    /* 31D5A28 8006E48C 21200000 */  addu       $a0, $zero, $zero
    /* 31D5A2C 8006E490 5C00A38F */  lw         $v1, 0x5C($sp)
    /* 31D5A30 8006E494 50000524 */  addiu      $a1, $zero, 0x50
    /* 31D5A34 8006E498 21186200 */  addu       $v1, $v1, $v0
    /* 31D5A38 8006E49C 63E2000C */  jal        func_8003898C
    /* 31D5A3C 8006E4A0 5C00A3AF */   sw        $v1, 0x5C($sp)
    /* 31D5A40 8006E4A4 21200002 */  addu       $a0, $s0, $zero
    /* 31D5A44 8006E4A8 21280002 */  addu       $a1, $s0, $zero
    /* 31D5A48 8006E4AC 6000A38F */  lw         $v1, 0x60($sp)
    /* 31D5A4C 8006E4B0 F2FF4626 */  addiu      $a2, $s2, -0xE
    /* 31D5A50 8006E4B4 21186200 */  addu       $v1, $v1, $v0
    /* 31D5A54 8006E4B8 736F000C */  jal        func_8001BDCC
    /* 31D5A58 8006E4BC 6000A3AF */   sw        $v1, 0x60($sp)
    /* 31D5A5C 8006E4C0 01000424 */  addiu      $a0, $zero, 0x1
    /* 31D5A60 8006E4C4 0D000524 */  addiu      $a1, $zero, 0xD
    /* 31D5A64 8006E4C8 21300002 */  addu       $a2, $s0, $zero
    /* 31D5A68 8006E4CC 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 31D5A6C 8006E4D0 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 31D5A70 8006E4D4 00000000 */  nop
    /* 31D5A74 8006E4D8 09F84000 */  jalr       $v0
    /* 31D5A78 8006E4DC 4800A727 */   addiu     $a3, $sp, 0x48
    /* 31D5A7C 8006E4E0 08000324 */  addiu      $v1, $zero, 0x8
    /* 31D5A80 8006E4E4 020043A0 */  sb         $v1, 0x2($v0)
    /* 31D5A84 8006E4E8 20000324 */  addiu      $v1, $zero, 0x20
    /* 31D5A88 8006E4EC 0A0043A0 */  sb         $v1, 0xA($v0)
  .Llevel_44_8006E4F0:
    /* 31D5A8C 8006E4F0 01003126 */  addiu      $s1, $s1, 0x1
    /* 31D5A90 8006E4F4 0200222A */  slti       $v0, $s1, 0x2
    /* 31D5A94 8006E4F8 E4004010 */  beqz       $v0, .Llevel_44_8006E88C
    /* 31D5A98 8006E4FC 00000000 */   nop
    /* 31D5A9C 8006E500 F4B80108 */  j          .Llevel_44_8006E3D0
    /* 31D5AA0 8006E504 00000000 */   nop
  .Llevel_44_8006E508:
    /* 31D5AA4 8006E508 0780103C */  lui        $s0, %hi(D_8006A0B0)
    /* 31D5AA8 8006E50C B0A01026 */  addiu      $s0, $s0, %lo(D_8006A0B0)
    /* 31D5AAC 8006E510 0000028E */  lw         $v0, 0x0($s0)
    /* 31D5AB0 8006E514 00000000 */  nop
    /* 31D5AB4 8006E518 1F004010 */  beqz       $v0, .Llevel_44_8006E598
    /* 31D5AB8 8006E51C 4800B127 */   addiu     $s1, $sp, 0x48
    /* 31D5ABC 8006E520 686F000C */  jal        func_8001BDA0
    /* 31D5AC0 8006E524 21202002 */   addu      $a0, $s1, $zero
    /* 31D5AC4 8006E528 21202002 */  addu       $a0, $s1, $zero
    /* 31D5AC8 8006E52C 21282002 */  addu       $a1, $s1, $zero
    /* 31D5ACC 8006E530 D4FF1226 */  addiu      $s2, $s0, -0x2C
    /* 31D5AD0 8006E534 806F000C */  jal        func_8001BE00
    /* 31D5AD4 8006E538 21304002 */   addu      $a2, $s2, $zero
    /* 31D5AD8 8006E53C 5000A0AF */  sw         $zero, 0x50($sp)
    /* 31D5ADC 8006E540 21202002 */  addu       $a0, $s1, $zero
    /* 31D5AE0 8006E544 886E000C */  jal        func_8001BA20
    /* 31D5AE4 8006E548 21280000 */   addu      $a1, $zero, $zero
    /* 31D5AE8 8006E54C 21284000 */  addu       $a1, $v0, $zero
    /* 31D5AEC 8006E550 4100A228 */  slti       $v0, $a1, 0x41
    /* 31D5AF0 8006E554 05004014 */  bnez       $v0, .Llevel_44_8006E56C
    /* 31D5AF4 8006E558 40FF0224 */   addiu     $v0, $zero, -0xC0
    /* 31D5AF8 8006E55C 21202002 */  addu       $a0, $s1, $zero
    /* 31D5AFC 8006E560 316F000C */  jal        func_8001BCC4
    /* 31D5B00 8006E564 40000624 */   addiu     $a2, $zero, 0x40
    /* 31D5B04 8006E568 40FF0224 */  addiu      $v0, $zero, -0xC0
  .Llevel_44_8006E56C:
    /* 31D5B08 8006E56C 5000A2AF */  sw         $v0, 0x50($sp)
    /* 31D5B0C 8006E570 C8FF1026 */  addiu      $s0, $s0, -0x38
    /* 31D5B10 8006E574 21200002 */  addu       $a0, $s0, $zero
    /* 31D5B14 8006E578 21284002 */  addu       $a1, $s2, $zero
    /* 31D5B18 8006E57C 736F000C */  jal        func_8001BDCC
    /* 31D5B1C 8006E580 21302002 */   addu      $a2, $s1, $zero
    /* 31D5B20 8006E584 21204002 */  addu       $a0, $s2, $zero
    /* 31D5B24 8006E588 6C6F000C */  jal        func_8001BDB0
    /* 31D5B28 8006E58C 21280002 */   addu      $a1, $s0, $zero
    /* 31D5B2C 8006E590 6AB90108 */  j          .Llevel_44_8006E5A8
    /* 31D5B30 8006E594 00000000 */   nop
  .Llevel_44_8006E598:
    /* 31D5B34 8006E598 686F000C */  jal        func_8001BDA0
    /* 31D5B38 8006E59C C8FF0426 */   addiu     $a0, $s0, -0x38
    /* 31D5B3C 8006E5A0 686F000C */  jal        func_8001BDA0
    /* 31D5B40 8006E5A4 D4FF0426 */   addiu     $a0, $s0, -0x2C
  .Llevel_44_8006E5A8:
    /* 31D5B44 8006E5A8 0780053C */  lui        $a1, %hi(D_8006A08C)
    /* 31D5B48 8006E5AC 8CA0A524 */  addiu      $a1, $a1, %lo(D_8006A08C)
    /* 31D5B4C 8006E5B0 0000A28C */  lw         $v0, 0x0($a1)
    /* 31D5B50 8006E5B4 00000000 */  nop
    /* 31D5B54 8006E5B8 00DD4228 */  slti       $v0, $v0, -0x2300
    /* 31D5B58 8006E5BC 02004010 */  beqz       $v0, .Llevel_44_8006E5C8
    /* 31D5B5C 8006E5C0 00DD0224 */   addiu     $v0, $zero, -0x2300
    /* 31D5B60 8006E5C4 0000A2AC */  sw         $v0, 0x0($a1)
  .Llevel_44_8006E5C8:
    /* 31D5B64 8006E5C8 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 31D5B68 8006E5CC 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 31D5B6C 8006E5D0 3A000224 */  addiu      $v0, $zero, 0x3A
    /* 31D5B70 8006E5D4 AD006214 */  bne        $v1, $v0, .Llevel_44_8006E88C
    /* 31D5B74 8006E5D8 00000000 */   nop
    /* 31D5B78 8006E5DC 0680023C */  lui        $v0, %hi(D_800670FC)
    /* 31D5B7C 8006E5E0 FC70428C */  lw         $v0, %lo(D_800670FC)($v0)
    /* 31D5B80 8006E5E4 00000000 */  nop
    /* 31D5B84 8006E5E8 A8004010 */  beqz       $v0, .Llevel_44_8006E88C
    /* 31D5B88 8006E5EC 00000000 */   nop
    /* 31D5B8C 8006E5F0 0680023C */  lui        $v0, %hi(D_80067008)
    /* 31D5B90 8006E5F4 0870428C */  lw         $v0, %lo(D_80067008)($v0)
    /* 31D5B94 8006E5F8 00000000 */  nop
    /* 31D5B98 8006E5FC 01004230 */  andi       $v0, $v0, 0x1
    /* 31D5B9C 8006E600 A2004010 */  beqz       $v0, .Llevel_44_8006E88C
    /* 31D5BA0 8006E604 7800B027 */   addiu     $s0, $sp, 0x78
    /* 31D5BA4 8006E608 21200002 */  addu       $a0, $s0, $zero
    /* 31D5BA8 8006E60C 64FFA524 */  addiu      $a1, $a1, -0x9C
    /* 31D5BAC 8006E610 0E000224 */  addiu      $v0, $zero, 0xE
    /* 31D5BB0 8006E614 6800A0AF */  sw         $zero, 0x68($sp)
    /* 31D5BB4 8006E618 6C00A0AF */  sw         $zero, 0x6C($sp)
    /* 31D5BB8 8006E61C 6C6F000C */  jal        func_8001BDB0
    /* 31D5BBC 8006E620 7000A2AF */   sw        $v0, 0x70($sp)
    /* 31D5BC0 8006E624 21200000 */  addu       $a0, $zero, $zero
    /* 31D5BC4 8006E628 63E2000C */  jal        func_8003898C
    /* 31D5BC8 8006E62C 2C010524 */   addiu     $a1, $zero, 0x12C
    /* 31D5BCC 8006E630 21200000 */  addu       $a0, $zero, $zero
    /* 31D5BD0 8006E634 7800A38F */  lw         $v1, 0x78($sp)
    /* 31D5BD4 8006E638 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 31D5BD8 8006E63C 21186200 */  addu       $v1, $v1, $v0
    /* 31D5BDC 8006E640 63E2000C */  jal        func_8003898C
    /* 31D5BE0 8006E644 7800A3AF */   sw        $v1, 0x78($sp)
    /* 31D5BE4 8006E648 21200000 */  addu       $a0, $zero, $zero
    /* 31D5BE8 8006E64C 7C00A38F */  lw         $v1, 0x7C($sp)
    /* 31D5BEC 8006E650 2C010524 */  addiu      $a1, $zero, 0x12C
    /* 31D5BF0 8006E654 21186200 */  addu       $v1, $v1, $v0
    /* 31D5BF4 8006E658 63E2000C */  jal        func_8003898C
    /* 31D5BF8 8006E65C 7C00A3AF */   sw        $v1, 0x7C($sp)
    /* 31D5BFC 8006E660 01000424 */  addiu      $a0, $zero, 0x1
    /* 31D5C00 8006E664 0D000524 */  addiu      $a1, $zero, 0xD
    /* 31D5C04 8006E668 21300002 */  addu       $a2, $s0, $zero
    /* 31D5C08 8006E66C 6800A727 */  addiu      $a3, $sp, 0x68
    /* 31D5C0C 8006E670 8000A38F */  lw         $v1, 0x80($sp)
    /* 31D5C10 8006E674 0680083C */  lui        $t0, %hi(D_800670FC)
    /* 31D5C14 8006E678 FC70088D */  lw         $t0, %lo(D_800670FC)($t0)
    /* 31D5C18 8006E67C 21186200 */  addu       $v1, $v1, $v0
    /* 31D5C1C 8006E680 09F80001 */  jalr       $t0
    /* 31D5C20 8006E684 8000A3AF */   sw        $v1, 0x80($sp)
    /* 31D5C24 8006E688 06000324 */  addiu      $v1, $zero, 0x6
    /* 31D5C28 8006E68C 020043A0 */  sb         $v1, 0x2($v0)
    /* 31D5C2C 8006E690 20000324 */  addiu      $v1, $zero, 0x20
    /* 31D5C30 8006E694 23BA0108 */  j          .Llevel_44_8006E88C
    /* 31D5C34 8006E698 0A0043A0 */   sb        $v1, 0xA($v0)
  .Llevel_44_8006E69C:
    /* 31D5C38 8006E69C 6800A427 */  addiu      $a0, $sp, 0x68
    /* 31D5C3C 8006E6A0 39AD000C */  jal        func_8002B4E4
    /* 31D5C40 8006E6A4 01000524 */   addiu     $a1, $zero, 0x1
    /* 31D5C44 8006E6A8 6800A38F */  lw         $v1, 0x68($sp)
    /* 31D5C48 8006E6AC 00000000 */  nop
    /* 31D5C4C 8006E6B0 C0100300 */  sll        $v0, $v1, 3
    /* 31D5C50 8006E6B4 21104300 */  addu       $v0, $v0, $v1
    /* 31D5C54 8006E6B8 80100200 */  sll        $v0, $v0, 2
    /* 31D5C58 8006E6BC 23104300 */  subu       $v0, $v0, $v1
    /* 31D5C5C 8006E6C0 C3210200 */  sra        $a0, $v0, 7
    /* 31D5C60 8006E6C4 05008014 */  bnez       $a0, .Llevel_44_8006E6DC
    /* 31D5C64 8006E6C8 00000000 */   nop
    /* 31D5C68 8006E6CC 0780013C */  lui        $at, %hi(D_8006A0A0)
    /* 31D5C6C 8006E6D0 A0A020AC */  sw         $zero, %lo(D_8006A0A0)($at)
    /* 31D5C70 8006E6D4 C8B90108 */  j          .Llevel_44_8006E720
    /* 31D5C74 8006E6D8 00000000 */   nop
  .Llevel_44_8006E6DC:
    /* 31D5C78 8006E6DC 09008104 */  bgez       $a0, .Llevel_44_8006E704
    /* 31D5C7C 8006E6E0 00000000 */   nop
    /* 31D5C80 8006E6E4 0780033C */  lui        $v1, %hi(D_8006A0A0)
    /* 31D5C84 8006E6E8 A0A06324 */  addiu      $v1, $v1, %lo(D_8006A0A0)
    /* 31D5C88 8006E6EC 0000628C */  lw         $v0, 0x0($v1)
    /* 31D5C8C 8006E6F0 00000000 */  nop
    /* 31D5C90 8006E6F4 0A004018 */  blez       $v0, .Llevel_44_8006E720
    /* 31D5C94 8006E6F8 00000000 */   nop
    /* 31D5C98 8006E6FC C8B90108 */  j          .Llevel_44_8006E720
    /* 31D5C9C 8006E700 000060AC */   sw        $zero, 0x0($v1)
  .Llevel_44_8006E704:
    /* 31D5CA0 8006E704 0780033C */  lui        $v1, %hi(D_8006A0A0)
    /* 31D5CA4 8006E708 A0A06324 */  addiu      $v1, $v1, %lo(D_8006A0A0)
    /* 31D5CA8 8006E70C 0000628C */  lw         $v0, 0x0($v1)
    /* 31D5CAC 8006E710 00000000 */  nop
    /* 31D5CB0 8006E714 02004104 */  bgez       $v0, .Llevel_44_8006E720
    /* 31D5CB4 8006E718 00000000 */   nop
    /* 31D5CB8 8006E71C 000060AC */  sw         $zero, 0x0($v1)
  .Llevel_44_8006E720:
    /* 31D5CBC 8006E720 0780053C */  lui        $a1, %hi(D_8006A0A0)
    /* 31D5CC0 8006E724 A0A0A524 */  addiu      $a1, $a1, %lo(D_8006A0A0)
    /* 31D5CC4 8006E728 0000A38C */  lw         $v1, 0x0($a1)
    /* 31D5CC8 8006E72C 00000000 */  nop
    /* 31D5CCC 8006E730 2A106400 */  slt        $v0, $v1, $a0
    /* 31D5CD0 8006E734 04004010 */  beqz       $v0, .Llevel_44_8006E748
    /* 31D5CD4 8006E738 08006224 */   addiu     $v0, $v1, 0x8
    /* 31D5CD8 8006E73C 0000A2AC */  sw         $v0, 0x0($a1)
    /* 31D5CDC 8006E740 D5B90108 */  j          .Llevel_44_8006E754
    /* 31D5CE0 8006E744 2A108200 */   slt       $v0, $a0, $v0
  .Llevel_44_8006E748:
    /* 31D5CE4 8006E748 F8FF6224 */  addiu      $v0, $v1, -0x8
    /* 31D5CE8 8006E74C 0000A2AC */  sw         $v0, 0x0($a1)
    /* 31D5CEC 8006E750 2A104400 */  slt        $v0, $v0, $a0
  .Llevel_44_8006E754:
    /* 31D5CF0 8006E754 02004010 */  beqz       $v0, .Llevel_44_8006E760
    /* 31D5CF4 8006E758 00000000 */   nop
    /* 31D5CF8 8006E75C 0000A4AC */  sw         $a0, 0x0($a1)
  .Llevel_44_8006E760:
    /* 31D5CFC 8006E760 0780043C */  lui        $a0, %hi(D_8006A0A0)
    /* 31D5D00 8006E764 A0A0848C */  lw         $a0, %lo(D_8006A0A0)($a0)
    /* 31D5D04 8006E768 68AE000C */  jal        func_8002B9A0
    /* 31D5D08 8006E76C 00000000 */   nop
    /* 31D5D0C 8006E770 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 31D5D10 8006E774 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
    /* 31D5D14 8006E778 00000000 */  nop
    /* 31D5D18 8006E77C 01086228 */  slti       $v0, $v1, 0x801
    /* 31D5D1C 8006E780 05004014 */  bnez       $v0, .Llevel_44_8006E798
    /* 31D5D20 8006E784 00F06224 */   addiu     $v0, $v1, -0x1000
    /* 31D5D24 8006E788 0780013C */  lui        $at, %hi(D_8006A058)
    /* 31D5D28 8006E78C 58A022AC */  sw         $v0, %lo(D_8006A058)($at)
    /* 31D5D2C 8006E790 0780033C */  lui        $v1, %hi(D_8006A058)
    /* 31D5D30 8006E794 58A0638C */  lw         $v1, %lo(D_8006A058)($v1)
  .Llevel_44_8006E798:
    /* 31D5D34 8006E798 00000000 */  nop
    /* 31D5D38 8006E79C 07006104 */  bgez       $v1, .Llevel_44_8006E7BC
    /* 31D5D3C 8006E7A0 00000000 */   nop
    /* 31D5D40 8006E7A4 0680043C */  lui        $a0, %hi(D_8006019C)
    /* 31D5D44 8006E7A8 9C01848C */  lw         $a0, %lo(D_8006019C)($a0)
    /* 31D5D48 8006E7AC 0680023C */  lui        $v0, %hi(D_80060198)
    /* 31D5D4C 8006E7B0 9801428C */  lw         $v0, %lo(D_80060198)($v0)
    /* 31D5D50 8006E7B4 F7B90108 */  j          .Llevel_44_8006E7DC
    /* 31D5D54 8006E7B8 23108200 */   subu      $v0, $a0, $v0
  .Llevel_44_8006E7BC:
    /* 31D5D58 8006E7BC 15006018 */  blez       $v1, .Llevel_44_8006E814
    /* 31D5D5C 8006E7C0 40020424 */   addiu     $a0, $zero, 0x240
    /* 31D5D60 8006E7C4 0680023C */  lui        $v0, %hi(D_800601A0)
    /* 31D5D64 8006E7C8 A001428C */  lw         $v0, %lo(D_800601A0)($v0)
    /* 31D5D68 8006E7CC 0680043C */  lui        $a0, %hi(D_8006019C)
    /* 31D5D6C 8006E7D0 9C01848C */  lw         $a0, %lo(D_8006019C)($a0)
    /* 31D5D70 8006E7D4 00000000 */  nop
    /* 31D5D74 8006E7D8 23104400 */  subu       $v0, $v0, $a0
  .Llevel_44_8006E7DC:
    /* 31D5D78 8006E7DC 18006200 */  mult       $v1, $v0
    /* 31D5D7C 8006E7E0 12100000 */  mflo       $v0
    /* 31D5D80 8006E7E4 8B2E033C */  lui        $v1, (0x2E8BA2E9 >> 16)
    /* 31D5D84 8006E7E8 E9A26334 */  ori        $v1, $v1, (0x2E8BA2E9 & 0xFFFF)
    /* 31D5D88 8006E7EC 18004300 */  mult       $v0, $v1
    /* 31D5D8C 8006E7F0 C3170200 */  sra        $v0, $v0, 31
    /* 31D5D90 8006E7F4 10480000 */  mfhi       $t1
    /* 31D5D94 8006E7F8 83190900 */  sra        $v1, $t1, 6
    /* 31D5D98 8006E7FC 23186200 */  subu       $v1, $v1, $v0
    /* 31D5D9C 8006E800 21208300 */  addu       $a0, $a0, $v1
    /* 31D5DA0 8006E804 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 31D5DA4 8006E808 A4A024AC */  sw         $a0, %lo(D_8006A0A4)($at)
    /* 31D5DA8 8006E80C 09BA0108 */  j          .Llevel_44_8006E824
    /* 31D5DAC 8006E810 40020424 */   addiu     $a0, $zero, 0x240
  .Llevel_44_8006E814:
    /* 31D5DB0 8006E814 0680023C */  lui        $v0, %hi(D_8006019C)
    /* 31D5DB4 8006E818 9C01428C */  lw         $v0, %lo(D_8006019C)($v0)
    /* 31D5DB8 8006E81C 0780013C */  lui        $at, %hi(D_8006A0A4)
    /* 31D5DBC 8006E820 A4A022AC */  sw         $v0, %lo(D_8006A0A4)($at)
  .Llevel_44_8006E824:
    /* 31D5DC0 8006E824 5CAF000C */  jal        func_8002BD70
    /* 31D5DC4 8006E828 80010524 */   addiu     $a1, $zero, 0x180
    /* 31D5DC8 8006E82C 6FAF000C */  jal        func_8002BDBC
    /* 31D5DCC 8006E830 00000000 */   nop
    /* 31D5DD0 8006E834 0780063C */  lui        $a2, %hi(D_8006A0F4)
    /* 31D5DD4 8006E838 F4A0C624 */  addiu      $a2, $a2, %lo(D_8006A0F4)
    /* 31D5DD8 8006E83C 0000C290 */  lbu        $v0, 0x0($a2)
    /* 31D5DDC 8006E840 00000000 */  nop
    /* 31D5DE0 8006E844 06004014 */  bnez       $v0, .Llevel_44_8006E860
    /* 31D5DE4 8006E848 00000000 */   nop
    /* 31D5DE8 8006E84C 0780023C */  lui        $v0, %hi(D_8006A0B0)
    /* 31D5DEC 8006E850 B0A0428C */  lw         $v0, %lo(D_8006A0B0)($v0)
    /* 31D5DF0 8006E854 00000000 */  nop
    /* 31D5DF4 8006E858 09004010 */  beqz       $v0, .Llevel_44_8006E880
    /* 31D5DF8 8006E85C 90FFC424 */   addiu     $a0, $a2, -0x70
  .Llevel_44_8006E860:
    /* 31D5DFC 8006E860 0780023C */  lui        $v0, %hi(D_8006A098)
    /* 31D5E00 8006E864 98A0428C */  lw         $v0, %lo(D_8006A098)($v0)
    /* 31D5E04 8006E868 00000000 */  nop
    /* 31D5E08 8006E86C 40FF4224 */  addiu      $v0, $v0, -0xC0
    /* 31D5E0C 8006E870 0780013C */  lui        $at, %hi(D_8006A08C)
    /* 31D5E10 8006E874 8CA022AC */  sw         $v0, %lo(D_8006A08C)($at)
    /* 31D5E14 8006E878 23BA0108 */  j          .Llevel_44_8006E88C
    /* 31D5E18 8006E87C 00000000 */   nop
  .Llevel_44_8006E880:
    /* 31D5E1C 8006E880 84FFC524 */  addiu      $a1, $a2, -0x7C
    /* 31D5E20 8006E884 736F000C */  jal        func_8001BDCC
    /* 31D5E24 8006E888 ECFFC624 */   addiu     $a2, $a2, -0x14
  .Llevel_44_8006E88C:
    /* 31D5E28 8006E88C 9800BF8F */  lw         $ra, 0x98($sp)
    /* 31D5E2C 8006E890 9400B38F */  lw         $s3, 0x94($sp)
    /* 31D5E30 8006E894 9000B28F */  lw         $s2, 0x90($sp)
    /* 31D5E34 8006E898 8C00B18F */  lw         $s1, 0x8C($sp)
    /* 31D5E38 8006E89C 8800B08F */  lw         $s0, 0x88($sp)
    /* 31D5E3C 8006E8A0 A000BD27 */  addiu      $sp, $sp, 0xA0
    /* 31D5E40 8006E8A4 0800E003 */  jr         $ra
    /* 31D5E44 8006E8A8 00000000 */   nop
endlabel func_level_44_8006DC48
