.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_level_44_8006D3C8

dlabel jtbl_level_44_8006D3C8
    /* 31D4964 8006D3C8 78EC0680 */ .word .Llevel_44_8006EC78
    /* 31D4968 8006D3CC 98EC0680 */ .word .Llevel_44_8006EC98
    /* 31D496C 8006D3D0 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D4970 8006D3D4 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D4974 8006D3D8 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D4978 8006D3DC A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D497C 8006D3E0 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D4980 8006D3E4 80EC0680 */ .word .Llevel_44_8006EC80
    /* 31D4984 8006D3E8 98EC0680 */ .word .Llevel_44_8006EC98
    /* 31D4988 8006D3EC A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D498C 8006D3F0 78EC0680 */ .word .Llevel_44_8006EC78
    /* 31D4990 8006D3F4 98EC0680 */ .word .Llevel_44_8006EC98
    /* 31D4994 8006D3F8 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D4998 8006D3FC A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D499C 8006D400 98EC0680 */ .word .Llevel_44_8006EC98
    /* 31D49A0 8006D404 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49A4 8006D408 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49A8 8006D40C A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49AC 8006D410 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49B0 8006D414 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49B4 8006D418 98EC0680 */ .word .Llevel_44_8006EC98
    /* 31D49B8 8006D41C A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49BC 8006D420 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49C0 8006D424 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49C4 8006D428 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49C8 8006D42C A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49CC 8006D430 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49D0 8006D434 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49D4 8006D438 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49D8 8006D43C A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49DC 8006D440 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49E0 8006D444 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49E4 8006D448 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49E8 8006D44C A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49EC 8006D450 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49F0 8006D454 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49F4 8006D458 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49F8 8006D45C A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D49FC 8006D460 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D4A00 8006D464 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D4A04 8006D468 98EC0680 */ .word .Llevel_44_8006EC98
    /* 31D4A08 8006D46C A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D4A0C 8006D470 A8EC0680 */ .word .Llevel_44_8006ECA8
    /* 31D4A10 8006D474 98EC0680 */ .word .Llevel_44_8006EC98
enddlabel jtbl_level_44_8006D3C8


.section .text
/* Generated by spimdisasm 1.40.2 */

nonmatching func_level_44_8006EC28, 0x90

glabel func_level_44_8006EC28
    /* 31D61C4 8006EC28 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 31D61C8 8006EC2C 00210400 */  sll        $a0, $a0, 4
    /* 31D61CC 8006EC30 0780023C */  lui        $v0, %hi(D_800683B0)
    /* 31D61D0 8006EC34 B0834224 */  addiu      $v0, $v0, %lo(D_800683B0)
    /* 31D61D4 8006EC38 0780033C */  lui        $v1, %hi(D_8006A040)
    /* 31D61D8 8006EC3C 40A0638C */  lw         $v1, %lo(D_8006A040)($v1)
    /* 31D61DC 8006EC40 21208200 */  addu       $a0, $a0, $v0
    /* 31D61E0 8006EC44 1000BFAF */  sw         $ra, 0x10($sp)
    /* 31D61E4 8006EC48 0680013C */  lui        $at, %hi(D_80066F38)
    /* 31D61E8 8006EC4C 386F24AC */  sw         $a0, %lo(D_80066F38)($at)
    /* 31D61EC 8006EC50 EEFF6324 */  addiu      $v1, $v1, -0x12
    /* 31D61F0 8006EC54 2C00622C */  sltiu      $v0, $v1, 0x2C
    /* 31D61F4 8006EC58 13004010 */  beqz       $v0, .Llevel_44_8006ECA8
    /* 31D61F8 8006EC5C 80100300 */   sll       $v0, $v1, 2
    /* 31D61FC 8006EC60 0780013C */  lui        $at, %hi(jtbl_level_44_8006D3C8)
    /* 31D6200 8006EC64 21082200 */  addu       $at, $at, $v0
    /* 31D6204 8006EC68 C8D3228C */  lw         $v0, %lo(jtbl_level_44_8006D3C8)($at)
    /* 31D6208 8006EC6C 00000000 */  nop
    /* 31D620C 8006EC70 08004000 */  jr         $v0
    /* 31D6210 8006EC74 00000000 */   nop
  .Llevel_44_8006EC78:
    /* 31D6214 8006EC78 28BB0108 */  j          .Llevel_44_8006ECA0
    /* 31D6218 8006EC7C 21200000 */   addu      $a0, $zero, $zero
  .Llevel_44_8006EC80:
    /* 31D621C 8006EC80 0780043C */  lui        $a0, %hi(D_8006A084)
    /* 31D6220 8006EC84 84A08424 */  addiu      $a0, $a0, %lo(D_8006A084)
    /* 31D6224 8006EC88 B4B7000C */  jal        func_8002DED0
    /* 31D6228 8006EC8C 00000000 */   nop
    /* 31D622C 8006EC90 2ABB0108 */  j          .Llevel_44_8006ECA8
    /* 31D6230 8006EC94 00000000 */   nop
  .Llevel_44_8006EC98:
    /* 31D6234 8006EC98 0780043C */  lui        $a0, %hi(D_8006A0C4)
    /* 31D6238 8006EC9C C4A08424 */  addiu      $a0, $a0, %lo(D_8006A0C4)
  .Llevel_44_8006ECA0:
    /* 31D623C 8006ECA0 E3B6000C */  jal        func_8002DB8C
    /* 31D6240 8006ECA4 00000000 */   nop
  .Llevel_44_8006ECA8:
    /* 31D6244 8006ECA8 1000BF8F */  lw         $ra, 0x10($sp)
    /* 31D6248 8006ECAC 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 31D624C 8006ECB0 0800E003 */  jr         $ra
    /* 31D6250 8006ECB4 00000000 */   nop
endlabel func_level_44_8006EC28
